### ISSUE TITLE
Help with version of R used by Nvim-R

### ISSUE THREAD

**Issue by isthisthat** [jalvesaq/Nvim-R#10]
Hello and thank you for this brilliant plugin!
For the life of me, I can't get it load the right version of R. The first R executable in my PATH is the one I want, but the plugin keeps running a version under /usr/lib64/R (which doesn't have the right libraries installed). I've set `let R_path = "/path/to/preferred/R/R-3.1.2/bin"` in my `.nvimrc`, but that doesn't seem to change anything.
Thank you for your help.

**Comment by isthisthat** [comment]
May be worth mentioning that I have this on top of my `.nvimrc`:

    set runtimepath=~/tmp/Nvim-R,~/.vim,$VIMRUNTIME,~/.vim/after

Not if relevant to the issue.

**Comment by isthisthat** [comment]
It seems that the R subshell is started without my `.bash_profile` or `.bashrc` environment loaded and hence it doesn't know about my `PATH` on runtime. When I do `Sys.getenv("PATH")` on the Nvim-R shell, I get just the bare system paths. I wonder how I can tell Nvim-R to start in my current environment?

**Comment by isthisthat** [comment]
setting `.profile` didn't work either...

**Comment by jalvesaq** [comment]
It seems that you have this problem: https://github.com/jcfaria/Vim-R-plugin/issues/169

**Comment by isthisthat** [comment]
thank you! That solved the issue.
