### ISSUE TITLE
How to remap the LocalLeader?

### ISSUE THREAD

**Issue by llinfeng** [jalvesaq/Nvim-R#101]
While I have tried the following, the `<localleader>` for the Nvim-R plugin still seems to be `\`. 

1. Put the following in `_vimrc`: 
   ```
   autocmd BufNewFile,BufReadPost *.r let maplocalleader = ";"
   ```

2. Put the following in `c:\vim\vimfiles\ftplugin\r.vim`
   ```
   let maplocalleader = ";"
   let g:maplocalleader = ";"
   ```
How should I change the `<localleader>` correctly? Is there a certain key-value that I can pass to Nvim-R?

Thanks a lot!

All the best, 

-Linfeng

**Comment by jalvesaq** [comment]
It is better to have different keys for `<Leader>` (used by general plugins) and `<LocalLeader>` (used by filetype plugins). I have this in my vimrc:
```
let mapleader = ";"
let maplocalleader = ","
```

**Comment by llinfeng** [comment]
Great, thank you! I wrongly thought that I shall specify the `<localleader>` locally. Thanks for pointing out that `let maplocalleader = ","` should go to the `_vimrc`.
