### ISSUE TITLE
How can I run R after having specified where my profile is

### ISSUE THREAD

**Issue by statquant** [jalvesaq/Nvim-R#102]
I would like vim-R to start vim but after having specified where my profile is.
Typically run something like "R_USER_PROFILE=~/.dotfiles/.Rprofile R"
I do not want to put my profile visible in my /home or it is picked up everytime by Rstudio or any Rscript I run

I tried 
In bashrc
alias vimR = "R_USER_PROFILE=~/.dotfiles/.Rprofile R"
This works on the console

In vimrc
let R_app = "vimR" 
but vim-R "cannot find  the executable"

**Comment by jalvesaq** [comment]
Both Nvim-R and RStudio define environment variables that you can use in your Rprofile, like this:

```r
if(Sys.getenv("NVIMR_TMPDIR") != ""){
    # Configuration for Nvim-R
} else if(Sys.getenv("RSTUDIO") != ""){
    # Configuration for RStudio
}
```

To see the list of defined environment variables in R, do `names(Sys.getenv())`.

**Comment by statquant** [comment]
So you suggest my .Rprofile gets loaded all the time but on some cases like RSTUDIO I just do nothing ?
Looks good !

**Comment by jalvesaq** [comment]
If you prefer to use an alias in your .bashrc, it could be:
```
alias vim = "R_USER_PROFILE=~/.dotfiles/.Rprofile vim"
alias nvim = "R_USER_PROFILE=~/.dotfiles/.Rprofile nvim"
```
Then, when R is started by (Neo)Vim, it will inherit the environment variable (not tested).

**Comment by statquant** [comment]
the aliasing vim did not work (I tested before opening the issue)

**Comment by jalvesaq** [comment]
Thanks for the feedback! Since the first suggestion works, I am closing the issue.
