### ISSUE TITLE
Cheatsheet for Key bindings 

### ISSUE THREAD

**Issue by llinfeng** [jalvesaq/Nvim-R#103]
I've drafted a cheat-sheet for the Key bindings of Nvim-R. Here goes the Dropbox Link. 

https://www.dropbox.com/sh/7d8jty6mqmwyy6k/AACdSV2ueD8NsZHGiwrBDIpWa?dl=0

Yet, I am not sure how to add PDF to Wiki. Thus, I created this issue.

Hope this may help.

All the best, 

-Linfeng

**Comment by jalvesaq** [comment]
Thanks! I noted that you wrote "Eter" instead of "Enter"...

Do you mean Nvim-R wiki on github? Perhaps I have to activate it. If you want to edit pages in the wiki, I may try to activate it.

**Comment by llinfeng** [comment]
Thanks for catching the typo, fixed on the Dropbox folder.

**Comment by protist** [comment]
I'd be interested to see the cheatsheet, but it 404s now.
