### ISSUE TITLE
'R was already started' and cant reopen without relaunching vim (Windows)

### ISSUE THREAD

**Issue by jpmorris** [jalvesaq/Nvim-R#104]
I notice recent changes have been made to the R launch code.  Currently I'm unable to relaunch using \rf after R has been closed (accident or otherwise).  It just says 'R was already started. Now I have to close out vim and relaunch it every time.  I'm on windows (7.4.2251) just updated Nvim-R (on vim-plug).

**Comment by jalvesaq** [comment]
If you do `\rq` after you have closed R directly, the problem should be fixed. Nvim-R will warn that it couldn't close R and, then, clean its information about the no longer running R process.

**Comment by jpmorris** [comment]
Ok, yes if I do \rq it works.  Not sure if it's possible to have a relaunch check for a running session and do cleanup if not, but that would be easier.  But not a big deal, this works now that I know. Thanks!
