### ISSUE TITLE
Request: SendCmdToR and wait

### ISSUE THREAD

**Issue by mllg** [jalvesaq/Nvim-R#105]
Hi there, 

I try to integrate `codetools::checkUsagePackage()` into vim by sending its output to the quickfix window. First, I write the output to a temp file:
```{R}
library(codetools)
writeLines(capture.output(checkUsagePackage("[mypkg]")), "/tmp/rusage")
```
Then parse the results into vim:
```{vim}
set efm+=%m\ (%f:%l%.%#)
cfile /tmp/rusage
```
This already works quite well. However, I cannot automate this, because SendCmdToR does not wait for the command to finish. Thus, if you call cfile, the temp file is not yet created. Is there an easy way around this?

**Comment by jalvesaq** [comment]
Try this:
```vim
set efm+=%m\ (%f:%l%.%#)
" Wait up to two seconds
let ii = 0
while ii < 20
    let ii += 1
    sleep 100m
    if filereadable("/tmp/rusage")
        cfile /tmp/rusage
        call delete("/tmp/rusage")
        break
    endif
endwhile
```

**Comment by mllg** [comment]
Well, this obviously works. I guess having a native "wait" option would still be nice. Nevertheless, thanks!

**Comment by mllg** [comment]
If someone stumbles over this issue: This is now in the vim-devtools-package: https://github.com/mllg/vim-devtools-plugin/commit/0a822b75a53225cc4d9ff9c05a31cdbe3ab11b05
