### ISSUE TITLE
Error opening R console (Bash for Windows)

### ISSUE THREAD

**Issue by galadude** [jalvesaq/Nvim-R#106]
I'm trying to open the R console on Bash for Windows. I get an error that says
`[Terminal emulator] xterm: DISPLAY is not set`

Any idea what's going on?

**Comment by jalvesaq** [comment]
xterm requires the DISPLAY variable to be set on Linux. I don't know about xterm on Windows.

**Comment by jalvesaq** [comment]
This might be relevant to your case: http://x.cygwin.com/docs/ug/using.html

**Comment by galadude** [comment]
I'll have a look thanks. I'm not using cygwin though. [Bash for windows](http://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/) is an ubuntu "subsystem". There's recently been an update, so maybe it'll help.

**Comment by galadude** [comment]
You can kind of get it to work. You need to install xming, and open vim using the command "DISPLAY=:0 vim".

**Comment by jalvesaq** [comment]
I am closing the issue since you have found that xming is the way of making the plugin to work on Bash for Windows.
