### ISSUE TITLE
Installation with vim-plug

### ISSUE THREAD

**Issue by DevinBayly** [jalvesaq/Nvim-R#108]
Hi there,

I'm really interested in having the omnifunc completion to enable YCM to let me learn this language at a bit more rapid of a pace. 

Unfortunately I have a problem with the installation. I successfully downloaded the files in this repo using  the vim-plug plugin manager, but I don't think I have any access to the tools in Nvim-R because the \rf and :Rhelp aren't recognized. 

I'm also not getting any error messages to explore.

I'm curious whether having my R managed by miniconda is making this issue appear. However, the docs say that the r_path defaults to the first R executable found in the system path, and my system can certainly find that R (terminal launching of R interpreter is fine).

Any ideas, would be very welcome...

Devin

**Comment by jalvesaq** [comment]
You should see some of the plugin files listed by the command `:scriptnames`.

**Comment by jalvesaq** [comment]
If you do not get any error message it is most probably because the plugin is not successfully installed. If it was correctly installed, you should see many Nvim-R commands listed by `:nmap`, and `:Rhelp` should output the question "Did you already start R?".

**Comment by DevinBayly** [comment]
yea I'm not seeing any of those listings in :scriptnames or under :nmap. :Rhelp gives me a "not an editor command" err. 

I'm not sure what vim-plug didn't do, because there is an actual folder in the plugged directory.

**Comment by jalvesaq** [comment]
The existence of the folder is not enough. You must have in your vimrc between `plug#begin` and `plug#end`:
```
Plug 'jalvesaq/Nvim-R'
```

**Comment by DevinBayly** [comment]
Oh man I feel like I've messed that part up with many other plugins and now I know why! I'll double check on whether this does fix the issues

**Comment by DevinBayly** [comment]
Ok it's going now, but I have a few other issues to take care of, as it seems my vim needs to be updated

**Comment by jalvesaq** [comment]
Since this issue is solved, I am closing it.
