### ISSUE TITLE
R_term_cmd with gnome-terminal

### ISSUE THREAD

**Issue by iagomosqueira** [jalvesaq/Nvim-R#109]
I am on vim 8.0 and the latest Nvim-R. I try to set R_term_cmd to add some options to gnome-terminal, for example:
````
let R_term_cmd = "gnome-terminal --title R --maximize -e"
```

but when I open R from the R file I get this message:
```
[Terminal emulator] Failed to parse arguments: Unkonwn option -L
```
By default gnome-terminal is being used, and it works if I set it with R_term, it only fails when adding arguments in R_term_cmd

**Comment by iagomosqueira** [comment]
OK, that was the command I used to have in R-vim, but it now should be
```
let R_term_cmd = "gnome-terminal --title R --maximize -x"
```

making use of the -x flag and not -e.

**Comment by jalvesaq** [comment]
Thanks for the feedback, and as you certainly can see there, `--title` is no longer supported by gnome-terminal. I am closing the issue.

**Comment by iagomosqueira** [comment]
Thanks. Where is that warning about --title? It still shows up in gnome-terminal's man page

**Comment by jalvesaq** [comment]
My gnome-terminal is 3.18.3, and it does not have `--title` in its man page. The command
```
gnome-terminal --title R
```
gives: Option "--title" is no longer supported in this version of gnome-terminal.

**Comment by iagomosqueira** [comment]
Thanks, time to upgrade then.
