### ISSUE TITLE
How to start R from two different paths

### ISSUE THREAD

**Issue by rcastelo** [jalvesaq/Nvim-R#110]
hi,

i'm interested in starting R from vim with the Nvim-R plugin in two different ways. One starting the release version of R and another starting the development version of R. Both versions are located in two differerent paths of my computer. From the shell I use two aliases to access them:

```
alias R='/opt/R/release/bin/R'
allias Rdevel='/opt/R/devel/bin/R'
```

with the former vim-r-plugin, i hacked the code so that when calling R with options via '\rc' (the "custom start") the trailing space would be removed (let rcmd = b:rplugin_R . b:rplugin_r_args) so that typing 'devel' after '\rc' would start 'Rdevel'. Currently, with the latest version i cannot even start R, it says 'R executable not found'. i've googled around but could not find an answer to this, so i'd appreciate any hint on how to use two different versions of R from vim. i work on a linux box with Vim 8.0.16 and the last release version of Nvim-R.

thanks!!

robert.

**Comment by jalvesaq** [comment]
You may create an alias like this:
```
alias vrdev='PATH=/opt/R/devel/bin/R:$PATH nvim'
```

Or you can set `R_path` in your vimrc according to a condition. Example,  use `release/bin` unless you are in a specific directory:
```
autocmd BufNewFile,BufRead *.* let R_path="/opt/R/release/bin"
autocmd BufNewFile,BufRead /home/yourlogin/devpath/*.* let R_path="/opt/R/devel/bin"
```
Please, see `:h autocmd` for other possibilities.

**Comment by rcastelo** [comment]
hi,

thanks for the hint. i thought there was maybe some specific way of supporting the use of multiple versions of R. i'm not entirely happy with aliasing vim under multiple names and the use of different R versions is not depending on the location of the source files. so in the end i've added symlinks that point to the different R versions ('R' to release and 'Rdevel' to devel), include those symlinks in the PATH variable and replace line 863 of .vim/R/common_global.vim

`let rcmd = g:rplugin_R . " " . args_str`

by

`let rcmd = g:rplugin_R . args_str`

so that '\rf' start release R and '\rc' + devel starts devel R. just in case this may sound useful to anyone.

cheers,

robert.

**Comment by jalvesaq** [comment]
The problem of changing Nvim-R scripts is that you have to maintain them up to date.
Another idea is to create in your vimrc a map to change the value of `rplugin_R`:
```
nmap <LocalLeader>R :let g:rplugin_R = "/opt/R/release/bin/R"<CR>
nmap <LocalLeader>D :let g:rplugin_R = "/opt/R/devel/bin/R"<CR>
```

**Comment by rcastelo** [comment]
hi,
you're absolutely right and what you proposed seems to ma a much better alternative. however, after adding those to lines to the end of my .vimrc, when i open some 'test.R' file and type '\R' i only get at the bottom of the window the following message:

`:let g:rplugin_R = "/opt/R/release/bin/R"                                             0,0-1         All`

but i do not see that R has started anywhere. do you have any idea why this might not be working on my computer?

thanks,

robert.

**Comment by jalvesaq** [comment]
It does not start R. It just sets the value of g:rplugin_R. Then, when you type `\rf`, R will be started from "/opt/R/release/bin/R". It is possible to create shortcuts to directly start R, but it would be a bit more complicated.

**Comment by rcastelo** [comment]
ah! neat! that's good enough for me, thanks for the clarification!!  and thanks for the plugin, it's "life changing" ;)

**Comment by jalvesaq** [comment]
If you still prefer to make `<LocalLeader>D` and `<LocalLeader>R` starting R directly, put in your vimrc:

```
function StartReleaseR()
    let g:rplugin_R = "/opt/R/release/bin/R"
    call StartR("R")
endfunction

function StartDevelR()
    let g:rplugin_R = "/opt/R/devel/bin/R"
    call StartR("R")
endfunction

nmap <LocalLeader>R :call StartReleaseR()<CR>
nmap <LocalLeader>D :call StartDevelR()<CR>
```

**Comment by rcastelo** [comment]
Excellent!! That's just what I was looking for, thanks!!!

**Comment by rcastelo** [comment]
hi again,

one issue i've just encountered when using these functions starting R directly via '\R' and '\D' is that I cannot load the library 'rJava', which depends on my system-wide java installation while I can do it when starting R outside vim. It looks like starting R from vim forgets the whole configuration:

```
library(rJava)
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/opt/R/R-3.3.1/lib64/R/library/rJava/libs/rJava.so':
  libjvm.so: cannot open shared object file: No such file or directory
Error: package or namespace load failed for ‘rJava’
```

I've tried to add in the .Rprofile via Sys.setenv() the whole set of variables set by R CMD javareconf -e but it still does not work, while it does work when starting R outside vim (i.e., from the shell). Any hint?

**Comment by jalvesaq** [comment]
Perhaps there is an environment variable set in your .bashrc that is not being considered by Tmux. Did you try running R in a Neovim buffer? It does not depend on Tmux.

**Comment by rcastelo** [comment]
Not sure what a Neovim buffer is, but you're right that if I start R from vim via '\R' (or '\D') without tmux, then it works! So maybe is a tmux-related problem, but tmux is nice to be able to split the terminal window. Do you have any hint about running vim within tmux and being able to load the 'rJava' library in the corresponding R session?

**Comment by jalvesaq** [comment]
Neovim is a fork of Vim: https://github.com/neovim/neovim
It can run a terminal emulator in a split window (a Vim buffer where you can use Vim commands to copy, paste, highlight text, etc.).
