### ISSUE TITLE
problem with starting R

### ISSUE THREAD

**Issue by etheleon** [jalvesaq/Nvim-R#112]
when i enter <leader>rf I get an error:

`r connecting to /usr/local/bin/tmux (Socket operation on non-socket)^@`
in my vim buffer. 

its the same error message if i try to initiate a tmux within a existing pane.

**Comment by jalvesaq** [comment]
What is your version of Tmux? I can't reproduce the bug with Tmux 2.1.

**Comment by jalvesaq** [comment]
Did you solve the problem?

**Comment by jalvesaq** [comment]
I am closing the issue due to lack of feedback, and because I can't reproduce it.
