### ISSUE TITLE
Problem opening R with rnoweb files (vim-latex)

### ISSUE THREAD

**Issue by cwatson** [jalvesaq/Nvim-R#115]
Hello, I am unable to open R using `\rf` when opening the majority of `Rnw` files (strangely, it works for one of them). There is no message/error when I try, so I am not sure how to diagnose this. I have to manually `set ft=r`, open R, then `set ft=rnoweb`.

System/OS: CentOS 7.2.1511 (64-bit)
Linux 3.10.0-327.36.1.el7.x86_64
Vim version 8.0 (2016 Sep 12)
Tmux version 1.8
R version 3.3.1 (2016-06-21) -- "Bug in Your Hair"

As far as I can tell, everything else works perfectly (thank you for creating this plugin, it is by far my favorite and extraordinarily useful!). Do you know what the problem could be? Please let me know what other information I can provide.

**Comment by jalvesaq** [comment]
Tmux should be >= 2.0, but this has no relation with the bug that you report. I don't remember what is the problem of Tmux < 2.0.

Perhaps you have an old syntax file somewhere, or an autocommand defining `Rnw` as something else. What is the output of
```
:set ft?
```
This will tell us how the Rnw file is being recognized.
And the command below will show what syntax (and other) files were sourced:
```
:scriptnames
```

**Comment by cwatson** [comment]
For the first command, with both files (the one that works and the one that doesn't), it returns `rnoweb`.
For the second command, there are ~140 lines, mostly the same for both files (with the only differences, at a glance, being a few LaTeX packages). The vim plugins that are "active" include: `vim-latex`, `vim-airline`, `vim-gitgutter`, `vim-snipmate`.
The `nvimcom` version is 0.9.23

**Comment by jalvesaq** [comment]
Both Rnoweb files should load the same plugins. Perhaps `\rf` is mapped to different actions in each file. You can check this with:
```
:nmap \rf
```
Filetype plugins have to use `<LocalLeader>` in their shortcuts. Since Rnoweb activates at the same time R and LaTeX filetype plugins, shortcuts from Nvim-R and LaTeX plugins might be the same.

**Comment by cwatson** [comment]
Ah, for the file that doesn't work:
`n  \rf          @<Plug>Tex_RefreshFolds`

And for the one that does work:
`no \rf         *@:call StartR("R")<CR>`

Should I add that to my `.vimrc` as a quick fix? Or is there a way I can figure out why only 1 or 2 of my `.Rnw` files is being detected properly?

**Comment by jalvesaq** [comment]
Vim-latex from https://github.com/vim-latex/vim-latex does not have the strings `rnw` or `rnoweb`. I installed with vim-plug and did:
```
cd ~/.config/nvim/plugged/vim-latex
grep -R -i -w 'rnw\|rnoweb'
```

That is, probably you have defined that Rnoweb files should be treated as LaTeX files. If this is the case, you have to find where you have done this and fix it.

**Comment by jalvesaq** [comment]
Do all of your rnoweb files have the string `\documentclass`? Please, see this: https://sourceforge.net/p/vim-latex/mailman/message/6174966/

**Comment by cwatson** [comment]
I already have `let g:tex_flavor = 'latex'` in my `.vimrc`.

The majority do have `\documentclass` in them (but some are chapters which are included either by  `<<child=foo.Rnw>>` or `\input{foo.tex}`). The one file that works has `\documentclass{report}`, all of the others have `\documentclass{article}` or `\documentclass{beamer}`.

I use Vundle, and the `grep` command within `~/.vim/bundle/vim-latex` didn't return anything.

**Comment by jalvesaq** [comment]
I will put in the Nvim-R documentation that some of vim-latex keybindings clash with Nvim-R ones.

Vim-latex is a filetype plugin and it should use `<LocalLeader>`, but it seems that it uses `<Leader>`. Thus, an easy solution to avoid shortcut clashes would be to define different keys for `<Leader>` and `<LocalLeader>`. For example, I have this in my vimrc:
```
let mapleader = ";"
let maplocalleader = ","
```

**Comment by cwatson** [comment]
Thanks. However I am quite accustomed to using the default '\' as the leader. Do you know how I could change it just for `vim-latex`?

**Comment by jalvesaq** [comment]
You could try this:
```
autocmd BufNewFile,BufReadPre * let g:mapleader = "\\"
autocmd BufNewFile,BufReadPre *.Rnw let g:mapleader = ";"
autocmd BufNewFile,BufReadPre *.tex let g:mapleader = ";"
```

**Comment by cwatson** [comment]
That worked perfectly, thanks.
