### ISSUE TITLE
Separate components of plugin?

### ISSUE THREAD

**Issue by meriops** [jalvesaq/Nvim-R#116]
Would there be a way to use only the completion of R commands without loading / using the whole nvim-r plugin and, in particular, without using the communication (send code etc.) to a neovim split (as I'm already using a generic REPL to a tmux pane for that)?

**Comment by jalvesaq** [comment]
There is no way of disabling parts of the plugin, but you can get omni completion without starting R if the names of function and other objects of libraries were cached at least once. Please, try this and post here whether it works or not:

  - Enable Nvim-R and start R.
  - In R, load all libraries which you want supported by omni completion.
  - Quit both R and (Neo)Vim.
  - Put in your vimrc a line following the example (add all your libraries):
```
let R_start_libs = "base,stats,graphics,grDevices,utils,methods,foreign,memisc,psych,lme4"
```

Now, when editing an R script, start R with the generic REPL plugin. You have to repeat the above procedure once in a while to update the names and arguments of function of R packages.

By the way, what is the generic plugin? Other people might be interested in the same approach and they would want to know how to replicate your setup.

**Comment by meriops** [comment]
Yes, it does work as indicated and provides functions and arguments completion without starting R. 

With neovim and R opened each in its tmux pane, I use [vim-slime](https://github.com/jpalardy/vim-slime) to send code to R, mostly because it is simple and has less "new commands" to memorize than Nvim-R. I might swith to Nvim-R one day though...

**Comment by jalvesaq** [comment]
Thanks for the feedback. I'm closing the issue because we found a workaround for the problem.
