### ISSUE TITLE
E121: Undefined variable: g:rplugin_editor_pane

### ISSUE THREAD

**Issue by enricoferrero** [jalvesaq/Nvim-R#117]
Hello,

I'm using Nvim-R with Vim and Tmux.
I get the following errors in the Vim pane when trying to access the R docs from the R pane (e.g.: ?mean):

```
E121: Undefined variable: g:rplugin_editor_pane
E116: Invalid arguments for function system("tmux select-pane -t " . g:rplugin_editor_pane)
E15: Invalid expression: system("tmux select-pane -t " . g:rplugin_editor_pane)
```

The help file is then correctly displayed in the Vim pane. Also, those errors don't appear if I try to access the R docs directly from Vim (e.g.: ;rh).

I've looked for the `g:rplugin_editor_pane` option in the Nvim-R docs and couldn't find it.

Do you know what this error is about and how I can fix it?
Thanks!

**Comment by jalvesaq** [comment]
Thanks for reporting the bug. I created it 25 days ago: https://github.com/jalvesaq/Nvim-R/commit/6911f3072b647b41f055f36158e5a8a4f009f7ae
