### ISSUE TITLE
Can I map space to REDSendSelection?

### ISSUE THREAD

**Issue by protist** [jalvesaq/Nvim-R#118]
As per the suggestion in help, I mapped `Space` to `RDSendSelection` when in visual mode. However, I'd prefer it mapped to `REDSendSelection` instead (i.e. with the echo). Hence, instead of the recommended
```
vmap <Space> <Plug>RDSendSelection
```
I tried using
```
vmap <Space> <Plug>REDSendSelection
```
instead. However, `Space` didn't seem to do anything after this. Is there a way to map `Space` to `REDSendSelection`?

**Comment by jalvesaq** [comment]
The map works for me in both Vim and Neovim.

If you always prefer `echo=TRUE` when sourcing code, you could put in your vimrc:
```
let R_source_args = "print.eval = TRUE, echo = TRUE"
```

**Comment by protist** [comment]
Oh… erm, sorry. Yes, it works fine now. I was experimenting with changing mappings in a running instance of vim/R, which didn't work at all. Putting it in `vimrc` and restarting instead works fine. Thank you and sorry for the noise.
