### ISSUE TITLE
Binding ESC key breaks R arrow hotkey

### ISSUE THREAD

**Issue by ashiklom** [jalvesaq/Nvim-R#12]
First off, great plugin! I use it religiously!

One minor issue: As part of the "Learn Vimscript the Hard Way" series, I remapped my `<ESC>` key to `<nop>` to train my fingers to the (much better, in my opinion) `jk` for getting out of insert more. However, this change breaks the very useful `Shift -` key for creating R's assignment operator. From looking at your code, this is because the function `ReplaceUnderS()` calls the `<ESC>` key explicitly.

I feel like there's a relatively simple way to fix this. Maybe by using the `normal!` command instead of calling the `<ESC>` key? Or just using `inoremap` in the binding?

Removing my own maps on `<ESC>` fixed the problem, but I think this is worth fixing for people who might have `<ESC>` bound to other things.

**Comment by jalvesaq** [comment]
Could you please try the solution you proposed and either post a diff here or do a pull request?

**Comment by ashiklom** [comment]
Ok, I'll take a stab at it!
