### ISSUE TITLE
nvimcom installation error: unknown type name 'fd_set'

### ISSUE THREAD

**Issue by feinerer** [jalvesaq/Nvim-R#120]
The installation of the nvimcom package fails with the following error:

`* installing to library ‘/home/feinerer/R/x86_64-unknown-openbsd6.0-library/3.3’`
`* installing *source* package ‘nvimcom’ ...`
`** libs`
`egcc -std=gnu99 -I/usr/local/lib/R/include -DNDEBUG  -I/usr/local/include    -fpic  -O2 -pipe  -c nvimcom.c -o nvimcom.o`
`In file included from nvimcom.c:6:0:`
`/usr/local/lib/R/include/R_ext/eventloop.h:73:65: error: unknown type name 'fd_set'`
`extern InputHandler *getSelectedHandler(InputHandler *handlers, fd_set *mask);`

Operating system: OpenBSD 6.0-current
GCC (= egcc): gcc version 4.9.4
R version 3.3.1

`fd_set` is defined in `/usr/include/sys/select.h` on OpenBSD.

**Comment by jalvesaq** [comment]
I am going to include sys/select.h in nvimcom.c. Please, reopen the issue if the bug is not fixed.

**Comment by feinerer** [comment]
Unfortunately your change does not fix the problem.

The [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-devel/R-exts.html) manual mentions:
> Note that the header sys/select.h is needed: users should check this is available and define HAVE_SYS_SELECT_H before including R_ext/eventloop.h.

Following diff (reverting your fix and defining `HAVE_SYS_SELECT_H` immediately before `R_ext/eventloop.h`) works for me:

`diff --git a/R/nvimcom/src/nvimcom.c b/R/nvimcom/src/nvimcom.c`
`index 2b51a67..295703d 100644`
`--- a/R/nvimcom/src/nvimcom.c`
`+++ b/R/nvimcom/src/nvimcom.c`
`@@ -3,6 +3,7 @@`
` #include <R_ext/Parse.h>`
` #include <R_ext/Callbacks.h>`
` #ifndef WIN32`
`+#define HAVE_SYS_SELECT_H`
` #include <R_ext/eventloop.h>`
` #endif`
` `
`@@ -26,7 +27,6 @@`
` #include <pthread.h>`
` #include <signal.h>`
` #include <sys/time.h>`
`-#include <sys/select.h>`
` #endif`
` `
` static char nvimcom_version[32];`

**Comment by jalvesaq** [comment]
Thanks! It should be OK now.
