### ISSUE TITLE
Cannot start R in R 3.3.2

### ISSUE THREAD

**Issue by blayz3r** [jalvesaq/Nvim-R#121]
I updated my version of R from 3.3.1 to 3.3.2 and am getting the following
![2016-11-01_18-14-33](https://cloud.githubusercontent.com/assets/12205650/19909766/820d4ade-a05f-11e6-97d0-f6bdba465320.png)
 error when I try to start R.

**Comment by jalvesaq** [comment]
I installed R-3.3.2 on Windows 10, and did not have any problem with the current development version of Nvim-R.

**Comment by blayz3r** [comment]
Just tried it again, error is gone.I'm pretty sure I didn't change anything.

**Comment by jalvesaq** [comment]
Thanks for the feedback!
If someone experiences the same problem and can describe the procedure to replicate it, the issue should be reopened.
