### ISSUE TITLE
Vim Startup slow when opening R file

### ISSUE THREAD

**Issue by wngrtn** [jalvesaq/Nvim-R#123]
I have two modern Windows 10 machines. On one, opening vim with an R file takes more than three times as long as on the other (more than 10 seconds).

How would I go about diagnosing what happens during Nvim-R startup and why things are so slow on the one machine?

Is there anything specific to watch out for with respect to startup times?

**Comment by jalvesaq** [comment]
On Linux, we can run Vim from the command line as in the example:
```
vim --startuptime /tmp/vimtime
```
Then, we can look at the file /tmp/vimtime to see what time each script takes to be sourced. You have to find a way of doing the same on Windows. Perhaps changing the shortcut for GVim...

Once you find what script takes longer to be sourced in one machine than in the other, you would have to edit it and create variables registering the time, like this:
```vim
let g:time1 = reltimefloat(reltime())
" skip some (or many) lines of the code
let g:time2 = reltimefloat(reltime())
" skip some (or many) lines of the code
let g:time3 = reltimefloat(reltime())
```
After Vim startup, you would do in Normal mode:
```vim
:echo g:time2 - g:time1
:echo g:time3 - g:time2
```
Then, you would have to move the lines above (like in a binary search) until you find the specific line in the script that is causing the slowness.

**Comment by wngrtn** [comment]
Thank you for the excellent instructions. On the slow machine, calls to `system()` take more than a second. On the fast machine, they take mere milliseconds. This is with the exact same configuration files.

The only difference between the two machines that I could find is that the machine with the long startup time runs Windows 10 Pro while the other one runs Home.

Any clues? Does anybody else see these delays on Windows 10 Pro?

**Comment by jalvesaq** [comment]
I think you should ask for help in the Vim mailing list, if you are using Vim. You could also try Neovim, although its biggest advantage is the embedded terminal emulator which is no longer working on Windows.

**Comment by jalvesaq** [comment]
@wngrtn Any news on this issue?

**Comment by wngrtn** [comment]
Yes, sorry about not posting this earlier. It turned out that Kaspersky was slowing down each individual process spawned by Nvim-R while preparing to edit an `R` file.

**Comment by jalvesaq** [comment]
Thanks for the feedback! I noted that many DOS like windows appears in and quickly vanishes from the task bar when Vim is starting to edit an R script for the first time. This does not happen with Neovim. You could try it with Kaspersky running to see if the same problem affects Neovim too.
