### ISSUE TITLE
plugin fails to communicate with R on Windows

### ISSUE THREAD

**Issue by polde-live** [jalvesaq/Nvim-R#127]
I'm having trouble getting the plugin to work on my Windows 7 company machine.
The plugin works fine under Debian, but sending a line with "\l" or "\d" is working 1 out of 10 times. 
I'm working with gvim8, the gui menu item is not working as well. 

It seems to work somewhat better on my other Windows 10 machine, but can't tell what may be the difference. _vimrc and plugins configuration are the same on both systems.

Best Regards
pd

**Comment by jalvesaq** [comment]
This might be useful: https://github.com/jalvesaq/Nvim-R/issues/123

**Comment by polde-live** [comment]
Thanks, I will take a look,
best
pd

**Comment by jalvesaq** [comment]
@polde-live Is the problem solved?

**Comment by polde-live** [comment]
Seems like a problem with vim for Windows, I don't get this issue when running it in Cygwin terminal, so I switched.
