### ISSUE TITLE
Error starting konsole terminal

### ISSUE THREAD

**Issue by sjewo** [jalvesaq/Nvim-R#128]
First, let me thank you for this great plugin! 

I had some problems with R in an external kde konsole (16.08.3) terminal window with vim and neovim on a newly installed archlinux system. It seems that konsole needs quotes around the tmux command.
I patched `extern_term.vim` and added the missing quotes. Maybe you'd like to adopt the patch: bcc6811aef49396ac960c783723b3176261deb1f

**Comment by jalvesaq** [comment]
Thanks! I am going to apply it.
