### ISSUE TITLE
Consider making RStart / StartR available outside filetype r

### ISSUE THREAD

**Issue by ecerulm** [jalvesaq/Nvim-R#132]
I wanted to be able to start the R console but none of the key mapping where available until an R buffer is opened. I guess Nvim-R is a ftplugin only, that is only loaded when an R buffer is opened. 

It could be convenient (for me at least) that Nvim-R provides an :RStart , :Stop command (loaded as plugin/ ) I guess that would "require" to move most functions to autoload to avoid affecting vim startup time.

**Comment by jalvesaq** [comment]
The old Vim-R-plugin used to include a Vim script that could be moved to `~/.vim/plugin` directory to turn the ftplugin into a global plugin. But it was very problematic to maintain. Anyway, you can try to create your own `:RStart` command. Please, try this in your vimrc:

```vim
command RStart let oldft=&ft | set ft=r | exe 'set ft='.oldft | normal <LocalLeader>rf
```

Let me know if it works as you want. If yes, then I can put the tip in the Nvim-R documentation.

**Comment by ecerulm** [comment]
Yes, that works. Nice, Thanks. I guess it will always help new users if the documentation mentions how to "load" the plugin without having to open an R related file.
