### ISSUE TITLE
Black band over italic unknown words in RMarkdown 

### ISSUE THREAD

**Issue by l0ka** [jalvesaq/Nvim-R#134]
This plugin is great, I completely replace RStudio with a lightweight alternative.
I use quite a lot RMarkdown. I noticed that when I write a word in italic (between asterisks) that is unknown for the dictionary, it appears as a black band, within the editor. 
Is that expected? Can I change/remove the color?
Thanks

P.S.: I'm using Debian Jessie 8.6, with 3.16.0-4-amd64 linux kernel and Vim 8.0 (installed from Debian testing repository)

**Comment by jalvesaq** [comment]
This looks like a syntax highlighting problem, and it will be useful to know how the word is being classified by the syntax highlight algorithm. I have the following line in my vimrc:
```
map <F12> :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<' . synIDattr(synID(line("."),col("."),0),"name") . "> lo<" . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<CR>
```
Could you, please, put the above line in your vimrc and press `<F12>` over the word with the black band? What is the output, that is, what is the syntax group? How your colorscheme highlights the syntax group?

To know the colors used by your colorscheme, type in Normal mode `:hi`

**Comment by l0ka** [comment]
Thank you for your quick reply.

The output of `<F12>` is:
`hi<pandocEmphasis> trans<pandocEmphasis> lo<pandocEmphasis>` 
`Press ENTER or type command to continue`

The output of `:hi` is:
[hi.txt](https://github.com/jalvesaq/Nvim-R/files/649016/hi.txt)

**Comment by l0ka** [comment]
Thank you for your quick reply.

The output of `<F12>` is:
`hi<pandocEmphasis> trans<pandocEmphasis> lo<pandocEmphasis>` 
`Press ENTER or type command to continue`

The output of `:hi` is:
[hi.txt](https://github.com/jalvesaq/Nvim-R/files/649016/hi.txt)

**Comment by jalvesaq** [comment]
I can't see the color of `pandocEmphasis` in hi.txt but I guess that it is black foreground and black background. Unless you are sure that Nvim-R is causing the but, perhaps you should report the bug to https://github.com/vim-pandoc/vim-pandoc-syntax

**Comment by l0ka** [comment]
I tried to disable `vim-pandoc-syntax` and the problem is solved. So it's a problem regarding that plugin,
not Nvim-R.

**Comment by jalvesaq** [comment]
Thanks for the feedback. I'm closing the issue.
