### ISSUE TITLE
Combine RDSendSelection and RAction("head")

### ISSUE THREAD

**Issue by mchiapello** [jalvesaq/Nvim-R#135]
Hi,
if I select in visual mode a variable, I can sent it to the console by pressing `<space>`

There is a way to select a variable and print the head in the console?

I solved the problem doing:

`map <silent> <LocalLeader>h <ESC>:call RAction("head")<CR>`

But if I select a variable before a "$" I get the head of that specific column and not only the variable.

**Comment by jalvesaq** [comment]
I am going to add an extra optional argument to `RAction()`: the temporary value of 'iskeyword' that will be used to get the word under cursor. Then, you will be able to choose what will be included in the keyword. I think that what you want is:

```
map <silent> <LocalLeader>h <ESC>:call RAction("head", "@,48-57,_,.")<CR>
```
