### ISSUE TITLE
Error_installing_nvimcom

### ISSUE THREAD

**Issue by DadongZ** [jalvesaq/Nvim-R#137]
I have been using Nvim-R for a while and it works great since then. But it suddenly pop-out an error today by starting R with '\rf':
![screenshot](https://cloud.githubusercontent.com/assets/8431321/21438688/612191ec-c858-11e6-999a-51c9cf7e6ceb.png)

#nvim version
NVIM 0.1.4
Build type: None
Compilation: /usr/bin/cc -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-1AXpO2/neovim-0.1.4/build/config -I/build/neovim-1AXpO2/neovim-0.1.4/src -I/usr/include -I/usr/include -I/usr/include/luajit-2.0 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-1AXpO2/neovim-0.1.4/build/src/nvim/auto -I/build/neovim-1AXpO2/neovim-0.1.4/build/include
Compiled by buildd@babin

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

#linux version
Description:	Debian GNU/Linux 8.6 (jessie)
Release:	8.6
Codename:	jessie

Any suggestions?

**Comment by jalvesaq** [comment]
The development version of Nvim-R is tested with the development version of Neovim, and Neovim 0.1.4 was released in April.
You should either downgrade Nvim-R or upgrade Neovim.

**Comment by DadongZ** [comment]
Thanks, I will try it and let you know.

**Comment by DadongZ** [comment]
I have upgraded neovim but it doesn't solve the issue. I am wondering how
uninstall Nvim-R mannually. I installed it before I was using vundle. I am
going to install a later Nvim-R version.

**Comment by jalvesaq** [comment]
If you have installed the Vimball, the commands are:
```
:packadd vimball
:RmVimball Nvim-R
```

**Comment by jalvesaq** [comment]
Is the problem solved?

**Comment by jalvesaq** [comment]
Closing the issue for lack of information.
