### ISSUE TITLE
Send chunk \ce cannot handle back-ticks in function or variable names

### ISSUE THREAD

**Issue by FvD** [jalvesaq/Nvim-R#14]
A chunk that has a variable or function name with a back-tick will not be sent correctly to the R session. For example:

    ```{r}
    `%notin%` <- function(x,y) !(x %in% y) 
    ```

resulting in an `unexpected SPECIAL` error

    ```{r}
    `Binomial nomenclature` <- 3
    ```

resulting in an `unexpected INCOMPLETE_STRING` error

Perhaps the definition of the chunk could look at consecutive back-ticks. It seems as if it only looks at the first.

**Comment by jalvesaq** [comment]
The problem is caused by lines 1135 and 1505 of R/common_global.vim which are:

```vim
let lines = map(copy(lines), 'substitute(v:val, "^\\`\\`\\?", "", "")')
let line = substitute(line, "^\\`\\`\\?", "", "")
```
I don't know why these lines are there, but there must be a reason. These lines might be avoiding another bug...

I don't use Rmd. Could you, please, delete (or comment out) these two lines and see what happens?

**Comment by FvD** [comment]
Commenting those lines solves the issue. And it appears that the regular expression is too greedy. By ensuring that there are at least two consecutive backticks the issue is also solved

    let lines = map(copy(lines), 'substitute(v:val, "^(\\`\\`)\\?", "", "")')

I will make a pull request for the above solution.
