### ISSUE TITLE
R_LIBS and R_LIBS_USER not exported to tmux pane

### ISSUE THREAD

**Issue by phcerdan** [jalvesaq/Nvim-R#140]
The new `tmux` pane where `R` is executed is not reading the environment variables `R_LIBS_USER` or `R_LIBS` set in the pane where vim was opened.
How can I add my own `R_LIBS_USER` path to NvimR with `tmux`?
```
  let R_notmuxconf = 1
  let R_vsplit = 1
  let R_in_buffer = 0
  let R_applescript = 0
  let R_tmux_split = 1
```
If I use the default nvim `term` instead of the `tmux` pane, it works, ie, removing the last 3 options:
```
  let R_in_buffer = 0
  let R_applescript = 0
  let R_tmux_split = 1
```

**Comment by jalvesaq** [comment]
I have put in my `~/.bashrc`

```
export THIS_IS_A_TEST=Testing_Tmux
```

and in my `~/.tmux.conf`

```
set -g update-environment "THIS_IS_A_TEST"
```

Then, I can see `"Testing_Tmux"` when I run in R the command `Sys.getenv("THIS_IS_A_TEST")`. So, try this in your `~/.tmux.conf`:

```
set -g update-environment "R_LIBS_USER R_LIBS"
```

**Comment by phcerdan** [comment]
That works, even if `R_LIBS` are exported manually in just one terminal (not using `~/.bashrc`.)
