### ISSUE TITLE
Error using View() function

### ISSUE THREAD

**Issue by imantdaunhawer** [jalvesaq/Nvim-R#141]
I'm using the plugin in terminal vim on OSX (El Capitan) and I have an issue applying functions that make use of the X11 window system from the console (tmux window within xterm). Such an example is the `View()` function which, when run from the console, throws the following error:

```Error in View(dat) : X11 is not available```

Yet, I have no problem calling `View` from within Vim by using the shortcut `<leader>rv`, which simply opens the view on the data in a new buffer.

I would greatly appreciate your help in solving this issue or pointing me to the right direction.

**Comment by jalvesaq** [comment]
I don't have access to any OS X to make tests, but perhaps the environment variable DISPLAY is missing. You could try to configure tmux to export it. Please, see this: https://github.com/jalvesaq/Nvim-R/issues/140

**Comment by imantdaunhawer** [comment]
Thank's for the quick reply.

Turns out tmux was not the problem. The installation through the package manager `brew` was the source of the problem. Installing the "official" R and cleaning the cache `rm ~/.cache/Nvim-R` solved the problem for me.
