### ISSUE TITLE
Vim 8.0.170 - R Console opens in new tmux window

### ISSUE THREAD

**Issue by mickaeltemporao** [jalvesaq/Nvim-R#144]
I use vim directly within OSX terminal.
However, when I try to launch R within Vim 8, it opens the console in a new tmux window instead of opening it in a separate pane.

Does someone have the same problem? Or a solution?
Thanks for any help at all.
Mickael

**Comment by jalvesaq** [comment]
Please, do:
```vim
:h Nvim-R-Tmux
```

**Comment by jalvesaq** [comment]
Please, see also: https://github.com/jalvesaq/Nvim-R/issues/54#issuecomment-207516302

**Comment by mickaeltemporao** [comment]
Excellent this fixes it!
