### ISSUE TITLE
devtools::find_topic() migrated to r-pkgs/pkgload

### ISSUE THREAD

**Issue by nacnudus** [jalvesaq/Nvim-R#146]
The function `devtools::find_topic()` has been migrated to a new package, `pkgload::dev_help()` in the development version of devtools.

**Comment by jalvesaq** [comment]
Could you, please, do a pull request for this? I do not use devtools, and I could not find `find_topic()` in https://github.com/r-pkgs/pkgload
What I have found was:

> `dev_help()` now optionally takes a character vector of packages to search within.  This replaces `find_topic()`.

**Comment by nacnudus** [comment]
I'll try.  The relevant file seems to be R/nvimcom/R/nvim.help.R.  Should I add another `if(` block to try pkgload if `devtools::find_topic()` doesn't exist?

```r
    # try devtools first (if loaded)
    if ("devtools" %in% loadedNamespaces()) {
        if (missing(package)) {
            if (!is.null(devtools:::find_topic(topic))) {
                devtools::dev_help(topic)
                return(invisible(NULL))
            }
        } else {
            if (package %in% devtools::dev_packages()) {
                ret = try(devtools::dev_help(topic), silent = TRUE)
                if (inherits(ret, "try-error"))
                    .C("nvimcom_msg_to_nvim", paste0("RWarningMsg('", as.character(ret), "')"), PACKAGE="nvimcom")
                return(invisible(NULL))
            }
        }
    }
```

**Comment by jalvesaq** [comment]
Yes, I think that 
```
if ("devtools" %in% loadedNamespaces())
```
should be either
```
if ("devtools" %in% loadedNamespaces() && "pkgload" %in% loadedNamespaces())
```
or
```
if (sum(c("devtools", "pkgload") %in% loadedNamespaces()) == 2)
```

**Comment by nacnudus** [comment]
This will depend on https://github.com/r-pkgs/pkgload/pull/8 being merged.

**Comment by jalvesaq** [comment]
Is this issue still relevant?

**Comment by nacnudus** [comment]
I don't know but it isn't doesn't impact upon me any more.

**Comment by ashiklom** [comment]
This issue popped up for me while using a development version of `devtools`. The following fix to `nvim.help.R`, function `nvim.help` seemed to work for me:

```r
        if (missing(package)) {
            tryCatch(
              pkgload::dev_help(topic),
              error = function(e) .C(
                "nvimcom_msg_to_nvim",
                "RWarningMsg(Unable to get dev documentation)",
                PACKAGE = "nvimcom")
            )
            return(invisible(NULL))
        } else {...
```

**Comment by ashiklom** [comment]
The first one, which uses `devtools` to access the development documentation:

https://github.com/jalvesaq/Nvim-R/blob/db0acc21e11d51bc2fe83504c78cb2bef73d35cc/R/nvimcom/R/nvim.help.R#L42-L57

**Comment by jalvesaq** [comment]
@nacnudus did you try @ashiklom code?

**Comment by nacnudus** [comment]
@jalvesaq I've tried it and it works for me.
