### ISSUE TITLE
encoding issues in windows

### ISSUE THREAD

**Issue by gilles13** [jalvesaq/Nvim-R#151]
Hy,

I have encoding issues when I send command from gvim 8 to rgui.
my accented char print correctly in gvim, but seem to be converted when I send command line in rgui.
Any ideas to correct this problem ? set env variable ?
Thank you

**Comment by jalvesaq** [comment]
Gvim and R must use the same encoding.

**Comment by jalvesaq** [comment]
It seems that it is not possible to run R in UTF-8 locale on Windows. Then, you have two options:

  - Use GVim with native windows charset (in your case, Windows-1252).

  - Convert the strings before sending them to R (see issue #125).
