### ISSUE TITLE
support other language syntax highlighting in Rmarkdown code chunks

### ISSUE THREAD

**Issue by etheleon** [jalvesaq/Nvim-R#152]
Is it possible to enable syntax highlighting for code chunks besides R language for R markdown files?

I understand knitr currently supports other languages in the Rmd
https://yihui.name/knitr/demo/engines/

```{python}
print("hello world")
```

the [vim-pandoc/vim-pandoc-syntax](https://github.com/vim-pandoc/vim-pandoc-syntax) supports this by via the 

`:PandocHighlight LANG` command 

so for python it'll be 
`:PandocHighlight python`

**Comment by jalvesaq** [comment]
Please, reopen the issue at https://github.com/jalvesaq/R-Vim-runtime/issues

**Comment by jalvesaq** [comment]
@etheleon could you please try this branch: https://github.com/jalvesaq/R-Vim-runtime/tree/rmd_engine

**Comment by etheleon** [comment]
sure!
