### ISSUE TITLE
How to automatically open PDF file generated by \kr command?

### ISSUE THREAD

**Issue by qifei9** [jalvesaq/Nvim-R#153]
When using kint with rmd fild, sometimes I have to using `xelatex` latex engine and/or `bookdown::pdf_document2` output format. In this situation, I have to use `\kr` rather than `\kp` to generate the PDF file. Then the plugin cannot automatically open the generated PDF file.

I tried `\op` after `\kr`. This does not work too.

**Comment by jalvesaq** [comment]
You have to define the output options in the Rmd file. For example, put these lines at the very beginning of your Rmd:
```
---
title: "Data analysis"
output:
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
    latex_engine: xelatex
---
```
Then, you can use `<LocalLeader>kp` to generate and open the pdf.

See: http://rmarkdown.rstudio.com/pdf_document_format.html

**Comment by qifei9** [comment]
Many thanks.

However, this works for `pdf_document` output format but not for `bookdown::pdf_document2` output format. With the these options: 
```
---
title: "Data analysis"
output:
  bookdown::pdf_document2:
    toc: true
    toc_depth: 3
    number_sections: true
    latex_engine: xelatex
---
```
`<LocalLeader>kp` will run into command: 
```
/usr/bin/pandoc +RTS -K512m -RTS skeleton.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output skeleton.pdf --template /home/user/R/x86_64-pc-linux-gnu-library/3.3/rmarkdown/rmd/latex/default-1.17.0.2.tex --highlight-style tango --latex-engine pdflatex --variable graphics=yes
```
which does not take the defined options.

The `bookdown::pdf_document2` output format brings some additional features to `pdf_document`, for example, cross-reference of figures and tables. Sometimes these additional features are really necessary.

**Comment by jalvesaq** [comment]
Then, I have to make Nvim-R read the header to call `rmarkdown::render()` with the correct arguments. I will see this later.

**Comment by jalvesaq** [comment]
What command what you have to do manually?

**Comment by qifei9** [comment]
Sorry that I did not quite get the question "What command what you have to do manually?".

If I manually run `> render("./skeleton.rmd")`  or `> render("./skeleton.rmd", output_format='bookdown::pdf_document2')` with options:
```
---
title: "Data analysis"
output:
    bookdown::pdf_document2:
        keep_tex: false
        latex_engine: xelatex
        toc: true
        number_sections: false
        includes:
            in_header: header.tex
            before_body: doc_prefix.tex
fontsize: 12pt
documentclass: article
classoption: a4paper
geometry: a4paper, margin=1in
---
```
It works fine and I will get this output:
```
> render("./skeleton.rmd")


processing file: skeleton.rmd
  |................................                                 |  50%
  ordinary text without R code

  |.................................................................| 100%
label: f-all (with options)
List of 4
 $ echo     : symbol F
 $ fig.cap  : chr "Nice fig."
 $ fig.align: chr "center"
 $ fig.pos  : chr "htbp"


output file: skeleton.knit.md

/usr/bin/pandoc +RTS -K512m -RTS skeleton.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output skeleton.tex --table-of-contents --toc-de
pth 2 --template /home/qifei/R/x86_64-pc-linux-gnu-library/3.3/rmarkdown/rmd/latex/default-1.17.0.2.tex --highlight-style tango --latex-engine xelatex --include-in-header header.tex --includ
e-before-body doc_prefix.tex --variable graphics=yes --variable tables=yes --standalone
Latexmk: This is Latexmk, John Collins, 5 Sep. 2016, version: 4.48.

Output created: skeleton.pdf
```

**Comment by jalvesaq** [comment]
Thanks for the skeleton.init.md! However, I reached the conclusion that, instead of trying to call `rmarkdown::render()` with the correct arguments, nvimcom should simply check whether the extension of the output file is ".html" or ".pdf".
I am going to close the issue with the next commit. Please, reopen it if the problem remains.

**Comment by qifei9** [comment]
Now it works perfectly. Many thanks for your help and this wonderful plugin.
