### ISSUE TITLE
Update nvimcom fails to see local R_LIB

### ISSUE THREAD

**Issue by davvelsan** [jalvesaq/Nvim-R#154]
```
GVIM 8.0. Included patches: 1-237.
Nvim-R installed via vim-plug
R version 3.3.2 (2016-10-31)                  
nvimcom  0.9-26  2017-01-31 local 
```

I manage my R packages locally at `$HOME/.R/libs`. I update packages and run VIM as a local user, so `/usr/lib/R/library/` is not writtable. Every time Nvim-R needs to update nvimcom, it asks to create a local nvimcom install in `$HOME/R/x86_64-pc-linux-gnu-library/`.

I tried adding `R_LIBS` and `R_LIBS_USER`  to the PATH. I also tried adding the local library path to `.Library` and `.libPaths` in my `.Rprofile`. Yet the upgrade process never sees the local library.

What's funny is that Nvim-R _does_ see the local lib, because once the R process starts within Vim I get the following: `Warning message: Your version of Nvim-R requires nvimcom-0.9-26`

Moving the updated package to my local library fixes this issue, but it's not very convenient. What am I doing wrong?

**Comment by jalvesaq** [comment]
It is not a matter of setting the environment variable `PATH` because the path is used to find executable files (Rgui.exe, Rterm.exe, etc.). Is the environment variable `R_LIBS_USER` set to `$HOME/.R/libs`?
I use Linux, and I have this in my `~/.bashrc`:

```
export R_LIBS_USER=~/.cache/R
```

**Comment by davvelsan** [comment]
I have defined R_LIBS_USER in `~/.bashrc` and within a config file inside `~/.config/fish/conf.d`.

```
# ~/.bash.rc
export R_LIBS_USER=~/.R/libs

# ~/.config/fish/conf.d/bin.fish
set -x R_LIBS_USER "~/.R/libs"
```

I use both bash and fish shell, where appropriate. In either shell the result of `echo $R_LIBS_USER` points to the correct path.

Fish-shell stuff probably does not matter, though. Vim should run in bash. This is at the top of my `.~/vimrc`:

```
if &shell =~# 'fish$'
    set shell=/bin/bash
endif
```

**Comment by jalvesaq** [comment]
Do you have anything related with this issue in your .Rprofile?

**Comment by davvelsan** [comment]
Yes. I think this is all the related stuff in my `.Rprofile`

```
if(interactive()){
    .Library <- "~/.R/libs"
    .libPaths("~/.R/libs") # necessary for Nvim-R, even if R_LIBS_USER is set
    library(nvimcom)

    ...
}
```

**Comment by jalvesaq** [comment]
You should not put `library(nvimcom)` in your .Rprofile. I don't know what will be the effect of .Library and .libPaths.

**Comment by davvelsan** [comment]
Your're right, `nvimcom` was not needed in my `.Rprofile`. In addition, I tried launching R from **VIM**, not **GVIM**, and not only setting `.libPaths` was not needed, but also Nvim-R updated `nvimcom` without problems. So the issue seems to be with using GVIM.

////////////

If I use GVIM, if I don't set at least `.libPaths` it in my `.Rprofile`, R launched from Nvim-R won't see my local library. 

```
During startup - Warning messages:
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘nvimcom’
2: package ‘nvimcom’ in options("defaultPackages") was not found
```
And the output of `.libPaths()` is
```
"/usr/lib/R/library
```

In addition, this is what happens when, even with `.libPaths` modified at startup, I refuse to create a new local lib during `nvimcom` update:

```
* installing to library ‘/usr/lib/R/library’
Error: ERROR: no permission to install to directory ‘/usr/lib/R/library’
```

**Comment by jalvesaq** [comment]
I have a setup similar to yours (I export `R_LIBS_USER` in my `bashrc`) and Nvim-R works with Gvim here. I even deleted the file `~/.cache/Nvim-R/nvimcom_info` and nvimcom was correctly updated. So, I can't reproduce your issue and, consequently, I can't fix it.

**Comment by davvelsan** [comment]
That's weird. It must be something else in my system that is creating a conflict. I'll keep monitoring it, but meanwhile I'm closing this issue for now.

Thanks for your support, I'll post again when I have new info.

**Comment by davvelsan** [comment]
An update on this issue, I finally figured out how to trigger the bug.

It turns out to be a problem with how `openbox` executes commands via keyboard shortcuts. Normally I start VIM using the shortcut Ctrl-Alt-V, which in turn executes `gvim` command.

Launching VIM this way is what causes the problem of `NVim-R` not seeing my local library to update `nvimcom`. It is still a mystery why it only happens when updating `nvimcom`, and not for any other `R` packages, though.

I am reopening the issue because now it can be reproduced properly. Up to you to decide whether to keep it open. I'm not sure this is something that can/should be fixed, or simply avoided.

**Comment by davvelsan** [comment]
Sorry for double posting, but I want to post this separately. I'm starting to think this is an issue I should discuss with the `openbox` developer.

Starting VIM via `openbox` also causes tpope's `vim-fugitive` to not communicate with my local ssh-agent. I'm not sure what's going on with the shell `openbox` uses to exec commands via shortcuts.

**Comment by jalvesaq** [comment]
Thanks for your feedback!

I can reproduce the bug by opening GVim using Unity in Ubuntu. I did not test the whole issue. I just tried
```vim
:echo $R_LIBS_USER
```
and works in the terminal emulator, but not in GVim if it was started by Unity. The solution is to put the export line in `~/.profile`, not in `~/.bashrc`, because graphical applications are not supposed to run in an environment defined by `bash`. Their environment is defined by `~/.profile`. So, I put in my `~/.profile`:
```
export R_LIBS_USER=~/.cache/R
```
I think this is not an openbox bug. What you put in your `~/.profile` is valid for both desktop manager and login shells (the terminal emulator) while what is in the `~/.bashrc` is valid only for the terminal (and only if you are running bash). For more information, please, seek the string `.profile` at https://help.ubuntu.com/community/EnvironmentVariables

**Comment by davvelsan** [comment]
Thanks for your detailed answer. I have created `~/.profile` and added the export line. However, `$R_LIBS_USER` is still not declared when launching GVim from `openbox`, whereas if I launch it from the terminal it is indeed declared.

I will continue to monitor this issue on my end, but I'm closing it here for the time being, as this does not seem related to `NVim-R` at all.
