### ISSUE TITLE
knitr tufte handout style

### ISSUE THREAD

**Issue by gilles13** [jalvesaq/Nvim-R#155]
Hi,
is it possible to knit a document with tufte handout style ? 
when I try, I get the following error :
Unknown language engine 'marginfigure' (must be registered via knit_engines$set()

**Comment by jranke** [comment]
Is it possible that you have a syntax error in your chunk header? Did you include the "r" as in

```
```{r, marginfigure = ...}
```
?

**Comment by gilles13** [comment]
no, it seem that ```label, fig.margin = TRUE``` and ```marginfigure``` are not well interpreted by knitr engine

**Comment by jranke** [comment]
Yes, this syntax is not advertised by knitr. It wants `r` in braces, optionally with arguments.

**Comment by gilles13** [comment]
sorry, it's my fault. I was using knit functions (kn, kp, ...)
All I need is to use is markdown function (kr)
