### ISSUE TITLE
Consistent error on first use ROnJobStdout: FillRLibList

### ISSUE THREAD

**Issue by scottstanfield** [jalvesaq/Nvim-R#157]
I get this annoying error every single time I fire up Nvim-R and use it for the first time. For the rest of the session, it doesn't pop up.

I'm on Ubuntu. Latest R. Latest Nvim-R (as of this morning) and vimcom is updated. Running neovim. Trivial steps to reproduce:

1. Launch Nvim-r with `\rf`
2. Type in `print('hello world')`
3. Send that line using `\l` 

Also fails when sent as a block selection. Only happens the first time. I've been seeing this for months and months. Any ideas? It's a pretty clean install.

![image](https://cloud.githubusercontent.com/assets/280700/22704302/0de3679c-ed1c-11e6-816f-240a59017a8d.png)

**Comment by scottstanfield** [comment]
Saw that it was reported, then closed. I saw it back at issue #66

**Comment by scottstanfield** [comment]
I read through the code...I'm able to suppress the error/warning by placing this in my .vimrc

`let R_hi_fun = 0`

I think it "hides" the function by creating an empty function definition. Anyway, I'm not sure what the side-effects are down-stream, but I'm no longer getting the error. Probably not working as intended :)

**Comment by jalvesaq** [comment]
Note that `vimcom` is for the old Vim-R-plugin. Nvim-R uses nvimcom but it is updated and loaded automatically. You should not have either `library(vimcom)` or `library(nvimcom)` in your `.Rprofile`, and you should not manually install `nvimcom`.

**Comment by jalvesaq** [comment]
You should have only one `function.vim` in your entire nvim directory. How many of them can you see if you do the following?

```
cd ~/.config/nvim
ls -R | grep functions.vim
```

**Comment by jalvesaq** [comment]
@scottstanfield Is the problem solved?

**Comment by scottstanfield** [comment]
Sorry I didn't follow up in time. A few points:

I don't have `vimcom` installed, and my `.Rprofile` doesn't do anything but `library(colorout)`.

Only one `functions.vim`

I still need the workaround of `let R_hi_fun = 0` in my `~/dotfiles/.config/nvim/init.vim` file. Which is totally acceptable. 

So yeah, leave it closed. I'm happy to investigate more. I can repro for you on a clean install too.

**Comment by EmilRehnberg** [comment]
@jalvesaq I am suffering from this problem also, getting the error from the original post.

I have 3 `functions.vim`. They are in:
`./repos/github.com/Shougo/neosnippet.vim/test`
`./repos/github.com/Shougo/vimproc.vim/test`
`./repos/github.com/jalvesaq/Nvim-R/R`

Any suggestions to how to fix?

**Comment by jalvesaq** [comment]
I don't know what is the cause of the problem. Anyway, Nvim-R now should source `R/functions.vim` before starting R if the function `FillRLibList` does not exist: https://github.com/jalvesaq/Nvim-R/commit/af3aac27d8401f73829b5272b2c05e14d34153f4

**Comment by EmilRehnberg** [comment]
Thank you so much @jalvesaq !!
I don't get the error anymore. Case closed.
