### ISSUE TITLE
Can't seem to open tmp files

### ISSUE THREAD

**Issue by nabsiddiqui** [jalvesaq/Nvim-R#160]
I am running Vim 8.0 and I can't seem to read tmp files even if I set them to a different directory. I receive the following errors:

```
Error detected while processing function SendLineToR[79]..SendCmdToR_TmuxSplit:
line   20:
E484: Can't open file /tmp/vONs0PU/16
```

I feel like I am missing something very obvious.  I am running it through tmux(can't seem to get it to work without tmux yet or know if it is possible).  In nvim, I seem to be able to get everything to work.

**Comment by jalvesaq** [comment]
There is no error here with Vim 8.0.314, tmux 2.2, and the development version of Nvim-R.

**Comment by nabsiddiqui** [comment]
Sorry, I am confused.  Do you mean this is an expected error?

**Comment by jalvesaq** [comment]
No, the error is not expected. The plugin works without errors in my system. Tmux window is split and R run in the new pane.

That is, I cannot fix the bug because I can't reproduce it.

**Comment by nabsiddiqui** [comment]
Thank you for the follow up.  I figured out the error.  There was a problem in fish shell when it is set as default terminal.  I reset mine to bash and had it load fish terminal through bashrc instead.
