### ISSUE TITLE
system calling samtools gives gibberish

### ISSUE THREAD

**Issue by etheleon** [jalvesaq/Nvim-R#162]
I'm using samtools 1.3.1

and i ran this command in R

```r
system("samtools sort <unsorted bam> -o <sorted bam>")
```

it prints gibberish to my R pane. 

when I ran the same command in a separate R session, it doesnt have such a problem.

**Comment by jalvesaq** [comment]
It looks like a Tmux problem. Could you try Neovim? It does not need Tmux.

**Comment by jalvesaq** [comment]
Any news on this issue?
