### ISSUE TITLE
Hangs on Completion

### ISSUE THREAD

**Issue by blayz3r** [jalvesaq/Nvim-R#164]
![2017-02-18_16-28-27](https://cloud.githubusercontent.com/assets/12205650/23097356/96ac7e60-f5ff-11e6-8cc0-5a20d1ca1172.png)

Vim hangs for a couple of seconds when I trigger (C-X)(C-O) completion.Completion still works but I still get the error message "no reply".

2)Is there a way to trigger semantic completion on "." .I am using YCM

3)Example.R files have trailing blank lines that cause GVIM to hang(no sure what this is about)

**Comment by blayz3r** [comment]
2) and 3) can be ignored

When R is running issue 1) occurs .When R is closed completion works as it should.

**Comment by jalvesaq** [comment]
Is any message displayed after the attempt of completion if you type `:messages`?
Does R workspace has many objects or lists with many elements? Nvim-R waits only 100 milliseconds for R to build the list of objects. See lines 2909-2911 of `R/common_global.vim`.

**Comment by blayz3r** [comment]
![completion](https://cloud.githubusercontent.com/assets/12205650/23098072/c99d7816-f612-11e6-959a-e4ba8734b208.png)

Messages? only shows the R error: no reply.

My object browser is empty but I have a few packages installed.

The odd thing is that when I open an r file without starting R(,rf). All objects and function are available for completion instantly.When I start it hangs for a few seconds on .(dot) completion and gives me the error

**Comment by jalvesaq** [comment]
If R is running, the completion is slow because Nvim-R sends a message to R requesting the list of objects in its workspace and, then, it waits until R writes the list in a file. Finally, Nvim-R reads the file. Probably the whole process will be faster if you can set `R_tmpdir` to be created in a RAM "disk". Please, see:
```vim
:h R_tmpdir
```

**Comment by jalvesaq** [comment]
On another issue, a user have reported slowness caused by an antivirus software which was monitoring calls to `system()`...

**Comment by blayz3r** [comment]
Ok I played around with the file and it seems that completion works if I send something to R first before trying it.I guess I can live that.Anyway hope this didn't waste too much of your time.

**Comment by jalvesaq** [comment]
On Windows, nvimcom started with the flag `r_is_busy` set to `1`, which prevented some things of working (and also made it more stable, avoiding R crashes). However, Nvim-R also checks if nvimcom is running before sending commands to it. So, I guess the initial state of the flag might be `0`, and I set it to this value in the last commit.

Could you check if still there a hang during the completion? You can also stress test the plugin by issuing commands that uses nvimcom like `\rh` and `\rh` while R is still starting. If there is any bug, I will revert the value of `r_is_busy` to `1`.

**Comment by blayz3r** [comment]
Ok I tested "\rh" before updating the plugin and **before you** send input to R it gives you "waiting for reply" and goes silent

After I updated the Plugin the problem has gone away and dot completion,"\rh" and "\re"  work as they should.

**Comment by jalvesaq** [comment]
Thanks for the feedback!
