### ISSUE TITLE
Neovim freezes when calling `:Rhelp` with `,rh`

### ISSUE THREAD

**Issue by norival** [jalvesaq/Nvim-R#165]
Hi!

I have neovim freezing when I call `Rhelp` on a function name with `,rh`.

It seems to happen only when the syntax looks like this:
```
aggregate(data.frame(
```
If I put the cursor on `aggregate` and type `,rh`, neovim freezes. It works fine if the line looks like this:
```
aggregate(data.frame
```
I'm using the last version of Nvim-R and neovim 0.1.7.

Thank you!

**Comment by jalvesaq** [comment]
Thanks for reporting the bug!

**Comment by norival** [comment]
Thank you. I updated Nvim-R but the problem remains.

**Comment by jalvesaq** [comment]
Yes, I can see now. I tested only when the problematic line was the last one in the script.

**Comment by jalvesaq** [comment]
Please, check again.

**Comment by norival** [comment]
Yes! It works fine now 👍
Thank you!

**Comment by norival** [comment]
Yes! It works fine now 👍 
Thank you!

**Comment by jalvesaq** [comment]
Perhaps it was not an accident. You might have been tricked by the expression "Close and comment", which is logically flawed. It should be "Comment and close". I have reported this to github people, but they disagree.

**Comment by norival** [comment]
Yes, you are right, it is not very logical.
