### ISSUE TITLE
Feature request: RAction on visual selection

### ISSUE THREAD

**Issue by seb-mueller** [jalvesaq/Nvim-R#166]
In certain cases it would be desirable to perform an RAction (such as the <localleader>rt mapping etc) on a visual selection instead on the current object. 
This has been looked at in #135 , but it in my understanding the implemented solution allows a redefinition of what constitutes an object, which is already really helpful, but still has limitations for certain situation. Similarly, it is possible to submit visual selection with the <localleader>s* mapping, but this doesn't allow for performing actions on the selections.

Would it therefore be possible to allow a workflow in the following fashion:
-visually select a (complicated) object (i.e. the bold section of **iris[,-5]**[,1])
-submit to console with i.e. <localleader>rt which would run str(iris[,-5])

**Comment by jalvesaq** [comment]
Please, check if it is ok now.

**Comment by seb-mueller** [comment]
I've carried out a few test and it seems to work perfectly fine.
Thanks a lot for taking care of this so fast! 

Best wishes,
Sebastian
