### ISSUE TITLE
Issue on Windows OS

### ISSUE THREAD

**Issue by songcai** [jalvesaq/Nvim-R#168]
When opening a R file with the latest Nvim-R installed, the R file does not open in GVim window, and a message shows up in another Gvim window saying "C:\WINDOWS\system32\cmd.exe /c (wmic logicaldisk get  name ^>C:\Users\name\AppData\Local\Temp\VIo2FBF.tmp 2^>^&1)", and the Gvim stuck. I have to manually close the window with the message, then R file is displayed correctly in Gvim.

When I run Vim in terminal (windows command line), same thing happens but with the message shown in the title bar of the terminal.

**Comment by jalvesaq** [comment]
An user has reported that an antivirus blocks GVim when Nvim-R calls the `system()` function. So, if you run any antivirus, could you, please, disable it to see if GVim still hangs?

**Comment by jalvesaq** [comment]
Vim's documentation for `system()` says that the function has been "reported to fail when using a security agent application".

**Comment by songcai** [comment]
It still hangs after I disabled my antivirus program.

**Comment by jalvesaq** [comment]
I added a new option: `Rtools_path` (see https://github.com/jalvesaq/Nvim-R/commit/03c2de2d6541e46b2f0fec9f13dc7fd7921839f4). If you set it, you can avoid this specific call to `system()`. Another call to `system()` can be avoided by setting the value of `R_path`.

**Comment by songcai** [comment]
Many thanks, Jakson. It works like a charm!
