### ISSUE TITLE
Clear R console when line is sent from editor

### ISSUE THREAD

**Issue by insectopalo** [jalvesaq/Nvim-R#170]
Hi,

I'm using Nvim-R plugin with **vim 8.0** and **tmux 1.8**. I have

```vim
let R_in_buffer = 0
let R_applescript = 0
let R_tmux_split = 1
```
in my ~/.vimrc. When I send lines from vim to execute and there is code already typed in the prompt of the R session, the line sent gets appended to the already existent.

**Comment by jalvesaq** [comment]
There is already an option for this: `R_ca_ck`. Did you look at the documentation? Perhaps I should change the name of this option because it is hard to guess that `ca_ck` means "goes to the beginning of the line" and "clear the line from here to the end".
