### ISSUE TITLE
R_LIBS not exported to TMUX R pane.

### ISSUE THREAD

**Issue by joelbrunetti** [jalvesaq/Nvim-R#171]
I install R packages in a hidden folder in my home directory.
I have `export R_LIBS="~/.r_libs"` in my .bashrc file to set the environmental variable so R can find my libraries. 

I have not been having problems with this except for when I start R from within vim in a tmux session (by using \rf).

`$ echo $R_LIBS
 
~/.r_libs'

`$ R`

`> .libPaths()`

Result: Includes the path from R_LIBS.

`$ vim my.R`

`\rf`

Result: R starts in a new windows.

`> .libPaths()`

Result: Includes the path from R_LIBS.

`$ tmux`

`$ echo $R_LIBS

 ~/.r_libs`

`$ R`

`> .libPaths()`

Result: Includes the path from R_LIBS.

`$ vim my.R`

`\rf`

Result: R starts in a tmux pane complaining that there is no package called nvimcom.

`> .libPaths()`

Result: Does not include the path from R_LIBS.

`> Sys.getenv("R_LIBS")

[1] ""`

Result: The R_LIBS environment variable is not set.

Is there some place where R_LIBS gets over written? 
If not, how do I pass R_LIBS to my tmux R session?
Thanks!

**Comment by jalvesaq** [comment]
Would it work if you used `R_LIBS_USER` instead of `R_LIBS`?

**Comment by joelbrunetti** [comment]
Same result.

R launches properly outside of tmux.
Inside of tmux it fails to load R_LIBS_USER but this time instead of being blank R_LIBS_USER is overwritten with "~/R/x86_64-pc-linux-gnu-library/3.3".

**Comment by jalvesaq** [comment]
I can't reproduce the bug running Vim inside Tmux and R in a split pane. `Sys.getenv("R_LIBS_USER")` returns the same value defined in my `~/.bashrc`. However, I noted that the Nvim-R documentation has a tip for `~/.tmux.conf`. It is not necessary in my case, but you could try it:
```
   # If environment variables that you need are not becoming available for R,
   # export them in your ~/.bashrc and uncomment and edit this line:
   # set -g update-environment "R_LIBS_USER R_LIBS R_PAPERSIZE"
```

**Comment by joelbrunetti** [comment]
That fixed things.
Thanks Jakson

For anyone anybody else having problems, please remember to reload your tmux config.

From inside a tmux session:
`Ctrl-b + :`
`source-file ~/.tmux.conf`
