### ISSUE TITLE
Vertical split panes have uneven size

### ISSUE THREAD

**Issue by klmr** [jalvesaq/Nvim-R#173]
Since the last update of NVim-R, the vertical split panes have an extremely uneven size when launching R in a tmux split pane:

![screen shot 2017-03-21 at 11 42 18](https://cloud.githubusercontent.com/assets/38931/24145967/8262a15c-0e2b-11e7-8f63-15d14a2e2c5e.png)

The wider the terminal window, the more pronounced the difference (the R terminal always seem to take up 80 column; and my actual working setup is full-screen, so the difference is extreme). Both `R_rconsole_width` and `R_min_editor_width` are left at the default (80).

Instead, I would like them to be automatically split equally if there’s enough space, as they were before the Nvim-R update.

**Comment by jalvesaq** [comment]
If the width of Vim's window has not changed since its startup, you can set a different value for the R console width in your vimrc based on the width of Vim's window:
```vim
let R_rconsole_width = winwidth(0) / 2
```
Or a conditional value:
```vim
if winwidth(0) > 241
    let R_rconsole_width = 120
else
    let R_rconsole_width = winwidth(0) / 2 - 2
endif 
```

**Comment by klmr** [comment]
Is there a way to do this automatically, and ideally also when resizing? This also worked previously and is useful since I occasionally log into the same tmux session from a laptop with a smaller screen …

**Comment by jalvesaq** [comment]
Yes, you can put in your vimrc (perhaps you don't need the first line):
```vim
let R_rconsole_width = winwidth(0) / 2
autocmd VimResized * let R_rconsole_width = winwidth(0) / 2
```

**Comment by klmr** [comment]
Legendary. Indeed, the first line seems unnecessary.

**Comment by songcai** [comment]
I know this is closed but I just found this post. I got a possibly better solution for this. No need to use winwidth. Just put the following line in the vimrc, and it will give you even vertical or horizontal splits for always:

`autcmd BufNew * wincmd =`

It basically says that, whenever a new buffer is opened, run "CTRL-W =" to even out all windows.
