### ISSUE TITLE
Error when trying to start R

### ISSUE THREAD

**Issue by ravl1084** [jalvesaq/Nvim-R#174]
I open an R script and hit `\rf`. A console is open with `tmux` running on it on my current directory but R is not running. The message on vim is:
```
[Terminal emulator] IBusInputConte...text: no connection to ibus-daemon.
R did not load nvimcom yet
```
R is not running. Does this plugin support running R in a buffer in vim?

**Comment by jalvesaq** [comment]
Could you try Neovim?

**Comment by jalvesaq** [comment]
You can also try a different terminal emulator. See `:h R_term`.

**Comment by jalvesaq** [comment]
I will close this issue due to lack of feedback...
