### ISSUE TITLE
Workspace loads from $HOME, but saves in CWD (Mac OS X)

### ISSUE THREAD

**Issue by qabulin** [jalvesaq/Nvim-R#176]
No matter what directory I'm in, the Nvim-R console loads from the user home ~/.RData workspace.  However, the image that is saved when quitting goes to ~/<current_working_directory>/.RData.  I'm not sure how this is happening, and tried to remove every .RData file from my system to start fresh just in case.  I do not have this problem with just the vanilla R console by itself.

My version outputs: [Vim 8.0 & R-3.3.2](https://gist.github.com/qabulin/194500015ab0d47b2ef951fe1759e2f4)

Demonstration:
1. vanilla R console shows correct workspace object before change:
> getwd()
[1] "/Users/hito/code/r"
> ls()
[1] "cat"

2. Nvim-R pop-out console shows wrong workspace object, and overwrites CWD:
> getwd()
[1] "/Users/hito/code/r"
> ls()
[1] "dog"
> rat <- "lester"
> save.image()

3. vanilla R console shows same CWD workspace, now modified:
> getwd()
[1] "/Users/hito/code/r"
> ls()
[1] "dog" "rat"

4. vanilla R console shows home directory workspace, actually loaded above by Nvim-R:
> getwd()
[1] "/Users/hito"
> ls()
[1] "dog"

**Comment by jalvesaq** [comment]
What is your operating system? I can't reproduce the bug on Linux (Ubuntu 16.10).

**Comment by jalvesaq** [comment]
Please, see:
```vim
:h R_nvim_wd
```

**Comment by qabulin** [comment]
Thanks for the quick follow up!

My operating system: OS X 10.10.5 (14F2109)

Unfortunately, R_vim_wd = 1 does not give me Vim's working directory.  When R_vim_wd = -1, getwd() returns user home as expected, which is more accurate to the workspace behavior I'm experiencing.

After further digging and trying different options, it _seems_ that this may be just be related to the Mac Terminal app I'm using for the R console. There is a setting "New windows open with: Same Working Directory" that is not getting the working directory Vim is in, even when tweaking the R_vim_wd setting.

HOWEVER, if I use a Tmux window for my R console, the workspace current working directory does load and I DO get the correct image.

So for some reason, this appears to be limited only to using Terminal app for R console.

**Comment by jalvesaq** [comment]
Thanks for the feedback! I don't have any Mac to make tests, but we may let issue open because perhaps someone might know how to fix it.
