### ISSUE TITLE
When I try to load R from Vim, I keep getting a shell script rather than the consol

### ISSUE THREAD

**Issue by coralzhang** [jalvesaq/Nvim-R#177]
I installed Nvim-R from Vundle and get the following shell script "openR" popping out when I try to use /rf to call R start. 

```
> #!/bin/sh
> tmux -L NvimR -2 -f "/var/folders/40/xhks3lh54pnf3_sn6vc_q3z8h3p2b4/T/Nvim-R-xz84438/tmux.conf" new-session -s NvimR-322 'TERM=screen-256color NVIMR_TMPDIR=/var/folders/40/xhks3lh54pnf3_sn6vc_q3z8h3p2b4/T/Nvim-R-xz84438 NVIMR_COMPLDIR=/Users/xz84438/.cache/Nvim-R NVIMR_ID=1azOnVP4rK1NUTFD4FGgZg NVIMR_SECRET=n8P9yzDQswWq03BxQE5hA R_DEFAULT_PACKAGES=datasets,utils,grDevices,graphics,stats,methods,nvimcom R'
```

And I get the following warning when I try to send code and come back to vim. 

```
no server running on /private/tmp/tmux-540739940/NvimR 
 did not load nvimcom yet
```

It seems very like Tmux script is not being executed.

**Comment by coralzhang** [comment]
Just in case that you have not figured this out yet, I solved this problem by the following two steps.
I need to first point out that, the openR file invoked contains the command that needs to be executed by bash. It seems that the system is not executing the openR file.
First, make sure that for your OS X you have set up using the terminal to run .sh code by default.
Second, what I did is very ad hoc and might not be general, but works for me. You need to go back to the folder Nvim-R/R and edit the file extern_term.vim so that change all the openR to openR.sh. It sort of makes sense since my operating system does not know how to deal with the file openR.

**Comment by jalvesaq** [comment]
@coralzhang I have just renamed `openR` as `openR.sh`: https://github.com/jalvesaq/Nvim-R/commit/4be306cd36934a63242f98c66f5600a2a6846fc1

**Comment by coralzhang** [comment]
Great. Thanks for the change.

**Comment by songcai** [comment]
coralzhang: 

Please take a look at issue 179 (https://github.com/jalvesaq/Nvim-R/issues/179). Using openR.sh is causing troubles for me and on many other macs as I checked. I guess that it is your personal setting of mac system is causing the trouble, but 177 is not an issue for other mac users in general. Can you confirm that?

**Comment by coralzhang** [comment]
Great! Thanks!

**Comment by songcai** [comment]
coralzhang: it was a question. Could you please tell us if it is caused by your personal setting? Did you change the default bash shell to something else?

"Please take a look at issue 179 (#179). Using openR.sh is causing troubles for me and on many other macs as I checked. I guess that it is your personal setting of mac system is causing the trouble, but 177 is not an issue for other mac users in general. Can you confirm that?"

**Comment by jalvesaq** [comment]
@coralzhang Since you did not answer @songcai question, I assume that assume that @songcai is correct. So, I am renaming `openR.sh` back to `openR`.
