### ISSUE TITLE
Running R in an external terminal emulator with ssh

### ISSUE THREAD

**Issue by mattcbowers** [jalvesaq/Nvim-R#181]
I want to run neovim with R in a separate terminal emulator. Setting :let R_in_buffer = 0 works perfectly when I am at the computer. However, when I ssh in and try to launch R from neovim, R's external terminal opens on the remote computer, not on my local host. How do I get the external terminal to appear on my local host instead of the remote computer?

**Comment by jalvesaq** [comment]
I think that your problem is similar to this: https://github.com/jalvesaq/Nvim-R/issues/180

**Comment by jalvesaq** [comment]
@mattcbowers Did you try to pass either `-X` or `-Y` as arguments to ssh?

**Comment by mattcbowers** [comment]
Yes, I've been using ssh -Y. I tried your suggestions in #180  using the ip_address branch, but the external terminal with R still launches on the remote machine. However, I'm not sure what to grep for in the remote machine's .Rprofile code; both "site" and "wlan0" return empty.What should I grep for?

**Comment by klmr** [comment]
@mattcbowers Try `en0` if you’re using a wired connection. In general, you’re looking for a line containing `inet` that follows whatever internet adapter you are using. Unfortunately this doesn’t necessarily follow in the next line; see my last comment on #180. I can’t help but think that there must be an easier, more reliable way of retrieving the local IP address of the currently active network adapter.

**Comment by jalvesaq** [comment]
@mattcbowers if you have both Neovim and R in the remote machine, it will be much faster to run R with `R_in_buffer=1`. Please, search the web for "ssh X slow".

**Comment by mattcbowers** [comment]
@jalvesaq  good point. I'll stick with `R_in_buffer=1`. Thanks for your help!

**Comment by jalvesaq** [comment]
I am closing the issue because after https://github.com/jalvesaq/Nvim-R/commit/480be07424067f5905011494e2f55c03ee9d5915 it is possible to run local Vim and an external terminal emulator with remote R through ssh, although the configuration is complicated.

**Comment by jalvesaq** [comment]
@mattcbowers and @klmr You may find this useful, if you do not know it yet: http://ryanhafen.com/blog/rmote

**Comment by mattcbowers** [comment]
@jalvesaq  Thanks very much for sharing this!
