### ISSUE TITLE
cannot imap "(" in .vimrc

### ISSUE THREAD

**Issue by mingsu** [jalvesaq/Nvim-R#182]
I want to auto close the "(" to "()" in vim,

with Nvim-R installed, the following `imap` stop working in `*.r`
in .vimrc I put this:
> imap ( ()

However, for "{" and "[" are work as expect, and if I disable `Nvim-R`, all works fine.

Any ideas?

**Comment by mingsu** [comment]
I just found that this can be solved by using ultisnips, 

>snippet ( "auto close ()" iA
($1)
endsnippet

**Comment by jalvesaq** [comment]
I can reproduce the issue only if I put in the vimrc:
```
let R_args_in_stline = 1
```
Please, read the corresponding section of the Nvim-R documentation:
```
:h R_args_in_stline
```

**Comment by jalvesaq** [comment]
I believe the issue will be solved if you put `let R_args_in_stline=0` in your vimrc. Otherwise, please, reopen the issue.

**Comment by mingsu** [comment]
That's it, thank you very much.
