### ISSUE TITLE
error connecting to /tmp/tmux-6066/NvimR (No such file or directory)

### ISSUE THREAD

**Issue by huwenhuo** [jalvesaq/Nvim-R#187]
\rf return status is 1. This error happened when I run r code.

If I run r code again, the system tell me the R is not started.

I install the Nvim-R on the CentOs server and install all related software as user (tmux, R, vim, et al), and connect by ssh. 

Any hint? Thanks.

**Comment by jalvesaq** [comment]
I will add the following to Nvim-R's documentation:

> If you cannot install Neovim in the remote machine, and you can only use Vim
> in the remote machine, then, you will have to run both Vim and R in a Tmux
> session. Please, see |Nvim-R-Tmux|.

In your case, Vim might be trying to open a graphical terminal emulator. The best option is to run R in a Neovim buffer. If you cannot do this, please, configure your vimrc in the remote machine as described in the section *Nvim-R-Tmux*.

**Comment by huwenhuo** [comment]
They works perfectly after I add this:
`   let R_in_buffer = 0
   let R_applescript = 0
   let R_tmux_split = 1
`

**Comment by jalvesaq** [comment]
Thanks for the feedback!
