### ISSUE TITLE
package ‘nvimcom’ in options("defaultPackages") was not found

### ISSUE THREAD

**Issue by DadongZ** [jalvesaq/Nvim-R#188]
Thanks for your great vim plugin!
The Nvim-R plugin has been working great but suddenly today I got some issue with respect to nvimcom. After I open a file through nvim and open R console by `,rf`, I got below message in R console:
```
During startup - Warning messages:
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return
= TRUE,  : there is no package called ‘nvimcom’
2: package ‘nvimcom’ in options("defaultPackages") was not found
```

And I can't sent R script to R console (it shows"Not ready yet" at the bottom).

Any suggestions?

I learned the server has been upgraded today but I am not sure how much this upgrade could affect the Nvim-R. I have rerun the Vunble after that.

**Comment by jalvesaq** [comment]
This is a bug. Nvim-R should update nvimcom after R upgrade. As a workaround, you can delete the file `~/.cache/Nvim-R/nvimcom_info`. When this file is missing Nvim-R installs nvimcom.

**Comment by DadongZ** [comment]
Thanks for your information. It's very helpful.

**Comment by psmits** [comment]
Hi, I was using vim-r for years and recently started a fresh install and I'm having trouble installing Nvim-R.

I download the most recent Nvim-R.vmb, run `:so %` and I get the message that everything is ok.

I then open a *.R file and `\rf` doesn't open an R session and instead just replaces the first letter. If I open an R session and try to load the **nvimcom** package, I get as message that it has not been installed.

 If I open the Nvim-R.vmb vimball and run `:packadd vimball` I get this error message:
>E919: Directory not found in 'packpath': "pack/*/opt/vimball"

I have the most recent version of R installed (3.4.0)

Is there something I'm doing wrong?

**Comment by jalvesaq** [comment]
@psmits Perhaps an error was not displayed or was displayed too quickly. What is the output of
```
:messages
```
What is your version of Vim (or Neovim)?

**Comment by psmits** [comment]
I get nothing with `:messages` except the maintainer information. Similarly, the only message i get from the `:packadd vimball` fail is its fail message.

I'm using Vim 8.0.596.

Thank you!

**Comment by jalvesaq** [comment]
The package `vimball` is enabled by default in Vim. We only need `:packadd vimball` with Neovim. So, the error message in Vim is just saying that `vimball` is not an optional package.

If you are not using Windows, could you please try Neovim?

**Comment by psmits** [comment]
Switching to neovim solved the problem; everything worked perfectly. Thank you so much for this project!

**Comment by DadongZ** [comment]
Hi, I got this message again this morning:

##
During startup - Warning messages:

1: In library(package, lib.loc = lib.loc, character.only = TRUE,
logical.return
= TRUE,  :

there is no package called ‘nvimcom’

2: package ‘nvimcom’ in options("defaultPackages") was not found

##

If I delete the ~/.cache/Nvim-R/nvimcom_info, it shows nvimcom was failed
installed.

> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C
          LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] setwidth_1.0-4 colorout_0.9-9

loaded via a namespace (and not attached):
[1] compiler_3.4.1

Thanks

David

**Comment by DadongZ** [comment]
By the way, I was able to load the package by:
> library("nvimcom", lib.loc="~/R/x86_64-pc-linux-gnu-library/3.4")

Attaching package: ‘nvimcom’

The following object is masked from ‘package:utils’:

    vi

And  ~/.cache/Nvim-R/nvimcom_info:
0.9.27
/home.local/dz33/R/x86_64-pc-linux-gnu-library/3.4/nvimcom
/home.local/dz33/R/x86_64-pc-linux-gnu-library/3.4/nvimcom/bin

Why can't it be found?

**Comment by jalvesaq** [comment]
@DadongZ Could you try Neovim?

**Comment by jalvesaq** [comment]
Did you set the environment variable `R_LIBS_USER` in your `~/.bashrc` (or in your `~/.Rprofile`)? Perhaps this variable has different values when you run R in different ways, for example, if you set the variable in your `~/.profile` but not in your `~/.bashrc`.

**Comment by DadongZ** [comment]
I have replaced a new desktop recently and everything seems great now.
Thanks

**Comment by jalvesaq** [comment]
Other people might still be affected by this issue, but I'm closing it because I believe that the plugin is more robust now and it will work if Vim/Neovim is restarted.
