### ISSUE TITLE
Can't open R console in current terminal emulator

### ISSUE THREAD

**Issue by VitoRudolf** [jalvesaq/Nvim-R#189]
I'm using vim-8.0.586 writing R code.When I type "<localleader>rf" to open R console,it only opens in gnome-terminal in another window, however the terminal emulator which vim is opened is tilda. I want to open R console exactly in vim's window, just like the screenshot in the GitHub project, so I tried to follow the Nvim-R.txt's guide to configure my .vimrc file, but it seems no work. how can I solve this problem?
OS:Ubuntu 16.04, with plasma desktop; 
Terminal: tilda
and my vim configure is based on spf13

**Comment by jalvesaq** [comment]
The screenshot shows Neovim, not Vim. Please, see https://github.com/neovim/neovim/wiki/Installing-Neovim
If you cannot install Neovim, please see Nvim-R documentation:
```
:h R_term
:h Nvim-R-Tmux
```

**Comment by VitoRudolf** [comment]
I see. Thanks!

**Comment by VitoRudolf** [comment]
I see. Thanks a lot !
ps: this plugin is very useful!
