### ISSUE TITLE
Delay with default key binding for RDSendLine

### ISSUE THREAD

**Issue by alefa** [jalvesaq/Nvim-R#192]
First, I'd like to say that I love this plugin and use it almost every day. So thanks for making it! I'm very happy that I have all the functionality of an R IDE available in Vim.

Here's a small issue I noticed:
When using the default key binding for sending the current line to R and moving the cursor down (command RDSendLine, \<localleader\>d), there is a delay before the command is executed, i.e. execution is slower than for other key bindings such as \<localleader\>l for RSendLine. I think the reason for that is that Vim waits for a second key press (the waiting time is set by 'timeout' and 'ttimeout' in Vim). I noticed in the documentation that \<localleader\>dt is bound to executing 'dput()'. Could it be that that is responsible for the delay? For now, I've remapped RDSendLine to \<localleader\>dd. With this binding, there is no delay, but I would prefer to use a single letter because it's faster to type.
I'm using Neovim 0.1.7 on Debian Stretch, but the same delay also occurred on Vim 8, which I was using before switching to Neovim.

**Comment by jalvesaq** [comment]
Yes, `<LocalLeader>dt` is the problem. One solution is to change it to `<LocalLeader>td`. Then, to keep the consistency, I would also have to change `\pt` to `\tp`.

**Comment by alefa** [comment]
Sounds good to me. It would keep the key bindings mnemonic. So 't' stands for 'new tab', 'd' for 'dput', 'p' for 'print'.
