### ISSUE TITLE
Nvim-R doesn't recognize HEAD version of Tmux

### ISSUE THREAD

**Issue by thalesmello** [jalvesaq/Nvim-R#193]
Hello.

I use the development version of Tmux, which outputs the following in `tmux -V`:

```
tmux master
```

But, when I open an Rmd file with `vim foo.Rmd`:

```
Nvim-R requires Tmux >= 1.8 [Press <Enter> to continue]
```

**Comment by jalvesaq** [comment]
I believe it is fixed now (but I did not test).

**Comment by jalvesaq** [comment]
I'm closing the issue. Please, reopen it if it isn't fixed.
