### ISSUE TITLE
nvimcom is always loaded, regardless of how R is launched

### ISSUE THREAD

**Issue by klmr** [jalvesaq/Nvim-R#194]
I’ve occasionally noticed that when launching R via the command line, `nvimcom` has nevertheless been loaded and attached. This is bad for two reasons:

* It’s inefficient: I use `Rscript` a lot for R scripts that are launched a lot, and startup time matters. Loading unnecessary packages should be minimised.
* It breaks stuff; for instance, nvimcom appears to set `option('pager')` to a function that tries to communicate with Vim. But since no Vim instance Vim is loaded, this fails.

I’m a bit at a loss what’s happening here: I am running iTerm2 on macOS 10.12.4. Opening new windows or tabs *should* create a completely new terminal session, yet for some reason the environment variable `R_DEFAULT_PACKAGES` (containing `nvimcom`) is inherited, even though it’s not set in any config file.

Closing iTerm2 completely and re-opening solves the problem, but isn’t an appealing solution.

I initially thought this was only happening if Vim was at least loaded *somewhere*, i.e. in an unassociated terminal session but it turns out that even if there’s *no* Vim running on the system (as verified by `ps x | grep vim`), nvimcom is still loaded.

**Comment by jalvesaq** [comment]
On lInux, I can reproduce the issue only when running R in a Tmux split pane, and only if the other R is inside Tmux. The next commit is going fix the issue on Linux.

**Comment by klmr** [comment]
Thanks. I’ll take your word for it for now, since I have found the issue hard to reproduce. Let’s see.

**Comment by jalvesaq** [comment]
The environment variable will still be set in Tmux during the short interval between the moments when the command `\rf` is issued and Vim receives the message that nvimcom is started.
