### ISSUE TITLE
Navigation and typing slow down significantly when there are sizeable objects in memory

### ISSUE THREAD

**Issue by sheriferson** [jalvesaq/Nvim-R#199]
I run into an issue where there is very noticeable lag in navigation and typing in a .R file when Nvim-R is running and I have a dataframe of small to medium size (~30MB) in memory. The steps are more or less like this:

1. `vim myfile.R` (aliased to use Neovim)
2. `\rf` to start R (local leader is \\)
3. Run a few lines which include reading in a dataframe.
  `object.size(mydf) %>% format(unit = 'MB')` about 31.2 Mb, although I don't know if that's relevant.
4. At this point I have only executed a few lines and navigation in the file is significantly slowed.

I think the slowness is much worse when there are larger objects in memory.

Is this something that anyone else has noticed? Is it something with larger files/objects, or perhaps something with my setup? I'm using the latest version of Nvim-R.

I'm happy to provide any other information that might help figure this out.

**Comment by jalvesaq** [comment]
I have never seen any slowness in either Vim or Neovim due to large datasets (>900 MB and larger) being loaded in R. I only see slowness when R uses more memory than the available RAM. But, then, the whole system becomes sluggish.

**Comment by sheriferson** [comment]
Okay, thanks, that's good to know. Probably something in my vim plugin setup.
I'll close this for now.

**Comment by sheriferson** [comment]
I wanted to add a note in case other people run into this in the future.

It took a lot of trial and error, but I think I finally found the culprit. For me, it was the [indentLine](https://github.com/Yggdroot/indentLine) plugin. I'm not sure why the slow down seemed correlated with large objects being loaded into R, and I don't know why it didn't happen when editing large files that had a lot of indents when Nvim-R wasn't running. I don't understand vim/Neovim's drawing or processing loops well enough to have an educated guess. What I can confirm is that after disabling it, navigation and typing in an R file with Nvim-R running is dramatically faster.

**Comment by jalvesaq** [comment]
Did you open the Object Browser (`<LocalLeader>ro`)? The contents of the Object Browser is changed by R each time that either a new object is created or an existing object is changed. I did not install the indentLine plugin, by this line might the reason of the slowness: https://github.com/Yggdroot/indentLine/blob/master/after/plugin/indentLine.vim#L336
So, what happens if you put in your vimrc
```
let g:indentLine_newVersion = 1
```
?

**Comment by sheriferson** [comment]
The slowness would happen with or without the object browser being on.
I tried the setting you mentioned above and the lag was still immense. It gets to a point where holding `j` key down for a moment wouldn't show the cursor moving down each line fast, instead Neovim would freeze and after a second or two the cursor would just jump 10-20 lines down. Imagine same lag with all other motions.

Disabling indentLine makes the lag almost go away entirely.
