### ISSUE TITLE
Use Exuberant Ctags format for tags generated by :RBuildTags

### ISSUE THREAD

**Issue by alefa** [jalvesaq/Nvim-R#201]
Today I noticed that jumping to tags with fzf-vim's `:Tags` command doesn't work when the tags file has been generated by NVim-R's `:RBuildTags` command. Specifically, Vim jumps into the right file, but not to the right line. On the other hand, the `:Tags` command works fine in my C++ projects where I generate the tags file using `ctags -R .`. Inquiring further, I found that the relevant function in fzf-vim searches for a string that ends with `;"` to determine the line to jump to. The tagaddress in the files generated by exuberant ctags has the following format (see also the documentation [here](http://ctags.sourceforge.net/FORMAT)):

    /^search string$/;" optional comment

By contrast, the tagaddress in the tags file generated by `:RBuildTags` has this format:

    /^search string$

Would it be possible to change the `etags2ctags` function so that it appends `$/;"` to the end of each search string instead of just the dollar sign? I.e. simply change line 56 of etags2ctags.R to
```r
curaddr <- paste("/^", curaddr, "$/;"", sep = "")
```
Vim's inbuilt :tag function works correctly with the output of `:RBuildTags`, but according to the ctags documentation linked above the search string is supposed to be followed by a slash even in the old tags format without the semicolon and double-quote. According to my testing, just adding a slash at the end of each line is enough to jump to the correct line with `:Tags`.

**Comment by jalvesaq** [comment]
Thanks for reporting the bug!

**Comment by alefa** [comment]
Thanks a lot for fixing this so quickly!
