### ISSUE TITLE
Error detected while loading Rscript

### ISSUE THREAD

**Issue by tpthian** [jalvesaq/Nvim-R#202]
Hi Jackson,

I've just `source %` the vimball downloaded from `http://www.vim.org/scripts/script.php?script_id=2628`
What I did was
```
    vim Nvim-R.vmb
    :source %
```
Then when I tried to load an Rscript, error image appeared like this
<img width="682" alt="screen shot 2017-06-10 at 22 33 53" src="https://user-images.githubusercontent.com/25971745/27004112-e64ed2b6-4e2d-11e7-936b-f2f2c0788dad.png">

Would you please help explained this? I don't know where to put this so I put it in issue. If there's another place, more appropriate than this, then please point me to that address. I'll be more than happy to move it there.

Thank you very much in advance.

Gabe.

**Comment by jalvesaq** [comment]
Did you press the `Enter` key many times while sourcing the vimball? Because Nvim-R has many files, if you do not  press the `Enter` key, the installation will be incomplete.

**Comment by tpthian** [comment]
I did what you said and the error has gone. But now it appears one line of error 
`tmux executable not found [Press <Enter> to continue]`

How do I remove it?

**Comment by jalvesaq** [comment]
You have two options:
  - Use Neovim instead of Vim because neovim does not require Tmux.
  - Install Tmux.

**Comment by tpthian** [comment]
Thank you a ton @jalvesaq .
