### ISSUE TITLE
vim-airline and R_args_in_stline

### ISSUE THREAD

**Issue by zippeurfou** [jalvesaq/Nvim-R#203]
This ticket is more a feature request than anything else. I might do a PR for it if I get the time.
The doc states correctly that you can't do `let R_args_in_stline = 1` with a plugin that edit the statusline.
I was wondering how hard it would be to tweak it to make it compatible with vim-airline that is used widely.
An option would be to have a new variable like `R_store_args_in_var` that can take 0 or 1 and if it is one then you can access the content of what would normaly be added in the status line in a new variable such as `R_args_output`.
Doing like that would not break the current behavior while allowing for powerline to display it.
The way I understand is that the content should be what is inside [let s:sttl_str](https://github.com/jalvesaq/Nvim-R/blob/d658e26cb8233b0ca99e54ae2892f75ed3e5839d/R/common_global.vim#L2456
)
One thing that I am not sure is how to tell powerline to change it if something is in the variable otherwise don't do anything.

**Comment by jalvesaq** [comment]
Now, you can experiment with the options `R_set_sttline_cmd` and `R_restore_sttline_cmd`.

**Comment by jalvesaq** [comment]
The display of arguments in the status line still is not perfect because it does not support nested functions properly, but I am closing the issue because at least the status line created by vim-airline is restored.
