### ISSUE TITLE
Data doesn't display in excel when opened via R_csv_app

### ISSUE THREAD

**Issue by 001ben** [jalvesaq/Nvim-R#204]
### Description
When using the view data frame feature with R_csv_app set to excel, the data displays in a single column.

### System Setup:
- neovim 0.2.0
- latest Nvim-R
- OS X El Capitan (10.11.6)

### Config setup:
Excel is launched via a custom shell script that's available on the system path set up as below:
```bash
# saved in script named "open-with-excel" and available on path
open -a "Microsoft Excel" $1
```
Then in init.vim:
```vim
let g:R_csv_app = "open-with-excel"
```

**Comment by 001ben** [comment]
Did some investigation and it appears that this is caused because view data frame always exports the data frame using tab as a delimiter and not comma, regardless of if viewing in an external application or not.

See https://github.com/jalvesaq/Nvim-R/blob/93da031/R/nvimcom/R/nvimcom.R#L123-L124

**Comment by jalvesaq** [comment]
While I do not test whether your pull request works in a Portuguese locale, you might add this to your script:
```
sed -i -e "s/\t/,/g" "$1"
```
This workaround will not work if your data include text with commas.

**Comment by 001ben** [comment]
Sadly i deal with free text entry data fairly often, so it regularly includes tabs/commas that need quoting

**Comment by jalvesaq** [comment]
I added a new option: `R_csv_delim`. If it is not defined, tab characters will be used as field delimiters, but of course it would be better if I could guess the correct field delimiter based on the values of `R_csv_app`, operating system and locale.
