### ISSUE TITLE
Change runtimepath instructions for nvim 0.1

### ISSUE THREAD

**Issue by FvD** [jalvesaq/Nvim-R#21]
In nvim 0.1 there is no longer an .nvimrc file, but things have moved to ~/.config/nvim/init.vim. So the instruction for the runtimepath in the `readme.md` file would read:

    set runtimepath+=~/NVim-R, ~/.config/nvim, $VIMRUNTIME, ~/.config/nvim/after

However, I checked, and i have never set the runtimepath and worked with Nvim-R without issue. There is no mention in the documentation of what runtimepath would actually do, and what would go in the ~/NVim-R folder once set. 

Could you explain the need to set runtimepath a little bit further?

**Comment by jalvesaq** [comment]
Thanks! And, please, see the README now.

**Comment by FvD** [comment]
Thanks, the update covers my question.
