### ISSUE TITLE
R session does not start on os X

### ISSUE THREAD

**Issue by ilyakopy** [jalvesaq/Nvim-R#212]
Hi,

**System Setup**

- Vim 8.0.647
- OS X sierra
- Iterm 2

I am running mac OS X Sierra and I cannot invoke the R session from Nvim-R. When I attempt to start the R session I get the following message in Vim:

`:!xterm -T 'R' -e funnel.pl ~/.r-pipe "R && echo -e 'Interpreter has finished. Exiting. Goodbye.\n'"&`

When I exit from VIM I see the following:
`Press ENTER or type command to continue
/bin/bash: xterm: command not found`

Is there a setting i can set in .vimrc to fix this?

Thanks

**Comment by jalvesaq** [comment]
How did you install Nvim-R? The `funnel.pl` script is no longer used. It was replaced in 2009.

**Comment by ilyakopy** [comment]
I used Vundle 
`Plugin 'jalvesaq/Nvim-R'`

**Comment by jalvesaq** [comment]
You could try deleting from your vimrc all Nvim-R specific configuration. Probably you have set `R_term_cmd` in the wrong way.

**Comment by ilyakopy** [comment]
I got it working. It was a conflict with old files in the vim/polyglot package. Thanks!

**Comment by jalvesaq** [comment]
Thanks for the feedback!
