### ISSUE TITLE
Nvim-R can't be configured to address a different output directory of `latexmk`

### ISSUE THREAD

**Issue by nichtleiter** [jalvesaq/Nvim-R#214]
Hi all,

I configured `latexmk` so that every output file generated by latex is to be written in a subdirectory of the current working directory.

The corresponding line in my `.latexmkrc` is
```
$out_dir = "compiled";
```

There is currently no way to tell `Nvim-R` that the generated output files are in a specific subdirectory rather than the working directory.

It would be great if a future version of `Nvim-R` addresses this issue.

Best regards

**Comment by jalvesaq** [comment]
Thanks for your suggestion. I'm going to commit the fix now.

**Comment by nichtleiter** [comment]
Thanks a lot for adding the support! Much appreciated
