### ISSUE TITLE
RBuildTags deletes the generated tags file on case insensitive FS

### ISSUE THREAD

**Issue by siddharthab** [jalvesaq/Nvim-R#217]
OS X by default has a case insensitive file system.

`:RBuildTags` generates this command which assumes a case sensitive FS:
`rtags(ofile = "TAGS"); etags2ctags("TAGS", "tags"); unlink("TAGS")`.

Case insensitivity of the FS can be tested by:
```
touch aFILE
rm afile
ls aFILE
```

**Comment by jalvesaq** [comment]
Thanks for reporting the issue!
