### ISSUE TITLE
Files not found when using rstudio/blogdown

### ISSUE THREAD

**Issue by niklaas** [jalvesaq/Nvim-R#219]
For reference: rstudio/blogdown#63 . Nvim-R seems to mingle with `setwd()`, so rstudio/blogdown misses files. Do you have an idea what the problem might be here?

**Comment by niklaas** [comment]
I know about `R_nvim_wd`. I have set `let R_nvim_wd = 1` in my `~/.vimrc`. To clarify the issue, in the following you can see two R sessions. The first one is within the session spawned by Nvim-R, the second one is spawned by simply running `R` on the command line.

```
> getwd()
[1] "/home/niklaas/Documents/notebook"
> blogdown::build_site()
Error in tools::file_path_as_absolute(input) :
  file 'blogroll.Rmd' does not exist
Calls: local ... eval -> <Anonymous> -> setwd -> dirname -> <Anonymous>
In addition: Warning message:
In normalizePath(path, winslash = winslash, mustWork = mustWork) :
  path[1]="blogroll.Rmd": No such file or directory
Execution halted
Error in render_page(f) : Failed to render 'blogroll.Rmd'
```

```
> getwd()
[1] "/home/niklaas/Documents/notebook"
> blogdown::build_site()
Started building sites ...
Built site for language en:
0 of 1 draft rendered
0 future content
0 expired content
4 regular pages created
16 other pages created
5 non-page files copied
7 paginator pages created
4 tags created
total in 15 ms
```

As you can see `getwd()` is identical on both occasions, however running `blogdown::build_site()` only fails when using Nvim-R. Somehow Nvim-R messes with the current working directory..?

That said, I just figured out that `let R_nvim_wd = -1` i.e., preventing Nvim-R to set the working directory in any way, solves the issue -- still wondering why the same `getwd()` works in one but not in another case.

**Comment by jalvesaq** [comment]
Thanks for your feedback!
Nvim-R needs to change the working directory, but I don't remember what bug the option R_nvim_wd is avoiding (I have begun the development of Vim-R-plugin in 2009).

**Comment by niklaas** [comment]
What do you mean by "Nvim-R needs to change the working directory"? So I mess up functionality with `let R_nvim_wd = -1`?

**Comment by jalvesaq** [comment]
The working directory does not affect Nvim-R, but perhaps a few people will have to write the full path of files in their scripts when running commands that either read or write files. This might be the only "bug".

**Comment by niklaas** [comment]
Seems that this was an issue on rstudio/blogdown#63 's side. Got fixed. Thanks again for your help!
