### ISSUE TITLE
Key bindings

### ISSUE THREAD

**Issue by phmarek** [jalvesaq/Nvim-R#22]
Hi,

I see a lot of (functional!, not source) overlap between this project and `slimv`. Both make it possible to run another REPL process, and to exchange information between them. (In fact, I'm currently using `vim`, `slimv`, and `swank-r` for my R needs.)

Because of this overlap it would be great if both projects could be using the same keybindings; what is called "Send file" (`\aa`) here is "Evaluate buffer" (`,eb`) in `slimv`, and so on.

**Comment by jalvesaq** [comment]
I did not know about them. Thanks for the news! How can I see R running inside a Vim's buffer through slimv? I already installed slimv. What should I do now? I did not find instructions on how to install swank-r for Vim. 

You can change all Nvim-R key bindings. Please, see `:h Nvim-R-key-bindings`.

**Comment by phmarek** [comment]
Hi, thanks for the quick answer!


Well, I'm using this `~/.vim/after/syntax/r.vim`:
```
let g:swank_port=4009
let g:slimv_swank_cmd='!nohup setsid /usr/bin/xterm -e R -e "X11(); while (1) { swank() }" > /tmp/swankr.txt 2>&1 &'

let g:slimv_simple_compl=1

setlocal iskeyword-=*
setlocal iskeyword-==
setlocal iskeyword-=[
setlocal iskeyword-=]

:nnoremap <f2> "ryap"r:call SlimvEvalRegion()<CR>
:nnoremap <f3> "syap"s:call SlimvEvalSelection("t", getreg("r"))<CR>
```

along with the R parts from https://github.com/phmarek/swankr.


Yes, I know that I can change all key bindings (and have done so for too many plugins already) - but having some way to get them compatible out-of-the-box via a single `:let g:...=` would be nice, too!

**Comment by jalvesaq** [comment]
Today, I had time to look at swank. It is interesting to see R running in a Vim's buffer, but it has some bugs, e.g., when I pressed the backspace key there was an error. Neovim terminal is definitively better.

Regarding your question, there is no way of changing the key bindings other than mapping the `<Plug>`s one by one because the default key bindings are hard-coded in `R/common_global.vim` and `ftplugin/*.vim`. And I cannot change the default key bindings because they are in use for years now.

**Comment by jalvesaq** [comment]
I am closing the issue. If someone has a better solution than mapping the `<Plug>`s, please, either reopen the issue or make a pull request.

**Comment by phmarek** [comment]
Sorry for not responding earlier; I'd have hoped for a 2nd set of bindings in that script, that are used via simply changing a single configuration parameter - like `:set g:R_use_slimv_compatible_keys=1`...

**Comment by jalvesaq** [comment]
I could accept a pull request for this if the other software were highly popular. I guess this is not the case of slimv. So, in my opinion your demand is very specific, and in this case I think it would be more appropriate if  someone could write a Vim script to be listed as part of `R_source`. Please, see:
```vim
:h R_source
```

**Comment by mdlerch** [comment]
@phmarek , are you aware that you can map to your own liking in your own config?  You don't need to use the defaults?

```
ftplugin/r.vim

map <buffer> ,eb <Plug>RSendFile
```

etc...

**Comment by phmarek** [comment]
@mdlerch, yes, I know.

But I guess there'll be quite a few people using slimv already - and why should each of them configure the keys on her own?
