### ISSUE TITLE
cygwin + tmux + vim + R

### ISSUE THREAD

**Issue by edult** [jalvesaq/Nvim-R#224]
I am not able to get cygwin+ tmux + vim +  R setup working. I start tmux, than vim with an r file and type \rf  I get an error message /tmp/Nvim-R/libpaths Error in file, cannot open connection, calls:sink -> file

I am not sure what is going wrong. Is there anything wrong with my setup?

**Comment by jalvesaq** [comment]
I am sorry but I don't use cygwin. Perhaps someone else can help you.

**Comment by erw7** [comment]
@edult  I think you are using R for windows. Please install R from Cygwin setup(setup-x86.exe or setup-x86_64.exe).

**Comment by jalvesaq** [comment]
@edult : Does @erw7 suggestion works in your case?

**Comment by jalvesaq** [comment]
Vim >= 8.0.0946 has a built-in terminal emulator and does not need Tmux to run R. Neovim also does not need Tmux.

**Comment by jalvesaq** [comment]
@edult I installed Cygwin and tested Nvim-R.

I had to install some devel libraries to get nvimcom built. For each message of "-lxxx" not be found, I had to install the corresponding libxxx-devel package. Then, I had to fix an encoding issue (see https://github.com/jalvesaq/Nvim-R/commit/5de878a5bcfe990458493ba46c88bdcb28b0e10e).

Then, R ran just fine in a Vim buffer. I even installed the colorout package.

To run R in an external terminal emulator (after installing tmux, lxterminal and xorg-server), I had to call Vim with the DISPLAY environment variable manually set:
```
startxwin &
DISPLAY=:0.0 vim example.R
```
Certainly, this is not the better way of running the X server. Please, see: https://x.cygwin.com/docs/ug/using.html

Sending code to R through Tmux is slow. It is better to run R in Vim's built in terminal.
