### ISSUE TITLE
Problem with parentheses

### ISSUE THREAD

**Issue by mchiapello** [jalvesaq/Nvim-R#225]
When I insert a **(**, function arguments are displayed in Vim's status, but no parentheses are insert in the main document. Basically I am not anymore able to insert parentheses in my R scripts.

Today I installed vim-autocomplete, but then I removed it. The problem is not solved. I also update both Nvim-R and R-Vim-runtime.

**Comment by jalvesaq** [comment]
Please, put this in your vimrc:
```
let R_args_in_stline = 0
```

**Comment by mchiapello** [comment]
I tried it, but it did not solve the problem. Function arguments are not displayed in Vim's status and no parentheses are inserted.

**Comment by jalvesaq** [comment]
What is your version of Vim?

**Comment by mchiapello** [comment]
version 8.0.983

I just realised one thing. If I create a new file, I can enter the parentheses. If I open one of my *.R files I can not. Do this make sense?

**Comment by jalvesaq** [comment]
Perhaps an autocommand somewhere. What happens if you disable all plugins, but Nvim-R and R-Vim-runtime?

**Comment by mchiapello** [comment]
If I open one of my scripts in TextWrangler, copy it and paste it back into the R file and save it, I can insert parentheses again.

**Comment by mchiapello** [comment]
If I disable all plugins, but not Nvim-R and R-Vim-runtime, the problem is still there

**Comment by jalvesaq** [comment]
I am sorry, but I cannot reproduce the issue. Perhaps someone else will be able to help you.

**Comment by jalvesaq** [comment]
@mchiapello did you figure out what was causing the problem?

**Comment by mchiapello** [comment]
Unfortunately no,  but I realized it is not software depend,  but file dependent. When I create a new R script everything works fine,  while when I open some specific files,  I am not able to insert the parentheses in insert mode. It works if I copy and paste them in normal mode.Inviato con l'app di SolMail --------- Original Message ---------
From: Jakson Alves de Aquino 
To: jalvesaq/Nvim-R 
Date: Sun Nov 19 11:53:17 GMT+00:00 2017
Subject: Re: [jalvesaq/Nvim-R] Problem with parentheses (#225)

@mchiapello did you figure out what was causing the problem?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jalvesaq/Nvim-R","title":"jalvesaq/Nvim-R","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jalvesaq/Nvim-R"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jalvesaq in #225: @mchiapello did you figure out what was causing the problem?"}],"action":{"name":"View Issue","url":"https://github.com/jalvesaq/Nvim-R/issues/225#issuecomment-345510844"}}}

**Comment by jalvesaq** [comment]
Arguments are no longer shown in the status bar. So, more than three years later, I guess this issue is no longer relevant.
