### ISSUE TITLE
curwin error in MacVim

### ISSUE THREAD

**Issue by jesellers** [jalvesaq/Nvim-R#226]
When using Nvim-R with MacVim, upon loading via \rf, it displays this message:

Error detected while processing function StartR[118]..StartR_InBuffer: 
E475: Invalid argument: curwin

**Comment by jalvesaq** [comment]
What is your Vim version? The `curwin` argument was added in Vim 8.0.0910.

**Comment by jesellers** [comment]
The version in MacVim says "8.0.891". It's working in terminal, which is using  8.0.0997.

**Comment by jalvesaq** [comment]
I added a check for patch 0910: https://github.com/jalvesaq/Nvim-R/commit/410edda093346c186600c2b22d22c40bc08559c6

**Comment by jesellers** [comment]
That works. Thanks!
