### ISSUE TITLE
Support bracketed paste

### ISSUE THREAD

**Issue by randy3k** [jalvesaq/Nvim-R#227]
Regular R with readline 7.0 and [rice](https://github.com/randy3k/rice) support bracketed paste mode for pasting multiple lines. It would be nice for NVim-R to also support it. Basically, you just need to wrap the selected code by the sequences `\e[200~` and `\e[201~`.

**Comment by jalvesaq** [comment]
Would this works with large amounts of text (more than 4 thousands characters)? Could you do a pull request for this?

**Comment by randy3k** [comment]
I think the [console buffer](https://github.com/wch/r-source/blob/cbac1190b03876aa774ded24c638c1ddb36206e2/src/include/Defn.h#L1035) size is limited by R. Bracketed paste mode does not fix it. But It could be used to save history in blocks.

![aug-29-2017 22-13-15](https://user-images.githubusercontent.com/1690993/29852296-4a383dd6-8d07-11e7-88e0-d8ae54203992.gif)

step to reproduce:
- type `\e[200~`
- paste (note that nothing will happen)
- type `\e[201~`

**Comment by randy3k** [comment]
I can confirm that vanilla R + readline 7.0 doesn't work with text > 4096 chars. For the `rice` console, I will make it work with >4000 chars soon.

**Comment by randy3k** [comment]
FYI, `rice` is now working correctly for a line > 4096 chars.

<img width="1380" alt="screen shot 2017-09-04 at 1 01 25 am" src="https://user-images.githubusercontent.com/1690993/30012292-9d3c0e82-910c-11e7-9d56-cbc20774eed1.png">

**Comment by jalvesaq** [comment]
@randy3k I added a branch with support for bracketed paste: https://github.com/jalvesaq/Nvim-R/tree/bracketed
Nvim-R will use bracketed paste instead of `source()` if you put this in your vimrc:
```vim
let R_source_args = "bracketed paste"
```
It works if rice is running in a Tmux pane, but not in either Vim or Neovim builtin terminal.

**Comment by randy3k** [comment]
It actually also works well with neovim terminal with

```
let R_source_args = "bracketed paste"
let R_app = "rice"
let R_cmd = "R"
```

<img width="644" alt="screen shot 2017-09-04 at 10 16 42 pm" src="https://user-images.githubusercontent.com/1690993/30042338-bb87f16e-91be-11e7-8420-a17f8f92f866.png">

**Comment by randy3k** [comment]
By the way, thanks for the quick implementation.
It is working perfectly now.

**Comment by jalvesaq** [comment]
I copied the changes to the master branch, but I did not document it because it might not work in all circumstances (GVim + Rgui on Windows, MacVim + Rapp on OS X, etc).

**Comment by randy3k** [comment]
I think you just need to stress that it is intended for terminal R console and R GUI users should not enable it.

**Comment by jalvesaq** [comment]
It is not working well with race on either Vim or Neovim built-in terminal on Linux Ubuntu: the output does not appear. And I prefer to use `source()` because since the code is already in the script I prefer a cleaner R Console. If I put the feature in the documentation people will expect it to work well and will fill bug reports.

**Comment by randy3k** [comment]
I agree and I actually also prefer a cleaner console using `source`. As an alternative to change the default behavior, may be we can bind the `\l` key in visual mode when there are more than one line selected.

**Comment by randy3k** [comment]
And also `\d`

**Comment by jalvesaq** [comment]
I never use `\ss`, `\l` or `\d` because I bind everything to the space bar:
```vim
vmap <Space> <Plug>RDSendSelection
nmap <Space> <Plug>RDSendLine
inoremap <C-Space> <C-x><C-o>
```

**Comment by randy3k** [comment]
May be we just prepare a `<Plug>RDSendSelectionBracketed` and let users to bind it at their wills.

**Comment by jalvesaq** [comment]
I am sorry, but I already have spent more time than I should in a feature that I will never use.

**Comment by randy3k** [comment]
No problem. Thank you anyway.

**Comment by randy3k** [comment]
Just want to let you know that I find no problem running `rice` with Nvim-R on ubuntu too...
