### ISSUE TITLE
Problems quitting the R console

### ISSUE THREAD

**Issue by LouisAsh** [jalvesaq/Nvim-R#228]
I notice two issues related to quitting the R console, under gVim:

1) whenever I try to close the gVim window, the R console prevents me from doing so. I always have to go to the R console, manually quit by entering "q()" and only then I can close gVim. Is there a workaround this?

2) whenever I close the R console, I can't open a new one unless I close gVim and open gVim again. Is there a solution to that?

Thanks a lot!

PS: if you prefer, I can split the two above into two issues tickets

**Comment by jranke** [comment]
Did you try localleader rq? This works nicely for me under Win7, with gvim (R in a separate window).

**Comment by jalvesaq** [comment]
1. This is a Vim feature (or bug).
2. You should start R with `\rf` and quit it with `\rq`.

**Comment by LouisAsh** [comment]
Thank you both. Indeed `\rq` solves the second issue. The only problem is that `\rq` still requires one to focus on the R console and then close it manually with `:q`. Is there a way to make it so that `\rq` automatically closes the inner windows where the console being ended was?

**Comment by jalvesaq** [comment]
Should be fixed now: https://github.com/jalvesaq/Nvim-R/commit/30819d4efa5649f9cdb56dc2cd65e0b0aead98ab

**Comment by LouisAsh** [comment]
Works like a charm now. Thanks!
