### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by scheike** [jalvesaq/Nvim-R#23]
Dear Nvim-R.

I am a vim-r-plugin user and thought I would check out the Nvim-R. 
I am unfortunately somewhat stuck, after having installed neovim (easy), and vimballed
the nvim-r ?  It would extremely helpful with some more installation details on how to
do the next couple of steps. 

best

**Comment by jalvesaq** [comment]
Thanks for writing!
I added details to http://www.lepem.ufc.br/jaa/NvimR.html
Is the new information enough?

**Comment by scheike** [comment]
Well I got that far, the basic vimball installation seems to work fine, but when after tmux, and nvim, open an .R file and try to open R with rf  nothing happens at all. 

My .vimrc file is one that normally works fine with the old vim-r-plugin

best and thanks

**Comment by jalvesaq** [comment]
Did you create nvim and vim.init links?
```sh
cd ~/
ln -s .vim .config/nvim
ln -s .vimrc .config/nvim/init.vim
```

**Comment by scheike** [comment]
Yes, I had these files set-up. I have nvimcom installed as well and tmux going. Other installations seems to work in nvim, for example yankring, bufexplorer and vim-signature. There are no messages when I try messages ?   I realize this is not much to go on, but not sure what I could check further

thanks again for your time

**Comment by scheike** [comment]
think the issue might be that 

syntax on 

 is not working in nvim due to due to the way I have installed nvim

E484: Can't open file /usr/local/share/nvim/syntax/syntax.vim

**Comment by scheike** [comment]
This was indeed the problem, now I things are working just nicely

thanks

**Comment by jalvesaq** [comment]
Thanks for the feedback!
