### ISSUE TITLE
R did not load nvimcom yet

### ISSUE THREAD

**Issue by lyashevska** [jalvesaq/Nvim-R#231]
Similarly to issue #59 I experience problems with nvimcom.

I  installed Nvim-R using Vundle.
R version: 3.3.2
Platform: x86_64-pc-linux-gnu (64-bit)
vim: 8.0

I get message: 
During startup - Warning messages:
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘nvimcom’
2: package ‘nvimcom’ in options("defaultPackages") was not found 
> R_DEFAULT_PACKAGES
Error: object 'R_DEFAULT_PACKAGES' not found

:messages 
R did not load nvimcom yet

Thanks

**Comment by jalvesaq** [comment]
`R_DEFAULT_PACKAGES` is an environment variable, not an R object. Hence, the message that the "object R_DEFAULT_PACKAGES was not found" is very strange. Perhaps, there is something wrong in your .Rprofile.

**Comment by lyashevska** [comment]
.RProfile is empty. 
Unless something is wrong with Rprofile.site?

**Comment by jalvesaq** [comment]
I am sorry, but I do not know what might be causing the problem.

**Comment by lyashevska** [comment]
ok, thank you. Can't I install nvimcom manually as it used to be?

**Comment by jalvesaq** [comment]
Yes, you can. Please, do in a terminal emulator:
```
R CMD build /path/to/Nvim-R/R/nvimcom
R CMD INSTALL nvimcom_0.9-34.tar.gz
```
Of course, replace `/path/to/` with the appropriate path.

**Comment by lyashevska** [comment]
That solved nvimcom problem, thank you.
Minor issue: R window appears as a separate window, and not as a split. Everything is working though.
Tmux is installed. Version 2.1
What could cause it?

**Comment by jalvesaq** [comment]
The recommended way of running R now is in a Neovim buffer. Then, Tmux is not required. If users really want to run R in a Tmux split pane, they have to find the section Nvim-R-Tmux in the documentation to learn that they need to put in their vimrc:

```vim
   let R_in_buffer = 0
   let R_applescript = 0
   let R_tmux_split = 1
```

**Comment by lyashevska** [comment]
that' s great, thank you
