### ISSUE TITLE
close term

### ISSUE THREAD

**Issue by blayz3r** [jalvesaq/Nvim-R#232]
I am getting the following messages when I close R using <leader>rq.

_Error detected while processing WinLeave Auto commands for "*":
E16: Invalid range: call <SID>WinLeaveHandler()
Error detected while processing BufWinLeave Auto commands for "*":
E16: Invalid range: call eclim#common#buffers#TabLastOpenIn()
E16: Invalid range: cal s:record(expand('<abuf>', 1))_

Don't know how eclim fits in here.

I am on windows 10 using GVIM

**Comment by jalvesaq** [comment]
Perhaps someone who uses Eclipse and Eclim could help you...

**Comment by blayz3r** [comment]
I think closing R triggers a Winleave event and associated autocommands.

**Comment by jalvesaq** [comment]
Perhaps you should report the issue to eclim since it is happening inside one of its functions.

**Comment by blayz3r** [comment]
ok
