### ISSUE TITLE
Nvim-R only works on files in HOME directory (Mac OS X)

### ISSUE THREAD

**Issue by joelwatsonfish** [jalvesaq/Nvim-R#233]
Sorry... maybe there easy fix for this, but I couldn't figure it out.

Here's what I'm running:
Mac OS X Sierra (Version 10.12.6), 
Tmux 2.5
Vim version 8.0.165
R version 3.4.1 (2017-06-30)
and I installed Nvim-R via Vundle.

When I open terminal, open a tmux session, change to my HOME directory, use vim to open `~/test.R`, and type`;rf` the plugin works as it's supposed to (I've remapped my leader character from \ to ; ). However, if I change directories to `~/foo/bar/` and then use vim to open `~/foo/bar/test.R` the command `;rf` (and `\rf`) do not open an R session, but instead give a bell from vim (as if I've typed a nonsense command), but they don't yield an error message. 

In the HOME directory case, within vim, the command
`:nmap ;rf`
yields
`n  ;rf         *@:call StartR("R")<CR>`

In the subdirectory case, 
`:nmap ;rf`
yields
`No mapping found`
Similarly for `\rf` .  However, the command 
`:call StartR("R")`
starts an R session within a tmux pane as it's supposed to. The vim command `;l` does not send lines to the R session, but the command`:call SendLineToR("stay")` will successfully send a line to the R session. The command `:set filetype?` returns `filetype=r` and syntax highlighting works as it's supposed to.  

It doesn't seem to matter which directory from which I start vim, the plugin works if and only if the `test.R` file is in my HOME directory.

**Comment by jalvesaq** [comment]
I am sorry, but I cannot replicate the issue. You have to try an almost empty vimrc, with no plugin other than Nvim-R and Vundle and, then, if Nvim-R works, add plugins and vim options one by one until you discover the cause of the issue.

**Comment by joelwatsonfish** [comment]
Okay, fixed.  I'm not exactly sure what the problem was, but I commented out almost my entire .vimrc file (all but the lines needed for vundle and Nvim-R), and then added them back, line by line, checking for a difference.  I think I might of done something weird with `maplocalleader` and `leader`.   In any case, your response definitely helped fixe the problem.  Thank you very much.
