### ISSUE TITLE
the content of terminal-normal mode do not  update 

### ISSUE THREAD

**Issue by research41** [jalvesaq/Nvim-R#238]
vim: 8.0.1071
nvim-r: download from latest master branch
os: ms-windows 10, x64

- the content of terminal-normal mode do not  update .
however if I go to terminal-job mode and  back to terminal-normal mode, the content of terminal-normal mode will update. besides, when I start R using \rf, the terminal is in job mode and without syntax highlight .

following is about details.

when I edit a *.rmd file and press \rf, it is like following:
![default](https://user-images.githubusercontent.com/27892267/31505823-ca877e08-af43-11e7-9283-f28f7d5f4e2d.png)
as you can see, it is in terminal-job mode and without syntax highligt.

so I press `<c-\><c-n>` to enter terminal-normal mode (the `<esc>` will not work here, although I checked that the value of R_esc_term is 1), like follwing:
![default](https://user-images.githubusercontent.com/27892267/31506091-7c7eadfc-af44-11e7-9a1a-72ded3dfbc10.png)
now it is syntax highlight and beautful.

However when I send a R statement , the content of terminal-normal will not update. 
it is exactly the same as the above figure.

so I press `a` to enter job mode and find the content does update.  like following:
![default](https://user-images.githubusercontent.com/27892267/31506850-a6d28db0-af46-11e7-92e8-82d728a34baf.png)
the disadvantage is that you can not scroll the job-mode window. if it contains a error, you will miss it.

then I press `<c-\><c-n>` to go back to terminal-normal mode, and this time the content of terminal-normal window does update.
![default](https://user-images.githubusercontent.com/27892267/31507035-43482f1a-af47-11e7-8af5-efca503ead39.png)

so it is pretty annoy to debug R like this. 
It works if I use neovim instead of vim. however neovim is poor at dealing with utf8 file, I have to use vim.
is there any work around exist when you use vim and ms-windows system?

**Comment by jalvesaq** [comment]
What specifically is the problem of UTF-8 files in Neovim?
Anyway, please, update Vim and try again: https://github.com/vim/vim-win32-installer/releases

**Comment by jalvesaq** [comment]
Note: Vim cannot either syntax highlight or update the terminal in Normal mode. You have to wait until either these features are implemented in Vim or the UTF-8 issue is fixed in Neovim.

**Comment by research41** [comment]
what a pity!

**Comment by jalvesaq** [comment]
You could try this in your init.vim:
```
autocmd BufNewFile,BufRead *.csv set fileencoding=utf-8
```

**Comment by research41** [comment]
I have set `fenc=utf-8` in my .vimrc. 
when neovim open a *.csv file , its fileencoding is `utf-8`. however it does not help.
It is strange, the same csv file could be opened correctly with vim.

**Comment by jalvesaq** [comment]
I have just rebooted my computer on Windows and could test Neovim. Result: Neovim manages UTF-8 correctly. To test it yourself, do the following:

  1. Write a line like the following in Neovim-Qt:
```
echo "abc áà αβ"
```
  2. Split the window with `CTRL-W s`.

  3. Start the terminal with the command `:terminal`

  4. Visually select the line and yank it.

  5. Go to the terminal (`CTRL-W w`) and paste the line.

It should work: the line is correctly pasted. But if you try similar procedure on R Console, it will misinterpret the Unicode characters.

**Comment by jalvesaq** [comment]
After https://github.com/jalvesaq/Nvim-R/commit/9bb76270e3074cd94e49b1bed1a0f938c36e69d7 the `data.frame` `d` in the example below should be almost correctly displayed after `<LocalLeader>rv` if you don't send the code line by line, that is, if you send either the whole file (`<LocalLeader>aa`) or the code as selected lines (`<LocalLeader>ss`):

```r
a <- c(rep("abcd", 3), rep("ab αβ ♪", 2))
Encoding(a) <- "UTF-8"
x <- c(1, 3, 2, 5, 4)
d <- data.frame(a, x)
plot(d$a)
```

In my system, the Greek letters are OK, but the musical symbol appears correctly only in the plot; not in the csv file.

**Comment by research41** [comment]
Yes, you are right. the R console can not show "abc áà αβ" correctly. 
(ps: However Rgui works)

as for `<LocalLeader>rv` to show dataframe with utf8. 
I can not reproduce your example, no matter which method I choose to send code(`<localleader>aa`, `<localleader>ss`). the error is listed as following:
![default](https://user-images.githubusercontent.com/27892267/31632129-dfc851ae-b289-11e7-83e6-dd2c8bb2df7e.png)
If I use `<localleader>l` (that is line by line) , the error is `Process exited -1073740940`

**Comment by research41** [comment]
However If I change the first line code to exclude the musical symbol, then it  could be runned using  any above one of three method(\aa,\ss,\l), and as you mentioned, you can use `<localleader>rv` to view the `d` dataframe only by using  \aa and \ss method.
![default](https://user-images.githubusercontent.com/27892267/31632986-e82c306a-b28c-11e7-897b-74e2a3cfa2b7.png)
( ** However, as you can see, the Greek letters can not shown correctly in the terminal )

**Comment by research41** [comment]
for my situation,  I rarely input data in my soruce code. I import my data from stata dataset(which includes chinese characters) by using read.dta13 function. 
the dataset exported seems like to be cp936  (chinese) encoding. 

in my .vimrc I have set `fileencodings=utf-8,cp936`. the result is that vim will intelligently choose cp936 when utf-8 fails, while neovim stuck on utf-8 which fails to show chinese character correctly.
currently my workaroud is set `autocmd BufNewFile,BufRead *.csv set fileencodings=cp936,utf-8` in my init.vim. and finally neovim display correctly when you press `<localleader>rv` to view dataset.

the only problem left is neovim can not show utf8 characters in terminal window. it is filled with <blank> characters.

**Comment by jalvesaq** [comment]
The problem might be in RTerm.exe, and not in Neovim. It looks like that Rterm supports only a small subset of Unicode characters. What happens if you run Rterm directly in Windows cmd window, like this:
```
cd "C:\Program Files\R\R-3.4.2\bin\x64"
Rterm.exe
```
And, then, load and print two character objects, one encoded in CP936 and the other in UTF-8? If they are all displayed correctly, then the bug is in Neovim; otherwise, the bug is in Rterm.

**Comment by research41** [comment]
in my computer, I can not input cp936 or utf-8 characters in Rterm, even paste those characters. 
my R version is R 3.3.3

**Comment by jalvesaq** [comment]
So, I think we can close the issue since we cannot fix it in either Neovim or Nvim-R.
And, if Duncan Murdoch was right, the issue will not be fixed in R either:

> You might find it easier to convince Microsoft to add a UTF-8 locale, so then the native encoding would be UTF-8, and the problem would go away. (https://stat.ethz.ch/pipermail/r-devel/2013-November/067941.html)

**Comment by research41** [comment]
in latest Nvim-r, Is it possible to split a R console like Nvim-r github version, like:
![default](https://user-images.githubusercontent.com/27892267/31664129-3ff5d76c-b312-11e7-8a7c-0545ecf7200e.png)
because in windows it is the only way I can find to view utf8 characters in terminal/console.

**Comment by jalvesaq** [comment]
If you want to run Rgui in its own window instead of running Rterm in a Vim/Neovim buffer, you should put in your init.vim:
```
let R_in_buffer = 0
```
However, if you are going to use Rgui, then, I don't know of any advantage of Neovim over Vim. On the contrary, Vim is much better tested on Windows.

**Comment by research41** [comment]
thank you.
I think on window os, the gvim+nvim-r(with Rgui setting) is currently the best choice for me.
