### ISSUE TITLE
Unable to open pdf after knitting

### ISSUE THREAD

**Issue by mnosefish** [jalvesaq/Nvim-R#24]
versions: nvim-r--0.9.0, neovim--v0.1.0-45-gbb43d9b
After compiling pdf using `\kp`  for a .rmd file, I get the error message:

    Error detected while processing function ROnJobStdout:                              
    line    7:                                                                          
    E117: Unknown function: ROpenPDF                                                    
    Press ENTER or type command to continue  

This appears to be a new issue; I haven't had this problem before.
Attempted to update nvim-r and neovim.
Relevant lines in init.vim:

    let R_pdfviewer = "zathura"
    let R_openpdf = 1
                             
Edit: I should add that I can open the pdf manually just fine from outside nvim, so it is compiling correctly, however \op seems not to work because it simply calls \o and then pastes from the first register.

**Comment by jalvesaq** [comment]
Thanks for reporting the bug!
