### ISSUE TITLE
During startup - Warning messages:                                                                              

### ISSUE THREAD

**Issue by ganzuul** [jalvesaq/Nvim-R#241]
`During startup - Warning messages: `
`1: Setting LC_CTYPE failed, using "C" `
`2: Setting LC_COLLATE failed, using "C" `
`3: Setting LC_MESSAGES failed, using "C" `

This is also frequently printed when e.g. running install scripts. Functionality does not seem impaired, but it is console spam. 

I have made sure all my locale settings are correct and the the environment knows about them, so I don't know where the problem comes from. Running R directly from the terminal doesn't show these messages.

**Comment by jalvesaq** [comment]
Nvim-R does not set any LC_ environment variable. Are you setting them in your vimrc?

**Comment by ganzuul** [comment]
Ah, yes. I apparently messed up by using this:
https://github.com/amix/vimrc/blob/master/vimrcs/basic.vim#L75

Thank you very much. Commented out, I have no problem.
