### ISSUE TITLE
PDF knit fails with error "Error: pandoc document conversion failed with error 2"

### ISSUE THREAD

**Issue by mpjuers** [jalvesaq/Nvim-R#242]
Running (I think) RMakePDFK (default \<leader\>kp) results in "Error: pandoc document conversion failed with error 2", with the additional message that "--latex-engine has been removed.  Use --pdf-engine instead." I suspect this is due to a change in pandoc. I'm using pandoc 2.0.1.

**Comment by jalvesaq** [comment]
I'm still using pandoc 1.19.2.1 and it works. Anyway, the bug might in the `rmarkdown` package because Nvim simply calls `rmarkdown::render(Rmdfile, "pdf_document", ...)`.

**Comment by mpjuers** [comment]
OK. I downgraded pandoc and it's working fine. I looked at the pandoc changelog and it appears that v 2.0.0. they changed `--latex-engine` to `--pdf-engine` for a wonderful reason, I'm sure. Feel free to close this issue.

**Comment by jalvesaq** [comment]
Thanks for the feedback!
