### ISSUE TITLE
Skim attempts to open file with two extensions

### ISSUE THREAD

**Issue by frenchja** [jalvesaq/Nvim-R#243]
I'm not sure if this is a problem with my specific configuration with regards to how the base filename is passed.

*Steps:*
1.  Create `test.Rnw` using https://raw.githubusercontent.com/yihui/knitr/master/inst/examples/knitr-minimal.Rnw.
2.  Compile via `\kp` and open via `\op`.

I receive the error stating that "The document test.pdf.pdf could not be opened.".  

This error is fixed by modifying `R/skim.vim` to avoid appending `.pdf` to the fullpath:

```viml
if exists("*SyncTeX_forward2")
    finish
endif

function ROpenPDF2(fullpath)
    call system("env NVIMR_PORT=" . g:rplugin_myport . " " .
                \ g:macvim_skim_app_path . '/Contents/MacOS/Skim "' .
                \ a:fullpath . '" 2> /dev/null >/dev/null &')
endfunction

function SyncTeX_forward2(tpath, ppath, texln, tryagain)
    " This command is based on macvim-skim
    call system("NVIMR_PORT=" . g:rplugin_myport . " " .
                \ g:macvim_skim_app_path . '/Contents/SharedSupport/displayline -r ' .
                \ a:texln . ' "' . a:ppath . '" "' . a:tpath . '" 2> /dev/null >/dev/null &')
endfunction
```

Update:  Skim does not appear to append the pdf extension:

```bash
# Fails
/Applications/Skim.app/Contexts/MacOS/Skim test
```

**Comment by jalvesaq** [comment]
Thanks for reporting the bug!
I don't have a Mac OS X, but I inserted `let g:TheFullPath = a:fullpath` as the first line of `ROpenPDF2` in `zathura.vim` and could check that the `.pdf` extension is already part of `fullpath` with `:echo TheFullPath`.
The plugin is not well tested on Mac OS X...
