### ISSUE TITLE
RHelp stopped working with recent update 

### ISSUE THREAD

**Issue by jongbinjung** [jalvesaq/Nvim-R#244]
Seems like a recent update broke `RHelp` for me. I update my vim plugins roughly monthly, and was trying to diagnose which change broke `RHelp`, but it seems like I can't arbitrarily change the version of Nvim-R / `nvimcom`

Wondering (1) if it's just me and (2) whether there's a way for me to try different versions of nvimcom to diagnose the issue.

I'm on Vim 8.0.1274 and R 3.4.2, with Fedora 26.

**Comment by jalvesaq** [comment]
`:Rhelp` is working just fine here (with either Vim 8.0.1284 or Neovim 0.2.2-5-ge98bcf052).
Note that there is no `:RHelp` command.

**Comment by jongbinjung** [comment]
Ah, I was referring to the `<Plug>RHelp` mapping. 

But I've noticed `:Rhelp` does indeed work, and my `<Plug>RHelp` mapping seems to work some times ... perhaps it's worth just closing this issue until I actually figure out what the problem is.

Thanks!

**Comment by ErickChacon** [comment]
`:Rhelp` is working randomly for me on Neovim 0.2.0. Most of the times is not working. I thought it was conflicting with other package, so I reduced my init.vim to:

```
call plug#begin('~/.local/share/nvim/plugged')
Plug 'jalvesaq/Nvim-R' " R: run code, rmarkdown, help and more
call plug#end()
```  

but it still is working randomly without messages, warnings or anything. It just does not show the documentation. When :Rhelp is not working, the object browser does not show anything also.

**Comment by jalvesaq** [comment]
I confirm the issue, but since it is random, it is difficult to fix.

**Comment by jalvesaq** [comment]
Running with `options(nvimcom.verbose=4)` I could find and fix a bug. The error was happening if `:Rhelp` was called over a function with no argument between the parentheses.

**Comment by ErickChacon** [comment]
I updated the plugin, but I still have the same problem. After the update is works fine like 2 or 3 times, but later it stops working. I have tried to use `options(nvimcom.verbose=4)`, but nothing is shown.

**Comment by ErickChacon** [comment]
I thought it was a problem on the terminal only, but I have the same problem on https://github.com/onivim/oni

**Comment by jalvesaq** [comment]
Unfortunately, I can fix the issue only if we can replicate it consistently. The only change in nvimcom code in the last months was the declaration of its encoding as UTF-8 in the DESCRIPTION file. I have also changed the way the nvimcom library is unloaded by this should have an affect (if any) only when quitting R or detaching nvimcom. So, I guess something has changed in R 3.4.2.

**Comment by jalvesaq** [comment]
I have fixed another issue. The RHelp was not working if the object passed as first argument did not exist.

**Comment by ErickChacon** [comment]
I have the same version of R (3.4.2) and neovim (0.2.0) in another laptop with `Nvim-R` (commit `511ac10`), which is working without any problem.

**Comment by Figuera** [comment]
I am not sure if my problem is related to this, but my Rhelp is working with `R_nvimpager="horizontal"` or `"vertical"`  but is doing nothing, not even returning an error, with `"tab"` or `"tabnew"`.

Also, `nmap <Space> <Plug>RDSendLine` appear to be randomly not working (I am using `nmap <Space> \l<CR>` instead).

Running on Nvim-R 0.9.10.1, neovim 0.2.1 and R 3.4.2.

**Comment by jalvesaq** [comment]
@Figuera I can replicate the issue if I try Rhelp before sending any command to the R Console. If just after starting R I send any command to the R Console, such as `ls()`, then the Rhelp in a new tab works.

**Comment by Figuera** [comment]
@jalvesaq I run some tests, firstly it didn't work even if I send some ls()s before trying Rhelp. Then I ran a more complex command like `lm(runif(96) ~ runif(96))` and it finally worked, and it keep working even after I  close and reopen neovim (and ran Rhelp before anything). But it didn't last so long. I keep testing and got more cases where Rhelp was working as normal.

So it seems pretty random.

**Comment by jalvesaq** [comment]
Thanks for the feedback. I will look at this later, perhaps, only next week.

**Comment by jalvesaq** [comment]
@jongbinjung @ErickChacon @Figuera 
The issue should be fixed now. Please, reopen it if you still see the bug.

**Comment by Figuera** [comment]
I opened and closed neovim eigth times and Rhelp worked in every one of
them. Nice.

2017-11-18 13:43 GMT-02:00 Jakson Alves de Aquino <notifications@github.com>
:

**Comment by Figuera** [comment]
HMM maybe we should reopen this?

A new error is happening when I open R help. Well first, neither :Rhelp or /rh are working for me, sending help() to R works and a new tab with R help open up but that is not without problems, a new vertical windows is also open with no content, to get worse I get tons of vim package airline errors at the new vertical window.

I cant still use it but it is really annoying. My set up is the same as before so I dont think is something with my configuration. Is anyone else having similiar problems?

**Comment by jalvesaq** [comment]
I use vim-plug, I have just put the line below in my `init.vim`, and `\rh` is still working fine here (Ubuntu 17.10, development version of Neovim):
```vim
Plug 'vim-airline/vim-airline'
```
