### ISSUE TITLE
Can't send foreign characters to terminal (Windows)

### ISSUE THREAD

**Issue by adrianadermon** [jalvesaq/Nvim-R#245]
I'm running Nvim-R in Neovim 0.21 on Windows 10, and when I try to send or enter foreign characters in the terminal I get strange results.

To illustrate, if I send `print("ö")`, I get the output `"""`.  If I instead try to type `print("ö")` directly into the R console, it comes out as `print(""")`. The same happens if I enter the letter from my Swedish keyboard, or if I enter it as a Vim digraph (with Ctrl-K :o).

This also goes for any other unicode characters I try. "å" becomes "┼", "é" becomes "'", and "α" becomes "a". 

It happens on both my Windows 10 machines, regardless if I work in the GUI or the terminal (with cmd). 

I've tried it in Ubuntu Linux through the Windows Subsystem for Linux, and there everything works as you'd expect.

**Comment by adrianadermon** [comment]
I've realized that this is a problem with R running in the terminal in Windows, and so has nothing to do with your excellent plugin. Sorry about the false alarm.

**Comment by adrianadermon** [comment]
I looked into this a bit more, and it turns out that the problem is with the code page in the Windows terminal (cmd.exe). If I change the codepage in the terminal by running `chcp 1252` before starting R, everything works as expected (see [here](https://cran.r-project.org/bin/windows/base/rw-FAQ.html#Quotes-don_0027t-come-out-right-on-the-console_002fterminal_002fpager) for more information).

However, there's no easy way to make this change persist between sessions. Would it be possible to add a function to Nvim-R which runs the above command before starting the R console? It could be set through an option which allows the user to specify the desired codepage (1252 is appropriate for western Europe, but users elsewhere might need to use a different codepage).

**Comment by jalvesaq** [comment]
You may create a batch script named `chcpR.bat` with the following contents:
```bat
chcp 1252
Rterm.exe %*
```
and put in your `init.vim`:
```vim
let R_app = "chcpR"
```
Of course the batch script `chcpR.bat` must be in the system path or in the same directory of your R script.

**Comment by adrianadermon** [comment]
Works perfectly - thank you!

**Comment by jalvesaq** [comment]
If there is a need of mixing characters of different code pages, it will be necessary to use UTF-8, but because Rterm.exe tries to translate anything typed in its console to the current code page, the code must sourced, and not pasted into the console line by line, as discussed at https://github.com/jalvesaq/Nvim-R/issues/238#issuecomment-336648197 and in the following comments. I am closing the issue because this is an Rterm.exe limitation, and not a Nvim-R bug.
