### ISSUE TITLE
Running Nvim-R with sparkR

### ISSUE THREAD

**Issue by claytontstanley** [jalvesaq/Nvim-R#246]
I have a properly configured environment where typing sparkR connects to hadoop and drops me in an R repl. I'd like to hook this repl up to Nvim-R.

I change:
let R_app = "sparkR"                                                                                                          
let R_cmd = "sparkR"

In my .vimrc, then try \rf, and get this error:

Fatal error: you must specify '--save', '--no-save' or '--vanilla'^@

Any ideas how to approach this problem? It seems it should work since after a time running sparkR drops me in an R repl.

**Comment by claytontstanley** [comment]
Figured it out:

let R_app = "sparkR"
let R_cmd = "R"

**Comment by jalvesaq** [comment]
Thanks for the feedback! The information will be useful for others with similar problems.

**Comment by smilesun** [comment]
@claytontstanley , hi, I tried you configuration, but after start R from vim, it disappeared, any more configuration you have used ?

**Comment by smilesun** [comment]
sorry, restart solved the problem

**Comment by claytontstanley** [comment]
Just a note that I'm no longer using this workflow to run Nvim-R with sparkR. The other route is to launch vim and an .R file as normal, then library(SparkR), then configure everything within the launched vim session. This way you have more control over when you do and do not want to do spark things within a Nvim-R session.

**Comment by smilesun** [comment]
@claytontstanley , thanks a lot.  Do you mean to install sparkR package from here using R CMD INSTALL *.tar ?  Because the Cran sparkR is removed. 
`https://cran.r-project.org/src/contrib/Archive/SparkR/`
I do not quite understand how spark/bin/sparkR is different from a normal R installation or just a normal R but with sparkR pre-installed in the library. 

If I still want to use nvim R to launch sparkR, do you also have a suggestion?  I am using F6 in nvimR to launch a R session, and 
```
let R_app = "sparkR"
let R_cmd = "R"
```
works well. But everytime I want to use normal R I have to comment these two lines out, not sure if anyone has a solution.  maybe @jalvesaq ?

**Comment by smilesun** [comment]
To structure the problem again

I found the following in the nvimR documentation, which could launch a different R dynamically, but is it possible to do simliar things to switch between sparkR and normal R by pressing different shortcut ? For example, map F6 to normal R and map F7 to sparkR. 
```
        if system("df") =~ "remoteR"
            let $NVIM_IP_ADDRESS = substitute(system("hostname -I"), " .*", "", "")
            let R_app = "/home/locallogin/bin/sshR"
            let R_cmd = "/home/locallogin/bin/sshR"
            let R_compldir = "/home/locallogin/.remoteR/NvimR_cache"
            let R_tmpdir = "/home/locallogin/.remoteR/NvimR_cache/tmp"
            let R_remote_tmpdir = "/home/remotelogin/.cache/NvimR_cache/tmp"
            let R_nvimcom_home = "/home/locallogin/.remoteR/R_library/nvimcom"
        endif
```

**Comment by jalvesaq** [comment]
Try this:
```vim
function SparkR(what)
    let g:rplugin_R = a:what
    call StartR("R")
endfunction
nmap <silent> <F6> :call SparkR("R")<CR>
nmap <silent> <F7> :call SparkR("sparkR")<CR>
```

**Comment by smilesun** [comment]
it works! Thanks @jalvesaq   !!

**Comment by claytontstanley** [comment]
When I started solving this problem I figured there was a way to always launch 'R' but load up the sparkR library as needed. Once you are able to launch sparkR from the command line, then you should be able to follow these directions to initiate a spark context from an R session launched by 'R' (and not sparkR).

http://spark.apache.org/docs/latest/sparkr.html

**Comment by smilesun** [comment]
@Clayton Stanley,  that actually works as well.  Thanks

Clayton Stanley <notifications@github.com> schrieb am Fr., 1. Dez. 2017 um
13:52 Uhr:
