### ISSUE TITLE
Issue with nvimcom after update

### ISSUE THREAD

**Issue by nichtleiter** [jalvesaq/Nvim-R#248]
Hello,

I updated Nvim-R to the most recent version just now and since then the communication between Nvim-R and nvimcom is corrupt.

Maybe it is important to say that i have Nvim-R configured to start R inside a Tmux pane.

The following issues arise:
   * after knitting and compiling a Rnw file Nvim-R doesn't open the created PDF file. I get the message "The nvimcom package is required to make and open the PDF".
   * if i invoke the `help` command in R nothing happens in neovim
   * Nvim-R updates `nvimcom` on every start, although it is already installed.

Despite these issues the running R instance tells me that the `nvimcom` library is successfully loaded
```
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux buster/sid

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] nvimcom_0.9-45  devtools_1.13.3 magrittr_1.5    colorout_1.1-2

loaded via a namespace (and not attached):
[1] compiler_3.4.2 tools_3.4.2    withr_2.1.0    memoise_1.1.0  digest_0.6.12
```

If i look into the processes that run on my machine i also see that `nclientserver` is up and running.

Further more the variable `g:rplugin_nvimcom_bin_dir` is correctly set to `~/R/x86_64-pc-linux-gnu-library/3.4/nvimcom/bin` in Neovim.

For me it seems that `SetNvimcomInfo` hadn't  been called by `nclientserver` because the variables `g:rplugin_nvimcom_port`, `g:rplugin_R_version` etc. are all set to `0`.

After i downgraded Nvim-R to `v0.9.10` everything works flawless again. In other words the issue have crept in since then. 

Presumably the last changes of `nvimcom.c` are linked to this issue, but this is just a gut feeling.

I hope that my report is sufficient to look into the problem.

Best regards and thank you for your effort!

**Comment by jalvesaq** [comment]
Thank you!

**Comment by nichtleiter** [comment]
Unfortunately your last commit doesn't solve the issue!

I tested it and the issue remains, just like I explained.

**Comment by jalvesaq** [comment]
I am sorry, but I can no longer replicate the issue. The last commit fixed the bug for me.

**Comment by nichtleiter** [comment]
After i removed Nvim-R and setting it up again the issue remains.

`g:rplugin_nvimcom_port` is still set to `0` and i think this is the main problem. However i have no clue how to solve it.

Maybe you can give me a hint how to debug the code so i can try to fix the bug by myself.

And as always i really appreciate your relentless effort to improve Nvim-R

**Comment by jalvesaq** [comment]
If you put in your .Rprofile `options(nvimcom.verbose = 4)` then nvimcom will output a lot of information in the R Console.
If you put in your vimrc `let $DEBUG_NVIMR = 1`, nclientserver will append both received and sent messages to "/tmp/nclientserver_debug", and you can use ` tail` to see the messages in an terminal emulator:
```
tail -f /tmp/nclientserver_debug
```
