### ISSUE TITLE
E116: Invalid arguments for function SetNvimcomInfo

### ISSUE THREAD

**Issue by zhoosch** [jalvesaq/Nvim-R#250]
Hi there,

i have read much of the open issues and can't find a answert to my problem.
The problem appears with the last update (with vundle) 1 days ago. 
If i open a *.R file and start R with \rf the following messeages appear:

Messages maintainer: Bram Moolenaar <Bram@vim.org>
NERDTree: CWD is now: D:/ARBEIT/VL/QM
"test.r" 4950L, 186579C
"D:/Program Files/Vim/_vimrc" 1767L, 61062C
Error detected while processing function ROnJobStdout:
line    4:
E115: Missing quote: '.GlobalEnv package:nvimcom package:stats package:graphics package:grDevices package:utils package:datasets package:methods Autoloads package:base 
E116: Invalid arguments for function SetNvimcomInfo
Not ready yet
Not ready yet
R did not load nvimcom yet

My configuration for NVim-R:
if has("gui_running")
    inoremap <C-SPACE> <C-x><C-o>
else
    inoremap <NUL> <C-x><C-o>
endif
vmap <SPACE> <Plug>RDSendSelection
nmap <SPACE> <Plug>RDSendLine
" DEAKTIVIEREN von _ zu <-
let R_assign = 0
" DEAKTIVIEREN in tex-Files
let R_synctex = 0
autocmd BufNewFile,BufRead *.r,*.Rnw setlocal ts=2 sts=2 sw=2 noexpandtab tw=0
autocmd BufRead,BufNewFile *.r,*.Rnw setlocal wrap linebreak nolist wrapmargin=0
autocmd BufRead,BufNewFile *.r setlocal tw=96 " weil Boxoverflow! 
autocmd BufRead,BufNewFile *.Rnw setlocal tw=80 " weil Boxoverflow! 
" Change the <LOCALLEADER> key:
autocmd BufNewFile,BufRead *.r let maplocalleader = "-"
autocmd BufNewFile,BufRead *.r let mapleader = "_"
let R_insert_mode_cmds = 1 " Deaktiveren der Commands im R-Mode
let R_hl_term = 1
let g:R_allnames = 1  " versteckte Objekte anzeigen 
let R_show_args = 1 " Argumente anzeigen
let R_show_arg_help = 1 " Argumente anzeigen
let R_args_in_stline = 0 " Argumente beim ( tippen anzeigen
let R_wait_reply = 2
let Rout_more_colors = 1
let R_hi_fun = 1
let R_clear_line = 1
""let R_in_buffer = 0
""let R_applescript = 0
""let R_tmux_split = 1
let R_notmuxconf = 1

I've tried to compile nvimcom in the command line, installation was successful but the problem is there anyway.

OS: Windows 8.1
Rtools 3.3
R version 3.4.1 (2017-06-30) -- "Single Candle"
Platform: x86_64-w64-mingw32/x64 (64-bit)

Have you any suggestions for me? 

PS: I like your Plugin very much!

**Comment by zhoosch** [comment]
A downgrade on NVim-R 0.9.9 fix it. but i lose the tmux-styled buffer.

**Comment by jalvesaq** [comment]
Thanks for reporting the issue! I'm going to commit a workaround that will fix the issue if you do not have too many libraries loaded at startup and if the path to Nvim-R directory is not too long.

**Comment by zhoosch** [comment]
Works! Thx and Closed!
