### ISSUE TITLE
Windows paths interpreted as hex codes

### ISSUE THREAD

**Issue by niklaas** [jalvesaq/Nvim-R#252]
The issue is that `:RLoadPackage` translates to the following command in the R console i.e., it doesn't escape the `\` character:

```
> requireNamespace("devtools"); devtools::load_all("C:\Users\me\<some folder>")
```

Thus, R complains:

```
Error: '\U' used without hex digits in character string starting "C:\U"
```

Probably a workaround is to save the R package under a path that doesn't include "\U". A solution would be to escape `\` as discussed here: https://stackoverflow.com/questions/8425409/file-path-issues-in-r-using-windows-hex-digits-in-character-string-error

**Comment by jalvesaq** [comment]
This command is from https://github.com/mllg/vim-devtools-plugin

**Comment by niklaas** [comment]
Oh, thanks for clarifying! I opened another issue there.
