### ISSUE TITLE
Nvim-R can't communicate w/ browser on macOS Sierra

### ISSUE THREAD

**Issue by rcastelo** [jalvesaq/Nvim-R#254]
hi,
I'm using Vim 8.0.1200 and Nvim-R 0.9.9 on macOS Sierra 10.12.6 and when I start R, the R session seems unable to communicate with the browser. More concretely the R command:

`help.start()`

which should open the browser window with the R online help, does not open anything nor gives any error. This does not happen in my linux box with centOS. Opening the online help is the minimal example reproducing this problem and it is not a big deal. What annoys me about this problem is that, because of this, I cannot start shiny apps when using Vim+Nvim-R in my laptop.

any hint?

thankx.

**Comment by jalvesaq** [comment]
You could check if the value of `options("browser")` is OK.

**Comment by rcastelo** [comment]
This is what I get from an Nvim-R session:

```
options("browser")
$browser
function (u) 
.C("nvimcom_msg_to_nvim", paste0("StartTxtBrowser(\"w3m\", \"", 
    u, "\")"))
```

This is what I get from a regular R session:

```
options("browser")
$browser
[1] "/usr/bin/open"
```

So, is there anything I can change in my .vimrc to fix it?

**Comment by jalvesaq** [comment]
Perhaps you have copied the w3m example from Nvim-R documentation and put it in your .Rprofile, but it does not work in your case. So, just do not set the browser option in your .Rprofile.

**Comment by rcastelo** [comment]
True, I did it long time ago, forgot about it and didn't think about that option being responsible for the problem. thanks!!!!!
