### ISSUE TITLE
Nvim-R on WSL + tmux + terminator

### ISSUE THREAD

**Issue by merkliopas** [jalvesaq/Nvim-R#255]
I've installed WSL on my windows 10 machine and set up it to use with terminator over VcXsrv.

I've installed Nvim-R on my WSL vim and running `\rf` works in my terminal emulator. but I want to run it in tmux pane. I've added these lines to my .vimrc

> let R_term = 'terminator'
> let R_in_buffer = 0
> let R_applescript = 0
> let R_tmux_split = 1

But then there are two problems:

1. If I run `vim temp.R` and then `\rf`, R is opened in tmux pane but vim spits out these errors:

> Error detected while processing function CheckIfNvimcomIsRunning[3]..GetNvimcomInfo:
> line 37:
> E482: Can't create file /home/srn/.cache/Nvim-R/nvimcom_info
> Press ENTER or type command to continue

2. If I run `sudo vim temp.R` and then `\rf`, R session is not started and vim spits out these notifications

> [Terminal emulator] terminator: error: no such option: -L

and then

> "Job" exited with status 2

Any ideas how to fix that?

**Comment by merkliopas** [comment]
Interesting: I've deleted file `/home/srn/.cache/Nvim-R/nvimcom_info` and then problem 1. disappeared. though, problem 2 still persists.

**Comment by jalvesaq** [comment]
You should not use sudo to rum vim unless you want to edit system configuration files. Once you use sudo to run Nvim-R, the root becomes the owner of `nvimcom_info`. This is most likely the reason for problem 1( (`E482`).

You must start tmux before starting Vim. Otherwise, Nvim-R will change the value of `R_tmux_split` to `0`.

**Comment by merkliopas** [comment]
makes perfect sense. thanks for clearing that one up!
