### ISSUE TITLE
Odd behavior in sending lines when sending multi-line code in brackets

### ISSUE THREAD

**Issue by fklirono** [jalvesaq/Nvim-R#256]
Hello,

neovim v0.2.2 and latest Nvim-R plugin. Something has changed with the send-single-line commands (\<LocalLeader\>l and \<LocalLeader\>d) when going over multi-line code in brackets. The commands now seem to automatically look for the bracket closing of the code and send the whole chunk as one.

For example, sending with \<LocalLeader\>l the following when the cursor is at the first line would result in the whole chunk of code being sent.

```
for (n in 1:10){
cat('\n')
}
```
Previous behavior would just sent the first line of code. Is there a way to revert to the previous behavior? I have been very much used to it and it actually makes more sense for line-sending-code to send only one line at a time, no?

**Comment by mschilli87** [comment]
I'm using the same version of neovim and tried the above code before and after `:PlugUpdate`.
Before, only the first line was run, after all three.
So it definitely is related to a change in Nvim-R, not Neovim.

**Comment by jalvesaq** [comment]
When we send lines of code between brackets, nothing is interpreted by R until the closing bracketing is sent. So, I introduced this change to save time. Is there any advantage of sending the lines one by one? In fact, I consider a bug that Nvim-R does not recognize other cases of incomplete code,  like this:
```r
x <- a + b +
    c + d
```
If you prefer the old behavior, please, put in your vimrc:
```vim
let R_parenblock = 0
```

**Comment by fklirono** [comment]
ok thanks! The way I used this is by selecting the chunk of code I want to send and then doing \<LocalLeader\>l. This produces an error now. For example, if you select the code:

```
for (n in 1:10){
cat('\n')
}
```
and then do \<LocalLeader\>l this will run the for-loop and then produce an error because the closing bracket is sent as well being part of the selection.

So with this new feature I cannot select code spanning brackets anymore unless I do \<LocalLeader\>ss in which case I do not see in the session the code that I send. 

I guess it's a matter of getting used to this and changing my habits.
