### ISSUE TITLE
New R completion plugin for NCM

### ISSUE THREAD

**Issue by gaalcaras** [jalvesaq/Nvim-R#257]
I've created a plugin to provide "suggest as you type" R completion (kind of like RStudio): https://github.com/gaalcaras/ncm-R

![fullscreen screencast](https://user-images.githubusercontent.com/6551953/33690893-e896c35e-dae5-11e7-973d-cc1bffed1fcf.gif)

It uses the [NCM](https://github.com/roxma/nvim-completion-manager) completion framework and, of course, Nvim-R.

It seems like I'm not the only one interested in this kind of completion (see #175). Would you consider adding a link to the plugin in the doc and/or the README? It could help people find out about other auto completion solutions.

**Comment by jalvesaq** [comment]
Thanks for your plugin! However it is not working for me. I have tried with an almost empty `~/.conf/nvim` directory, with only `autoload/plug.vim` and `init.vim`, and the `init.vim` is:
```vim
call plug#begin('~/.cache/vim-plug')
Plug 'roxma/nvim-completion-manager'
Plug 'jalvesaq/Nvim-R', { 'for' : 'r'}
Plug 'gaalcaras/ncm-R'
call plug#end()

let mapleader = ";"
let maplocalleader = ","
```
When I type  `summ` the completion menu that appears has only `summary <Key>` because the script already has the word "summary" typed in. Any idea of what is causing the problem?

**Comment by gaalcaras** [comment]
Thanks, the feedback is much appreciated :)

Unfortunately, I am unable to reproduce your issue. I used your minimal vimrc, ran `:PlugInstall` then closed nvim and opened an R script. Completion was working fine right out of the box.

The only way I found to reproduce your problem was to delete the contents of `g:rplugin_compldir`. I solved it by loading some packages (including `base`, `utils`, etc.), then restarting nvim.

You could try to run the following:
```
NVIM_PYTHON_LOG_FILE=nvim.log NVIM_PYTHON_LOG_LEVEL=INFO nvim
```
Then try to use completion, then check the contents of `nvim.log_py3_cm_core` to see if there are any suspicious messages.

**Comment by jalvesaq** [comment]
In DEBUG level, I got this:
```
2017-12-07 15:23:39,164 [DEBUG @ msgpack_stream.py:send:33] 14947 - sent [2, 'nvim_call_function', ('cm#register_source', [{'channel': {'type': 'python3', 'module': 'cm_sources.r', 'events': []}, 'name': 'R', 'priority': 9, 'enable': True, 'abbreviation': 'R', 'word_pattern': '[\\w_\\.]+', 'scoping': True, 'scopes': ['r'], 'early_cache': 1, 'cm_refresh_patterns': ['\\$', '::', '"', "'", ',\\s([\\w_\\.]{3})?', '^\\s{2,}([\\w_\\.]{3})?$', '\\(([\\w_\\.]{3})?']}])]
2017-12-07 15:23:39,164 [DEBUG @ base.py:send:113] 14947 - Sending 'b'\x93\x02\xb2nvim_call_function\x92\xb2cm#register_source\x91\x8a\xa7channel\x83\xa4type\xa7python3\xa6module\xaccm_sources.r\xa6events\x90\xa4name\xa1R\xa8priority\t\xa6enable\xc3\xacabbreviation\xa1R\xacword_pattern\xa8[\\w_\\.]+\xa7scoping\xc3\xa6scopes\x91\xa1r\xabearly_cache\x01\xb3cm_refresh_patterns\x97\xa2\\$\xa2::\xa1"\xa1\'\xb0,\\s([\\w_\\.]{3})?\xb5^\\s{2,}([\\w_\\.]{3})?$\xaf\\(([\\w_\\.]{3})?''
2017-12-07 15:23:39,164 [INFO @ cm_core.py:_detect_sources:149] 14947 - source <cm_sources.r> registered
```
It looks suspicious to me that `events` in the first line above is `[]`. It is also strange that the `omnifunc` is `csscomplete#CompleteCSS` while I was typing "read.table":

```
2017-12-07 15:23:48,370 [DEBUG @ msgpack_stream.py:_on_data:56] 14947 - received message: [2, b'cm_refresh', [{b'cm-css': {b'scopes': [b'css', b'scss'], b'cm_refresh_patterns': [b'[\\w\\-]+\\s*:\\s+'], b'cm_refresh': {b'omnifunc': b'csscomplete#CompleteCSS'}, b'auto_popup': 1, b'name': b'cm-css', b'priority': 9, b'scoping': 1, b'early_cache': 0, b'sort': 1, b'enable': 1, b'cm_refresh_length': 3, b'abbreviation': b'css', b'word_pattern': b'[\\w\\-]+'}, b'cm-bufkeyword': {b'early_cache': 0, b'name': b'cm-bufkeyword', b'priority': 5, b'enable': True, b'auto_popup': 1, b'sort': 1, b'channel': {b'id': 6, b'module': b'cm_sources.cm_bufkeyword', b'events': [b'InsertEnter', b'BufEnter'], b'type': b'python3'}, b'abbreviation': b'Key', b'cm_refresh_length': 4}, b'R': {b'scopes': [b'r'], b'cm_refresh_patterns': [b'\\$', b'::', b'"', b"'", b',\\s([\\w_\\.]{3})?', b'^\\s{2,}([\\w_\\.]{3})?$', b'\\(([\\w_\\.]{3})?'], b'early_cache': 1, b'name': b'R', b'priority': 9, b'enable': True, b'auto_popup': 1, b'sort': 1, b'scoping': True, b'cm_refresh_length': 3, b'channel': {b'module': b'cm_sources.r', b'events': [], b'type': b'python3'}, b'abbreviation': b'R', b'word_pattern': b'[\\w_\\.]+'}, b'cm-jedi': {b'scopes': [b'python'], b'cm_refresh_patterns': [b'^(import|from).*\\s', b'\\.', b'\\(\\s?', b',\\s?'], b'early_cache': 0, b'name': b'cm-jedi', b'priority': 9, b'enable': True, b'auto_popup': 1, b'scoping': True, b'sort': 1, b'channel': {b'module': b'cm_sources.cm_jedi', b'events': [], b'type': b'python3', b'multi_thread': 0}, b'abbreviation': b'Py', b'cm_refresh_length': 3}, b'cm-keyword-continue': {b'early_cache': 0, b'name': b'cm-keyword-continue', b'priority': 5, b'enable': True, b'sort': 0, b'cm_refresh_length': 0, b'auto_popup': 0, b'channel': {b'id': 8, b'module': b'cm_sources.cm_keyword_continue', b'events': [], b'type': b'python3'}, b'abbreviation': b'', b'word_pattern': b'\\w+'}, b'cm-gocode': {b'scopes': [b'go'], b'cm_refresh_patterns': [b'\\.'], b'early_cache': 1, b'name': b'cm-gocode', b'priority': 9, b'enable': True, b'auto_popup': 1, b'sort': 1, b'scoping': True, b'cm_refresh_length': 3, b'channel': {b'module': b'cm_sources.cm_gocode', b'events': [], b'type': b'python3'}, b'abbreviation': b'Go', b'word_pattern': b'[\\w/]+'}, b'cm-tags': {b'early_cache': 0, b'name': b'cm-tags', b'priority': 6, b'enable': True, b'auto_popup': 1, b'sort': 1, b'channel': {b'id': 9, b'module': b'cm_sources.cm_tags', b'events': [b'WinEnter'], b'type': b'python3'}, b'abbreviation': b'Tag', b'cm_refresh_length': 4}, b'cm-tmux': {b'early_cache': 0, b'name': b'cm-tmux', b'priority': 4, b'enable': False, b'auto_popup': 1, b'sort': 1, b'channel': {b'module': b'cm_sources.cm_tmux', b'events': [b'CursorHold', b'CursorHoldI', b'FocusGained', b'BufEnter'], b'type': b'python3'}, b'abbreviation': b'Tmux', b'cm_refresh_length': 4}, b'cm-filepath': {b'options': {b'path_pattern': b'(([^\\W]|[-.~%$]|[/\\\\])+)'}, b'cm_refresh_patterns': [b'(\\.[/\\\\]+|[a-zA-Z]:\\\\+|~\\/+)', b'([^\\W]|[-.~%$]|[/\\\\])+[/\\\\]+'], b'early_cache': 0, b'name': b'cm-filepath', b'priority': 6, b'enable': True, b'auto_popup': 1, b'cm_refresh_length': 4, b'sort': 0, b'channel': {b'id': 7, b'module': b'cm_sources.cm_filepath', b'events': [], b'type': b'python3'}, b'abbreviation': b'path', b'word_pattern': b'([^\\W]|[-.~%$])+'}}, {b'lnum': 3, b'bufnr': 1, b'col': 8, b'changedtick': 12, b'typed': b'read.ta', b'filetype': b'r', b'curpos': [0, 3, 8, 0, 8], b'filepath': b'/home/aquino/music/nada/test.R'}, 0]]
```

**Comment by gaalcaras** [comment]
I'm getting the same messages and it's working fine, so I think we should look elsewhere.

With INFO level, ncm-R regularly outputs this kind of message (for instance, after you've typed "read.table"):
```
2017-12-07 20:17:28,587 [INFO @ r.py:cm_refresh:594] 18781 - word: "read.table", func: "", pkg: , pipe: None
```
Do you see any?

**Comment by jalvesaq** [comment]
No, I can't find the strings "read.table", "pkg" and "func" in the log.

I am going to mention your plugin the the Nvim-R documentation. Perhaps someone else can replicate the issue, and help you to find a solution. In my experience, it too hard to fix an issue when I cannot replicate it. For example, the Nvim-R bugs that do not affect my system (Ubuntu 17.10).

**Comment by gaalcaras** [comment]
> No, I can't find the strings "read.table", "pkg" and "func" in the log.

Strange. This has happened to me once or twice, usually because of a typo somewhere in the plugin, causing an error that wasn't reported in the logs. But since it works on my machine (Arch Linux), I can't figure out what the problem is.

> I am going to mention your plugin the the Nvim-R documentation.

Thanks!

> Perhaps someone else can replicate the issue, and help you to find a solution. In my experience, it too hard to fix an issue when I cannot replicate it. For example, the Nvim-R bugs that do not affect my system (Ubuntu 17.10)

I agree. I've duplicated the issue in my repo: https://github.com/gaalcaras/ncm-R/issues/1 so that you can close this one.

**Comment by jalvesaq** [comment]
@gaalcaras Perhaps displaying the function arguments in the pop up menu when completing function names is not highly useful because the arguments will be in the new pop up menu anyway when the user opens the parenthesis. Maybe the title of the function would be more useful, and I have just changed the format of omnils_ files to include the title of functions and other package objects. The titles are inserted between the characters `\x08` and `\x05`, and ncm-R stopped working here after this change.

**Comment by gaalcaras** [comment]
That's a good idea. Displaying the list of arguments made sense when ncm-R didn't do argument completion, but now it's redundant. I also thought it was too much information at times, since some R functions have lots of arguments.

I planned to change that down the road, but since you've already updated Nvim-R, I've made the change now in `master` for functions and datasets:

![function titles](https://user-images.githubusercontent.com/6551953/34070198-8847c5e2-e261-11e7-9e18-662e4fba3c6f.png)
![datasets titles](https://user-images.githubusercontent.com/6551953/34070197-85da60e4-e261-11e7-9676-d216c3821133.png)

By the way, ncm-R stopped working because of a weird entry in `omnils_stats_3.4.3`: the `spec.pgram` function used 2 lines instead of one, it didn't do that before.

Do you think Nvim-R could maintain a file of packages in `g:rplugin_compldir` with their descriptions? This could allow ncm-R to display packages and their descriptions inside of `library()`.

**Comment by jalvesaq** [comment]
I have fixed omnils_stats and added the title and description of packages to `pack_descriptions` with `\x09` as field separator.

By the way, what does `[+]` in ncm-R pop up menu mean?

**Comment by jalvesaq** [comment]
Would something like the code below be enough to enable `ncm-R` for the other R filetypes ("rnoweb", "rmd", "rrst", "rhelp", "rdoc")?
```python
if self.nvim.eval('&filetype != "r"') and self.nvim.eval('b:IsInRCode(0) == 0'):
    return
```

**Comment by gaalcaras** [comment]
> I have fixed omnils_stats and added the title and description of packages to pack_descriptions with \x09 as field separator.

Excellent, I'll get to work on this.

> By the way, what does [+] in ncm-R pop up menu mean?

These are snippets. If you have [UltiSnips](https://github.com/SirVer/ultisnips) installed, then if you select a suggestion and type <kbd>Tab</kbd>, then ncm-R expands the snippet. See: https://github.com/gaalcaras/ncm-R#snippets. It find it most useful for arguments for now.

> Would something like the code below be enough to enable ncm-R for the other R filetypes ("rnoweb", "rmd", "rrst", "rhelp", "rdoc")?

No, this won't work, but NCM defines "scopers" that will do what you want. I'm working on this on a local feature branch, I've got it working for Rmarkdown but it needs some more testing before I merge it. I'm not familiar with the other filetypes though. Do they also work with code chunks defined by specific syntax? If so, that's a bit more work to support them. If they're just "normal R scripts" and completion can occur anywhere in the file, then it'll be easy enough to get ncm-R to work with them.

**Comment by jalvesaq** [comment]
> I'm not familiar with the other filetypes though. Do they also work with code chunks defined by specific syntax?

The most widely used are Rnoweb (R + LaTeX) and Rmarkdown. In Rnoweb, R code chunks are delimited by
```
<<.*>>=
@
```
But LaTeX language is much more complicated than Markdown. So, having RMarkdown support will already be great, and it will make it easier for someone else to support Rnoweb.

> If they're just "normal R scripts" and completion can occur anywhere in the file, then it'll be easy enough to get ncm-R to work with them.

No, they are not just R scripts. They are like Rmarkdown: some regions are R and other regions are other language.

**Comment by gaalcaras** [comment]
All right, I'll focus on Rmarkdown first then tackle Rnoweb.

I've updated master in ncm-R, it should support package descriptions now.

**Comment by jalvesaq** [comment]
It works, but after some errors. Now that ncm-R displays more error messages, I could find what might be a problem in your algorithm: When you call `_r_output_to_file()`, you can't expect that the output file will be immediately available because R takes some time to process the message and also because it looks like that it does not flush the file immediately. I even inserted a `flush(stdout())` in `nvim.bol.R` in the hope that it will make the process faster.

Regarding the list of loaded packages, I may convert `s:loaded_libs` (used at `R/functions.vim`) into `g:rplugin_loaded_libs` if you could use it because it is updated automatically by nvimcom (which calls `FillRLibList()` when a new library is loaded). So, you would not have to run `.packages()` anymore.

**Comment by jalvesaq** [comment]
Please, try https://github.com/jalvesaq/Nvim-R/tree/auto_list
I renamed `s:loaded_lists` as `g:rplugin_loaded_libs` and, if the environment variable `NCM_R` exists, the `GlobalEnv_` file is continuously updated. So, you don't have to call `BuildROmniList`. I believe that `ncm-R` will be even faster after that.

**Comment by gaalcaras** [comment]
Yes! I've known about this flaw since the beginning, this implementation dates back to the very beginning of ncm-R, when my goal was to build a working plugin quickly without much concern about speed. I have lots of ideas to try and make ncm-R as fast as possible in the future.

I'll look at the `auto_list` branch and see how it works out. Thanks a lot for helping with the plugin!

**Comment by gaalcaras** [comment]
New feature branch: https://github.com/gaalcaras/ncm-R/tree/auto-list

ncm-R does feel noticeably faster for me. I've also made a change to refresh the list of matches as soon as a package is loaded (before that, it could take two or more refresh events). The experience is a lot smoother overall. What do you think?

Since we're trying to make ncm-R feel faster, do you think Nvim-R could automatically generate the `omnils_` files for the `R_DEFAULT_PACKAGES` if none exist? For now, ncm-R displays an error message instructing the user to load libraries.

**Comment by jalvesaq** [comment]
The earliest moment when the `omnils_` files can be generated is just after building nvimcom.
I'm going to commit a change for this.

**Comment by jalvesaq** [comment]
@gaalcaras `ncm-R` fails with `omnils_lm.beta_1.5-1` even after I have fixed some issues in the title of functions.

**Comment by jalvesaq** [comment]
It seems that the problem is at this line of `r.py`
```python
pkg_name = re.search(r'_(\w+)_', filename).group(1)
```
because a dot is not a `\w` character.

**Comment by jalvesaq** [comment]
@gaalcaras I did a test here and R refuse to build a package with an underscore in the version number. So, you can safely replace `\w` with `.` in the `re.search` command.

**Comment by gaalcaras** [comment]
Fixed on the `auto-list` branch : https://github.com/gaalcaras/ncm-R/tree/auto-list

**Comment by jalvesaq** [comment]
@gaalcaras Could you please add an option to not sort the completion results? It is easier to read the list of matches when they are sorted. However, I can see two advantages of not getting arguments of functions sorted:

1. Usually, the first arguments are the most important and more commonly used ones.

2. If I pass an argument in its default position, there is no need of including the name of the parameter. So, I can use the list of arguments not to complete, but as a guidance on what I have to type.

So, it would be nice if people could choose whatever they prefer.

The option to sort or not the matches could be added to the call of `register_source()` at `pythonx/cm_sources/r.py`. I tried adding `sort=0` and it worked as expected.

**Comment by gaalcaras** [comment]
I've been looking into this, but I'm actually not sure I understand what you mean by "sorted". Could you take a screenshot or give an example of what the menu would look like before / after sorting?

For now, suggestions are sorted like so:
1. By default: objects from the Global Env > functions > pkg names
2. Inside a function:
     1. If inside pipe: variables from the piped dataframe > function arguments (> functions > pkgs)
     2. If not: arguments > objects from the Global Env (> functions > pkgs)

Each subgroup is indeed not sorted, the order remains the same as in the source of completion (omnils for argument functions, etc.).

I've also tested adding `sort=0` in `register_source()` and could not notice a change in suggestion sorting. Looking at `:help cm#register_source()` or even at the [function definition](https://github.com/roxma/nvim-completion-manager/blob/cf18fb775ef265c9319d2d4fd8815d84ce345040/pythonx/cm_core.py#117) didn't help either, the `sort` argument does not appear in them. Maybe you're looking for something like `:help g:cm_matcher`?

**Comment by jalvesaq** [comment]
This is the default result:

![notsorted](https://user-images.githubusercontent.com/891655/34984807-ddf3a898-fa90-11e7-9d0c-7582bfeb03f1.png)

But I have this in my `init.vim`:
```
autocmd FileType r call cm#enable_for_buffer() | sleep 300m | let g:_cm_sources['R']['sort'] = 0
```
Then I get this:

![sorted](https://user-images.githubusercontent.com/891655/34984827-ee0cdea2-fa90-11e7-9555-fe38f14ca324.png)

That is, because the results are not sorted, I know that the first argument is `n` and, consequently, I can type `rnorm(1000)` instead of `rnorm(n=1000)`.

**Comment by gaalcaras** [comment]
That makes sense! Thanks for the screenshots. I agree the second one is better.

I achieve the same result with:
```
let g:cm_matcher = {'module': 'cm_matchers.substr_matcher'}
```

Does that work for you too?

**Comment by jalvesaq** [comment]
Yes, it works for me too. However, `g:cm_matcher` is a global variable, so I guess it could affect other file types, such as Python.

**Comment by gaalcaras** [comment]
In the end, I went with your first suggestion of using `sort=0`, this behaviour should be the default.

I also added RMarkdown and Rnoweb support into the master branch.

**Comment by jalvesaq** [comment]
Thank you, @gaalcaras !
