### ISSUE TITLE
auto/omi completion with R6

### ISSUE THREAD

**Issue by smilesun** [jalvesaq/Nvim-R#261]
- Is it possible to complete something like `self$`
- Is it possible to complete when one types `R6Class("clasname",)`
- Is it possible to complete the function body when one types` 'func'` then it completes to '`function(){}'`

**Comment by jalvesaq** [comment]
- Yes, omni completion completes the names list elements.

- If `R6class` is a function of a loaded package, its arguments might be completed with `<C-X><C-A>` (but after the merge of https://github.com/jalvesaq/Nvim-R/tree/omni_one it will be completed with `<C-X><C-O>`).

- No, you have to install a snippet plugin.

However, there is no automatic completion. You have to install a plugin that automates the completion. See, for example: https://github.com/gaalcaras/ncm-R

**Comment by blayz3r** [comment]
I am having a couple issues integrating YCM and Nvimr .I am pretty sure this worked well at some point.
Issue 1:
I sometimes get the the error below on semantic completion.
![omnifunc](https://user-images.githubusercontent.com/12205650/34168609-f2336044-e4b2-11e7-9ff7-0c6077ca79b1.png)

When it works the trigger is not consumed i.e if completion is triggered by the dot there is an extra dot at the end.
![omni](https://user-images.githubusercontent.com/12205650/34168621-f666084c-e4b2-11e7-97f1-7f9076fedcd2.png)

Let me know if these are YCM issues and not Complete#R. YCM works with other file types though.

**Comment by jalvesaq** [comment]
I have made some changes in the omni function in the last days, but it is working fine when triggered by `<C-X><C-O>`.

**Comment by jalvesaq** [comment]
@blayz3r How do you integrate YCM and Nvim-R?

**Comment by blayz3r** [comment]
After installing both plugins I use the option:
let g:ycm_semantic_triggers = { 'r' : ['.','::', '$', '@'] }

**Comment by jalvesaq** [comment]
Now I can see the issue that you reported. I don't know the reason, but, as I told, the omni completion works fine when manually called by `<C-X><C-O>` with YCM disabled.

By the way, I think a better semantic trigger is:
```vim
let ycm_semantic_triggers = { 'r' : ['re!..', '::', '$', '@'] }
```
Did you try https://github.com/gaalcaras/ncm-R ?

**Comment by blayz3r** [comment]
ncm-R doesn't have vim 8  support yet. I'll have to use R with YCM disabled for now I guess.

**Comment by jalvesaq** [comment]
It supports Vim 8. Please, see the "Installation" section at https://github.com/roxma/nvim-completion-manager

**Comment by blayz3r** [comment]
I was responding as per https://github.com/gaalcaras/ncm-R/issues/2. I'll test it out

**Comment by jalvesaq** [comment]
@blayz3r If you are going to try ncm-R, I suggest that you test the `auto-list` branch with Nvim-R's `auto_list` branch. If using vim-plug, you can try them with:

```vim
Plug 'jalvesaq/Nvim-R', {'branch': 'auto_list'}
Plug 'roxma/nvim-completion-manager'
Plug 'gaalcaras/ncm-R', {'branch': 'auto-list'}
```

**Comment by smilesun** [comment]
@jalvesaq , could you explain a stupid question?  what does "^" mean in the following documentation? I have already mapped the ctrl+x to close the nerdtree tab, so ctrl+a then ctrl+x does not work 

```
Complete object name                              ^X^O
Complete function arguments                       ^X^A
```

**Comment by jalvesaq** [comment]
It means the `<Ctrl>` key. It is not commonly used to represent the Control Key.

**Comment by smilesun** [comment]
I have put inoremap <S-tab> <C-X><C-A> but when I press control+tab after a function name, nothing happened. am I doing something wrong?

**Comment by jalvesaq** [comment]
`<C-X><C-A>` no longer exists. Please, use `<C-X><C-O>` to complete the names of arguments. The documentation will be fixed when I merge the branch `auto_list`.

**Comment by jalvesaq** [comment]
@smilesun In the `auto_list` branch, an R6ClassGenerator object is recognized as environment. It can be completed with omni completion and is highlighted in the Object Browser with the color of `Include` syntax group.

**Comment by gaalcaras** [comment]
@blayz3r I've just tried ncm-R with vim8, and I'm glad to report it works. However it's all dependent on you getting NCM to work with vim8, there is some additional work to get there: https://github.com/roxma/nvim-completion-manager#requirements . And since there's a compatibility layer between NCM and vim, ncm-R is a bit slower on vim 8 (though it felt usable during my short test).

**Comment by jalvesaq** [comment]
@smilesun Environment objects are completed now. This includes R6ClassGenerator objects.
