### ISSUE TITLE
Mapping to move from terminal to code windows does not work

### ISSUE THREAD

**Issue by statquant** [jalvesaq/Nvim-R#264]
Hello,
I'd like to report an issue that might very well be unrelated to `Nvim-R`, but still.
First let me report that I use it in vim `8.0.1360` in conjunction with `roxma/nvim-completion-manager`,`roxma/vim-hug-neovim-rpc`,`gaalcaras/ncm-R` and I am now enjoying 
- sending lines to an open terminal without having to run vim in `screen`, `tmux`
- as you type completion 

However I have the following mappings in my `.vimrc`
```
nmap <c-S-left> <c-w>h
nmap <c-S-right> <c-w>l
nmap <c-S-up> <c-w>k
nmap <c-S-down> <c-w>j
```
Say I open a terminal horizontally with `<mapleader>rf` I will be able to change window doing `<c-S-down> <c-w>j` but cannot 'go back up' using `<c-S-up> <c-w>k` (using the <c-w> still works)

Would this be related to the plugin ?
As a side note I would never want to use the terminal in `normal` mode (why would we ?), would there be a way to prevent it ?

**Comment by jalvesaq** [comment]
You can type `:nmap` to see a list of actual maps and look for something suspicious.

**Comment by statquant** [comment]
So this appears to be happening by just opening vim and creating a `:terminal` in another buffer.
Mapping the replicates `<c-w>h-l-k-j` using `C-` semms to be working outside of the terminal and fails in the terminal window...

This is very annoying :(

**Comment by jalvesaq** [comment]
You are in `Terminal` mode which is a kind of `Insert` mode with the input redirected to the application running in the terminal, including the `<Esc>` key. You have to do `<C-\><C-N>` to go to normal mode and, then, your mappings will work. Please, see `:h Terminal-mode`.

Since this is not a Nvim-R's bug, I'm closing the issue.
