### ISSUE TITLE
Request: Directly send commands to R

### ISSUE THREAD

**Issue by fennerm** [jalvesaq/Nvim-R#265]
First of all, thanks so much for this plugin! Makes me so happy to be able to write R in vim.

I often find myself stepping through my code and just needing to examine a variable or run some quick command in the REPL before continuing. Right now the best way to do this seems to be to shift focus to the REPL, run your command then shift back to the edit buffer. It would be much more efficient if we could just type e.g "\: "print(foo[1, ])" from the edit buffer to execute it in the REPL without ever leaving the edit buffer.

I looked all over for this feature in your docs but sorry if I just missed it.

**Comment by jalvesaq** [comment]
I added a new command (`:RSend`): https://github.com/jalvesaq/Nvim-R/commit/1d53eb82f24ee23306a870d28b9e20f349a1dd54

Is this what you want?

**Comment by fennerm** [comment]
Not home to test it at the moment, but that looks perfect- thanks so much for the quick response!
