### ISSUE TITLE
show dimension size/number of elements in object browser

### ISSUE THREAD

**Issue by blablablerg** [jalvesaq/Nvim-R#266]
In RStudio, the objectbrowser shows the dimensions of dataframes and number of elements in a vector. It is quite handy to have a quick overview when working in R, to check if nothing strange is happening during data cleaning/tidying. 

I wonder if such a thing would be possible with Nvim-R?

**Comment by jalvesaq** [comment]
Please, try the brach https://github.com/jalvesaq/Nvim-R/tree/df_dim

I have just added the number of rows and columns of data.frames between square brackets because the color of the object name already tells us that it is either a list or a data.frame. For lists, I added the number of elements.

**Comment by blablablerg** [comment]
I was very busy, so couldn't check it earlier. It works! 

Thanks for the quick solution!
