### ISSUE TITLE
recommand to use autoload script to make project layer easy to understand

### ISSUE THREAD

**Issue by wsdjeg** [jalvesaq/Nvim-R#267]
I just read the info:

```
" Why not an autoload script? Because autoload was designed to store
" functions that are only occasionally used. The Nvim-R has
" global variables and functions that are common to five file types
" and most of these functions will be used every time the plugin is
" used.
```

but I still can not understand why we can not use autoload script, I am author of SpaceVim, and I want to create a `lang#R` layer for in, in this layer, I want to use this plugin, but I just read the code, I found I can not understand the logic.

I know the this plugin provides five windows (filetypes), but why we can not use autoload find?

when you call function named `r#help#init()`, I think `autoload/r/help.vim` will be sourced.

**Comment by jalvesaq** [comment]
I am sorry, but I prefer everything sourced at Vim startup, and I do not plan to use the autoload directory.

Someone would have to re-write the plugin in the way that you want and tell me what I should do to note the advantages of the new design. I am sorry, but I really do not have time for doing this myself.

**Comment by wsdjeg** [comment]
Thanks, I will look into it if I have time. :)
