### ISSUE TITLE
automatically stop the editor from switching to edit mode after issuing a command

### ISSUE THREAD

**Issue by biorelated** [jalvesaq/Nvim-R#268]
Many thanks for an awesome library and utility! 
Is there a way to automatically stop the editor from switching to edit mode after issuing a command? For example I issue `\ss` to run the current selection and the editor switches to edit mode. I want it to remain in command mode because I also want to run another selection and I find it annoying to hit the `esc `key to return to command mode.

**Comment by jalvesaq** [comment]
What do you mean by "edit mode" (please, see `:h vim-modes`)?

After `\ss`, Vim remains in Visual Mode; after `\sa`, Vim goes to Normal mode an the cursor goes down to the next line of code.

**Comment by biorelated** [comment]
I meant "insert mode" not edit mode. For me (on neovim)` \sa` goes down and to insert mode;  not down and normal mode. Not sure why and thought it was a default setting that I could switch. Now it seems that down and normal mode is the default.

**Comment by jalvesaq** [comment]
I also use Neovim, but I can't replicate the issue. After `\sa` the cursor goes down and to Normal mode.

**Comment by biorelated** [comment]
I will look into my nvim settings and environment again and see if I can create a reproducible example. Its not that this is a show stopper.
