### ISSUE TITLE
nvimcom can not be loaded

### ISSUE THREAD

**Issue by mllg** [jalvesaq/Nvim-R#269]
I have encountered this problem on MacOS Sierra and Arch. Here is the output (sorry for localized error messages, `LC_ALL` is set in `.Rprofile` which is not parsed, see below):
```
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  es gibt kein Paket namens ‘nvimcom’
2: package ‘nvimcom’ in options("defaultPackages") was not found 
> nvimcom:::nvim.buildomnils("datasets")
Fehler in loadNamespace(name) : es gibt kein Paket namens ‘nvimcom’
```

I assume 4db8beaba52c0679322b6421cd9f181a6d681878 is to blame here. R is started with `--vanilla`, but my user library is set in my `.Rprofile`. Note that `--vanilla` also excludes certain environment variables. Versions prior to this commit work for me.

**Comment by jalvesaq** [comment]
I removed the `--vanilla`. Does it work now?

**Comment by mllg** [comment]
Works for Arch. Will test later on MacOS.

**Comment by mllg** [comment]
Works on MacOS, too. Thanks for fixing this so quickly.
