### ISSUE TITLE
Code working in batch but not when handing over to vim console

### ISSUE THREAD

**Issue by cpfaff** [jalvesaq/Nvim-R#270]
He

I use tmux+Nvim-R+Vim. I have an R script with code which was working fine for the past weeks in the depicted interactive combination. All of a sudden handing over some code does not work anymore and throws errors. It seems like some things are not handed over anymore properly which leads to interpretation errors on the side of the R console. 
Example:

```r
# works
a = cars[1]
b = cars[2]
cbind(a, b)
```

```r
# does not 
a = cars[1]
b = cars[2]
cbind(a, 
          b)

>       b)
Error: unexpected ')' in "      b)"
```

While one could place everything on one line it often also helps to better structure
the code. And it is also perfectly valid to place a newline after a comma and have the rest of the command to continue on the next line. If I put the second example into a file and execute it via `R CMD BATH script.R` it works again.

Can you reproduce this? Any ideas what causes this?

**Comment by jalvesaq** [comment]
I can't replicate the issue. What is your version of Tmux?

**Comment by jalvesaq** [comment]
My Tmux version is 2.5. Anyway, you may try this in your vimrc:

```vim
R_parenblock = 0
```

**Comment by cpfaff** [comment]
Sorry for bothering you. I found the problem. It was me. I forgot to pin the version of the package in vim. I was on the tip of your master branch. That is of course not a release or stable version and may break every now and then. I now have:

```vim
Plug 'jalvesaq/Nvim-R', { 'tag': 'v0.9.10' }
```

And that one seems to work

**Comment by mschilli87** [comment]
potentially related(?): https://github.com/jalvesaq/Nvim-R/issues/256

**Comment by jalvesaq** [comment]
@cpfaff you didn't bother me. If bugs in the development version are not reported, they will not be fixed. In this case, however, I can't replicate the issue and, thus, I can't fix it.

**Comment by cpfaff** [comment]
@jalvesaq that is true as well. I will compile more information. Maybe that helps to pin it down. 

* OS: Arch Linux
   * 4.14.12-1-zen #1 ZEN SMP PREEMPT Fri Jan 5 18:19:09 UTC 2018 x86_64 GNU/Linux
* VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan  3 2018 07:13:39)  
* tmux 2.6

**Comment by cpfaff** [comment]
If anything else could help let me know. I will try to provide the information.

**Comment by jalvesaq** [comment]
I installed Tmux 2.6, but I still cannot replicate the issue with Vim 8.0.1333.

**Comment by cpfaff** [comment]
I see. Maybe something with my particular environment or setup is broken. I also have problems with colorout which I could not replicate on another machine. See https://github.com/jalvesaq/colorout/issues/14
