### ISSUE TITLE
Error detected while processing zathura.vim

### ISSUE THREAD

**Issue by DadongZ** [jalvesaq/Nvim-R#272]
I got the following error while opening a .Rnw file. Would you have some suggestions to fix it?

```
"XXX.Rnw" 201L, 6373C
Error detected while processing /home.local/dz33/.vim/bundle/Nvim-R/R/zathura.vim:
line    9:
E684: list index out of range: 1
E15: Invalid expression: split(system("zathura --version 2>/dev/null"))[1]
```

**Comment by jalvesaq** [comment]
What is the version number of `zathura` in your system?
What is the output of `zathura --version` in a terminal emulator?

**Comment by DadongZ** [comment]
Have fixed it. The zathura has some issue working on server. Thanks

**Comment by jalvesaq** [comment]
Thanks for the feedback!
