### ISSUE TITLE
R_show_args error

### ISSUE THREAD

**Issue by gilles13** [jalvesaq/Nvim-R#273]
Hello,

R_show_args seem to return error when set to 0

error message
function CompleteR[108]..GetRCompletion[28]..RFillOmniMenu line 82
E121: variable not define : ttl

Is this my conf or a real bug ?

I use Vim 8.0 and tmux

Same error with Neovim

Thank you

**Comment by jalvesaq** [comment]
It's a bug. Thanks for reporting it!
