### ISSUE TITLE
R_show_arg_help

### ISSUE THREAD

**Issue by gilles13** [jalvesaq/Nvim-R#274]
Hello (again),

i have some problems with R_show_arg_help.
If I set it to 0, it doesn't throw an error, but preview open anyway.
Again, is it my conf ?

Thanks for your time and efforts.

Gilles

**Comment by jalvesaq** [comment]
It's another bug introduced by https://github.com/jalvesaq/Nvim-R/commit/3f156f4f02d674e37a1f9d176de03201363c3a08
Thanks for reporting it! I'm going to push the fix.
