### ISSUE TITLE
Minor mistake in Nvim-R.txt help file

### ISSUE THREAD

**Issue by alaindanet** [jalvesaq/Nvim-R#275]
Hi,
I have just found a minor mistake in the Nvim-R.txt (help file) line 2093 (Nvim-R-key-bindings section).

This command is missing `<CR>` at this end:
`     map <silent> <LocalLeader>s :call g:SendCmdToR("search()")`
It then should be:
 `map <silent> <LocalLeader>s :call g:SendCmdToR("search()")<CR>`

Thank you so much for developing this amazing plugin.

Cheers,
Alain.

**Comment by jalvesaq** [comment]
Thanks for reporting it!
