### ISSUE TITLE
nvimcom is always 'not ready yet'

### ISSUE THREAD

**Issue by wilkox** [jalvesaq/Nvim-R#278]
Thanks for the fantastic plugin! I've been using it without trouble from a while but this problem has suddenly shown up on a new install:

From inside an RMarkdown document, I'm able to open an R pane with `\rf`. Before the pane opens, the following message always appears:

`Updating nvimcom... Building lists for omni completion... OK!`

It's not clear why nvim-R wants to update nvimcom every time. nvimcom is definitely installed and working, as I can load it successfully with `library(nvimcom)`. If I try to send any code from the RMarkdown pane to the R pane, I get the message `Not ready yet` and nothing is sent. After a while, the following message appears:

`The package nvimcom wasn't loaded yet. Please, quit R and try again.`

I've tried all the standard keybindings for sending code and `\rf` works as expected, so I don't think it's anything to do with localleader.

* neovim v0.2.2
* nvim-R v0.9.11
* nvimcom v0.9-61
* R v3.4.3
* tmux v2.6
* OS X El Capitan 10.11.6

Any help would be appreciated!

**Comment by wilkox** [comment]
I've found a workaround: forcing R to open in a tmux split by adding

```vim
let R_in_buffer = 0
let R_applescript = 0
let R_tmux_split = 1
```

to my init.vim makes the problem go away. However, I'm leaving the issue open as I still can't get it to work in the default (and my preferred) configuration of opening R in a nvim buffer.

**Comment by jalvesaq** [comment]
Before starting R for you, when Nvim-R detects that nvimcom either is not installed yet or is outdated, it runs R three times:

   - to build the nvimcom package;
   - to install the nvimcom package;
   - to build the omni completion lists and syntax scripts.

It looks like that the nvimcom package is being installed in a directory that is no longer valid when R is finally started to be used interactively.

**Comment by jalvesaq** [comment]
Could you, please, run these commands in R running in the neovim buffer:
```
sink("/tmp/env_buffer")
Sys.getenv()
sink()
```
And these commands in R within tmux:
```
sink("/tmp/env_tmux")
Sys.getenv()
sink()
```
And, then, compare the results:
```
nvim -d /tmp/env_buffer /tmp/env_tmux
```
Do you see any difference between the two environments that might be relevant?

**Comment by wilkox** [comment]
Yes, the tmux split session has four additional environment variables not present in the neovim buffer session:

```bash
MYVIMRC                 /Users/wilkox/nvim/init.vim
NVIM_LISTEN_ADDRESS     /var/folders/jh/zybl02rx1sg8cqfh9tkxhnf00000gn/T/nvimlk3xO3/0
VIM                     /usr/local/Cellar/neovim/0.2.2/share/nvim
VIMRUNTIME              /usr/local/Cellar/neovim/0.2.2/share/nvim/runtime
```

**Comment by wilkox** [comment]
Also, even in a tmux split, I still see `Updating nvimcom... Building lists for omni completion... OK!` every time I open an RMarkdown document and `The package nvimcom wasn't loaded yet. Please, quit R and try again.` still appears after a while even though I have no problem sending code from nvim to R.

**Comment by jalvesaq** [comment]
I was expecting that the path to nvimcom installation would be different...
Please, update Nvim-R, start R and run in Neovim the command `:RDebugInfo`.
Where is nvimcom being installed, and is it at the expected directory?

**Comment by wilkox** [comment]
nvimcom is being installed to /usr/local/lib/R/3.4/site-library, which seems right to me. There's never a problem loading nvimcom in an R session whether started by nvim-R in a tmux split, in a vim buffer, or just R launched from the command line.

Here's the complete output of `:RDebugInfo`:

```
CMD_INSTALL
* installing to library ‘/usr/local/lib/R/3.4/site-library’
* installing *source* package ‘nvimcom’ ...
** libs
clang -I/usr/local/Cellar/r/3.4.3_1/lib/R/include -DNDEBUG   -I/usr/local/opt/gettext/include -I/
usr/local/opt/readline/include -I/usr/local/include   -fPIC  -g -O2  -c nvimcom.c -o nvimcom.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -mult
iply_defined suppress -L/usr/local/Cellar/r/3.4.3_1/lib/R/lib -L/usr/local/opt/gettext/lib -L/usr
/local/opt/readline/lib -L/usr/local/lib -o nvimcom.so nvimcom.o -L/usr/local/Cellar/r/3.4.3_1/li
b/R/lib -lR -lintl -Wl,-framework -Wl,CoreFoundation
(cd apps; make)
cc -pthread -std=gnu99 -O2 -Wall nclientserver.c -o nclientserver
installing via 'install.libs.R' to /usr/local/lib/R/3.4/site-library/nvimcom
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (nvimcom)
libPaths
['/usr/local/lib/R/3.4/site-library', '~/Library/R/3.4/library']
Build_Omnils
> nvimcom:::nvim.buildomnils("datasets")
> nvimcom:::nvim.buildomnils("utils")
> nvimcom:::nvim.buildomnils("grDevices")
> nvimcom:::nvim.buildomnils("graphics")
> nvimcom:::nvim.buildomnils("stats")
> nvimcom:::nvim.buildomnils("methods")
> nvimcom:::nvim.buildomnils("nvimcom")
> nvimcom:::nvim.buildomnils("base")
>
.libPaths()
CMD_build
* checking for file ‘/Users/wilkox/.local/share/nvim/plugged/Nvim-R/R/nvimcom/DESCRIPTION’ ... OK

* preparing ‘nvimcom’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘nvimcom_0.9-61.tar.gz’
```

**Comment by jalvesaq** [comment]
And, after R is started, what is the output of `.libPaths()`? Is it the same of the above output? On Linux, `/usr/local` is not writable by common users.

**Comment by wilkox** [comment]
```
> .libPaths()
[1] "/usr/local/lib/R/3.4/site-library"
[2] "/usr/local/Cellar/r/3.4.3_1/lib/R/library"
```

It's the same in both the tmux split and nvim buffer.

**Comment by wilkox** [comment]
As far as I can tell nvimcom is successfully loaded every time an R session is started by nvim-r. For example, after an R session with `\rf` all the nvimcom functions are available in the session:

```r
> nvimcom::
nvimcom::nvim.srcdir            nvimcom::nvim.interlace.rrst
nvimcom::nvim.interlace.rnoweb  nvimcom::nvim.names
nvimcom::nvim.interlace.rmd     nvimcom::nvim.plot
nvimcom::nvim.print             nvimcom::vi
nvimcom::etags2ctags            nvimcom::nvim.list.args
```

Thanks for all your help with this problem!

**Comment by jalvesaq** [comment]
In addition to nvimcom being loaded, the nclientserver application should be available. What is the output of
```
:echo rplugin_nvimcom_bin_dir
```

**Comment by wilkox** [comment]
Before the `The package nvimcom wasn't loaded yet. Please, quit R and try again.` message appears, it's /usr/local/lib/R/3.4/site-library/nvimcom/bin. After the message appears, it's empty.

nclientserver seems to be where it should be and executable:
```shell
~$ cd /usr/local/lib/R/3.4/site-library/nvimcom/bin
....4/site-library/nvimcom/bin$ ll
total 32
-rwxr-xr-x  1 wilkox  admin    14K  7 Feb 11:22 nclientserver
....4/site-library/nvimcom/bin$ ./nclientserver
call RSetMyPort('10103')
```

**Comment by jalvesaq** [comment]
Everything seems to be OK. You still could check the value of `R_wait`. Its default value is 60 seconds which I guess is enough for almost all cases. For now, I have no other idea of what else might be wrong.

**Comment by jalvesaq** [comment]
Only now I noted that the second directory in `:RDebugInfo` output (`~/Library/R/3.4/library`) is different from the second directory from `.libPaths()` output (`/usr/local/Cellar/r/3.4.3_1/lib/R/library`). However, this should not be a problem because `rplugin_nvimcom_bin_dir` points to `/usr/local/lib/R/3.4/site-library/nvimcom/bin` which is within the first directory in both outputs.

**Comment by wilkox** [comment]
Thanks for your help anyway. Using git-bisect I was able to isolate commit 545685b as where the problem was introduced. I think it's something to do with the change to `CheckIfNvimcomIsRunning()` but I haven't quite figured it out yet.

**Comment by jalvesaq** [comment]
What is the output of
```
:echo rplugin_jobs
```
'ClientServer' should be non-zero.

Perhaps the function `StartNClientServer` is not working well on Mac OS X. It has a script level variable (`s:what_r`) that would not be available in a debug session. You would have to replace `s:what_r` with `g:what_r` in `R/common_global.vim` before debugging the function:
```
:debug call StartNClientServer()
```
and, then, press `s` to run first line of the function and `n` to next lines.
Unfortunately, I don't have access to any Mac OS X.

**Comment by wilkox** [comment]
It looks like [lines 921-013 of nvimcom.c](https://github.com/jalvesaq/Nvim-R/blob/08f2b62192b6b8b98156c541e8343e976865ea02/R/nvimcom/src/nvimcom.c#L912-L913) do get executed, but the message never reaches nvim and `SetNvimcomInfo()` isn't called. I've also noticed that while the nclientserver process starts, it never sends or receives any data.

**Comment by jalvesaq** [comment]
It looks like the bug is specific to Neovim on Mac OS X. Below is a small test with the relevant code from Nvim-R:

File `/tmp/get_output.vim`:
```
function! OnJobStdout(job_id, data, etype)
    for cmd in a:data
        let cmd = substitute(cmd, '\r', '', 'g')
        if cmd == ""
            continue
        endif
        exe cmd
    endfor
endfunction

call jobstart('sh /tmp/cmds.sh', {'on_stdout': function('OnJobStdout')})
```

File `/tmp/cmds.sh`:
```
#!/bin/sh

echo "let s:xyz = 123"
echo "let s:abc = 'ABC'"
echo "echo s:xyz . s:abc"
```

After saving the two files, to try the test, you should do `:so %` in Neovim while editing `get_output.vim`. The command `:so %` means "source this file", and the output should be `123ABC`.

**Comment by jalvesaq** [comment]
A simple test would be to put square brackets around `nvc` at line 676 of common_global.vim:
```
    let g:rplugin_jobs["ClientServer"] = StartJob([nvc], g:rplugin_job_handlers)
```

**Comment by wilkox** [comment]
The `jobstart` test works: 123ABC is printed. Sorry, I didn't understand the test with the square brackets but they didn't seem to change anything.

I'm pretty sure that nclientserver is started – I can see it appear in my list of processes after `\rf`. It also looks like nvimcom tries to talk to nclientserver, because it tries to [send SetNvimcomInfo](https://github.com/jalvesaq/Nvim-R/blob/08f2b62192b6b8b98156c541e8343e976865ea02/R/nvimcom/src/nvimcom.c#L912-L913). But for some reason the message never makes it back to nvim and SetNvimcomInfo is never run.

**Comment by wilkox** [comment]
Finally figured it out. I use pyenv to manage my python versions. It places 'shim' python executables into `~/.pyenv/shims`, which is then added to my $PATH. This shims directory includes an executable named `python3` even if a python version > 3 is not currently installed – the executable prints out 'pyenv: python3: command not found' and returns an error. However, [common_global.vim will still detected that python3 is executable](https://github.com/jalvesaq/Nvim-R/blob/08f2b62192b6b8b98156c541e8343e976865ea02/R/common_global.vim#L3668-L3669), and set it as the python binary to use. Later, when GetRandomNumber tries to run getRandomNumber.py, it captures an error instead of a random number, so $NVIMR_SECRET is invalid.

I've opened a pull request with a fix for this issue. I'm not sure if it's the best solution though.

Thanks for all your patience and help in fixing this! I'm very happy to be able to use the plugin normally again.

**Comment by jalvesaq** [comment]
Thanks! I merged your pull request as a temporary solution, but I will try to use nclientserver to generate the random numbers to avoid the need of using Python.
