### ISSUE TITLE
|R_LIBS_USER|

### ISSUE THREAD

**Issue by LiNk-NY** [jalvesaq/Nvim-R#283]
Hi Jakson, @jalvesaq 
I have multiple installations of R and I use them separately.
I want to be able to define an `R_LIBS_USER` environment variable
so that `Nvim-R` knows where to look. 

The option of using `~/.Renviron` or `~/.bashrc` does not work since they are
being used by the RStudio server.

I thought it would be easy to just do:
```
autocmd VimEnter * let R_LIBS_USER='/path/to/library/folder'
```
in the `~/.vimrc` but this doesn't get read when loading `Nvim-R`.

Your suggestions are highly appreciated. Thanks for your attention.

Best,
Marcel

**Comment by jalvesaq** [comment]
You don't need the VimEnter event. Simply put in your vimrc:
```
let R_LIBS_USER='/path/to/library/folder'
```
Then, start R and check:
```
Sys.getenv("R_LIBS_USER")
.libsPath()
```
I tested on Neovim with R running in the built-in terminal, and the path defined by `R_LIBS_USER` was the first one listed by `.libsPath()`.

**Comment by jalvesaq** [comment]
If the above does not work (for, example, if you are running R in a tmux split pane), you could try to put in the beginning of your `~/.Rprofile`:
```
if(Sys.getenv("NVIMR_TMPDIR") != ""){
    Sys.setenv(R_LIBS_USER="/path/to/library/folder")
}
```

**Comment by LiNk-NY** [comment]
Hi Jakson, @jalvesaq 
Thank you for your prompt response. 
Unfortunately, these solutions did not work for me. 
The `let` command sets the variable but the `.libPaths` are not updated with the file path.
I am using `tmux` in conjunction with `Nvim-R` in a split pane.

The `~/.Rprofile` did not work for me either. 
Setting an `~/.Renviron` file did the trick but I rather not use this option since
I have multiple installations of R on my computer. 

Best regards,
Marcel

**Comment by jalvesaq** [comment]
It seems that tmux requires the environment variable being prefixed to the command, but I almost dropped the support for running R in a Tmux split pane to have less code to maintain. I prefer R running in a Neovim buffer.

**Comment by jalvesaq** [comment]
@LiNk-NY I changed the way that running R in a tmux split pane is set (you should see a warning about that), and the environment variable `R_LIBS_USER` is set in the tmux pane now.
