### ISSUE TITLE
gdb debugging for Rcpp

### ISSUE THREAD

**Issue by smilesun** [jalvesaq/Nvim-R#285]
could you suggest a way to debug Rcpp using Nvim-R? Firstly, to make all functions remain if one execute `R -d gdb`

**Comment by jalvesaq** [comment]
You may try this:

1. Manually run g++ to build the library `Rcpp.so` with the arguments
```
-O0 -g -o /path/to/library/Rcpp/libs/Rcpp.so
```

2. Put this line in your `vimrc`:

```
let R_args = ['--quiet', '--no-save', '-d', 'gdb']
```
3. In Vim/Neovim, do `<LocalLeader>`rf to start gdb.

If you want to run R within valgrind, put something like this in your `vimrc`:
```
let R_args = ['--quiet', '--no-save', '-d', '"/usr/bin/valgrind --log-file=/tmp/Rvalgrindlog --leak-check=full --show-leak-kinds=all"']
```

**Comment by smilesun** [comment]
is this necesary `-O0 -g -o /path/to/library/Rcpp/libs/Rcpp.so` if i only want to debug Rcpp packages but not Rcpp itself?

**Comment by jalvesaq** [comment]
I thought you were wanting to debug Rcpp. For a Rcpp package, you only need to manually compile the library of that package.
