### ISSUE TITLE
Filetype indent

### ISSUE THREAD

**Issue by romagnolid** [jalvesaq/Nvim-R#286]
Hi Jackson, 
first of all thanks for this great vim plugin.
I'd like to use 2 spaces for indentation in R files so I created a ftplugin/R.vim file with the following options

    setlocal softtabstop=2
    setlocal tabstop=2
    setlocal shiftwidth=2   

but it's not working.
I googled the problem but haven't found a solution yet. 
Do you have any suggestion?

**Comment by jalvesaq** [comment]
Perhaps, what you want is:
```
let r_indent_align_args = 0
```
Please, see `:h ft-r-indent`.

**Comment by romagnolid** [comment]
Right, I forgot to mention that I've already put that in my .vimrc but the problem persists.

**Comment by jalvesaq** [comment]
Could you please give an example of code manually indented as you wanted?

**Comment by romagnolid** [comment]
Sure, when working with a *.R filetype I'd like to have an indentation of 2 spaces both when I type "tab" and automatically inserted when I go to a new line. 

    subtract <- function(x, y) {
      if (x > y) {  # two spaces
        z <- x - y 
      } 
      return(x+y)  
    }

While for any other file I want to keep 4 spaces.
I wonder if there's a conflit with the .vimrc where softtabstop, tabstop, shiftwidth are set to 4. Maybe ftplugin options are overwritten?

**Comment by jalvesaq** [comment]
Did you try
```
autocmd FileType r setlocal sw=2
```
?

**Comment by romagnolid** [comment]
Just tried it but it's not working. I wonder if there are conflicts with some plugin or with the order of commands in my vimrc.

**Comment by jalvesaq** [comment]
It works here.

**Comment by romagnolid** [comment]
It works! It was a matter of properly sourcing the vimrc. Thanks for the help!

**Comment by romagnolid** [comment]
I add an update that may be useful to other users.
Instead of "R.vim" one must call the ftplugin file "r.vim" (lowercase). Maybe it's common knowledge but I didn't know that.
