### ISSUE TITLE
Disable Knit mappings

### ISSUE THREAD

**Issue by Figuera** [jalvesaq/Nvim-R#287]
This is a very specific problem, but I seem to be unable to solve on my on.

I have a DVORAK keyboard so my mappings are all different, specifically 'k' is my <leader> and <localleader> and 'kk' is mapped to ESC. This is causing a lot of miss clicking since nvim-R Knit Mapping maps <leader>k*.

I would like for this mapping to work only or .Rmd files and not on .R files, is that possible?

Alternatively, I tried to unmap these key combination but had no success, none of the following seen to work:

```
unmap <leader>kn
nunmap <leader>kn
unmap kkn
unmap <buffer> kkn
unmap <LocalLeader>kh
map <leader>kn <NOP>

```
Any ideas?

**Comment by jalvesaq** [comment]
Did you try commands like these?
```
nmap <LocalLeader>nr <Plug>RKnit
nmap <LocalLeader>nh <Plug>RMakeHTML
nmap <LocalLeader>np <Plug>RMakePDF
```
Please, see `:h Nvim-R-key-bindings`.

**Comment by Figuera** [comment]
Thanks for the reply Jackson.

(I forgot to put the codings marks up there, sorry)

The type of mapping that your solution proposes never works for me (Don't know why), but even if they worked they would not unmap the `<LocalLeader>kh` which is the most important part for me.

**Comment by jalvesaq** [comment]
Did you put the commands in your vimrc? You have to map all the `<Plug>`s that are mapped to `<LocalLeader>k.` by default: RMakePDFK, RMakePDFKb, RMakeODT, RMakeWord, RMakeRmd, RMakeAll.

**Comment by Figuera** [comment]
Thanks again Jackson.

It worked!

But I am dazzled by why. First of all, none of the mappings commands worked if I simply send it in as a normal command (`:nmap <LocalLeader> <Plug>RKnit`), it also didn't work if put the mapping commands under a filetype R `autocmd` (which was why I was having trouble setting these mappings). Do you know why?

I am also wondering why that when I remapped the `<Plug>`s  the originals `<LocalLeader>k*` stopped to work, this is an expected `<Plug>` behavior?

**Comment by jalvesaq** [comment]
All maps are defined at once when the Vim sets the file type, that is, after vimrc is already sourced. If the `<Plug>` map exists, it is used; if not, the default key binding is created.
