### ISSUE TITLE
Omni-completion sometimes crashes (indefinitely hangs) neovim

### ISSUE THREAD

**Issue by ashiklom** [jalvesaq/Nvim-R#288]
Doing function omni-completion (`Control-X Control-O`) on function definitions sometimes causes neovim to hang indefinitely.

Unfortunately and frustratingly, I have been unable to come up with a reproducible example, but it seems to be triggered by the `devtools::load_all()` function on moderately large packages. For instance, in my workflow, I often have a test script open that looks like:

```r
devtools::load_all("/path/to/package")
my_function(|)
```

When I trigger the omni-completion at cursor position `|`, neovim hangs with the message `-- Omni completion (^O^N^P) -- Searching...` and doesn't respond to any key commands (`q`, `Control-C`, etc.), so I am forced to kill the terminal instance. Interestingly, my CPU usage during the hang is very low, which suggests a low-level segfault or similar error rather than something CPU-intensive like an infinite loop or neovim trying to process a lot of data.

Because this doesn't happen for minimal test packages that I've tried to create as reproducible examples, I'm guessing this is specific to more complex packages.

Happy to help debug this in any way I can, but would be nice to get your advice on where to start. I've tested this with only the nvim-R plugin (no other plugins), and with `-V9` for maximum logging of nvim, but that hasn't revealed anything useful. Is there a neovim completion log (or similar) that would be worth looking at to see what's going on?

**Comment by jalvesaq** [comment]
If you put the command `options(nvimcom.verbose=4)` in your `~/.Rprofile`, nvimcom will output debugging info at the R Console, and, if the environment variable `DEBUG_NVIMR` is defined with any value, the `nclientserver` application will save debugging info in the file `/tmp/nclientserver_debug` which you may follow in another terminal emulator or Tmux split pane with the command:
```
tail -f /tmp/nclientserver_debug
```

**Comment by ashiklom** [comment]
Thanks for the quick response! I tried all of that but unfortunately didn't get too much more information. The last line in the debug file is just this:

```
stdin: [2]8085881291534984208nvimcom:::nvim_complete_args("read_ed_veg", "", extrainfo = TRUE)
```

(`read_ed_veg` is the function on which I'm calling the completion).

This may not be directly related, but some other times when I get similar crashes during omni-completion, I see the following error in the R console:

```
VECTOR_ELT() can only be applied to a 'list', not a 'NULL'
```

Digging a bit deeper, I added some `message` statements to `nvim_complete_args` to confirm that the function has been entered, and based on those, the hang/crash happens _before_ the `nvim_complete_args` function has even been called (the messages I added do print to the console when completion is successful).

**Comment by ashiklom** [comment]
Digging a little further, I found this in `R/common_global.vim::GetRArgs1`:

```
    let ii = 1000
    while ii > 0 && s:ArgCompletionFinished == 0
        sleep 30m
    endwhile
```

As far as I can tell, the counter `ii` is never actually updated here, or used anywhere else in this function. My guess is that this is triggering an infinite `while` loop if completion is unsuccessful for any reason, and that's what's causing the completion to hang.

**Comment by ashiklom** [comment]
Digging a little more...

I think the problem may be that running `help` on packages that are loaded with `load_all` triggers the following message:

```
Using development documentation for <function>
```

Because Nvim-R somehow isn't equipped to handle this unexpected output, rather than parsing the help, it opens the help in the R window and just sits there. Meanwhile, because it is just sitting there with the help open but without actually reading it, the `while` loop in the vimscript from above will run indefinitely.

Indeed, if I do `options(help_type = "html")`, every time I try to trigger completion, a new browser window opens with the function's help, but the completion step itself proceeds without error.

Perhaps a simple solution is to make sure the function parsing the help file for the function arguments calls `suppressMessages(help(...))` instead of just help?

**Comment by ashiklom** [comment]
Even more digging! Turns out that calling `devtools::load_all` quietly substitutes base R's `help` functions for `devtools` versions, which apparently have behavior incompatible with `nvimcom:::gbRd.fun`.

The fix is therefore to use replace `"help"` with `utils::help` (no quotes) in `gbRd.fun`. I'll open a PR that does this.

**Comment by ashiklom** [comment]
Sorry to keep spamming this, but after a bit more digging, it looks like the GitHub version of `devtools` resolves this problem. The GitHub version of `devtools` moved `load_all` and `dev_help` (the offending function) into a new `pkgload` package, and that package's version of `dev_help` has the expected behavior (https://github.com/r-lib/pkgload/blob/master/R/dev-help.r#L25-L45).

I tested out the omni-completion with the GitHub version of `devtools` and it works fine, even after running `devtools::load_all`.

At some point, it may be worth considering adding something like this to `gbRd.fun` to ensure the correct behavior:

```r
if (requireNamespace("devtools") && packageVersion("devtools") >= "1.13.5.9") {
    help_fun <- help
} else {
    help_fun <- utils::help
}
x <- do.call(help_fun, list(...))
```

**Comment by jalvesaq** [comment]
Probably it will be better to always call `utils::help`.

**Comment by jalvesaq** [comment]
It seems that you have fixed everything with your pull request, which I have already merged...

**Comment by jalvesaq** [comment]
Thank you for your contribution!

**Comment by ashiklom** [comment]
Sure thing, happy to help.

Once the new version of `devtools` drops on CRAN, might be worth switching back to just using `help`. Having access to the development version of documentation, which is loaded via `devtools::load_all` is pretty handy. I'll keep it around on my fork to see if there are any hiccups.

But in the meantime, this issue can probably be closed.
