### ISSUE TITLE
Rout_more_colors not working after update

### ISSUE THREAD

**Issue by ranranking** [jalvesaq/Nvim-R#29]
This option is not working after I updated Nvim-R. 
Neovim version 0.1.2
R version 3.2.3
nvimcom version 0.9-8.4

I tried to install the released version of nvimcom and problem solved. But when I open r from neovim, it shows warning message: Your version of Nvim-R requires nvimcom-0.9-8.4. I don't know whether it is because of nvimcom or Nvim-R that Rout_more_colors not woking.

<img width="626" alt="screen shot 2016-02-25 at 3 35 15 pm" src="https://cloud.githubusercontent.com/assets/7812475/13336901/e10a248e-dbd5-11e5-8b44-126e28adf10e.png">
<img width="631" alt="screen shot 2016-02-25 at 3 36 47 pm" src="https://cloud.githubusercontent.com/assets/7812475/13336909/e6b3dcfe-dbd5-11e5-9122-34cf28e6bfdc.png">

**Comment by jalvesaq** [comment]
When you send the first command to R running in a Neovim terminal, Nvim-R asks to nvimcom if the colorout package is loaded. If it is loaded, the output is not highlighted as Rout file type. You have two options: Do not load colorout if R was started by Nvim-R (you may put in your .Rprofile something like this):

```r
if(Sys.getenv("NVIMR_TMPDIR") == "" && (interactive() || isatty(stdout()))){
    options(colorout.noninteractive = TRUE)
    library(colorout)
}
```

Or, force Nvim-R to highlight the output even if colorout is loaded (put in your vimrc):

```vim
let R_hl_term = 1
```

**Comment by ranranking** [comment]
Thank you very much! That solve the problem!
