### ISSUE TITLE
Highlight functions from global environment

### ISSUE THREAD

**Issue by ashiklom** [jalvesaq/Nvim-R#291]
Per discussion in #289, it would be nice to add the ability to highlight functions that are in the global environment (`.GlobalEnv`).

**Comment by jalvesaq** [comment]
@ashiklom please, update Nvim-R and read the documentation on `R_hi_fun_globenv`.

**Comment by ashiklom** [comment]
This looks fantastic, thank you!

**Comment by jalvesaq** [comment]
I added a new valid value for R_hi_fun_globenv. Now, there are three options:
- 0: No highlight
- 1: Highlight new functions, but do not clear the highlighting when they are deleted.
- 2: Redo the highlighting after each command is sent to R.
