### ISSUE TITLE
Install nvimcom package in a different library

### ISSUE THREAD

**Issue by jarodmeng** [jalvesaq/Nvim-R#294]
Currently Nvim-R always install nvimcom in the first library which is usually a user library. It might make sense to install nvimcom in a site library so that a user can switch user library (e.g., stable vs dev) without having to reinstall nvimcom.

Perhaps a setting to allow user to supply a library location and if it's not set, then default to the current behavior?

**Comment by jalvesaq** [comment]
Perhaps you could manipulate where nvimcom is installed by changing the value of the `R_LIBS_USER` environment variable.

**Comment by rohitfarmer** [comment]
I am struggling with the same issue. Even after setting R_LIBS_USER, it's still defaulting to the root directory on which I do not have permission to write. I just want to install everything in my local home directory and that is in the path, but further down in the list.
