### ISSUE TITLE
csv in terminal program

### ISSUE THREAD

**Issue by coachshea** [jalvesaq/Nvim-R#295]
First, thank you for the great plugin.

I am using neovim, but I prefer to view csv files in sc/scim. As of now, as far as I understand, I can view a csv file in a buffer or an external program. I was wondering if there was a way to use nvim's terminal feature to view the file in a split or tab using sc/scim.  Any help is greatly appreciated.

Thanks again for all your great work.

**Comment by jalvesaq** [comment]
Please, try the branch https://github.com/jalvesaq/Nvim-R/tree/term_app and put in your init.vim:
```
let R_csv_app = 'terminal:scim'
let R_csv_delim = ','
```
Does it work as you exepected?

**Comment by coachshea** [comment]
That works perfectly!! Thank you very much!!

-- 
John Shea
cell: 617-605-5763
email: coachshea@fastmail.com

**Comment by Nevrage** [comment]
Thank you very much for supporting scim!

Though on Windows the following keeps opening the dataframe in a vim buffer

`let R_csv_app = 'c:/Program Files/Microsoft Office/Office15/EXCEL.EXE'
 let R_csv_delim = ','`

While `excel.exe file.csv` does open `file.csv` in a new instance of excel.

Am I missing something?

**Comment by jalvesaq** [comment]
@Nevrage I have just made a minor change (see https://github.com/jalvesaq/Nvim-R/commit/d0ca77a9b279a53a4c7e5f09d039416a9ee9b6bf) but it should not affect the issue that you are reporting. I tested the code with Vim and it opens the data.frame in LibreOffice. I don't have Excel installed to test the code with.

**Comment by Nevrage** [comment]
It does seem to affect it. Excel now opens up when hitting csv_app but I get a 
`Sorry, we couldn't find iris.csv. Is it possible it was moved, renamed or deleted.` error message from excel.

**Comment by jalvesaq** [comment]
Does the file `iris.csv` exist? It should have been created after `<LocalLeader>rv`.
