### ISSUE TITLE
How to go to the R terminal?

### ISSUE THREAD

**Issue by shuaiwang88** [jalvesaq/Nvim-R#297]
How to switch between nvim terminal (Source) and the R terminal(Console).

**Comment by jalvesaq** [comment]
Basically, press `CTRL-W w` in Normal mode. For more options, please, do in either Neovim or Vim:
```
:h window-moving
```

**Comment by mschilli87** [comment]
Assuming you use default `vim` bindings, <kbd>Ctrl</kbd>+<kbd>W</kbd><kbd>l</kbd> should switch to the left and <kbd>Ctrl</kbd>+<kbd>W</kbd><kbd>h</kbd> to the right split (or <kbd>Ctrl</kbd>+<kbd>W</kbd><kbd>k</kbd> to the upper and <kbd>Ctrl</kbd>+<kbd>W</kbd><kbd>j</kbd> to the lower in case you use vertical splits).

**Comment by shuaiwang88** [comment]
@jalvesaq I am able to R console now. But after I typed something it turned to TERMINAL mode and not able to go back to the source window.

**Comment by shuaiwang88** [comment]
I followed [https://vi.stackexchange.com/questions/4919/exit-from-terminal-mode-in-neovim/4922](url) to exit the TERMINAL mode from the R console to Normal mode. 
Press <C-\><C-n>
