### ISSUE TITLE
neovim: undesired insert mode in edited file after send if startinsert is set for term

### ISSUE THREAD

**Issue by doubleloop** [jalvesaq/Nvim-R#299]
Minimal vimrc:
```
$ cat test_vimrc
call plug#begin('~/.local/share/nvim/plugged')
Plug 'jalvesaq/Nvim-R'
call plug#end()
au WinEnter term://* startinsert
$ nvim -u test_vimrc test.r
```
If I start r (`\rf`) and do any send (for example `\ae`), the cursor stays in the edited file (as it should) but insert mode is started and AFAIK it should not.
Works the same for `au WinEnter * if &buftype == 'terminal' | startinsert | endif`

**Comment by jalvesaq** [comment]
What happens if you put this in your vimrc:
```
let R_setwidth = 0
```

**Comment by doubleloop** [comment]
Same behavior.

**Comment by jalvesaq** [comment]
I get a different behavior here (Neovim on Linux). I can replicate the issue only when `R_setwidth=1`.

**Comment by jalvesaq** [comment]
For me, the issue was fixed by https://github.com/jalvesaq/Nvim-R/commit/550151ba2125c8cd108f843faa8fae8cb662f818

**Comment by doubleloop** [comment]
Great! I just checked and 550151b fixed the issue :)
