### ISSUE TITLE
Can I set R_rconsole_height to really small value?

### ISSUE THREAD

**Issue by ranranking** [jalvesaq/Nvim-R#30]
I tried to set this option to 5 but the height on startup was still half of my window. When I set it to a large value, for example 30, it actually worked. The startup window height increased. At first I thought it might because of the startup messages. I tried to use Rstart custom and type --quiet, but nothing changed. So I am asking, whether it is possible to set this option to a small value? I set R_vsplit = 0

**Comment by jalvesaq** [comment]
Now, you can. Thanks for asking!

**Comment by jalvesaq** [comment]
The minimum is 1... Zero does not work. Compare:
```vim
:belowright 0new
:belowright 1new
:belowright 2new
```

**Comment by ranranking** [comment]
Thank you very much!
