### ISSUE TITLE
Object omni-completion not working

### ISSUE THREAD

**Issue by ashiklom** [jalvesaq/Nvim-R#300]
I think there might be a bug in the object omni-completion (`R_complete = 2`). I am using a test script that looks like this:

```r
very_long_variable <- list(
  apple = 5,
  orange = 10,
  banana = 15
)
very_long_variable2 <- 10

very_long_[*]
```

After `source`ing the file, with the cursor at the `[*]`, I press `C-X C-O` and get the "Pattern not found" error.

After digging around, I found this block at the end of the definition for `BuildROmniList` in `R/common_global.vim`:

```vim
    if string(g:SendCmdToR) != "function('SendCmdToR_fake')"
        let s:globalenv_lines = []
    else
        let s:globalenv_lines = readfile(g:rplugin_tmpdir . "/GlobalEnvList_" . $NVIMR_ID)
    endif
```

If I change `!=` to `==` in the `if` statement, the completion works as expected.

Is this a bug? Shouldn't we be returning blank global environment lines if R is _not_ loaded, rather than if it _is_ loaded (which I think is what the equality is testing for)?

**Comment by jalvesaq** [comment]
It's a bug, and your fix is correct. I didn't note it because I have `ncm-R` installed.
Thanks for reporting the bug and fixing it.
