### ISSUE TITLE
Correctly mapping SendSelection

### ISSUE THREAD

**Issue by jamesdunham** [jalvesaq/Nvim-R#302]
A while ago I ran into an issue sending selections to R. They'd be sent repeatedly, about once for each of the lines they contained. Using the map
```
autocmd Filetype r,rmd vnoremap <silent> <LocalLeader>sv :call SendSelectionToR("echo", "stay")<CR>
```
Selecting these two lines in visual mode
```
library(httr)
library(stringr)
```
And hitting `<LocalLeader>sv` outputs
```
> base::source("/tmp/Nvim-R-james/Rsource-24707", print.eval=TRUE, echo=TRUE)
^A^Kbase::source("/tmp/Nvim-R-james/Rsource-24707", print.eval=TRUE, echo=TRUE)
> library(httr)
> library(stringr)
> base::source("/tmp/Nvim-R-james/Rsource-24707", print.eval=TRUE, echo=TRUE)
> library(httr)
> library(stringr)
```
Experimenting, I found that deleting `'<,'>` from the visual mode command avoids the issue entirely. This map works as expected:
```
autocmd Filetype r,rmd vnoremap <silent> <LocalLeader>sd :<backspace><backspace><backspace><backspace><backspace> call SendSelectionToR("echo", "stay")<CR>
```
But is there a better way? Thanks!

**Comment by jalvesaq** [comment]
In the function `RCreateMaps` at `R/common_global.vim` mappings in Visual mode includes an `<Esc>` key. Example:
```
vnoremap <buffer><silent> <LocalLeader>ss  <Esc>:call SendSelectionToR("silent", "stay")
```

**Comment by jamesdunham** [comment]
Okay, thanks!
