### ISSUE TITLE
Is this going to work for python or is there something like Nvim-R for python?

### ISSUE THREAD

**Issue by shuaiwang88** [jalvesaq/Nvim-R#303]
The Nvim-R blows my mind. Thank you!
I really want something like this works on python.
Cheers!

**Comment by jalvesaq** [comment]
Thank you! I very rarely use Python and the only plugin for Python that I have installed is
[jedi-vim](https://github.com/davidhalter/jedi-vim) which is used by [nvim-completion-manager](https://github.com/roxma/nvim-completion-manager). But you may also be interested in one of these:

- [neoterm](https://github.com/kassio/neoterm)
- [vim-slime](https://github.com/jpalardy/vim-slime)
- [repl.nvim](https://gitlab.com/HiPhish/repl.nvim)
- [vimcmdline](https://github.com/jalvesaq/vimcmdline)

I'm the author of the last one, but I almost never use it, and I've never used the other three.

**Comment by shuaiwang88** [comment]
Tested vimcmdline and it is exactly what I am looking for.
 I really appreciate your effort!!!
