### ISSUE TITLE
Does this mean return head(df) 48-57 lines? 

### ISSUE THREAD

**Issue by shuaiwang88** [jalvesaq/Nvim-R#305]
https://github.com/jalvesaq/Nvim-R/blob/db0acc21e11d51bc2fe83504c78cb2bef73d35cc/doc/Nvim-R.txt#L2230

**Comment by jalvesaq** [comment]
No, it means: Get the word under the cursor, considering part of words the following characters:

- `@`: alphanumeric characters, that is a-z, A-Z, and accented letters in some languages.
- `48-57`: bytes 48 to 57, that is, numbers from 0 to 9
- `_`: underline
- `.`: dot

You can also add if you want:

- `@-@`: the "at" character

**Comment by shuaiwang88** [comment]
So what if I want show top 10 rows like head(df, 10) as default?

**Comment by jalvesaq** [comment]
Please, update Nvim-R and put in your vimrc:
```
nmap <silent> <LocalLeader>h :call RAction('head', ', n = 10')<CR>
```

**Comment by shuaiwang88** [comment]
BTW what snippet plugin do you use for R?

**Comment by jalvesaq** [comment]
Currently, I'm not using any snippet plugin because I rarely used the `snipMate` when it was installed and I found it more useful to put this in my `init.vim`:

```
inoremap <Tab> <C-N>
inoremap <S-Tab> <C-P>
```
