### ISSUE TITLE
nclientserver.exe for 32-bit Windows

### ISSUE THREAD

**Issue by harryln** [jalvesaq/Nvim-R#306]
I use Nvim-R in both gvim and nvim under 32-bit Windows. But both has the error information: Application nclientserver.exe not found. I have checked the installed R package 'nvimcom' and found nclientserver.exe is in '/nvimcom/bin/i386'. Do I need to tell Nvim_R explicitly where this function is? Many thanks for your help in advance.

By the way 64-bit Windows has no any problem.

**Comment by jalvesaq** [comment]
All my tests were in a 64-bit Windows. Could you please update the plugin and try again?

**Comment by harryln** [comment]
Update Nvim-R and it works with both gvim and nvim under 32-bit Windows! Many thanks for your prompt update and great efforts to provide such a great plugin for R programming.
