### ISSUE TITLE
Feature request: include other interactive scripting, e.g., bash

### ISSUE THREAD

**Issue by webbp** [jalvesaq/Nvim-R#309]
Great project, I use it every day! It would be awesome (neo)vim could be used with any script executor (bash, python, node, lua, perl, php, etc...) instead of just R.

**Comment by jalvesaq** [comment]
Do you mean some kind of Rmarkdown script with chunks of code written in Python, bash, etc?

Or are you think of a general plugin to send commands to an interpreter? For this, please, look at https://github.com/jalvesaq/Nvim-R/issues/303

**Comment by webbp** [comment]
Yes, vimcmdline is what I was looking for :)
