### ISSUE TITLE
no Nvim-R.vmb release?

### ISSUE THREAD

**Issue by manumart** [jalvesaq/Nvim-R#31]
Hi Jalvesaq,
I could not find any Nvim-R.vmb release as mentionned at https://github.com/jalvesaq/Nvim-R for instsalling Nvim-R.vmb ? COuld you please help for installing it?

Thank you anyway so much for the work so far!

Manuel

**Comment by jalvesaq** [comment]
There was 1 release, but it was in an website that I no longer use. It is now at [Google Drive](https://drive.google.com/folderview?id=0ByMBQcSs9G7KUXZDQmwxTmMxNGM&usp=drive_web&tid=0ByMBQcSs9G7KYkotRGpRYjlLVDg)

The next release will be at https://github.com/jalvesaq/Nvim-R/releases

**Comment by jalvesaq** [comment]
I released new versions of both Nvim-R and nvimcom:
https://github.com/jalvesaq/Nvim-R/releases
https://github.com/jalvesaq/nvimcom/releases
