### ISSUE TITLE
R console width ignores terminal line numbers

### ISSUE THREAD

**Issue by ashiklom** [jalvesaq/Nvim-R#310]
The width of my R console seems to be set incorrectly, even with `R_setwidth = 1`.

```r
getOption("width")
# [1] 80
Sys.getenv("COLUMNS")
# [1] "76"
```

I think what may be happening is that, because my Neovim terminal buffer has line numbers, the number of columns available to R is reduced by the width of the line number bar, but R's `width` option isn't adjusted. For instance, when I generate a ton of output, so that my terminal buffer is several thousand lines long, I get...

```r
Sys.getenv("COLUMNS")
# [1] "74"   # <- Now smaller, because 2 more digits of line numbers
getOption("width")
# [1] 80
```

I've been hacking around this by defining a simple function like this to set the width interactively. Perhaps you could use this instead of whatever the current algorithm to set the line width?

```r
setwidth <- function () {
    w <- Sys.getenv("COLUMNS")
    options(width = as.integer(w))
}
```

I'm not sure if all terminals/shells set the `COLUMNS` variable, but in my brief tests, bash, zsh, and sh all use it, and they are the three most common cases.

**Comment by jalvesaq** [comment]
Workarounds for the issue are:

   1. **Ask the R Core team to set the width option when R gets the `SIGWINCH` signal.** This is the best solution. If you have the required patience, you can check if someone has already made this request and join the conversation to try to convince the R Core Team that this is an important issue.

   2. **Subtract 6 from the window width if 'numbers' is set in the R Console window when R was started up.** This is the simplest solution to be implemented into Nvim-R, but it might not work for everyone.

   3. **Make nvimcom check the `COLUMN` environment variable after each top-level command.** This is simple too, but the first command executed after the number of columns has changed will still be executed with the outdated width option.

   4. **Make Nvim-R send a message to nvimcom check the `COLUMNS` environment variable before sending a command to R Console.** This would crash R on Windows, and I'm not sure if it would be stable on other systems. For example, I don't know what will happen if you send a command to R when it still is executing another command. Also, I don't know how long Nvim-R should wait after sending to nvimcom the command to update the width before actually sending the command to R Console; perhaps 10 milliseconds would be enough, but perhaps not for all systems.

   5. **Do not set the 'number' option for the R Console window.** That is, put in your `init.vim`:
```
autocmd TermOpen * setlocal nonumber
```

**Comment by ashiklom** [comment]
I'd be perfectly happy with an even simpler version of **2**, whereby the R console width is adjusted by an integer value specified by the user -- e.g. `R_shrink_width_by = 6`.

3 also sounds like a great option. At least for me, my console width doesn't change very often -- in fact, I like to `set wfw` on my terminal window to keep it from doing so.

In the meantime, I'll do **5** locally to work around the problem. Might not be a bad idea to add a sentence to the documentation about this.

**Comment by jalvesaq** [comment]
I implemented **2** and **3**, but instead of creating the new option `R_shrink_width_by`, the option `R_setwidth` now also accepts negative numbers, as described in the documentation.

**Comment by ashiklom** [comment]
This is perfect, thanks!
