### ISSUE TITLE
E118: Too many arguments for function: ROnJobStdout

### ISSUE THREAD

**Issue by webbp** [jalvesaq/Nvim-R#311]
I see this message every time I open an R file in nvim:
`E118: Too many arguments for function: ROnJobStdout`

Workaround:
```
bundle/Nvim-R/R/nvimrcom.vim:19:
- function ROnJobStdout(job_id, data)
+ function ROnJobStdout(job_id, data, dummy)
```

Investigating further, here is an odd thing:
```
+ 20   call append(line('$'), dummy)
```
yields
```
Error detected while processing function ROnJobStdout:
line    2:
E121: Undefined variable: dummy
```

**Comment by jalvesaq** [comment]
What version of Nvim-R are you using? The function `ROnJobStdout` starts on line 24, and it already receives three arguments:
```
function ROnJobStdout(job_id, data, etype)
```

**Comment by webbp** [comment]
Oops yeah `vim-plug` `:PlugUpdate` fixed it :) Sorry for taking up your time.
