### ISSUE TITLE
How to automatically `:set bufhidden=hide` for the R terminal buffer?

### ISSUE THREAD

**Issue by sieste** [jalvesaq/Nvim-R#312]
I want to locally set the R terminal buffer hidden so that it doesnt get deleted when I switch to a different buffer with `:bnext`. At the moment I start the R session with `\rf` and then manually call `:set bufhidden=hide` in the terminal buffer. Can this be automated with a vimrc entry? 
 
Thanks!

**Comment by jalvesaq** [comment]
Please, look for the example of either `TermOpen` (Neovim) or `TerminalOpen` (Vim) in the documentation.

**Comment by sieste** [comment]
Thanks, I added to vimrc

    autocmd TermOpen * :set bufhidden=hide

**Comment by jalvesaq** [comment]
If you use both Vim and Neovim, then you need this:

```vim
if has('nvim')
  autocmd TermOpen * :set bufhidden=hide
else
  autocmd TerminalOpen * :set bufhidden=hide
endif
```
