### ISSUE TITLE
let R_tmux_split = 1 disappears

### ISSUE THREAD

**Issue by smilesun** [jalvesaq/Nvim-R#313]
Now when I open a R session, the console does not appear in the tmux split, anyway to fix this?

**Comment by smilesun** [comment]
sorry, I am stupid, just find the answer here: https://github.com/jalvesaq/Nvim-R/blob/master/R/tmux_split.md

but one question to ask: do you really want to remove the tmux integration in the future? I could not believe this since this is so convenient

**Comment by jalvesaq** [comment]
I will not add new features to Tmux split because I no longer use it, but I will drop the integration in the future only if it becomes buggy. Currently, the code is working, but if someone wants to maintain it, then, the steps are:

- Create a new repository.
- Copy both tmux_split.vim and tmux_split.md (renamed as README.md) to the new repository.
- Tell me the link to the repository, so I can add the link to Nvim-R documentation.

**Comment by zippeurfou** [comment]
@jalvesaq Is there a way to do some key remapping?
I have a very specific way to navigate in tmux/vim that I would like to keep.
Here is my `.tmux.conf` part that is relevent:
```
# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n C-h if-shell "$is_vim" "send-keys C-h"  "select-pane -L"
bind-key -n C-j if-shell "$is_vim" "send-keys C-j"  "select-pane -D"
bind-key -n C-k if-shell "$is_vim" "send-keys C-k"  "select-pane -U"
bind-key -n C-l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"
bind-key -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"
bind-key -T copy-mode-vi C-h select-pane -L
bind-key -T copy-mode-vi C-j select-pane -D
bind-key -T copy-mode-vi C-k select-pane -U
bind-key -T copy-mode-vi C-l select-pane -R
bind-key -T copy-mode-vi C-\ select-pane -l
#Remap so I can resize easily
bind J resize-pane -D 10
bind K resize-pane -U 10
bind H resize-pane -L 10
bind L resize-pane -R 10
```
As you can see I can navigate from pane to pane by using CTRL + H/J/K/L which I find very handy. I was able to do it using the `R_tmux_split` before. I have been looking at the doc and it seems I have to press ctrl + w + w for example. However it seems there is no way to change it (from `Nvim-R-key-bindings`) let alone use it in the way I want it.
Am I missing something?

**Comment by jalvesaq** [comment]
All Nvim-R key bindings start with `<LocalLeader>`, so I think you should not have any conflict between Nvim-R key bindings and your Tmux key bindings.

I did not change anything relevant in the R/tmux_split.vim script. You should be able to use R running in a Tmux split as you used to do before.

The command <kbd>Ctrl</kbd>+<kbd>w</kbd>+<kbd>w</kbd> is a Vim command; it was not defined by Nvim-R.

**Comment by zippeurfou** [comment]
@jalvesaq somehow it does not work, I can successfully go into the `aR  "!R [running]"` buffer but I can't exit it with the shortcut I have defined. Meanwhile if I `:vs` it does work correctly.

**Comment by jalvesaq** [comment]
I can't see any problem here while running R in either Vim or Neovim buffer. R starts with `<LocalLeader>rf` and quits with `<LocalLeader>rq`. What key binding have you defined to quit R?

**Comment by jalvesaq** [comment]
Probably you have to press <kbd>Ctrl</kbd>+<kbd>\\</kbd>+<kbd>Ctrl</kbd>+<kbd>n</kbd> to go to what Vim calls Terminal-normal mode. See: `:h Terminal-mode`.

**Comment by zippeurfou** [comment]
funny enough doing `nnoremap <C-H> <C-W><C-H>` and then `<C-H>` do not work but calling `<C-W><C-H>` do works. Is there a reason for that?

**Comment by jalvesaq** [comment]
Please, search the string ":tmap" in `terminal.txt` (Vim documentation). I rarely remap Vim key bindings, and never remapped terminal key bindings, but I guess the solution is there.

**Comment by zippeurfou** [comment]
@jalvesaq I found some "issues" playing with the terminal way in vim.
1.  `Ctrl`+`\`+`Ctrl`+`n` works perfectly but if I do `Ctrl`+`\`+`n` then R exit which is pretty frustrating as you can guess.
https://cl.ly/243d2S3T1v1F
2. resizing iterm2 or showing the documentation change the size of the terminal pane
https://cl.ly/2T292i103F02

**Comment by jalvesaq** [comment]
1. Does not happen with Neovim, only with Vim.

2. This is a know issue. Please, see #52. Some people have played with 'winfixwidth'. You can also try different values for `R_nvimpager`.

**Comment by josswright** [comment]
I'm having some complications with this here. My use case is that I use this to start R in a separate terminal window to give me flexibility in arranging my windows. (I typically have a half-screen vim window, then the other half split between plot output at the top, and the R console at the bottom -- this isn't something that can be done with an internal vim buffer.)

I've just copied the tmux_split.vim file as shown above, but when opening R _without_ being in tmux I get: 

```
Error detected while processing function ROnJobStdout[7]..RSetMyPort[4]..FinishStartingR:                                                                      
line  143:                                                                                                                                                     
E117: Unknown function: StartR_ExternalTerm 
```

**Comment by jalvesaq** [comment]
Puting this in your vimrc should fix the issue:

```vim
if $TMUX != ''
    R_source = '/path/to/tmux_split.vim'
endif
```

**Comment by josswright** [comment]
Thanks for the quick reply.

I've now got this in my init.vim:
```
if $TMUX != ''
	let R_source = '$HOME/.config/nvim/opt/tmux_split.vim'
endif
let R_in_buffer = 0
let R_term_cmd = "kitty"
```

When I hit <LocalLeader>rf then my terminal starts with R. When I try to send any code to the R instance, though, such as <LocalLeader>l or <LocalLeader>aa, I get this error:
```
usage: paste-buffer [-dpr] [-s separator] [-b buffer-name] [-t target-pane] 
```

For any subsequent commands, I get:
```
Did you already start R? 
```

**Comment by statquant** [comment]
@josswright check again I think @jalvesaq might have fixed this today

**Comment by josswright** [comment]
That does seem to have fixed it! Thanks for letting me know. (And thank you @jalvesaq for taking the time.)
