### ISSUE TITLE
compilation failed for nvimcom

### ISSUE THREAD

**Issue by winmos** [jalvesaq/Nvim-R#315]
dear all,

since i switched to nvim-r, i can't seem to get nvimcom working.
i get the error-message below. i tried installing nvimcom inside R but that doesn't work either.
i switched from vim 8 to neovim: no effect.

in some threads it is stated, that building nvimcom manually might help, but i didn't find hints where to get the actual nvimcom tar.gz-file.

any help appreciated!

thank you

winfried

error-message:
***********************************************************************
function (howWide = Sys.getenv("COLUMNS")) 
{
    options(width = as.integer(howWide))
}
* installing to library ‘/home/winfried/R/x86_64-pc-linux-gnu-library/3.4’
* installing *source* package ‘nvimcom’ ...
** libs
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c nvimcom.c -o nvimcom.o
/bin/bash: gcc: Befehl nicht gefunden
/usr/lib/R/etc/Makeconf:159: die Regel für Ziel „nvimcom.o“ scheiterte
make: *** [nvimcom.o] Fehler 127
ERROR: compilation failed for package ‘nvimcom’
* removing ‘/home/winfried/R/x86_64-pc-linux-gnu-library/3.4/nvimcom’
***********************************************************************

**Comment by jalvesaq** [comment]
You have to install `gcc`.

**Comment by winmos** [comment]
hi,
gcc is already installed.

Jakson Alves de Aquino <notifications@github.com> schrieb am Fr., 6. Apr.
2018, 23:30:

**Comment by jalvesaq** [comment]
The error message is

> /bin/bash: gcc: Befehl nicht gefunden

**Comment by winmos** [comment]
obviously i had problems with my gcc installation. i installed it before, i also installed build-essental. researching my /usr/bin i found multiple instances of gcc (gcc-5, gcc-6, ...) but not a file named only "gcc". so i symlinked gcc to gcc-6.

afterwards the error-message sligthly changed: nvim-r complained, that g++ is missing. it turned out, that the situation with g++ was the same than with gcc. i tried the same solution as above.

that finally worked.

:-) 

thank you for that great plugin!!
i have been using it for years now.

**Comment by jalvesaq** [comment]
@winmos you should either manually install gcc or use a package manager. Manually changing files in the installation made by a package manager might be a precarious solution. If gcc is updated to gcc-7, your symbolic link will stop working, and you may no longer remember of having created it.

It might be better to completely uninstall gcc and install it again.

**Comment by winmos** [comment]
@jalvesaq thank's for the hint! i tried to install gcc several days via apt-get. but that didn't work. therefore
i resorted to the solution stated above. what i could have done is trying to uninstall gcc before, i didn't do that. alas: i will update to ubuntu 18.04 within the next weeks and hope, that this problem will be gone then anyway...
