### ISSUE TITLE
Syntax highlighting disappears when using external terminal

### ISSUE THREAD

**Issue by fennerm** [jalvesaq/Nvim-R#316]
When using an external terminal the syntax highlighting seems to work when the REPL is first started, but disappears as soon as you run a single command in the REPL. This doesn't happen for me when run in a vim split.

Here's a screencap showing the problem:

![scaled](https://user-images.githubusercontent.com/13209544/38446307-1dc98fc8-39ac-11e8-9f5f-ab28de0ed155.gif)

This was produced with a minimal vimrc containing just the following:

```vim

call plug#begin('$VIM/plugged')
Plug 'jalvesaq/Nvim-R'"
let g:R_hi_fun = 1
let g:R_in_buffer = 0
let g:R_term = 'urxvt'
call plug#end()
```

System: Arch Linux
Editor: Neovim
Terminal: urxvt

**Comment by jalvesaq** [comment]
I'm sorry, but I can't replicate the issue with the development version of Neovim, and using an `init.vim` similar to the above one.

**Comment by fennerm** [comment]
Oh no :(. It probably some file in my system neovim config then. Apologies for the wild goose chase, I'll let you know if I find out anything relevant.
