### ISSUE TITLE
auto completion of brackets

### ISSUE THREAD

**Issue by smilesun** [jalvesaq/Nvim-R#323]
Hi, is it possible that when I type  `fun1 = functi`, it can automatically complete the bracket and the rest of letters?  `fun1 = function(){}`

**Comment by jalvesaq** [comment]
Maybe what you want is a snippet plugin. I no longer use any such plugin, but you could look for "snipMate", "Ultisnip" or "neosnippet". Nvim-R includes an example of snipMate file for the R language: https://github.com/jalvesaq/Nvim-R/blob/master/R/r.snippets

**Comment by aenda** [comment]
Furthermore, ultisnips has support for moving the cursor through your snippet. My typical workflow for writing some function might be type `fun<C-j>` which will expand to full function definition and select the function name, type `fun1<C-j>arg1, arg2<C-j>return arg1 + arg2`. So I never had to type out `function`, `()`, or `{}`, but my end result is
```
fun1 <- function (arg1, arg2) {
    return arg1 + arg2
}
```
All I need in my vimrc for this is loading `Plug 'SirVer/ultisnips'` and
`let g:UltiSnipsExpandTrigger="<C-j>"`

There are also plugins for autoexpanding/closing brackets like vim-closer and auto-pairs (which can work in conjunction with vim-surround) which have somewhat related functionality to your question.
