### ISSUE TITLE
\o (evaluate and insert output as comment) fails if line contains a semicolon

### ISSUE THREAD

**Issue by dryya** [jalvesaq/Nvim-R#324]
\o works fine for me except when the line I want to evaluate has a semicolon in it, which I am assuming fails to get escaped somehow - I haven't taken a look at the code. The error I get is
"Error: VECTOR_ELT() can only be applied to a 'list', not a 'NULL'".

This occurs for me even with a very minimal vimrc with just nvim-r. 
```
set rtp^=$HOME/.dotfiles/nvim
call plug#begin('$HOME/.dotfiles/nvim/plugged')
Plug 'jalvesaq/nvim-r'
call plug#end()
```

![2018-04-19-182223_swaygrab](https://user-images.githubusercontent.com/4873173/39023157-a2a7a46c-43fe-11e8-9215-1268075fe263.png)

Let me know if you can reproduce.

**Comment by aenda** [comment]
OK, so this will fail in any case where a line is valid R code but has some characters print doesn't like, such as if there is a comment at the end. Would it be worthwhile for me to look into sanitizing input when I have some time, or is that outside the scope of nvim-r? If so, are there any other relevant parts of nvim-r besides the SendLineToRAndInsertOutput() function, and would there be anything else that is valid R "code" but breaks print besides ';' and '#'?

It seems to me that any inline comments could simply be removed before the line is sent, and `foo(); bar()` could turn into
```
{
  foo()
  bar()
}
```
before being sent.

**Comment by jalvesaq** [comment]
> would there be anything else that is valid R "code" but breaks print besides ';' and '#'?

I don't know. Someone requested this functionality (`\o`), and I implemented it, but I have never used it.
Nvim-R should sanitize the line. I will remove the `#` and eveything to the right of it, and, please, post here any other cleaning that you think is necessary.

The code evaluated by `nvimcom` is prefixed with the byte `\x08`. So, to find all parts of Nvim-R that might generate invalid R code, you should search for `SendToNvimcom("\x08"`.

**Comment by jalvesaq** [comment]
Nvim-R is being superseded by R.nvim, a new project that will be inaugurated in a week at the [R-nvim](https://github.com/R-nvim) organization.
Please, check out [tmp-Nvim-R](https://github.com/jalvesaq/tmp-R-Nvim) and help us to find the last remaining bugs before R.nvim inauguration.
When the project is officially started, you will be able to open issues there and request new features.

Nvim-R will remain alive as a feature-frozen project for Vim users. If you want to know the reason, please, see [this discussion](https://github.com/jalvesaq/Nvim-R/discussions/797).
