### ISSUE TITLE
Can you add a command to rebuild a package

### ISSUE THREAD

**Issue by statquant** [jalvesaq/Nvim-R#328]
Hello when I build a package I find convenient to be able to rebuild it on demand
I have 
`nmap <LocalLeader>zz :update<CR>:call g:SendCmdToR('system(sprintf("R --vanilla CMD INSTALL %s --no-multiarch --with-keep.source --no-lock", here::here()))')<CR>`

`here::here` is from the here package that uses the heuristics to find the .closest Rproj then .git/.svn from getwd().
Maybe you can do better from within vim because you'll have the file the user is looking at so you can start from this file.
Do you feel adding something along those lines ?

**Comment by jalvesaq** [comment]
Please, look at this:
https://github.com/mllg/vim-devtools-plugin
I have never used it, but perhaps it has what you want.
