### ISSUE TITLE
Can you use base::source(..., local=TRUE) for <mapleader>ff

### ISSUE THREAD

**Issue by statquant** [jalvesaq/Nvim-R#329]
I see when I do `<mapleader>ff` that a tmp file is created with this function and that you call `base::source(tempFile, print.eval=TRUE)`, the problem is that in debug mode you are not in the same environment. At least when I debug packages I cannot use `<mapleader>ff` because of this (the updated code is updated only in `.GlobalEnv`).

Could you make it  `base::source(tempFile, print.eval=TRUE, local=TRUE)` because that would work in debug mode. 
I tested it manually and it solves it

**Comment by jalvesaq** [comment]
Please, see `:h R_source_args`.
