### ISSUE TITLE
Console height increased after opening terminal in nvim

### ISSUE THREAD

**Issue by ranranking** [jalvesaq/Nvim-R#33]
For example, I set R_rconsole_height=3. After I opened neovim terminal in horizontal split window and closed it, the R console height would increase. But this situation won't happen when I use Unite, which also opens a buffer in split window. After I closed Unite, the R console height kept unchanged. Is it a problem from neovim? or is it a problem from Nvim-R?

**Comment by jalvesaq** [comment]
I think neither Vim nor Neovim record the window's size. I don't use Unite. Could you, please, detail the procedure to reproduce Unite behavior, so I could install Unite and see what it does.

**Comment by ranranking** [comment]
Oh, thank you for the help. If you want to try Unite, you can simply use ':Unite -auto-resize -here file/a sync' and see whether it's working. Although in my case, when using Unite, for a very small amount of time, the console height increased, and it went back immediately.

**Comment by ranranking** [comment]
I am not sure whether other fuzzy finder plugins have the same behavior, like fzf and ctrlp

**Comment by jalvesaq** [comment]
I can see that when the Unite window is closed the the two windows (R script and R) go back to their original sizes. But the same happens after using Vim help. Example: `:h vsplit`.
I don't know how to make Vim/Neovim restore the windows sizes after, for example, pressing in Normal mode `<c-w><s-h><c-w><s-k>`, where `<c-` is CTRL and `<s-` is SHIFT.

**Comment by ranranking** [comment]
Yes, this seems to be weird. So this is Neovim/Vim's problem? Do you know the possible reason why windows can go back to the original sizes when using help windows or Unite windows but when using the terminal windows, they can not?

**Comment by jalvesaq** [comment]
Options 'winheight', 'winminheight' and 'winfixheight' should do the trick, but they are not working as I expect. Please, see `:h windows`.

**Comment by ranranking** [comment]
Yes, I saw these options, but I am not sure how to use these options in R console window

**Comment by jalvesaq** [comment]
It's confusing because it seems that 'winheight' and 'winminheight' are almost the same thing. Now, I have a better understanding of how they work.

You should not set anything in the R console window because the options only try to guarantee the minimum height. Thus, if you want a small R Console window you have to set a large 'winheight' for the script window. For example, in my terminal, nvim returns "44" for `:set lines?`. Nvim needs 1 line for the ruler and two for the status lines of the two windows. Hence, if I want the R Console window with 4 lines, I have to go to the script window and `:set winheight=37`.

Interestingly, if I `:set winheight=37` before starting R, the focused window (either the terminal or the script) will always be 37 lines high.

**Comment by ranranking** [comment]
I tried this:
```vim
  autocmd Bufreadpre *.r setlocal winheight=40 
```
This works fine with me. I opened a r file, the window is regular full screen. After I opened R and opened terminal and can closed it, the R console window didn't change, and after I closed R, the script window returned to normal full screen. 

I can not set `winminheight`, it kept saying the winheight should not be smaller than winminheight even though I didn't set up a winheight.

**Comment by jalvesaq** [comment]
I still don't understand 'minwinheight'...

I think I should not try to mess with 'winheight' in the plugin because it will be impossible to make all users happy. Some will prefer never setting the option, others will prefer to set it before starting R and still others, after starting R.

**Comment by ranranking** [comment]
Yes, I think you don't have to put this into the plugin. I am already happy that I can set the window height now. Thank you for the help!
