### ISSUE TITLE
When debuging and reaching an error in a plot I seem to get in a loop

### ISSUE THREAD

**Issue by statquant** [jalvesaq/Nvim-R#331]
When I am in debug mode and debug a plot function I get the strangest behaviour where the error seem to be stuck in some kind of loop.
I'll try to post something reproducible
![image](https://user-images.githubusercontent.com/3612473/40161994-5f9cbee8-59aa-11e8-89ba-f32dcfa118c4.png)

**Comment by jalvesaq** [comment]
Are you using the function `mtrace` from the package `debug`?
```r
library(debug)
mtrace(your.function)
your.functiion()
```

**Comment by jalvesaq** [comment]
I don't know how to replicate the issue. I've tried the following:
```
b <- 1:33
Nothing <- function(x) {
    browser()
    y <- x + rnorm(length(x), mean = mean(x))
    m <- lm(y ~ x)
    plot(m)
}
Nothing(b)
```
I have to press <kbd>Enter</kbd> in the R Console to advance in the code, but if I send commands from the editor to the R Console, such as `summary(y)`, the code is executed normally.

**Comment by jalvesaq** [comment]
I close the issue because I can't replicate it.

**Comment by statquant** [comment]
I think this is due to using debugging in parallelism.

**Comment by jalvesaq** [comment]
I added limited debugging functionality to https://github.com/jalvesaq/Nvim-R/tree/debug

I will merge the `debug` branch soon.
