### ISSUE TITLE
Console non-responsive after loading larger files

### ISSUE THREAD

**Issue by cfbeuchel** [jalvesaq/Nvim-R#332]
Hi! 

I'm using the most recent version of  Nvim-R (0.9.11.1), both on Neovim 0.2.2 and 0.2.0 (multiple systems - openSUSE Leap 42.3 and on my personal laptop on Ubuntu Mate 16.04.4 LTS), sometimes accessing the openSUSE version via ssh and sometimes by accessing files via sshfs.

I only recently started using nvim+Nvim-R and the plugin is working very nicely for me. However, currently I am experiencing this issue of a frozen terminal on all my systems, all while using the same setup, i.e. the same init.vim.

The issue occurs on a project that requires me to work on relatively large (up to 1GB) files with both several thousand rows and columns (~3,000 rows and 20,000 columns, 50,000 rows and 4,000 columns etc.). Normally, this shouldn't be a problem for R and never has been on RStudio but when loading the files via Nvim-R, the terminal buffer experiences some kind of freeze a few seconds after loading the file. I am able to navigate the console and do the following things:

* calling `help(foo)` opens the correct manual entry in the help-buffer opened via \rh
* calls to non-existent objects result in a `... not found` error-message
* calling `update.packages()` does not return the usual `"Packagename":  Version x.x.x.x is available...` dialog but only the `Update (y/N/c)?` dialog
* Otherwise, the update function is responding as is expected
* Tab-completion in the console works

What does not work is the calling of existing objects, numers or functions. These only result in the dissapearance of the '>' promt for a few seconds (~20) and a subsequential re-appearance with no output being produced. 

Anyway, I am turning into a big fan of nvim and Nvim-R and enjoy working from the terminal, but I need to process these rather large and larger files. 

I would appreciate any comments or ideas on why this occurs on my system. I wasn't able to find any discussion on a similar issue and would also be thankful for directions in case this has been discussed already. Thanks for your help!

**Comment by jalvesaq** [comment]
Perhaps nvimcom is taking too much time to list all objects from R's workspace. You could try:

  1. Don't open the Object Browser.

  2. Don't load the [ncm-R](https://github.com/gaalcaras/ncm-R) plugin.

  3. Put in your init.vim: `let R_hi_fun_globenv = 0`

**Comment by cfbeuchel** [comment]
I adopted all your suggestions and everything is working flawlessly now! It does look like ncm-R was the problem. Leaving the Object Browser did not cause the any negative changes after removing ncm-R. However, R does experience some lag. `R_hi_fun_globenv` was set to `0` by default if I am not mistaken. Closing the Object Browser and setting `R_hi_fun_globenv = 0` while leaving ncm-R active did also return functionality of the console but with a severe lag.

So I believe we identified our culprit. Deactivating ncm, ncm-R and UltiSnips restored the performance. 

Thank you for quick and helpful reply!

**Comment by jalvesaq** [comment]
Please, see the documentation on `R_ls_env_tol`.

**Comment by cfbeuchel** [comment]
Thank you for further addressing this issue! If I understand correctly, this would allow me to keep ncm-R loaded in my .vimrc and I wouldn't have to disable ncm-R by hand when working on larger files? This surely seems to be a nice and convenient solution.

**Comment by jalvesaq** [comment]
> If I understand correctly, this would allow me to keep ncm-R loaded in my .vimrc and I wouldn't have to disable ncm-R by hand when working on larger files?

Yes, but it wasn't well tested yet.
