### ISSUE TITLE
Vim 8.1 error

### ISSUE THREAD

**Issue by blayz3r** [jalvesaq/Nvim-R#333]
I get errors when I start R in vim 8.1 and try to send text, this might be related to the changes in the vim terminal feature

![image](https://user-images.githubusercontent.com/12205650/40227737-4e43e3de-5a5d-11e8-894c-17fd09377f49.png)

**Comment by jalvesaq** [comment]
I installed Vim 8.1 on Windows and didn't see errors, but I don't have airline installed and I have run R only briefly.

**Comment by blayz3r** [comment]
It works for the most part without airline, but once airline is installed you get the error

**Comment by jalvesaq** [comment]
The error happens in vim-airline code. So, you should report the issue at [vim-airline](https://github.com/vim-airline/vim-airline). Please, reopen the issue if you are sure that it's a Nvim-R bug.
