### ISSUE TITLE
Set omnifunc depending on cursor position in Rmarkdown files

### ISSUE THREAD

**Issue by sorennikolaus** [jalvesaq/Nvim-R#334]
Disclaimer: I am pretty new to vim and vimscript.

It would be great to be able to set the omnicompletion function based on the current cursor position in the file (like a polymode autocompletion). So one would be able to complete R code as well as citations (and at a later point even text cross references from bookdown/pandoc-crossref) when editing dynamic documents. From what I know, no text editor delivers something like this yet. Your work, @jalvesaq, made it incredibly easy for me to hack together a working solution in minutes. The `insertEnter` event might be a great candidate to fire an autocomand.

My solution is by no means generalizeable yet. At the moment the alternative to `CompleteR` points to `pandoc#completion#Complete` (so [vim-pandoc](https://github.com/vim-pandoc/vim-pandoc) has to be installed). The only way to make it filetype speicific, i.e. guarantee that the following is solely executed within the scope of Rmd files is to include it in a proper filetype plugin, right?  Anyway, here is the code (currently in my init.vim): 
```
augroup completion
  autocmd!
  autocmd insertEnter * call SetOmnifuncRmd() 
augroup END

function! SetOmnifuncRmd()
  if RmdIsInRCode(0) == 0
    setlocal omnifunc=pandoc#completion#Complete
    return
  endif
  setlocal omnifunc=CompleteR
endfunction
```

**Comment by sorennikolaus** [comment]
Okay, I've [learned something](https://neovim.io/doc/user/filetype.html) again and the above is now contained in my personal `~/.config/nvim/after/ftplugin/rmd.vim`. That basically is an answer to my last question.

**Comment by jalvesaq** [comment]
Thanks for reporting the issue. It should be fixed now. Could you, please, delete your `~/.config/nvim/after/ftplugin/rmd.vim` and try again?

**Comment by sorennikolaus** [comment]
Thank you. But the fix doesn't seem to work yet. When opening an Rmarkdown file without the above fix (with vim-pandoc installed) the `&omnifunc` is initially set to `pandoc#completion#Complete`, what of course never changes.

**Comment by jalvesaq** [comment]
Vim runtime files are outdated. Please, install [R-Vim-runtime](https://github.com/jalvesaq/R-Vim-runtime).

**Comment by sorennikolaus** [comment]
With the updated runtime files it is now working as expected. Thank you for your fast response!
