### ISSUE TITLE
2 windows 10 encoding problem

### ISSUE THREAD

**Issue by ddtpower3** [jalvesaq/Nvim-R#335]
Hi jalvesaq,

I'm new to nvim-r, so please ignore my report if you have known about these.
My windows language is Chinese. I'm working with a portable gvim8, and its enc and fenc is set utf8. After I installed  nvim-r and tried to start R with \rf, it didn't work. So I traced into the problem and found it's because my HOME directory in win10 is named with Chinese character. When nvimcom_path.R is written, it has some Chinese with UTF-8 coding, but R can't understand it. After I add '--encoding UTF-8' to R command line, R can be started without any problem.

The second problem happened when I try to send code to R from vim. If there is any Chinese character in the path of my working directory. The temp R code file can be write by vim, but Rgui can't parse the file path correctly. Here is the relevant  code in common_global.vim(line 1383):
    let ok = g:SendCmdToR('nvimcom:::source.and.clean("' . fpath .  '"' . sargs . ')')
It seems when fpath is encoded with UTF-8, R can't parse it properly even I've set R_source_args to 'encoding="UTF-8"' in my vimrc. Is there any options I can use?

Thanks,

**Comment by ddtpower3** [comment]
I find a solution for the 2nd issue, I add a line in function SendCmdToR_Windows, if vim encoding is 'utf-8'
let cmd = iconv(cmd, 'utf-8','gbk'), and nvimr now can work perfectly on my laptop. I hope this can be help.

**Comment by ddtpower3** [comment]
Just a thought. Maybe vim variables should not be send to R without iconv, since vim internal encoding is different from R default encoding which is default 'native.enc'.  Neither SendCmdToR nor JobStdin can have R handle path args with multibyte characters in it properly.

**Comment by jalvesaq** [comment]
Thanks for your contribution! Could you do a pull request for this?
