### ISSUE TITLE
Scroll up / down

### ISSUE THREAD

**Issue by LiNk-NY** [jalvesaq/Nvim-R#336]
Hi Jackson, @jalvesaq 
I've finally switched to using the Nvim-R buffer rather than `tmux`. 
One issue I'm having is that I am unable to scroll up in the R buffer.

I didn't spot any mention of scrolling in the documentation. 

Thank you for your attention. 

Best regards,
Marcel

**Comment by mschilli87** [comment]
@LiNk-NY: Did you try <kbd>Ctrl</kbd>+<kbd>F</kbd>/<kbd>Ctrl</kbd>+<kbd>B</kbd>? How do you scroll in your editor buffer?

**Comment by LiNk-NY** [comment]
Thanks Marcel for your quick response. I can scroll without a problem in the editor buffer. 
Those key combinations do not work for me in the R buffer, unfortunately. 
I am used to using the mouse-mode or scrolling with `<ctrl + b> [ + PgUp` in `tmux`.

**Comment by jalvesaq** [comment]
If the terminal is in TERMINAL mode, I press `<Esc>` to go to NORMAL mode. Then, I use Vim's motion commands in Normal mode (`j`, `k`, `l`, `h`, `gg`, `G`, etc).

**Comment by mschilli87** [comment]
@LiNk-NY : As @jalvesaq pointed out, I assumed you are in NORMAL mode when trying to scroll. Should have mentioned the <kbd>Esc</kbd> just in case.
Isn't that the main power of vim, that it becomes so natural that we have issues explaining how we do thing we do all day? :wink:

**Comment by LiNk-NY** [comment]
Thank you @jalvesaq @mschilli87 for your responses. 

Unfortunately, that doesn't solve it for me. [Esc] does nothing in the R console.
I've posted my `~/.vimrc` as a gist. Relevant lines start [here](https://gist.github.com/LiNk-NY/511af1e43d8296e85881031d62706245#file-vimrc-L49).

**Comment by mschilli87** [comment]
@LiNk-NY:  Wait, is this Vim or NeoVim you are using?

From your statement

>I've finally switched to using the Nvim-R buffer rather than tmux.

I assumed we talk about NeoVim.
But

> I've posted my ~/.vimrc as a gist.

seems to imply Vim.

**Comment by jalvesaq** [comment]
In Vim you have to press `CTRL-\ CTRL-n` to go to what is equivalent to NORMAL mode.

**Comment by LiNk-NY** [comment]
Yes, I'm using vim with the Nvim-R plugin. 
I didn't realize I needed to switch to NORMAL mode. Thanks all!

**Comment by LiNk-NY** [comment]
Hi Jackson, @jalvesaq

Just one more thing: 
I want to map the <kbd>Esc</kbd> key to NORMAL mode (<kbd>Ctrl</kbd> <kbd>\\</kbd> + <kbd>Ctrl</kbd> <kbd>N</kbd>) within the R buffer in my `~/.vimrc`. 
I am aware of the `R_esc_term` option but `let R_esc_term = 1` in my `~/.vimrc` isn't working. 

Your feedback is appreciated.

Regards,
Marcel

**Comment by jalvesaq** [comment]
I don't remember what I have done, but most probably I've tried to map the `Esc` key in Vim and it did not work. That's why Nvim-R maps the key only in Neovim.

**Comment by LiNk-NY** [comment]
Thanks for all your help!
