### ISSUE TITLE
"q" triggers recursive mapping on rdoc

### ISSUE THREAD

**Issue by leogama** [jalvesaq/Nvim-R#337]
https://github.com/jalvesaq/Nvim-R/blob/f2bf13c7bdc51103b13e29bfad90f9713f69dd91/ftplugin/rdoc.vim#L138

Just need to substitute `nmap` by `nnoremap`.

**Comment by jalvesaq** [comment]
Thanks for reporting the problem and how to fix it!
Should I replace all instances of `map` with `noremap` in Nvim-R?
