### ISSUE TITLE
Repeated useless "installing nvimcom" with multiple users sharing the same R library

### ISSUE THREAD

**Issue by webbp** [jalvesaq/Nvim-R#338]
Multiple users share the same .Rprofile and .libPaths()[1] so that we can all install and share libraries without issue...without issue, except for nvimcom: whenever a different user launches nvimr, nvimcom gets unnecessarily reinstalled, but now owned by the other user. This costs us crucial seconds of potential data analysis every day ;)

**Comment by jalvesaq** [comment]
`R_compldir` does stores any personal information, only information extracted from packages, and about nvimcom installation. So, I think the issue will be solved if all users set `R_compldir` in their vimrc with the same value. Example:

```vim
let R_compldir = '/path/to/shared_Nvim-R_cache"
```

**Comment by jalvesaq** [comment]
> R_compldir does stores any personal information

The correct is: Nvim-R does not store any personal information in the `R_compldir` directory.

**Comment by webbp** [comment]
Thanks! I will try that.

**Comment by jalvesaq** [comment]
Another option, that will not require your users to edit the vimrc, is creating a symbolic link from `~/.cache/Nvim-R` to a shared directory. But the symbolic link would have to be created by each user anyway.

**Comment by jalvesaq** [comment]
@webbp Did you solve the problem? Other people might benefit from the solution...

**Comment by webbp** [comment]
@jalvesaq Sorry, I believe that one of the solutions did work, but I don't remember which one, and I no longer have a shared .Rprofile and .libPaths with another Nvim-R user, so the problem hasn't recurred.

**Comment by webbp** [comment]
@jalvesaq while I have your attention, what's your recommended way of disabling an Nvim-R keystroke? Specifically, I want to unmap underscore to <-.

**Comment by jalvesaq** [comment]
> Specifically, I want to unmap underscore to <-.

```
let R_assign = 0
```

For other key bindings you could map them for some combination of keys that you would never use. Example:

```
nmap JJC <Plug>RSimpleComment
```

**Comment by webbp** [comment]
Thanks!!
