### ISSUE TITLE
Win7 Failed to install nvimcom - make: cc: command not found

### ISSUE THREAD

**Issue by n31k** [jalvesaq/Nvim-R#339]
* installing to library 'c:/R/r-3.5.0/library'
* installing *source* package 'nvimcom' ...
** libs
c:/Rtools/mingw_32/bin/gcc  -I"c:/r/r-3.5.0/include" -DNDEBUG       -D`c:/r/r-3.5.0/bin/R --slave -e 'cat(Sys.info()[[1]])'` -DLWS_NO_FORK  -DWIN32   -O3 -Wall  -std=gnu99 -mtune=generic -c nvimcom.c -o nvimcom.o
c:/Rtools/mingw_32/bin/gcc -shared -s -static-libgcc -o nvimcom.dll tmp.def nvimcom.o -lWs2_32 -Lc:/r/r-3.5.0/bin/i386 -lR
(cd apps; make -f Makefile.win)
make[1]: Entering directory '/Users/user/AppData/Local/Temp/RtmpAn8u6R/R.INSTALL1d101c525192/nvimcom/src/apps'
cc -m32 -mwindows -std=gnu99 -O3 -Wall -DWIN32 nclientserver.c -o nclientserver.exe -lWs2_32
make[1]: cc: Command not found
make[1]: *** [Makefile.win:10: nclientserver.exe] Error 127
make[1]: Leaving directory '/Users/user/AppData/Local/Temp/RtmpAn8u6R/R.INSTALL1d101c525192/nvimcom/src/apps'
make: *** [Makevars.win:11: nvimapps] Error 2
ERROR: compilation failed for package 'nvimcom'
* removing 'c:/R/r-3.5.0/library/nvimcom'

**Comment by jalvesaq** [comment]
> make[1]: cc: Command not found

The C Compiler was not found. Did you install RTools?

**Comment by n31k** [comment]
Yes!

**Comment by jalvesaq** [comment]
Perhaps you can find something useful in the output of:
```
:RDebugInfo
```

**Comment by n31k** [comment]
I think it has something to do with the version of RTools? Or R for that matter?

**Comment by jalvesaq** [comment]
It might be RTools, Cygwin, environment variables, your .Rprofile, etc.
The last time that I rebooted my laptop on Windows, I tested Nvim-R with R 3.5.0, so I guess R is not the problem.

I don't use Windows, and the support for Windows is difficult to maintain. Perhaps someone else can help you with this issue...

**Comment by n31k** [comment]
We had discussed this in the past, and you had then suggested to use  RTools 3.3

It fixed it this time as well!

I think this is how I got it to work last time. I now notice that this version has a separate gcc-[version] dir and it also adds it to the path during installation. Perhaps this is why this version works for some people as you said?
