### ISSUE TITLE
load function does not correctly load nested function via : ,ff 

### ISSUE THREAD

**Issue by zamaterian** [jalvesaq/Nvim-R#34]
Load nested functions dosn't include the outer function.

Cheers

getInParentsFrame  <-  function(name){
    # recursing through parent frames looking for name
    sysf  <- rev(sys.parents())
    ff  <-  function(sysf){
        n  <-  head(sysf,1)
        if (length(sysf) == 0)
        {
            return ("")
        }
# CURSOR HERE

```
    env  <-  sys.frame(n)
    if (identical(env, emptyenv()))
    {
        return ("")
    }
    else if (exists(name, envir = env, inherits = FALSE))
    {
        get(name,envir=env)
    }
    else
    {
        ff(tail(sysf,-1))
    }}
ff(sysf)
```

}
results in  the tmp file            :

cat /tmp/Nvim-R-te/Rsource-11287 

```
ff  <-  function(sysf){
    n  <-  head(sysf,1)
    if (length(sysf) == 0)
    {
        return ("")
    }

    env  <-  sys.frame(n)
    if (identical(env, emptyenv()))
    {
        return ("")
    }
    else if (exists(name, envir = env, inherits = FALSE))
    {
        get(name,envir=env)
    }
    else
    {
        ff(tail(sysf,-1))
    }}
```

**Comment by jalvesaq** [comment]
Please, review you post. It seems that there is something wrong with the markdown format.

What happens if you end the function with
```
    }
}
```
instead of
```
    }}
```

**Comment by jalvesaq** [comment]
If I copied your code correctly, I think `<LocalLeader>ff` is getting the function correctly. It does not rely on indentation, and it is getting the nested function completely. If you want to send the outer function to R, you should either put the cursor outside the nested function or mark the block of code and press `<LocalLeader>bb`.

**Comment by zamaterian** [comment]
Correct, but since the inner function is part of the lexical scope for the outer function, then the inner function should only be reload in context of the outer function. Not in the global scope.

A similar case is when you have a tryCatch function, where you have defined error, warning, interrupt function. You need to move to the outer function outside of the tryCatch to reload/ otherwise you get an compile error.

**Comment by jalvesaq** [comment]
Certainly you are right for most use cases, but in some circumstances the user might want to test only the inner function. Anyway, it would be too complicated to implement a smart algorithm that decides what to send to R based on context. Unless someone is wanting to implement this, it might be better to remove the functionality triggered by `<LocalLeader>ff` than having the currently broken one.

We already have an alternative in the plugin: to send a marked block of lines. The user has only to press, for example, `ma` before the lines that must be sent and `mb` after them to mark the block and, then, press `<LocalLeader>bb`. In the Nvim-R documentation I suggest the use of vim-signature plugin to make the marks visible.

**Comment by zamaterian** [comment]
I would probably keep the current imp; maybe change the documentation to indicate it only loads current function scope. 

I could probably try to cook something together like `<localleader>ft`  (reload toplevel function in scope). 

I think I have a hackup unction somewhere that does it for clojure.

**Comment by jalvesaq** [comment]
I added a note on this other limitation to section 5.3 (https://github.com/jalvesaq/Nvim-R/commit/6428766fac71088197e5a630fc608ab6212d95d2).
