### ISSUE TITLE
Feature request: Option to start terminal and help buffer as "unlisted"

### ISSUE THREAD

**Issue by simongrund1** [jalvesaq/Nvim-R#340]
I recently switched from Tmux to using Vim's terminal buffers, and I found myself getting caught in the terminal buffer when cycling between buffers in a window/split I am editing (`:bnext`, `:bprevious`). I then have to switch to normal mode, cycle out of it, and return to insert mode in the actual terminal window.

The behavior I would expect is that cycling through buffers excludes the terminal and (optionally) the help window. I can achieve that by running `set nobuflisted` in these windows after the have been created (e.g., after hitting `<leader>rf`). Is it possible to add an option that will cause the terminal and help buffers to be always started with `nobuflist` option? Or is there any "trick" I'm missing that prevents me getting caught up in the terminal buffer?

Thanks in advance, best wishes!

**Comment by simongrund1** [comment]
Perfect. I replaced the `TermOpen` with `TerminalOpen` and put it in my `.vimrc`. This does the job for the terminal window. I achieved the same for the help buffer by also adding:

```vim
autocmd BufEnter R_doc setlocal nobuflisted
```

The issue can be closed, though I'd still be happy to see it as a feature at some point.

Many thanks!

**Comment by jalvesaq** [comment]
The change would make no difference to me because I don't have the habit of using the `:bnext` and `:bprevious` commands, but I don't know how most people would prefer R_doc, Object Browser and Terminal (listed or unlisted). So, we may leave the issue open...
