### ISSUE TITLE
Auto-quitting not working

### ISSUE THREAD

**Issue by romagnolid** [jalvesaq/Nvim-R#341]
I put the suggested string in my vimrc file
`autocmd VimLeave * if exists("g:SendCmdToR") && string(g:SendCmdToR) != "function('SendCmdToR_fake')" | call RQuit("nosave") | endif`
but when I quit Vim the R terminal remains open.
I noticed that g:SendCmdToR is set "*SendCmdToR_fake()" even though I start R from Vim.
What could be the cause?
Currently I'm using Vim 8.0

**Comment by romagnolid** [comment]
With `R_in_buffer = 0` it works but with `R_in_buffer = 1` it doesn't.

**Comment by jalvesaq** [comment]
The VimLeave event happens when you quit all buffers, including the buffer where R is running in.

**Comment by romagnolid** [comment]
Oh, I see...
So I wasn't really closing Vim, having one window occupied by the R terminal.
I guess the only way to immediatly close both windows is to run :qa!
