### ISSUE TITLE
Cannot find the log file with latexmk build directory set

### ISSUE THREAD

**Issue by stefanheyder** [jalvesaq/Nvim-R#344]
I have the following setup in my _~/.latexmkrc_:

```
#/usr/bin/env perl
@generated_exts = qw(aux fls lot out idx ind lof lot out toc acn acr alg glg glo gls ist);

$pdf_mode = 2;
$pdflatex = 'pdflatex -synctex=1 %O %S';
$pdf_previewer = "start zathura --unique";

$biber='biber --validate-datamodel %O %S';
$out_dir = 'build';
```
When I try to build a _\*.Rnw_ file using **\<leader\>kp** latexmk is run as expected. After that, the following error is thrown:
```
Error in file(con, "r") : cannot open the connection
.....
cannot open file 'xyz.log': No such file or directory
```
which is probably caused by 'xyz.log' being placed in the build directory. I have looked at `b:rplugin_pdfdir`, which contains the correct path (including the build directory).

Is there something I am doing wrong?

**Comment by jalvesaq** [comment]
Does it work now?

**Comment by stefanheyder** [comment]
Yes it does, thank you for fixing this so quickly :)
