### ISSUE TITLE
how to update the omni library

### ISSUE THREAD

**Issue by akahanaton** [jalvesaq/Nvim-R#345]
Hi jalvesaq
I'm using macvim and seems the omni complete library in ~/.cache/Nvim.R in not automatically updated after I installing the new libraries,  
Could you please give me some hint how can I get it to work, or is there a way I can update the omni library manually?
Thank you very much,

Best

**Comment by akahanaton** [comment]
oh, it works now, thanks

**Comment by jalvesaq** [comment]
You reopened the issue... Is it working or not?

**Comment by akahanaton** [comment]
Yes, it is working great, thx
