### ISSUE TITLE
Using formatR to reformat specific portion of code

### ISSUE THREAD

**Issue by statquant** [jalvesaq/Nvim-R#350]
Hello,
you might know about [formatR ](https://yihui.name/formatr/) which allow automatic formatting. I was wondering if you had an idea how to leverage the package in Nvim-R.
Given that you already know how to "extract" code from a function, paragraph, file  maybe that would not require too much work ?
For instance
```
R> formatR::tidy_source(text = "x = 1; x=2; for(i in 1:n){print(i)}; test = function(x=1){return(x)}", arrow = TRUE)
x <- 1
x <- 2
for (i in 1:n) {
    print(i)
}
test <- function(x = 1) {
    return(x)
}
```
I am thinking something along formatR::tidy_source(text = the vim selection) or formatR::tidy_source(the tmp file that NvimR creates) ?
 
You might be raising the point that all this could be done "offline" but formatR changes a LOT of things, so the easy and efficient way is to reformat when for instance you debug. Being able to do that would be very nice I think.

**Comment by jalvesaq** [comment]
The command `:Rformat` already exists, and it calls `formatR::tidy_source()`.

**Comment by statquant** [comment]
That's great thanks, the docs indeed mention it. 
Do I need to modify the code so I can pass the arguments I want to tidy_source ?
How can I vmap Rformat to run on selection ?
How can I nmap Rformat to run on the function I am within ?

**Comment by jalvesaq** [comment]
> Do I need to modify the code so I can pass the arguments I want to tidy_source ?

Currently, `:Rformat` does not accept arguments, but I can add this feature if you want. Then, whatever were typed after `:Rformat` would be passed as arguments for tidy_source. Do you need this?

> How can I vmap Rformat to run on selection ?

```
vmap ts :Rformat<CR>
```

> How can I nmap Rformat to run on the function I am within ?

The function detection is buggy. And, currently, it's not possible because Nvim-R does not have a function to select the function where the cursor is.

**Comment by jalvesaq** [comment]
It's possible to control the default values of `formatR::tidy_source()` arguments with `options()` in the `.Rprofile`. So, I think only rarely someone will need to pass arguments through `:Rformat`.

**Comment by statquant** [comment]
You're right that's good idea I'll modify the .Rprofile
> The function detection is buggy. And, currently, it's not possible because Nvim-R does not have a function to select the function where the cursor is
I might have phrased that wrong, when I do <LocalLeader>ff from within a function the addin sources the function I am in perfectly... Can't the same process be used ?

**Comment by jalvesaq** [comment]
> For some reason the width is not taken correctly into account

Nvim-R pass Vim's `&textwidth` as the value of the `tidy_source`'s `width.cutoff` argument. This is already explained in Nvim-R's documentation.

> It seems that the indentation is lost after calling Rformat how can I call = after calling Rformat

You can't because `:Rformat` deletes the old text and inserts new text. It's necessary to select the new text and do = manually.
