### ISSUE TITLE
Merge auto-list branch

### ISSUE THREAD

**Issue by blayz3r** [jalvesaq/Nvim-R#351]
I believe this branch enables nvim-r to work with ncm completion like below:

Plug 'jalvesaq/Nvim-R', {'branch': 'auto_list'}
Plug 'roxma/nvim-completion-manager'
Plug 'gaalcaras/ncm-R', {'branch': 'auto-list'}

**Comment by jalvesaq** [comment]
I thought that the brach was 'auto_start' because the branch 'auto_list' does not exist. I don't remember this branch, but probably it was already merged because ncm-R is well integrated with Nvim-R in the master branch.

**Comment by blayz3r** [comment]
Ok the branch is mentioned here: https://github.com/jalvesaq/Nvim-R/issues/261#issuecomment-353027993. I guess we close the issue and I'll move to the main branch.
