### ISSUE TITLE
error installing nvimcom: cc: Command not found

### ISSUE THREAD

**Issue by mcooganj** [jalvesaq/Nvim-R#352]
hi, 

i just installed Nvim-R and tried `\rf` at the open -- and had the below error.  The problem seems to be that `make[1]: cc: Command not found`. 

I"m starting R without an .Rprofile, so it's a clean boot.  I am using vim 8.1.1

* installing to library 'C:/Users/mcoog/Documents/R/win-library/3.5'
* installing *source* package 'nvimcom' ...
** libs
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG       -D`C:/PROGRA~1/R/R-35~1.1/bin/R --slave -e 'cat(Sys.info()[[1]])'` -DLWS_NO_FORK  -DWIN32   -O2 -Wall  -std=gnu99 -mtune=generic -c nvimcom.c -o nvimcom.o
c:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o nvimcom.dll tmp.def nvimcom.o -lWs2_32 -LC:/PROGRA~1/R/R-35~1.1/bin/x64 -lR
(cd apps; make -f Makefile.win)
make[1]: Entering directory '/Users/mcoog/AppData/Local/Temp/RtmpgBEnCi/R.INSTALL2c60aa9b96/nvimcom/src/apps'
cc -m64 -mwindows -std=gnu99 -O3 -Wall -DWIN32 nclientserver.c -o nclientserver.exe -lWs2_32
make[1]: cc: Command not found
make[1]: *** [Makefile.win:10: nclientserver.exe] Error 127
make[1]: Leaving directory '/Users/mcoog/AppData/Local/Temp/RtmpgBEnCi/R.INSTALL2c60aa9b96/nvimcom/src/apps'
make: *** [Makevars.win:11: nvimapps] Error 2
ERROR: compilation failed for package 'nvimcom'
* removing 'C:/Users/mcoog/Documents/R/win-library/3.5/nvimcom'
In R CMD INSTALL

**Comment by jalvesaq** [comment]
I'm sorry about that! Unfortunately, I could never make nvimcom build in all Windows configurations, and I'm really tired of trying to do it. Perhaps, someone else can help you.

**Comment by mcooganj** [comment]
I’d be happy to have a look at it. Perhaps you could tell me what you’ve discovered during your travails in some other forum?

**Comment by harryln** [comment]
Hi, There,
I had this problem before and encountered today. Just change `Nvim-R\R\nvimcom\src\apps\Makefile.win`:

**Comment by jalvesaq** [comment]
@mschilli87 ?

**Comment by mschilli87** [comment]
I guess `CC=gcc` should be fine, but I also have no idea right now why all this makes a difference.
Don't hava a windows box to test as of now. As long as strictly assigning `gcc` doesn't break anything on linux/mac, if Windows wants it, why not? ;-)

**Comment by jalvesaq** [comment]
@mschilli87, some people use `clang` use instead of `gcc`, and both work on Linux.

On Windows, the compilation depends on a number of factors to be successful.

  - Rtools must be installed.

  - The `.Rprofile` cannot have any code that outputs anything. For example, if you put `cat("Hello!\n")` in your `.Rprofile` `gcc` may complain that it didn't find the file `Hello`.

  - If Cygwin is installed and either its `gcc` or its `make` is called instead of Rtools' ones, the compilation fails.

  - If any non GNU `make` is called, the compilation fails.

  - For some people, not all versions of Rtools work.

The fact is that whenever I fix a bug for someone, I introduce a new bug for someone else.

**Comment by mschilli87** [comment]
@jalvesaq: I can try to give it some thought once have access to a Windows box and try different combinations of OS/make/compiler...but no promises! :wink:

**Comment by jalvesaq** [comment]
> I can try to give it some thought once have access to a Windows box and try different combinations of OS/make/compiler...but no promises!

That's great, because I'm not going to do it.

**Comment by mschilli87** [comment]
just for reference:  https://github.com/jalvesaq/Nvim-R/issues/342#issuecomment-475227689

**Comment by jalvesaq** [comment]
Closing because this issue is too old and many things have changed since it was opened. Please, see https://github.com/jalvesaq/Nvim-R/issues/456

**Comment by mcooganj** [comment]
I bumped into this problem again today. The solution was to set the path for rtools

let $PATH = "c:\\rtools40\\usr\\bin;c:\\rtools40\\mingw64\\bin;" . $PATH
