### ISSUE TITLE
Add R_term_cmd_2, ...

### ISSUE THREAD

**Issue by statquant** [jalvesaq/Nvim-R#354]
Hello, would that be able to more R_term_cmd, the idea being that with tillix we could ask to split the terminal vertically or horizontally ?

**Comment by jalvesaq** [comment]
How would Nvim-R decide whether to use R_term_cmd or R_term_cmd_2?
It's better to define the value of R_term_cmd dynamically with an autocmd, instead of having a fixed value defined in the vimrc.

**Comment by statquant** [comment]
Nvim-R would start R with any of those, but yeah being able to redefine R-Term_cmd dynamically when pressing say <localleader>rf (that would split vertically) or <localleader>rfh (horizontal split) would be the same. Will look at what "autocommands" are

**Comment by jalvesaq** [comment]
I don't have tillix installed, but below is a template of a command that you could try:

```vim
autocmd VimResized * if winwidth(0) > 140 | let R_term_cmd = 'cmd for v split' | else | let R_term_cmd = 'cmd for h split' | end
```

The above command will work as expected only if the cursor is on the R script window where you will start R from when Vim is resized.

**Comment by jalvesaq** [comment]
Please, reopen the issue if it's not solved.
