### ISSUE TITLE
Feature Request to Integrate Nvim-R with the R reticulate library for a python interface

### ISSUE THREAD

**Issue by dcbdan** [jalvesaq/Nvim-R#356]
Nvim-R has been pretty awesome and when I use python, I use vim-slime customized to have the same keybindings as Nvim-R.

However, the recent [reticulate library](https://rstudio.github.io/reticulate/index.html) provides a seamless interaction between R and python. The library makes it possible to access python objects from R and R objects from python. The R function `reticulate::repl_python` also opens a persistent python interpreter. What would be pretty awesome is if Nvim-R (1) used reticulate to send python chunks to the python interpreter and (2) provided python syntax highlighting in python chunks.

This feature request is different from #303, #309 because of the reticulate library.
 
Here is a (silly) working Rmd file for example (just change '' to ''') :
```
``{r}
library(reticulate)
w = array(rnorm(6), dim = c(3,2))
``

``{python}
import matplotlib.pyplot as plt
import numpy as np
w = np.random.normal(size = [3,2])
print(w)
print(r.w)

plt.figure()
plt.hist(np.random.normal(size = 1000))
plt.show()
``

``{r}
print(py$w)
print(w)
``
```

**Comment by jalvesaq** [comment]
For syntax highlight of python chunks, please, put in your vimrc (Vim) or init.vim (Neovim):

```vim
let g:rmd_fenced_languages = ['r', 'python']
let g:markdown_fenced_languages = ['r', 'python']
```
Then, if you either are using the development version of Vim or have the "plugin" R-Vim-runtime installed, you should get the python syntax highlighted. Note however that rmd chunks should be delimited by three backticks, and not two.

**Comment by dcbdan** [comment]
Thanks, I got python syntax highlighting to work.

I used two backticks only because the markdown on github got in the way (I imagine there is an escape sequence or some way to do it..)

To evaluate python chunks via reticulate, it suffices to call `reticulate::py_run_string` or `reticulate::py_run_file` in R. Is there an easy way to call py_run_string or py_run_file with python input when inside python chunks?

For now, the quick hack I came up with modified `SendCmdToR_TmuxSplit` by wrapping the input string with `reticulate::py_run_string`. I put the following into my vimrc:
```
function SendCmdToRHack(py_raw_str)
    let r_raw_str = 'reticulate::py_run_string("' . substitute(a:py_raw_str, '"', '\\"', "g") . '")'
    if g:R_clear_line
        let cmd = "\001" . "\013" . r_raw_str
    else
        let cmd = r_raw_str
    endif

    let str = substitute(cmd, "'", "'\\\\''", "g")
    if str =~ '^-'
        let str = ' ' . str
    endif
    "let scmd = "tmux set-buffer '" . str . "' && tmux paste-buffer -t " . g:rplugin_rconsole_pane
    let scmd = "tmux set-buffer '" . str . "\<C-M>' && tmux paste-buffer -t " . g:rplugin_rconsole_pane
    let rlog = system(scmd)
    return 1
endfunction

function SendReticulate()
  let str = s:get_visual_selection()
  :call SendCmdToRHack(str)
endfunction

map <LocalLeader>qq :<c-u> call SendReticulate()<CR>
```

**Comment by jalvesaq** [comment]
We have to make some changes in the code for this, and I started to do these changes on the "reticulate" branch: https://github.com/jalvesaq/Nvim-R/tree/reticulate

I'll continue the work on this later...

**Comment by jalvesaq** [comment]
I forgot to commit the changes yesterday... Could you please check the brach now?

**Comment by jalvesaq** [comment]
I finished the changes that I had in mind:

  - Send `reticulate::py_run_string()` to R Console if sending a line within a Python chunk.

  - Send `reticulate::py_run_file()` to R Console if sending multiple lines of Python code.

  - Jump to Python chunk too after either `<LocalLeader>gn` or `<LocalLeader>gN` in Normal mode.

  - Complete knitr options in the chunk header.

  - Complete Python code if the [jedi-vim](https://github.com/davidhalter/jedi-vim) plugin is installed.

I still have to fix the integration with [zotcite](https://github.com/jalvesaq/zotcite).

Did I miss something? The changes are not well tested...

**Comment by dcbdan** [comment]
Awesome, I've been using the changes and will definitely be using them over the next few weeks. Right now, sending a line within a python chunk or sending an enitre python chunk works. <LocalLeader>gn works as described as well.

-  Sending visual selection doesn't work: it gives the error of "Not inside an R code chunk."
- <LocalLeader>gN on the first line of a python chunk does not jump to the previous chunk

**Comment by jalvesaq** [comment]
Thanks for trying the branch! The two issues should be fixed now.

**Comment by mschilli87** [comment]
@dcbdan 
> I used two backticks only because the markdown on github got in the way (I imagine there is an escape sequence or some way to do it..)

The key is to use more backticks:

`````
````
```{r chunk}
# code
```
````
`````

And yes, to show you four ticks, I had to use five. :wink:

**Comment by jalvesaq** [comment]
@dcbdan Did you find any bug? I believe the reticulate brach is ready to be merged.

**Comment by dcbdan** [comment]
I think it can be merged--at least it works the way I want it to.

I did switch to vim-pandoc-syntax to get latex highlighting and lost python highlighting. I had no luck getting both python and latex highlighting correct. Do you know how that can be fixed?

**Comment by jalvesaq** [comment]
The default markdown syntax highlighting that comes with Vim does not include LaTeX. Using vim-pandoc-syntax, the command below should highlight Python chunks:

```
:PandocHighlight python
```
