### ISSUE TITLE
Opens new split with R console buffer when sending from another tab

### ISSUE THREAD

**Issue by norival** [jalvesaq/Nvim-R#357]
Hi!

I noticed a new behaviour since the last update, I don't know if it is intended or not.

If I send a line/selection/file... from a tab where the R console buffer is not open, it automatically splits the current buffer to open the R console buffer. If I set `let R_auto_scroll = 0`, this doesn't happen anymore. Is there a way to disable this behaviour while keeping the `auto_scroll` feature?

Thank you!
Xavier

**Comment by jalvesaq** [comment]
It was not intended.

Could you try the branch https://github.com/jalvesaq/Nvim-R/tree/from_tab ?
The cursor will jump back to the original tab before jumping to the original window, but the user will not see the R Console, and will not see the command being pasted. Is that OK?

**Comment by norival** [comment]
I tried it, it works fine. For me it is ok, I use tabs when I'm editing functions files, I source them and then I usually jump to the tab where the console is, to test the modifications.

Thank you :)
