### ISSUE TITLE
Error: package nvimcom wasn't loaded yet 

### ISSUE THREAD

**Issue by biorelated** [jalvesaq/Nvim-R#36]
I installed this package but when I start my R session, I get this error
`The package nvimcom wasn't loaded yet`

Any ideas on how to resolve it. The package says that nvimcom is bundled with this plugin. What setup config am I missing. 
Thank you.

**Comment by jalvesaq** [comment]
There is no mandatory setup. It should work. What is your system?

**Comment by biorelated** [comment]
OS X (Al Capitan) 
Neovim 0.1.2
Nvim-R version 0.9.1

**Comment by jalvesaq** [comment]
Sorry, but I don't have access to a OS X. So, I have no way of discovering what is wrong because it works on Linux.

If there was an error compiling nvimcom, you should see the compiler log indicating the error just after the message "Updating nvimcom..." which appears when you do `<LocalLeader>rf` and nvimcom either is not installed or is outdated.

**Comment by drarrae** [comment]
I get this on OS-X with vim-7.4.1583 running inside Tmux-2.1 and iTerm-2.1.4 ... needed iTerm's "Step back in time" to capture this.  I just switched from vim-R-plugin so may have some lingering setup for that that is not compatible with NVim-R perhaps??
 
Updating nvimcom... OK!
line   13:
E121: Undefined variable: g:R_term
E15: Invalid expression: g:R_term == "rxvt" || g:R_term == "urxvt"
line   43:
E121: Undefined variable: g:R_silent_term
E15: Invalid expression: g:R_silent_term

Relevent sections of .vimrc are:
" do I still need this first one also??
Bundle 'jalvesaq/R-Vim-runtime'
Bundle 'jalvesaq/Nvim-R'

" make R run in a pane below the current terminal vim
" using tmux not screen.
let vimrplugin_tmux = 1
let vimrplugin_applescript = 0

" stick to current color scheme
let rout_follow_colorscheme = 1

I really have just switched to NVim-R so I have yet to peruse the docs to dig deeper into this myself.

**Comment by jalvesaq** [comment]
@drarrae You can do this to see past error and warning messages:
```vim
:messages
```

Currently, R-Vim-runtime is not necessary because R runtime files are updated in Vim >= 7.4.1439.

I committed some changes to let you pass the first error. Let's we see what happen now.

Later I will try to discover why R_tmux_split is not working.

**Comment by drarrae** [comment]
haha 3 years of vim and never needed 'messages:' before... learn something new everyday.
I tried to replicate on machine at home and by dropping 

Bundle 'jalvesaq/R-Vim-runtime'
let R_in_buffer = 0
let R_applescript = 0

so I only have 

Bundle 'jalvesaq/Nvim-R'
let R_tmux_split = 1

all is working.

Loving the speed.  Feels more responsive.

**Comment by jalvesaq** [comment]
@biorelated Did you install Nvim-R vimball? It does not include nvimcom yet. Only the development version (here at github) already includes it.

**Comment by drarrae** [comment]
Both installs were direct from github. Though the second one would have
included your changes after my first post above.
I use vundle btw. Hence the Bundle(...) entry.

**Comment by jalvesaq** [comment]
Thanks for the feedback, @drarrae 

I believe the issue reported by @biorelated is fixed in Nvim-R 0.9.2 released today.

**Comment by biorelated** [comment]
@jalvesaq Sorry I missed your earlier communication. Yes I had downloaded the earlier tarball. Thank you for fixing this in the latest release! The issue has been resolved! Thank you very much for this!

**Comment by jalvesaq** [comment]
Thanks for the feedback, @biorelated !
