### ISSUE TITLE
Local Loader not working

### ISSUE THREAD

**Issue by setyawendha** [jalvesaq/Nvim-R#361]
\ not working 
:echo maplocalloader 
E121 : Undefined variable : maplocalloader
E15: Invalid expression: maplocalloader

**Comment by jalvesaq** [comment]
The name of the variable is maplocalleader because it refers to a key in the keyboard that must be pressed before the remaining of the command, the leader. Vim has two leader keys:

 - `leader`: should be mapped in general plugins.

- `localleader`: should be mapped in file type plugins.

**Comment by setyawendha** [comment]
maplocalleader give same result
I am absolutely new, how/where can I map these leader and local leader ?

**Comment by jalvesaq** [comment]
You have to put in your vimrc or init.vim:
```vim
let maplocalleader = ","
```
Of course, replace the comma with the key that you want to use as `LocalLeader`.

**Comment by setyawendha** [comment]
:echo maplocalleader
\
but still not run R
\rf do insert 'f' instead of open R session

**Comment by jalvesaq** [comment]
If you have changed the default value of maplocalleader, then you have to use it. For example, if your maplocalleader is a comma, you have to press `,rf` to start R.

**Comment by setyawendha** [comment]
problem was I tested in non R script file, apologize stupidity
