### ISSUE TITLE
Can't seem to set rtools path in Windows

### ISSUE THREAD

**Issue by joeheywood** [jalvesaq/Nvim-R#362]
Trying to use this at work on a Windows 7 machine. Our IT dept refuse to save Rtools at C:\rtools - so it's saved in C:\Program Files\rtools. 

I have included in intit.vim:
`let Rtools_path = "C:\\Program Files \\Rtools"`

But it seems to be looking for gcc in C:\rtools. Error message:

> * installing to library 'M:/R Library'
> * installing *source* package 'nvimcom' ...
> ** libs
> c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG       -D`C:/PROGRA~1/R/R-35~1.0/bin/R --slave -e 'cat(Sys.info()[[1]])'` -DLWS_NO_FORK  -DWIN32   -O2 -Wall  -std=gnu99 -mtune=generic -c nvimcom.c -o nvimcom.o
> c:/Rtools/mingw_64/bin/gcc: not found
> make: *** [nvimcom.o] Error 127
> ERROR: compilation failed for package 'nvimcom'

Any idea what is going on? Am I missing something?

Any help much appreciated.

**Comment by jalvesaq** [comment]
> ` let Rtools_path = "C:\\Program Files \\Rtools"`

It looks like that there is an extra space after the word "Files".

**Comment by joeheywood** [comment]
Sorry. My mistake. I don't know how I managed to add a space there. 

I have tried the following.

```
let Rtools_path = "C:\\Program Files\\Rtools"
let Rtools_path = "C:/Program Files/Rtools"
```

I've noticed that if I put a wrong path (such as `let Rtools_path = :\\Incorrect\\Path\\"`), I get a message at the bottom of the screen in red saying `Is RTools installed? ... is not a directory`. 

But the above two, I don't get this error message.

**Comment by li-ruijie** [comment]
My experience with Rtools is that regardless of where it is installed, many compilations still look for Rtools at C:\Rtools. I have given up on trying to change the location and just symllink my install to C:\Rtools. A bonus is that I can easily switch versions of Rtools by changing where the symlink points to.

**Comment by amoreiras** [comment]
According to the Rtools documentation: 

> R looks for compilers in the default installation path in C:\Rtools\. If you install Rtools anywhere else, you have to point R to the path of gcc, g++, ld, by setting a variable called BINPREF. For example:

    BINPREF="M:/R/Rtools-3.5/mingw_$(WIN)/bin/"

I believe if you define this variable in your `.Rprofile` it should work. The Rtools path can also be added to your path in `.Rprofile` as `PATH="M:\Rtools\bin;${PATH}"` under the same assumption that Rtools alternate location is `M:\Rtools`.

**Comment by jalvesaq** [comment]
I believe that the better place to define environment variables is the vimrc/init.vim because they will already be defined when Vim/Neovim calls R. If an environment variable is supposed to be defined both for R called by Vim/Neovim and for R called directly, then it should be defined at the `.bashrc`, `.profile` or equivalent configuration file (Linux) or on the Control Panel (Windows).

**Comment by jalvesaq** [comment]
I updated the way that Rtools is set. Now, you have to set the environment variable PATH with the paths for both `make` and `gcc`. It worked with R 4.0.0 and Rtools 40. Please, see https://github.com/jalvesaq/Nvim-R/issues/456
