### ISSUE TITLE
Rterm.exe becomes unresponsive and crashes when set as the R_app for Windows instead of the "R Console"

### ISSUE THREAD

**Issue by Nevrage** [jalvesaq/Nvim-R#363]
## Scenario 
I need to use rterm.exe instead of the R console. The main reason being a will to make a tmux-like environnement in [ConEmu](https://conemu.github.io/) on Windows.

## Issue 
Changing the R_App to rterm.exe, open a functional instance of Rterm in ConEmu or CMD.
The user is able to inteact with the instance direcly without issue but crashes as soon as a line is sent from Vim.

## Steps 
* Install R, vim and NvimR on Windows 
* Change the R_app to rterm or rterm.exe
* open an R file in vim
* press <LocalLeader>rf
* interact with the newly open instance of Rterm
* Go back to vim and send a line to R by pressing <LocalLeader>d
* Observe

# Info 
* Windows 7 Enterprise SP1 x64

**Comment by jalvesaq** [comment]
On Windows, Vim/Neovim sends a message to nvimcom which calls the C function `Rconsolecmd`, but this function is defined only in Rgui.exe, not in Rterm.exe. If you want to run Rterm.exe you have to keep `R_in_buffer` at its default value which is 1.

I will add a warning on this, and improve the documentation on `R_app`.

**Comment by jalvesaq** [comment]
Both Gvim and Neovim have improved the support to run R in their builtin terminal. Now, the nvim.exe application is working well in the CMD window.

**Comment by jalvesaq** [comment]
Please, see https://github.com/jalvesaq/Nvim-R/issues/456
