### ISSUE TITLE
Help opens additional unwanted split

### ISSUE THREAD

**Issue by bdcaf** [jalvesaq/Nvim-R#364]
This is a bit of a weird issue.  It took me long to put together a reproducible example.  
I think the summary is the buffer that was used to start Nvim-R keeps reappearing in a split whenever
I open the help from the R buffer.

Reproducible example:
1.  `nvim test.R`
2.  `\rf` to start Nvim-R
3.  `:e test2.R`
4.  now `<C-w><C-w>` to get into R buffer
5.  `?ls` to show a help (doesn't matter whether in tab of split)
6.  In the tab of the R process now is an extra split showing test.R

**Comment by jalvesaq** [comment]
Thanks for reporting the issue!

**Comment by bdcaf** [comment]
Amazing! Thanks for the quick fix!
