### ISSUE TITLE
new feature: compile naked child Rnw file with local leader+n+p

### ISSUE THREAD

**Issue by smilesun** [jalvesaq/Nvim-R#365]
I use Rnw files to create exams for my students, I put separate quiz into child Rnw file and include them in the main Rnw in the way

    <<child="xx.Rnw">>@
The xx.Rnw contains the problem statement and also the answer and the main Rnw include the class of the latex template. 

This means that you can not compile the child Rnw file alone since it has no latex  `\begin{document}` like statement, is it possible to have a feature to compile those child document with a default latex template to see first if works or not? 

This will be of particular useful since compiling the whole document is quite expensive.

**Comment by jalvesaq** [comment]
Nvim-R is being superseded by R.nvim, a new project that will be inaugurated in a week at the [R-nvim](https://github.com/R-nvim) organization.
Please, check out [tmp-Nvim-R](https://github.com/jalvesaq/tmp-R-Nvim) and help us to find the last remaining bugs before R.nvim inauguration.
When the project is officially started, you will be able to open issues there and request new features.

Nvim-R will remain alive as a feature-frozen project for Vim users. If you want to know the reason, please, see [this discussion](https://github.com/jalvesaq/Nvim-R/discussions/797).
