### ISSUE TITLE
Strange Encoding Issue with Neovim on Win10

### ISSUE THREAD

**Issue by wngrtn** [jalvesaq/Nvim-R#366]
I just installed neovim, R and Nvim-R on a new Win10 machine. When I open an R window in Neovim I get loads of strange characters in the R Console window, e.g. sending `library(tidyverse)`, results in:

> options(width=68); library(tidyverse)
-- ?[1mAttaching packages?[22m --------------------------------tidyverse 1.2. --
?[32mv?[39m ?[34mggplot2?[39m 3.0.0.      ?[32mv?[39m ?[34mpurrr  ?[39m 0.2.5

... and so on.

Any clues what might be going on?

**Comment by mschilli87** [comment]
@wngrtn:

I can confirm that loading tidyverse results in coloured output using icons - so these are escape sequences that you shell does not understand/interpret.
