### ISSUE TITLE
Feature Request: Syntax Highlighting for Python Chunks in Rmd

### ISSUE THREAD

**Issue by marskar** [jalvesaq/Nvim-R#369]
Thank you for enabling support for python chunks in R markdown files via reticulate.
I would like to request Syntax Highlighting for Python Chunks in R markdown files.
Currently, R chunks have syntax highlighting, while Python chunks, are monotone.
<img width="684" alt="screen shot 2018-10-27 at 6 58 03 pm" src="https://user-images.githubusercontent.com/12806339/47610080-875faf80-da1a-11e8-98eb-e2451c245c97.png">

**Comment by jalvesaq** [comment]
Are you using any plugin for syntax highlight of markdown documents? Please try disabling all plugins and keeping only [R-Vim-runtime](https://github.com/jalvesaq/R-Vim-runtime).

**Comment by oli666** [comment]
I am experiencing the same with only the two plugins mentioned above enabled.

**Comment by jranke** [comment]
Thanks @oli666 - this fixes the issue for me as well if I disable vim-pandoc-syntax.

**Comment by jalvesaq** [comment]
Thanks @oli666
