### ISSUE TITLE
R_path should be the full path, not the directory

### ISSUE THREAD

**Issue by klmr** [jalvesaq/Nvim-R#37]
I need to launch a wrapper script instead of R itself. Consequently, my R_path used to be configured (in Vim-R-plugin) as follows:

```
   let vimrplugin_r_path = "~/.R/launcher.sh"
```

This `launcher.sh` is just starting R on my local computer, but on the cluster on which I’m working it’s a more complex command that submits an interactive job to a cluster:

```bash
  bsub -Is -XF -M 16000 -R 'rusage[mem=16000]' R
```

Alas, this no longer works because `R_path` now expects only a directory. As a workaround I can rename `launcher.sh` to `R` but this isn’t really desirable because it creates confusion with executable names. Was there a good reason for changing this setting to expect a directory rather than a path to the executable?

**Comment by jalvesaq** [comment]
I don't remember why I have changed this. Perhaps because it's complicated to work with full path on Windows due to the backslashes. But I agree with you that it's better to have the full path. I will see this on Saturday because anything that mess with file paths must be tested on Windows too and I can't do this now.

**Comment by jalvesaq** [comment]
I implemented the option `R_app` which was already documented, but not implemented.
Users should set `R_path` if the R executable is not in the `$PATH`, and should set `R_app` if wanting to change the default R application. If `R_path` exists, it's added to the `$PATH`. So, your problem should be solved with:

```vim
let R_path = "~/.R"
let R_app = "launcher.sh"
```

**Comment by klmr** [comment]
Awesome. Thanks.
