### ISSUE TITLE
\rv does not open Excel or Calc on Win10 (neovim 0.3.1)

### ISSUE THREAD

**Issue by wngrtn** [jalvesaq/Nvim-R#371]
I have this in my init.vim on Win10:

```vim
let R_csv_app = 'C:/Program Files/Microsoft Office/root/Office16/EXCEL.EXE'
```

When I run `\rv` the cursor turns into a spinning wheel for a tenth of a second, but nothing else happens. No warning is shown. Same behavior for LibreOffice Calc. I tried backslashes instead of forward slashes and that brings up a file not found error.

How do I diagnose this?

**Comment by jalvesaq** [comment]
Does setting `R_csv_delim` to the correct value (either "," or ";") make any difference? Example:

```vim
let R_csv_delim = ","
```

**Comment by wngrtn** [comment]
No change, unfortunately. The status line shows "Wait ..." for about 10 seconds, but then nothing happens.

Tried deactivating Kaspersky on a hunch because it is often the culprit when external programs don't start, but it didn't make a difference.

**Comment by jalvesaq** [comment]
I confirm the bug in Neovim on Windows, and I don't know how to fix it, but GVim can start LibreOffice.
