### ISSUE TITLE
Omnicompletion: R source not properly escaped

### ISSUE THREAD

**Issue by mllg** [jalvesaq/Nvim-R#372]
Consider the following code:

```r
foo = function(x, y, z) { x }
foo(identical("x"), |
```
`|` is cursor position where omni completion is triggered via `<c-o>`.

This blocks neovim for a few seconds, and then yields an error (Error: VECTOR_ELT() can only be applied to a 'list', not a 'NULL')  in the nvimcom package here: <https://github.com/jalvesaq/Nvim-R/blob/master/R/nvimcom/src/nvimcom.c#L693>

It looks like nvimcom tries to evaluate the following line of code (I just printed *buf with `Rprintf()` in ` nvimcom_eval_expr()`):
```r
nvimcom:::nvim_complete_args("foo", "", firstobj = "identical("x")", extrainfo = TRUE)
```
Note that `"` is not properly escaped for argument `firstobj`.

As a side note, I don't understand why `cmdexpr` can be `NULL` if `status == PARSE_OK`. At least the documentation is not very clear on this (<https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Parsing-R-code-from-C>). I guess it would be best to throw in some additional checks before attempting to extract elements.

**Comment by jalvesaq** [comment]
Thanks for reporting the issue. Is it fixed now?

**Comment by mllg** [comment]
Yes, solved. Thanks for the fix.
