### ISSUE TITLE
"Pull" current REPL line into Vim?

### ISSUE THREAD

**Issue by josswright** [jalvesaq/Nvim-R#373]
Would it be possible to have a binding to let Nvim-R 'pull' the current REPL line from the R session and insert it into the current buffer?

I know that there's ```\o``` to evaluate the current line and insert the output as a comment, but I quite often find myself tinkering in the R REPL itself, getting the command correct there, then having to copy it back to the Neovim buffer manually. It would be incredibly useful to have a binding that pulls whatever is written in the current REPL line (or, I suppose, pulls the last executed command there if that's stored anywhere) and just inserts it at the cursor.

(I know that the obvious suggestion is just not to do that tinkering in the REPL and instead do everything directly in Neovim, but in practice directly typing in R seems to work most comfortably for me. In particular, I often want to type a few throwaway commands to get a feel of some data or output, but don't necessarily want that in the Neovim buffer. I then find that a final command should be inserted and have to copy and paste with the mouse.)

I don't know enough about the architecture of NVim-R to know if this is possible, but it would be incredibly useful for me.

**Comment by jalvesaq** [comment]
You could put this in your `init.vim` or `vimrc`:

```vim
nmap <F7> <C-W>lG?^> \S<CR>Y<C-W><C-W>pdw
```
That is, when you press `F7` in normal mode, the cursor will jump to the window on the right (presumably the R console), go to the end of the buffer, search backward for the last non empty prompt line, copy it, move the cursor back to the previous window, paste the line and delete the prompt.

**Comment by josswright** [comment]
Thanks for the reply. My R REPL runs in tmux in a separate terminal window. (Mainly because of the flexibility of being able to move it around, have it on a separate monitor, etc.)

Is there anything architecturally that would make this possible? Is the flow from Neovim to the tmux window/REPL one-way, or could this theoretically work? I'd be happy to start digging into it if there's a possibility, but at the moment I really don't understand how that channel works.

**Comment by jalvesaq** [comment]
You could try this:

```vim
nmap <F7> :Rinsert last_command()<CR>
```
