### ISSUE TITLE
Error detected while processing function StartR

### ISSUE THREAD

**Issue by JohnCoene** [jalvesaq/Nvim-R#374]
I'm running into the following error when hitting <kbd>\<leader\></kbd> + <kbd>rf</kbd> on a `.R` file.

```
Updating nvimcom... Building lists for omni completion... OK!
Error detected while processing function StartR[31]..StartNClientServer[2]..FinishStartingR:
line  144:
E117: Unknown function: StartR_ExternalTerm
```

I'm on Mojave running R 3.5.1, nvimcom is installed and can be called with `library`.

```r
packageVersion("nvimcom")
#> [1] ‘0.9.75’
```

**Comment by jalvesaq** [comment]
What is your Nvim-R configuration in your vimrc?

**Comment by JohnCoene** [comment]
None really, coming from Ubuntu where I did not have to setup anything specific.

```vim
call plug#begin('~/.vim/plugged')

Plug 'https://github.com/jalvesaq/Nvim-R'

call plug#end()
```

Apologies if I missed something in the setup.

**Comment by mchiapello** [comment]
I am experiencing the same issue. Any advice?

**Comment by mchiapello** [comment]
> I am experiencing the same issue. Any advice?

I was not using tmux session!

**Comment by songcai** [comment]
I am on Mojave 10.14.2 and everything is fine. I never experience the problem that you you encountered.

Are you using Nvim or Vim? What is the version number of your editor? Are you running NVim-R using the built-in terminal of NVim or Vi? If not, what external terminal are you using? I suggest that you use the newest Nvim or Vim and add "let R_in_buffer = 1" in .vimrc to see what happens.

**Comment by Blosberg** [comment]
> I am on Mojave 10.14.2

I'm getting the following (similar) error on the latest OSX 10.14.4 (regular vim version 8.1):

`Error detected while processing function RObjBrowser[14]..StartObjBrowser:
line   46:
E117: Unknown function: nvim_win_get_buf
E15: Invalid expression: nvim_win_get_buf(g:rplugin.ob_winnr)`

I installed `nvim-R` with minpac, and then just opened an R script file with vim, and then hit `\rf` to open the R command line within vim. 

I see the above when I use the quick-key `\ro` to open the object (environment) browser in the top corner. I see the same thing on Ubuntu, and I have the same `.vimrc` in each case, so I don't think it's a platform issue. 

> I suggest that you ... add "let R_in_buffer = 1" in .vimrc

Did so, and see no change. 

After seeing this error, I still seem to be able to open the environment browser, and everything _seems_ to be working ok, so hopefully I can just ignore this, but I'm worried something unseen is going wrong. Would gladly do further testing if anyone has any more suggestions. 

Nevertheless, thanks for the great plugin!

**Comment by jalvesaq** [comment]
I have just fixed this bug:
```
Unknown function: nvim_win_get_buf E15: Invalid expression
```
The bug was introduced on April 9, 2019 (https://github.com/jalvesaq/Nvim-R/commit/a1257b0f3bef1eb61ca0cd0e4c726c2acd4b1336).

**Comment by Blosberg** [comment]
> I have just fixed this bug:

Indeed :). I just updated and the error messages are gone. Thanks very much!

**Comment by jalvesaq** [comment]
@JohnCoene, do you still see this error?
```
Updating nvimcom... Building lists for omni completion... OK!
Error detected while processing function StartR[31]..StartNClientServer[2]..FinishStartingR:
line  144:
E117: Unknown function: StartR_ExternalTerm
```

**Comment by ck2136** [comment]
Hi I'm also running Mojave 10.14.4. 
I get this error:

<img width="1109" alt="Screen Shot 2019-05-14 at 4 50 16 PM" src="https://user-images.githubusercontent.com/21317713/57737322-8154b780-7668-11e9-9137-4426df8d619b.png">

```
sessionInfo()

R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.4

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.0 tools_3.6.0 
```

```
~/.vimrc

 24 " nvimr setting {{{
 25 let R_console_width = 57
 26 let R_min_editor_width = 19
 27 let R_in_buffer = 1
```

**Comment by jalvesaq** [comment]
What is the version of Vim? Do you see `+terminal` in the output of `:version`.

**Comment by jalvesaq** [comment]
@ck2136, your Vim does not have the function `term_start()`. You should upgrade your Vim, use Neovim or put `let R_in_buffer = 0` in your vimrc.

**Comment by BlueGrisGris** [comment]
Hello!

I had the same error as https://github.com/JohnCoene 
I have: Mojave 10.14.5, R 3.60, vim 8.0

I checked vim --version and saw: +channel; +job; but -conceal

I switched to macvim, and --version revealed:  +channel; +job; +conceal

Using macvim,  \rf in a .R file worked!

I think the issue has to do with the standard compilation of vim 8.0 on macs not including conceal.
