### ISSUE TITLE
automatic install of nvimcom only as root

### ISSUE THREAD

**Issue by winmos** [jalvesaq/Nvim-R#375]
hi,

i tried to use nvim-R in a newly installed system. when i first invoked R from within nvim, i got the message, that the program has no permission to write nvimcom to my local library (situated in my home directory).

by startin nvim with sudo everything worked fine -> nvimcom installed!

what could be the problem with this? why doesn't nvim update nvimcom in the normal (non-sudo) mode? 

all the best and thank you!
winfried

**Comment by jalvesaq** [comment]
Perhaps you have installed nvimcom with sudo and now it requires sudo to be updated. You could try in the terminal:

```
sudo R
remove.packages("nvimcom")
```

**Comment by winmos** [comment]
it was a similar problem: i created the directory for the r-libraries with sudo. chown resolved the problem.
thank you!
