### ISSUE TITLE
Can’t scroll up in R pane Nvim-R. Vim pane scrolls fine.

### ISSUE THREAD

**Issue by chrisvacc** [jalvesaq/Nvim-R#376]
The R pane in Nvim-R won’t allow me to scroll up. It did at first, then stopped working. It doesnt work in the xterm or guy versions.

Also, while I’m here, perhaps you know the answer to this too? [set -o vi / set -o emacs in mccvim terminal? (for a plugin called Nvim-R) #831](https://github.com/macvim-dev/macvim/issues/831)

**Comment by jalvesaq** [comment]
I can't replicate the issue: the R output is scrolled as usual by moving two fingers in the touchpad of my laptop (on Linux), but, please, read the paragraph on `R_auto_scroll` in the section 6.1 of Nvim-R documentation.

You can start a terminal running a shell in either Vim or Neovim with the command `:terminal`. To start another application you should simply add the name of the application. Examples:

```
:terminal nvim
:terminal vim
:terminal emacs
```

You may also be interested in reading Vim's documentation on how to move windows around. Please, do in Vim:

```
:h window-moving
```

**Comment by chrisvacc** [comment]
Yes, I’m using 2 finger scrolling on macOS. Nada. The vim window works, but not the r/term window. I turned off all my plugins except Nvim-R, still the same thing. The white is GUI vim, the black is vim running in terminal. Same issue. But note, in terminal the 2 finger scrolling allows me to. scroll through my list of commands, so I’m thinking that may be part of the issue.

https://www.youtube.com/watch?v=6bIgYrVb-Fw

Perhaps something in my .zshrc (zshell rc) that’s telling it to scroll through commands rather than scroll up and down? But then I open a terminal window running zsh I can still scroll with 2 fingers.

**Comment by jalvesaq** [comment]
The scrolling works in Neovim, but not in Vim. I think it is a Vim feature. Vim only scrolls the output if I enter Normal mode by typing  CTRL-\ CTRL-N
I don't have zsh installed, but you could compare:

```
:terminal bash
:terminal zsh
:terminal R
```

**Comment by chrisvacc** [comment]
Hmm, i can confirm that scrolling works in neovim, but not vim, and also if i enter NORMAL mode in `:terminal` it works. Hmm..

**Comment by chrisvacc** [comment]
Oh well, it’s not that often I have to scroll up in the R terminal, so I guess I’ll just enter NORMAL mode when I have to. That solution is fine. Thanks for your help!
