### ISSUE TITLE
Nvim-R with termite

### ISSUE THREAD

**Issue by supersambo** [jalvesaq/Nvim-R#377]
I'm not able get nvim-R running using termite. With 

`let R_term = 'termite' `
or
`let R_term_cmd = 'termite'`

in my vimrc I get `"Job" exited with status 1` on `\rf` and no terminal opens. However when hitting `\rq` I do not get the` 'Did you aready start R?'` message but `'can't find window NvimR-262'`. 

Everything works fine with urxvt or gnome-terminal. I'm not sure if this is actually an issue or if termite is just not on the list of compatible terminals...

System Info:
Linux 64-bit
R version 3.5.2 (2018-12-20)
nvimcom_0.9-27 
VIM 8.1

**Comment by jalvesaq** [comment]
Can you run tmux in termite?

**Comment by supersambo** [comment]
Yes I can.

**Comment by jalvesaq** [comment]
The `R_term` and `R_term_cmd` options are useful only to run R in a Tmux session in an external terminal emulator. The main reason for this is to run R and Vim in different windows when you have two monitors. If you want to use Vim commands to copy and paste things, then, you have to run R in a Vim/Neovim built-in terminal. Be sure that the value of `R_in_buffer` is 1 (the default), start Vim/Neovim in termite, edit an R script, and press `<LocalLeader>rf`.

**Comment by supersambo** [comment]
Sorry for answering so late. I must say I'm a bit confused, apparently my setup behaves somewhat differently :). 
Whenever I run `<LocalLeader>rf` it opens a new terminal, according to what I've set in `R_term`, and all of the documented (!) terminals I've tried so far work perfectly (gnome-terminal, xterm, urxvt). However, `let R_in_buffer = 1` does not have any effect. No matter what, it always opens a new terminal and not a buffer within vim (which I actually do like). Also, it doesn't open R within a tmux session at least I can't see any tmux bottombar and and `tmux list-sessions` doesn't list any.

**Comment by jalvesaq** [comment]
Are you using an old Vim version? Does it have the `:terminal` command?

**Comment by supersambo** [comment]
I'm using Vim 8.1.877. `:terminal` successfully opens a terminal in vim.

**Comment by jalvesaq** [comment]
I have simplified the test to turn R_in_buffer = 0. Could you update the plugin and try again, please.
If it still doesn't run in the built-in terminal, you could start Vim without opening any file and check the value of R_in_buffer:

```vim
:echo R_in_buffer
```

**Comment by supersambo** [comment]
It does open in the terminal now when `R_in_buffer = 1`. Thanks!

Coming back to my initial question :). If setting `R_in_buffer = 0` (which is my preferred way of using it) it still does not use tmux. Again, everything works perfectly still and I'd even prefer avoiding tmux but I'd like to get my current setup (`R_in_buffer = 0` so it opens in a seperate terminal without tmux) working with termite. 

Is there a way of doing this?

**Comment by jalvesaq** [comment]
Please, look at https://github.com/jalvesaq/Nvim-R/blob/master/R/tmux_split.md
