### ISSUE TITLE
An error is reported at startup if no .inputrc file is present in the home directory

### ISSUE THREAD

**Issue by jpasquier** [jalvesaq/Nvim-R#378]
An error is reported at startup if no .inputrc file is present in the home directory

```
Error detected while processing .../Nvim-R/R/common_global.vim:
line 3658:
E108: No such variable: "s:inputrc"
```
If I put an empty  .inputrc in my home directory, this error does not occur.

Moving `unlet s:inputrc` from line 3658 to line 3656 in R/common_global.vim (i.e. inside the if / endif block where `s:inputrc` is defined) seems to solve the issue.

**Comment by yech1990** [comment]
https://github.com/jalvesaq/Nvim-R/pull/379

**Comment by jalvesaq** [comment]
I'm sorry about that. It is fixed now.

**Comment by jpasquier** [comment]
Thank you very much
