### ISSUE TITLE
Run R via tmux in split window instead of new, external application

### ISSUE THREAD

**Issue by klmr** [jalvesaq/Nvim-R#38]
I’m running NVIM 0.1.3-dev with Nvim 0.9.1 inside iTerm 2 Build 1.0.0.20130319. I’d like to use tmux instead running R inside an Nvim buffer for various reasons (1). In Vim/Vim-R I could simply launch Vim inside tmux and then, when launching R using \<leader>rf, I got a nice vertically split screen with Vim and the R console.

I’ve tried achieving the same in Nvim-R using the following configuration:

```vim
let R_term = "xterm"
let R_silent_term = 1
let R_vsplit = 1
```

However, when launching R via \<leader>rf, R is instead launches inside a separate xterm.app window. How can I disable this and instead launch R inside the tmux split screen?

---

(1) The main reason is that the input mode in the R console works very weirdy; it doesn’t respect inputrc (duh), but nor does it accept proper vim movement commands; for instance, Esc, 0 does not go to the beginning of the command line (well; it does, but once I go back into insert mode I’m back at the end of the line). It also seems inconvenient that I cannot change focus back to the editor buffer without first leaving insert mode; but maybe I’m overlooking something.

**Comment by jalvesaq** [comment]
We have this in the documentation section about terminal emulator options:

> Note: The options of this section are ignored on Mac OS X, where the
> command `open` is called to run the default application used to run shell scripts.

We can change this if people using Mac OS X write a pull request and test it.

My goal is to make the plugin simpler for inexperienced users, that know nothing about tmux, and that would not be comfortable having to configure many applications just to use the plugin. To make Tmux optional, so users don't have to learn it if they don't want to, I moved the documentation about it to section 9 (FAQ and tips). In this section, we have this:

> Before Neovim's built in terminal emulator was developed, the best way
> of running R was inside a Tmux session. It is still possible to do this,
> as explained in this section.

> Tmux >= 1.8 is required, and you have to put in your vimrc:

```vim
   let R_in_buffer = 0
   let R_applescript = 0
   let R_tmux_split = 1
```

I can't notice any difference between Neovim terminal and the parent terminal emulator on Linux, and I see as a good thing that we have Normal and Terminal (Insert) modes in the terminal: the Normal mode is to move around and copy and paste text while the Terminal mode is to use the terminal as if I was not in a text editor.

**Comment by klmr** [comment]
Damn, I had read the *whole* documentation, *and* I had grepped for `tmux`. And still I missed that section. Thanks a lot: it now works exactly as expected.

Incidentally, I think that your approach to make the plugin easier to configure for beginners is definitely the right path. It’s just that the combination MacVim(!) + Vim-R used to work perfectly for me (missing features due to the lack of `clientserver` notwithstanding), and now incremental updates have stopped it from working completely, so I had to set up a configuration from scratch.

Regardless, this is one of the best Vim plugins I’ve ever worked with. I’d love to contribute but Vim script gives me the willies.

---

Regarding the moving around in the Neovim terminal, I agree that the distinction between normal mode and insert mode is good (in fact, it’s better than what tmux mode offers). However, it prevents me from moving around *inside the R prompt*; that is, I cannot edit the prompt itself, just append to it. Normally, I can use Vim movement commands to navigate the prompt (using vim keymapping in `~/.inputrc`).

**Comment by paulrougieux** [comment]
I use vim inside tmux and would like to open R in a new tmux split (because of the tmux zoom option, and also resizing splits is easier in tmux). Based on the update section, the option seems to have been removed:

     0.9.12 (2018-08-19)
     * Remove option R_tmux_split.

But  `:help R_csv_app` still explains how to display a csv tables in a tmux pane:

    If you are running Vim/Neovim within Tmux, you may prefer:  
    let R_csv_app = 'tmux new-window vd'

Is it possible to use a similar trick to have Nvim-R start the R session in a tmux pane:

    `split-window -h R`

**Comment by jalvesaq** [comment]
The command to open `vd` in a new Tmux pane works without the need of any special support by Nvim-R, and it's independent of the support for opening R in a Tmux split pane.

For the equivalent to Tmux zoom command, please, seek the word "zoom" in Nvim-R documentation.

It's still possible to open R in a Tmux split pane: https://github.com/jalvesaq/Nvim-R/blob/master/R/tmux_split.md
