### ISSUE TITLE
Error when help is displayed in nvim

### ISSUE THREAD

**Issue by jpasquier** [jalvesaq/Nvim-R#380]
I get an error when I try to display an help page in neovim 0.2.2:

```
Error detected while processing function ROnJobStdout:                                                                                                                                                                                
line    7:
E116: Invalid arguments for function ShowRDoc
```

I tried to reproduce this issue with the default config of neovim and nvim-r (empty init.vim) and with no plugin other than nvim-r installed. This issue still persist with this configuration.

**Comment by jalvesaq** [comment]
Nvim-R is developed with the development version of Neovim, and I can't guarantee compatibility with older versions. Neovim 0.2.2 was released on November 2017. So, you should try either Nvim-R 0.9.10 or 0.9.11.

**Comment by jalvesaq** [comment]
But I confirm the bug. Sorry. I introduced it yesterday.
