### ISSUE TITLE
[support] Running  Nvim-R in windows

### ISSUE THREAD

**Issue by lf-araujo** [jalvesaq/Nvim-R#381]
Hi Jackson,

I have been attempting to make Nvim-R run on a windows machine, however I am stuck in part of the installation. 

1. R is installed with administrative privileges (which I do not have) in C:\\Users\\luis.araujo\\Documents\\R\\R-3.5.1\\bin\\x64\\R.exe
2. Nvim-R was installed using a vim package manager that I am used to use called dein, but it is similar to more common ones;
3. I have set R path to the above directory

But whenever I try to start R from Nvim-R with \rf I get:

```
Durante a inicializa<e7><e3>o - Warning messages:^M^@1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :^M^@  there is no package called 'nvimcom'^M^@2: package 'nvimcom' in options("defaultPackages") was not found ^M^@Error in file
(file, if (append) "a" else "w") : ^M^@  n<e3>o <e9> poss<ed>vel abrir a conex<e3>o^M^@Calls: sink -> file^M^@Al<e9>m disso: Warning message:^M^@In file(file, if (append) "a" else "w") :^M^@  n<e3>o foi poss<ed>vel abrir o arquivo '/tmp/Nvim-R-luisaraujo/libpaths': No su
ch file or directory^M^@Execu<e7><e3>o interrompida^M^@
Aperte ENTER ou digite um comando para continuar
```

I found [this](https://github.com/jalvesaq/Nvim-R/issues/163) ticket and tried to build and install nvimcom. Building works as expected and a file `nvimcom_0.9-76.tar` appears where within Nvim-R folder.

Installation fails, however:

```
$ C:\\Users\\luis.araujo\\Documents\\R\\R-3.5.1\\bin\\x64\\R.exe CMD install nvimcom
install: missing destination file operand after 'nvimcom'
Try 'install --help' for more information.
```

- I am out of ideas now, how you suggest I go about it?

Many thanks from long time user of Nvim-R on linux.

Best,

**Comment by jalvesaq** [comment]
The message "there is no package called 'nvimcom'" means that the package nvimcom is not installed.

Why Nvim-R's temporary directory is on `/tmp` ? This is not a default Windows directory. If you have set `R_tmpdir` in your vimrc, you should ensure that the directory exists.

**Comment by lf-araujo** [comment]
Thank you for the answer,

I am using the same terminal emulator that is installed when git is installed on windows.

The `/tmp` directory in this terminal seems to mirror windows temporary directory at `C:\Users\luis.araujo\AppData\Local\Temp`.

I haven't changed `R_tmpdir`

**Comment by jalvesaq** [comment]
I guess that `/tmp` is `C:\tmp`.

**Comment by jalvesaq** [comment]
For years, I have rebooted my computer on Windows only to fix something on Vim-R-plugin and Nvim-R, but the last time that did this was on October 2018. Perhaps someone with more experience on Windows will be able to help you.

Anyway, I don't remember what terminal emulator comes with git but this shouldn't make any difference. What does make difference is if you have installed R and nvimcom in either Cywin or msys and is trying to use regular GVim. If you are using Cygwin, you have to use Vim that is installed in Cygwin. If you are using Gvim, you have to install R for Windows and Rtools.

**Comment by jranke** [comment]
How come your R installation is in your home directory, but still was done using administrative privileges? Maybe you do not have writing privileges in the directory that nvimcom should be installed to?

What vim version are you using?

I am happily using nvim-R with gVim under Windows.

**Comment by jalvesaq** [comment]
I could try today in a virtual machine and it worked. Please, see https://github.com/jalvesaq/Nvim-R/issues/456
