### ISSUE TITLE
Include markdown filetypes

### ISSUE THREAD

**Issue by DryLabRebel** [jalvesaq/Nvim-R#382]
Hi,

I had a similar question [to this issue](https://github.com/jalvesaq/Nvim-R/issues/132).

Had you considered extending the default filetypes that work with Nvim-R to include ordinary markdown?

**Comment by jalvesaq** [comment]
Markdown is not an R filetype. I know that some people need to run R and Python, and possibly other programming languages, from a markdown document, but I have never had to include a language other than R in markdown. This means that I would not be the first one to see bugs and it would not be easy for me to fix them.

Moreover, the default syntax highlighting of markdown doesn't highlight R code in fenced blocks. There are many flavors of markdown and people install many plugins for markdown, and it's impossible to keep Nvim-R well integrated with all these plugins.

**Comment by DryLabRebel** [comment]
Yeah that makes sense.

My motivation was that Nvim-R makes it extremely convenient to publish Markdown documents into PDF, making it an extremely effective general tool for producing rendered markdown documents.

If you extended it to include markdown, it might serve as a very popular markdown editing plugin even for non-R users.

But your right, and yeah there's probably a good plugin for markdown that does it already, I'm just too lazy to find it.
