### ISSUE TITLE
Feature request: Should provide Roxygen comment generation

### ISSUE THREAD

**Issue by brandones** [jalvesaq/Nvim-R#383]
RStudio generates [Roxygen skeletons](https://blog.rstudio.com/2015/05/06/rstudio-v0-99-preview-more-editor-enhancements/) for functions. This is a wonderful feature. Nvim-R should do it, too.

**Comment by jalvesaq** [comment]
I don't use Roxygen. So, it's better if someone else does a pull request for this. But, it might be even better to use a plugin that inserts snippets such as [vim-snippets](https://github.com/honza/vim-snippets).

**Comment by brandones** [comment]
Yeah, you're quite right. I made some UltiSnips snippets and they're actually mostly better than what RStudio does. For future generations finding this:

```
snippet #'p "Roxygen package template" b
#' `!p snip.rv = snip.basename`: $1
#'
#' $2
#'
#' @docType package
#' @name `!p snip.rv = snip.basename`
endsnippet


snippet #' "Roxygen function template" b
#' $1
#'
#' @param $2
#'
#' @return $3
#'
#' @examples
#' $4
#'
#' @export
endsnippet
```
