### ISSUE TITLE
New source methods causes error in debug mode

### ISSUE THREAD

**Issue by hongyuanjia** [jalvesaq/Nvim-R#384]
Thanks for this great plugin!

On https://github.com/jalvesaq/Nvim-R/commit/8b530a53615960d8d9ed13f513b5dc0e5f740895, changes were made to the source method, which causes some variable scoping problem in debug mode.

Considering this simple case below. If my cursor is at `z` and I hit `<LocalLeader>pp` to evaluate the paragraph

```r
test <- function (x) {
    browser()

    y <- x + 1
    z <- y + 2
    z

}

test(0)
```
Before https://github.com/jalvesaq/Nvim-R/commit/8b530a53615960d8d9ed13f513b5dc0e5f740895, `base::source()` is directly used, and everything works fine. I added `local = TRUE` to `R_source_args` to make sure all variables are evaluated in the environment where `base::source()` is called.

```vim
let R_source_args = "print.eval = TRUE, local = TRUE, encoding = 'UTF-8'"
```

```r
> test(0)
Called from: test(0)
Browse[1]> base::source("/tmp/Nvim-R-hongyuanjia/Rsource-29073", print.eval = TR
UE, local = TRUE, encoding = 'UTF-8')
[1] 3
```

However, after https://github.com/jalvesaq/Nvim-R/commit/8b530a53615960d8d9ed13f513b5dc0e5f740895, I get an error message.

```r
Called from: test(0)
Browse[1]> NvimR.paragraph(print.eval = TRUE, local = TRUE, encoding = 'UTF-8')
Error in eval(ei, envir) : object 'x' not found
Browse[1]> 
```

What should I do to reserve the old scoping? Thanks!

**Comment by hongyuanjia** [comment]
By the way, could you please give some suggestions on how to easily debug functions using NVim-R? Could you describe your typical work flow of debugging using NVim-R? Mine is manually insert `browser()` and evaluate each lines and find the reason.

In `9.1.5. Debugging R functions` in the help file, debug package is suggested. Unfortunately, debug has been removed from CRAN, as also stated in the help file. Do you use it for daily basis?

Thanks.

**Comment by hongyuanjia** [comment]
After digging a little bit, adding `local = parent.frame()` in `NvimR.*()` functions does the trick. Please see [here](https://github.com/hongyuanjia/Nvim-R/commit/2dd9c5c05303a864ed25fdc5e414102ced227935).

```r
NvimR.selection <- function(..., local = parent.frame()) NvimR.source(..., local = local)
NvimR.paragraph <- function(..., local = parent.frame()) NvimR.source(..., local = local)
NvimR.block     <- function(..., local = parent.frame()) NvimR.source(..., local = local)
NvimR.function  <- function(..., local = parent.frame()) NvimR.source(..., local = local)
NvimR.chunk     <- function(..., local = parent.frame()) NvimR.source(..., local = local)
```

I am not sure if this will break some functionality of option `R_source_args`, though.

**Comment by jalvesaq** [comment]
The new source functions were developed following a request made by @chrisvacc of a more clean and informative source method, and we didn't anticipate this issue.

I tried your solution, and it works. Could you do a pull request, please? If someone still finds an issue with the new source functions, I will have to go back to calling `base::source` directly.

**Comment by hongyuanjia** [comment]
Sure! A pull request has been sent.

**Comment by jalvesaq** [comment]
Thanks! I merged the pull request.

**Comment by jalvesaq** [comment]
> By the way, could you please give some suggestions on how to easily debug functions using NVim-R? Could you describe your typical work flow of debugging using NVim-R? Mine is manually insert `browser()` and evaluate each lines and find the reason.

The debug package is no longer on CRAN due to many warnings during R CMD check, but it still works. I may adapt its code to Nvim-R/nvimcom in the future.

**Comment by hongyuanjia** [comment]
Thanks! I will give debug package a try. Hope Nvim-R will have its built-in debugging functionality in the near future.

**Comment by jalvesaq** [comment]
I added limited debugging functionality to https://github.com/jalvesaq/Nvim-R/tree/debug

I will merge the `debug` branch soon.

**Comment by hongyuanjia** [comment]
Super! Looking forward to that

**Comment by jalvesaq** [comment]
I finished the implementation. If no bug is reported in the next 24 hours, I will merge the changes into the master branch.
