### ISSUE TITLE
Colors in Windows Terminals

### ISSUE THREAD

**Issue by blayz3r** [jalvesaq/Nvim-R#386]
This is a question about colors in a Windows terminal, I am able to see colors with Neovim and in Vim normal mode. My question is does https://github.com/vim/vim/commit/aa5df7e3127dff6b7336df0903f5c569a40eb174
 enable colors to be viewed in vim 8 terminal insert mode?

**Comment by jalvesaq** [comment]
The last time that I rebooted my laptop on Windows was about October 2018, but I just tried to set the syntax highlighting in the terminal and it works only while in Normal mode. The command to enable the syntax is `:set syntax=rout`

**Comment by blayz3r** [comment]
Cool, this is really more of a nice to have. Thanks
