### ISSUE TITLE
Proper way of installing nvimcom in Linux/Arch systems

### ISSUE THREAD

**Issue by hinojojojo** [jalvesaq/Nvim-R#388]
Hi
I would like to know what would be a recommended way of installing nvimcom in a Linux system (specifically I use Manjaro, an Arch-derived one, but I guess that does not matter much). I know that nvimcom is installed automatically by neovim or vim, but the installation requires granting writing permission to the system library at /usr/lib/R/library, even if you have changed the folder for user library to other part not requiring additional permissions.
What would be a recommended way to deal with this issue and be able to install nvimcom without granting writing permissions to anyone?

Sorry if this is a newbie question, but I haven't found much information about this in other places.

**Comment by jalvesaq** [comment]
Are you running neovim through `sudo`? You should run just `nvim` and not `sudo nvim`.

**Comment by hinojojojo** [comment]
No, I just run nvim

**Comment by jalvesaq** [comment]
Can you install packages with the command `install.packages()` when running R directly in the terminal? For example, `install.packages("data.table")`.

**Comment by hinojojojo** [comment]
Yes, packages can be installed perfectly on my user library for R packages, but if I try them to install in the system library (/usr/lib/R/library) R (or me) does not have the writting permissions and I did not wanted to gran writing permissions for that folder. Apparently nvimcom needed some step at the system library as its automatic installation required writing permissions on the system library.

However, when I tried today, just before writing this, I was able to get nvimcom installed automatically. I am almost sure that I haven't changed anything beside just installing a package in R directly.

**Comment by jalvesaq** [comment]
> However, when I tried today, just before writing this, I was able to get nvimcom installed automatically. I am almost sure that I haven't changed anything beside just installing a package in R directly.

This means that Nvim-R failed to detect the correct directory that should be made to install nvimcom. R created the directory when you installed a package. Then nvimcom was successfully installed.

**Comment by hinojojojo** [comment]
haha, well, I am glad that the solution was easier than I thought. I was having the same issue in my two computers.
Thank you very much for your support.

**Comment by jalvesaq** [comment]
I can't replicate the issue on Ubuntu. I get the following question in Neovim's status bar when I try to run R for the first time and there is no package installed in the `~/R` directory:

```
"/usr/local/lib/R/library" is not writable. Should "~/R/x86_64-pc-linux-gnu-library/3.5" be created now? [y/n]                                                       
```
I have only to press `y` to get nvimcom installed. When I do `<LocalLeader>rf` again, R starts.

**Comment by jalvesaq** [comment]
I've made some improvements to the `CheckNvimcomVersion()` function. Perhaps if you were installing the plugin now you would not see any bug.

**Comment by khughitt** [comment]
I don't think I've run into this issue on Arch before, but I tested it out just now with no `~/R` directory to see if I could replicate the issue and Nvim-R is able to detect/install Nvimcom to the user library:

```
"/usr/lib/R/library" is not writable. Should "~/R/x86_64-pc-linux-gnu-library/3.5" be created now? [y/n] y                              
Updating nvimcom... Building lists for omni completion... OK!                                                                           
Application "nclientserver" not found.                                                                                                  
Press ENTER or type command to continue     
```              

It throws the `nclientserver` warning the first time, but attempting to open a terminal a second time results in Nvimcom being properly updated/running.

**Comment by jalvesaq** [comment]
@hinojojojo I released a new version of Nvim-R today. If you still find problems, please report the issue again.
