### ISSUE TITLE
Application "nclientserver" not found

### ISSUE THREAD

**Issue by fotossinto** [jalvesaq/Nvim-R#389]
Hi!
I installed Termux, R and Nvim on my Chromebook. However, when I type \rf to start running R in nvim, it says `Application "nclientserver" not found`.
I followed what [this](https://conr.ca/post/installing-r-on-android-via-termux/) guy did to install nvim, so that I could have a layout similar to RStudio.

Thanks

**Comment by jalvesaq** [comment]
The message means that the nvimcom package that comes with Nvim-R was not running, or that it's running, but failed to start the server. Maybe nvimcom wasn't installed... You could try running R directly in the terminal and install any package with the `install.packages()` command to make it easier the automatic installation of nvimcom by Nvim-R.

**Comment by fotossinto** [comment]
I tried it, and it says that `package 'nvimcom' is not available (for R version 3.5.2)`

**Comment by jalvesaq** [comment]
The package `nvimcom` is not available on CRAN, but can you install another package that needs the compilation of C code? Example: `install.packages("descr")`.

**Comment by jalvesaq** [comment]
@fotossinto Could you update Nvim-R and try again, please?

**Comment by fotossinto** [comment]
Hi! Sorry, for the late reply.
I couldn't install any other package that needs the compilation of C code; it said 
`sh: make: not found` 
`Warning in system (cmd): error in running command`
`ERROR: compilation failed for package 'descr'`

And when trying to update the Nvim-R: 
`E: conflicting values set for option Trusted regarding source https://its-pointless.github.io/files termux`
`E: the list of sources could not be read`

**Comment by jalvesaq** [comment]
You need at least `make` and `gcc` to compile `nvimcom`.
