### ISSUE TITLE
R_assign breaks down in rmarkdown filetype

### ISSUE THREAD

**Issue by vvarik** [jalvesaq/Nvim-R#394]
For R files, `R_assign`={0,1,2,3} behaves exactly as explained in Nvim-R documentation. When the filetype is rmarkdown, however, I get following error (regardless of the R_assign value):

    Error detected while processing function ReplaceUnderS
    line    1:
    E117: Unknown function: b:IsInRCode
    E15: Invalid expression: &filetype != "r" && b:IsInRCode(0) == 0
    line   47:
    E121: Undefined variable: isString
    E15: Invalid expression: isString

It seems harmless, but one can not use underscores any more. I'm on Linux (Ubuntu 18.04) and have rmarkdown plugin installed. It does not seem to matter if I use Vim or gVim, both give me the same error.

**Comment by vvarik** [comment]
I suspect it is an easy thing to fix if you know what you're doing, but I don't. Therefore, as a temporary workaround, I have disabled the feature altogether by commenting out the lines in .vim/plugged/Nvim-R/common_global.vim:

    " Replace 'underline' with '<-'
    if g:R_assign == 1 || g:R_assign == 2
        silent exe 'inoremap <buffer><silent> ' . g:R_assign_map . ' <Esc>:call ReplaceUnderS()<CR>a'
    endif

**Comment by jalvesaq** [comment]
Maybe this issue is a duplicate of https://github.com/jalvesaq/Nvim-R/issues/393

**Comment by vvarik** [comment]
I confirm that the error goes away when I remove rmarkdown plugin.  I might have some additional confounding issue(s) though: now without rmarkdown plugin, although R_assign values 1 and 2 work exactly as they should, values 0 and 3 give me `<-` each time I press underscore.

**Comment by jalvesaq** [comment]
I can't replicate the issue. R_assign works as described in the documentation here.

**Comment by vvarik** [comment]
I had 'R-vim-runtime' plugin installed (this got carried along in my .vimrc from ancient times). I removed that and the error went away even with 'rmarkdown' installed. I hope I did not waste too much of your time, jalvesaq, and thanks for writing these plugins.

**Comment by vvarik** [comment]
Recently, the problem reoccurred. Don't know if it makes any sense, but I suspect now that removing r-markdown plugin and then installing it again somehow makes the problem go away. I do use vim-plug, so one could think I also changed the order the plugins are loaded and this did the trick. This is not true, I just commented out `Plug 'vim-pandoc/vim-rmarkdown'`, uninstalled, removed the comment, installed. Now it works. Maybe it helps someone.

**Comment by paulrougieux** [comment]
Note this error also appears in an Rmarkdown document if you are editing R code outside of a chunk:

```
x_ 

Error detected while processing function ReplaceUnderS:
line    1:
E117: Unknown function: b:IsInRCode
line   47:
E121: Undefined variable: isString
```

The assignment works fine within an R chunk (sometimes). 
```
    x_ # will try to auto replace _ to  "<-" and create an issue here 
    ```{r}
    x_ # Will auto replace to "x <-" fine
    ```
```
It seem I cannot only reproduce this issue in a fresh .Rmd file. The issue disappears once there is at least one chunk in the document.
