### ISSUE TITLE
R documentation buffer too narrow with :set number

### ISSUE THREAD

**Issue by cswingle** [jalvesaq/Nvim-R#395]
I have `set number` in my `nvim/init.vim`. When I open R documentation, the width it choses to use to format the documentation assumes there are no numbers, so some lines get forceable wrapped in unattractive ways. I see there's a nvim option for disabling numbers in terminals (so there aren't numbers in the R console), but I don't see any options for disabling numbers in the documentation buffer (or other Nvim-R spawned buffers). Could that either be made an option, or have the code that formats the R documentation determine the width post-number in the case where `set number` is in nvim's config?

**Comment by jalvesaq** [comment]
I can:

- create an option to set/unset `number` in the documentation buffer;

- consider the option `number` while calculating the buffer width;

- simply `set nonumber`.

Of course, the third option is the easiest to me. Do you see any advantage of having `number` set in the documentation buffer? If not, I will simply unset it.

**Comment by cswingle** [comment]
I can't imagine why you'd want `number` set in the documentation (or global object) buffers since the numbers are pretty meaningless in that context. The `set nonumber` third option would make me happy, and if it's easy to accomplish, even better.

**Comment by jalvesaq** [comment]
It's just one line... Thanks for your feedback.
