### ISSUE TITLE
Command to kill current R command

### ISSUE THREAD

**Issue by shreeramsenthi** [jalvesaq/Nvim-R#397]
So I've got some chunks of code that take a fair bit of time to run and frequently catch typos right after I start running the code. Currently, I have to switch to the terminal window, enter insert mode, press Ctrl+c, exit insert mode, and switch back to the previous split.

So rather than being more responsible with checking my code before running, I wrote up this shortcut to do that for me and mapped it to <LocalLeader>rk:

```
nmap <LocalLeader>rk :RSend <CR><C-w><C-p>i<C-c><C-\><C-n><C-w><C-p>
```

To see it in action, start R, and send `while(1){}`. Notice that the R session is now unresponsive. Now punch in the shortcut and we're back in action!

I use the `:RSend` command to "find" the terminal window relative to the current window, but this has the unfortunate side effects of adding that to your command history and adding the terminal window to your window switching history.

Is there a better way to implement this feature? And is this something anyone else would have use for? If so, I could make a pull request with this incorporated.

**Comment by jalvesaq** [comment]
Did you try

```
:RStop
```
?

**Comment by shreeramsenthi** [comment]
Oh man, I don't know how I missed that! I remember seeing it somewhere and assuming it just closed the R session. Thanks!
