### ISSUE TITLE
Option to start object window with all the object collapsed

### ISSUE THREAD

**Issue by xiaoouwang** [jalvesaq/Nvim-R#398]
Hello tks for the plugin, is there a option to set so that the objects window is opened with all the items folded (collapsed) by default ? I've checked the documentation to no avail, only finding out that 

  . Collapse (all lists)                               \r-

Cheers

**Comment by jalvesaq** [comment]
Please, search for `R_objbr_opendf` and `R_objbr_openlist` in the documentation.
