### ISSUE TITLE
base::source(..., spaced = spaced) limits R version to >= 3.4

### ISSUE THREAD

**Issue by UnobtainiumXDA** [jalvesaq/Nvim-R#399]
Commit d25976ec98f8ddfcf89f5d245844a7d57cd594b0 from February 3rd 2019, introduced the 'spaced' argument to base::source() calls.   I've only just updated my NVim-R package today and I get the following error message In R version 3.3.3 (which I need to use for all R code at work):

> NvimR.chunk()
Error in base::source(getOption("nvimcom.source.path"), ..., print.eval = print.eval,  : 
  unused argument (spaced = spaced)

spaced was added in R version 3.4.  

An R version wrapper is thus needed for the source() call in NVimR.source line 175 or so of R/nvimcom/R/nvimcom.R.  For example, the below works for me:

    NvimR.source <- function(..., print.eval = TRUE, spaced = FALSE)
    {
           if (with(R.Version(), paste(major, minor, sep = '.')) >= '3.4.0') {
              base::source(getOption("nvimcom.source.path"), ..., print.eval = print.eval, spaced = spaced)
           } else {
              base::source(getOption("nvimcom.source.path"), ..., print.eval = print.eval)
          }
    }

**Comment by jalvesaq** [comment]
Thanks!
