### ISSUE TITLE
Is insert supposed to put the assignment operator?

### ISSUE THREAD

**Issue by alexhallam** [jalvesaq/Nvim-R#403]
I was reading this part of the documentation.

![Rnvim_docs](https://user-images.githubusercontent.com/9298693/56073381-afe12900-5d70-11e9-9a4d-64363018bcd0.png)

I assumed that if I pressed the "Insert" button on the keyboard that `<-` would print. This did not work for me. What would you suggest I do to debug this?

**Comment by jalvesaq** [comment]
No, sorry. It means press `_` to insert ` <- `.
Any suggestion on how to make this clearer in the documentation?

**Comment by alexhallam** [comment]
haha, I did not notice the `_` over the O. Sorry, I do not have a better idea for improving the documentation. I think it is clear enough.

Thanks for maintaining this package!
