### ISSUE TITLE
Nvim not launching from opt with packadd

### ISSUE THREAD

**Issue by Blosberg** [jalvesaq/Nvim-R#409]
First, thanks very much for an excellent plugin.
I'm using Vim 8.1 on CentOS 7; I've installed the plugin using `call minpac#add('jalvesaq/Nvim-R')` and then launched it with `\rf`, and had good experiences using it. 
However, I had some trouble with leaving it on all the time (e.g. underscores automatically becoming assignments, etc.), so I decided to install the plugin to the "opt" folder instead with this in my .vimrc:  `call minpac#add('jalvesaq/Nvim-R', {'type': 'opt'} ) `.
From within my vim session, I then run `:packadd Nvim-R`, followed by the `\rf` binding, but nothing happens: I just keep `r`eplacing the character under the cursor with an "f", because vim is apparently not catching the remapping. Any suggestions as to why I'm not able to launch Nvim-R from an `opt` installation?

Thanks for any advice you can offer.
Edit: additional information: when I enter `:echo get(g:, 'maplocalleader', '\')` I get a `\`, so I'm fairly confident the local leader is defined.

**Comment by jalvesaq** [comment]
The plugin functions are loaded when the file type is defined. So, if you have already opened the file you could try
```vim
set ft=r
```
replacing `r` with the file type (`rmd`, `rnoweb`, etc).

You can disable the underscore replacement with the option
```vim
let R_assign = 0
```
What other "features" are annoying you?
