### ISSUE TITLE
Unmap ReplaceUnderS

### ISSUE THREAD

**Issue by lukaskawerau** [jalvesaq/Nvim-R#410]
I'm trying to unmap to auto-expansion of `_` to `<-` in insert mode, but as a new Vim user I can't figure out how this works.  

Following some advice on SO, I've created a file in `/after/plugin/` that sets `:iunmap <buffer> _`, but I get the message that there is no such mapping. When I type this in while editing it works, though.

Can you tell me how I can unmap this?

**Comment by matsburg** [comment]
There is an option for this included in the plug-in. Put this in your vimrc to disable the auto-expansion completely:
```vim
let R_assign = 0
```
You can also change it to use a different key combination, see `:help R_assign_map`.

**Comment by jalvesaq** [comment]
Thanks for answering the question, @matsburg !

**Comment by lukaskawerau** [comment]
@matsburg Thank you for the help, much appreciated! :)
