### ISSUE TITLE
Problem with neovim when R is not visible/made visible again

### ISSUE THREAD

**Issue by gmasarotto** [jalvesaq/Nvim-R#411]
First of all, thank for the great plugin! I love it and I used a lot with essentially no problems in vim/gvim. But recently, I wanted to move to neovim, and, I have a problem which make me impossible to use neovim with this plugin. 

The problem is that I use 
- to hide  the terminal windows where R is running (usally hitting \<C-w\>o in the .[R,Rnw,Rmd] window) and then either
- to send commands switching to the R console buffer to see the output;
- or to re-split the window making the R console visible again and sending new commands to it.

However,  after the terminal with the R console have been hidden the first time, I get the following error every times I send a command to R

>Errore/i eseguendo function SendLineToR[140]..SendCmdToR_Buffer:                    
>riga   30:
>Invalid window id
>Invalid window id

Note that the R commands are executed (and echoed if I request that). 
The described workflow works perfectly using vim.

guido

(ps) I am running vim/neovim on an updated Arch Linux box (so vim 8.1.1186, neovim 0.3.7.2) .
To reproduce the problem:
- launch neovim
- open whatever.R
- digit some commands in it  (eg. > 1+1)
- open R (for example \<localleader\>rf)
- send the line to R (for example using \<localleader\>l); all  should work as expected;
- close the window with R running (eg hitting \<C-W\>o in whatever.R)
- resend the line to R when the R console is hidden. ***You should get the error***
- Split the window, open the terminal with R in the other window and go back to
the window showing 'whatever.R'.
- Send the command to R. ***You should get the error***
- If you look to the R console, you should see that the lines you sent have been executed.

**Comment by jalvesaq** [comment]
`<C-w>o` kills R here, but I could replicate the issue with `:hide`. Could you please update the plugin and try again?

**Comment by gmasarotto** [comment]
Hi Jackson,
tried the new version of nvimbuffer, and...it works like a charm.
Obrigado!
guido

**Comment by jalvesaq** [comment]
Thanks for the feedback! I'm closing the issue.
