### ISSUE TITLE
Incompatibility with tmuxinator when calling StartR() on vim's startup

### ISSUE THREAD

**Issue by Nevrage** [jalvesaq/Nvim-R#412]
Hello,

I am using NvimR within a tmux session with the snippet mentioned somewhere in the issue tracker or the documentation:

```
if $TMUX != ''
    let R_source = '~/.vim/bundle/Nvim-R/R/tmux_split.vim'
    let R_csv_app = 'tmux new-window scim --txtdelim="\t"'
endif

```

I am also using tmuxinator to easily open entire projects with a YAML such as this one

```
name: IDE 
root: ~/Project/Example

windows:
        - To-Do: vim todo.txt
        - Mail: neomutt -e "source client.muttrc"
        - File Explorer: ranger
        - Scripts: cd App/Research/Script.R/ && vim -p *.R  -c 'call StartR("R")'
```

The tmux session opens with all the programs described here.
The issue is that the R session linked to the vim pane is open in the first tmux window.

Is there I could ask tmux/or vim to open it at the right time or anchor it to a specific window?
Is there a way for you to fix on your side?

I understand this is a compatibility issue that could be due to tmux/tmuxinator and tmux does not seem to be actively supported by the plugin anymore but that would be greatly appreciated

Thanks,

**Comment by jalvesaq** [comment]
I'm sorry for not answering your question in almost a year... But I can't maintain tmux_split.vim and until now nobody accepted the invitation in tmux_split.md to take over the maintenance of the script.
