### ISSUE TITLE
E121: Undefined variable: g:SendCmdToR when autostarting R

### ISSUE THREAD

**Issue by amorris28** [jalvesaq/Nvim-R#414]
I'm trying to start R automatically upon opening an `.R` or `.Rmd` file following this section of the documentation: 
>9.1. How to start and quit R automatically?~
>
>If you want that R is started automatically when you start editing an R
>script, you should create in |vimrc| auto commands for each R file type that
>you usually edit. However, you should try to start R only if it is not already
>started. Examples for R and RMarkdown:
>>
>   autocmd FileType r if string(g:SendCmdToR) == "function('SendCmdToR_fake')" | call >StartR("R") | endif
>   autocmd FileType rmd if string(g:SendCmdToR) == "function('SendCmdToR_fake')" | call >StartR("R") | endif
><
>And if you want to quit automatically when quiting Vim, put in your |vimrc|
>(replace `"nosave"` with `"save"` if you want to save R's workspace):
>>
>   autocmd VimLeave * if exists("g:SendCmdToR") && string(g:SendCmdToR) != "function('SendCmdToR_fake')" | call RQuit("nosave") | endif
><

I add these lines to my `.vimrc`:
```
autocmd FileType r if string(g:SendCmdToR) == "function('SendCmdToR_fake')" | call StartR("R") | endif
autocmd FileType rmd if string(g:SendCmdToR) == "function('SendCmdToR_fake')" | call StartR("R") | endif
autocmd VimLeave * if exists("g:SendCmdToR") && string(g:SendCmdToR) != "function('SendCmdToR_fake')" | call RQuit("nosave") | endif
```
but when I open an `.R` file in vim I get the following error:
>Error detected while processing FileType Autocommands for "r":
>E121: Undefined variable: g:SendCmdToR
>E116: Invalid arguments for function string
>E15: Invalid expression: string(g:SendCmdToR) == "function('SendCmdToR_fake')" | call StartR("R") | endif

Any idea what I'm doing wrong? Heres's my [.vimrc](https://github.com/jalvesaq/Nvim-R/files/3308162/vimrc.txt) for reference.

**Comment by jalvesaq** [comment]
It looks like some scripts were not completely sourced when the FileType event is triggered. Here (Neovim on Ubuntu, R_in_buffer = 1), R starts, but I can't send commands (message: "Not ready yet"). However, it works if I add a short sleep to the auto command:

```
autocmd FileType r sleep 1 | if string(g:SendCmdToR) == "function('SendCmdToR_fake')" | call StartR("R") | endif
```

**Comment by jalvesaq** [comment]
Does it make any difference if you put all Nvim-R options after the vim-plug's  begin/end block?

**Comment by amorris28** [comment]
Putting the Nivm-R options after vim-plug totally works. Now start and stop are working correctly. Thank you!

**Comment by jalvesaq** [comment]
Thanks for the feedback!
