### ISSUE TITLE
Nvim-R execute all R script above the current line?

### ISSUE THREAD

**Issue by smilesun** [jalvesaq/Nvim-R#415]
Not sure if this has been there before?  something like \su?

**Comment by jalvesaq** [comment]
This feature is missing. There is `<LocalLeader>ch` but only for Markdown, Rnoweb and ReStructured Text. It's not enabled for R.

What would be the most mnemonic key binding?

- `\su`: Send code UP (lines above the current one, not including the current line).

- `\sh`: Send the code from the beginning of the buffer up to Here (including current line).

- `\ch`: Send the chunk of code from the beginning of the buffer up to Here (including current line).

**Comment by smilesun** [comment]
i vote for \su

**Comment by jalvesaq** [comment]
The feature is implemented. Please, reopen the issue if you find any problem in the implementation.

**Comment by jalvesaq** [comment]
I'm sorry! I have committed the code in the wrong branch. Now, it's correct.
