### ISSUE TITLE
Allowing data to be viewed in splits

### ISSUE THREAD

**Issue by matsburg** [jalvesaq/Nvim-R#416]
Hi,

Currently, `RViewDF` opens data in a new tab. However, I think it would be useful to have the option of opening it in a split since this would allow viewing the data whilst still being able to see the original buffer.

Also, I often want to quickly view the head of a `data.frame` whilst I am coding, and opening the whole of the `data.frame` can be slow if it is large. Hence I suggest also introducing the option of viewing a certain number of rows of the data, rather than the whole thing.

I have this functionality working in a fork and can submit a PR if you would be interested.

Thanks!

**Comment by jalvesaq** [comment]
Yes. But could you update the `doc/Nvim-R.txt` too before submitting the pull request, please?

**Comment by jalvesaq** [comment]
Your pull request was merged and it is working perfectly. Thanks!
