### ISSUE TITLE
Default behavior for `RSendFile` when tmp file exists

### ISSUE THREAD

**Issue by andy-kwei** [jalvesaq/Nvim-R#418]
First, thanks for building this amazing plugin! It makes my R workflow so much cleaner. I have a question regarding the default warning behavior for `RSendFile` when a tmp file exists, as seen in the snippet below:

https://github.com/jalvesaq/Nvim-R/blob/42b188ad02b67c8d20d28a30bfa6a111aab5fcab/R/common_global.vim#L1390-L1410

This is usually fine, but it becomes a little inconvenient when working with Rcpp, where memory errors would cause the console to terminate ungracefully. This leaves the tmp file behind, in which case I would have to go into the terminal to find and remove it every time before being able to run `RSendFile` again.

I'm wondering if it would make more sense to overwrite the tmp file directly without producing the warning, or show the user a (y/n) prompt to delete the tmp file. Happy to submit a PR if this change makes sense, but I could be missing something.

**Comment by jalvesaq** [comment]
There is a very remote possibility of the file being manually created by the user. In this case, Nvim-R would delete user data. The fix might be changing the function `source.and.clean` (`R/nvimcom/R/nvimcom.R`) to:

```r
source.and.clean <- function(f, ...)
{
    on.exit(unlink(f))
    ok <- source(f, ...)
    if(inherits(ok, "try-error")){
        unlink(f)
    }
}
```

**Comment by jalvesaq** [comment]
Could you try the above change? You would have to delete the file `~/.cache/Nvim-R/nvimcom_info` to force the rebuild of nvimcom.

**Comment by andy-kwei** [comment]
Thanks for the quick response! The change above did not fix it - I added some print statements and the `if(inherits(ok, "try-error"))` line never gets reached when the console exits ungracefully.

Here's a minimal code example that triggers a segfault when sourced:
```
# uncomment this line if Rcpp is not installed
# install.packages("Rcpp")

Rcpp::cppFunction(paste0('
  void segfault() {
    *(int*)0 = 0;
  }
'))

segfault()
```

**Comment by andy-kwei** [comment]
On a related note, it would also be nice if the plugin could detect the crash and run `RClose` automatically to clean up. Usually when this happens, I have to run `RClose` before being able to run `RStart` again as the plugin believes the console is still running, even though the console pane closes automatically upon crash (this is only an issue in the tmux version I believe).

This is definitely not a big deal, but would be a nice behavior I think.

**Comment by jalvesaq** [comment]
With your `segfault()` function I can replicate the issue and I'm going to commit a change that fixes it when R is running in Neovim's terminal, but if R is running in an external terminal emulator you have to do `<LocalLeader>rq` after R has crashed.

**Comment by andy-kwei** [comment]
Works great! Thanks for the quick fix :)

**Comment by jalvesaq** [comment]
Thanks for the feedback! I'm closing the issue.
