### ISSUE TITLE
question: R terminal does not show in ls

### ISSUE THREAD

**Issue by ssh352** [jalvesaq/Nvim-R#419]
use neovim to open test.R, \rf to start R terminal in a split buffer. Then I use ls to list all buffers but I don't see the R terminal in the buffer list? is that expected? 

Also if I close the R terminal, but not \rq to quit it, how can I get the R terminal split back? Thanks!

**Comment by matsburg** [comment]
The R terminal buffer has the option `nobuflisted` set by default, which means it doesn't appear in the buffer list produced by `ls`. But you can use `ls!` to include unlisted buffers.

To open the R terminal buffer in a vertical split you could do something like

```vim
nnoremap <Leader>vt :exe "vertical sbuf " . bufnr("Rterm")<CR>
```

Where "Rterm" is just a string that matches the name of the terminal buffer ("Rterm" works on windows, but I think it might need to be something different on linux).

**Comment by jalvesaq** [comment]
If you close the terminal with the command `:q`, Neovim kills R. You could try `:hide` instead.

**Comment by ssh352** [comment]
Thank you both, I was a tmux+nvim-r user and successfully converted to use the built in terminal.
