### ISSUE TITLE
can't send code to R terminal after hiding it 

### ISSUE THREAD

**Issue by ssh352** [jalvesaq/Nvim-R#421]
I open a test.R, \rf to start R, then :hide to hide the R terminal split, :sp to open a split, :b2 to switch to the R terminal buffer, then I use \aa to send some code to the R terminal split and got the following error

<img width="824" alt="Screen Shot 2019-07-10 at 4 27 20 PM" src="https://user-images.githubusercontent.com/41779116/60953428-b8c1a680-a32f-11e9-8b25-1487cf323445.png">

**Comment by jalvesaq** [comment]
I can't replicate the issue. Is your Nvim-R up-to-date? The issue that you reports is supposed to have been fixed some days ago: https://github.com/jalvesaq/Nvim-R/commit/798db1140494d713c286e4524f2db9737e23eeb6

**Comment by ssh352** [comment]
Thank you. Updating the nvim-r to latest version fixed it.
