### ISSUE TITLE
SendSelectionToR sends code multiple times

### ISSUE THREAD

**Issue by wngrtn** [jalvesaq/Nvim-R#422]
Since one of the recent upgrades, all mappings that send a selection to R do no longer send it once. Instead they send the entire selection as many times as there are lines in the selection.

Just by blaming `SendSelectionToR` in `common_global.vim` I suspect that this is related to 61209dc, but my knowledge of vimscript and of the codebase are not sufficient to understand what is going wrong.

**Comment by jalvesaq** [comment]
Please, update the plugin and try again.

**Comment by wngrtn** [comment]
Many thanks! Works just fine again.
