### ISSUE TITLE
Is it possible to open the source file where a function is defined

### ISSUE THREAD

**Issue by statquant** [jalvesaq/Nvim-R#423]
Hello,
I find myself it the following situation very often: I load several packages I wrote and some exported function fails. The easiest way to debug is for me to find the source file the problematic function is in and use `degubonce(my_pkg::my_fun)` .
The process of finding the said file is annoying, is there a way to find this file and open it in vim ?
I know about `system.file(package = "my_pkg")` that would give me the library where I should find source files but finding the file containing the function is the difficult part for me.
Regards

**Comment by statquant** [comment]
Actually I realize open a fake file containing the function definition would work as well, this is probably much easier in nvimr framework

**Comment by matsburg** [comment]
You can jump to function definitions using `ctags`, see `:h Nvim-R-tagsfile` for help on setting this up for use with Nvim-R. You would need to create tags files for your packages and tell vim to add these to the list of tags files it uses for .R files.

But, for your particular use case of debugging functions, it may be easier to use the `mtrace` function in the `debug` R package. Look at tip '9.15. Debugging R functions' in the Nvim-R help for some more information.

**Comment by statquant** [comment]
Thanks @matsburg I red `:h Nvim-R-tagsfile` and that's useful but a little manual. Typically what you'd like is build the tags dynamically when you load a package for instance. If you change a function in your package you kind of want.
I just found out that there is something like that in https://github.com/mllg/vim-devtools-plugin I'll test and come back with feedback

**Comment by statquant** [comment]
Yeah it is actually very good, highly recommended
