### ISSUE TITLE
Problems with sending selected lines to console

### ISSUE THREAD

**Issue by duarteguilherme** [jalvesaq/Nvim-R#424]
For some reason, when I select lines in visual mode and then "\ss", the plugin runs the selected lines x times (x is the number of lines).

So for example, if I have something like:

   x  <- x %>%
      mutate(y = z + 1) %>%
      select(-z) %>%
      arrange(b)

and I try to run those lines using "\ss", the plugin runs these lines 4 times.

Is this a bug?

**Comment by mschilli87** [comment]
@duarteguilherme: IIRC, Nvim-R considers the whole pipeline 'one-line'.
If you place the cursor on the `x <- x %>%` line and run the current line, you'll see the cursor move down
below the `arrange(b)` line after executing everything. Thus, what you see is running all the code once (for the `x <- x %>%` line), all but the `x <- x %>%` line again (for the `mutate(y = z + 1) %>%` line), etc.

So to answer your question, I don't think this is considered a bug.

**Comment by jalvesaq** [comment]
@mschilli87 I introduced a bug 16 days ago (https://github.com/jalvesaq/Nvim-R/commit/61209dc8d282459f71fc30b5a48851c200f968c0) and fixed it 4 days ago (https://github.com/jalvesaq/Nvim-R/commit/fede9baebac89cbab86638af175b103c07bafd4f).
@duarteguilherme Could update the plugin and try again?

**Comment by duarteguilherme** [comment]
It worked. Thank you
