### ISSUE TITLE
Command to run R notebook params global

### ISSUE THREAD

**Issue by RichardJActon** [jalvesaq/Nvim-R#425]
In Rstudio if your YAML header contains a `params` argument like the example below it creates an immutable list called params with elements for the items in params. It would be great to have a command that created this list from your YAML header if you open an R notebook in the editor.

    ---
    params:
      variable: "With a value"
      complexity: "`r normalizePath('~/file.txt')`" # the `r <some code>` constructs are evaluated during creation of the list
    ---

#> params$variable
#> [1] "With a value"

**Comment by jalvesaq** [comment]
I've tried this in RStudio:

````
---
title: "R Notebook"
params:
  xxx: "abc"
  yyy: "`r rnorm(100)`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

Try to print yyy:

```{r}
print(params$yyy)
```
````

The `rnorm` command was not evaluated. The output is:

```
[1] "`r rnorm(100)`"
```

**Comment by jalvesaq** [comment]
The result in Nvim-R is the same after `<LocalLeader>kr`. However, if I send the line `print(params$yyy)` to R in RStudio the object `params` is created in R's workspace while in Nvim-R I get the error "object 'params' not found". So, what you want is a command to create the object `params` in R workspace, right? Please, try adding this line to your `vimrc`:

```
nmap <silent> <LocalLeader>pr :call g:SendCmdToR('params <- lapply(knitr::knit_params(readLines("' . expand("%") . '")), function(x) x$value)')<CR>
```

Then, you will be able to get the object `params` created after pressing `<LocalLeader>pr` in Normal mode.

**Comment by RichardJActon** [comment]
Excellent! that works. 

Yes you are right about the evaluation of stuff in the `` "`r <some R>`" `` constructs when they are in params I forgot that - interestingly it does work in other fields like bibliography. Also according to the documentation for `knitr::knit_params()` you can get that same results with params content if the `evaluate` option has its default value of `TRUE` and you use the syntax:

    ---
    params:
      date: !r Sys.Date()
    ---

This also works in Nvim-r with your solution.

One oddity though the resultant params object differs slightly from the one generated in RStudio, which has a class and is not just a plain list:

    $paramName
    [1] "paramValue"
    
    attr(,"class")
    [1] "knit_param_list"

I don't know why that would be if RStudio also uses `knit_params` to generate the list.

Also do you think that `\ch` should evaluate params like this given that pressing the evaluate all above chunks button in Rstudio also updates the params list?

**Comment by jalvesaq** [comment]
If you need the class, the command becomes more complicated:

```
nmap <silent> <LocalLeader>pr :call g:SendCmdToR('params <- lapply(knitr::knit_params(readLines("' . expand("%") . '")), function(x){ y  <- x$value; class(y) <- attr(x, "class"); y})')<CR>
```
For now, you have to press `<LocalLeader>pr` before `<LocalLeader>ch`. I may make this automatic later.

**Comment by RichardJActon** [comment]
Hmm that's not quite it either - that gives each element of the list the class `knit_param` which is not what Rstudio generates just calling `params <- knitr::knit_params(readLines("' . expand("%") . '"))` gives a list of `knit_param` objects but not a `knit_param_list` object for some reason; it appears to get converted to a `knit_param_list` by RStudio: 

https://github.com/rstudio/rstudio/blob/d4d6a5f4ce26ac55fc9eab69e0ecaf6c66d922ec/src/cpp/session/modules/SessionRMarkdown.R#L245-L265

So I think this might the way to go:

    nmap <silent> <LocalLeader>pr :call g:SendCmdToR('params <- lapply(knitr::knit_params(readLines("' . expand("%") . '")), function(x) x$value); class(params) <- "knit_param_list"')<CR>

Thanks for the help.

**Comment by jalvesaq** [comment]
Nvim-R is being superseded by R.nvim, a new project that will be inaugurated in a week at the [R-nvim](https://github.com/R-nvim) organization.
Please, check out [tmp-Nvim-R](https://github.com/jalvesaq/tmp-R-Nvim) and help us to find the last remaining bugs before R.nvim inauguration.
When the project is officially started, you will be able to open issues there and request new features.

Nvim-R will remain alive as a feature-frozen project for Vim users. If you want to know the reason, please, see [this discussion](https://github.com/jalvesaq/Nvim-R/discussions/797).
