### ISSUE TITLE
Setting R_openhtml=0 seems to have no effect

### ISSUE THREAD

**Issue by statquant** [jalvesaq/Nvim-R#428]
Hello, 
I wanted to prevent firefox from opening each time I render (\kr) a Rmd document but it does not seem to be working.
Would you see the same on your side, I use linux (centos7 with xfce desktop) ?
Regards

**Comment by jalvesaq** [comment]
I can't see the issue here. Are you sure that the value of `R_openhtml` is `0`? Please, check the output of
```
:echo R_openhtml
```

You might also want to look at Nvim-R's documentation:

```
:h Nvim-R-reload-html
```

**Comment by statquant** [comment]
Hello, I checked and `R_openhtml` is `0`. I do not have `Nvim-R-reload-html` I am behind so I'll pull (I have local changes) and come back

**Comment by jalvesaq** [comment]
Is it working now?

**Comment by statquant** [comment]
Yes it is thanks
