### ISSUE TITLE
question: how to keep the terminal open while I do ctrl-w o

### ISSUE THREAD

**Issue by ssh352** [jalvesaq/Nvim-R#429]
I open a test.R, use \rf to start R terminal in a split. Then I opened a couple other R files in more splits.  After reviewing the other R files, I want to close them. So I do a ctrl-w o in test.R split. This causes the R terminal to be hidden as well. Is there a workaround to close other splits while having the R terminal open? Thanks!

**Comment by jalvesaq** [comment]
I can't see a solution for this looking at Vim/Neovim's help:
```
:h CTRL-W_o
```
What command do you use to reopen the R window? You could bind `CTRL-W_o` in R scripts to close all windows and then open the terminal window. If you just view the other scripts, you could open them in new tabs...

**Comment by ssh352** [comment]
> What command do you use to reopen the R window? You could bind `CTRL-W_o` in R scripts to close all windows and then open the terminal window. If you just view the other scripts, you could open them in new tabs...

I use fzf :Buffers to list all buffers, select the R terminal buffer, then do ctrl-x to get the R window back. I can use the tabs instead, Thanks!
