### ISSUE TITLE
tmux NvimR process keeps running after closing NvimR

### ISSUE THREAD

**Issue by amorris28** [jalvesaq/Nvim-R#433]
Sometimes when I start R from Vim using Nvim-R, the tmux window pops open, but it fails to start R and this process remains running as seen in `top` and is using 100% of one my CPUs:
```
tmux -L NvimR -2 -f /tmp/Nvim-R-andrew/tmux.conf new-session -s NvimR-648 NVIMR_TMPDIR=/tmp/Nvim-R-andrew NVIMR_COMP+
```
The process will not be killed with SIGTERM (e.g. `kill -TERM pid`). I can only kill it with SIGKILL (`kill -KILL pid`). 

Playing around with it in an Nvim-R session, it looks like that process is started with I send a command from Vim to the R session in tmux, but is stopped as soon as the process completes. The only time it it gets stuck running is when I start R with `\rf` and it fails to load R. In this case I have to close the tmux window and retry `\rf` and then manually SIGKILL that process.

Any idea how to fix this?

Edit: I also noticed that I get a warning in my Vim window that says:
```
The package nvimcom wasn't loaded yet. Please, quit R and try again
```
Edit 2:
Looking at the documentation. I have not set `R_DEFAULT_PCKAGES` in my .Rprofile. I also haven't had this problem previously and haven't made any changes to my settings, there's just a 50:50 chance of whether R successfully loads nvimcom or not.

**Comment by jalvesaq** [comment]
Is any error messages displayed? You can see them again with the `:messages` command.

**Comment by jalvesaq** [comment]
I don't know how to replicate the issue, but if you upgrade Nvim-R you will be able to know what command was called to start R in an external terminal emulator. Just type in Normal mode `:RDebugInfo`.

**Comment by amorris28** [comment]
R open command from updated `:RDebugInfo`:
```
urxvt --title R -e tmux -L NvimR -2 -f "/tmp/Nvim-R-andrew/tmux.conf" new-session -s NvimR-09
6 "NVIMR_TMPDIR=/tmp/Nvim-R-andrew NVIMR_COMPLDIR=/home/andrew/.cache/Nvim-R NVIMR_ID=1064596
481513842694 NVIMR_SECRET=8948596281363474520 NVIMR_PORT=10101 R_DEFAULT_PACKAGES=datasets,ut
ils,grDevices,graphics,stats,methods,nvimcom R"
```

If I try to open R with `\rf`  I briefly get a message that says:
`wait...`

If I wait a minute I get this message:
`The package nvimcom wasn't loaded yet. Please, quit R and try again.`

If I try to close R with `\rq`:
`no server running on /tmp/tmux-1000/NvimR                                           `

If opening R is successful I get a brief message that says:
`updating nvimcom... `
And if I look at the output of `:RDebugInfo` it looks like it went through the process of installing nvimcom, which is installed in my `~/R` directory.

I'm not sure how to tell you replicate the issues because it happens sporadically. To demonstrate it working and not working in this comment I just had to start nvim and start R a couple of times so that it would work once and fail once.

**Comment by jalvesaq** [comment]
Could you try running the "R open command" manually directly in the terminal? Maybe you can see a useful error message.
You could also try another terminal emulator instead of urxvt.

**Comment by amorris28** [comment]
I ran the R open command in the terminal and the same thing happens. Another terminal window opens up and the tmux process keeps running endlessly. There was no error message. I tried running Nvim-R with the default `let R_in_buffer=1` and I do not get this problem, so it's definitely associated with tmux.

Also tried all of this in xterm and I get the same problem. 

Looking at the `:RDebugInfo` output, sometimes it seems to hang on `building 'nvimcom_0.9-83.tar.gz'`

Another thing it does is when I try to `\rq` it will say `can't find window: Nvim-R-449`

**Comment by jalvesaq** [comment]
Since yesterday, nvimcom is built with the `--no-lock` option (see https://github.com/jalvesaq/Nvim-R/commit/ca285ac3e72e3bc619179212ba4e3b58776ca325). Does this make any difference to your issue?

**Comment by amorris28** [comment]
Doesn't seem to have changed anything

**Comment by jalvesaq** [comment]
Then, I'm sorry, but I don't know what might be causing the bug.

**Comment by amorris28** [comment]
I switched over to Ubuntu 19.04 with gnome-terminal as the R buffer and this bug appears to have gone away, so it might be associated with Arch/Manjaro. Feel free to close this issue.

**Comment by jalvesaq** [comment]
Thanks for the feedback!
