### ISSUE TITLE
open R in another terminal

### ISSUE THREAD

**Issue by olesendan** [jalvesaq/Nvim-R#435]
Hi Jalvesaq.

I'm trying to figure out, if it's possible to let nvim-r open R in another terminal?

My context is:
arch linux
i3wm
urxvt
neovim
nvim-r

I've tried to see what the manual says about this feature. From what I can read, it's documentet, that it's possible with tmux. I'm trying not to have to many programs, and in my workflow, tmux would only be used for this one thing, so would like to avoid instlling.

Is there a way around this with any of this settings:

R_term_cmd:
R_app:
R_cmd:

would I be able to pass an command like :terminal open R? Would nvim-r be able to comunicate with R if it's in another terminal?

The reason for this, is that I find the navigation and resizing more intuitive in i3wm than in neovim.

Greetings from danmark
Dan Olesen

**Comment by jalvesaq** [comment]
To run R in another terminal, you have to:

  1. Install tmux
  2. Put the following line in your `init.vim`:
```
let R_in_buffer = 0
```

**Comment by jalvesaq** [comment]
One way of not using Tmux was if I implemented R running within Neovim because we need a way of controlling R's standard input.

**Comment by jalvesaq** [comment]
@olesendan do you have `screen` installed?

**Comment by olesendan** [comment]
Hi Jalvesaq

what is screen, and is it of any use besides opening R?

I'm vundering that if we have to rely on screen, then one migth aswell install tmux?
I will look at screen,

from my understanding of nvim-r, then nvim-r communicates with nvimcom( which communicates with R). can nvimcom detect R in another terminal?

Greetings from Denmark
Dan

**Comment by olesendan** [comment]
Hi again

Have just read about screen on arch linux.org

Whish one(tmux, screen) would you prefer if you should choose one? to me the seem to solve the same problem. So i'm thinking, futureproofing, footprint, complexity of usersetup?

Dan Olesen

**Comment by jalvesaq** [comment]
Screen and Tmux do basically the same thing. Screen is older and still more widely available than Tmux which was developed to overcome some of Screen's shortcomings. I used Screen in the [Vim-R-plugin](https://www.vim.org/scripts/script.php?script_id=2628) from 2009 to 2013, and Tmux is used since 2011.
If you install Tmux, you don't have to configure anything because Nvim-R creates a temporary configuration script for Tmux before running it in another terminal emulator.
I don't have time to adapt `R/extern_term.vim` to use screen, but if someone did it I could accept a pull request.

**Comment by olesendan** [comment]
Hi Jalvesaq.

I don't use or have screen installed. So in my opion we shold not go down that road.

You wrote earlier 

> "One way of not using Tmux was if I implemented R running within Neovim because we need a way of controlling R's standard input"

what do you mean with that? Should R not run in an terminal? 

I'm only asking this question because I'm not an sysadmin, and will never be. So terminal multiplexers are maybe a bit overkill. if there is another solution

unfortually I can't program. I'm just an user of R, and like your plugin. 

Greetings from Denmark
Dan Olesen

**Comment by LiNk-NY** [comment]
Hi Dan, @olesendan 

Without Tmux or Screen, you can't really open R in another terminal from vim.
That is what these programs do. 

I recommend Tmux but the installation does require some minimal effort. 

You can resort to copying and pasting code from vim to the terminal.
Just know that there are better ways of doing it and usually in life, 
doing better usually requires effort :wink: 

Best,
Marcel

**Comment by olesendan** [comment]
Hi Marcel.

Thank you, for your reply.

Actually I'm trying tmux, for neovim. I'm just using neovim minimal tmux config, because I do not use tmux for anything else(that I know of). The only problem, I've experienced is that vifm have stopped showing its window. I'm guessing that somehow tmux interference with vifm(my terminal is just showing a blank screen, when I try to run vifm).

tmux does just what I'm looking for, it opens R in it's own window. My reason for asking the question, was to awoid a extra program for only one operation.

Greeetings from denmark
Dan Olesen
