### ISSUE TITLE
package ‘nvimcom’ in options("defaultPackages") was not found

### ISSUE THREAD

**Issue by neumanrq** [jalvesaq/Nvim-R#437]
### The surface error 

When trying to start the `nvimcom` connection, I get the following error message:

```
Beim Start - Warnmeldungen:
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.ret
urn = TRUE,  :
  es gibt kein Paket namens ‘nvimcom’
2: package ‘nvimcom’ in options("defaultPackages") was not found
>
```

### Context 

OSX v10.14.6
NVIM v0.4.2
R v3.6.1

It could be the case that the underlying problem is related to #188, but the proposed solution (deletion of  `~/.cache/Nvim-R/nvimcom_info`) does not work - so it could be the case that there's something new happening here.

### What I have tried so far… 

(1) I cloned the repo, `cd`ed into the directory `Nvim-R/R/nvimcom` and tried installing the package locally (by `devtools::install_local`) which worked fine, so I assume that compilation parts of `nvimcom` are working fine on my machine. 

(2)  Because of (1) I tried to install and load the package locally from the R-session within nvim. The installation worked fine, but calling `library(nvimcom)` then resulted in this error message:

```
Fehler: package or namespace load failed for ‘nvimcom’:
 .onAttach in attachNamespace() für 'nvimcom' fehlgeschlagen, Details:
Aufruf: if (as.integer(getOption("nvimcom.lsenvtol")) < 10) options(nvimcom.lsenvtol = 10)
Fehler: Argument hat Länge 0
Zusätzlich: Warnmeldung:
Your version of Nvim-R requires nvimcom-0.9-28.
```

Unfortunately, I'm running out of ideas - any inspiration on how to proceed/fix/debug are welcome! ☀️

**Comment by jalvesaq** [comment]
We should discover why the automatic updating of nvimcom is not working. Anyway, the current version of nvimcom is 0.9-83, and your Nvim-R requires nvimcom 0.9-28. So, could you update Nvim-R? I can only fix issues in the development version of Nvim-R.

**Comment by neumanrq** [comment]
I've run `:PlugInstall!` which should clone the latest state of the Nvim-R repository (doesn't it?) but the problem remains. Do you mean something different by updating Nvim-R?

**Comment by jalvesaq** [comment]
I usually do `:PlugUpdate` to update my plugins. I don't know if `:PlugInstall!` updates what is already installed.

**Comment by neumanrq** [comment]
It looks like `:PlugUpdate!` fixed the problems for me. So after this, everything is working and I can't reproduce the above problem any longer. Thanks for your help and for your entire work on Nvim-R!
