### ISSUE TITLE
R dont start <localleader> rf

### ISSUE THREAD

**Issue by olesendan** [jalvesaq/Nvim-R#438]
Hi All.

Today nvim-r have stopped being able to start R.
I can start R from the terminal.

It worked yesterday, but not today. I don't recall making any changes to my setup.
I'm on:
archlinux
I3
bash
urxvt
R 3.6.1

In my .Rprofile I have
   if(Sys.getenv("NVIMR_TMPDIR") != ""){
       library( nvimcom)
       library( colorout)
   }

When I try to start R from vim(<localleader> rf) I get the following error
    Error in library(nvimcom) : there is no package called 'nvimcim'^@Execution halted^@

running :RDebugInfo I get 
    .libpaths()
    Error in library(nvimcom) : there is no package called 'nvimcom'
    Execution halted.

I'v tried to do manuel install of nvimcom in R, which do not work - install.packages("nvimcom").

What am I doing wrong?

Greetings from denmark
Dan Olesen

**Comment by olesendan** [comment]
ok.

False alarm. It has started working again, so don't know what has happend on my computer

/Dan

**Comment by olesendan** [comment]
I'we managed to get this errormessage now.

***Successfully loaded .Rprofile ***
Hej Dan
Velkommen til Rstudio med R
Dato er: Fri Oct  4 13:40:25 2019

* installing to library ‘/home/dano/.config/R/library’
* installing *source* package ‘nvimcom’ ...
staged installation is only possible with locking
** using non-staged installation
** libs
ccache gcc -I"/usr/include/R/" -DNDEBUG   -D_FORTIFY_SOURCE=2  -fpic  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt  -c nvimcom.c -o nvimcom.o
ccache gcc -shared -L/usr/lib64/R/lib -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -o nvimcom.so nvimcom.o -L/usr/lib64/R/lib -lR
(cd apps; make)
make[1]: Entering directory '/tmp/RtmpbuFkFO/R.INSTALL68e3917ac89/nvimcom/src/apps'
cc -pthread -std=gnu99 -O2 -Wall nclientserver.c -o nclientserver
make[1]: Leaving directory '/tmp/RtmpbuFkFO/R.INSTALL68e3917ac89/nvimcom/src/apps'
installing via 'install.libs.R' to /home/dano/.config/R/library/nvimcom
** R
** byte-compile and prepare package for lazy loading
Error in localeToCharset() : could not find function "localeToCharset"
Error: package or namespace load failed for ‘nvimcom’:
 unable to load R code in package ‘nvimcom’
Execution halted
ERROR: lazy loading failed for package ‘nvimcom’
* removing ‘/home/dano/.config/R/library/nvimcom’

If I remove this from my .Rprofile, R starts as expected. 
if(Sys.getenv("NVIMR_TMPDIR") != ""){
library( nvimcom)
library( colorout)
}

Have other experienced this today?

/Dan

**Comment by jalvesaq** [comment]
Please, remove `library(nvimcom)` from your .Rprofile. The loading of nvimcom is triggered by the environment variable `R_DEFAULT_PACKAGES` which is set by Nvim-R.

**Comment by olesendan** [comment]
Hi Jalvesaq.

So this block is not nessarary anymore

if(Sys.getenv("NVIMR_TMPDIR") == ""){
       options(defaultPackages = c("utils", "grDevices", "graphics", "stats", "methods"))
   } else {
       options(defaultPackages = c("utils", "grDevices", "graphics", "stats", "methods", "nvimcom"))
   }
This one is the inspration for my little block in my .Rprofile.

/Dan

**Comment by jalvesaq** [comment]
This block should be used only if you have to set `defaultPackages` in your Rprofile.

**Comment by olesendan** [comment]
Hi Jalvesaq

I have this line in my .Renvion
R_DEFAULT_PACKAGES=graphics,grDevices,methods,stats,utils

Do this change your advise. 

I'm vundering what have changed, all was working yesterday, so something has changed?
/Dan

**Comment by jalvesaq** [comment]
I can't replicate the issue. Omni completion is working on my system.

**Comment by olesendan** [comment]
Hi Jalvesaq.

I think something has happend on my system. 
Besides that omnicomplete has stopped working I've also noticed that I can not send an paragraph to R. I get the following error:
"Error in NvimR.paragraph() : could not find function "NvimR.paragraph"" 

I just have figure out, what I have done...

**Comment by jalvesaq** [comment]
It looks like you have changed the configuration of your system. The usual fix when someone doesn't know what configuration was changed is to make a backup of all suspect configuration files, delete them and, then, create them again adding the pieces of the old configuration files one at a time and testing if the system works again.

**Comment by olesendan** [comment]
Hi Jalvesaq.

Thank you, for your reply. 
I'm still quite new to this. When you write "It looks like you have changed the configuration of your system", I read it as you are meaning the configuration of arch linux? or do you mean vim/nvim-r/R configuation?.

Are Nvim-r functions like "Sendline" different than "NvimR.paragraph" and "nvim.interlace.rmd"? 

Greetings 
Dan Olesen

**Comment by jalvesaq** [comment]
If you have edited files at the `/etc` directory (Renviron), then you should completely uninstall R and install it again.
If you have only edited `~/.config/nvim/init.vim`, then, you should only rewrite it.

> Are Nvim-r functions like "Sendline" different than "NvimR.paragraph" and "nvim.interlace.rmd"?

`Sendline` doesn' t exist. `RSendLine` is just a label for a specific key binding. The other two are nvimcom functions.

**Comment by olesendan** [comment]
Hi Jalvesaq.

Thank you for your time.

I think I have located the problem.

so for future reference.
the problem was this line in my .Rprofile
options( pager = 'internal')
I now realize, that this is only for windows(which is where I come from). On linux it should not be there.
I probely hd it commented out, and then without realizing what I did, uncommeted it.

Greetings from Denmark
Dan Olesen
