### ISSUE TITLE
E117: Unknown function: RMakePDF

### ISSUE THREAD

**Issue by rng-daemon** [jalvesaq/Nvim-R#439]
Recently, whenever I try to compile a .Rnw sweave file via vim, I get the error
"E117: Unknown function: RMakePDF".
The compiler step .Rnw -> .tex works via _R_ session. Just the transformation to PDF does not work.
I use Nvim-R via pathogen and I removed the package and downloaded the latest Git version again

**Comment by jalvesaq** [comment]
Thanks for reporting the issue. It seems that the bug was there for a long time. Please, update Nvim-R and open the issue again if it's not fixed.
