### ISSUE TITLE
Can't install nvimcom: permission denied

### ISSUE THREAD

**Issue by protist** [jalvesaq/Nvim-R#44]
I'm trying to create an Arch Linux `PKGBUILD` for `nvim-r`. I'm not sure if you are familiar with Arch packaging, but the pertinent lines are as follows.

    vim -c "UseVimball ${pkgdir}/usr/share/vim/vimfiles" -c q \
      "${srcdir}/Nvim-R.vmb"
    rm "${pkgdir}/usr/share/vim/vimfiles/.VimballRecord"
    rm "${pkgdir}/usr/share/vim/vimfiles/doc/tags"

Basically, this installs the vimball (downloaded from the Github `Releases` page) into `/usr/share/vim/vimfiles/` (with root permissions). However, when I open a `*.Rmd` file in `vim`, then start `R` with `<leader>rf`, I get the following error.
```
* installing to library ‘/home/protist/R/x86_64-pc-linux-gnu-library/3.2’
* installing *source* package ‘nvimcom’ ...
** libs
gcc -I/usr/include/R/ -DNDEBUG  -D_FORTIFY_SOURCE=2    -fpic  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong  -c nvimcom.c -o nvimcom.o
Assembler messages:
Fatal error: can't create nvimcom.o: Permission denied
/usr/lib64/R/etc/Makeconf:134: recipe for target 'nvimcom.o' failed
make: *** [nvimcom.o] Error 2
ERROR: compilation failed for package ‘nvimcom’
* removing ‘/home/protist/R/x86_64-pc-linux-gnu-library/3.2/nvimcom’
```
I don't quite understand how `nvimcom` is being installed, but is the error due to the original vimball being installed with root permissions? If so, would you suggest I fix the `PKGBUILD` to install `nvimcom` during the package installation, i.e. with root permissions and out of vim/R?

**Comment by jalvesaq** [comment]
I think it is better to split nvimcom installation in two steps:

  1. Build nvimcom_X.Y-Z.tar.gz in a writable directory.
  2. Install nvimcom_X.Y-Z.tar.gz

I'm going to commit a change that does this.

**Comment by jalvesaq** [comment]
Can you, please, confirm that it works now?

**Comment by protist** [comment]
Thank you for the quick response and fix! However, my Arch PKGBUILD was based around installing the package as a vimball. I'm not 100% sure how to install it from source. If you could explain how, then I'd be happy to test. Thank you again.

**Comment by jalvesaq** [comment]
If you type "make" in Nvim-R directory, the Nvim-R.vmb file will be created in the /tmp dir. Then, you can temporarily change you Arch PKGBUILD to use /tmp/Nvim-R.vim instead of the one downloaded from github. If it works, I will release a new version of Nvim-R.

**Comment by protist** [comment]
That didn't seem to work for me.
```
$ make
# Update the version date in doc/Nvim-R.txt header and in the news
sed -i -e "s/^Version: [0-9].[0-9].[0-9].[0-9]/Version: 0.9.2/" doc/Nvim-R.txt
sed -i -e "s/^0.9.2 (201[0-9]-[0-9][0-9]-[0-9][0-9])$/0.9.2 (`date +"%Y-%m-%d"`)/" doc/Nvim-R.txt
nvim -c "%MkVimball Nvim-R ." -c "q" list_for_vimball
/bin/sh: nvim: command not found
Makefile:12: recipe for target 'vimball' failed
make: *** [vimball] Error 127
```

**Comment by jalvesaq** [comment]
You don't have Neovim installed, but you can edit the Makefile and replace `nvim` with `vim`.

**Comment by protist** [comment]
Great! That seems to fix it. (Shouldn't nvim-r automatically work out whether to use `vim` or `nvim`?)

However, I get another error. The R session loads, but says `Error in library(vimcom) : there is no package called 'vimcom'`. Despite this, it seems to work fine.

**Comment by jalvesaq** [comment]
The `Makefile` is for developers only, and its main purpose is to build Nvim-R.vmb. It's not part of Nvim-R.vmb.

You should delete the line `library(vimcom)` from your .Rprofile because it's no longer used.

**Comment by jalvesaq** [comment]
I will fix the Makefile.

**Comment by protist** [comment]
> The Makefile is for developers only, and its main purpose is to build Nvim-R.vmb. It's not part of Nvim-R.vmb.

Okay, fair enough. That makes sense.

> I will fix the Makefile.

Please don't waste time on this if you feel it's unnecessary. I understand the rationale now.

> You should delete the line library(vimcom) from your .Rprofile because it's no longer used.

Oh yes, of course. Thanks for that. And thank you for the prompt help and attention again!

**Comment by jalvesaq** [comment]
When I told "will fix", in reality, I had already fixed it, but I will git-commit the change only later today when I will have time to release the new version.
Thanks for the feedback!

**Comment by protist** [comment]
Thank **you**! Also, just to let you know, (n)vim-r is a wonderous thing of beauty! Previously I'd been using R-studio, but oddly enough for a GUI, I found it quite fiddly and unintuitive at times. Since I've discovered (n)vim-r, I haven't looked back! It's simple and intuitive, and aligns perfectly with both R and vim. Thank you again!

**Comment by jalvesaq** [comment]
Thanks!

**Comment by jalvesaq** [comment]
Version 0.9.3 is released.

**Comment by protist** [comment]
Brilliant! Works perfectly, and I've uploaded the [PKGBUILD](https://aur.archlinux.org/packages/nvim-r/) to Arch's AUR.

Just a small question, I ran the PKGBUILD through Arch's namcap, which checks the package. It picked up on the following files:
```
/usr/share/vim/vimfiles/R/nvimcom/man/nvimcom-package.Rd
/usr/share/vim/vimfiles/R/nvimcom/man/nvim.print.Rd
/usr/share/vim/vimfiles/R/nvimcom/man/nvim.interlace.rmd.Rd
/usr/share/vim/vimfiles/R/nvimcom/man/nvim.srcdir.Rd
/usr/share/vim/vimfiles/R/nvimcom/man/nvim.plot.Rd
/usr/share/vim/vimfiles/R/nvimcom/man/etags2ctags.Rd
/usr/share/vim/vimfiles/R/nvimcom/man/nvim.interlace.rnoweb.Rd
/usr/share/vim/vimfiles/R/nvimcom/man/nvim.list.args.Rd
/usr/share/vim/vimfiles/R/nvimcom/man/nvim.interlace.rrst.Rd
/usr/share/vim/vimfiles/R/nvimcom/man/nvim.names.Rd
```
which it listed as "Potential non-FHS man page". They don't seem like man pages to me, so I just just curious as to what they were?

**Comment by jalvesaq** [comment]
They are the documentation of the nvimcom's functions visible to users, and they are converted into either man pages or html pages when you do in R `help("nvimcom-package")`, `help("nvim.print")` etc... They can also be converted into pdf.

**Comment by protist** [comment]
Ah excellent. These are working fine, so it looks like it's just namcap that is confused. Thanks again.

**Comment by jalvesaq** [comment]
If it is really important to avoid the warnings, Nvim-R could check if nvimcom_0.9-14.tar.gz exists before trying to build it, and your PKGBUILD would have to create nvimcom_0.9-14.tar.gz and delete the nvimcom directory.

**Comment by protist** [comment]
Interesting idea! However, I honestly wouldn't bother about it. namcap is fairly buggy at times, and these were just warnings. Also, namcap is only really used by the package author, and I'm happy enough to ignore it, since I know it's fine. Thanks again.
