### ISSUE TITLE
add math bloc syntax

### ISSUE THREAD

**Issue by olesendan** [jalvesaq/Nvim-R#440]
Hi Jalvesaq.

I'm writing a lot of math expressions in Rmd and R files.
When I'm using underscore(_) which subscripts in LaTex it interferes with the syntax.

to get around this behaviour I've scearched online and have found this workaround.

`" define a region that starts with $ or $$ and continues until the start pattern occurs again
syn region markdownLatexRegion matchgroup=markdownLatexBoundary start=/\z(\$\$\=\)/ end=/\z1/ keepend extend
" link the new syntax items to existing highlight colours
hi! link markdownLatexRegion Comment
hi! link markdownLatexBoundary Identifier`

from this answer
https://www.reddit.com/r/vim/comments/97vc8f/would_like_some_help_with_syntax_rules/

Would it be possible to implement something similar in nvim-r?

Greetings from Denmark
Dan Olesen

**Comment by jranke** [comment]
Hello Dan,

for Rmd files, you can use the vim-pandoc plugin with the vim-pandoc-syntax plugin which take care of this.

Johannes

**Comment by olesendan** [comment]
Hi Johannes

Thank you for your solution.

I've tried it, It does conseal more than I like in math blocks, Are you aware of a way to change this?
ex. $\dot{V}O_{2}max}$ conseals to \dot{V}O_max. Hopfully without changing the conseal for citations, which hides the zotero key

Greetings from Denmark
Dan

**Comment by jranke** [comment]
I don't know. But I know that I am using `let pandoc#syntax#conceal#use=0` in my `.vimrc`. Maybe there are more options you could try.

**Comment by olesendan** [comment]
Thank you jranke.

putting your suggestion in my vinrc does not seem to do anything. 

I will mess around a bit, to see if I can figure this out.

Dan
