### ISSUE TITLE
Run current file with command line arguments

### ISSUE THREAD

**Issue by ekiefl** [jalvesaq/Nvim-R#441]
Hello,

I really love this plug-in so thanks very much for putting all your effort and ingenuity into it. I have read `:help Nvim-R` (perhaps not thoroughly enough) and could not find out how I can run the current file, i.e. `\aa`, except with commandline arguments passed as well. For example, this script takes two arguments:

```
args = commandArgs(trailingOnly=TRUE)

file1 <- args[1]
file2 <- args[2]
```

How could I run this where I pass 2 filenames?

Thank you in advance.

Cheers,
Evan

**Comment by jalvesaq** [comment]
Nvim-R calls the function `nvimcom::source.and.clean()` which actually calls `source()`, and it doesn't seem to accept files as arguments other than the file to be sourced.

Maybe you could change your script to use environment variables, such as:

```r
file1 <- Sys.getenv("FILE_1")
file2 <- Sys.getenv("FILE_2")
```

Then you would run your script with a command like this:

```sh
FILE_1=/tmp/file_1.csv FILE_2=/tmp/file_2.csv Rscript myscript.R
```
And, while editing `myscript.R`, before typing `<LocalLeader>aa`, you would do in Neo(Vim):

```vim
:let $FILE_1 = "/tmp/file_1.csv"
:let $FILE_2 = "/tmp/file_2.csv"
```

**Comment by ekiefl** [comment]
This is a good workaround. Thanks.
