### ISSUE TITLE
Code completion in Python chunk not working

### ISSUE THREAD

**Issue by oli666** [jalvesaq/Nvim-R#442]
I am using 'ncm2/ncm2-jedi' to do completion for py files. This works perfectly well. I do not get completion to work though for python chunks within rmd files (The completion works for R chunks). 
Having temporarily switched from 'ncm2/ncm2-jedi' to 'davidhalter/jedi' had no effect either. 

I have tried after having disabled all plugins except the following: 

Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'
Plug 'gaalcaras/ncm-R'
Plug 'jalvesaq/Nvim-R'
Plug 'jalvesaq/R-Vim-runtime'
Plug 'ncm2/ncm2-bufword'
Plug 'ncm2/ncm2-path'
Plug 'w0rp/ale'
Plug 'ncm2/ncm2-ultisnips'
Plug 'ncm2/ncm2-jedi'

Syntax highlighting is working for both, R and Python within chunks. 
System: NVIM v0.5.0-dev on Ubuntu 18

**Comment by jalvesaq** [comment]
Perhaps you should report the issue to the developer of `ncm2-jedi` because I did nothing to make `ncm-R` deal with Rmd files. This is a feature native to ncm-R:

https://github.com/gaalcaras/ncm-R/blob/master/pythonx/ncm2_subscope_detector/rdocs.py

**Comment by oli666** [comment]
Reported as suggested
