### ISSUE TITLE
Start R in existing window

### ISSUE THREAD

**Issue by hhoeflin** [jalvesaq/Nvim-R#443]
Hi,

I was wondering if it is possible to start the R process in an existing window. Currently, R always opens a new window, which of course disrupts my window arrangement. Having the R process open in the current window that is active would be great. Same thing also for the object browser.

There is a workaround that I have been considering along the lines:
- Check number of windows
- StartR
- If number of windows has not changed, do nothing
- If number of windows has changed, go to previous window (the R window), close it, and open previous buffer (which is then the R buffer)

but this feels kind of hacky and I would like to load the R buffer in the current window in case it started already. For this I would need a reliable way to get the buffer number of the already started R process.

Thanks!

**Comment by jalvesaq** [comment]
Suppose that you are editing an R script. You press `<LocalLeader>rf`. The R script buffer is closed and now R is running at its place, and you can no longer see the R script. Is this what you want?

**Comment by hhoeflin** [comment]
As the <LocalLeader>rf is tied to bufferes with R-files, this is not quite the situation I was looking for. I was looking for a command ":StartRHere" that would 
-start the R session if it is not started
- put the R session buffer in the window if it is already running

Having this done with the LocalLeader would always require to first load an R-buffer into the window where you want the R session to be, which is ok but not super practical. And same for the object browser.

**Comment by jalvesaq** [comment]
Please, try the branch https://github.com/jalvesaq/Nvim-R/tree/nosplit and put in your init.vim:

```
let R_rconsole_width = 0
let R_rconsole_height = 0
command RStart let oldft=&ft | set ft=r | exe 'set ft='.oldft | let b:IsInRCode = function("DefaultIsInRCode") | normal <LocalLeader>rf
```
When both `R_rconsole_width` and `R_rconsole_height` have value zero, Nvim-R will not split the window before starting R. The terminal running R will replace the current buffer. So, to achieve what you want, you have to:

 - Split the window with the command `:belowright new` or any other command that creates a new buffer.
 - Issue the Normal mode command `:RStart`.

The tip for creating the `:RStart` command is already in Nvim-R's documentation.

**Comment by hhoeflin** [comment]
thanks for implementing the new branch so quickly.

I tried it and I have the following issue:
When I use the RStart command, the buffer that I was in when I was typing it gets closed. Instead, it should only be hidden.

**Comment by jalvesaq** [comment]
I call `termopen` to start R, and Neovim's documentation says:

> This function fails if the current buffer is modified (all buffer contents are destroyed).

I believe that most people prefer that Nvim-R splits the window for them because this means less work. Users have some control over the placement of R Console as explained in section _Control of R window_ of Nvim-R's documentation.

I can create a new option like `R_after_start` to allow users to define Vim commands to be executed after R is started.

**Comment by hhoeflin** [comment]
I see, thanks. I guess I could try and modify the RStart command above by adding an 'enew' before the other commands.

**Comment by jalvesaq** [comment]
Please, update the `nosplit` branch. I have modified the `R_after_start` and it now is a list of commands that might be a mix of Vim commands and external commands.
You don't need to set the values of either `R_rconsole_width` or `R_rconsole_height`. Please, put this in your init.vim:

```vim
let R_after_start = [':hide']
```

Does it work?

**Comment by hhoeflin** [comment]
Works - thank you! It now opens R at first in a separate window, but then hides the buffer R was originally initiated from, leading to the desired result!

Minor quibble: When I now do <LocalLeader> rf in a buffer with an r-script, and I do want it to open a separate window ... it doesn't. 

Thank you for the support.

**Comment by hhoeflin** [comment]
One other thing. The object browser window using <LocalLeader> ro still open in another window.

**Comment by jalvesaq** [comment]
> When I now do rf in a buffer with an r-script, and I do want it to open a separate window ... it doesn't.

You may map a key combination to set the value of `R_after_start` to `[]` and another to set the value of `R_after_start` to `[':hide']`. Something like:

```vim
nmap <F2> :let R_after_start = []<CR>
nmap <F3> :let R_after_start = [':hide']<CR>
```

**Comment by jalvesaq** [comment]
> One other thing. The object browser window using ro still open in another window.

I added the option `R_after_ob_open` to the `nosplit` branch. Please, look at the documentation.

**Comment by jalvesaq** [comment]
I undid the no-split-window change because it didn't solve the issue.

If you want to run two commands (change an option and start R) from a single shortcut, you have to put them in a function, as in the example that I presented at https://github.com/jalvesaq/Nvim-R/issues/444

**Comment by hhoeflin** [comment]
Thanks for letting me know. Did you undo all the changes or only some of them?

**Comment by jalvesaq** [comment]
I only undid the option of not splitting the window when both `R_rconsole_width` and `R_rconsole_height` were zero: https://github.com/jalvesaq/Nvim-R/commit/c4d7ea3d7240eacd4c668f776cfb0950eedb3d5d

**Comment by jalvesaq** [comment]
I'm going to merge the changes into the master branch and close this issue...
