### ISSUE TITLE
Is there a way to start R with arguments and without

### ISSUE THREAD

**Issue by statquant** [jalvesaq/Nvim-R#444]
Hello, I know about R_args but I’d like to be able to do something like \rv that would start R —vanilla and \rf normal R

**Comment by jalvesaq** [comment]
There is `<LocalLeader>rc` that allows you to choose the arguments before starting R. If you don't want to be asked about the arguments, you would have to create a function in your vimrc/init.vim:

```vim
function StartRWithArgs(argv)
  let g:R_args = a:argv
  call StartR("R")
endfunction

nmap <LocalLeader>sv :call StartRWithArgs(['--vanilla'])<CR>
nmap <LocalLeader>sf :call StartRWithArgs([])<CR>
```

**Comment by statquant** [comment]
many thanks
