### ISSUE TITLE
How can I redefine mappings

### ISSUE THREAD

**Issue by statquant** [jalvesaq/Nvim-R#446]
Hello I am trying to redefine `<LocalLeader>rv`, I tried `autocmd VimEnter,FileType r,rmd nnoremap <LocalLeader>rv :call StartR("R") <CR>` but without success, is it possible ?

**Comment by jalvesaq** [comment]
As explained in the section _Custom key bindings_ of Nvim-R's documentation, you should put in your vimrc something like:

```vim
nmap <LocalLeader>vd <Plug>RViewDF
```

**Comment by statquant** [comment]
thanks
