### ISSUE TITLE
Disable autocompletion

### ISSUE THREAD

**Issue by denismaciel** [jalvesaq/Nvim-R#447]
Hi, 

Thanks for this amazing plugin first of all. I am trying to use coc.vim for autocompletion and I would like disable Nvim-R's autocompletion completely. Is that possible at all?

**Comment by jalvesaq** [comment]
The omnicompletion provided by Nivm-r is triggered only when `<c-x><c-o>` is typed in Insert mode. Anyway, if you want to disable it you could put in your vimrc or init.vim:
 
```vim
autocmd FileType r setlocal omnifunc=
```

**Comment by denismaciel** [comment]
Thanks. Nvim-R had nothing to do with the problem I was having. It was another plugin interfering with coc.vim's completion. My bad.
