### ISSUE TITLE
How to run all chunks before the current chunk (\su doesn't work in R markdown files) ?

### ISSUE THREAD

**Issue by grepinsight** [jalvesaq/Nvim-R#448]
Hello! Thanks for making Nvim-R. It's a really awesome package for vim/R users, and since I have started using it, I haven't had to use Rstudio for a while since I am more productive in Nvim-R.

That said, I write a lot of R markdown files, and it seems that currently there is no `All lines above the current one \su` equivalent for Rmd files. 

Is there a function that I am missing?

**Comment by jalvesaq** [comment]
It's `<LocalLeader>ch`, meaning _send the chunks from the first one to here_. And the `<Plug>` name for creating a custom key binding is `RSendChunkFH`.

**Comment by grepinsight** [comment]
Thank you for your response @jalvesaq  and the answer! 
I missed that portion the doc.
