### ISSUE TITLE
How to prevent nvimcom to be loaded in a second "term" ?

### ISSUE THREAD

**Issue by grepinsight** [jalvesaq/Nvim-R#449]
## Setting

Let's say I have a `myfile.R` file and `R-session` open (via \rf).  
Let's say `myfile.R` is in `/path/to/myfile.R`. Then If I type the following in R, 

```
getwd()
"path/to"
```
I get `path/to` which  is expected.

## Problem

When I open an another buffer in vim and open a terminal using `:term` and in that terminal I am in `/different/path/`, I get the following error:

When I start an `R`, `nvimcom` is loaded(!) and `getwd()` returns `path/to` where `myfile.R` resides as opposed to `/different/path`.

## Question

How can I make it such that a separate terminal in vim has an environment isolated from the previous R session that's running?

**Comment by jalvesaq** [comment]
I can't replicate the issue. The command `getwd()` returns different paths if R is started from files that share the same name but are located at different directories.

**Comment by grepinsight** [comment]
Now I cannot replicate the issue either ;) Sorry!
