### ISSUE TITLE
Can't turn off R_assign

### ISSUE THREAD

**Issue by thejmazz** [jalvesaq/Nvim-R#45]
Have tried setting it inside and out of .vimrc, have tried changing R_assign_map as well. Mvim and I'm loading plugin with Vundle as `Plugin 'vim-scripts/Vim-R-plugin'`

**Comment by jalvesaq** [comment]
I have just tested, and `R_assign` works in both Vim and Neovim on Linux.

**Comment by thejmazz** [comment]
I'm on OSX. Hm, correct me if I'm wrong, but should

```
:echo $R_assign
```

print anything, if I have not assigned it in `.vimrc` or by command?

**Comment by jalvesaq** [comment]
The `$` prefix is for environment variables, but `R_assign` is a Vim's global variable. You should put in your vimrc:
```vim
let R_assign = 0
```
And you can check in Vim:
```vim
:echo R_assign
```
Please, in Normal mode Vim do:
```vim
:help R_assign
```

**Comment by thejmazz** [comment]
Oh, I didn't realize about the `$`.

Yes, I've done this before, but `a_` still turns into `a ->`:
![vim-r](https://cloud.githubusercontent.com/assets/1270998/13993679/b6bbafc2-f0f7-11e5-9676-0c1182289fee.gif)

**Comment by jalvesaq** [comment]
It looks like Nvim-R is not installed, but the animated gif is too fast and I don't know how to stop it. I couldn't see the vimrc carefully.

**Comment by jalvesaq** [comment]
The name of the plugin is `Nvim-R` now. See: https://github.com/jcfaria/Vim-R-plugin/issues/204

**Comment by jalvesaq** [comment]
Try this:

```
Plugin 'jalvesaq/Nvim-R'
```

**Comment by thejmazz** [comment]
Okay yeah, I guess it is b/c I was using `Vim-R`. I'll need to update my Vim as I'm on `7.4.1553` atm.

**Comment by freencis** [comment]
Just had this. Solved by clearing ~/.vim/views/ folder

**Comment by jalvesaq** [comment]
In `lazy.nvim`, `init` is run before `config` and should be used for Vim plugins that rely on global variables:

```lua
{
    'jalvesaq/Nvim-R',
    lazy = false,
    init = function()
      vim.g.R_assign = 0
    end
  }
```

Specifically for `R_assign`, `config` should also work because I included a workaround in Nvim-R.

Please, see also: https://github.com/jalvesaq/Nvim-R/discussions

**Comment by jsr-p** [comment]
I see, thank you; config also worked, but I'll use the stricter one :smile:
