### ISSUE TITLE
Opening files that do not have the default extension

### ISSUE THREAD

**Issue by rpietro** [jalvesaq/Nvim-R#453]
@jalvesaq Jakson, while most of my files are in Rmd or R, sometimes I will need to run nvim-r (which, btw, is an **awesome** plugin) in .md and .wiki (for vimwiki) files. I went through the documentation and found the following line of code, and inserted it to my init.vim:

`command RStart let oldft=&ft | set ft=r | exe 'set ft='.oldft | let b:IsInRCode = function("DefaultIsInRCode") | normal <LocalLeader>rf`

I sourced init.vim, but it doesn't work, meaning that Nvim-r does not activate after <lead>rf. I installed  Nvim-R through Plug on Manjaro, running nvim v0.4.3 from an Xfce terminal with tmux. I tried with and without tmux and it doesn't work either way. I have installed all required packages listed in the documentation. Nvim-r currently works perfectly with .R and .Rmd extensions.

I would appreciate any help, right now I don't even know where to start debugging it.

**Comment by jalvesaq** [comment]
@rpietro I have just tried the `:RStart` command with a `txt` file and it worked fine (Ubuntu 19.10). I don't know what might be going wrong in your system.

The `init.vim` script is sourced automatically by Neovim as part of its startup process. So, you shouldn't have to source it manually.

Because Nvim-R is a filetype plugin, and because its commands and shortcuts are not undone when the file type is changed, when we do the command `ft=r`, all of Nvim-R functionality becomes available for the buffer, even after the command that restores the original file type.

**Comment by rpietro** [comment]
It's strange indeed. I haven't found the solution yet, but this is what I tried so far:

1. To discard the possibility of a conflict with an nvim plugin or any other init.vim configuration, I just cleared my entire init.vim, leaving only Nvim-R and the script that should allow me to run it with any file. I then ran PluginInstall to make sure no other plugins were left, and then opened an .R file. Ran perfectly. Opened a .txt file and nothing.
2. I did the same thing with .zshrc, ran with a clean file to avoid conflicts with oh-my-zsh plugins, but to no avail

I then noticed that the <leader> is not even being recognized as a leader in files other than .R and .Rmd. I know that because when I press r it gets in replace mode. My detective work in relation to the leader key went like this:

3. I haven't remapped the leader (I checked and it is the default \), 
4. even when I remapped it to "," it still doesn't work. 
5. It's also not a leader timeout issue, I tried it with multiple variations of time and it got me nowhere. 

The weird thing is that the leader works with other packages. For example, in vimwiki \wr will allow me to rename the file I am in, and it works like a charm.   

Last thing I tried was to get in a txt file and manually set its syntax to R. I then checked to make sure that it had taken my command, which it did, and I tried to open nvim-r. Nothing

So, I am not really sure where else to investigate. This doesn't seem to be an Nvim-R issue and so maybe this issue should be closed. If I can get to a solution at some point I will report it here in case somebody might have the same problem.

**Comment by jalvesaq** [comment]
> Last thing I tried was to get in a txt file and manually set its syntax to R. I then checked to make sure that it had taken my command, which it did, and I tried to open nvim-r. Nothing

Setting the syntax to R will only change the highlighting. It's necessary to change the file type:
```vim
: set filetype=r
```

**Comment by rpietro** [comment]
@jalvesaq you are the man, that solved my problem. thank you so much.
