### ISSUE TITLE
.Rnw files not recognised by nvim-R

### ISSUE THREAD

**Issue by PierceMc** [jalvesaq/Nvim-R#455]
Hello,

On my laptop, the plugin doesn't start when opening a file with .Rnw as a filetype. It works for .R, but nothing for .Rnw. 

Is there a way to explicitly tell nvim to load the plugin when opening .Rnw files? Or is this an issue that is known?

**Comment by jalvesaq** [comment]
It works with Rnoweb files. When a file with `.Rnw` extension is opened, the filetype should be `rnoweb`. What is the output of the command below?

```vim
:set ft?
```

**Comment by PierceMc** [comment]
the output of `:set ft` is `filetype=rnoweb`. But `\rf` does nothing in the file.

**Comment by statquant** [comment]
You need to set the ft
`autocmd BufRead,BufNewFile *.Rnw set filetype=r`
Then all will be like it was a R file

**Comment by jalvesaq** [comment]
Files with the `.Rnw` extension should be automatically recognized by either Vim or Neovim as `rnoweb`. If you set them as `r`, then Nvim-R's functionalities specific to rnoweb files will not be available, such as compiling the PDF, opening the PDF, SyncTeX, sending the chunk where the cursor is in etc...

**Comment by PierceMc** [comment]
Are there any cases where the .Rnw extension would not be recognised as such? Or is there a way to tell nvim explicitly that I want to load Nvim-R functionality?

**Comment by jalvesaq** [comment]
It looks like that either Nvim-R is not properly installed or another plugin is taking over as the file type plugin for files with the `.Rnw` extension. If you couldn't find the problem just looking at your vimrc/init.vim, you could try replacing it with an almost empty one (with just Nvim-R installed) and, gradually, put back the lines of the original vimrc/init.vim, restarting Vim/Neovim and R after each addition.
