### ISSUE TITLE
Nvim-R works no more  (Windows 10)

### ISSUE THREAD

**Issue by Dulohan** [jalvesaq/Nvim-R#456]
I was using Nvim-R 0.9.10 under Windows 10 together with vim 8.1 and R 3.4.0. For some reason, I had to recompile Nvim-R. 
I did compilation by hand, as I had to manually adapt  already during the first installation the "BINPREF" variable pointing to the gcc compiler. 
Compilation did not produce any error messages. 
Nevertheless, when I open an R file, \rf does not work and there is also no "R" dropdown menu generated. 
In the C:\Users\Myname\AppData\Roaming\Nvim-R folder, there is no nvimcom_info File generated. 
I also tried R-3.6.1 and Nvim-R 3.9.13 which didn't work either. 

Thank's in advance for any reply!

**Comment by jalvesaq** [comment]
I no longer have access to a Windows machine with R installed, but the issue that you described doesn't look like a Windows specific problem.

Perhaps Nvim-R is not properly installed: you should get at least an error message after \rf, and the R menu should be visible. Please, try the procedures described in section 3.3 (Troubleshooting) of Nvim-R's documentation.

**Comment by blayz3r** [comment]
Nvim-R works with Windows 10 vim 8.2

**Comment by Dulohan** [comment]
Thank you very much for your answers!
The following variables are set in my _vimrc: 
let R_path = "C:\\Programme_2\\MyR\\R\\R-3.4.0\\bin\\x64"
let R_cmd = "C:\\Programme_2\\MyR\\R\\R-3.4.0\\bin\\x64\\Rgui.exe"
let Rtools_path = "C:\\Programme_2\\Rtools"
let R_set_home_env = 0
let R_assign = 0
let R_in_buffer = 0
With these settings, nvimR worked well previously. 

I tried now also to install R via the vimball in which I inserted again the BINPREF in 

#CC?=gcc
ifeq "$(WIN)" "64"
	BINPREF ?= c:/Programme_2/Rtools/mingw_64/bin/
    CFLAGS+=-m64 -mwindows -std=gnu99 -O3 -Wall -DWIN32
else
	BINPREF ?= c:/Programme_2/Rtools/mingw_32/bin/
    CFLAGS+=-m32 -mwindows -std=gnu99 -O3 -Wall -DWIN32

CC = $(BINPREF)gcc 

Now, during the compilation, there appear some error messages, here the first one:  

wrote C:\Programme_2\vim\vimfiles/R/nvimcom/src/apps/Makefile.win
extracted <>: 0 lines
extracted <>: 0 lines
extracted <714>: 0 lines
extracted <#include <stdlib.h>>: 0 lines
extracted <#include <ctype.h>>: 0 lines
extracted <#include <sys/types.h>>: 0 lines
Fehler beim Ausführen von "function vimball#Vimball":
(Error executing ...)
Zeile  113:
E739: Kann Verzeichnis nicht erstellen: C:/Programme_2/vim/vimfiles/#include <sys   
(can't create directory:)

i.e, for some reason, during installation it tries to write commands to the folder C:/Programme_2/vim/vimfiles/ instead of executing them .           
At the end of installation, the folder contains some spurious folders, like "    hints.ai_family = AF_INET;" 

Nevertheless, after finalization, I can start R from within vim, and also get the R dropdown menu. 
However, there appear some error messages
starting with: 
Warning: unknown option -f 
and also the rest of the command is not recognized
C:\WINDOWS\system32\cmd.exe /c (C:\Programme_2\MyR\R\R-3.4.0\bin\x64\Rgui.exe --no-restore --no-save --slave -f ^"C:/Users/myname/AppData/Local/Temp/NvimR-myname/nvimcom_path.R^" ^>C:\Users\myname\AppData\Local\Temp\VIoCDC.tmp 2^>^&1)

Hence the program doesn't work.

**Comment by Dulohan** [comment]
Ok, the -f option does not exist for  Rgui, so I have to change 
let R_cmd = "C:\Programme_2\MyR\R\R-3.4.0\bin\x64\Rgui.exe"
to
let R_cmd = "C:\Programme_2\MyR\R\R-3.4.0\bin\x64\R.exe"
But now I get 
"Fatal error: cannot open file ' ': Inalid argument ^@^@

**Comment by jalvesaq** [comment]
You could try setting the `PATH` environment variable in your vimrc instead of editing the Makefile.win and, since, you would be editing the `PATH` you could add the R path to it:

```vim
let $PATH = "c:\\Programme_2\\Rtools\\mingw_32\\bin;C:\\Programme_2\\MyR\\R\\R-3.4.0\\bin\\x64;" . $PATH
```

As I said, I don't have access to Wndows but, perhaps, with the above line in your vimrc you would not need to configure `R_app`, `R_cmd`, `R_path`.

Note that you have to use either forward slashes between double quotes or backward slashes between single quotes.

**Comment by jalvesaq** [comment]
Please, update the plugin, upgrade R for version 4.0.0, upgrade Rtools, delete any definition of `R_app`, `R_cmd` or `R_path` from your vimrc and put this in your vimrc:

```
let $PATH = "c:\\rtools40\\usr\\bin;c:\\rtools40\\mingw64\\bin;" . $PATH
```

I still don't have access to a real machine running Windows, but it worked on this virtual machine: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
