### ISSUE TITLE
Question: how can I redefine a RAction

### ISSUE THREAD

**Issue by statquant** [jalvesaq/Nvim-R#457]
Most of the shortcuts \r* are already taken and some of I never use.
How can I redefine a RAction for instance nmap <silent> <LocalLeader>rd :call RAction("debugonce")<CR> ?

**Comment by jalvesaq** [comment]
Please, look at section 7 of Nvim-R documentation, _Custom key bindings_. If the documentation is not clear, please, comment here and I will try to improve it.

**Comment by statquant** [comment]
Hello, I red it and I am not sure it answers might question
Clearly defining the bellow works perfectly

> nmap <silent> <LocalLeader>dg :call RAction("debugonce")<CR>

But I want to use another binding that is already defined and that's where I can't make it
The bellow for me does not redefine what is already defined (a setwd command)

> nmap <silent> <LocalLeader>rd :call RAction("debugonce")<CR>

Sorry to be missing the obvious here

**Comment by jalvesaq** [comment]
It's not obvious. You would have to change the shortcut for `setwd` to something that would not cause trouble:

```
nmap <silent> <LocalLeader>TT <Plug>RSetwd
nmap <silent> <LocalLeader>rd :call RAction("debugonce")<CR>
```

But perhaps I should add an option to disable unwanted commands.

**Comment by jalvesaq** [comment]
I'm going to add a new option: `R_disable_cmds`. Then you will be able to disable the shortcuts that you never use.

**Comment by statquant** [comment]
That's great, thanks
