### ISSUE TITLE
How to autospace from both sides of "<-"?

### ISSUE THREAD

**Issue by DadongZ** [jalvesaq/Nvim-R#459]
Thanks for your nice plugin. 
I am wondering whether there is a way to automatically add spaces when I am typing "<-" which seems making script looks more elegant. such as
`x <- rnorm(100)` rather than `x<-rnorm(100)`.

**Comment by jalvesaq** [comment]
By default, when "_" is inserted it is converted into " <- ". Please, see Nvim-R's documentation:
```
:h Nvim-R-use
:h R_assign
```
