### ISSUE TITLE
adapt start options for R

### ISSUE THREAD

**Issue by winmos** [jalvesaq/Nvim-R#460]
Hi,

I am aware, that I can change the R startoptions with `let R_args`.
But what if i want to start R from within vim-R like this: `xvfb-run R --no-save`

Is there a possibility to tell nvim-r to start R like this?

[https://stackoverflow.com/questions/1710853/how-to-run-r-on-a-server-without-x11-and-avoid-broken-dependencies](url)

Thanks for help!
Winfried

**Comment by jalvesaq** [comment]
You could try something like:

```
let R_cmd = '/usr/bin/xvfb-run'
let R_args = ['R', '--no-save']
```

**Comment by jalvesaq** [comment]
I've noted that I already have `xvfb-run` installed and I could try it. What works for me is:

```
let R_cmd = '/usr/bin/xvfb-run R'
let R_app = '/usr/bin/xvfb-run R'
let R_args = ['--no-save']
```

I get the warning at Neovim startup:
> R executable not found: '/usr/bin/xvfb-run R'

But it works.

**Comment by winmos** [comment]
Yes, it works also for me! 
This gives me the possibility to run R on a headless server and still use `dev.print()`
Great, thank you!
