### ISSUE TITLE
Requested info about python alternatives

### ISSUE THREAD

**Issue by ekiefl** [jalvesaq/Nvim-R#461]
Not quite sure if this belongs here, apologies if it doesn't. I love this project so much, it actually made me _want_ to code in R. I wish there was something this good for python, but I can't find anything. Does anyone have suggestions?

EDIT: https://github.com/jalvesaq/vimcmdline

**Comment by jalvesaq** [comment]
When editing Python code, in addition to vimcmdline, I also use [jedi](https://github.com/davidhalter/jedi), [ncm2](https://github.com/ncm2/ncm2), and [ncm2-jedi](https://github.com/ncm2/ncm2-jedi).

**Comment by matsburg** [comment]
I have a question related to this. Do you have any ideas on how to implement something like `RViewDF` for Python using vimcmdline? I've tried a function which sends a command like `df.to_csv("file/path.csv")` to the REPL, then starts a while loop to check if the csv file exists, and opens it once it does exist, but I couldn't get it to work (vim gets stuck in the while loop even after the csv file has been created).

**Comment by jalvesaq** [comment]
When Nvim-R was still called Vim-R-plugin, it used to use loops. The pseudo algorithm of these loops was somewhat like:

```vim
call MessageToR("create_a_file")
let ii = 0
while ii < 10
    sleep 500m
    ii += 1
    if filereadable("the_file")
        sleep 300m " The file creation might not be finished yet.
        call DoSomethingWithTheFile("the_file")
        break
    endif
endwhile
```

**Comment by matsburg** [comment]
Thanks, that works well for me.
