### ISSUE TITLE
Nvim R not detecting python code chunk when combined with vim-rmarkdown

### ISSUE THREAD

**Issue by mumblingdrunkard** [jalvesaq/Nvim-R#462]
I have a file that contains some python code. When I disable the vim-rmarkdown plugin along with vim-pandoc and vim-pandoc-syntax I can send python to the R-session without issue via reticulate.

I do not get latex highlighting when this is done so I'd like to be able to use the pandoc-plugins. When the other plugins are enabled, I can still send lines of R-code to the session, but the lines of python get sent as if they were R.

It seems the block-detection fails altogether when vim-pandoc vim-pandoc-syntax and vim-rmarkdown are enabled as I can send lines that are outside a block as well.

EDIT: After some more experimentation it seems these two plugins really don't want to play nice.
I have disabled vim-rmarkdown and can now send code correctly, but now python is not highlighted the way I want.

EDIT2: Further experimentation reveals:
Nvim-R will only detect the block when a lowercase r is used. It also won't allow pandoc to fold the three backticks into a lambda. If the lowercase r is made uppercase the folding can happen, but Nvim-R will not detect it as an R-block. This is not the case for python where both folding of the three backticks happens and the block is correctly detected as python. I really don't get this, this is weird.

EDIT3: [Wrong]

EDIT4: If I disable the R-Vim-runtime then syntax highlighting works correctly for both R and python, but I can not send python to the session correctly. If I enable it, I can send python correctly but python is not highlighted. the backticks before an r-block are not replaced with a lambda either.

EDIT5: Further developments
When using \cc to send a chunk it works just fine, even for python, but \bb only works for R blocks when the R-Vim-runtime is disabled.

**Comment by Hackzen** [comment]
After some more experimentation it seems these two plugins really don't want to play nice.
I have disabled vim-rmarkdown and can now send code correctly, but now python is not highlighted the way I want.

**Comment by jalvesaq** [comment]
I'm sorry for the long delay.

Only now I looked at vim-rmarkdown's README. I could see that it is part of vim-pandoc and that it allows the compilation of RMarkdown documents. This is the same thing that Nvim-R does. So, I guess you don't need both Nvim-R and vim-rmarkdown. You could choose between one of them.
