### ISSUE TITLE
Nvim-R-remote

### ISSUE THREAD

**Issue by winmos** [jalvesaq/Nvim-R#463]
Dear All,

I tried to setup remote access of my Nvim-R to an ec2 instance (described in the Nvim-R help under Nvim-R-remote).

I think i got the steps right, but when I try to start R on the remote machine from within my local vim instance, I get the following message:

> Pseudo-terminal will not be allocated because stdin is not a terminal. ^M^@Fatal error: cannot open file  '/home/winfried/.remoteR/NvimR_cache/tmp/nvimcom_path.R': No such file or directory^@

Can someone point me in a direction?

Thank you!

Winfried

**Comment by winmos** [comment]
I found a solution to the pseudo-terminal problem:
set the flag -T (not -t) in sshR
for explanation see:
https://stackoverflow.com/questions/7114990/pseudo-terminal-will-not-be-allocated-because-stdin-is-not-a-terminal

but the fatal error still persists...

**Comment by winmos** [comment]
I found a solution to the pseudo-terminal problem:
set the flag -T (not -t) in sshR
for explanation see:
https://stackoverflow.com/questions/7114990/pseudo-terminal-will-not-be-allocated-because-stdin-is-not-a-terminal

but the fatal error still persists...

**Comment by m3hdad** [comment]
I have the same problem here, it would be great if someone could help us understand,
my permissions for nvimcom_path.R is 644

NvimR is great, THANKS in advance

**Comment by jalvesaq** [comment]
If I could, I would improve the section "Nvim-R-remote" of the documentation despite never needing to access R at another machine. Unfortunately, I don't have time for this. So, it would be great if someone could check if the documentation is clear, accurate and up to date, and submit a pull request improving it, if necessary.

**Comment by jalvesaq** [comment]
Please, try the branch https://github.com/jalvesaq/Nvim-R/tree/remote if this issue still is relevant to you...
