### ISSUE TITLE
Have a more specific tab name when using pager instead of R_doc

### ISSUE THREAD

**Issue by strboul** [jalvesaq/Nvim-R#464]
I use *R*'s built-in pager option to view objects, data.frames etc., an example is below.

```r
utils::page(mtcars, method = "print")
```

When I call this in the _Nvim-R_ terminal, it creates a new tab with the name of `R_doc`. It'd be nice if it opens a new tab with the same name as the invoked call for these types of situations. Even further: it'd be much better if we can have a tab name same as the call name opened with the `\rh` command or `?` in the *Nvim-R* terminal.

I have these options in my `init.vim`:

```vim
let R_assign = 0
let R_nvim_wd = 1
let R_nvimpager = "tab"
if executable("radian")
  let R_app = "radian"
  let R_cmd = "R"
  let R_hl_term = 0
  let R_args = []
  let R_bracketed_paste = 1
endif
```

Thanks a lot for the great work and the great plugin!

**Comment by jalvesaq** [comment]
I didn't know that we could do this. If you type in Vim/Neovim `:set filetype?` you will see that the file type is `rdoc`. The reason is that I only expected to use Vim as pager for R documentation. I even created a function to display data.frames. Try, for example:

```r
nvimcom:::nvim_viewdf(mtcars)
```

**Comment by jalvesaq** [comment]
>  It'd be nice if it opens a new tab with the same name as the invoked call for these types of situations.

What to do if there is already a buffer with the name of the object?
If the object is a function, shouldn't the filetype of the buffer be set as R to get proper syntax highlighting?
If the object is either a data.frame or matrix, shouldn't the filetype of the buffer be set as csv?

Maybe I should generalize the command called by `<LocalLeader>rv` to work with any type of object.

**Comment by strboul** [comment]
> nvimcom:::nvim_viewdf(mtcars)

I like this and it's probably better than using the pager; however, it still does poor formatting, at least on my machine. And I am not a big fan of `csv.vim` plugin.

<img width="357" alt="Screenshot 2020-02-22 at 17 33 27" src="https://user-images.githubusercontent.com/25015317/75095838-7769c880-5599-11ea-8b61-4d0c74bc3c79.png">

> What to do if there is already a buffer with the name of the object?

I'd just jump into that buffer. If users want to reload, they should delete the buffer and do a re-call. If this is done, it should be an option in the plugin.

I see that you've posed good questions but I don't have much idea about them.

**Comment by jalvesaq** [comment]
If you want the documentation of different R objects in their own tab, named after the object, please, put in your init.vim/vimrc:

```vim
let R_nvimpager = "tabnew"
```

**Comment by jalvesaq** [comment]
I have just found Visidata which seems to be the best option for visualizing data.frames and matrices. Now, I have the following in my init.vim:

```vim
let R_csv_app = 'tmux new-window vd'
```

Please, update Nvim-R if you want to try Visidata.

**Comment by strboul** [comment]
> I have just found Visidata which seems to be the best option for visualizing data.frames and matrices. Now, I have the following in my init.vim:
> 
> ```viml
> let R_csv_app = 'tmux new-window vd'
> ```
> 
> Please, update Nvim-R if you want to try Visidata.

Visidata looks very nice! However, I observed two quirks with the Nvim-R after I added this option to my `init.vim` file:
1. If Visidata isn't installed in the system, the command `\rv` doesn't return/inform about anything. A helpful message in the command line would be helpful (if possible).
2. The tsv files are saved into the current directory. Would it be better if they are destored after quitting from the table viewer? They can be better in the temp directory as well.

**Comment by jalvesaq** [comment]
> Visidata looks very nice! However, I observed two quirks with the Nvim-R after I added this option to my init.vim file:

I have fixed both issues on the branch [dput_obj](https://github.com/jalvesaq/Nvim-R/tree/dput_obj). On this branch, `\rv` works with all types of R objects, calling `dput()` if the object is neither a data.frame nor a matrix.

**Comment by jalvesaq** [comment]
I have just merged the `dput_obj` branch into the master branch and deleted the `dput_obj` branch.

**Comment by jalvesaq** [comment]
I improved the name of pager buffers. Now, they will include the "(help)" string only when a buffer is actually displaying an R help document. The filetype of the buffer will be set to `rdoc` only when it is an R help document. I also added this to Nvim-R' documentation:

> Unless the value of `R_nvimpager` is "tabnew", the buffer name will always be "R_doc" to force the reuse of the window when users jump from one help page to another.

**Comment by inventionate** [comment]
> The tsv files are saved into the current directory. Would it be better if they are destored after quitting from the table viewer? They can be better in the temp directory as well.

Maybe I'm doing something wrong, but for me the tsv files are still saved in the working directory and not deleted after quit. Do I have to configure something explicitly?

**Comment by jalvesaq** [comment]
Is the value of `R_nvimpager` "tabnew"?

**Comment by inventionate** [comment]
No, the value was vertical. I have now changed it, but the problem still exists. When I display a data.frame with \rv, a :terminal window opens and I can view the data.frame with visidata. I then close the terminal window and continue working. Unfortunately, even after closing Neovim, the object is in the file directory as a TSV file, which was probably created when I first opened it.

**Comment by jalvesaq** [comment]
According to the documentation, the name will be different from `R_doc` only if the value of R_nvimpager is "tabnew".

**Comment by inventionate** [comment]
Thank you and yes, that is clear. Perhaps I have also not expressed myself clearly. It's about the fact that a tsv file is created, which should not be. The name doesn't really matter, it's about the file itself.

**Comment by jalvesaq** [comment]
The tsv file is deleted when you finish (quit) Vim. The is the meaning of line 1546 of R/common_global.vim:
```
    call AddForDeletion(tsvnm)
```

**Comment by inventionate** [comment]
Yes, that's how I understood it in the documentation. Unfortunately, it is not true (at least for me). The file is not deleted when I quit Vim.

**Comment by inventionate** [comment]
And if I understand the code correctly, the file should be in the tmp directory. But in my case it is created in the working directory and as I said it stays there even after closing Vim.

**Comment by inventionate** [comment]
It seems to me that the copy operation is the problem (line 1552 in common_global.R). The tmp file is deleted, but not the one copied to the working directory. For example, if I add `call AddForDeletion(a:oname . '.tsv')` right after, the file is copied and it is in the working directory. However, as soon as I then close Vim, it is also successfully deleted. Am I possibly missing something or is this an acceptable fix?


Translated with www.DeepL.com/Translator (free version)

**Comment by jalvesaq** [comment]
I think it's better not to copy the file to the working directory at all.

**Comment by jalvesaq** [comment]
It should be OK now.

**Comment by inventionate** [comment]
Great! Thank you very much for your quick fix and yes, I absolutely agree that not to copy at all is the better way to go.
