### ISSUE TITLE
Synchroneous autocompletion for R using tab

### ISSUE THREAD

**Issue by statquant** [jalvesaq/Nvim-R#466]
Hello, I use the Nvim-R fall the time and it's amazing but I miss some autocompletion a bit. 
I know about https://github.com/gaalcaras/ncm-R that is refered in https://github.com/jalvesaq/Nvim-R/issues/175 but I find it to work poorly with vim8. I think anyway that I do not need async autocompletion for vim. What I do not like is 

- to have to hit <C-x><C-o> for function completion 
- have to cycle wit <C-n> or <C-p> to complete my function name 
- have to hit <C-x><C-a> for arguments then

I'd like to be able to in do the following in insert mode
 
- when I hit <tab> in insert mode get function complete 
- be able to cycle suggestion with <tab> and <S-tab> 
- once I have selected and opened (get arg competion with tab again)

I am aware of http://stackoverflow.com/questions/2269005/how-can-i-change-the-keybinding-used-to-autocomplete-in-vim that you refer to in section 9.6 but that does not really says much.
I am asking you as maybe you might be doing something similar

**Comment by jalvesaq** [comment]
ncm-R works well in Neovim, and I no longer use Vim. Unfortunately, I no longer have spare time to add many new features to Nvim-R.

**Comment by statquant** [comment]
I got deoplete + languageserver to work very well with the help of @ErickChiron, should I write a paragraph and PR it to you in the docs ?

**Comment by jalvesaq** [comment]
> I got deoplete + languageserver to work very well with the help of @ErickChiron, should I write a paragraph and PR it to you in the docs ?

Yes, please.
