### ISSUE TITLE
Nvim-R inside Docker: Updating nvimcom... 

### ISSUE THREAD

**Issue by ErickChacon** [jalvesaq/Nvim-R#467]
I use Nvim-R inside a docker container. It works great, but the only problem is that the message "Updating nvimcom ..." appears everytime when I restart the container. After some tests, I can see that the problem is because the file `.../nvimcom_info` is not being written when building the docker image. I was wondering if I can use **command lines only** to ensure that this file is being written.

My set-up ,after a clean installation of neovim,  is as follows. First, I install a plugin manager:
```
# vim plugin manager
ARG vimplug_v="518a356"
RUN curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/${vimplug_v}/plug.vim
```

Later, I install the plugins.
```
# install plugins for neovim
RUN nvim --headless +PlugInstall +UpdateRemotePlugins +qall > /dev/null
```

Finally, I try to use Nvim-r from the terminal to update the required files, so it does not need updating after I start the container.
```
# initiallize nvim-r for .cache folder
RUN mkdir .cache && \
  nvim --headless test.R '+call StartR("R")' +qall
```

This last line reduces the time that the updating will take when initializing the container, but nvimcom is still updated because `.../nvimcom_info` is not being created. It would be great if I can run a similar command to the last line that ensures creating `.../nvimcom_info`.

Please, ignore RUN and ARG if you do not use docker.

**Comment by jalvesaq** [comment]
Is this comment helpful: https://github.com/jalvesaq/Nvim-R/issues/570#issuecomment-826013702 ?
