### ISSUE TITLE
R 3.6.3 support

### ISSUE THREAD

**Issue by inventionate** [jalvesaq/Nvim-R#469]
Unfortunately the plugin no longer works with the current R version 3.6.3. I get, after R is started in a Neovim buffer, the following error message:

```
Error detected while processing function ROnJobStdout:
line 7:
E115: Missing quote: '3.6.3^B.^B
```

Can you help me, please? Thank you in advance!

I'm using macOS 10.15.3, Neovim 0.4.3 and the latest version of your great plugin.

**Comment by StefanBRas** [comment]
It still works for me on Ubuntu (18.04.4 LTS) with Neovim version 0.4.3 and Nvim-r version 0.9.13.1.

Maybe something is handled differently on macOS when Nvim-r extracts R's version number. You could try to run

`
:echo substitute(system("R --version"), '.*R version \(\S\{-}\) .*', '\1','')
`

in Neovim, which should output `3.6.3`.

**Comment by inventionate** [comment]
Many thanks for the answer.

The command also outputs `3.6.3` for me. 

Any other ideas?

**Comment by StefanBRas** [comment]
Not really, i'm not that familiar with Vim script. Does

`
:echo len(substitute(system("R --version"), '.*R version \(\S\{-}\) .*', '\1',''))
`

show 5? Maybe it includes some whitespace character or espace sequences which isn't shown with `echo`.

**Comment by inventionate** [comment]
Yes, it's showing 5.

Unfortunately I don't know anything about Vimscript either. Whitespace characters or espace sequences sounds likely. Maybe I'll come up with another idea to find the error.

Anyway, thanks for the help!

**Comment by inventionate** [comment]
OK, I found the problem. It is related to my .Rprofile file, which I recently modified. Apparently nvim-r does not support the prompt package.

Thank you again. I close this issue for now.

**Comment by jalvesaq** [comment]
Please, update Nvim-R. I replaced the bug with a less important one. Now, if the prompt includes a newline character, it will not be correctly highlighted in the ouput of `<LocalLeader>ao`.

**Comment by inventionate** [comment]
Many thanks! Now everything works wonderfully.
