### ISSUE TITLE
R_vsplit=1 results in jumbled panes

### ISSUE THREAD

**Issue by ajkal** [jalvesaq/Nvim-R#47]
I am running vim with Nvim-R and I have encountered a problem with the vertical split option. When I initiate R and then switch to the R pane (i.e. with <Ctrl-a>-o), the lines in R seem to bleed over into my vim Rscript pane. It is purely an aesthetic thing, and when I switch back to the vim Rscript pane and move the cursor over those lines, they clear up. When I switch back, however, the bleedover reoccurs. The following screenshot should illustrate the issue. This does not happen when the panes are split horizontally.

![screenshot from 2016-03-22 17 25 12](https://cloud.githubusercontent.com/assets/8230490/13991895/2e643394-f0f0-11e5-835c-d340d57b09bc.png)

**Comment by jalvesaq** [comment]
I have never seen this before, but it looks like a Tmux bug.

**Comment by jalvesaq** [comment]
It may also be a problem with the way the plugin configures tmux. It may not work on Mac OS X. The configuration is done in lines 7-17 of R/extern_term.vim.

I'm sorry, but we have to wait until someone who has access to a Mac fix the bug.

**Comment by jalvesaq** [comment]
Are you using Linux? Anyway, please, see:
```
:h R_notmuxconf
```

**Comment by jalvesaq** [comment]
R/extern_term.vim is unrelated with the problem. I was confused by other issues reported on the same day. Could you please post here your `~/.tmux.conf`?

**Comment by jalvesaq** [comment]
@ajkal Do you still see this bug? Did you discover what was causing the problem?

**Comment by ajkal** [comment]
Hi Jakson,

I still haven't figured out the issue. I'm using an HPC cluster running
CentOS. Since I don't have root access I'm using local installations of vim
and Nvim-R. I realize this can complicate things.

-Andrew

On Sat, May 21, 2016 at 4:41 PM, Jakson Alves de Aquino <
notifications@github.com> wrote:

> @ajkal <https://github.com/ajkal> Do you still see this bug? Did you
> discover what was causing the problem?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jalvesaq/Nvim-R/issues/47#issuecomment-220799232>
>



-- 
Andrew Kalenkiewicz
Cellular & Molecular Biology B.S.
University of Michigan, Ann Arbor
734-709-0355
ajkal@umich.edu

**Comment by jalvesaq** [comment]
Thanks for the feedback! Unfortunately, I can't reproduce the bug and I don't know how to fix it. If you could try Neovim, it could be the solution because it does not depend on Tmux to run R.

**Comment by edwmurph** [comment]
Any update on this?

I can't get \rf to open in a split session in iterm2. I'm on a Mac osx 10.13. I've tried all of the following vimrc configs but none of them work:

let R_routnotab = 1
let R_vsplit=1
let R_tmux_split = 1

**Comment by jalvesaq** [comment]
@edwmurph, what is your version of Vim? The option `R_vsplit` no longer exists and, by default, R will start in Vim's built-in terminal emulator unless you put `let R_in_buffer = 0` in your vimrc.

**Comment by edwmurph** [comment]
@jalvesaq `VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb  2 2017 02:17:46)`

**Comment by jalvesaq** [comment]
It is more than one year old. Could you upgrade it? Does it have the `job` feature? You can check it with
```
:echo has('job')
```
You could also try Neovim.

**Comment by edwmurph** [comment]
@jalvesaq Thanks that was it! Also for anyone else who might have hit this issue I needed no additional .vimrc configs.
