### ISSUE TITLE
Tmux split pane to run R doesn't work after update

### ISSUE THREAD

**Issue by aneichyk** [jalvesaq/Nvim-R#474]
I recently updated the plugin and since then R opens in a new terminal window instead of splitting pane. All the options remained the same.
It seems from the release notes that R_tmux_split option has been removed. So what is the alternative? How to get R to start in tmux pane rather than a new window?
My .vimrc has

```
let R_in_buffer = 0                                                          
let R_applescript = 0                                                        
let R_tmux_split = 1  
```

**Comment by jalvesaq** [comment]
Please, see https://github.com/jalvesaq/Nvim-R/blob/master/R/tmux_split.md
