### ISSUE TITLE
Cannot see all of the output

### ISSUE THREAD

**Issue by Zhu-Justin** [jalvesaq/Nvim-R#475]
Hi there,
Thanks for all your hard work in making this. I was wondering if there is a way to see all of the outputs of a long R selection (either by scrolling up or some keybindings). Since I'm using vim, I do not think I have the ability to scroll nor do I know the keybindings to scroll through the entire output. If this already exists, could you let me know how to use it? Otherwise, could you make this a feature? Thank you very much!

**Comment by matsburg** [comment]
If the output is in a terminal buffer in vim, you can press `<C-\><C-n>` to get to normal mode and then scroll up using normal vim movements. e.g. k or `<C-u>`.
