### ISSUE TITLE
Keybinding to open specific R version (e.g. toggle between release and dev)

### ISSUE THREAD

**Issue by tgirke** [jalvesaq/Nvim-R#476]
What is the most elegant and intended keybinding to open a specific R version in nvim-r? A typical use case would be to have keybindings to open R-release, R-devel or just any R-version-xyz installed on a system. The following command from the [nvim-r manual](https://raw.githubusercontent.com/jalvesaq/Nvim-R/master/doc/Nvim-R.txt) lets me set the R_path. With this one could define a custom keybinding, but an _official/intended_ solution would be nice to have. I apologize if there is already one in place that I missed.  

```sh
let R_path = '/path/to/my/preferred/R/version/bin'
```

**Comment by jalvesaq** [comment]
A user has asked similar question a few days ago by email. `R_path` is used to change the environment variable `$PATH` which defines which R version will be the first one to be found. The `$PATH` variable is adjusted when the first R script is read. I will see if the reading of `R_path` can be postponed until R is going to be started.

**Comment by tgirke** [comment]
Great. Given that a large user base of nvim-r may be developers, a simple and intuitive mechanism to switch between R versions would be very useful.

**Comment by jalvesaq** [comment]
Please, could you update Nvim-R and try this in your init.vim/vimrc?

```vim
function StartRFromPath(path)
    let g:R_path = a:path
    call StartR("R")
endfunction

nmap ,rx :call StartRFromPath('/usr/bin')<CR>
nmap ,ry :call StartRFromPath('/usr/local/bin')<CR>
```

Of course, you have to replace `,rx` and `,ry` with your preferred key bindings and the paths with the actual R paths.

**Comment by tgirke** [comment]
Works great! I haven't done too much testing yet, but let you know if I run into any problems. - Thanks for adding this very useful feature.
