### ISSUE TITLE
Failed to start R in Vim on Windows

### ISSUE THREAD

**Issue by hongyuanjia** [jalvesaq/Nvim-R#478]
I reset my Windows machine and tried to setup my R working environment using Gvim. But I encountered the error below:

<img width="1078" alt="Snipaste_2020-04-25_19-21-35" src="https://user-images.githubusercontent.com/20545387/80278581-3a9d8780-872a-11ea-9ddf-e7c7b2ff0f04.png">

Looking at the source code of `IsDirWritable()`, it is wired that the error comes from line 13 `catch E482` which should not be executed because I am in Gvim not NeoVim.

Anything insights? Thanks!

**Comment by jalvesaq** [comment]
The function `IsDirWritable()` was an attempt to avoid a Neovim bug, but perhaps the bug is already fixed. So, could you upadate Nvim-R and try again, please?

**Comment by hongyuanjia** [comment]
Thanks! It has been fixed. Appreciate your quick response!
