### ISSUE TITLE
Rstop within browser prompt

### ISSUE THREAD

**Issue by petobens** [jalvesaq/Nvim-R#479]
Consider the following minimal init.vim:
```vim
let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/jalvesaq/Nvim-R
filetype plugin indent on
```
Now open `nvim` and do:
1. Edit a `foo.R` file with
```R
x <- 2
browser()
y <- 3
```
2. Press `\rf` to start R, then `\aa` to send the file and finally `\rq` to quit.
After pressing `\rq` I get an error saying 
```
In quit(save = "no") : cannot quit from browser
```
So my question is: is there a way to run `Rstop` when being inside a browser prompt? Thanks in advance.

**Comment by jalvesaq** [comment]
`:RStop` sends the signal `SIGINT` do R, but R decides what to do next. It seems that it simply ignores `SIGINT` if running `browser()`.

**Comment by petobens** [comment]
So there is no possible workaround for this?

**Comment by jalvesaq** [comment]
You can do in a terminal emulator:

```
killall R
```

If R still doesn't die:

```
killall -9 R
```

**Comment by jalvesaq** [comment]
The signal number 9 is the `SIGKILL`. I could create a new command, `:RKill`, to send the `SIGKILL` to R.

**Comment by petobens** [comment]
That would be nice. Thanks

**Comment by jalvesaq** [comment]
Please, update the plugin and let me know if `:RKill` does what you need.

**Comment by petobens** [comment]
I kind of does. Isn't it simpler to add a mapping that sends `Q` (to quit the `browser`) and then `quit(save="no")` to exit?

**Comment by jalvesaq** [comment]
This is a very specific need. I don't believe that there are many people missing a mapping for this. You can put this in your vimrc:

```
autocmd FileType r nmap <buffer><silent> <LocalLeader>bq :call g:SendCmdToR('Q')<CR>
```

Isn't `browser()` supposed to require interaction from the user? Why don't you manually type `Q` in the R Console? I'm just curious.

**Comment by petobens** [comment]
Yep that's probably better. Thanks
