### ISSUE TITLE
Focus of window when calling R

### ISSUE THREAD

**Issue by songcai** [jalvesaq/Nvim-R#48]
If invoking R in a separate terminal window, the focus is given to the newly called terminal window that runs R. Is it possible to keep the focus on the nvim/vim terminal window?

Thanks.

**Comment by jalvesaq** [comment]
Yes, you can create an AppleScript to do this. Please, see the example for Linux:
```
:h R_after_start
```

**Comment by songcai** [comment]
Many thanks, Jakson.

**Comment by songcai** [comment]
A digression, but is there a way to send a R command, say ls(), automatically when R console is invoked by ",rf"?

**Comment by jalvesaq** [comment]
You can put the following line at the very end of `StartR()` function at `R/common_global.vim`:
```vim
    call g:SendCmdToR("ls()\n")
```

**Comment by songcai** [comment]
I got a solution for focusing the neovim terminal window instead of the R window on Mac OS. Jakson, you can use this in the documentation if you think it helps.

I put all the essential scripts under ~/scripts/, and do the following. Note that you have to change the path according to your own setting.
1. In my ~/.vimrc, I added the following line
`let R_after_start="~/scripts/after_R_start`

2. Under ~/scripts, I created a bash script named after_R_start, and made it executable. The content is as follows
`#!/bin/bash
osascript ~/after_R_start.scpt`

3. Under ~/scripts, I created an applescript named after_R_start.scpt with the following content
`tell application "Terminal"
  set index of window 1 where name contains ".R" to 1
  delay 0.05
  activate window 1
end tell

tell application "System Events"
  tell process "Terminal"
    click menu item (name of window 1) of menu of menu bar item "Window" of menu bar 1
  end tell
end tell`

Now everything is set, and when you invoke R in a separate terminal in Mac OS, the focus will come back to the neovim terminal window.

**Comment by jalvesaq** [comment]
Thanks for the feedback! According to http://apple.stackexchange.com/questions/103621/run-applescript-from-bash-script a single script will do the job if its first line is
```
#!/usr/bin/env osascript
```
Does the above suggestion work?
And why do you click the menu?

**Comment by songcai** [comment]
Thanks, Jakson. The trick worked perfectly.

Now the reason for the click: That script perform a click on the "title bar" of the window. If I do not click it, the first chunk of the script only raise the window to the front but do not bring focus to it. After that I have to click it once to really "activate" that window.

Using the trick, the following is a working script (without the need of two separate scripts)
'#!/usr/bin/env osascript'
' '
'--Raise the Terminal window containing name ".R".'
'tell application "Terminal"'
'  set index of window 1 where name contains ".R" to 1'
'  delay 0.05'
'  activate window 1'
'end tell'
' '
'--Click the title bar of the raised window to bring focus to it.'
'tell application "System Events"'
'  tell process "Terminal"'
'    click menu item (name of window 1) of menu of menu bar item "Window" of menu bar 1'
'  end tell'
'end tell'

**Comment by jalvesaq** [comment]
I added the example to the documentation. Thanks!

**Comment by songcai** [comment]
It is a pleasure that I can contribute a little.
We all thank you for your wonderful plugin, and very much appreciate every effort you put in it.

**Comment by jalvesaq** [comment]
Thanks! I'm closing the issue.
