### ISSUE TITLE
starting with environment variables set

### ISSUE THREAD

**Issue by tjtnew** [jalvesaq/Nvim-R#480]
Is it possible to start R with an environment variable set?   

For example from a terminal I can start R with the environment variable TMPVAR set to 1
```
TMPVAR=1 R 
```
Is it possible to do this within vim when starting Nvim-R?  Apologies if I have missed something in the documentation.

**Comment by jalvesaq** [comment]
Only a few environment variables are read on the FileType event (when you start editing any type of R file): `$TMP`, `$TMPDIR`, and `$WINDOWID`. These variable have to be defined either on the `vimrc` or before starting Vim/Neovim. All other environment variables can be either set or changed before starting R. Example:

```
:let $TMPVAR = "1"
```

**Comment by tjtnew** [comment]
Thank you. I'm new to vim so did not realise that would work. Cheers!
