### ISSUE TITLE
Documentation of user written packages opens as 'rout' file type in Vim buffer

### ISSUE THREAD

**Issue by vvarik** [jalvesaq/Nvim-R#482]
I load package with `devtools::load_all('./r')`. The issue is that associated R documentation get's assigned 'rout' filetype in Vim buffer.  `:set ft=rdoc` restores expected functionality/looks until I open next documentation page. Problem disappears when I build and install the package. All worked flawlessly until fairly recently, I reckon upgrading all my vim plugins couple days ago, though.

Ubuntu 18.04, Vim 8.2.647, Nvim-r 0.9.13.1

**Comment by vvarik** [comment]
I put options(nvimcom.verbose=4) in .Rprofile. Then, I see that:
`nvimcom Received: [8] 3630487191531206582nvimcom:::nvim.help("myfun", 84L)`
`nvimcom_eval_expr: 'nvimcom:::nvim.help("myfun", 84L)'`
`nvimcom_nvimclient(ShowRDoc('mypackage:myfun.Rd')): '10102' (10102)`

**Comment by vvarik** [comment]
Thanks a lot, that did it with just a minor touch, I had to change it to `set filetype=rdoc`.

**Comment by jalvesaq** [comment]
But I can't fix this in Nvim-R because the file extension `.Rd` corresponds to the file type `rhelp` in Vim.

Perhaps in this case devtools should call `edit("path/to/mypakcage/man/myfun.Rd")` instead of `nvimcom:::nvim.help("myfun", 85L)` if the goal is to allow the package developer to have quick access to the documentation source.

**Comment by vvarik** [comment]
I'd say `devtools::load_all()` is not so much about accessing source, but using the code / documentation right away without (ever) installing it. Really useful when organizing / sharing some project specific code that you / others do not necessarily want to install, just to use.

I don't know enough to understand the implications of allowing `.Rd` to correspond to `rdoc` in this particular patch. What I do know is twofold: 1) it fixes the problem for me (again, I don't know at what cost); 2) CRAN package help files, too, open as `rdoc` filetypes in my Vim. 

This all makes me also wonder what do the lines 2382-2384 in the `common_global.vim` file then mean as they superficially seem to couple some `help` with `rdoc`.
