### ISSUE TITLE
Is it possible to use Nvim-R on Windows with a separate R instance

### ISSUE THREAD

**Issue by alexcoulton** [jalvesaq/Nvim-R#485]
Is it possible to use Nvim-R on Windows with a R instance, i.e. not using the integrated terminal pane in vim and instead using an R console?

I often have projects with multiple files, and Vim's insistence of keeping panes within tabs prevents me from seeing the R console when switching tab.

I know I can do this with tmux on Linux but is it possible on Windows?

**Comment by jalvesaq** [comment]
You can try this in your vimrc:

```
let R_in_buffer = 0
```

**Comment by alexcoulton** [comment]
Amazing, thank you
