### ISSUE TITLE
Can I turn off "." as a word delimiter in Rmd files?

### ISSUE THREAD

**Issue by alexcoulton** [jalvesaq/Nvim-R#486]
Currently Nvim-R seems to treat variables internally separated by a . as separate words when editing Rmd files.

e.g. my.variable.name

Is it possible to treat these as whole words?

**Comment by jalvesaq** [comment]
The option 'iskeyword' can be only one for buffer. This is a Vim/Neovim limitation, and we can't set different values for main text and chunks of R code. You can put this in your vimrc/init.vim:

```
autocmd FileType rmd setlocal iskeyword=@,48-57,_,.,192-255
```

But, then, dots will be considered part of words in regular text.
