### ISSUE TITLE
Nvim-R works still no more (Windows 10) 

### ISSUE THREAD

**Issue by Dulohan** [jalvesaq/Nvim-R#490]
I just read the proposed solution by jalvesaq, on my post "Nvim-R works no more", which was closed. 
I installed R 4.0.0, and Rtools 4.0, Nvim-R_0.9.13 and vim 8.1 and set the path to the rtool40 mingw32 and mingw64 folders. 
Now I could compile without error messages. In vim the R dropdown menu appears and an R window can be opened. However, then both the vim and R window become unresponsive. 
In the AppData\Roaming\Nvim-R folder, a README and a path_to_nvimcom file, but no nvimcom_info file.

**Comment by jalvesaq** [comment]
Please, try:
1. Use the latest version of GVim.
2. Use Neovim.
In the test that I did yesterday, omnicompletion was not perfect in Neovim-Qt, but worked well in nvim in the cmd terminal.

**Comment by jalvesaq** [comment]
Nvim-R 0.9.3 is the released version, but I can only test the development version of the plugin because I don't have spare time to keep both stable and development versions.

**Comment by Dulohan** [comment]
Hi Jakson, I fully understand this and I am grateful for any help. I would also prefer to work under a unixoid system instead of windows. The more I would like to use my favourite tools (e.g. vim). 

This is only a sidenote: if R_term = Rgui , or the g:rplugin.Rcmd, the compilation does stop because with Rgui, the option "-f" does not exist. This is used in the CheckNvimcomVersion function in "common_global.vim".

**Comment by jalvesaq** [comment]
The `R_term` option is used only on Unix systems and it should be completely innocuous on Windows. The variables in the `rplugin` dictionary are supposed to be internally defined by Nvim-R. Users should only define in their `vimrc` the variables starting with the `R_` string and documented in `doc/Nvim-R.txt`.

Please, see the instructions on section _6.3_, _Windows specific options_, especially the definition of the `PATH` environment variable which has to include the directories of both `make` and `gcc`.

I released a new version of Nvim-R today, and I added a `stable` branch to Nvim-R's repository. I will try to fix in the stable branch any bug that is reported and that I can replicate.

**Comment by Dulohan** [comment]
Brilliant! The new vball works out of the box, I only had to set the R_path!
Thank you so much!
