### ISSUE TITLE
Localleader commands not working

### ISSUE THREAD

**Issue by MarWeUMR** [jalvesaq/Nvim-R#492]
Hi,

I installed the plugin using vim-plug. Somehow the `<localleader>xy` commands do not work though.
When I execute `:nmap` there are all the commands listed and when I'm using e.g. `:call StartR('R')`, the extension works. Using <localleader>rf on the other hand gives me 

> E486: Pattern not found: rf

I'm rather new to the vim world so I'm totally lost here. 
Thanks in advance for any help!

**Comment by jalvesaq** [comment]
By default, the `<LocalLeader>` is `\` and not `/`.

**Comment by MarWeUMR** [comment]
Ok, problem solved. It wasn't associated with this plugin in any way. This issue can be deleted, but thank you anyway!
