### ISSUE TITLE
error_installing_nvimcom

### ISSUE THREAD

**Issue by yuejuny** [jalvesaq/Nvim-R#493]
hi all,
I have been using nvim-r for a long time. Yesterday I updated the plugin, it stopped working. I tried many things. The same error came up again and again. 
- NeoVim0.4.3
- Plug to manage plugins
- windows 10

Error messages:

* installing to library 'C:/Program Files/R/R-4.0.0/library'
* installing *source* package 'nvimcom' ...
** using staged installation
** libs
"C:/rtools40/mingw64/bin/"gcc  -I"c:/PROGRA~1/R/R-40~1.0/include" -DNDEBUG       -D`c:/PROGRA~1/R/R-40~1.0/bin/R --slave -e 'cat(Sys.info()[[1]])'` -DLWS_NO_FORK  -DWIN32   -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c nvimcom.c -o nvimcom.o
nvimcom.c: In function 'nvimcom_list_libs':
nvimcom.c:1022:10: warning: unused variable 'rcmd' [-Wunused-variable]
     char rcmd[128];
          ^~~~
nvimcom.c:1021:10: warning: unused variable 'pkgtitle' [-Wunused-variable]
     char pkgtitle[128];
          ^~~~~~~~
C:/rtools40/mingw64/bin/gcc -shared -s -static-libgcc -o nvimcom.dll tmp.def nvimcom.o -lWs2_32 -Lc:/PROGRA~1/R/R-40~1.0/bin/x64 -lR
(cd apps; make -f Makefile.win)
make[1]: Entering directory '/c/Users/MyName/AppData/Local/Temp/RtmpC0gnUN/R.INSTALL1ee446fa52de/nvimcom/src/apps'
gcc -m64 -mwindows -std=gnu99 -O3 -Wall -DWIN32 nclientserver.c -o nclientserver.exe -lWs2_32
make[1]: gcc: Command not found
make[1]: *** [Makefile.win:10: nclientserver.exe] Error 127
make[1]: Leaving directory '/c/Users/MyName/AppData/Local/Temp/RtmpC0gnUN/R.INSTALL1ee446fa52de/nvimcom/src/apps'
make: *** [Makevars.win:11: nvimapps] Error 2
ERROR: compilation failed for package 'nvimcom'
* removing 'C:/Program Files/R/R-4.0.0/library/nvimcom'

**Comment by jalvesaq** [comment]
As expalined in the updated documentation, please, put in your vimrc:

```
let $PATH = "c:\\rtools40\\usr\\bin;c:\\rtools40\\mingw64\\bin;" . $PATH
```

**Comment by yuejuny** [comment]
thank you so much for the prompt response. Sorry I did not read the document.
