### ISSUE TITLE
Error detected while processing function StartFloatWin: Undefined variable: s:user_data

### ISSUE THREAD

**Issue by anasem** [jalvesaq/Nvim-R#497]
Hello, 

When auto complete floating menu is opened and trying to select an item the following error is produced:

`Error detected while processing function StartFloatWin: Undefined variable: s:user_data`

**Comment by jalvesaq** [comment]
Thanks for reporting the issue! I need to know what is your Vim/Neovim version, and what you are completing. Function names, function arguments, elements of data.frames?

**Comment by jalvesaq** [comment]
Are you using `asyncomplete`, `coc.nvim`, or `ncm-R` for automatic omnicompletion? I also need this information to try to replicate the issue.

**Comment by emeralit** [comment]
I have the same issue with Neovim v0.4.3 and ncm-R.

**Comment by anasem** [comment]
I'm also using Neovim v0.4.3 and ncm-R same as @emeralit  (on Linux). The problem started after last plugin update.

**Comment by anasem** [comment]
Thanks a lot, it works perfectly now!

**Comment by emeralit** [comment]
Thanks you!

**Comment by jalvesaq** [comment]
This is a provisory fix. It would be better to have the floating window working with ncm-R, which is developed by @gaalcaras

**Comment by jalvesaq** [comment]
The last change committed to https://github.com/gaalcaras/ncm-R was on December 2018, and ncm2 seems to be only receiving bug fixes: https://github.com/ncm2/ncm2/commits/master

So, although ncm-R still works well, perhaps I should no longer make reference to it in Nvim-R's documentation.

**Comment by emeralit** [comment]
Hi,
I tried to remove ncm2 and ncm-R plugins and installed deoplete in my init.vim.  Now I have the same error as this issue.

**Comment by 942kid** [comment]
Hi, I also have the same error messages after the last Nvim-R update. I am using neovim v0.4.3 but a different tab completion plugin, [VimCompletesMe](https://github.com/ajh17/VimCompletesMe). However, after I switched to coc the completions worked fine.

**Comment by emeralit** [comment]
@942kid Hi, how did you configure coc? Thanks

**Comment by jalvesaq** [comment]
Does deoplete has a source for R?

**Comment by jalvesaq** [comment]
Now the initial value of `s:user_data` unconditionally `{}`.

**Comment by 942kid** [comment]
Hi @emeralit, I followed [the github README](https://github.com/neoclide/coc.nvim/blame/master/README.md#L121). Sorry for the confusion, but I just realized that the same error **did happen** when tab completion was mapped as in the example setup. It won't appear when the float window pop up for choices.

**Comment by 942kid** [comment]
> Now the initial value of `s:user_data` unconditionally `{}`.

Thanks a lot, @jalvesaq, for the quick fixes.

It seems the plugin now works fine with the tab completion. I just updated and tried with coc.

**Comment by anasshe3sha3y** [comment]
> Now the initial value of `s:user_data` unconditionally `{}`

I had the same problem with `coc.nvim` and the update fixed it. Thank you!
