### ISSUE TITLE
How to restore access to Nvim-R windows after they are hidden?

### ISSUE THREAD

**Issue by srearl** [jalvesaq/Nvim-R#498]
Apologies if I am missing something obvious but when working in Nvim-R, if my environment changes such that the R interactive terminal is no longer visible, I am unable to restore access to the Nvim-R interfaces. For example, if I am working on an R script interactively with Nvim-R but make the R script the only visible window (e.g., via `:only`), I do not seem to be able to reacquire any of the Nvim-R windows. In those cases, the only solution I have found thus far is to quit Nvim-R (`\rq`) as it does seem to be still be running then start a new session (`\rf`). Is this expected behaviour?

Nvim-R is absolutely fantastic BTW!

**Comment by jalvesaq** [comment]
When I do the command `:only`, I get the message:

> "R" exited with status 129

I have tried `:hide` in the R window and, then, I can list hidden buffers with the command `:buffers!` and reopen the buffer (after splitting the windows again) with the command `:b 2` where `2` is the buffer's number.

However, I think that this procedure is too complicated. Please, seek the word "zoom" in the plugin's documentation. When I want to focus on a single window, I type `gz`, and, when I'm done, I close the tab.

**Comment by srearl** [comment]
Excellent. Thank you very much for clarifying.

**Comment by ipstone** [comment]
Thanks, just one comment/restate @jalvesq 's answer:
- `:buffers!` to list he hidden buffers
- `:b 2` to switch to the hidden buffer, say if R session has buffer number 2.

(It wasn't very clear to me in the first place for the above answer).
