### ISSUE TITLE
R Help is not displayed in nvim

### ISSUE THREAD

**Issue by FvD** [jalvesaq/Nvim-R#5]
To repeat in on Ubuntu 14.04 tmux 1.8:

  1.  Open an R session with \rf
  2.  move to the R session and type ?dplyr::dplyr (or whatever other package)

```
    Error detected while processing function ROnJobActivity..ShowRDoc:
    Line 17
    E121: Undefined variable: g:rplugin_R_bufname
```

**Comment by jalvesaq** [comment]
Thanks for reporting the bug. It is fixed now: https://github.com/jalvesaq/Nvim-R/commit/c64af4d9cee0013a9a27bd736c71464401f0355b
