### ISSUE TITLE
Pacman's p_unload(all) freezes nvim-R

### ISSUE THREAD

**Issue by krishnakumarg1984** [jalvesaq/Nvim-R#500]
When using the `R` package manager `pacman`,  the `p_unload(all)` command entirely freezes `nvim-R` and the whole session becomes unresponsive to the point of having to force-quit `vim`. This is a bug in `nvim-R` because in the basic R console, `p_unload(all)` works just fine instantaneously.

The following is a minimal example to reproduce the problem. 

```R
# Install pacman ("package manager") if needed
if (!require("pacman")) install.packages("pacman")

# Load contributed packages with pacman
pacman::p_load(pacman, party, psych, rio, tidyverse)

# Clear packages
p_unload(all)  # Remove all add-ons
```

### Additional Information

> sessionInfo()
R version 4.0.1 (2020-06-06)
Platform: x86_64-apple-darwin19.5.0 (64-bit)
Running under: macOS Catalina 10.15.5
>
Matrix products: default
BLAS/LAPACK: /usr/local/Cellar/openblas/0.3.9/lib/libopenblasp-r0.3.9.dylib
>
locale:
[1] en_GB/en_GB/en_GB/C/en_GB/en_GB
>
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base
>
loaded via a namespace (and not attached):
[1] compiler_4.0.1
```

**Comment by jranke** [comment]
Does this maybe unload nvimcom as well?

**Comment by krishnakumarg1984** [comment]
@jranke Ah. That should explain it. However, it renders `nvim-R` ineffective because I need to work collaboratively with my colleagues on existing `R` scripts such as the minimal example above. It would be unfair for me to ask the whole team to modify their scripts just because of my chosen working environment.

**Comment by jalvesaq** [comment]
You could try to load nvimcom again. Maybe setting the environment variable `R_DEFAULT_PACKAGES` could be useful. Please, seek "R_DEFAULT_PACKAGES" in Nvim-R's documentation.

**Comment by krishnakumarg1984** [comment]
Ah. We share `.RProfile` in my team with a set `R_DEFAULT_PACKAGES` to provide the same working environment to all.

Can I split my `.RProfile` across a personal file (containing `nvimcom`), and a team file?

**Comment by jalvesaq** [comment]
Does the example in the documentation work?

```
   if(Sys.getenv("NVIMR_TMPDIR") == ""){
       options(defaultPackages = c("utils", "grDevices", "graphics", "stats", "methods"))
   } else {
       options(defaultPackages = c("utils", "grDevices", "graphics", "stats", "methods", "nvimcom"))
   }
```

**Comment by krishnakumarg1984** [comment]
@jalvesaq This is what I used in my `~/.RProfile` (a slight modification of the suggested version in the documentation to avoid `hard-coding` default packages in a fresh install.

```R
if(Sys.getenv("NVIMR_TMPDIR") == ""){
   options(defaultPackages = c(getOption("defaultPackages")))
} else {
   options(defaultPackages=c(getOption("defaultPackages"), "nvimcom"))
}
```

However, the issue persists.

**Comment by jalvesaq** [comment]
That's a good idea, and it can be simplified to:

```r
if(Sys.getenv("NVIMR_TMPDIR") != "")
   options(defaultPackages=c(getOption("defaultPackages"), "nvimcom"))
```

I will update the documentation.

I'm sorry that it doesn't solve your problem.

**Comment by krishnakumarg1984** [comment]
@jalvesaq Do you know why it doesn't work for me? Is there some hackery possible?

**Comment by jalvesaq** [comment]
I installed `pacman` and put `library(pacman)` in my `~/.Rprofile`. After starting R, the output of `p_loaded()` is:

```
[1] "nvimcom"  "pacman"   "colorout"
```

But everything is normal. I can send commands to R, open R help documents, do omni completion, etc...

**Comment by krishnakumarg1984** [comment]
@jalvesaq Yes. Upto the point you describe, everything works for me too (and this issue is not about loading, but about unloading).

Now try `p_unload(all)`. Immediately everything about `nvim-R` just freezes completely. The use case for this command in our team's workflow is the following:

Let's say you installed a bunch of packages for some analysis, and after getting some intermediate results (say 50% of your workflow is done at this point), you may want to free up memory/clean up your workspace etc for a different type of analysis. Sure, we could just open another R script and start afresh, but if the content of the 2nd half of the analysis is logically related with the first half, you want to proceed, but after removing all the packages loaded by pacman to give you a clean slate. Now, in a large project such as a memory-intensive bookdown document, it is almost a requirement since there is no point in keeping in memory a package required for chapter-1, when we are at the point of working on / knitting chapter-5. Several other use cases exist for unloading all loaded packages and to start from scratch. It would be tedious to specify each of the 25 loaded package names manually, and hence `p_unload(all)`.

Somehow the idea is that `p_unload(all)` must retain `nvimcom` so that the vim session doesn't become unresponsive.

**Comment by jalvesaq** [comment]
According to pacman documentation, this should work:

```r
p_unload("nvimcom", negate = TRUE)
```

I tryed `p_unload("kdkeisldjes", negate = TRUE)` and there was no error message. So, the command to unload all packages but `nvimcom` should be harmless to your colleagues.

**Comment by krishnakumarg1984** [comment]
@jalvesaq Great. That's good enough for me for now. Thanks a lot for all your help.

Just in case if it is (technically) possible, can you maybe fortify `nvimcom` against `p_unload(all)` so that the R-session within vim remains alive.  To not disrupt current behaviour, this could be added as an optional config to `nvim-R`  `let_nvimcom_persistent = 1` with the default at `0`. 

By the way, I forgot to thank you for this awesome plugin. This can help me to ditch `rstudio`!

**Comment by jalvesaq** [comment]
Unfortunately, as far as I know, this is not possible. Users are free to load and unload any package.

**Comment by krishnakumarg1984** [comment]
@jalvesaq Hmm.. Yes. How about automatically attempting to reload `nvimcom` upon unloading (as long one of the R-family filetype buffers remain open in vim), and again make this setting optional (`let_nvimcom_reload_connection = 1`)?

**Comment by jalvesaq** [comment]
I would have to add code to nvimcom to send a message for Neovim when being stopped but it could be stopped because R was quitting... Then Nvim-R would send `library(nvimcom)` to an R that was going to quit. I'm sorry, but I'm not going to try this.

The real solution would be to write an R frontend to make nvimcom unnecessary. Maybe I will do that in the distant future, not anytime soon.

**Comment by krishnakumarg1984** [comment]
>I would have to add code to nvimcom to send a message for Neovim when being stopped but it could be stopped because R was quitting... Then Nvim-R would send library(nvimcom) to an R that was going to quit. I'm sorry, but I'm not going to try this.

Hmm. True that. This is where the user choice plays a role, and the user makes a conscious opt-in to this type of behaviour. The probability of an `R` session alone quitting while `R`-family buffers are active might be low, so with a conscious user opt-in, this is probably not all that bad?  If the user absolutely wants to quit `R` (i.e. not be stuck at the infinite loop you are worried about), they can unload the `R-family` buffers, or when they are fully done with their `vim` session, do a `:qa`.  Remember, there are multiple safety guards here: 
1. Check whether R-family (.r,.rnw,.rmd etc.) buffers are still open
2. Check if the user is really interested in this behaviour with their opt-in setting
3. Check if `R_DEFAULT_PACKAGES` contain `pacman`

Ultimately, it is upto to you to decide whether this is something you'd consider. Respecting your decision, I shall not further push in this direction. Apologies.

**Comment by jalvesaq** [comment]
I'm sorry but my intention is not to support specific packages. Even if I used `pacman` or `devtools` I think it would be better to support them in a vim script to be sourced by Nvim-R through the `R_source` option. If someone writes such a script, I will mention it in Nvim-R's documentation.
