### ISSUE TITLE
Oxygen documentation of Oxygen documentation parsed incorrectly

### ISSUE THREAD

**Issue by zkamvar** [jalvesaq/Nvim-R#502]
Hello,

I'm working on a package that would use oxygen documentation for processing and need to include oxygen syntax inside my oxygen documentation like so:

```r
#' @examples
#' # parse text
#' 
#' txt <- parse_txt("#' An example
#' #' of parsed text
#' #' 
#' #' @sometag
#' #' 
#' #' Sometag attributes
#' #' ")
#' 
#' # the text is now parsed
#' txt
```

If I try to execute this in my session, None of the text beyond the first line is evaluated. Is there a way around this?

I attempted to look into `common_global.vim`, modifying `CleanOxygenLine` to use a lookbehind, but no luck:

```vim
function CleanOxygenLine(line)
    let cline = a:line
    if cline =~ "^\s*\\(#\\{1,2}'\s*\\)\\@<!#\\{1,2}'"
        let synName = synIDattr(synID(line("."), col("."), 1), "name")
        if synName == "rOExamples"
            let cline = substitute(cline, "^\s*\\(#\\{1,2}'\s*\\)\\@<!#\\{1,2}'", "", "")
        endif
    endif
    return cline
endfunction

```

**Comment by jalvesaq** [comment]
I don't use ROxygen. So, please, open a pull request if you can fix the issue. Thanks!
