### ISSUE TITLE
`R_objbr_place` bottom and above produce strange results

### ISSUE THREAD

**Issue by AdrienLeGuillou** [jalvesaq/Nvim-R#503]
When using Nvim-R version > 0.9.11, having `let R_objbr_place = 'console,above'` does not position the object browser as intended. Everything gets squished at the top (script, console, and browser) [Screenshot with the issue](https://i.ibb.co/bWmnsNh/not-working.png)

With Nvim-R version 0.9.11 and `let R_objbr_place = 'console,top'` the result is as expected. [Screenshot of version 0.9.11, no issue](https://i.ibb.co/rFP9cQ7/working.png)

I tried this with versions 0.9.12, 0.9.13, 0.9.14, and directly from master.

**Comment by jalvesaq** [comment]
Thanks for reporting the issue!
