### ISSUE TITLE
Support bookdown render functionality

### ISSUE THREAD

**Issue by krishnakumarg1984** [jalvesaq/Nvim-R#508]
The [`bookdown`](https://bookdown.org/yihui/bookdown/) R-package helps in compiling multi-page HTML output resembling the gitbook formats which are absoloutely beautiful (and packed with usability features).  

Currently, the supported key bindings do not account for `bookdown`  and only cover single-page rendering of Rmarkdown documents. To clarify, `bookdown` is not a separate documentation format. It is simply RMarkdown syntax source files, but separated into multiple files (one per chapter) for long-form reports, books and theses.

Can you please provide suitable infrastructure to execute the `bookdown::render_book` function from within vim?  Its calliogn syntax and default arguments are given below ([extracted verbatim from the official documentation](https://bookdown.org/yihui/bookdown/build-the-book.html)):

```r
render_book(input, output_format = NULL, ...,
  clean = TRUE, envir = parent.frame(),
  clean_envir = !interactive(), output_dir = NULL,
  new_session = NA, preview = FALSE,
  config_file = "_bookdown.yml")
```

**Comment by paulrougieux** [comment]
In bookdown.org [build-the-book](https://bookdown.org/yihui/bookdown/build-the-book.html), Yihui (the package author) recommends using a makefile. With a make file, book building can be started from vim in a separate buffer with:

    :term make

**Comment by jranke** [comment]
You can also use

```
:make
```

**Comment by mikemc** [comment]
Another option that doesn't require any change to Nvim-R is to define your own shortcut to run "render_book()" in the current session, similar to "<LocalLeader>kr" for standard Rmarkdown rendering. E.g. I put the following in ".vim/ftplugin/rmd.vim",
```
" Bookdown rendering
map <silent> <LocalLeader>kbb :call g:SendCmdToR("bookdown::render_book('.')")<CR>
```
which assumes the R working directory is the root of the book project; you might also use `here::here()`. I would also like to have a shortcut to `bookdown::preview_chapter()`, e.g.
```
map <silent> <LocalLeader>kbc :call g:SendCmdToR("bookdown::preview_chapter(???)")<CR>
```
but I'm not sure what to replace `???` with to get the the current file path to be inserted into the command.

**Comment by paulrougieux** [comment]
> define your own shortcut to run bookdown::render_book() in the current session

Using your current R session is not desirable when the sites takes more than a few seconds to render. I would recommend using another R session to render the site, so that you are able to continue interacting with R in the main session. Three ways to use another R session :

1. Render the site in a separate Vim split with a make file.
2. Render the site in a separate tmux pane with a bash command such as 

    cd ~/project_repository/  &&  Rscript -e "bookdown::render_book()"

3. Use a continuous integration tool to build the site when you push to your remote git repository. (For example here is the configuration file [.gitlab-ci.yml](https://github.com/paulrougieux/paulrougieux.github.io/blob/master/.gitlab-ci.yml) I use for gitlab CI)

**Comment by jalvesaq** [comment]
Nvim-R is being superseded by R.nvim, a new project that will be inaugurated in a week at the [R-nvim](https://github.com/R-nvim) organization.
Please, check out [tmp-Nvim-R](https://github.com/jalvesaq/tmp-R-Nvim) and help us to find the last remaining bugs before R.nvim inauguration.
When the project is officially started, you will be able to open issues there and request new features.

Nvim-R will remain alive as a feature-frozen project for Vim users. If you want to know the reason, please, see [this discussion](https://github.com/jalvesaq/Nvim-R/discussions/797).
