### ISSUE TITLE
Recognise knitr root.dir option in setup chunk and set the working directory accordingly

### ISSUE THREAD

**Issue by paulrougieux** [jalvesaq/Nvim-R#509]
I tend to use paths relative to a project's directory. Let's imagine for example that we have the following directory structure: 
```
project/      
| data/          
| | iris.csv     
| subdir/        
| | notebook.Rmd 
```
If I have an R markdown document in `project/subdir`, I write this at the beginning of the R markdown file, in a special chunk called setup (yihui.org [setting opts_knit in setup chunk](https://yihui.org/knitr/objects/) ):

    ```{r setup, include=FALSE}
    library(knitr)
    opts_knit$set(root.dir="..") # file paths are relative to the root of the project directory
    ```

Then I load data or source scripts from subsequent chunks as such:

    ```{r load}
    read.csv("data/iris.csv")
    ```

When starting the R command prompt with `<localleader>rf`, the working directory is set to the location of the markdown file we are currently editing. And of course the second chunk will not work and will return 

```
> read.csv("data/iris.csv")
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'data/iris.csv': No such file or directory

```
Would it be possible to create an option to call:

    setwd(opts_knit$get()$root.dir)

This would need to be called only once when starting the R buffer corresponding to a markdown file?

**Comment by paulrougieux** [comment]
One solution based on :help Nvim-R-key-bindings, is to use SendCmdToR as such:

    :call g:SendCmdToR("setwd(opts_knit$get()$root.dir)")

I mapped this to <localleader>wd by editing my .vimrc as follows:

    map <silent> <LocalLeader>wd  :call g:SendCmdToR("setwd(opts_knit$get()$root.dir)")<CR>

To use it, I run the setup chunk with <localleader>ca, then I call <localleader>wd.

**Comment by jalvesaq** [comment]
Thanks for the feedback!

**Comment by jmrussell** [comment]
I believe I'm having the same issue and neither one of the 2 solutions seems to resolve the problem. I am new to editing vim-plugins... is there a place I can start to see what command is being sent to the R console with \kh? It seems like it might be ignoring the opt_knit$root.dir argument

**Comment by jalvesaq** [comment]
@jmrussell , the commands sent to R Console can be seen in the R Console itself. If you want to see messages sent to nvimcom, put in your `~/.Rprofile`:

```r
options(nvimcom.verbose = 4)
```

**Comment by jmrussell** [comment]
@jalvesaq 

Thanks, I will check that out. The thing that was throwing me for a loop was

```
nvim.interlace.rmd <- function(Rmdfile, outform = NULL, rmddir, ...)
{
    if(!require(rmarkdown))
        stop("Please, install the 'rmarkdown' package.")

    oldwd <- getwd()
    on.exit(setwd(oldwd))
    setwd(rmddir)

    res <- rmarkdown::render(Rmdfile, outform, ...)

    brwsr <- ""
    if(grepl("\\.html$", res)){
        brwsr <- getOption("browser")
        if(!is.character(brwsr))
            brwsr <- ""
    }

    .C("nvimcom_msg_to_nvim",
       paste0("ROpenDoc('", res, "', '", brwsr, "')"),
       PACKAGE = "nvimcom")
    return(invisible(NULL))
}
```

Is this using setwd() to change the wd to the location of the .Rmd file so that you can provide render() the full path before changing it back?

I should clarify the issue is that for my working directory (both getwd() in R and pwd in vim) return the same value - the equivalent to project/ in the OP and knitting fails with a wrong file path message when I do something like

```
knitr::include_graphics("data/plot1.png")

```

and works when I do

```
knitr::include_graphics("../data/plot1.png")

```
Oddly enough, just sending 

```
include_graphics("data/plot1.png")

to the R console works perfectly fine.

I gather you've taken a step back from this project (which is absolutely wonderful btw, I've converted several coworkers to using this in their workflow) so I don't expect you to fix it, but any guidance is awesome.

**Comment by paulrougieux** [comment]
I use Nvim-R to edit Rmd files but I knit them in a separate tmux pane, using  a call to 

    # cd ~/project_path && Rscript -e "rmarkdown::render('notebook.Rmd', 'pdf_document')"

What happens when  you render it in that way?

**Comment by jmrussell** [comment]
I still get a path error. I'm starting to suspect it has nothing to do with Nvim-R and more to do with the way knitting .Rmds work for some reason.
