### ISSUE TITLE
can't use Nvim-R on windows

### ISSUE THREAD

**Issue by zihaoxingstudy1** [jalvesaq/Nvim-R#510]
1 * installing to library 'D:/Program Files/work/R-4.0.2/library'
  2 * installing *source* package 'nvimcom' ...
  3 ** using staged installation
  4 ** libs
  5 D:/PROGRA~1/work/R-40~1.2/etc/x64/Makeconf:244: warning: overriding commands for target `.m.o'
  6 D:/PROGRA~1/work/R-40~1.2/etc/x64/Makeconf:237: warning: ignoring old commands for target `.m.o'
  7 "D:/Program Files/work/rtools40/mingw64/bin/"gcc  -I"D:/PROGRA~1/work/R-40~1.2/include" -DNDEBUG       -D`D:/PROGRA~    1/work/R-40~1.2/bin/R --slave -e 'cat(Sys.info()[[1]])'` -DLWS_NO_FORK  -DWIN32   -O2 -Wall  -std=gnu99 -mfpmath=sse     -msse2 -mstackrealign -c nvimcom.c -o nvimcom.o
  8 gcc: error: unrecognized command line option '--slave'; did you mean '--shared'?
  9 make: *** [nvimcom.o] Error 1
Error_installing_nvimcom

**Comment by jalvesaq** [comment]
I guess the chances of success will be higher if Rtools were in a directory without spaces in its name. See: https://stackoverflow.com/questions/30125476/installing-rtools-error-with-space-in-path
