### ISSUE TITLE
RFC: rnoweb with vimtex

### ISSUE THREAD

**Issue by lervag** [jalvesaq/Nvim-R#511]
Someone suggested to load vimtex for `.Rnw` files, see [here](https://github.com/lervag/vimtex/issues/1729). I'm not really into the whole R community, but I have to admit that rnoweb and Rmarkdown and similar looks very interesting!

I've noticed that the "intrinsic" rnoweb plugin that ships with Vim relies on the selected LaTeX plugin with `runtime! ftplugin/tex.vim`. I was curious if it would be interesting and possible to somehow collaborate to make a good interface between vimtex and Nvim-R in this sense.

I think vimtex could provide some nice features to rnoweb files, like:

* omnicompletion (which works well with most autocomplete frameworks)
* compilation of `.tex` to `.pdf` with good support for parsing errors and showing them in the quickfix list
* text objects
* some utility commands for LaTeX (e.g. toggle delimiters, environments, and so on)

On the other hand, it seems you have a backend that already works well for everything R related, and in this case, for compiling from `.Rnw` to `.tex`, as well as some related stuff like synctex support between `.Rnw` and `.tex`, and so on.

What do you think?

**Comment by jalvesaq** [comment]
I'm sorry, but I no longer edit Rnoweb documents, and it's unlikely that I will have spare time to work on this issue.

**Comment by lervag** [comment]
Ok, no problem.
