### ISSUE TITLE
Unformatted line with %>% causes endless loop of SendLineToR

### ISSUE THREAD

**Issue by ltschmitt** [jalvesaq/Nvim-R#512]
I just updated Nvim-R again since a couple of months ago and I noticed a problem with the behaviour of <Plug>RDSendline. Every line containing %>% will cause the next line to be executed. I saw that this was implemented in #41890d9 which is great. However, for me it always executes the next line regardless if %>% is at the end of the line or if there is a line following at all.

For example this works as intended:
```{r}
library(tidyverse)
as_tibble(cars) %>%
      mutate(test = speed + dist)
```
Whereas this causes the next line to be executed even though it is not intended:
```{r}
library(tidyverse)
as_tibble(cars) %>% mutate(test = speed + dist)
print(cars)
```
And this causes an endless loop of sending the last line to R:
```{r}
library(tidyverse)
as_tibble(cars) %>% mutate(test = speed + dist)
```
I get this error:
```
E132: Function call depth is higher than 'maxfuncdepth'
Error detected while processing function SendLineToR[151]
```

Is there an option to turn off the nextline execution of %>%?

For now reverted the Update to before #41890d9 and it works fine again.

My Nvim-R settings:
```
let R_external_term = "st -n Rsession -e"
let R_openpdf = 1
let R_openhtml = 1
let R_assign = 0
let R_insert_mode_cmds = 1
let R_clear_console = 0
let R_clear_line = 1
let R_args = ['--no-save']
autocmd VimLeave * if exists("g:SendCmdToR") && string(g:SendCmdToR) != "function('SendCmdToR_fake')" | call RQuit("nosave") | endif
let R_start_libs = "base,stats,graphics,grDevices,utils,dplyr,ggplot2,magrittr,purrr,stringr,tidyr"
let Rout_more_colors = 0
let R_hi_fun_global = 2
let R_pdfviewer = 'zathura'
let R_objbr_place = 'console,right'
```

**Comment by jalvesaq** [comment]
Thanks for reporting the bug. It should be fixed in a minute.

**Comment by ltschmitt** [comment]
That was fast! Thanks it works now!
