### ISSUE TITLE
Support for nvim-lua/completion-nvim and neovim's built-in LSP

### ISSUE THREAD

**Issue by gwbrck** [jalvesaq/Nvim-R#513]
As student of social science I am very thankful for this great out-of-the-box working R plugin. But I struggle with my autocompletion configuration for completion-nvim. I tried to follow this [guide](https://github.com/nvim-lua/completion-nvim/wiki/custom-completion-source#create-completion-source-with-omni-func) to use the omni-func of Nvim-R with completion-nvim. I couldn't make it work. 

Is it possible to use completion-nvim with Nvim-R at all?
Any suggestions which function to call? 
Thank you!

**Comment by jalvesaq** [comment]
The name of the omnifunc is "CompleteR". I don't know if it will work well with `completion-nvim`.

**Comment by gwbrck** [comment]
Thank you! 
I get an error:
`Error executing vim.schedule lua callback: /Users/gwbrck/.config/nvim/lua/nvimr.lua:5: Vim(if):E121: Undefined variable: s:compl_type` 
I'll keep trying...

**Comment by jalvesaq** [comment]
Could you try this branch?: https://github.com/jalvesaq/Nvim-R/tree/g_compl_menu

I replaced `s:compl_menu` with `s:r_compl_type` with `g:r_compl_type` because `s:` variables are visible only within the scripts where they are defined.

**Comment by gwbrck** [comment]
Thanks for the effort. Unfortunately, that's not it.
`Error executing vim.schedule lua callback: /Users/gregor/.config/nvim/lua/nvimr.lua:5: Vim(if):E121: Undefined variable: g:r_compl_type`

**Comment by jalvesaq** [comment]
In this case, I don't know what might be wrong, and I'm too busy these days to investigate the issue now.

Automatic omnicompletion works with both yami-beta/asyncomplete-omni.vim and neoclide/coc.nvim.

**Comment by jalvesaq** [comment]
I deleted the `g_compl_menu` branch because it didn't solve anything...

**Comment by gwbrck** [comment]
There is a very simple solution to this problem, which I unfortunately overlooked. Completion-nvim can handle omnicompletion very well. You just have to activate "omni" in the completion-chain-logic of completion-nvim. You can also specify certain filetypes, like .r or .rmd. This is how it works for me:
```vim
let g:completion_chain_complete_list = {
    \ 'r': [
    \       {'mode': 'omni'},
    \       {'complete_items': ['snippet']},
    \       {'complete_items': ['buffers']},
    \],
    \ 'default': [
    \       {'complete_items': ['path'], 'triggered_only': ['/']},
    \       {'complete_items': ['lsp', 'snippet']},
    \       {'complete_items': ['buffers']},
    \]
    \}
```
