### ISSUE TITLE
Package development: ^H appears in Roxygen generated documentation for my package

### ISSUE THREAD

**Issue by suntzuisafterU** [jalvesaq/Nvim-R#514]
Hi,

OS: macOS Catalina (10.15.5)
Nvim-R: version 0.9.14.1
NeoVim: v0.4.3
R: v4.0.1

I am not sure if this is an Nvim-R problem, or an issue with the way that I am calling `devtools::document()`, but I have not been able to find any resources elsewhere (try googling "^H" if you are looking for a real challenge!).

So the issue is that, documentation for all packages installed in the normal manner is displayed correctly.
When I document and install my own package, then open it from the R terminal with `?foo` I get something that looks like:
```
_^HD_^He_^Hs_^Hc_^Hr_^Hi_^Hp_^Ht_^Hi_^Ho_^Hn:

       Register a new experiment and get the relevent ExpID back.
```
According to wikipedia, ^H is what a terminal displays instead interpreting a backspace.

The documentation is displayed correctly in R-studio.
Any suggestions would be appreciated.

**Comment by suntzuisafterU** [comment]
Update:
I also just noticed that I can not use `q` to close the documentation buffer for my own package.
Maybe this buffer is being treated differently than other documentation buffers?

**Comment by jalvesaq** [comment]
The R documentation in text format is similar to a `man` page. The function  `FixRdoc` (`Nvim-R/ftplugin/rdoc.vim`) makes some changes in the documentation buffer when the 'filetype' of the buffer is set to `rdoc` to prepare it to be highlighted by `Nvim-R/syntax/rdoc`. I don't use devtools to know how it processes the documentation.

**Comment by jalvesaq** [comment]
You could try this to see if it fix the documentation:

```
:set filetype=rdoc
```

**Comment by jalvesaq** [comment]
Maybe this is useful: https://github.com/mllg/vim-devtools-plugin

**Comment by suntzuisafterU** [comment]
Thanks, `:set filetype=rdoc` works.  Is there a way to have this set automatically when I open the help file?

I installed the vim-devtools-plugin but it does not appear to do anything in particular to help this.

Also, I noticed the following message when viewing with Nvim-R in the R console that does not show up when viewing in a stand alone R console:
```
Rendering development documentation for 'synth_data'
```
I grepped the source for this package and this message does not appear to be coming from Nvim-R.

I also tried `devtools::load_all()` which masks `?` and `help` for opening development documentation, but this did not resolve the issue.

**Comment by suntzuisafterU** [comment]
Wait it is working now.  I will explain shortly

**Comment by suntzuisafterU** [comment]
Calling `devtools::document()` or `devtools::install()` causes the development package to be loaded into the environment in a form that is different from using `library(MyLib)`.

My solution is to call `devtools::unload()` and then reload the library with `library(MyLib)`.
This also fixes an issue where the R terminal no longer supports autocompletion of objects exported from the development library after using the devtools package from within the Nvim-R terminal.

Here is the complete command I use, bound to an appropriate key.
```
:RSend devtools::document(); devtools::install(); devtools::test(); devtools::unload(); library(MyLib)
```

**Comment by jalvesaq** [comment]
Thanks for the feedback. It might be useful for other users.

**Comment by suntzuisafterU** [comment]
Thanks for the library.  RStudio is a disaster.

**Comment by jalvesaq** [comment]
RStudio has some features that Nvim-R does not, and it is a lifesaver for most R users in the world. But I agree that a small number of people have more fun using Nvim-R than would have using RStudio.

**Comment by suntzuisafterU** [comment]
Oh definitely.  I still use it for debugging etc.  Disaster is harsh.  There is something with the way they handle threading that has given me grief in the past, thats all.

And vim isn't for everyone.
