### ISSUE TITLE
"Not Ready Yet" when trying to autostart R in nvim but works fine when manually starting

### ISSUE THREAD

**Issue by dewoller** [jalvesaq/Nvim-R#515]
Hey @jalvesaq  Jakson, thank you so much for your work.  I use nvim-R for at least 4 hours every day, and it is so lovely to have access to R as an extension of my finger muscle memory.

My problem is not a big problem, but maybe you could help.  It seems to be a timing issue.  When I try to autostart R from my nvim-R.vim profile, R autostarts,  but when I try to use it, I get the "Not Ready Yet" error for every command.

# Background
Ubuntu linux, 18.04
NVIM v0.5.0-dev
R version 4.0.2 (2020-06-22) -- "Taking Off Again"

I use the following lines to autostart R from my nvim-R

```
autocmd FileType r if string(g:SendCmdToR) == "function('SendCmdToR_fake')" | call StartR("R") | endif
autocmd FileType rmd if string(g:SendCmdToR) == "function('SendCmdToR_fake')" | call StartR("R") | endif

```

# Failure debug information when autostarting R

In this case, the output of RDebugInfo is as follows:

##  RDebugInfo 

```
Start_nclientserver
StartR
R_version
4.0.2
```

The debugging information that comes from enabling  
## options(nvimcom.verbose = 4)

```

nclientserver port:
nvimcom 0.9.82 loaded
    NVIMR_TMPDIR = /tmp/Nvim-R-dewoller
    NVIMR_ID = 5241881171225510186
nvimcom port: 10001
nvimcom_nvimclient(SetNvimcomInfo('0.9.82', '/usr/l
ocal/lib/R/site-library/nvimcom', '10001', '17286',
 '0', '4.0.2.> + nvimcom stats graphics grDevices u
tils datasets methods base')): '' (0)
nvimcom_nvimclient() called although Neovim server
port is undefined
```
>

# Success debug information when manually starting R after 

When I do not autostart R, and I start R manually, it works well, as advertised.   Debug information follows

## RDebugInfo

```
CMD_INSTALL
* installing to library ‘/usr/local/lib/R/site-library’
* installing *source* package ‘nvimcom’ ...
** using staged installation
** libs
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-ttHamR/r-base-4.0.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c nvimcom.c -o nvimcom.o
gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o nvimcom.so nvimcom.o -L/usr/lib/R/lib -lR
(cd apps; make)
make[1]: Entering directory '/tmp/Rtmprz2LHR/R.INSTALL5d04ccb6370/nvimcom/src/apps'
cc -pthread -std=gnu99 -O2 -Wall nclientserver.c -o nclientserver
make[1]: Leaving directory '/tmp/Rtmprz2LHR/R.INSTALL5d04ccb6370/nvimcom/src/apps'
installing via 'install.libs.R' to /usr/local/lib/R/site-library/00LOCK-nvimcom/00new/nvimcom
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (nvimcom)
libPaths
['/usr/local/lib/R/site-library', '/home/dewoller/R/x86_64-pc-linux-gnu-library/4.0']
Start_nclientserver
StartR
Build_Omnils
> nvimcom:::nvim.buildomnils("datasets")
> nvimcom:::nvim.buildomnils("utils")
> nvimcom:::nvim.buildomnils("grDevices")
> nvimcom:::nvim.buildomnils("graphics")
> nvimcom:::nvim.buildomnils("stats")
> nvimcom:::nvim.buildomnils("methods")
> nvimcom:::nvim.buildomnils("nvimcom")
> nvimcom:::nvim.buildomnils("base")
>
.libPaths()
CMD_build
* checking for file ‘/home/dewoller/.cache/vimfiles/repos/github.com/wsdjeg/Nvim-R/R/nvimcom/DESCRIPTION’ ... OK
* preparing ‘nvimcom’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘nvimcom_0.9-82.tar.gz’

```

##  options(nvimcom.verbose = 4)

```
nclientserver port: 10101
nvimcom 0.9.82 loaded
    NVIMR_TMPDIR = /tmp/Nvim-R-dewoller
    NVIMR_ID = 25618794157045698
> nvimcom port: 10001
nvimcom_nvimclient(SetNvimcomInfo('0.9.82', '/usr/local/lib/R/site-library/nvimcom', '10001', '32190', '0', '4.0.2.> + nvimcom stats graphi
cs grDevices utils datasets methods base')): '10101' (10101)
>
```

**Comment by jalvesaq** [comment]
Your nvimcom version is 0.9.82, but the current nvimcom version on github is 0.9-92.1 (stable branch) and 0.9-99 (master branch). So, first, you should update Nvim-R. Anyway, starting R automatically is not going to work because the `nclientserver` application is started automatically and, then, R can be started only after the launching of `nclientserver` is finished (1 second or so). Since probably many people would prefer R starting automatically, I may consider adding an option named `R_auto_start` for this.

**Comment by jalvesaq** [comment]
Could you try the branch https://github.com/jalvesaq/Nvim-R/tree/auto_start please?

**Comment by jalvesaq** [comment]
I forgot to say: you have to put `R_auto_start = 1` in your vimrc.

**Comment by a-figment** [comment]
> Your nvimcom version is 0.9.82, but the current nvimcom version on github is 0.9-92.1 (stable branch) and 0.9-99 (master branch). So, first, you should update Nvim-R. 

Doesn't nvimcom [automatically update and install](https://github.com/jalvesaq/Nvim-R/commit/0c9d01d395c724e8ad9a552f4923344d07b00a20)? I couldn't see anything in the [docs](https://raw.githubusercontent.com/jalvesaq/Nvim-R/master/doc/Nvim-R.txt) about updating.

**Comment by jalvesaq** [comment]
Nvimcom updates automatically, but only if Nvim-R is updated manually. The version of nvimcom is outdated in @dewoller's output, so I guess that Nvim-R is outdated.

**Comment by jalvesaq** [comment]
I'm going to merge the changes from the `auto_start` branch into the master branch which should fix the issue.
