### ISSUE TITLE
Error starting Nvim-R

### ISSUE THREAD

**Issue by a-figment** [jalvesaq/Nvim-R#516]
Been a couple days since I've used Nvim-R and now I am unable to start a session using `\rf`. I am seeing a couple of what look to be syntax errors:

`Error detected while processing function StartR[17]..CheckNvimcomVersion[65]..IsDirWritable: E654 Missing delimeter after search pattern: 482`

and a couple of other missing `endifs`. I was able to comment out the lines 

```
if !CheckNvimcomVersion()
    return
endif
```

in `~/.vim/R/common_global.vim` within the `StartR(whatr)` function to get a different set of errors (trailing characters) but it enables R to start at least. However following that there is the `Not ready yet` error, making it not possible to send commands to R from vim as normal

Running Fedora v31, R verision 3.6.3, with vimx.

**Nvim-R config**
```
let R_app = "radian"
let R_cmd = "R"
let R_bracketed_paste = 1
```

**Comment by jalvesaq** [comment]
The function IsDirWritable no longer exists. You certainly are using an outdated version of Nvim-R.

**Comment by a-figment** [comment]
> The function IsDirWritable no longer exists. You certainly are using an outdated version of Nvim-R.

Thanks. Will need to look later; I uninstalled and and tried re-installing with Plug as per the readme, but plug is unable to access the repo.
