### ISSUE TITLE
List of tags for R functions

### ISSUE THREAD

**Issue by paulrougieux** [jalvesaq/Nvim-R#517]
I like to have a list of functions to navigate the few scripts I'm currently editing in a package. For python code, I have been successfully displaying such a list using the taglist plugin. I managed to build tag files as explained in `:help RBuildTags` .

However the taglist plugin doesn't work with R code and the generated ctags files aren't recognise by the taglist plugin. As per http://vim-taglist.sourceforge.net/manual.html

> The taglist plugin doesn't use a tags file stored in disk. For every opened
   file, the taglist plugin invokes the exuberant ctags utility to get the
   list of tags dynamically. The Vim system() function is used to invoke
   exuberant ctags and get the ctags output. This function internally uses a
   temporary file to store the output. This file is deleted after the output
   from the command is read. So you will never see the file that contains the
   output of exuberant ctags.

Is there another way to display a list of the tags generated by `:RBuildTags`  for the buffer currently opened in vim?

**Comment by jalvesaq** [comment]
I'm sorry, but because this is a feature that I don't use I can't work on this issue. I no longer have the spare time that I used to have in the past. However, I can evaluate a pull request if someone does one.

**Comment by paulrougieux** [comment]
Thanks for the comment. This is probably not the right place to ask but I was wondering if there is a nice way to list tags generated by `RbuildTags`. I found this [2017 post](https://tinyheero.github.io/2017/05/13/r-vim-ctags.html) which explains a way to display a list of R tags with tagbar, however this blog post doesn't use `RbuildTags` and the tagbar plugin doesn't work with external tags files anyway. 

I don't know how to provide a nice list of tags yet. Maybe simply opening the tags file in a buffer is enough to get an overview of all functions in a package anyway.
