### ISSUE TITLE
Sign text conflicts with `ambiwidth="double"`

### ISSUE THREAD

**Issue by mnacamura** [jalvesaq/Nvim-R#518]
If `set ambiwidth=double`, then the following error happens:
```
Error detected while processing /home/mnacamura/.local/share/nvim/site/pack/m
inpac/start/Nvim-R/R/common_global.vim:
line 1272:
E239: Invalid sign text: ▬▶
```
`ambiwidth=double` is often preferred when editing CJK text. It might be better to have fallback ASCII sign texts in that case.

**Comment by jalvesaq** [comment]
Thanks for reporting the issue!
