### ISSUE TITLE
Development documentation not rendered properly

### ISSUE THREAD

**Issue by mllg** [jalvesaq/Nvim-R#519]
Man pages provided via `devtools`/`pkgload` do not render properly anymore. To reproduce, you need to load a package with 

```
pkgload::load_all(path_to_pkg_root)
```

And then `:Rhelp <topic>`.

Problem seems to be that the generated text file (as created by `pkgload::dev_help()` and `pkgload:::print.dev_topic()` / `tools::Rd2txt()`) contains escape sequences. An example for such a file is attached (note that I had to change the file extension from ".text" to ".txt" for Github).

[Rtxt555e1af4c785.txt](https://github.com/jalvesaq/Nvim-R/files/4889108/Rtxt555e1af4c785.txt)

Let me know if you need more information.

**Comment by jalvesaq** [comment]
I can replicate the issue with the command above and the bug should be fixed in the next commit.
