### ISSUE TITLE
restore size of windows

### ISSUE THREAD

**Issue by sesselastronaut** [jalvesaq/Nvim-R#52]
Hope this is the right channel for issue like this: When I open a help in R and close it, the object window holding the R console all of a sudden is taking half of the window size in comparison to the 1/3 set up. I was wondering if there's a way to restore the windows to the initial sizes before the opening of the help file. This occurs on linux running nvim in terminal.

**Comment by jalvesaq** [comment]
Please, see https://github.com/jalvesaq/Nvim-R/issues/33

**Comment by sesselastronaut** [comment]
thanks! the :set winheight=37 command does the resize to my liking

**Comment by jalvesaq** [comment]
Nvim-R is being superseded by R.nvim, a new project that will be inaugurated in a week at the [R-nvim](https://github.com/R-nvim) organization.
Please, check out [tmp-Nvim-R](https://github.com/jalvesaq/tmp-R-Nvim) and help us to find the last remaining bugs before R.nvim inauguration.
When the project is officially started, you will be able to open issues there and request new features.

Nvim-R will remain alive as a feature-frozen project for Vim users. If you want to know the reason, please, see [this discussion](https://github.com/jalvesaq/Nvim-R/discussions/797).
