### ISSUE TITLE
Nvimcom without Rtools on Windows?

### ISSUE THREAD

**Issue by Figuera** [jalvesaq/Nvim-R#520]
Is it possible to install nvimcom without Rtools on Windows?

Rtools is quite heavy and it is mostly composed of mingw packages. Considering that I am already using MSYS2 for other purposes, can't Nvim-R uses the gcc compiler from MSYS2 instead of Rtools?

I tried installing and got:

```
"c:/rtools40/mingw64/bin/"gcc  -I"L:/Programs/R/R-4.0.2/include" -DNDEBUG       -D`L:/Programs/R/R-4.0.2/bin/R --slave -e 'cat(Sys.info()[[1]])'` -DLWS_NO_FORK  -DWIN32   -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c nvimcom.c -o nvimcom.o
/bin/sh: c:/rtools40/mingw64/bin/gcc: No such file or directory
```

MSYS2's gcc is on my PATH but Nvim-R is specifically looking for Rtools' compiler. Why is that the case?

**Comment by Figuera** [comment]
Just notice that R always ignores my MSYS's compiler in favor of the Rtools one, even if the latter is not available. Therefore I give up hope on having this resolved the way I wanted.

**Comment by jalvesaq** [comment]
What version of Nvim-R are you using? Nvim-R no longer looks for Rtools, and R should use whatever `gcc` and `make` that are in the `PATH`.

**Comment by Figuera** [comment]
Turns out that `C:\Program Files\R\VERSION\etc\x64\Makeconf` defines a env variable called `BINPREF` that points to the Rtools bin folder. Changing this variable to point to MSYS2 bin folder (usually `C:/msys64/mingw64/bin`)  achieves what I desire. But I don't know the consequences yet and will proceed with caution.
