### ISSUE TITLE
Error in omnils file

### ISSUE THREAD

**Issue by typhooncamel** [jalvesaq/Nvim-R#523]
I've been getting an error when loading specific packages:  `[ClientServer] Number of separators: 5 ...B^?) Error in omnils file: surveillance` (for instance, or another package name). The error is mostly inconsequential, except that when using omni completion it sometimes freezes the R session. I am not using any omni completion package here. I don't know whether it's anything in my configuration that is producing this. What I find very confusing is that this happens often, but not always. This is using an external emulator and tmux. Any ideas?

_Update_: This may not even have anything to do with omni completion, sometimes the R session just freezes.

_Update 2_: The R session doesn't freeze, it actually eventually reports `Time to build GlobalEnv omnils [26131604 bytes]: 443455.558000 ms`.

**Comment by jalvesaq** [comment]
Can you identify the package causing the problem? Then, I could install it to try to replicate the issue.

**Comment by jalvesaq** [comment]
Surveillance... I see now.

**Comment by typhooncamel** [comment]
The issue started with surveillance, but I've had it also happen with deSolve now, so I don't think it's specific to surveillance.

**Comment by jalvesaq** [comment]
The bug causing the warning "Number of separators: 5" is fixed now.

**Comment by jalvesaq** [comment]
The big time required to build the GlobalEnv omnils file is probably another issue. The time for this task to be completed on my laptop is about 3.5 seconds when I load a map with more than 5000 polygons. So, I guess that you have a very big object, either a list or an S4 object with thousands of elements each with dozens of elements.

**Comment by typhooncamel** [comment]
Awesome, thank you very much! 

Could be large objects - in at least one of the instances I was working with a big data.table object (half a million rows). Is there a work around to prevent it from doing that in such situations?

**Comment by jalvesaq** [comment]
The number of rows should not matter. The problem would be a big number of columns because each column results in one line more in the omnils file.

**Comment by typhooncamel** [comment]
One of the objects has about 200 columns, would that do it?

**Comment by jalvesaq** [comment]
Currently, nvimcom reads the names of list elements recursively, but the next time that it reads the list of objects it goes one level less deep into the lists if the time to build the omnils file was bigger than 300 milliseconds. I would have to change the algorithm and make it abort the building of the omnils file as soon as a specific time threshold is reached.

One data.frame with 200 columns should have its column names added to the omnils file in less than 1 millisecond.

**Comment by typhooncamel** [comment]
That makes sense to me, I really don't know what's causing the hangup. That's the biggest object I load in this very short script, and I doubt the package loads big objects either. Anyway, thank you for your help, very much appreciated, as always. If I figure anything more out, I'll let you know.

**Comment by typhooncamel** [comment]
OK, so the mistake might have been that one of the columns was a list of lists, and wasn't supposed to be, so my bad! Sorry for the trouble.

**Comment by jalvesaq** [comment]
Thanks for the feedback!
