### ISSUE TITLE
Pressing <CR> in Insert mode adds magrittr %>% without having set this in init.vim

### ISSUE THREAD

**Issue by anuragnsharma** [jalvesaq/Nvim-R#528]
**ISSUE**
While in insert mode, the `%>%` pipe is added when I hit `<CR>`. I'm unable to find anything in my init.vim file that might have caused this.

**VERSION**
```
:ver
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedant
ic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdia
gnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-85913-1wbgqz6/n
eovim-0.4.3/build/config -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/deps-bui
ld/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include
-I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/include
Compiled by brew@Catalina.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.3/share/nvim"
```
**DETAILS**
When I checked :map! I find this `i  <CR>        *@<Esc>:normal! a %>%<CR>a`

Consequently, other keybindings mapped to `<CR>` such as `<C-M>` also produce the same result.

This issue occurs only when in a .R file with or without the console toggled on.

I tracked the location of the command using `:verbose imap <CR>` which gave `Last set from ~/.local/share/nvim/view/~=+random.R=1.vim line 161`. I tried editing the file by either deleting or commenting out the line 161 which reads `inoremap <buffer> ^V^M ^V^[:normal! a %>%^V^Ma` however each time even though the save is successful, if I open a new .R file, `<CR>` again produces a `%>%` and upon reopening `~/.local/share/nvim/view/~=+random.R=1.vim`, line 161 is restored. I've tried editing with nano, vim, nvim and plain old TextEdit to no avail.

Additionally, the file `~/.local/share/nvim/view/~=+random.R=1.vim` was created at the same time as when I first installed NeoVim and configured Vim-R.

**Comment by anuragnsharma** [comment]
Out of frustration, I reinstalled the entire set up thrice to no avail. On the fourth try, having deleted every single file from all previous installations, the issue did not reappear, so closing for now.

**Comment by jalvesaq** [comment]
If you go Nvim-R directory and do `grep -R '%>%'` you will see that the string `%>%` appears only in the function that sends lines to R Console: if the line ends with `%>%`, the next line is sent too. So, Nvim-R does not map `<CR>` to `%>%`.

Does the discussion below help?

https://www.reddit.com/r/neovim/comments/b5pjxk/whats_the_purpose_of_the_folder/

**Comment by anuragnsharma** [comment]
Yes indeed. This is very very helpful as I use the linked piece of code to save my code-foldings. I will make the necessary changes.
