### ISSUE TITLE
Support for running arbitrary R commands (for unit testing)?

### ISSUE THREAD

**Issue by Aehmlo** [jalvesaq/Nvim-R#529]
I suspect this is something that `Nvim-R` already supports or that can be hacked in, but after perusing the documentation, I'm at a loss for how to pull it off. I'd like to have a key binding, something like `<LocalLeader>rt`, to execute `devtools::test()` (or whatever) in the attached R session. Is this something that's supported?

**Comment by jalvesaq** [comment]
It's in the section _Custom key bindings_. What you want is either:

```
nmap <silent> <LocalLeader>rt :call RAction("devtools::test")<CR>
```

or 

```
   map <silent> <LocalLeader>s :call g:SendCmdToR("devtools::test()")<CR>
```

**Comment by Aehmlo** [comment]
Ah, I had totally missed `RAction`; thank you!
