### ISSUE TITLE
Unknown function termopen in Vim

### ISSUE THREAD

**Issue by kazougen** [jalvesaq/Nvim-R#53]
I'm currently using Vim on ubuntu 14.04. I also compile Vim from source to satisfy the dependencies. But when I started R by using \rf the following errors shown on

>```
 Error detected while processing function StartR[88]..StartR_Neovim:
> line   28:
> E117: Unknown function: termopen
> E15: Invalid expression: termopen(g:rplugin_R . " " . join(g:rplugin_r_args), {'on_exit': function('ROnJobExit')})
> line   43:
> E492: Not an editor command:         tnoremap <buffer> <Esc> <C-\><C-n>
> line   45:
> E216: No such group or event: TermClose <buffer> call OnTermClose()
> The package nvimcom wasn't loaded yet.

```

**Comment by jalvesaq** [comment]
The error that you reported should never happen due to the following code in R/common_global.vim:
```
call RSetDefaultValue("g:R_in_buffer",         1)
if !exists("*termopen")
    let g:R_in_buffer = 0
endif
```
That is, if the function `termopen` does not exist, `R_in_buffer` is turned zero regardless of its previous value. And the code that resulted in the reported error is sourced only if `R_in_buffer` is not zero (also in R/common_global.vim):
```
if g:R_in_buffer
    runtime R/nvimbuffer.vim
endif
```
Could you, please, completely uninstall the plugin, making sure that all files were really deleted, and, then, install it again?

**Comment by kazougen** [comment]
> Could you, please, completely uninstall the plugin, making sure that all files were really deleted, and, then, install it again?
I installed it again, and it didn't work with the same errors. Im sure that the old files were completely uninstall
p/s: I used pathogen to install and removed the submodule using git commands.

**Comment by jalvesaq** [comment]
Sorry, but I can't reproduce the bug and I have no idea of what might be causing the problem. I suggest that you try to replace pathogen with vim-plug because you are not the first person to report problems with pathogen.

**Comment by kazougen** [comment]
I have checked the code manually, the code runs fine and there aren't problems with Pathogen. I find out that `R_in_buffer` is assigned to `1` because of those following code in R/tmux.vim
```
if !executable('tmux')
    let g:R_in_buffer = 1
    let g:R_tmux_ob = 0
    finish
endif
```
Those code let the process run R/nvimbuffer.vim which is fail
After that, I reassign `R_in_buffer` to zero, start R again and new errors shown up

> Error detected while processing function StartR:
> line  116:
> E117: Unknown function: StartR_ExternalTerm

I don't have time to check that error. Just post here for any fix.

**Comment by jalvesaq** [comment]
Thanks for locating the bug! I'm going to fix it now.
