### ISSUE TITLE
revisting Error in omnils file

### ISSUE THREAD

**Issue by srearl** [jalvesaq/Nvim-R#530]
Wonderful, wonderful plugin, thank you so very much!

I have been getting a warning when loading a particular package: `[ClientServer] Number of separators: 5 (%@%^F^C^F^Fcapeml^F['<94>&^Lm<ca>^?) Error in omnils file: capeml`. This seems nearly identical to what @typhooncamel had reported in https://github.com/jalvesaq/Nvim-R/issues/523. The offending package is [capeml](https://github.com/CAPLTER/capeml). Thus far, I see the warning only with that package. As far as I can tell, though, nothing seems to break, and the package functions work fine despite the warning. To be sure, I wrote the capeml package so the problem could be related to it rather than Nvim-R but I am not sure how to being troubleshooting the problem. Thanks for any insight.

environment:
- Ubuntu 20.04.1 LTS
- R version 4.0.2 (2020-06-22)
- NVIM v0.4.3

**Comment by jalvesaq** [comment]
I installed the capeml package, but I don't get any error message when I load it.

**Comment by srearl** [comment]
@jalvesaq Thank you for looking into it. I am at a loss. Since neither the capeml package or Nvim-R functionality seem to be compromised, I will not worry about it and just ignore the warning. Thanks again for your time (and the plugin!).
