### ISSUE TITLE
Open R-buffer in terminal mode

### ISSUE THREAD

**Issue by tlhenvironment** [jalvesaq/Nvim-R#531]
Thanks a lot for the great plugin!
When shifting between the vim editor and the R-buffer (which happens a lot during my workflow), is it possible to have the buffer opened in insert mode (terminal mode).
Now, I have to press C-w (move to R-buffer), and then i (to access terminal mode). Can the terminal mode be opened automatically? I feel I missed something in the documentation..

**Comment by jalvesaq** [comment]
Does this help?
https://vi.stackexchange.com/questions/3670/how-to-enter-insert-mode-when-entering-neovim-terminal-pane

**Comment by tlhenvironment** [comment]
Yes, working now. Thanks 👍
