### ISSUE TITLE
Converting the documentation to Github markdown

### ISSUE THREAD

**Issue by jamespeapen** [jalvesaq/Nvim-R#532]
Thanks for a great vim plugin! 

I've been using it for some time and since I read the documentation a lot, I converted it from the text file to separate markdown files to make it easier to read and follow links and see code chunks with syntax highlighting. I have tried to preserve all the references by making links to the relevant sections.

I have it as a wiki on my forked repo <https://github.com/jamespeapen/Nvim-R/wiki> if you'd like to check it out. I think it would be useful to move the documentation to the wiki section of your repo. I can't make a pull request to do that, but you can merge them together as shown by this gist: <https://gist.github.com/larrybotha/10650410>

If you don't want it as a wiki, but as part of the `doc` folder, I can put in a pull request to do that.
Hope this is useful!

**Comment by jalvesaq** [comment]
Thank you for your work!

Is it possible to automatically convert Vim documentation into Markdown or the other way around? If I simply replace the Vim documentation with a Markdown-based wiki, it will be reported as an issue. Example: https://github.com/jalvesaq/vimcmdline/issues/91

So, it will be better if it's possible to maintain one version of the documentation and automatically convert it into the other. But even this would add an extra task to be executed whenever I did any change in the documentation...

**Comment by jamespeapen** [comment]
I wasn't thinking of the wiki as a replacement for the vim documentation; it would just be a web-friendly interface to read the documentation. The vimdoc would still be available to view within vim. 

I don't know of an automatic way to do this, especially since the wiki is treated as a separate repo to the code repo and has multiple pages and links to different sections. However, if it would work for you, I am happy to join the project and regularly make the updates to the wiki whenever there is a change to the vimdoc.

**Comment by jamespeapen** [comment]
Thanks! I'll keep mine in sync with your documentation.
