### ISSUE TITLE
change nvimcom default install path?

### ISSUE THREAD

**Issue by yuejuny** [jalvesaq/Nvim-R#534]
hi all
This is an awesome package. I have been using it for a while. Thank everyone who contributes!
With a new laptop issued by my employer, I encountered this issue. 
",rf" tries to install nvimcom in path C:/Program Files/R/R-4.0.2/library" which I do not have write access. It also suggest an alternative path "C:/users/xxxxx/OneDrive/Documents/R/win-library/4.0". This is a mapped OneDrive folder. But this is not the path I want to install nvimcom. 
My question is how can I specify a path for this?

**Comment by obarisk** [comment]
What's your .libPaths()?

**Comment by yuejuny** [comment]
> What's your .libPaths()?

aha. Now what is going on. The suggested path is the R lib path. thanks.
