### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by anasem** [jalvesaq/Nvim-R#535]
Hello,  

I've noticed for several times after working for a while in a session I get this error message
when this happens, I can't send new commands to the console.

```R
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file '/dev/shm/Nvim-R-anas/Rsource-2096949': Too many open files
```

**Comment by jalvesaq** [comment]
I looked at `R/nvimcom/src/nvimcom.c` and couldn't find any `fopen` without the corresponding `fclose`. So, I don't know what might be causing the bug.

**Comment by anasem** [comment]
It's strange
if I do
`lsof | awk '{print $1}' | sort | uniq -c | sort -r | head` I find tens of sockets  and a  new  open  socket  every time I send  a command to R console.

Here is a snippet of the output of  `ss -tuapn  | grep R`
```
udp   ESTAB      0      0                                 127.0.0.1:35767                           127.0.0.1:10101 users:(("R",pid=723105,fd=65))             
udp   ESTAB      0      0                                 127.0.0.1:35785                           127.0.0.1:10101 users:(("R",pid=723105,fd=46))             
udp   ESTAB      0      0                                 127.0.0.1:52194                           127.0.0.1:10101 users:(("R",pid=723105,fd=120))            
udp   ESTAB      0      0                                 127.0.0.1:52328                           127.0.0.1:10101 users:(("R",pid=723105,fd=44))             
```

**Comment by jalvesaq** [comment]
Thanks for the additional commands. I can replicate the bug now, and I will see how to close the TCP connections made by nvimcom.

**Comment by jalvesaq** [comment]
I believe the bug is fixed now. If not, please, reopen the issue.
