### ISSUE TITLE
Should I use this as a R newbie?

### ISSUE THREAD

**Issue by quantum-booty** [jalvesaq/Nvim-R#537]
I just started learning R yesterday, and I am already getting frustrated by the built in vim support of R Studio. After digging around, I found this plugin. So my question is, what are the limitations of this plugin? What important feature would I be missing out? Would using Nvim-R hinder my learning progress? Would you recommend it to a R newbie?

**Comment by jalvesaq** [comment]
This is a personal question. There is no single answer for everyone. You could try both RStudio and Nvim-R and keep using whatever best fits you. If you already have fun using either Vim or Neovim, then you might like Nvim-R.

**Comment by mschilli87** [comment]
I would say being a vim user but R novice you'll have an easier experience with this plugin than RStudio.
I would recommend to also get autocompletion via ncm2 if you miss that from a full blown IDE.
The main 'problems' are that not all macros from RStudio have a matching binding so you might have to actually learn what those do to set them up. But I am not aware of anything important that you could do with RStudio but not with this plugin.

**Comment by quantum-booty** [comment]
Thank you @jalvesaq, I will try both :)
@mschilli87 I can't get ncm2 to work, it looks like it's no longer maintained.
data(iris) <esc> \d <cr>
iris$
and no autocompletion comes up

```

call plug#begin('~/.config/nvim/plugged')
Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'
Plug 'jalvesaq/Nvim-R'
Plug 'gaalcaras/ncm-R'
Plug 'ncm2/ncm2-bufword'
Plug 'ncm2/ncm2-path'
call plug#end()

autocmd BufEnter * call ncm2#enable_for_buffer()    
set completeopt=noinsert,menuone,noselect
```
