### ISSUE TITLE
Error: unexpected symbol

### ISSUE THREAD

**Issue by Tongzhoutz** [jalvesaq/Nvim-R#538]
I have run into such problem when implementing a multiple command, such as "for", "while" etc... 

My code is often like this:

for (s in 1:10) {
      ......
      ......
}

but an error message always pops up after being executed: Error: unexpected '}' in "}". 

I'm pretty sure the code is syntactically correct and give correct outputs. Plus, there is no such problem when it is executed on R studio.

So I was wondering if anyone can shed light on what the possible reason? thanks

**Comment by jranke** [comment]
I remember having a problem with two adjacent tab characters in similar loops... I have not been using tab characters for a long time, so I do not remember what it was.

**Comment by Tongzhoutz** [comment]
> I remember having a problem with two adjacent tab characters in similar loops... I have not been using tab characters for a long time, so I do not remember what it was.

Thanks. I tried to avoid using tabs, but the problem still persists.

**Comment by jalvesaq** [comment]
The message means that an extra `}` was sent to R, but I can't replicate the issue.

**Comment by Tongzhoutz** [comment]
> The message means that an extra `}` was sent to R, but I can't replicate the issue.

Thanks. Maybe it is owing to my local vim settings.
