### ISSUE TITLE
Force R to use existing tmux session

### ISSUE THREAD

**Issue by jimhester** [jalvesaq/Nvim-R#54]
I have been using the Vim-R-Plugin with homebrew vim within a tmux session on OS X and wanted to preserve the existing behavior. Namely the R session starts within the tmux session rather than in a new window.

After combing through the docs I eventually found setting `let g:R_tmux_split = 1` in my `.vimrc` did what I wanted.

I am not sure if this setup is common enough to document, but I wanted to document the problem and solution in case others have the same issue.

If you don't feel any further documentation is needed this can be closed as I have a resolution.

**Comment by jalvesaq** [comment]
My goal is to incentive the use of Neovim because its setup is simpler for new users. If using Neovim and running R in a Neovim buffer, the plugin will depend only on R, which is an obvious dependency. No special configuration is required in the vimrc, bashrc, Rprofile or tmux.conf. The option `R_tmux_split` is in the *FAQ* section because if it was in the *Options* section I would have to bring all the complication from Vim-R-plugin *Installation* and *Use* sections to Nvim-R.

We may let this issue open for some weeks because Vim-R-plugin users will find it useful.

**Comment by mccurdyc** [comment]
@jimhester @jalvesaq would you be willing to help me preserve the behavior of the Vim-R-Plugin on OS X?
I would prefer to have R open in another Tmux pane instead of its own window.

I have tried setting `let g:R_tmux_split = 1` in my `.vimrc` but now I am receiving the error:

```Error detected while processing function StartR:                                                                                                                                                                                      
line  119:                                                                                                                                                                                                                            
E117: Unknown function: StartR_TmuxSplit ```

**Comment by mccurdyc** [comment]
If I remove the `let g:R_tmux_split = 1` from my `.vimrc`, R starts as expected, but in a new window.

I am running tmux version 2.1 and a custom-built Vim 7.4 with `+channel +conceal +job` enabled.

**Comment by jalvesaq** [comment]
Are you sure that you do not have old files in your .vim directory? The file R/tmux_split.vim will not be completely sourced (and, consequently, the function `StartR_TmuxSplit` will not be defined) if the function `TmuxActivePane` is already defined. If you do this
```
cd ~/.vim
grep -R 'function TmuxActivePane'
```
the searched string should be found in only one script (R/tmux_split.vim).

**Comment by mccurdyc** [comment]
After `grep`ping the `.vim` directory this was the only file to contain this function declaration.

``` ~/.vim grep -rnw "." -e 'function TmuxActivePane'
./plugged/Nvim-R/R/tmux_split.vim:7:function TmuxActivePane()
~/.vim ```

**Comment by mccurdyc** [comment]
I even tried installing Nvim-R as a Vimball file (version 0.9.3) and removing and cleaning the plugged version.

**Comment by jalvesaq** [comment]
On Ubuntu 16.04, if Vim is already running in a Tmux session, `\rf` starts R in a Tmux split pane. I tested with this minimal vimrc:

```vim
set nocompatible
call plug#begin('~/.config/nvim/plugged')
Plug 'jalvesaq/Nvim-R'
call plug#end()
filetype plugin indent on
syntax on
let R_tmux_split = 1
```

**Comment by mccurdyc** [comment]
@jalvesaq Thank you for all of your help. I found the issue to be this line in my `.vimrc`.

```
set ft = R
```

**Comment by LiNk-NY** [comment]
I had the same problem as Jim. 
I thought it had something to do with Tmux but the `let g:R_tmux_split = 1` in the `.vimrc` fixed it.

**Comment by jalvesaq** [comment]
I installed the development version of Tmux (2.4) and it works with both options `R_tmux_split=0` and `R_tmux_split=1`.

**Comment by LiNk-NY** [comment]
Hi Jakson, 
Thanks for looking into this. I was getting a NvimR "server" error when entering **F2** to connect to R. But it's working reliably now.
