### ISSUE TITLE
R_show_args

### ISSUE THREAD

**Issue by liston** [jalvesaq/Nvim-R#540]
When I open any .R file in neovim, I  get the message 'The option R_show_args' no longer exists.
Is there anything wrong and how can I stop it from appearing.

**Comment by jalvesaq** [comment]
You should remove the `R_show_args` from your vimrc/init.vim because this option to see the arguments of functions in a preview window no longer exists. The arguments are now _always_ shown in a floating window unless you are using an old version of either Vim or Neovim.

**Comment by liston** [comment]
Thank you.
