### ISSUE TITLE
one-line functions

### ISSUE THREAD

**Issue by dseynaev** [jalvesaq/Nvim-R#541]
when using `\ff`with
```
f <- function() { 5 }
```
I get `The function opening brace was not found.`

**Comment by jalvesaq** [comment]
I'm sorry, but I consider this issue not worth fixing. The logic of sending commands in Nvim-R is: either send a single line or send multiple consecutive lines (selected lines, paragraph, marked block, function, or the whole file). A single line function fits in the first category.
