### ISSUE TITLE
Comments get removed when sourcing using `NvimR.selection()`

### ISSUE THREAD

**Issue by LiNk-NY** [jalvesaq/Nvim-R#542]
Hi Jakson, @jalvesaq 
I hope you are well. 
I am wondering why my text inputs have hashtag comments automatically removed when sourced with `NvimR.selection()`.
I need these comments as input to another function.

Example R code:

```r
"
This is a test.

## Important RMarkdown header

End test.
"
```

Unexpected result:

```r
> NvimR.selection()
[1] "\nThis is a test.\n\n\nEnd test.\n"
```

Expected result:

```r
[1] "\nThis is a test.\n\n## Important RMarkdown header\n\nEnd test.\n"
```

Thank you!

**Comment by jalvesaq** [comment]
There is an option for this. Please, look for `R_commented_lines` in Nvim-R's documentation.
