### ISSUE TITLE
Error detected while processing function StartR[17]..CheckNvimcomVersion[65]..IsDirWritable[14]..funct

### ISSUE THREAD

**Issue by Zhu-Justin** [jalvesaq/Nvim-R#544]
Hi there,
Hope you are doing well! Recently, I have been getting the following error when trying to start nvim-R using the \rf keybinding:
```
Error detected while processing function StartR[17]..CheckNvimcomVersion[65]..IsDirWritable[14]..funct
ion StartR[17]..CheckNvimcomVersion[65]..IsDirWritable:
line   13:
E654: missing delimiter after search pattern: 482
Error detected while processing function StartR[17]..CheckNvimcomVersion:
line   65:
E171: Missing :endif
Error detected while processing function StartR:
line   17:
E171: Missing :endif
```
I am running this on Mac OS 10.13.6. What would be the appropriate way to fix this issue? Thank you so much!

**Comment by jalvesaq** [comment]
The function `IsDirWritable` no longer exist. Could you, please, update Nvim-R and try again?

**Comment by Zhu-Justin** [comment]
Thank you jalvesaq, do you know how to update Nvim-R? Thank you again!

**Comment by jalvesaq** [comment]
How did you install it? You could either uninstall and install it again or simply install it again.

**Comment by Zhu-Justin** [comment]
Thank you jalvesaq, I am currently using Vundle to install it
Plugin 'jalvesaq/Nvim-R'

**Comment by jalvesaq** [comment]
I use [vim-plug](https://github.com/junegunn/vim-plug), and I have to run the command `:PlugUpdate`. Vundle might have a similar command.

**Comment by Zhu-Justin** [comment]
Thank you jalvesaq! I was able to solve this issue by doing the following:
1. Remove `Plugin 'jalvesaq/Nvim-R'` from my .vimrc
2. Run `PluginUpdate`
3. Add `Plugin 'jalvesaq/Nvim-R'` to my .vimrc
4. Run `PluginUpdate`

This should work for anybody who needs to update using Vundle!

**Comment by jalvesaq** [comment]
Thanks for the feedback!
