### ISSUE TITLE
The appropriate place to change the mapping of backtick for rmd file?

### ISSUE THREAD

**Issue by chunyunma** [jalvesaq/Nvim-R#546]
I recently installed Nvim-R and have been exploring its many features.
This morning, I stumbled upon the mapping for backtick, which is to produce a chunk head.
I understand that this mapping would only occur at the beginning of a paragraph, 
so I can still use inline code such as "... the average is  \`r mean %>% round(2)\`."
However, I still anticipate a scenario where I might need a single pair of backticks
at the beginning of a paragraph.
I would like to change the current mapping from a single backtick to a double backtick.
I have located where the mapping was set:
/Users/chunyun/.local/share/nvim/plugged/Nvim-R/ftplugin/rmd_nvimr.vim

```
inoremap <buffer><silent> ` <Esc>:call RWriteRmdChunk()<CR>a  #line23
```

Can I change this line to 
```
inoremap <buffer><silent> `` <Esc>:call RWriteRmdChunk()<CR>a
```
with a double backtick?

Or is there a more appropriate place to make this happen, for example, my config file? 
I feel a bit uneasy about changing directly files that came with the plugin.
I searched throughout the documentation for Nvim-R 
but could not find any mentioning.

Thanks a bunch!

**Comment by jalvesaq** [comment]
If you change the source code you have to take care of keeping your changes during updates of the source code. You could use an autocommand in your `vimrc` to change the map, but I'm going to do a minor change that will allow the `R_rmdchunk` option to be used for this.

**Comment by jalvesaq** [comment]
I believe the issue will be fixed if you update Nvim-R and put this in your vimrc:

```
let R_rmdchunk = '``'
```

**Comment by chunyunma** [comment]
Thank you so much!! 
I noticed that you did not release the updates on the stable branch. 
I assume this was done intentionally. 
I am going to remove `{'branch': 'stable'}` in my config and update Nvim-R.

**Comment by jalvesaq** [comment]
Yes, I only change the stable branch to fix bugs and this issue could better be seen as a lack of feature than a bug.
