### ISSUE TITLE
Object browser shows too much stuff on Libraries

### ISSUE THREAD

**Issue by hinojojojo** [jalvesaq/Nvim-R#547]
Hi,
I recently installed Nvim-R in neovim. In this installation, I noticed that the Library in the object browser shows a lot of stuff under each package. I believe is showing even the methods used by each package, take a look at the screenshot here: 

![nvimR](https://user-images.githubusercontent.com/36875204/96501270-02709080-1205-11eb-9236-879b24c022fd.png)

My previous installations of Nvim-R only showed the functions for each package. How can I change it to show only the functions for each package? I believe this behaviour may be related to the recent changes to the options for configuring Nvim-R. In case its important, this was installed on neovim, and I run it under st terminal, in arch Linux.

**Comment by jalvesaq** [comment]
The change that I could find that caused this difference in behavior was from 2017: https://github.com/jalvesaq/Nvim-R/commit/c924024ece0bd14b44acb508b5a0b654a40921a8 (`R/nvimcom/R/nvim.bol`, lines 345 and 350). We may let this issue open and when I have spare time I can make the Object Browser to hidden objects beginning with a dot in the libraries list when `R_objbr_allnames` = `0`.
