### ISSUE TITLE
Autocomplete error when using Ctrl-p/Ctrl-n

### ISSUE THREAD

**Issue by BertrandSim** [jalvesaq/Nvim-R#548]
In vim 8.1, insert mode completion with Ctrl-p/Ctrl-n gives an error. 

Steps to reproduce:
1. Open a blank r file
2. Type in
``` 
abc
abd
```
3. Start r with `<leader>rf`
4. Trigger omnicompletion in a function. In insert mode, type in `rnorm(` and hit `<C-X><C-O>`
5. `Esc` to stop the omnicompletion
6. Trigger word completion. In insert mode, type in `ab` and hit `<C-P>`

Error message: 
Scanning tags.
Scanning: !Rterm.exe --no-save
match 1 of 3
Error detected while processing function StartFloatWin:
line    8:
E716: Key not present in Dictionary: abd
Error detected while processing function StartFloatWin:
line    8:
E116: Invalid arguments for function deepcopy(s:user_data[v:event['completed_item']['word']])
Error detected while processing function CreateNewFloat[53]..FormatInfo:
line   20:
E715: Dictionary required

I traced this to Commit 28f91f1. 
This was the commit where omnicompletion `<C-X><C-O>` has nice floating windows in vim8.1, which I appreciate.
However, the word completion with `<C-P>` results in an error.

**Comment by jalvesaq** [comment]
I can't replicate the issue in Vim 8.2 on Linux. Could you, please, upgrade Vim? If upgrading Vim fixes the issue, I will change the Vim version requirement to 8.2.

**Comment by BertrandSim** [comment]
Actually, I think I have found a fix. 
The problem is that `s:user_data` in `common_global.vim` does not reset after omnicompletion. 
That is, after step 5, `s:user_data` was not reset to `{}`.
In step 6, s:user_data still contains information about the rnorm function. Since there is no abd in this dictionary, the error results.

I'll propose a small change in a PR

**Comment by jalvesaq** [comment]
Thanks for fixing the bug!

**Comment by BertrandSim** [comment]
You're welcome. And thanks for this great plugin :)
