### ISSUE TITLE
R markdown

### ISSUE THREAD

**Issue by etheleon** [jalvesaq/Nvim-R#55]
Hi, the syntax highlighting for R markdown is not working. 

and i can send code from outside the triple backtick braces. any idea how can i fix this?

**Comment by jalvesaq** [comment]
What specifically is not working? The syntax highlighting looks like normal to me here, and I can't send code from outside R chunks.

**Comment by jalvesaq** [comment]
Can someone confirm the issue? Otherwise, I will close it.

**Comment by EmilRehnberg** [comment]
I am also having issues with the highlighting of R code blocks:
![0028-04-19 9 15 57](https://cloud.githubusercontent.com/assets/2344965/14624682/750df350-060f-11e6-9b4f-802e00569a02.png)

**Comment by EmilRehnberg** [comment]
@jalvesaq please let me know if there's any information that I can forward to make sense of this.

**Comment by jalvesaq** [comment]
I have seen a markdown plugin that does this. Do you have any markdown plugin installed?

**Comment by EmilRehnberg** [comment]
Removing the markdown plugin did the trick.
Thank you very much @jalvesaq !
