### ISSUE TITLE
Object Browser, named elements, reserved keywords

### ISSUE THREAD

**Issue by BertrandSim** [jalvesaq/Nvim-R#550]
If a list (or a data.frame) has elements (or columns) whose names are reserved keywords in R (such as "if", "for", "next", etc.), pressing `<CR>` on those elements in the object browser produces an error. 

Steps to reproduce:
1. Start R with `\rf`
2. In the R console, enter
```
lis <- list(1)
names(lis) <- "next"
```
3. Open the object browser with `\ro`
4. In the object browser, expand `lis`, by navigating to it, and pressing `<CR>` 
5. Look at the the `str` of "next" by navigating to it, and pressing `<CR>` 

```
Error: unexpected 'next' in "str(lis$next"
```

The command `str(lis$next)` is sent to the command line. 
But "next" is a reserved keyword in R, and thus should be surrounded in backticks.
ie., the command should be ``str(lis$`next`)``.

(FYI, The full list of reserved keywords can be found in `?Reserved`)

**Comment by jalvesaq** [comment]
Thanks for reporting the bug and helping to find the solution!

**Comment by BertrandSim** [comment]
The new commit works well. Thanks for the quick implementation :)
