### ISSUE TITLE
Omni-completion crashes and the problem is reproducable (Different situation from #288)

### ISSUE THREAD

**Issue by ttbond** [jalvesaq/Nvim-R#552]
Hello! The problem is that nvim-R has no response (can't use RDSendLine or RDSendSelection) after using CTRL-O to complete the name of the variant and this always happend in the situation that I use names() to index a vector (with length greater than 100 thousand). But, different from the problem mentioned in #288, the CPU usage is always 100%.

**Comment by jalvesaq** [comment]
Could you, please, provide a reproducible example?

**Comment by jalvesaq** [comment]
I could replicate with

```
xxxx <- 1:910000
xxxx <- as.list(xxxx)
names(xxxx) <- paste0("a", as.character(xxxx))
```

Then, when I try to complete `xxxx$` the CPU stays on 100%. Omnicompletion doesn't crash. It just doesn't wait for the reply which is taking too long to return. Then, as you described, I can no longer send commands to R.

**Comment by ttbond** [comment]
Thank you for your prompt reply and sorry about the incomplete infomation before. Because I'm not sure where the problem exactly comes from, I just saved the workspace where the problem happened. But It seems that you have figured it out. That's exactly my problem.

**Comment by ttbond** [comment]
Wait a moment! The problem not only happened when you try to complete xxxx$ and whatevet you tried to complete, the problem happened. If necessary, I can send my worksapce to you. Thanks.

**Comment by jalvesaq** [comment]
When we try to complete anything, nvimcom tries to build the complete list of objects. But, because R' workspace has hundreds of thousands of objects (or elements within objects) the buffer with the list of objects grows immensely, and the function `strlen` in line 351 of nvimcom.c takes too long to run.

I could note this by running R within gdb and killing R when the CPU is on 100%.

**Comment by ttbond** [comment]
Thank you~ I will try to avoid using ctrl-o after index with names().

**Comment by jalvesaq** [comment]
I will try to fix the issue. Thanks for reporting it.

**Comment by jalvesaq** [comment]
The last commit has made `nvimcom_glbnv_line` faster because `strlen` is no longer called with the entire buffer as the argument. I guess that you can go beyond the 100 thousand threshold, but the bug is not fixed yet.

**Comment by ttbond** [comment]
Help a lot! Thank you!

**Comment by jalvesaq** [comment]
I limited the number of items in omni completion to 2000. If this is not enough, the next step would be to create an option to disable omni completion.

**Comment by jalvesaq** [comment]
Actually, I don't need to create an option to disable omni completion because an auto command can do it:

```vim
autocmd FileType r set omnifunc=
```
