### ISSUE TITLE
New testthat does not work from inside vim

### ISSUE THREAD

**Issue by mllg** [jalvesaq/Nvim-R#554]
I've observed some confusing behavior regarding testing in parallel with the new testthat version. 

To reproduce, the following steps are required:

1. Checkout https://github.com/r-lib/testthat to have an example package which uses parallel tests
2. Start R and run `testthat::test_local("~/testthat")`

If run from an R session started by nvim-r, all tests are ignored (you should see something like `[ FAIL 0 | WARN 0 | SKIP 0 | PASS 0 ]`). If R is started from the shell OTOH, everything runs as expected (you should see some tests passing/failing).

The environment for the tests does not seem to be set up properly, but I'm unsure how to debug this.

**Comment by jalvesaq** [comment]
I can replicate the issue, but I don't know how to start debugging be the problem.

**Comment by mllg** [comment]
Maybe @gaborcsardi can give some hints or explain why R sessions started via callr might behave differently?

**Comment by gaborcsardi** [comment]
Try running callr sessions manually, e.g. 

```r
rs <- callr::r_session$new()
rs$run(function() Sys.getpid())
rs$call(function() Sys.getpid())
rs$wait()
rs$read()
```

**Comment by gaborcsardi** [comment]
It seems like the working directory of the subprocesses is set to `R` inside the package, I am not sure why. The test suite is supposed to run in `tests/testthat`.

**Comment by gaborcsardi** [comment]
```
let R_nvim_wd = -1
```
fixed it.

**Comment by mllg** [comment]
Thanks Gabor!

**Comment by jalvesaq** [comment]
Thanks @mllg for reporting the issue, and @gaborcsardi for explaining the problem.
I believe the bug is going to be fixed by the next commit.

**Comment by mllg** [comment]
> I believe the bug is going to be fixed by the next commit.

Confirmed. Thanks.
