### ISSUE TITLE
Send above lines does not work in R files, potential key binding issue

### ISSUE THREAD

**Issue by jperales** [jalvesaq/Nvim-R#556]
I use `<Plug>RSendChunkFH` very often in Rmd files. However, I don't find any workaround for .R files. I guessed `<Plug>RSendAboveLines` would be equivalent. But it does not work as expected. Not a single line is sent to the console. I wonder if there is another equivalent, or if I am using it in the wrong way.
I have the impression that my config key binding is not working properly. Several key bindings do not work. Maybe this is the source of my issue here. For instance, `<LocalLeader>su` triggers "Insert mode with deletion of 1 char" since `s` starts that mode, then type "u". Similarly, `<LocaLeader>rf` makes a replacement ("Replace mode") with "f". It looks other important keys in vim interrupt the key bindings. I do some workarounds by remapping them. Do other users have the same problem?

Thanks,
Javier

**Comment by jalvesaq** [comment]
I can't look at this right now, but perhaps @BlueDrink9 could help because he has recently contributed to Nvim-R's mapping system.

**Comment by BlueDrink9** [comment]
I'll see what I can do, but may take a day or two to respond

**Comment by BlueDrink9** [comment]
Have you updated to the latest commit? The leader mappings sound like they may be affected by a recent change, although that is unexpected. See if your binding issues happen on a version of Nvim-R from this time last year?

Regarding sending  chunks in .R files, do you mean sending the current "block" (vim motion `{`)? That should be possible using `<Plug>RSendMotion`, and adding `ap` ('a paragraph' text object) afterwards. Eg `nmap <localleader>fh <Plug>RSendMotion ap` maybe? Or `nmap <localleader>h <Plug>RSendMotion` then use `<localleader>hap`

**Comment by jalvesaq** [comment]
Nvim-R is being superseded by R.nvim, a new project that will be inaugurated in a week at the [R-nvim](https://github.com/R-nvim) organization.
Please, check out [tmp-Nvim-R](https://github.com/jalvesaq/tmp-R-Nvim) and help us to find the last remaining bugs before R.nvim inauguration.
When the project is officially started, you will be able to open issues there and request new features.

Nvim-R will remain alive as a feature-frozen project for Vim users. If you want to know the reason, please, see [this discussion](https://github.com/jalvesaq/Nvim-R/discussions/797).
