### ISSUE TITLE
could not find function "viewdf"

### ISSUE THREAD

**Issue by chunyunma** [jalvesaq/Nvim-R#557]
In the documentation, 
there was an example for mapping `viewdf`: 

```
# 9.21 Create custom mappings for viewing data.frames or matrices

   nmap <silent> <LocalLeader>vl :call RAction("viewdf", ", location='aboveleft vsp'")<CR>
```

I tried to incorporate this in my `vimrc`, 
but received an error 'could not find function "viewdf"'. 

I sense that I am missing something, 
and searched for some clue in the manual, 
but am still at a loss. 
The only relevant information I could find in the manual 
is the builtin function `RViewDF`. 
However, I could not make the connection between "`RViewDF`" and "`viewdf`". 

Any help would be greatly appreciated!

**Comment by matsburg** [comment]
Some things have been renamed since that documentation was written, so the way to do that now would be:
`nmap <silent> <LocalLeader>vl :call RAction("viewobj", ", howto='aboveleft vsp'")<CR>`
I will open a PR to update the documentation.

**Comment by chunyunma** [comment]
@matsburg 
Thank you so much!  Your fix solved the problem!

**Comment by jalvesaq** [comment]
Thanks for reporting the issue, @chunyunma, and for confirming that it's fixed by @matsburg.
And, @matsburg, thanks for fixing it.
