### ISSUE TITLE
E174: Command already exists: add ! to replace it

### ISSUE THREAD

**Issue by chunyunma** [jalvesaq/Nvim-R#559]
I turned on this feature following the suggestion in the doc: 

```
9.18 Enable the plugin when editing any file type~
>
   command RStart let oldft=&ft | set ft=r | exe 'set ft='.oldft | let b:IsInRCode = function("DefaultIsInRCode") | normal <LocalLeader>rf
<
```

But I received an error "E174: Command already exists: add ! to replace it".

Once I changed `command RStart ...` to `command! RStart ...`, 
the feature started working properly.

**Comment by jalvesaq** [comment]
@chunyunma, maybe you have created the command `:Rstart` elsewhere because it's not created by Nvim-R.

**Comment by chunyunma** [comment]
That's odd ... I cannot find any "RStart" among the output of `:command` other than the setting mentioned above.

**Comment by jalvesaq** [comment]
If you run `grep -R RStart` in Nvim-R's directory, you will see that the string "command RStart" is found only in doc/Nvim-R.txt.

**Comment by chunyunma** [comment]
Thank you very much!  This is what I saw when I ran `grep -wR RStart *` inside Nvim-R's directory: 

```
R/common_global.vim:    call RCreateMaps('nvi', 'RStart',       'rf', ':call StartR("R")')
R/gui_running.vim:    call RCreateMenuItem('nvi', 'Start/Close.Start\ R\ (default)', 'RStart', 'rf', ':call StartR("R")')
doc/Nvim-R.txt:       nmap <buffer> <Leader>sr <Plug>RStart
doc/Nvim-R.txt:       imap <buffer> <Leader>sr <Plug>RStart
doc/Nvim-R.txt:       vmap <buffer> <Leader>sr <Plug>RStart
doc/Nvim-R.txt:   RStart
doc/Nvim-R.txt:   command RStart let oldft=&ft | set ft=r | exe 'set ft='.oldft | let b:IsInRCode = function("DefaultIsInRCode") | normal <LocalLeader>rf
doc/Nvim-R.txt:The above Vim line will create the Normal mode command `:RStart` which when
```

All but the first two are found in `doc/Nvim-R.txt`, as you predicted. 
What should I make of the first two?

**Comment by jalvesaq** [comment]
The first two are not `:command`s. They are aliases for key bindings.

**Comment by jalvesaq** [comment]
You could try running `grep -Rw RStart` in other directories where the command might have been defined, such as `~/.config/nvim`.

**Comment by chunyunma** [comment]
I think I may have found out the reason for the `E174`!!!!
I searched high and low, could not find a second place where I might have defined `RStart`. 
Then re-reading the help documentation of `:command`, 
the second sentence rang a bell:

```
If the command
already exists, an error is reported, unless a ! is
specified, in which case the command is redefined.
There is one exception: When sourcing a script again,
a command that was previously defined in that script
will be silently replaced.
```

It turns out that I have been sourcing the `vimrc` 
every time I make some change to it. 
But if I just leave `command RStart ...` in the `vimrc`, 
restart nvim instead of re-sourcing `vimrc`, 
there will not be an E174!!

This whole time, I have been fighting a non-existent problem. 
I may add back the `!` just so that I can continue to source `vimrc` 
whenever I make changes it. 
But now I know why I need that `!`.

Thank you again for your patience and help!

**Comment by jalvesaq** [comment]
Thanks for the feedback!
