### ISSUE TITLE
Replicate Rstudio's "Install and Restart" button?

### ISSUE THREAD

**Issue by Freguglia** [jalvesaq/Nvim-R#562]
Hello, I have started using the plugin a while ago and it completely redefined my workflow in R, but I'm still having trouble with one specific feature from Rstudio that I'm unable to replicate using Nvim-R.

When developing a package, I tend to have an R session running with examples that I use to test the functions I'm writing. Whenever I make changes to the source code of the package, Rstudio's `Install and Restart` button reinstalls the package and restarts the R session (keeping the same global environment) and reloads the package.

I was able to replicate the install part from an arbitrary file in the source code, e.g., find where is the package root folder, run `Rcpp::compileAttributes()` and `R CMD INSTALL`.

Is it possible to restart the R session keeping the Global Environment from Nvim-R?

**Comment by Freguglia** [comment]
I'm able to reload the package with 
```
command! RReload execute printf(":RSend detach('package:%s', unload = TRUE); library(%s)", fnamemodify(getcwd(), ':t'), fnamemodify(getcwd(), ':t'))
```
given that vim's working directory is the package root folder. It does not replicate Rstudio's button exactly, but it is enough for my workflow. I wonder if there is a less hacky and more elegant way of achieving that. I might add some kind of check if the current working directory is really an R package later.

**Comment by jalvesaq** [comment]
I have developed three R packages in the past (descr, colorout, and DataEntry), but they are already stable and I no longer develop any package R. So, I don't plan to add support for the development of R packages because it would be too laborious for me to maintain them. However, the [vim-devtools-plugin](https://github.com/mllg/vim-devtools-plugin) could be helpful to you.
