### ISSUE TITLE
unable to start data viewer (linux)

### ISSUE THREAD

**Issue by cmoralesmx** [jalvesaq/Nvim-R#563]
Hello, I followed the installation instructions, most of the essential functionality seem to be working. I can,  
- use the key bindings to start the R terminal inside nvim
- use the object browser
- get omni completion as I type
- send code from the vim buffer to the R terminal  

However, evey time I try to view a CSV file or a dataframe, I get the error
```
Error in .External2(C_dataviewer, x, title) : unable to start data viewer
```
I have tried the following settings independently but without success,
```vim
let R_csv_app = 'terminal:vd'
let R_csv_app = 'tmux new-window vd'
let R_df_viewer = 'terminal:vd'
```
I checked `journalctl` for any hints but nothing gets logged there from this issue.  

I do have `visidata` installed in my system and can use it from the termnal.  

I observe the same behaviour using `Alacrity` and `xfce4-terminal` both using `tmux` or standalone. I am using Arch Linux, xfce4, and R 4.0.3

Any advice please?

**Comment by jalvesaq** [comment]
Are you using Vim or Neovim?

**Comment by cmoralesmx** [comment]
I am using Neovim

**Comment by jalvesaq** [comment]
I could find a bug when the option was
```
let R_csv_app = 'tmux new-window vd'
```
and I have just fixed it.

But the other two work. I can't fix the issue because I can't replicate it.

You could try the full path fo vd:
```
let R_csv_app = 'tmux new-window /usr/bin/vd'
```

**Comment by jalvesaq** [comment]
Note: `R_df_viewer` is supposed to call an R function that will take care of displaying the data. So, the option below is not going to work:

```
let R_df_viewer = 'terminal:vd'

```

The example in the documentation still works if the `relimp` package is installed.

**Comment by jalvesaq** [comment]
Closing because cannot replicate.
