### ISSUE TITLE
custom `R_assign_output`-operator and additional `R_pipe`-operator

### ISSUE THREAD

**Issue by n0542344** [jalvesaq/Nvim-R#564]
Thanks a lot for the great plugin!  Thanks to it I was able to switch from `RStudio` to `nvim` for my development.  But there is a thing I wasn't able to do and I'm unsure if I just didn't understand the documentation or if this functionality isn't implemented.

I'd like to be able to switch the output when using the 'R_assign'-option (I just named this `R_assign_output`, but that name is obviously up to you).  I normally try to have a separate line for (almost) everything, that's why most of my scripts use something similar to the following:

```
varname <-
  something
```

Therefore I'd like to change the output of the `R_assign`-operator from ` <- ` to ` <-<CR>  `.  Is that possible?

In addition I'd like to ask if it is possible to also create an `R_pipe`-operator which would work in a similar way.

**Comment by jalvesaq** [comment]
I have tried to include a new line in the output of R_assign, but the new line doesn't get indented. So, instead of

```
varname <-
    something
```

the result was

```
varname <-
something
```

If I added a single space after the `\n`, it did get indented, but the result was:

```
varname <-
     something
```
That is, it was wrongly indented too (5 spaces instead of 4).
So, it seems that a simple `R_assign_output` option would not work.

**Comment by jalvesaq** [comment]
Nvim-R is being superseded by R.nvim, a new project that will be inaugurated in a week at the [R-nvim](https://github.com/R-nvim) organization.
Please, check out [tmp-Nvim-R](https://github.com/jalvesaq/tmp-R-Nvim) and help us to find the last remaining bugs before R.nvim inauguration.
When the project is officially started, you will be able to open issues there and request new features.

Nvim-R will remain alive as a feature-frozen project for Vim users. If you want to know the reason, please, see [this discussion](https://github.com/jalvesaq/Nvim-R/discussions/797).
