### ISSUE TITLE
don't move cursor to R's terminal when send line in debug (browser)

### ISSUE THREAD

**Issue by kklot** [jalvesaq/Nvim-R#568]
As described in the title, is there an option where we can specify this? Currently when `\rl` for example, the cursor moves to the R console, I'd like to have the cursor stays where it is in the source file.

**Comment by jalvesaq** [comment]
Could you, please, try the branch https://github.com/jalvesaq/Nvim-R/tree/rdbg ?
The cursor jumps to R Console only once, when the debugging starts, but I can add an option to completely avoid the jump to R Console if you still think it would be better.

**Comment by kklot** [comment]
That's quick! I tried reinstalling
```
Plug 'jalvesaq/nvim-r', {'branch': 'rdbg'}
```
and restarted R console (`\rq` and `\rf`) but it still jumps as the previous version.

**Comment by jalvesaq** [comment]
Could you, please, update and try again?

**Comment by jalvesaq** [comment]
You have to put in your vimrc/init.vim:

let R_dbg_jump = 0

**Comment by kklot** [comment]
I think it still jumps 🤔, I had `let R_dbg_jump = 0`

**Comment by jalvesaq** [comment]
It has to jump to the window with the code of the function (line 1395 of common_global.vim) to change the cursor position (line 1396). Then, it jumps back to the original position, whatever it was (line 1408).

If `R_dbg_jump = 1`, then the first jump is to R Console to allow the user to issue commands to inspect the values of variables, and press `<Enter>` to execute the code one line at a time.
