### ISSUE TITLE
A case about maintaing tmux splits

### ISSUE THREAD

**Issue by statquant** [jalvesaq/Nvim-R#569]
Hello, I might be wrong but it seems that starting R in the tmux split window is not possible anymore, am I right ?
If I am then I would to make a case for keeping it, note that I am speaking `vim-8` here, as opposed to `nvim`
If you work on a remote server as opposed to locally it is almost certain that you'll have to use tmux just because you want your session to be persistent. That being said why do I think splitting in a tmux pane is better:

- if you split a vim buffer into 2 windows and `\rf` you'll end up having the terminal on half the window
  
![image](https://user-images.githubusercontent.com/3612473/105606892-b7ca5b80-5d93-11eb-854b-64e1482591a3.png)
granted that you could start R as soon as you open a R file but that's not as good

- am I right that the vim terminal is a mess ? I tried to set up `<C-Up>` and `<C-Down>` to navigate from/to a buffer onto the terminal before realizing that this is incompatible with mapping `<Esc>` to `<C-\><C-n>`.
- When using `nvim-r` the terminal gets messed up when alternating normal-terminal and insert-terminal and sending lines that can result if session being stuck
- `<C-\>n` (replace n by any other key) results in the terminal disappearing

That being said, may thanks for `nvim-r` it is truly amazing

**Comment by jalvesaq** [comment]
Please, read https://github.com/jalvesaq/Nvim-R/blob/master/R/tmux_split.md

**Comment by statquant** [comment]
Ah great, can I PR a mention of this in the docs or is it not in on purpose ?

**Comment by jalvesaq** [comment]
No, because it's no longer maintained.
I will add a note if somebody wants to maintain this functionality at another repository.
