### ISSUE TITLE
Open different versions of R 

### ISSUE THREAD

**Issue by dFenix7** [jalvesaq/Nvim-R#570]
Love this plugin! Am a vim user, but was using ess until I encoutered this plugin. I tried many before and none comes close to this for R integration.

My problem is the following. I would like to use the plugin with different versions of R. In my system I have R, R-doc and R-dev which run either the base version of R, a docker with R or the development version of R. 

I tried to play with :call StartR("R"), but could only open the base R. I tried to change it to :call StartR("R-dev"), but it did not work.

I went through the documentation and could not see any option to do this. Is there something I am missing? 

Thank you very much for the help and for the plugin.

Best,

Evarist

**Comment by jranke** [comment]
Please have a look at #476. Personally, I am using this. 

```" The following is adapted from issue https://github.com/jalvesaq/Nvim-R/issues/476
function StartRdevel()
    let g:R_path = '~/svn/R/r-devel/build/bin'
    call StartR("R-devel")
endfunction

nmap ,rx :call StartRdevel()<CR>
```
Don't know about the documentation though.

**Comment by dFenix7** [comment]
Thank you very much jranke! 

That solves the issue for the R-dev. The R running inside a docker image also works but get the following error messages:
```
Error detected while processing function StartRFromPath[2]..StartR[33]..CheckNvimcomVersion:
line   66:
E484: Can't open file /var/folders/23/zs2zcmxx74q37ymfqs2spl3h0000gp/T/Nvim-R-evaristplanet/libpaths
line   69:
E684: list index out of range: 0
E116: Invalid arguments for function isdirectory(libpaths[0]) && filewritable(libpaths[0]) == 2) && !exists("g:R_remote_tmpdir")
Updating nvimcom... Building lists for omni completion... OK!
Press ENTER or type command to continue
```

I'll try to find a solution. I think Nvim-R is trying to find the path to the R libs which is most likely defined from the host machine and not the docker one. Will see if I can disable that.

For the docker, I created an executable file named R with the following code inside:
```
#!/bin/sh
docker run -i --rm --privileged lvg/r-4.0.3:v1 R --vanilla
```

Thanks a lot, will let you know in case I find a solution

**Comment by jalvesaq** [comment]
Your Nvim-R temporary directory is `/var/folders/23/zs2zcmxx74q37ymfqs2spl3h0000gp/T/Nvim-R-evaristplanet/`.
You could try setting the value of `R_tmp_dir` to a path that actually works.
Maybe section 9.20 of Nvim-R's documentation (_Remote access_) could be useful...

**Comment by dFenix7** [comment]
Thanks for the help

I set the `R_tmp_dir` to a path that exists in both the host and the docker image (it's actually a shared folder between them) but I get the same error message

Will carefully read the _Remote access_ section

**Comment by jalvesaq** [comment]
@dFenix7, each time Nvim-R starts a new version of R it will rebuild all files in the `~/.cache/Nvim-R` directory. This is OK for those like me who only change R versions when a new version is released (about four times a year). For you and @jranke who frequently need to run different versions of R, it might be good to change the value of `R_compldir`, but this has to be done on Vim/Neovim startup (before Nvim-R code is sourced). A conditional value in the `vimrc`/`init.vim` based on the current directory name could do the trick if you always need a specific version of R in a specific directory. Example:

```vim
if expand("%:p") =~ 'my_R_packages'
    let R_compldir = '~/.cache/NvimRdev'
    let R_path = '~/svn/R/r-devel/build/bin'
endif
```

**Comment by LiNk-NY** [comment]
After some testing I was able to set this to the version of R that I want when I press <kbd> F2 </kbd>:
```
let g:R_app=usrhome."/src/svn/r-4-2/R/bin/R"
```

**Comment by jalvesaq** [comment]
Nvim-R is being superseded by R.nvim, a new project that will be inaugurated in a week at the [R-nvim](https://github.com/R-nvim) organization.
Please, check out [tmp-Nvim-R](https://github.com/jalvesaq/tmp-R-Nvim) and help us to find the last remaining bugs before R.nvim inauguration.
When the project is officially started, you will be able to open issues there and request new features.

Nvim-R will remain alive as a feature-frozen project for Vim users. If you want to know the reason, please, see [this discussion](https://github.com/jalvesaq/Nvim-R/discussions/797).
