### ISSUE TITLE
Is there a color scheme for light backgrounds?

### ISSUE THREAD

**Issue by nntesla892** [jalvesaq/Nvim-R#573]
It's quite hard to read the light gray and bright green text colors when using a light color scheme. They work fine on dark backgrounds, but on light backgrounds I struggle.

![SC](https://user-images.githubusercontent.com/77494495/107274590-836bc600-6a48-11eb-94c8-0ffb05c522a0.png)

Is there a different color scheme, and if not, is there a way I can change the colors directly?

Thanks.

**Comment by jalvesaq** [comment]
There is no color scheme for light backgrounds, but you can customize the colors.
Please, read section "9.17. Syntax highlight of .Rout files" of Nvim-R documentation.
