### ISSUE TITLE
How to work with vim's `mksession`?

### ISSUE THREAD

**Issue by kklot** [jalvesaq/Nvim-R#574]
I'd like to be able to start vim from saved session created with `mksession`. 

Currently, when we save a session with Nvim-R running, reopening that will recover the same layout including an R instance. But Nvim-R would not recognise that R started by vim.

**Comment by jalvesaq** [comment]
Please, see session "5.5. R must be started by Vim" of Nvim-R's documentation. The communication between Neovim/Vim and R depend on some environment variables having exactly the same value in both applications. Moreover, both must have their TCP servers running (nclientserver on Neovim and nvimcom on R) and both must know the TCP port of each other.

That is, although not impossible, it would not be easy to make `mksession` to work.

**Comment by SoaresAlisson** [comment]
I didn't try it yet, but maybe this plugin can be an alternative solution to handle multiple files in vim. If it works with Nvim-R, let us know.
https://gitlab.com/nvpm/nvpm 

> I'd like to be able to start vim from saved session created with `mksession`.
> 
> Currently, when we save a session with Nvim-R running, reopening that will recover the same layout including an R instance. But Nvim-R would not recognise that R started by vim.

**Comment by jalvesaq** [comment]
Nvim-R is being superseded by R.nvim, a new project that will be inaugurated in a week at the [R-nvim](https://github.com/R-nvim) organization.
Please, check out [tmp-Nvim-R](https://github.com/jalvesaq/tmp-R-Nvim) and help us to find the last remaining bugs before R.nvim inauguration.
When the project is officially started, you will be able to open issues there and request new features.

Nvim-R will remain alive as a feature-frozen project for Vim users. If you want to know the reason, please, see [this discussion](https://github.com/jalvesaq/Nvim-R/discussions/797).
