### ISSUE TITLE
Nvim-R errors if .vim folder is a symbolic link on Windows

### ISSUE THREAD

**Issue by hongyuanjia** [jalvesaq/Nvim-R#576]
I encountered a problem recently when resetting my vim setup on a Windows PC.

My `$HOME/.vim` folder is a symbolic link to the `.vim` folder in my Dropbox. Nvim-R failed to start with error messages saying that:

```
Nvim-R is installed in more than one place
```

listing both the symbolic link (`$HOME/.vim`) and also the `.vim` folder in my Dropbox. This seems to be related to

https://github.com/jalvesaq/Nvim-R/blob/4a14da13b8cf4d850ab287e07e179a436b0b972b/R/common_global.vim#L4346-L4348

But I didn't know what was the root reason for this. Any insights?

**Comment by jalvesaq** [comment]
I didn't know that Windows also has symbolic links...

Could you do the opposite: make your `.vim` folder in your Dropbox a symbolic link to `$HOME/.vim`?
The name of Vim's directory on Windows is not `vimfiles`?

**Comment by hongyuanjia** [comment]
Yea, Windows can make symbolic links using PowerShell.

```powershell
New-Item -ItemType SymbolicLink -Path ~\.vim -Target ~\Dropbox\.vim
```

I have added `set runtimepath^=~/.vim` in my `.vimrc` so that `.vim` folder works.

I will try the opposite to see if it works. I use my Dropbox to backup lots of program settings located in `Documents` and `%APPDATA%`. So that when I reinstall Windows or use another PC, I can use a PowerShell script to make symbolic links to the corresponding folders in Dropbox to recover almost all my preferences. So it would be best if I can stick to the current approach.

Could you explain why the current approach did not work? Thanks!

**Comment by jalvesaq** [comment]
> Could you explain why the current approach did not work?

Unfortunately, I don't know. After adding code that I think might not work on Windows, I start Windows in a virtual machine to check if Nvim-R still works. That's the only time that I "use" Windows.

**Comment by hongyuanjia** [comment]
I can confirm that the opposite works, i.e. make `.vim` folder in my Dropbox a symbolic link to `$HOME/.vim`.

I found that if `$HOME/.vim` is a symbolic link, `&rtp` will include both `$HOME/.vim` and the `.vim` folder in Dropbox. Have no idea on the reason. Will post here if I find more.

**Comment by hongyuanjia** [comment]
*Updates*:
Even though the opposite works, making the `.vim` folder a symbolic link in Dropbox will break version control. That `.vim` folder is under version control using Git with `plugged` (I'm using vim-plug) folder ignored.

I did not have a Linux machine now. When `~/.vim` is a symbolic link, could you tell me if `&rtp` will include both the symbolic link and the resolved path on Linux? If so, it means that the current implementation in Nvim-R will prohibit users to use a symbolic link for `~/.vim`. Otherwise, it is a Windows-specific thing.

**Comment by hongyuanjia** [comment]
I find a temporary solution. Instead of symbolic linking the `.vim` folder in my Dropbox, I make links for all files and folders under `.vim` folder except the `plugged` folder. This time Nvim-R works.

**Comment by jalvesaq** [comment]
On Linux, I renamed `~/.vim` as `vvvv`, created a symbolic link to `vvvv` called `.vim` and everything worked just fine. So, the issue seems to be specific to Windows.

**Comment by jalvesaq** [comment]
I have this in my `init.vim`:
```
call plug#begin('~/.cache/vim-plug')
```
which equivalent, on Windows, would be
```
call plug#begin($APPDATA . '/vim-plug')
```

**Comment by hongyuanjia** [comment]
Thanks for testing.

I have this in my `init.vim`. So I guess if I want to make symbolic links to `.vim`, I should change the plugin folder to somewhere else.
 
```vim
call plug#begin('~/.vim/plugged')
```

Anyway, I am satisfied with the current temporary solution. Thanks for developing Nvim-R. I use it for years. Close the issue now.
