### ISSUE TITLE
channel, conceal and job features in vim

### ISSUE THREAD

**Issue by enricoferrero** [jalvesaq/Nvim-R#58]
I'm trying to migrate to Nvim-R from Vim-R-Plugin.
Unfortunately neovim won't install on my system so I have to use vim.

How can I enable the channel, conceal and job features in vim at compilation time? Google is failing me.

Thanks,
Enrico

**Comment by enricoferrero** [comment]
just compile with `--with-features=huge`

**Comment by yuejuny** [comment]
i compiled using VisualStudio2008 in windows 7. Huge feature is enabled. But I don't see channel feature. See my screen shot. could you please point me to the right direction?
![image](https://cloud.githubusercontent.com/assets/7442131/16959680/3d62b78c-4db4-11e6-9a51-faba94f83a4c.png)

**Comment by jalvesaq** [comment]
Current development version of Vim is 7.4.2072. You are almost 1500 patches behind it.

**Comment by yuejuny** [comment]
@jalvesaq i cloned vim repository this morning.

**Comment by yuejuny** [comment]
@jalvesaq but i think you are right. my version was too old. thank you.

**Comment by yuejuny** [comment]
@jalvesaq `git tal -l ` returns a list like this
v7-4-658
v7-4a
v7-4a-001
...
v7-4b-022

which version I should use to compile?

**Comment by yuejuny** [comment]
:laughing: :coffee: finally figured out. thanks a lot.

**Comment by yuejuny** [comment]
@jalvesaq @enricoferrero I got this message when I tried to start R from vim. How can I get it resolved? :bow: 
> *** arch - i386
> c:/Rtools/mingw_32/bin/gcc  -I"c:/PROGRA~1/R/R-33~1.1/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"  -D`c:/PROGRA~1/R/R-33~1.1/bin/R --slave -e 'cat(Sys.info()[[1]])'` -DLWS_NO_FORK  -DWIN32   -O3 -Wall  -std=gnu99 -mtune=core2 -c nvimcom.c -o nvimcom.o
> Warning message:
> In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
>   there is no package called 'ctv'
> c:/Rtools/mingw_32/bin/gcc -shared -s -static-libgcc -o nvimcom.dll tmp.def nvimcom.o -lWs2_32 -Ld:/Compiler/gcc-4.9.3/local330/lib/i386 -Ld:/Compiler/gcc-4.9.3/local330/lib -Lc:/PROGRA~1/R/R-33~1.1/bin/i386 -lR
> (cd apps; make -f Makefile.win)
> make[1]: Entering directory `/cygdrive/c/Users/i50230/AppData/Local/Temp/RtmpCKShDp/R.INSTALL287c662d4467/nvimcom/src-i386/apps'
> gcc -m32 -mwindows -std=gnu99 -O3 -Wall -DWIN32 nclientserver.c -o nclientserver.exe -lWs2_32
> make[1]: Leaving directory `/cygdrive/c/Users/i50230/AppData/Local/Temp/RtmpCKShDp/R.INSTALL287c662d4467/nvimcom/src-i386/apps'
> installing via 'install.libs.R' to c:/Program Files/R/R-3.3.1/library/nvimcom
> 
> *** arch - x64
> c:/Rtools/mingw_64/bin/gcc  -I"c:/PROGRA~1/R/R-33~1.1/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"  -D`c:/PROGRA~1/R/R-33~1.1/bin/R --slave -e 'cat(Sys.info()[[1]])'` -DLWS_NO_FORK  -DWIN32   -O2 -Wall  -std=gnu99 -mtune=core2 -c nvimcom.c -o nvimcom.o
> Warning message:
> In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
>   there is no package called 'ctv'
> c:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o nvimcom.dll tmp.def nvimcom.o -lWs2_32 -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -Lc:/PROGRA~1/R/R-33~1.1/bin/x64 -lR
> (cd apps; make -f Makefile.win)
> make[1]: Entering directory `/cygdrive/c/Users/i50230/AppData/Local/Temp/RtmpCKShDp/R.INSTALL287c662d4467/nvimcom/src-x64/apps'
> gcc -m64 -mwindows -std=gnu99 -O3 -Wall -DWIN32 nclientserver.c -o nclientserver.exe -lWs2_32
> nclientserver.c:1:0: sorry, unimplemented: 64-bit mode not compiled in
>  #include <stdio.h>
>  ^
> make[1]: *** [nclientserver.exe] Error 1
> make[1]: Leaving directory `/cygdrive/c/Users/i50230/AppData/Local/Temp/RtmpCKShDp/R.INSTALL287c662d4467/nvimcom/src-x64/apps'
> make: *** [nvimapps] Error 2
> Warning: running command 'make -f "Makevars.win" -f "c:/PROGRA~1/R/R-33~1.1/etc/x64/Makeconf" -f "c:/PROGRA~1/R/R-33~1.1/share/make/winshlib.mk" SHLIB="nvimcom.dll" WIN=64 TCLBIN=64 OBJECTS="nvimcom.o"' had status 2
> ERROR: compilation failed for package 'nvimcom'
> * removing 'c:/Program Files/R/R-3.3.1/library/nvimcom'
> * restoring previous 'c:/Program Files/R/R-3.3.1/library/nvimcom'

**Comment by jalvesaq** [comment]
Perhaps you have the same problem reported at https://github.com/jalvesaq/Nvim-R/issues/79

**Comment by yuejuny** [comment]
Yeah. Rtools33 works. Thanks a lot Jakson.
