### ISSUE TITLE
source custom R code defined in vimrc before/after sending code to R.

### ISSUE THREAD

**Issue by she3o** [jalvesaq/Nvim-R#582]
Hi :smile:, I was wondering if there is a way to run a script every time I send code to be sourced (i.e. with `\aa`, `\pp`, etc) 
for example, the following in init.vim
```
let R_run_before_sending = 'tictoc::tic()'
let R_run_after_sending = 'tictoc::toc()'
```
would run a benchmark everytime I send code to R without adding `tic()` and `toc()` everywhere.
This is very similar to defining `.First()` and `.Last()` in `~/.Rprofile`. the only difference is that it would run everytime code is sourced instead of only when starting/quiting R.

In fact, This specific example is why I searched for this feature in the first place but, I imagine it would be helpful in other situations:

### Profiling:
```
let R_run_before_sending = 'Rprof(tmp <- tempfile())'
let R_run_after_sending = 'Rprof(NULL); print(prof.tree::prof.tree(tmp))'
``` 

### Remove objects (say, to ensure a reproducible analysis when running `\aa`):
```
let R_run_before_sending_file = 'rm(list = ls())'
```

### Do whatever `.Last()`/`.First()` do:
```
let R_run_before_sending = '.First()'
let R_run_after_sending = '.Last()'

```
there are probably unlimited ways in which this could be used but I couldn't find something similar in the docs or issues.

**Comment by jalvesaq** [comment]
This feature doesn't exist yet, and I think not that many people would use it routinely. I think it is better to have a "plugin" replacing the current SendToR function and set it to be sourced by `R_source`. While such a plugin doesn't exist, you could try this in your vimrc/init.vim:

```vim
function ToggleTicToc()
    if string(g:SendCmdToR) =~ "SendTicToc"
        let g:SendCmdToR = s:original_func
        echo 'TicToc disabled'
    else
        let s:original_func = g:SendCmdToR
        let g:SendCmdToR = function('SendTicToc')
        echo 'TicToc enabled'
    endif
endfunction

function SendTicToc(...)
    let cmd = 'tictoc::tic(); ' . a:1 . '; tictoc::toc()'
    if a:0 == 2
        return s:original_func(cmd, a:2)
    else
        return s:original_func(cmd)
    endif
endfunction

command RTicToc call ToggleTicToc()
```

Then, you can run the command `:RTicToc` to add/remove the tic and toc commands from the code sent to R.
