### ISSUE TITLE
Error loading 'nvimcom': could not find function "localeToCharset"

### ISSUE THREAD

**Issue by typhooncamel** [jalvesaq/Nvim-R#585]
I have only recently been having this issue (the past couple of days), possibly when updating the plugin. Every time I now try to start R from neovim, an R console opens but immediately get the following error:

```
nvimcom 0.9.112 loaded
Error: package or namespace load failed for 'nvimcom':
 .onAttach failed in attachNamespace() for 'nvimcom', detaills:
  call: localeToCharset()
  error: could not find function "localToCharset"
nvimcom 0.9.112 loaded
```
After which R takes 100% of a CPU and is unresponsive. The only thing I can then appear to do is kill the process. When opening an R session independently of neovim, I seem to be able to load package 'nvimcom' no problem.

Any idea what might be causing this issue? Thanks!

I'm running Ubuntu 20.04, neovim v0.5.0-dev. I usually still run R using this plugin via tmux, but the same issue is there when using the neovim terminal instead.

**Comment by jalvesaq** [comment]
Thanks for reporting the issue. I prefixed `localeToCharset` with `utils::` and should work now.

**Comment by typhooncamel** [comment]
Thank you for such a quick response and solution!
