### ISSUE TITLE
nvim-R Plots within WSL2

### ISSUE THREAD

**Issue by sebffischer** [jalvesaq/Nvim-R#588]
I am not sure whether this is the right place to raise this "issue" but I am runninng into the problem of how to display plots when running nvim-R within WSL2. When simply sending the plot-command to the R terminal, no plots are shown. 

I tried to add 

```
export DISPLAY=:0 
```
to my .zshrc but I am then getting the following error: 

```
Error in .External2(C_X11, d$display, d$width, d$height, d$pointsize,  :
    4   unable to start device X11cairo
``` 

Can this be fixed somehow?

**Comment by jalvesaq** [comment]
I've just searched the meaning of "WSL2"... Does it have a command to start the X Server? If yes, you could put that command in your `~/.Rprofile`.

**Comment by sebffischer** [comment]
Thank you! I found a fix for the problem which is to install the latest WSL preview build that supports gui applications.

**Comment by jalvesaq** [comment]
Thanks for the feedback!
