### ISSUE TITLE
Error building omnils_ file.

### ISSUE THREAD

**Issue by jpasquier** [jalvesaq/Nvim-R#590]
Dear Jackson

Thank you for your plugin. I use it daily for several years in my work.

When I open an R file I get the following message in the command line even before I start R with `<localleader>rf`:

```
Error building omnils_ file. Run :RDebugInfo for details.
```

After starting R, I get this message again when I send a first command. From the second command, the message does not appear again and the plugin seems to work normally.

Here is the output of `:RDebugInfo`:

```
Error running R code                                                                                         
Exit status: 256
Error in library("nvimcom") : there is no package called ‘nvimcom’
Execution halted
R_version
4.0.4
```
This bug appear in the master branch (af730e6) but not in the stable branch (6 commits behind).

Best regards,

Jérôme

**Comment by jalvesaq** [comment]
Thanks for reporting the issue! What is your operating system?

**Comment by jpasquier** [comment]
Debian Bullseye (testing) with neovim 0.4.4

**Comment by jalvesaq** [comment]
I was aware of this bug on Windows, not on Linux. I'm finishing a reorganization of part of Nvim-R's code, but I will work on this issue in a couple of hours.

**Comment by jalvesaq** [comment]
Could you please update and see if the bug remains? While reorganizing the code I fixed some minor bugs.

**Comment by jpasquier** [comment]
The bug remains. I get the same message and the output of `:RDebugInfo` is the same than before.

**Comment by jalvesaq** [comment]
On Windows, the same bug happens because the directory where packages are installed depends on how R is started. It can be a subdirectory of either `~/R`  or `~/Documents/R`. If there is no package installed yet, then this directory will not exist, but Nvim-R would ask:

```
"/usr/local/lib/R/site-library" is not writable. Should "/home/yourlogin/R/x86_64-pc-linux-gnu-library/4.0" be created now? [y/n]
```

This message doesn't appear on Neovim on Windows, possibly due to a redraw issue, but it appears to me on Linux (either nvim 0.4.4 or 0.5.0).

So, I can' replicate the issue, but could you, please, compare the output of `.libPaths()` when R is running directly in the terminal and when it's running in Neovim?

**Comment by jpasquier** [comment]
I have the same paths in the two consoles. Normally, I put the packages in `~/.R` and not `~/R`. To do that, I set `R_LIBS_USER=~/.R/x86_64-pc-linux-gnu-library/4.0` in `~/.Renviron`. Now, if I move the packages in `~/R` and delete `.Renviron`, the bug does not appear.

But it would be nice that Nvim-R supports a custom location for the packages.

**Comment by jalvesaq** [comment]
Thanks. Now I can replicate the issue. The fix is to replace `--vanilla` with `--no-restore --no-save`.

**Comment by jpasquier** [comment]
Works !

Thank you very much.

Best regards
