### ISSUE TITLE
Does not work with neovim 0.5 +

### ISSUE THREAD

**Issue by chunyunma** [jalvesaq/Nvim-R#592]
I have been playing with the neovim nightly build lately. 
This morning, I installed Nvim-R and opened a `test.R`. 
Then I got several error messages:

```
Error detected while processing function ROnJobStdout[8]..UpdateSynRhlist:
line    7:
E117: Unknown function: SourceRFunList
Press ENTER or type command to continue
Error detected while processing function ROnJobStdout[8]..UpdateSynRhlist:
line    7:
E117: Unknown function: SourceRFunList
Press ENTER or type command to continue
Error detected while processing function ROnJobStdout[8]..UpdateSynRhlist:
line    7:
E117: Unknown function: SourceRFunList
Press ENTER or type command to continue
Error detected while processing function ROnJobStdout[8]..UpdateSynRhlist:
line    7:
E117: Unknown function: SourceRFunList
Press ENTER or type command to continue
Error detected while processing function ROnJobStdout[8]..UpdateSynRhlist:
line    7:
E117: Unknown function: SourceRFunList
Press ENTER or type command to continue
Error detected while processing function ROnJobStdout[8]..UpdateSynRhlist:
line    7:
E117: Unknown function: SourceRFunList
Press ENTER or type command to continue
Error detected while processing function ROnJobStdout[8]..UpdateSynRhlist:
line   10:
E117: Unknown function: FunHiOtherBf
```

I have been using Nvim-R for a while with the Neovim stable build. 
In the doc, it only mentioned that Nvim-R requires `Neovim >= 0.4.3`. 
Am I to assume that Nvim-R would only work with a stable version?

Thank you very much!

**Comment by inventionate** [comment]
I discovered similar problems with the latest Neovim nightly. Have you tried the current Nvim-R master branch? This fixed it for me.

**Comment by chunyunma** [comment]
@inventionate  Thank you!  I just tried it. Sadly, the error messages did not go away for me.
For some context, I am on a Mac, and this is what I did:

- Install 
In `$XDG_CONFIG_HOME/nvim/lua/plugins.lua`, add 
`use {'jalvesaq/Nvim-R', branch = 'master'}`

- Config
In `$XDG_CONFIG_HOME/nvim/plugin/nvim-r.vim`, ported from my old `init.vim`

```
" set R path
let R_path = '/Library/Frameworks/R.framework/Versions/Current/Resources/bin'
" Change default to no saving work image and no startup message
" This only affects the behaviour of R inside vim
let R_args = ['--no-save', '--quiet']
" quick insert chunk delimiter in rmd with two instead of one backticks
let R_rmdchunk = '``'
let R_assign = 3
nmap <LocalLeader>: :RSend 
" use visidata to view data frames
let R_csv_app = 'terminal:vd'
nmap <silent> <LocalLeader>vh :call RAction("viewobj", 
	\", howto='topleft 11sp', nrows=5")<CR>
" objects from kniting will not be placed in the global env
let R_rmd_environment = 'new.env()'
" enable commands in insert mode
let R_insert_mode_cmds = 1
" don't set working directory
let R_nvim_wd = -1
" enable nvim-r for any files
command RStart let oldft=&ft | set ft=r | exe 'set ft='.oldft | 
	\let b:IsInRCode = function("DefaultIsInRCode") | normal <LocalLeader>rf
" show help in horizontal split
let R_nvimpager = "horizontal"
```

Interestingly, when I pressed through all the previously mentioned error messages, 
I could still fire up R with `<localleader>rf`, and send commands with `<localleader>l`. 
But some new error messages showed up when nvim-r gets activated.

```
Error detected while processing function ROnJobStdout[8]..SetNvimcomInfo:
line    2:
E716: Key not present in Dictionary: "nvimcom['home'] . '" and "' . a:nvimcomhome . '"')"
Press ENTER or type command to continue
Error detected while processing function ROnJobStdout[8]..SetNvimcomInfo:
line    2:
E116: Invalid arguments for function RWarningMsg
```

I have not tested extensively, but it seems that nvim-r would still function, 
despite these error messages, which will become a nuisance if I want to keep using nvim 0.5+

**Comment by jalvesaq** [comment]
@chunyunma, thanks for reporting the issue. I can replicate it if I put in my init.vim:

```
let r_syntax_fun_pattern = 1
```

I'll fix it.


@inventionate, thanks for the help!

**Comment by chunyunma** [comment]
Thank you so much for the quick fix!

I just updated nvim-r and the error messages were gone when I open `.R` and `.Rmd` files.
However, when I fire up R with `<localledear>rf`, the following error messages still showed up:

```
Error detected while processing function ROnJobStdout[8]..SetNvimcomInfo:
line    2:
E716: Key not present in Dictionary: "nvimcom['home'] . '" and "' . a:nvimcomhome . '"')"
Press ENTER or type command to continue
Error detected while processing function ROnJobStdout[8]..SetNvimcomInfo:
line    2:
E116: Invalid arguments for function RWarningMsg
```

**Comment by jalvesaq** [comment]
@chunyunma, I fixed the other issue, reported in your second comment. Could you, please, update and try again?

**Comment by chunyunma** [comment]
Yay!  Error messages are GONE!
Thank you so much!!!
