### ISSUE TITLE
Error detected while processing function CompleteR

### ISSUE THREAD

**Issue by jpasquier** [jalvesaq/Nvim-R#593]
Dear Jakson,

I encountered the following bug (error message) during omnicompletion:

```
Error detected while processing function CompleteR[67]..GetRArgs[17]..WaitRCompletion[5]..ROnJobStdout:
line    8:
E117: Unknown function: FinishArgsCompletion
Press ENTER or type command to continue
```

Steps to reproduce: 

1) minimal neovim config (with vim-plug installed):

```
syntax on
call plug#begin('~/.local/share/nvim/plugged')
Plug 'jalvesaq/Nvim-R'
call plug#end()
```
2) Open an empty R file and start the plugin

3) Begin to write `mtcars[c("m` and try to complete with C-X C-O

---

I use `lifepillar/vim-mucomplete` which try a buffer word completion after omnicompletion. I wanted to complete the strings in quotes with buffer word completion and not omnicompletion.

Neovim 0.4.4, Debian 11

Best regards,

Jérôme

**Comment by jalvesaq** [comment]
I can't replicate the issue with your minimal vimrc. I get the message "Pattern not found". Maybe this bug was fixed a few hours ago. Could you update Nvim-R and try again?

**Comment by jpasquier** [comment]
Thank you for your response. I updated the plugin and all is working as expected. Sorry for the inconvenience.
