### ISSUE TITLE
AskComplInfo() function not found

### ISSUE THREAD

**Issue by 942kid** [jalvesaq/Nvim-R#595]
After updating to the most recent plugin version, the omni completion function seems to causing some errors with the messages like

> `Error detected while processing CompleteChanged Autocommands for "<buffer=x>"`
> `E117: Unknown function: AskForComplInfo`

It seems to related to the new changes in `common_buffer.vim` below:

https://github.com/jalvesaq/Nvim-R/blob/2710b81da40ee7f04c3cc4bb21b343c23e2fe8d4/R/common_buffer.vim#L18

The float window will appear, but the errors freeze the completion. 

Not sure if it is related to certain completion engine.. For completion, I am using coc.nvim and [coc-r-lsp](https://github.com/neoclide/coc-r-lsp) with the following config in .vimrc:

```
" coc tab configuration
" Use tab for trigger completion with characters ahead and navigate.
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config.
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~ '\s'
endfunction

inoremap <silent><expr> <Tab>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<Tab>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
```

The completion only breaks for `.R` and `.Rmd` files. It works fine for the other file types.

Any hints to resolving the errors would be much appreciated!

**Comment by srearl** [comment]
@942kid - I cannot recall if those were the same error messages but I had trouble with omni completion after updating as well. I also am using CoC. I added the following to my vimrc, which solved the problem (hopefully this will work for you also).

`let R_set_omnifunc = []               " do not use nvim completion (using coc)`

**Comment by 942kid** [comment]
@srearl Adding this line to disable nvim omni completion works like a charm. Thank you so much!
