### ISSUE TITLE
Latest update 275859a throws error in nvim 0.5 +

### ISSUE THREAD

**Issue by chunyunma** [jalvesaq/Nvim-R#597]
Updated Nvim-R today to the latest release on master branch. 
Opened an `.rmd` file and started typing, 
and got the following error messages: 

`Unknown function: AskForComlInfo`
`Unknown function: OnCompleteDone`.

Everything was working fine until I updated Nvim-R an hour ago.
My only guess is that the latest update 275859a had something to do with these errors?

I will try to test it on a clean machine with minimal settings shortly 
and let you know if I get different results. 

Thank you very much!

**Comment by jalvesaq** [comment]
I'm sorry for the regression. I believe it's going to be fixed by the next commit.
