### ISSUE TITLE
CreateNewFloat error during completion with completion-nvim or nvim-compe

### ISSUE THREAD

**Issue by AdrienLeGuillou** [jalvesaq/Nvim-R#599]
When trying to select a completion option with completion-nvim or nvim-compe (with Ctrl-n) I get the following errors:

``` 
Error detected while processing function CreateNewFloat[8]..FormatInfo:
line    2:
E716: Key not present in Dictionary: "cls"
Error detected while processing function CreateNewFloat[8]..FormatInfo:
line    2:
E15: Invalid expression: ud['cls']
Error detected while processing function CreateNewFloat[8]..FormatInfo:
line    5:
E716: Key not present in Dictionary: "cls"
Error detected while processing function CreateNewFloat[8]..FormatInfo:
line    5:
E15: Invalid expression: ud['cls'] == 'a'
E37: No write since last change (add ! to override)
E474: Invalid argument
```

I presume the `CreateNewFloat` is this function : https://github.com/jalvesaq/Nvim-R/blob/6aad7a7cfa07ccd9ae67757dc4493ddd57660553/R/complete.vim#L67

I was able to get the error with this minimal init.vim:

```
"sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
"       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
call plug#begin('~/.vim/plugged')

Plug 'nvim-lua/completion-nvim'
Plug 'neovim/nvim-lspconfig'
Plug 'jalvesaq/Nvim-R', { 'branch': 'stable' }

call plug#end()

colorscheme desert

autocmd BufEnter * lua require'completion'.on_attach()
" Use <Tab> and <S-Tab> to navigate through popup menu
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

" Set completeopt to have a better completion experience
set completeopt=menuone,noinsert,noselect

" Avoid showing message extra message when using completion
set shortmess+=c

lua << EOF
local lspconfig = require'lspconfig'
lspconfig.r_language_server.setup{}
EOF

```

tell me if I can provide more information

**Comment by jalvesaq** [comment]
Since you are using R's `languageserver`, I guess you don't need Nvim-R's omnicompletion. So:

On the stable branch, you could try:

```vim
autocmd FileType r setlocal omnifunc=
```

On the master branch, you could do instead:

```vim
let R_set_omnifunc = []
```

**Comment by jalvesaq** [comment]
I guess I will have to delete the `stable` branch because I can't maintain it. I wish I had time, but I don't.

**Comment by AdrienLeGuillou** [comment]
I switched to the master branch and disabled omnicompletion and it now works like a charm.

Thanks a lot for this great plugin!

**Comment by jalvesaq** [comment]
I had time to look at the problem now and fixed it in both stable and master branches. The fix was the same in both branches. Anyway, you still need to disable Nvim-R's omni completion if you are not going to use it. Indeed, it is better to put this in the `init.vim` because I may enable auto completion by default in the future:

```vim
let R_auto_omni = []
let R_set_omnifunc = []
```
