### ISSUE TITLE
No handy vim-pandoc smart auto-formatting mode in Rmd files

### ISSUE THREAD

**Issue by inventionate** [jalvesaq/Nvim-R#600]
I think this is probably a problem with the rmd ftplugin in combination with vim-pandoc. If I enable vim-pandoc smart formatting by `let g:pandoc#formatting#mode = "hA"` everything works as expected in Rmd files except for the formatting of R code chunks. Unlike all other chunks, e.g. ` ```{python}`, the intelligent formatting remains active, which is why the option in Rmd files makes no sense. Would it be possible to support this very comfortable feature of vim-pandoc also for Rmd files?

In essence, the automatic formatting within the R code chunks should be deactivated (like all other code chunks) and only used for prose.

**Comment by jalvesaq** [comment]
I can't change a feature of another plugin. You have to request the vim-pandoc team to support a chunk delimiter that includes an opening brace. Knitr requires the opening brace and vim-pandoc doesn't recognize it.

For omni completion, Nvim-R sets 'omnifunc' to CompleteR and sets the value of a buffer variable with the name of whatever was the omnifunc. It then calls this function if the completion wasn't triggered in a block of R code. This might work with vim-pandoc because general plugins seems to be sourced before file type plugins. That is, to fix the issue, I would have to create a formatting fuction that would actually call vim-pandoc's function if the cursor was in a region of Markdown code.

**Comment by inventionate** [comment]
Thank you for your fast answer. Are you sure it is because the opening brace? It works fine for all other code chunks including braces, e. g. the python example:

````markdown
In an Rmd file … smart formatting is enabled here

 ```{python}

# No smart formatting


 ```

In an Rmd file … smart formatting is enabled here


 ```{r}

# Smart formatting still enabled

 ```

In an Rmd file … smart formatting is enabled here
````
 
Furthermore, the problem even exists without Nvim-R installed. I assume the neovim built-in rmd ftype is the problem. If I have time I'll try to test it without this.

Of course, I will be happy to contact the maintainers of vim-pandoc if I can identify the problem more precisely. Thank you for your hints!

**Comment by inventionate** [comment]
Yep, I think it has to do with the rmd filetype definition. If I set the filetype to pandoc, the smart formatting works correctly without any change. Can you replicate this?

**Comment by inventionate** [comment]
To clear up a misunderstanding, it has nothing to do with omni completion. It is about the formatting module of vim-pandoc, which does not work correctly for rmd files expecially r chunks. 
There is a function that automatically reformats paragraphs with hard linebreaks when they are changed. So, for example, an intelligent `textwidth=100` and `formatoptions=a`. vim-pandoc recognises code chunks and adjusts these settings so that they are not applied within code chunks and this won't work for r code chunks.

**Comment by inventionate** [comment]
OK, I think I've found the problem. vim-pandoc uses uses highlighting information for smart formatting and r code chunk highlighting groups are overwritten by rmd filetype definition. I don't know where's the best place to fix this. Do you have a suggestions? Many thanks in advance!

**Comment by jalvesaq** [comment]
Maybe they should support the official rmd highlighting groups:
https://github.com/vim/vim/blob/master/runtime/syntax/rmd.vim

**Comment by inventionate** [comment]
I agree and thank you! In the meantime I've fixed it :-)

There is an undocumented variable `g:pandoc#formatting#smart_autoformat_blacklist`. I've added `rmdrChunk`in my .vimrc and it worked. I'll open an issue at vim-pandoc and mention that. For now it seems to work.

Thank you again very much for your super fast help!
