### ISSUE TITLE
last version worked with R 3.6 ?

### ISSUE THREAD

**Issue by comicfans** [jalvesaq/Nvim-R#601]
Hello,  I've updated nvim-R recently but found it doesn't follow source line during debug ,and "R version < 4" warning showed, but due to environment restriction , I can only use R 3.6, I'd like to know which version still worked with old version ? which functional not work if using latest nvim-R ? Thanks

**Comment by jalvesaq** [comment]
R 3.6.0 was released in April, 2019, and Nvim-R's release closest to this date was 0.9.13, but support for debugging functions was introduced in version 0.9.14. So, you could try 0.9.14. Please see: https://github.com/jalvesaq/Nvim-R/releases

**Comment by comicfans** [comment]
> R 3.6.0 was released in April, 2019, and Nvim-R's release closest to this date was 0.9.13, but support for debugging functions was introduced in version 0.9.14. So, you could try 0.9.14. Please see: https://github.com/jalvesaq/Nvim-R/releases

 I've take a try. Thank you
