### ISSUE TITLE
Always bell when sending codes to R in Vim built-in terminal on Windows

### ISSUE THREAD

**Issue by hongyuanjia** [jalvesaq/Nvim-R#603]
If launching R in Vim built-in terminal, whenever I send codes to it, there is a bell sound. This did not happen on Linux. If I directly type R code in that terminal, there is no sound.

I have already set `noerrorbells` and `visualbell`:

```
set noerrorbells
set visualbell t_vb=
au GUIEnter * set visualbell t_vb=
```

Any insights? Thanks!

**Comment by jalvesaq** [comment]
Looking at the code, my only guess is that `R_clear_line` could be causing the bell. Did you set it?

**Comment by hongyuanjia** [comment]
Yes. I set `R_clear_line` to `1`. Resetting it to `0` fixes the issue. Thanks!

**Comment by jalvesaq** [comment]
Thanks for the feedback. Nvim-R's documentation says how to disable the bell only for R, but I don't know if Vim's terminal emulator on Windows reads the `~/.inputrc`.

**Comment by hongyuanjia** [comment]
I just tried that approach by creating `~/.inputrc`, but it did not work.

**Comment by jalvesaq** [comment]
Looking at R's source code (version 4.1.0), it seems that there is no option to control the bell. It's hardcoded to run in Rterm (`src/gnuwin32/getline/getline.c`, lines 426 and 1379) and to not run in Rgui (`src/gnuwin32/rui.c`, line 1195).
