### ISSUE TITLE
Vimdiff folding mixed up when comparing R files

### ISSUE THREAD

**Issue by gjcooper** [jalvesaq/Nvim-R#604]
When I am using vimdiff or git difftool (with vimdiff as the driver) to compare I see the diff load as expected (with identical lines folded away and changes displayed).

After approximately 1 second though if I am viewing R files then one of the two buffers folds the file via the syntax method which I have set up (foldmethod gets changed to syntax from diff it appears). If I change it back to the diff foldmethod then it sticks and can be viewed as expected.

If I am viewing other filetypes (python, javascript etc) I do not get this behaviour.

I've looked through the Nvim-R code to see if I can track down whether it is something being set here, but can't see anywhere that could be causing this and thought I would just reach out to see if you had any ideas.

**Comment by jalvesaq** [comment]
Thanks for reporting the issue. The bug was introduced while fixing https://github.com/jalvesaq/Nvim-R/issues/602.
