### ISSUE TITLE
Warning: 'randint2' not recognized

### ISSUE THREAD

**Issue by BertrandSim** [jalvesaq/Nvim-R#605]
Hi, I just updated this plugin to the latest master branch. When opening an R file, I get the following warning:

> Using insecure communication with R due to failure to get random numbers from nclientserver: 'randint2' is not recognized as an internal or external command, operable program or batch file. 

When I ran git checkout on the latest release (v0.9.16), the warning message disappeared.

I'm using windows gvim 8.1.1424, R 4.0.2

If you require any additional info, I'll be happy to provide them

**Comment by jalvesaq** [comment]
I can't replicate the issue on Windows running in a virtual machine. It has R 4.1.0 installed, and, as expected, the file `randint2.exe` is in the directory `~/Downloads/R/win-library/4.1/nvimcom/bin/x64/`. Do you see anything that seems to be informative with the command `:RDebugInfo`?

**Comment by BertrandSim** [comment]
Hi jalvesaq, I just updated nvimcom, and tried again. 
There was nothing useful in `:RDebuginfo` (it only shows my R_version). I also did not find randint2.exe in the directory you specified.

I tracked down the commits, and the warning message appeared in c48c756.

In particular, here's a detailed breakdown of the messages from the commits between 45b9ea9 (v0.9.16, latest release) and c48c756. 

```
45b9ea9 -- ok
76a8d66 -- ok
346399e -- [ClientServer] Failed to open "C:/Users/Bertrand/AppData/Local/Temp/NvimR-bertrand/libnames_1744520237"
0ad41c2 -- A similar error as 346399e, with '17445..' replaced by a different number
c48c756 -- see below
```

For c48c756, I typed `:set ft=r`, this ran startup scripts for R. Interestingly, my antivirus Bitdefender gave me the following:
```
Item was deleted. Threat name: Gen:Variant.Bulz.213087. Path: C:\Users\Bertrand\AppData\Local\Temp\RtmpWGmXij\R.INSTALLc88409d571b\nvimcom\src\apps\randint2.exe. 
```
followed by the message in vim
```
Using insecure communication with R due to failure to get random numbers from nclientserver: 'randint2' is not recognized as an internal or external command, operable program or batch file. 
```

Could you advise on how to address this?

**Comment by jalvesaq** [comment]
You have to find a way to teach your antivirus that `randint2.exe` should not be deleted.

Nvim-R uses environment variables with random numbers to identify messages as legitimate in its communication with R. Without these random numbers, it's easier for someone else in your network to send commands to be executed by R. But this is only a very remote possibility because Nvim-R will still generate the `NVIMR_ID` and `NVIMR_SECRET` environment variables using the current time, and it will warn of any message received with wrong values for these variables.

**Comment by BertrandSim** [comment]
Thanks for the detailed explanation. 
Yes, it seems I have to find a way to make an exclusion to that in the antivirus software.. It will be difficult though, since random numbers are used in the filepath. 
In any case, thanks again.
