### ISSUE TITLE
hope the Nvim-R can  send the bash shell or python code inside the Rmarkdown to the shell or python interpreter

### ISSUE THREAD

**Issue by ZihaoXingUP** [jalvesaq/Nvim-R#606]
Rmarkdown only can send R code using Nvim-R, I hope the Nvim-R can also send the bash shell or python code inside the Rmarkdown to the shell or python interpreter.

**Comment by jalvesaq** [comment]
I'm sorry, but this is a feature that I don't use. I don't have spare time and it would require too much work to develop something that I possibly would never use. Lastly, I have prefered to have all data manipulation in R (and, much more rarely, in Shell and Python) scripts and only use Markdown to analyse the already manipulated data. I use [vimcmdline](https://github.com/jalvesaq/vimcmdline) to help the development of Shell and Python scripts.

I can accept a pull request, though.

**Comment by jalvesaq** [comment]
[quarto-nvim](https://github.com/quarto-dev/quarto-nvim) can do what you are requesting and we can improve the integration, but not in Nvim-R. Please, see https://github.com/jalvesaq/Nvim-R/discussions

**Comment by jalvesaq** [comment]
Nvim-R is being superseded by R.nvim, a new project that will be inaugurated in a week at the [R-nvim](https://github.com/R-nvim) organization.
Please, check out [tmp-Nvim-R](https://github.com/jalvesaq/tmp-R-Nvim) and help us to find the last remaining bugs before R.nvim inauguration.
When the project is officially started, you will be able to open issues there and request new features.

Nvim-R will remain alive as a feature-frozen project for Vim users.
