### ISSUE TITLE
Error with `ShowRDoc` on macOS

### ISSUE THREAD

**Issue by cwatson** [jalvesaq/Nvim-R#607]
Hi, I'm running vim 8.2 (from Homebrew) on macOS Big Sur 11.2.3.
When I type `\rh` on a function, or type `:Rhelp qnorm`, *even* when I type `?qnorm` in the R terminal, I see the following error:

    E115: Missing quote: 'R Help on `qnorm'')
    E116: Invalid arguments for function ShowRDoc

If I type `:Rhelp 'qnorm'`, I see

    E116: Invalid arguments for function RWarningMsg

However, when I type `:call ShowRDoc('qnorm')`, it works fine.

I'm not sure what's causing this and can provide more info if necessary. Thanks!

**Comment by jalvesaq** [comment]
I don't have access to Mac OS to try replicating the issue.
Does it work in Neovim?
