### ISSUE TITLE
Cannot install nvimcom

### ISSUE THREAD

**Issue by orbitoo** [jalvesaq/Nvim-R#608]
There seems to be an error, and it told me that "make not found" when I tried to start R.
![Screenshot 2021-06-21 173401](https://user-images.githubusercontent.com/86230731/122740776-d6b21880-d273-11eb-8696-1210618e0c48.png)
I thought I'm supposed to install this plugin (or package? I'm not sure.) so I used Rterm to try a second time, and it told me that I can't install this package because it's not available on R 4.1.0.
![Screenshot 2021-06-21 173351](https://user-images.githubusercontent.com/86230731/122741170-36a8bf00-d274-11eb-9e74-cfdc4e85eb6f.png)
However, this plugin was just updated a few days ago, so I'm quite confused and I don't think the error was produced because of this.

**Comment by jalvesaq** [comment]
Did you install [Rtools40](https://cran.r-project.org/bin/windows/Rtools/)?

**Comment by orbitoo** [comment]
> Did you install [Rtools40](https://cran.r-project.org/bin/windows/Rtools/)?

Not yet. I'll try. Thanks for your instant reply.
