### ISSUE TITLE
Visual selection in Nvim-R plugin sends one line too much to terminal

### ISSUE THREAD

**Issue by mwesthues** [jalvesaq/Nvim-R#61]
I have just set up the [Nvim-R](https://github.com/jalvesaq/Nvim-R) plugin for `Neovim` to send lines of code from an `.R`-file opened with `Neovim` to a terminal inside a `tmux` session.

Previously, I have worked with its predecessor [Vim-R](https://github.com/jcfaria/Vim-R-plugin), which is no longer being maintained. 

In the old `Vim-R`, it was easy to send a visually selected block of code to the terminal by pressing the `r` key while in visual mode after adding the following line to my `.vimrc`:

    let g:vimrplugin_map_r = 1

However, this feature seems to be deprecated in the new `Nvim-R`-plugin. As a workaround I have tried to add the following line to my `.vimrc`:

    vmap <Space> <Plug>RDSendSelection 

This actually allows me to send a visually selected section to the terminal, however, it always includes the next non-empty line after the selection, which is irritating. This is especially so, because it even ignores multiple blank lines.

How can I modify this behavior?

**Comment by jalvesaq** [comment]
I can't see this bug here. If I select three lines, only these three lines are sent to R when I press `<Space>`. I can check this by looking in the Object Browser what objects are created.

Note that you can map `r` to send selection:

```
vmap r <Plug>RDSendSelection
```

**Comment by mwesthues** [comment]
Thanks for the mapping advice. That worked and I like it! However, I still have the problem with too many lines being send to the terminal. Would it make sense to post my `.vimrc` or some other configuration file? Maybe I have introduced a conflict somewhere. Sorry for the inconvenience.

**Comment by jalvesaq** [comment]
Yes, you could either post your vimrc here or send it by e-mail to me.

**Comment by Norival** [comment]
Hi!
I have the same problem, the next non-empty line is sent when I try to send a visual selection with the mapping:
`vmap r <Plug>RDSendSelection`
or
`vmap <Space> <Plug>RDSendSelection`

Another problem is that the line under the cursor is sent to the console when I start R (with F2).
Both problems are resolved if I remove:
`nmap <Space> <Plug>RDSendLine`
from my r.vim.

Thanks!

**Comment by jalvesaq** [comment]
I still cannot reproduce the bugs. When I press `r` in Normal mode, the three selected lines are sent and the cursor jumps to the next non-empty line. Starting R with `<F2>` does not send any line. Perhaps you have a very old ftplugin/r.vim in your vim directory or something at after/ftplugin/r.vim or some maps in your vimrc.

**Comment by Norival** [comment]
Thank you for the answer. I've found the solution with the `:map` command. I had:

`no <F2>          <Plug>RStart<Space>`
`v  <Space>      <Plug>RDSendSelection<Space>`

There were trailing spaces at the end of the mappings in my ftplugin/r.vim...

Thank you! Now it works fine.

**Comment by mwesthues** [comment]
I detected the same problem as described by @Norival, namely trailing spaces in my `.vimrc`. Problem solved. Many thanks for this great plugin @jalvesaq!
