### ISSUE TITLE
can the Nvim-R  run the R code inside the html file except R or Rmd file

### ISSUE THREAD

**Issue by ZihaoXingUP** [jalvesaq/Nvim-R#610]
i write some R code inside the html file, i hope the Nvim-R will also can select, send and run the R code inside the html file.

**Comment by jalvesaq** [comment]
Please, see section "9.18 Enable the plugin when editing any file type" in Nvim-R's documentation.

**Comment by ZihaoXingUP** [comment]
> Please, see section "9.18 Enable the plugin when editing any file type" in Nvim-R's documentation.

thanks, i read the documentation and solved this problem

**Comment by jalvesaq** [comment]
Thanks for the feedback.
