### ISSUE TITLE
Attempt to read `version` and `Rversion` from `nvimcom/DESCRIPTION` if present

### ISSUE THREAD

**Issue by hqurve** [jalvesaq/Nvim-R#612]
Hi, I'm trying to package nvim-r for nix and although it works well, there's one little thing which I would prefer.

Upon first run, nvim-r would attempt to build nvimcom. Since in nix, the system R library path is not writable, it would then attempt install it in the home directory. Although it works, I would prefer if such a library is not kept in my home directory.

After some searching, I realized that nvim-r can use the global `g:R_nvimcom_home` to set the location of nvimcom. However, it does not read the version and rversion of it (which are held in `nvimcom/DESCRIPTION`) which causes the `rversion` check in `CheckNvimcomVersion` to fail and request that it be built. Is there any particular reason for this? If there isn't, would it be okay to add the following code to the end of `R/start_ncs.vim`?

```
if exists("g:R_nvimcom_home")
    let nvimcom_home = substitute(g:R_nvimcom_home, '/nvimcom', '', '')
    let s:ncs_path = FindNCSpath(nvimcom_home)

    if s:ncs_path != '' && filereadable(nvimcom_home . '/nvimcom/DESCRIPTION')
        let g:rplugin.nvimcom_info['home'] = nvimcom_home

        let ndesc = readfile(g:rplugin.nvimcom_info['home'] . '/nvimcom/DESCRIPTION')

        let versionline = matchstr(ndesc, '^Version: ')
        if versionline != ''
            let g:rplugin.nvimcom_info['version'] = substitute(versionline, '^Version: ', '', '')
        endif

        let buildinfoline = matchstr(ndesc, '^Built:')
        if buildinfoline != ''
            let rinfo = matchstr(buildinfoline, 'R [.0-9]\+')
            if rinfo != ''
                let g:rplugin.nvimcom_info['Rversion'] = substitute(rinfo, 'R ', '', '')
            endif
        endif
    endif
endif
```

For reference, this is the description file produced when nix builds nvimcom.
```
Package: nvimcom
Version: 0.9-122
Date: 2021-06-06
Title: Intermediate the Communication Between R and Either Neovim or
        Vim
Author: Jakson Aquino
Maintainer: Jakson Alves de Aquino <jalvesaq@gmail.com>
Depends: R (>= 3.0.0)
Suggests: knitr, rmarkdown
Imports: methods, tools
Encoding: UTF-8
Description: Provide a service to intermediate the communication between R and either Neovim or Vim.
License: GPL (>= 2)
URL: https://github.com/jalvesaq/nvimcom
Built: R 4.0.4; x86_64-pc-linux-gnu; 2021-07-25 17:00:57 UTC; unix
```
while this is the description file produced when I let nvim-R build nvimcom locally
```
Package: nvimcom
Version: 0.9-122
Date: 2021-06-06
Title: Intermediate the Communication Between R and Either Neovim or
        Vim
Author: Jakson Aquino
Maintainer: Jakson Alves de Aquino <jalvesaq@gmail.com>
Depends: R (>= 3.0.0)
Suggests: knitr, rmarkdown
Imports: methods, tools
Encoding: UTF-8
Description: Provide a service to intermediate the communication between R and either Neovim or Vim.
License: GPL (>= 2)
URL: https://github.com/jalvesaq/nvimcom
NeedsCompilation: yes
Packaged: 2021-07-24 12:30:27 UTC; hqruve
Built: R 4.0.4; x86_64-pc-linux-gnu; 2021-07-24 12:35:53 UTC; unix
```
I have no idea why the title is wrapped but the description isn't. In either case, for the sake of avoiding possible errors, I used `matchstr` to find the lines starting with `Version` and `Built`

Edit: changed the suggested code after testing

**Comment by jalvesaq** [comment]
I don't use Nvim-R remotely, so I never set the value of `R_nvimcom_home`. I will merge your pull request since it fixes an issue for you and is innocuous for most people, including myself.
