### ISSUE TITLE
The file has no mark!

### ISSUE THREAD

**Issue by codemeleon** [jalvesaq/Nvim-R#614]
Hi,

When I try to execute a code block using `\bb`, I get message "The file has no mark!" without any output.
How can I fix it?

Thank you.

**Comment by codemeleon** [comment]
I was using the command incorrectly.

**Comment by TymekDev** [comment]
What is the correct way to use this command? I cannot seem to make it work.

**Comment by jalvesaq** [comment]
It's a manually _marked_ block of lines, not a block of code. Perhaps we could improve the documentation wording to make this more clear. When sending lines, Nvim-R recognizes a curly brace block and sends it.

**Comment by jalvesaq** [comment]
Consider the code:

```
1
2  x <- 3
3  y <- 2
4
5  z <- x + y
6
```

Go to line 1 and press `ma`. Go to line 6 and press `mb`. Go to line 4 and press `\bb`.

**Comment by TymekDev** [comment]
Thanks for clarification!
