### ISSUE TITLE
Is it possible to render Rmd document "up to cursor" ?

### ISSUE THREAD

**Issue by statquant** [jalvesaq/Nvim-R#615]
Hello, when working on long Rmd files, I often want to be able to call render but only on the document from the top to cursor. 
```
---
---

a

b
    <--- say the cursor is here only the top would be rendered
c

d

```
Would you consider adding this feature, maybe it is already available (I do not find it in the docs though).
If you do not like the idea I assume I could do it by selecting top to cursor, saving in a temp file and run render on this temp file.

Many thanks for the plugin, it's amazing

**Comment by jalvesaq** [comment]
The feature already exists (although I never use it). It's in the list of key bindings (section 4.1 of Nvim-R's documentation): `<LocalLeader>ch`.

**Comment by statquant** [comment]
Sorry but `<mapleader>ch` execute the code of the chunks up to cursor, it does not call render up to cursor. Sorry if I was not clear

**Comment by jalvesaq** [comment]
I will accept a pull request for this if someone writes the code. In the meanwhile, the alternative is to run `<LocalLeader>ch` in the previous chunk and either select or mark the block of code of the current chunk that should be sent.
