### ISSUE TITLE
erro with omni completion ?

### ISSUE THREAD

**Issue by gilles13** [jalvesaq/Nvim-R#616]
Hello,

I have difficulties with omni completion. I have got error when I try to omni complete personnal function, like

myfun <- function(x,y) {
   x+y
}

I use vim 8.2 inside tmux.

Here is my .vimrc config

let R_in_buffer = 0
let R_external_term = 1
let R_synctex = 0
let R_show_arg_help = 0
let R_rconsole_width = 80
let R_min_editor_width = 18
let R_nvimpager = "tab"
let R_pdfviewer = "zathura"
let R_objbr_place = "script,below"
let R_set_omnifunc = ["r",  "rmd", "rnoweb", "rhelp", "rrst"]
let R_auto_omni = ["r",  "rmd", "rnoweb", "rhelp", "rrst"]
nnoremap <silent> <LocalLeader>h :call RAction("head")<CR>
nnoremap <silent> <LocalLeader>v :call RAction("View")<CR>
nnoremap <silent> <LocalLeader>mt :call RAction("tail")<CR>
nnoremap <silent> <LocalLeader>md :call RAction("dim")<CR>

The (begin of) error message : 
E15, Invalid Expression: "^Bnot_checked^]], 'ttl', ....

I'm desesperate, I use nvimr every days :''(

Thx for this great job !

**Comment by jalvesaq** [comment]
I'm sorry, but I can't replicate the issue with either Vim 8.2 (not inside Tmux) or Neovim.

**Comment by gilles13** [comment]
problem solve with distribution upgrade

**Comment by jalvesaq** [comment]
Thanks for the feedback.
