### ISSUE TITLE
Option to disable detection of .s and .S files

### ISSUE THREAD

**Issue by xiamaz** [jalvesaq/Nvim-R#617]
`.s` and `.S` files are commonly used as file endings for assembly files, but also for S files which might be valid R code.

When adding autocommands to redetect these files as assembly, the editor has the correct filetype, but a nvimcom process and the nvim-r plugin are still started.

"""
autocmd BufNewFile,BufRead *.S set ft=asm
autocmd BufNewFile,BufRead *.s set ft=asm
"""

Is there any other way to disable certain filetype detections for this plugin? Any help would be much appreciated!

**Comment by jalvesaq** [comment]
Does anyone still use S? Maybe we could simply delete the two lines that refer to S from `ftdetect/r.vim`.
