### ISSUE TITLE
Tmux no longer being spawned, getting R inside of a vim buffer instead

### ISSUE THREAD

**Issue by slagtermaarten** [jalvesaq/Nvim-R#618]
Hi, 
Thanks first and foremost for maintaining this super useful package.
I recently updated my vim packages and now notice new R sessions are no longer being spawned in new tmux panes, but in new vim buffers instead. I haven't altered my vim settings at all since this 'break' occurred. Is this the end of tmux support of the master branch? Or can I still get it to work somehow? 
Kind regards, Maarten

**Comment by jalvesaq** [comment]
Maybe this is a duplicate of https://github.com/jalvesaq/Nvim-R/issues/474

**Comment by slagtermaarten** [comment]
Hi, thanks, it's not. I had already implemented the changes suggested in the linked article.

**Comment by jalvesaq** [comment]
I can't replicate the issue. Although I'm no longer maintaining the code it still works with both Vim and Neovim:

```vim
let R_in_buffer = 0
let R_source = '/path/to/Nvim-R/R/tmux_split.vim'
```

**Comment by slagtermaarten** [comment]
Hmm that's weird, it doesn't work for me anymore and I don't recall changing anything related. The buffer based version seems to work for me as well, I'll work like this for a while. Thanks..!
