### ISSUE TITLE
Problems with line breaks

### ISSUE THREAD

**Issue by BiliBraker** [jalvesaq/Nvim-R#619]
I have the following script, which runs perfectly:

```
g1 <- ggplot(data = advanced, aes(x = pub_year, y = advanced_percent)) +
        geom_line() +
        labs(x = "Year of publication", y = "Advanced imputation (%)", title = "Percentage of advanced imputation in papers (1999-2016)") +
        ylim(0, 50) +
        theme_bw()
```

If I add a line break before "title", however, I got the following error:

> Error: Cannot add ggproto objects together. Did you forget to add this object to a ggplot object?

According to [this post](https://community.rstudio.com/t/could-anybody-help-me-cannot-add-ggproto-objects-together/11271/2), it is a syntax error.

Infos:

- nvim: v0.4.3
- OS: Ubuntu 20.04.2 LTS
- R: 4.1.1

**Comment by BiliBraker** [comment]
I've tried your script with visual selection (I've selected the whole script and then sent it to R) and it crashed with the following error:
```
> library("ggplot2")
data(mtcars)
g1 <- ggplot(data = mtcars, aes(x = mpg, y = qsec)) +
    geom_line() +
    labs(x = "Year of publication",
         y = "Advanced imputation (%)",
         title = "Percentage of advanced imputation in papers (1999-2016)") +
         y = "Advanced imputation (%)",
         title = "Percentage of advanced imputation in papers (1999-2016)") +
    ylim(0, 50) +
    theme_bw()
g1
Use suppressPackageStartupMessages() to eliminate package startup messages
> data(mtcars)
> g1 <- ggplot(data = mtcars, aes(x = mpg, y = qsec)) +
+     geom_line() +
+     labs(x = "Year of publication",
+          y = "Advanced imputation (%)",
+          title = "Percentage of advanced imputation in papers (1999-2016)") +
+          y = "Advanced imputation (%)",
Error: unexpected ',' in:
"         title = "Percentage of advanced imputation in papers (1999-2016)") +
         y = "Advanced imputation (%)","
>          title = "Percentage of advanced imputation in papers (1999-2016)") +
Error: unexpected ')' in "         title = "Percentage of advanced imputation in papers (1999-2016)")"
>     ylim(0, 50) +
+     theme_bw()
Error: Cannot add ggproto objects together. Did you forget to add this object to a ggplot object?
Run `rlang::last_error()` to see where the error occurred.
> g1
Error: object 'g1' not found
>
```

However it worked with line-by-line selection.

**Comment by jalvesaq** [comment]
I can't fix the issue because I can't replicate it. The problem might be in your terminal emulator (old Neovim's one). You could try in your `init.vim`:

```vim
let R_bracketed_paste = 1
```

If this does not fix the issue, you could try an external terminal emulator:

```vim
let R_external_term = 1
```

**Comment by BiliBraker** [comment]
Unfortunately, none of the above solved the issue. I use urvxt as terminal emulator, but tried it with gnome-terminal with no luck.

**Comment by jalvesaq** [comment]
I installed `urxvt` 9.22 and still can't replicate the issue.

**Comment by jalvesaq** [comment]
If this issue is still relevant to you, could you try the minimal `init.lua` suggested at https://github.com/jalvesaq/Nvim-R/wiki/Minimal-init.lua-to-report-bugs to confirm that it is really a Nvim-R bug? Please, reopen the issue if you confirm the bug still exists.
