### ISSUE TITLE
Does not load in recent neovim nightly releases

### ISSUE THREAD

**Issue by nacnudus** [jalvesaq/Nvim-R#620]
Thank you for Nvim-R.  I have relied on it for several years, and it deserves much more praise.

It does not load in recent neovim nightly releases.  I have used `git bisect` to find the first neovim commit where it stopped working, which is https://github.com/neovim/neovim/commit/396280d3030685c6b7c4d962f24bb5171a735b47.  I don't know enough about how Nvim-R and neovim work to know where to report this, so please let me know if I ought to open an issue in neovim.

**Comment by jalvesaq** [comment]
I'm sorry, but I can't replicate the issue with the current development version of Neovim on Linux. R is starting as usual with `<LocalLeader>rf`.

**Comment by nacnudus** [comment]
Thanks for your quick reply.

I can produce the error on two different computers, both running Arch Linux.

```
$ nvim --version
'Tipz:' vim --version
NVIM v0.6.0-dev+344-gb3b02eb52
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az139-151

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

**Comment by nacnudus** [comment]
It seems to only occur when using packer and init.lua, so perhaps the problem is with packer.  I'll keep investigating.  Here's my init.lua file anyway.

```lua
vim.g.mapleader = ' '
vim.g.maplocalleader = ','

-- Bootstrap packer
local fn = vim.fn
local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
  fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
  vim.cmd 'packadd packer.nvim'
end

vim.api.nvim_exec(
  [[
  augroup Packer
    autocmd!
    autocmd BufWritePost init.lua PackerCompile
  augroup end
]],
  false
)

require('packer').startup(function()
  use { 'jalvesaq/Nvim-R', ft = { 'r' } }
end)
```

**Comment by nacnudus** [comment]
It works with paq, so the problem seems to be with packer.  Sorry for causing this distraction.

```lua
vim.g.mapleader = ' '
vim.g.maplocalleader = ','
 
require "paq" {
    "jalvesaq/Nvim-R"; 
}
```

**Comment by jalvesaq** [comment]
Thanks for the feedback!

**Comment by git-em** [comment]
@nacnudus Did you manage to make it work with packer?

**Comment by jalvesaq** [comment]
I didn't install `packer` (I use vim-plug), but maybe you shouldn't add `ft = { 'r' }`. Even if you never edit Rmd or Rnoweb files, documentation and the object browser have their own file types, and the R Console is highlighted as `rout`.

**Comment by git-em** [comment]
I've tried without `ft = { 'r' }` and also `use { 'jalvesaq/Nvim-R', ft = { 'r', 'rmd', 'rrst', 'rout' } }`, but neither worked for me. According to `:PlugStatus` the plugin is being loaded, although none of the commands work. I thought it might be related to the plugin `filetype.nvim` -- which replaces the original `filetype.vim` file -- but i removed it and nothing changed. 

I've only recently changed to lua configs, so it might be something else. Once i have time to learn more about lua and packer i shall try to figure it out (and if so, i'll post here).

Thank you very much for developing and maintaining such a great plugin! @jalvesaq 
Obrigado, mesmo! (;

**Comment by git-em** [comment]
Turns out the problem was my neovim build. Some conflict with the files and paths of two different versions.

I just removed everything and installed a fresh version of `NVIM v0.7.0-dev+1082-g046950f63`. Everything running perfectly out of the box with  https://github.com/wbthomason/packer.nvim/commit/75d70d454a852afd92d0f9272d286558ba532954, simply with `use  'jalvesaq/Nvim-R'`.

Thanks again!
