### ISSUE TITLE
Updating nvimcom errors when using Neovim on Windows Cygwin64

### ISSUE THREAD

**Issue by gwd999** [jalvesaq/Nvim-R#621]
Anyone here has some experience with Nvim-R "updating"

When opening a .R file in Neovim v0.5.1 
it shows the message "Updaring nvimcom" 
and ends it with message "Failed to install nvimcom" 

My Sys info: 

WINDOWS 10 Pro 
R-4.0.5  (non standard path) 
Rtools40  (default path) 
R_LIB (non standard path) 

The package installation messages look like: this:  
```
 * installing to library 'D:/R_LIB/4.0'
 * installing *source* package 'nvimcom' ...
 ** using staged installation
 ** libs
 "C:/rtools40/mingw64/bin/"gcc  -I"C:/R/R-4.0.5/include" -DNDEBUG       -D`C:/R/R-4.0.5/bin/R --slave -e 'cat(Sys.info()[[1]])'` -DLWS_NO_FORK  -DWIN32   -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c nvimcom.c -o nvimcom.o
... 
In file included from nclientserver.c:10:
/usr/include/w32api/winsock2.h:1025:34: error: conflicting types for ‘select’ 
.... 
In file included from nclientserver.c:10:
/usr/include/w32api/winsock2.h:1034:34: error: conflicting types for ‘gethostname’ 
...
make: *** [Makevars.win:11: nvimapps] Error 2
ERROR: compilation failed for package 'nvimcom'
```
Thanks in advance for any advice from someone with experience on that topic? 
PS: maybe it would be helpful if the neovim pkg would be available again from somewhere to building and install in R independently?

**Comment by jalvesaq** [comment]
The nvimcom package cannot be on CRAN. Even if it could, there would be a version mismatch whenever a new version was needed and you had only updated either your Vim plugins or your R libraries.

Failure to build nvimcom on Windows is a recurrent problem. I have never managed to fix the issue properly. A pull request fixing the issue is welcome.

**Comment by gwd999** [comment]
Will give it a shot - not really sure I will manage ...

**Comment by jalvesaq** [comment]
Please, see: https://github.com/jalvesaq/Nvim-R/issues/775
