### ISSUE TITLE
Browser fails to run when browser option contains switches

### ISSUE THREAD

**Issue by josswright** [jalvesaq/Nvim-R#630]
I've recently had to start working with RMarkdown documents, and have been using my browser to view rendered output.

To get around the issue -- documented on the wiki FAQ -- that browsers typically open links in a new tab, I created a new R-specific Firefox profile with the option `browser.link.open_newwindow` set to `1`. This causes externally-passed links to open in the current tab. (Incidentally, this seems a much simpler option than the one currently suggested on the wiki.)

I then set my R browser option as: `options( browser="firefox -kiosk -P R" )` to load my specific firefox profile named "R". (The `kiosk` switch removes window decorations; in combination with the `full-screen-api.ignore-widgets` set to `TRUE`, this gives an output window visually very similar to a standard x11() canvas.)

This works fine in a normal R session, but when I use `\kr` to knit the markdown document I get the error:

```
Invalid value for argument cmd: "firefox -kiosk -P R"  is not executable
```

I've now solved this by making a specific script `r-firefox` that wraps up the call into a single command:

```
#!/bin/sh

firefox -kiosk -P R $@
```

This still seems an undesirable bug, though, as the browser option will work in a typical R session, but not when called from the knit command. 

For reference, I can call `browseURL(...)` directly in an NVim-R session with the longer, switches-included version of the browser option above without errors.

**Comment by jalvesaq** [comment]
Thanks for reporting the issue and for teaching us about Firefox profiles. After the next commit, your `r-firefox` script will no longer be required. It will be enough to set `options(browser="firefox -kiosk -P R")` in the `.Rprofile`. I'm also updating Nvim-R's documentation.
