### ISSUE TITLE
Specify knit output directory

### ISSUE THREAD

**Issue by josswright** [jalvesaq/Nvim-R#631]
Apologies if there's an option that I've missed.

Is there any way to specify the output location for rendering an RMarkdown file when called with `\kr`? Currently, the output is put in the same directory as the .Rmd file. It would be very convenient if it could be specified to write to, say, an `output` subdirectory and have the appropriate path loaded by the web browser or PDF viewer.

**Comment by jalvesaq** [comment]
Currently, the path is hardcoded with `setwd()` to the RMarkdown document's directory, but I can create an option to pass extra arguments to `rmarkdown::render()`, including `output_dir`.

**Comment by josswright** [comment]
That would be amazing, thank you!
