### ISSUE TITLE
issue with Nvim-R in combination with renv

### ISSUE THREAD

**Issue by sebffischer** [jalvesaq/Nvim-R#632]
When running renv::init() in a new project directory and afterwards starting Nvim-R inside the project, causes Nvim-R to not work. More specifially, the error message in the R console is 

`During startup - Warning message:
package ‘nvimcom’ in options("defaultPackages") was not found`

When then trying to execute a line, the error message is "not ready yet".

**Comment by jalvesaq** [comment]
Please, see: https://github.com/jalvesaq/Nvim-R/issues/445
