### ISSUE TITLE
enhancement: send everything after or before the `<-` assignment operator

### ISSUE THREAD

**Issue by SoaresAlisson** [jalvesaq/Nvim-R#637]
Suppose that I have:

```
R_Object  <- ABunch_of_R_code(
      new_lines_with_more_R_things,
      new_lines_with_more_R_things)
``` 

Wherever my cursor is in such a code, is there any way to run (send to R console) only 1) the R_Object or; 2) run everything after the `<-` operator?
If there is not such implementation yet, I think it can be very helpful and a big productivity improve when we are editing a  code.

Anyway, thanks to this plugin.

**Comment by jalvesaq** [comment]
You could select what you want and type `<LocalLeader>ss` in Normal mode.
