### ISSUE TITLE
Notebok-like new behaviour (enhancement suggestion)

### ISSUE THREAD

**Issue by lf-araujo** [jalvesaq/Nvim-R#638]
Hi @jalvesaq,

This is not a bug report, but an enhancement suggestion/discussion.

Language notebooks are extremely useful for scientific analyses, hence Jupyter's  popularity. Emacs with org-mode and babel is possibly even more impressive, as it is a complete GUI instead of a web interface. 

The usefulness of these approaches lies in that the results are reproducible, time proof as they are mostly fixed in text, and easily shared between collaborators.

Inline image is obviously not possible in Vim, or at least it is not easy to implement. But Vim is much, much quicker than Jupyter and Emacs. Emacs is a single thread tool, so demanding processes in R will hang the entire interface. We know this is not the case with Nvim-R.

- Would it be possible to achieve a middle ground, imageless, notebook type using R and Nvim-R? I argue it is possible and the groundwork is partially laid in the repository.

There is a little forgotten function in Nvim-R called `SendLineToRAndInsertOutput()` which does what it says: adds the output of a single line into commented code just below the command itself. Furthermore, Nvim-R already have genial rmarkdown support.

In order to achieve something similar to Emacs babel, one could extend such function to work with Rmd chunks.  For example, make it  extract the contents of a Rmd chunk, run it on the terminal, and paste it *below* said chunk as a markdown comment like so:

```
<--
# THIS IS THE OUTPUT OF THE CHUNK
-->
```

Ideally, such behaviour would be aware of the chunk header so that a chunk like `{r echo = F}` shouldn't generate the output inline; or a chunk like `{r, eval=TRUE, echo = FALSE, message=FALSE, warning=FALSE}` shouldn't output the warnings or messages.

Also, the new behaviour could be aware of the chunks options:

```r
# Knitr options
knitr::opts_chunk$set(
  comment = NA, # remove comment symbol
  cache.path = "../cache/", # where should I save cache?
  fig.path = "../graphs/", # where should I save figures?
  echo = F, # dont echo by default
  cache = F, # dont cache by default
  fig.width = 10, # setting the best witdth for figures
  fig.height = 7, # best height
  dpi = 300
) # high dpi for publication quality
```

- Is there anything that could be used to at least diminish the problem of not showing the images inline? I think the combination of two new behaviours could ameliorate this:

1. Since nvimr knows about knitr paths and the heading for the chunk (`{r, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE, fig.height=10, fig.width = 10}`) then it should know where to save the figure from the png(), jpeg(), pdf() device. With this info, after saving the file, it could output the path:

```
<--
../graphs/histogram.png
-->
```

2. A key combination that opens the file from that path with the systems file, image manager (xdg-open in linux, and open in MacOs, etc).

I was reserving some time to do this myself, however a new job came around and won't be able to implement. So these are my ideas. If you find not aligned with the design for Nvim-R you can close it.

Thank you for the most important piece of software in my daily workflow, @jalvesaq!

**Comment by jalvesaq** [comment]
Unfortunately, I don't have spare time to develop something that I'm not using, and RMarkdown is good enough for me. But we may let the issue open for the unlikely possibility of someone wanting to work on this.

**Comment by jalvesaq** [comment]
Nvim-R is being superseded by R.nvim, a new project that will be inaugurated in a week at the [R-nvim](https://github.com/R-nvim) organization.
Please, check out [tmp-Nvim-R](https://github.com/jalvesaq/tmp-R-Nvim) and help us to find the last remaining bugs before R.nvim inauguration.
When the project is officially started, you will be able to open issues there and request new features.

Nvim-R will remain alive as a feature-frozen project for Vim users. If you want to know the reason, please, see [this discussion](https://github.com/jalvesaq/Nvim-R/discussions/797).
