### ISSUE TITLE
AutoStart [12] StartNClientServer[3] StartingR[103] StartR_InBuffer

### ISSUE THREAD

**Issue by 777uliahshafar** [jalvesaq/Nvim-R#639]
My vim show an error when using auto_start R. I have read the post that this is because nclientserver must initiate first before R. So we need to add ``R_auto_start=1 in vimrc``, but it didn't work for me.  ``

**Comment by jalvesaq** [comment]
I can't replicate the issue. `R_auto_start` works as expected here in both Neovim and Vim.

**Comment by 777uliahshafar** [comment]
Thank you for fast response,  I have two file that behave differently. When I use .Rnw with  large text in which take up to 3 second to load it didn't show the error, but when I open .R file with just one script (20lines) and load very quick the error was show up.  This my first issue on github, I don't know how to demostrate problem well in here.

I have updated the plugin and it's not change. Anyway, The R console is just active but after the error show up and the position is change under the coc-explrer not under the R file. 

![Screen Shot 2021-12-04 at 04 46 35](https://user-images.githubusercontent.com/67497706/144681942-e8c31d28-22e3-4d67-a6f0-90e1385c0486.png)

**Comment by jalvesaq** [comment]
Thanks for posting the actual error message! Although I can't replicate the issue, I believe that it is fixed now. Could you, please, update Nvim-R and try again?

**Comment by 777uliahshafar** [comment]
Awesome it fixed. I think I can start my morning now, :D

**Comment by jalvesaq** [comment]
Thanks for the feedback, and good morning!
