### ISSUE TITLE
key mapping for send line / selection with control-enter

### ISSUE THREAD

**Issue by wahani** [jalvesaq/Nvim-R#64]
As a RStudio user I kind of got used to sending R-code with `<Control-Enter>` to the REPL. However this was tricky to configure in neovim and I didn't find anything in the documentation of Nvim-R. So here is one solution working in Ubuntu 14.04 with gnome-terminal. The tricky part is to find out what the terminal actually sees when `<Control-Enter>` is hit; this I found out using [this stackoverflow question](http://stackoverflow.com/questions/598113/can-terminals-detect-shift-enter-or-control-enter). And here is the solutions:

```vim
nnoremap <C-J> :call SendLineToR("stay")<CR><Down> 
inoremap <C-J> <Esc>:call SendLineToR("stay")<CR><Down><Home>i
vnoremap <C-J> :call SendSelectionToR("echo", "stay")<CR><Esc>
```

`<C-J>` is interpreted as nil: `<NL>` which is apparently what gnome-terminal detects as input. Since there is already an example for `<Space>` in the documentation I thought it might be an interesting addition.

Thanks for Nvim-R!
-s

**Comment by jalvesaq** [comment]
Thanks for writing! I see one problem with your suggestion: the user might be sending `<C-Enter>` to the terminal, but actually what is typed is `<C-J>`, so the experience is different from that of RStudio users. At least here (Ubuntu 16.04, gnome-terminal), the mappings did not allow me to type `<C-Enter>` to send code to R. When I press `<C-Enter>` the cursor simply moves one character forward.

This works here:

```vim
nmap <silent> ^M :call SendLineToR("down")<CR>
```

where `^M` is inserted with `<C-V><C-Enter>` in Insert mode.

**Comment by wahani** [comment]
Yes it varies between systems -- and maybe also between terminal applications -- which is why I think documentation may be helpful. Maybe a link to this issue is sufficient. It would have saved me some time as a nvim beginner...

**Comment by jalvesaq** [comment]
Does the `^M` work for you?

**Comment by wahani** [comment]
No, the solution is not working for me.

**Comment by jalvesaq** [comment]
Thanks for your contribution!

**Comment by scottstanfield** [comment]
For what it's worth on the Mac with iTerm2, I set iTerm2 to send an unused Unicode glyph, like this Maltese Cross (✠). So a ctrl-enter sends ✠ instead.

Then in my `.init.vim` I have this:

```
nnoremap <silent> ✠ :call SendLineToR("stay")<CR><Esc><Home><Down>
inoremap <silent> ✠ <Esc>:call SendLineToR("stay")<CR><Esc>A
vnoremap <silent> ✠ :call SendSelectionToR("silent", "stay")<CR><Esc><Esc>
```

The above works. However `vnoremap` (the visual block mode) sends one line at a time (so four lines generate four `base::source` messages), whereas `\ss` sends just one.

So I'm getting close to getting ctrl-enter to work in insert, normal and visual mode.

I also have the same keystrokes working for Python 3 for https://github.com/kassio/neoterm plugin.

```
nnoremap <silent> ✠ :TREPLSendLine<cr>j
inoremap <silent> ✠ <ESC>:TREPLSendLine<cr>A
vnoremap <silent> ✠ :TREPLSendSelection<cr>gv
```

*Yes, I'm making VIM my IDE for Python and R*

**Comment by scottstanfield** [comment]
I finally have <space> *and* <control-enter> working on Mac OS and iTerm 2, at the same time. This gives me the RStudio control-enter experience, and the space bar feature. 

I don't know why some times I had to use `<Plug>` and others `:call`, sometimes `<silent>`, sometimes not. But it's all working after a lot of trial and error.

<space> sends the line (normal mode) or selection (block mode)
```
vmap <silent> <Space> <Plug>RSendSelection<Esc><Esc>
nmap <silent> <Space> :call SendLineToR("stay")<CR><Esc><Home><Down>
```

<control-enter> sends the line (normal and insert) or selection (block mode)
```
" Mac iTerm: custom map control-enter to something unique. Maltese cross in this case.
nmap <silent> ✠ :call SendLineToR("stay")<CR><Esc><Home><Down>
imap <silent> ✠ <Esc>:call SendLineToR("stay")<CR><Esc>A
vmap ✠ <Plug>RSendSelection<Esc><Esc>

```

**Comment by jalvesaq** [comment]
Thanks for the feedback!

**Comment by marskar** [comment]
@scottstanfield, I think it will be a lot better to have your terminal send the appropriate escape code for each key combo:

| KeyCombo       | EscapeCode |
|----------------|------------|
| \<S-CR\>       | [13;2u     |
| \<M-CR\>       | [13;3u     |
| \<M-S-CR\>     | [13;4u     |
| \<C-CR\>       | [13;5u     |
| \<C-S-CR\>     | [13;6u     |
| \<M-C-CR\>     | [13;7u     |
| \<M-C-S-CR\>   | [13;8u     |

Here's a screenshot from iTerm:
![image](https://user-images.githubusercontent.com/12806339/97055810-8e602080-1555-11eb-9070-c9c0d2586611.png)

Then you can use the same mapping in terminal vim and vim GUIs.
Here are the mappings I use to send code:
```vim
autocmd FileType rmd   nmap <buffer> <M-S-CR> <Plug>REDSendChunk
autocmd FileType r     nmap <buffer> <M-S-CR> <Plug>RESendFile
autocmd FileType r,rmd nmap <buffer> <silent> <M-CR> :call SendLineToR("down")<CR>
autocmd FileType r,rmd nmap <buffer> xmap <M-CR> <Plug>REDSendSelection
```
**NOTE:** I do not know how to differentiate between `<M-CR>` and `<A-CR`> in neovim. If you can find the escape code for `<D-CR>`, please let me know!
