### ISSUE TITLE
How to debug the debugger

### ISSUE THREAD

**Issue by sebffischer** [jalvesaq/Nvim-R#640]
For some reason, using 

```
f = function() print("hallo world"
debugonce(f)
f()
```

does not work anymore. Previously for me the line was highlighted in the file, and when debugging other files they were opened in new buffers. 

Can you help me on how to debug this? It used to work before but I have no idea why it does not anymore.

**Comment by jalvesaq** [comment]
I can't replicate the issue. The function (with the closing parenthesis after the print function) is highlighted here.

**Comment by sebffischer** [comment]
Ok I think I know know what the problem is: When I send the lines to the console individually it is not working (i.e. the content of the function `f` is printed into the console. But when I send the whole file it is working as expected, meaning it opens a new buffer with the temp-file. Not sure whether this is an issue only for me or also for others.

**Comment by sebffischer** [comment]
Ok I think I know know what the problem is: When I send the lines to the console individually it is not working (i.e. the content of the function `f` is printed into the console. But when I send the whole file it is working as expected, meaning it opens a new buffer with the temp-file. Not sure whether this is an issue only for me or also for others.

**Comment by sebffischer** [comment]
Does it also work for you when sending the lines to the console individually? (For me it works as expected when I send the whole file to the console, then it opens the temporary file as soon as the debugger starts) The problem seems to me in my case that it does not recognize that the source code for the function that is being debugged is in the open buffer.

**Comment by jalvesaq** [comment]
Actually, it works only if I use the " <- " operator.  Using " = " it doesn't work.

**Comment by jalvesaq** [comment]
Could you, please, update Nvim-R? It should work now.

**Comment by sebffischer** [comment]
It is working, thanks a lot!

**Comment by jalvesaq** [comment]
Thanks for the feedback!
