### ISSUE TITLE
Open tmp.R files in readonly mode?

### ISSUE THREAD

**Issue by sebffischer** [jalvesaq/Nvim-R#641]
Hallo, 

This is a feature request. 
Sometimes when I am debugging, I unintentionally edit the **R.tmp.R file, which can be annoying if I don't realize this, because then changes can be lost and I have to fix bugs again. 
Is it possible to enable a flag that allows to open these temporary files in read-only mode? 

Thank you for Nvim-R! :)

**Comment by jalvesaq** [comment]
Actually, the file should be immediately deleted after being sourced. See the source code of `nvimcom:::source.and.clean`:

```R
function (f, ...)
{
    on.exit(unlink(f))
    source(f, ...)
}
```

You could write an auto command in your vimrc/init.vim to do something (echo a warning message, turn the buffer read-only...) if the file name ends in ".R.tmp.R", but this will not be necessary if we discover why the temporary file isn't being deleted.

**Comment by sebffischer** [comment]
But this is only relevant when I send the code to the console, right? I am tallking about the debugging scenario, where the source-files for the debugged functions are opened.

**Comment by jalvesaq** [comment]
Nvim-R is being superseded by R.nvim, a new project that will be inaugurated in a week at the [R-nvim](https://github.com/R-nvim) organization.
Please, check out [tmp-Nvim-R](https://github.com/jalvesaq/tmp-R-Nvim) and help us to find the last remaining bugs before R.nvim inauguration.
When the project is officially started, you will be able to open issues there and request new features.

Nvim-R will remain alive as a feature-frozen project for Vim users. If you want to know the reason, please, see [this discussion](https://github.com/jalvesaq/Nvim-R/discussions/797).
