### ISSUE TITLE
Automatically turn off spelling in R terminal using Radian

### ISSUE THREAD

**Issue by fisher-j** [jalvesaq/Nvim-R#643]
I am using `R_app = "radian"` on windows 10 and would like to have spell check turned off by default.

`au TermOpen * setlocal nospell`, though, prevents any terminal from opening with `\rf`

There are no errors, or any visible response.

What is the correct way to automatically `set nospell` in the R terminal?

**Comment by jalvesaq** [comment]
I can't replicate the issue on Linux with regular R. Maybe someone else could help you.
