### ISSUE TITLE
:command

### ISSUE THREAD

**Issue by alexchaichan** [jalvesaq/Nvim-R#648]
Hey, 

I was wondering waht the command is to start the R session?

Yes know the default ist `\rf`

but I want to use a function to start vim with commands like

```
function(){
    cd path/to/dir
    nvim script.R "+:NERDTreeToggle" "+:\rf" 
```

and for this I need the default `:` command . 
I searched  all the files in the project but couldn't find it :/

**Comment by jalvesaq** [comment]
If you do:

```
:nmap
```

you will find that `\rf` is converted into `:call StartR("R")`.

So, you this should work:

```
nvim script.R '+:NERDTreeToggle' '+:call StartR("R")'
```

Please see also the documentation on `R_auto_start`.

**Comment by jalvesaq** [comment]
It fails to load nvimcom. So, the solution is a bit more complex.

Put in your init.vim:

```
if $AUTOSTARTR == "yes"
  let R_auto_start = 1
endif
```

And change your (bash?) function to:

```
function start_R(){
    cd path/to/dir
    AUTOSTARTR="yes" nvim script.R "+:NERDTreeToggle"
}
```

**Comment by alexchaichan** [comment]
Thank you very much!

On osx and arch this work fine for me

function(){
    cd path/to/dir
    nvim script.R  "+:call StartR('R')"  "+:call StartObjBrowser()" "+:NERDTreeToggle"
}

**Comment by alexchaichan** [comment]
Unfortunately the Object Browser is not working when I start the device this way.

Createt object doesn't appear until I close `\ro` and reopen `\ro` :/

**Comment by jalvesaq** [comment]
You should call `RObjBrowser()` instead of `StartObjBrowser()`.
I have also just added the option `R_objbr_auto_start`.
