### ISSUE TITLE
nvim-R upgrade failed on macOS Catalina

### ISSUE THREAD

**Issue by ssh352** [jalvesaq/Nvim-R#649]
I used vim-plug to upgrade nvim-R and it failed a compiling nvimcom:
<img width="876" alt="Screen Shot 2022-01-28 at 12 12 36 PM" src="https://user-images.githubusercontent.com/41779116/151486201-10858cd5-5a89-49ce-9403-5753e701cb84.png">
<img width="917" alt="Screen Shot 2022-01-28 at 12 13 24 PM" src="https://user-images.githubusercontent.com/41779116/151486204-4fb8ac4c-e710-4b8f-b351-5f81aa00133e.png">
<img width="909" alt="Screen Shot 2022-01-28 at 12 13 43 PM" src="https://user-images.githubusercontent.com/41779116/151486209-e46e70ae-9667-4624-80e1-17b47dddf7a4.png">
<img width="352" alt="Screen Shot 2022-01-28 at 12 14 52 PM" src="https://user-images.githubusercontent.com/41779116/151486385-f808c614-018e-4210-b568-324607d47c4a.png">

<img width="868" alt="Screen Shot 2022-01-28 at 12 18 12 PM" src="https://user-images.githubusercontent.com/41779116/151486586-6847c8b5-c98b-4e9d-a8a5-8b2ae3fc3d41.png">

clang is brew installed clang 13. My OS is macOS Catalina with the all updates installed. I had no problem with nvim-R with this setup before this upgrade.  Could someone advise?

**Comment by jalvesaq** [comment]
I don't have a Mac OS, but is `TARGET_OS_IPHONE` correct? Are you sure that your compiling tools are correctly configured?

**Comment by jalvesaq** [comment]
This might be useful: https://stackoverflow.com/questions/69421366/compilation-failed-after-r-update-stdio-h-nonnull

**Comment by ssh352** [comment]
sorry forgot to update: it used brew installed clang to upgrade. I removed brew installed clang and it worked.

**Comment by jalvesaq** [comment]
Thanks for the feedback!
