### ISSUE TITLE
Set `winfixheight` by default

### ISSUE THREAD

**Issue by TerseTears** [jalvesaq/Nvim-R#650]
Hello and thank you for the great plugin.

Just a very minor issue. Presently, `Nvim-R`' s default is to only set `winfixwidth` which is only useful for vertical split. Setting `winfixheight` allows a horizontal R session split to maintain its size as well. The corresponding line: https://github.com/jalvesaq/Nvim-R/blob/51636d3b680d478ade97fb433375759e100db4d6/R/start_r.vim#L2089

**Comment by jalvesaq** [comment]
The automatic horizontal size adjustment when either splitting or closing windows was not bothering me, but I agree that `R_buffer_opts` will be more consistent if it includes 'winfixheight'. Thanks for noting that!
