### ISSUE TITLE
Launching a new R process from within Nvim-R uses the wrong working directory

### ISSUE THREAD

**Issue by klmr** [jalvesaq/Nvim-R#651]
Hi Jakson,

Please consider the following code:

```r
message(getwd())
setwd('..')
message(getwd())
system2('Rscript', c('-e', shQuote('message(getwd())')))
```

If we save this code as `test.r` and execute it directly (e.g. via `Rscript`), it behaves as espected:

```bash
$ Rscript test.r
/Users/konrad/tmp/r/foo
/Users/konrad/tmp/r
/Users/konrad/tmp/r
```

However, if I open `test.r` inside Vim, start R, and execute the code (e.g. via <kbd>\\</kbd><kbd>a</kbd><kbd>a</kbd>), something very weird happens, and the output is:

```
/Users/konrad/tmp/r/foo
/Users/konrad/tmp/r
/Users/konrad/tmp/r/foo
```

That is, **the R subprocess that I launched is executed in the wrong working directory.**

This only happens for R processes. For example, `system2('sh', c('-c', 'pwd'))` prints `/Users/konrad/tmp/r`, as expected. But it happens even if the R process is invoked indirectly. In fact, my actual use-case is slightly different from the above. Rather than running `Rscript`, I’m running GNU make, and R is invoked inside the `Makefile`. The `Makefile` has the correct working directory; its R subprocess has the wrong one.

And just to clarify, this isn’t an issue with `system2` only — other ways of invoking a subprocess cause the same behaviour (e.g. `pipe` or `sys::exec_wait`).

**Comment by klmr** [comment]
I’ve found a workaround: passing `env = 'NVIMR_TMPDIR='` to `system2`:

```r
system2('Rscript', c('-e', shQuote('message(getwd())')), env = 'NVIMR_TMPDIR=')
```

However, I feel that this should work without changes to user code.

**Comment by jalvesaq** [comment]
I can replicate the issue. Nvimcom needs `NVIMR_TMPDIR` to know where to save temporary files. So, unsetting the variable during R startup is not an option, but you can specifically avoid the `setwd()` on R startup with this in your vimrc/init.vim:

```vim
let R_nvim_wd = -1
```

**Comment by jalvesaq** [comment]
This option was introduced in 2014 (https://github.com/jcfaria/Vim-R-plugin/pull/99), and has already caused problems (https://github.com/jalvesaq/Nvim-R/issues/219).

**Comment by klmr** [comment]
I think the fundamental issue is that nvimcom is loaded in R subprocesses. Is this actually something that’s intentional/desirable?

Maybe as part of the nvimcom startup (i.e. in `.onLoad`) the package should remove itself from the `R_DEFAULT_PACKAGES` list. That way, R subprocesses that are launched from within the R session in Vim won’t load nvimcom and won’t be affected by Nvim-R.

As a consequence these subprocesses also won’t be able to communicate with Nvim-R any longer but they wouldn’t do that anyway, would they? At least that isn’t my expectation as a user.

**Comment by jalvesaq** [comment]
Thanks, you are right! Actually, `R_DEFAULT_PACKAGES` was being reset during R startup, but I guess the code is broken since I moved some code from `R/common_global.vim` to other scripts to make Vim/Neovim startup faster. The issue should be fixed in the next commit.
