### ISSUE TITLE
Latency when using "local leader l" in a .Rnw document

### ISSUE THREAD

**Issue by BlueGrisGris** [jalvesaq/Nvim-R#652]
Hello,

I am noticing significant latency when sending to R with  "local leader l" from a .Rnw document.  This latency does not occur with  "local leader d", or when with  "local leader l" in a .R document.  Curious behavior, but not debilitating.  

I am using macOS version 10.14.6 and R version 4.1.2.

Thanks!

https://user-images.githubusercontent.com/26747788/153047340-3c83d44e-4fdd-454c-b0cc-8cd87e94bc73.mov

**Comment by jalvesaq** [comment]
Please, type `:nmap \l` in Vim to discover what key bindings start with `\l` (replace `\` with your `<LocalLeader>`).

**Comment by jalvesaq** [comment]
> Does this mean that it is waiting for a second character of a vimtex keybinding that starts with l?

Yes.

> Is the fix just rebinding everything that starts with l in vimtex?

This would fix the issue. But it's easier to rebind the Nvim-R command. The Nvim-R documentation has this following example:

```vim
vmap <Space> <Plug>RDSendSelection
nmap <Space> <Plug>RDSendLine
```

**Comment by BlueGrisGris** [comment]
I am sorry I do not quite follow what these commands do.  Should I add them to my vimrc?  Will they rebind \l to \<space> for sending the current line of R code?

Thanks!

**Comment by jalvesaq** [comment]
Yes, you should put the command in your vimrc. But alias is `RSendLine`.
