### ISSUE TITLE
Create and communicate with multiple R sessions

### ISSUE THREAD

**Issue by enptfb55** [jalvesaq/Nvim-R#653]
Not sure if this already exists but I'm wondering if it would be possible to create and communicate with multiple R sessions from within nvim-R. I think emac's ess has the ability to do something similar. I'd be happy to implement if you think it's worth while.

I'm thinking something along the lines of the following:
`<leader>\rf` -> creates session 0, nvimcom defaults to this session
`<leader>\rf` -> creates session 1, nvimcom switches to this session
`<leader>\sr 0` -> switches nvimcom to session 0
`<leader>\sr 1` -> switches nvimcom to session 1

**Comment by jalvesaq** [comment]
This was possible in the past: https://github.com/jcfaria/Vim-R-plugin/commit/ec5691fd62c8459eaecd58539bc9bd647bdc0e60

But it was too complicated to maintain in 2013 and would be even more nowadays. I'm sorry, but if you need two R instances you will have to run two Vim/Neovim instances. In addition to being easier to maintain, I think it is less confusing for users.
