### ISSUE TITLE
Small print area when using R_min_editor_width  for vertical splitting

### ISSUE THREAD

**Issue by zen3gr** [jalvesaq/Nvim-R#654]
Hello everyone,

I like to have the R console of nvim-R to the right of the text file currenty editing. In order to achieve that, according to the documentation, an appropriate R_min_editor_width value must be set. My question regards small displays: is there a way for R_min_editor_width to be small such that console actually spawns on the desired position of the screen but the `\o` command prints in the "full length" and not be limited by the value of R_min_editor_width?  I'm attaching a screenshot indication the limitation of the print command.

vimrc segment regarding nvim
"rnvim-r settings
" let R_auto_start = 2 "start R when opening an .r script
"start R console vertically
let R_rconsole_width = winwidth(0) / 3
autocmd VimResized * let R_rconsole_width = winwidth(0) / 2
let R_min_editor_width = 20

Thanks in advance.
![Screenshot 2022-02-21 10 07 29](https://user-images.githubusercontent.com/88621786/154913838-f29c1345-3ed8-4a3e-bb00-9f239423beed.png)

**Comment by jalvesaq** [comment]
Nvim-R is being superseded by R.nvim, a new project that will be inaugurated in a week at the [R-nvim](https://github.com/R-nvim) organization.
Please, check out [tmp-Nvim-R](https://github.com/jalvesaq/tmp-R-Nvim) and help us to find the last remaining bugs before R.nvim inauguration.
When the project is officially started, you will be able to open issues there and request new features.

Nvim-R will remain alive as a feature-frozen project for Vim users. If you want to know the reason, please, see [this discussion](https://github.com/jalvesaq/Nvim-R/discussions/797).
