### ISSUE TITLE
Nvimcom installation Error

### ISSUE THREAD

**Issue by blayz3r** [jalvesaq/Nvim-R#658]
![image](https://user-images.githubusercontent.com/12205650/158426261-13ea64ab-a253-4f7d-a3e5-f80f5373f829.png)
![image](https://user-images.githubusercontent.com/12205650/158426492-ceaf651e-a1ab-4f58-b7f2-17dc15f68fab.png)

**Comment by jalvesaq** [comment]
Thanks for reporting the issue! I should be fixed now.

**Comment by blayz3r** [comment]
It's working now thanks!
