### ISSUE TITLE
Error in building nvimcom

### ISSUE THREAD

**Issue by rohitfarmer** [jalvesaq/Nvim-R#659]
Hi there, I am getting this error which Nvim-R is building nvimcom. Any suggestion in resolving this would be helpful. Thanks.

```
* installing to library ‘/sysapps/cluster/software/Anaconda3/2020.07/envs/R-4.1.0/lib64/R/site-library’
Error: ERROR: no permission to install to directory ‘/sysapps/cluster/software/Anaconda3/2020.07/envs/R-4.1.0/lib64/R/site-library’
Error in installed.packages()["nvimcom", c("Version", "LibPath", "Built")] :    subscript out of bounds Calls: cat Execution halted
```

**Comment by jalvesaq** [comment]
There are other issues including the string "anaconda": https://github.com/jalvesaq/Nvim-R/issues?q=is%3Aissue+anaconda

Can you find any useful information there?
