### ISSUE TITLE
Add `.qmd` to the list of auto start file type extensions

### ISSUE THREAD

**Issue by vincentarelbundock** [jalvesaq/Nvim-R#660]
https://quarto.org

Quarto appears to be the next-generation R-markdown. It is developed by the RStudio team and uses the same type of fences as Rmarkdown:

````
```{r}
2 + 2
```
````

Would it be useful/possible to add `.qmd` to the list of extensions recognized and auto-launched by Nvim-R?

**Comment by jalvesaq** [comment]
Thanks for the notice! I didn't know about Quarto. I will migrate from RMarkdown to Quarto soon because it supports cross-references. Then, I will add support for it in both Nvim-R and https://github.com/jalvesaq/R-Vim-runtime.

**Comment by vincentarelbundock** [comment]
Wonderful!

**Comment by jalvesaq** [comment]
I started playing with Quarto (not really using it yet). The file type detection is done in [R-Vim-runtime](https://github.com/jalvesaq/R-Vim-runtime).  If using [vim-plug](https://github.com/junegunn/vim-plug), you have to add to your `vimrc`/`init.vim`:

```vim
Plug 'jalvesaq/R-Vim-runtime', {'branch': 'quarto'}
Plug 'jalvesaq/Nvim-R', {'branch': 'quarto'}
```

You still have to manually run either `quarto preview` or `quarto render`. I noted that `quarto preview` outputs useful information to debug errors in the code. So, it doesn't seem to be a good idea to run it automatically in the background.

I also started supporting Quarto in [zotcite](https://github.com/jalvesaq/zotcite):

```vim
Plug 'jalvesaq/zotcite', {'branch': 'quarto'}
```

**Comment by vincentarelbundock** [comment]
This is wonderful, thanks so much!

I just tried it and it works fantastic. I'll just create a keybinding for `quarto render %` and be all set.

The only issue I've encountered is that LSP completion does not seem to be triggered in R chunks, whereas it is in .Rmd documents. But that probably has to do with my vim setup (I recently started using neovim with nvim-cmp, and am not yet super familiar with the whole setup). I'll let you know if I ever identify the problem and figure out if it is related to `Nvim-R` at all.

Thanks!

**Comment by jalvesaq** [comment]
Is there any syntax that is specific to Quarto and that would not work on RMarkdown? I asked this question at https://github.com/quarto-dev/quarto-vim/pull/5 but maybe you know the answer...

**Comment by vincentarelbundock** [comment]
I wish I did, but no, sorry!

**Comment by jalvesaq** [comment]
The only difference that I have found so far was on how to control pandoc in the YAML field: RMarkdown requires `pandoc_args`, and Quarto, `filters`. But there is no need for a different Vim syntax script just for this. The other difference is that Quarto is better rendered by `quarto` command line, and RMarkdown by the `rmarkdown` package, what turns it useful to have different file types.
