### ISSUE TITLE
`R_source_args` was not expected when sourcing `start_options.R`

### ISSUE THREAD

**Issue by hongyuanjia** [jalvesaq/Nvim-R#662]
It is related to #335.

If the default encoding in Vim is set to `utf-8`, Nvim-R encodes the current working directory as `UTF-8` and saves it as `start_options.R` under the Nvim-R temporary directory. This will ensure that the path can be correctly read by R. Since encoding is set to `utf-8` in Vim, `writefile()` will also write `start_options.R` in `UTF-8` encoding.

https://github.com/jalvesaq/Nvim-R/blob/9bd7c2e76f692d0881d56d01592d7113cbb38112/R/start_r.vim#L136-L145

This works for most cases, except there are multibyte characters, e.g. Chinese, in the directory name:
```
Error: package or namespace load failed for 'nvimcom':
 .onLoad failed in loadNamespace() for 'nvimcom', details:
  call: source(paste0(Sys.getenv("NVIMR_TMPDIR"), "/start_options.R"))
  error: invalid multibyte character in parser at line 11
During startup - Warning message:
package 'nvimcom' in options("defaultPackages") was not found
```

This is because in `nvimcom.R`, the `start_options.R` file is sourced using `base::source()` with default arguments where `encoding = getOption("encoding")`. The default encoding value for Windows is `"native.enc"`. Thus, the R parser errored when found multibyte character with malformed encoding.

https://github.com/jalvesaq/Nvim-R/blob/9bd7c2e76f692d0881d56d01592d7113cbb38112/R/nvimcom/R/nvimcom.R#L15-L17

My question is: **Is there any way to pass the `g:R_source_args` to the nvimcom package when starting R?**

Maybe another approach is to save it as `start_options_utf8.R` when `&encoding == "utf-8"` in `start_r.vim` and add a simple logic to detect the encoding argument for `base::source()` based on the file name? E.g.:

```r
    if(file.exists(paste0(Sys.getenv("NVIMR_TMPDIR"), "/start_options_utf8.R"))){
        source(paste0(Sys.getenv("NVIMR_TMPDIR"), "/start_options_utf8.R"), encoding = "UTF-8")
    } else if(file.exists(paste0(Sys.getenv("NVIMR_TMPDIR"), "/start_options.R"))){
        source(paste0(Sys.getenv("NVIMR_TMPDIR"), "/start_options.R"))
    } else {
        ...
    }
```

**Comment by jalvesaq** [comment]
I'm sorry, but I can't fix the issue. If someone who uses Windows wants to help and create a pull request, maybe putting the following line in his or her `init.vim` will replicate the bug:

```vim
let R_tmpdir = '测试'
```

**Comment by hongyuanjia** [comment]
This is the minimal VIMRC to reproduce the error

```vim
language messages English_United States
set langmenu=en_US.UTF-8  

set runtimepath^=~/.vim

set nocompatible

filetype plugin indent on
syntax on

set ruler
set encoding=utf-8
set fileencoding=utf-8
set laststatus=2

call plug#begin()
Plug 'jalvesaq/Nvim-R'
call plug#end()

let R_tmpdir = '测试'
let R_path = 'C:/Program Files/R/R-4.1.0/bin/x64/
```

Below is the error message:

```
Building nvimcom...
Error detected while processing BufNewFile Autocommands for "*.r"..function dist#ft#FTr[29]..FileType Autocommands for "*"..function <SNR>4_LoadFTPlugin[17]..script C:\Users\hongy\.vim\plugged\Nvim-R\ftplugin\r_nvimr.vim[7]..C:\Users\hongy\.vim\plugged\Nvim-R\R\common_buffer.vim[7]..C:\Users\hongy\.vim\plugged\Nvim-R\R\common_global.vim[1304]..function GlobalRInit[5]..CheckNvimcomVersion[52]..SetRHome:
line    4:
E482: Can't create file 测试/run_cmd.bat
Error detected while processing BufNewFile Autocommands for "*.r"..function dist#ft#FTr[29]..FileType Autocommands for "*"..function <SNR>4_LoadFTPlugin[17]..script C:\Users\hongy\.vim\plugged\Nvim-R\ftplugin\r_nvimr.vim[7]..C:\Users\hongy\.vim\plugged\Nvim-R\R\common_buffer.vim[7]..C:\Users\hongy\.vim\plugged\Nvim-R\R\common_global.vim[1304]..function GlobalRInit[5]..CheckNvimcomVersion:
line   71:
E482: Can't create file 测试/nvimcom_path.R
Fatal error: cannot open file '<b2><e2><ca><d4>/nvimcom_path.R': No such file or directory^@^@
```

I try the solution I mentioned above and it worked for me. I will open a PR shortly.

**Comment by hongyuanjia** [comment]
I have opened a PR. Hope it can solve this issue.
