### ISSUE TITLE
Maximum number of lines when viewing data.frame?

### ISSUE THREAD

**Issue by kdzhang** [jalvesaq/Nvim-R#664]
Hi there, 

Thanks for this amazing plugin! Is it possible to add an option to control the maximum number of lines when viewing `data.frame`? 

Sometimes writing large temporary files to the disk can be quite time-consuming, while I often only need to view the first 100 lines to see whether things work properly or not. When I do need the full data, I often export the full dataset and use a cml lazy reading tool like `visidata`. 

Thank you again for bringing this wonderful plugin!

**Comment by jalvesaq** [comment]
Please, see section 9.21 (_Create custom mappings for viewing data.frames or matrices_) of Nvim-R's documentation.

**Comment by kdzhang** [comment]
Thank you so much! Sorry for not reading carefully enough.
