### ISSUE TITLE
`Error: invalid multibyte character in parser` when sending lines to external terminal

### ISSUE THREAD

**Issue by anasem** [jalvesaq/Nvim-R#667]
Thank you for all your work!
After updating R to 4.2, I was unable to send commands to the terminal on Linux.
When I send anything I get on the terminal the command followed by `M` on the same line.
Pressing enter gives the error
`Error: invalid multibyte character in parser at line 1`

I'm using kitty as an external terminal but also tried with xterm.

**Comment by jalvesaq** [comment]
I can't replicate the issue with either `foot` or `xterm` on Sway window manager, but a similar problem was fixed about a month ago: https://github.com/jalvesaq/Nvim-R/pull/661

**Comment by anasem** [comment]
Thank you, yes it seems this was the issue! I was still on `stable` branch.
