### ISSUE TITLE
Error: object 'X' not found

### ISSUE THREAD

**Issue by ewancarr** [jalvesaq/Nvim-R#67]
Whenever I call help from R (e.g. `$ ?summarise`), I see the error "`Error: object 's' not found`". 

![image](https://cloud.githubusercontent.com/assets/1553551/15365987/43cdaf7a-1d1a-11e6-9c8d-6e2ea9e19967.png)

The help file is then loaded correctly (in a new tab), but is there any way to avoid seeing these error messages?

Many thanks!

(I'm on VIM 7.4.1832, Debian 8.4, R 3.2.5)

**Comment by jalvesaq** [comment]
I can't reproduce the bug. Can you try without a .Rprofile, with only the default libraries loaded (nvimcom is loaded by Nvim-R), and with a minimal vimrc like the below one?:

```vim
set nocompatible
call plug#begin('~/.config/nvim/plugged')
Plug 'jalvesaq/Nvim-R'
call plug#end()
filetype plugin indent on
syntax on
let R_tmux_split = 1
```

**Comment by ewancarr** [comment]
Sorry for the *very* slow reply. 

* Your minimal configuration did not reproduce the problem, and after some trial and error, I've identified (I think) the problem as a clash with key mappings related to the [`vim-colemak`](https://github.com/jooize/vim-colemak) package.

* If I remove this package, the problem goes away. So this isn't a bug in Nvim-R at all, and **this issue can be closed**. 

(Now I just need to work out how to modify `vim-colemak` to avoid this clash.). Thanks!

**Comment by jalvesaq** [comment]
Thanks for the feedback!
