### ISSUE TITLE
debugger hangs on error

### ISSUE THREAD

**Issue by slagtermaarten** [jalvesaq/Nvim-R#672]
Hi 
Thanks (again) for developing this amazing plugin.
Lately, my R session in Vim hangs every time I send some syntactically incorrect code to the R debugger (browser()) and in general when I get an R error. CTRL-C will not let me break out, only waiting for like a minute will get me out (which gets frustrating.. quickly). I don't seem to have this problem in terminal R. Any idea what this could be?
Thanks,
Maarten

**Comment by jalvesaq** [comment]
I'm sorry, but I'm not able to replicate the issue. Could you give an example, please?

**Comment by slagtermaarten** [comment]
Hi, I'm sorry too, I can't replicate the issue anymore. I'm a bit embarrassed but happy I can keep working now. Thanks for you quick response!

**Comment by jalvesaq** [comment]
Thanks for the feedback. Please, reopen the issue if it appears again.
