### ISSUE TITLE
Local Leader Not Working

### ISSUE THREAD

**Issue by amarakon** [jalvesaq/Nvim-R#673]
I added this in my `init.vim`:

```vim
" Change Leader and LocalLeader keys:
let maplocalleader = ','
let mapleader = ';'
```

But whenever I try `,rf` or `;rf`, it just replaces the current character with `f`.
I am sure that the file I am editing is an R script because the file type is *r*.

**Comment by jalvesaq** [comment]
When this happens it's because Nvim-R isn't enabled. Perhaps, it's not properly installed. Do you see Nvim-R files listed by the command `:scriptnames`?

**Comment by amarakon** [comment]
I do see the Nvim-R files with the command `:scriptnames`.
I do not think this is an issue with it not being installed.
For example, I remember setting the option `let rmd_syn_hl_chunk = 1` and that successfully allowed chunk header options to be highlighted.
If you want, you can check my Neovim [configuration](https://github.com/amarakon/.config/blob/master/nvim/init.vim) file.
I did not install this plugin via a plugin manager, but the files are there.

**Comment by jalvesaq** [comment]
I couldn't see any problem in your `init.vim`. But I can't fix the issue because I can't replicate it.

**Comment by amarakon** [comment]
I figured out the solution, I had my `timeoutlen` too low. https://stackoverflow.com/questions/11560294/vim-leader-not-working

**Comment by jalvesaq** [comment]
Thanks for the feedback!
