### ISSUE TITLE
Indentation in Rd files: does not work with `\examples` or `\dontrun`

### ISSUE THREAD

**Issue by iago-pssjd** [jalvesaq/Nvim-R#677]
Why does indentation work with `\format` or `\description` but it does not with `\examples` or `\dontrun`? I mean, after `\description{` or `\format{` and pressing return, the cursor is placed in next line in column 9, while after `\examples{` or `\dontrun{` and pressing return, the cursor gets placed in column 1. Same after `gg=G`.

Thanks!

**Comment by jalvesaq** [comment]
I wrote the script long ago, and I don't remember the reason for not indenting. If it was not a mistake, I guess if we indent the code it will also get indented in the final document (HTML, PDF, or plain text).

**Comment by iago-pssjd** [comment]
Thanks for the answer, @jalvesaq.

> If it was not a mistake, I guess if we indent the code it will also get indented in the final document.

May you test this to confirm it? Otherwise, might you tell me which is the script I should look at and the part of the code where indentation is specified, so I may test the behaviour after including `\examples` and `\dontrun`?

**Comment by jalvesaq** [comment]
Yes, I confirm. You can also manually indent the example in an `.Rd` file, build and install the package and see the result. So, I think it is correct to not indent the code within `\example{}` and `\dontrun{}`.

**Comment by iago-pssjd** [comment]
Thanks @jalvesaq . Then, I close the issue.
