### ISSUE TITLE
How to cancel ('_' to '<-') this shortcut key?

### ISSUE THREAD

**Issue by zihaoxingstudy1** [jalvesaq/Nvim-R#678]
How to cancel this shortcut key? , It makes it inconvenient for me to  print underline every time, I often use '=' instead of '<-', so ''<-" is not necessary for me.

**Comment by jamespeapen** [comment]
```vim
let R_assign = 0
```

https://github.com/jamespeapen/Nvim-R/wiki/Options#assignment-operator-and-rnoweb-completion-of-code-block

**Comment by jalvesaq** [comment]
Thanks, @jamespeapen !
