### ISSUE TITLE
Can't launch radian as terminal

### ISSUE THREAD

**Issue by babaolanqiu** [jalvesaq/Nvim-R#681]
I tried to start R terminal after configuring `R_path` to R executable and `R_app` to radian, and it shows
```
Usage: radian^@^@radian: error: no such option: --slave^@
```
Seems to me it passed an argument `--slave` that radian can't recognize. I can run radian and R normally out of vim. Any idea how to fix this? Thanks.

**Comment by babaolanqiu** [comment]
Yeah I have tried that (`echo R_args` in vim returns `[]`), but it still shows the same error.

**Comment by jalvesaq** [comment]
Please, try this:

```vim
let R_cmd = 'R'
```

**Comment by babaolanqiu** [comment]
Thanks, it works!
