### ISSUE TITLE
Problems rendering citations created with Rdpack

### ISSUE THREAD

**Issue by dhersz** [jalvesaq/Nvim-R#682]
Hi! I have recently started using [Rdpack](https://github.com/GeoBosh/Rdpack) to manage citations in the documentation of a package I'm developing. They don't seem to render correctly when reading the docs with Nvim-R, although they do work fine with RStudio and pkgdown.

Here's a sample documentation code from accessibility:

```r
#' Floating catchment area accessibility
#'
#' Calculates accessibility accounting for the competition of resources using
#' one of the multiple accessibility metrics in the floating catchment area
#' family. The function currently includes `2SFCA` 2-Step Floating Catchment
#' Area \insertCite{luo2003measures}{accessibility}, and `BFCA` Balanced
#' Floating Catchment Area \insertCite{paez2019demand}{accessibility}.
#' Accessibility can be calculated using multiple alternative decay functions
#' passed through the `decay_function` parameter.
#' ...
#' ...
#' ...
#' @references
#' \insertAllCited{}
```

This is how it gets rendered by Nvim-R:

```
Description:

     Calculates accessibility accounting for the competition of
     resources using one of the multiple accessibility metrics in the
     floating catchment area family. The function currently includes
     2SFCA 2-Step Floating Catchment Area
     \Sexpr[results=rd,stage=build]{if(!exists(".Rdpack.currefs"))
     .Rdpack.currefs <-
     new.env();Rdpack::insert_citeOnly(key="luo2003measures",package="accessibility",
     cached_env=.Rdpack.currefs)}, and ‘BFCA’ Balanced Floating
     Catchment Area
     \Sexpr[results=rd,stage=build]{if(!exists(".Rdpack.currefs"))
     .Rdpack.currefs <-
     new.env();Rdpack::insert_citeOnly(key="paez2019demand",package="accessibility",
     cached_env=.Rdpack.currefs)}. Accessibility can be calculated
     using multiple alternative decay functions passed through the
     ‘decay_function’ parameter.
```

This is how it looks in the [pkgdown page](https://ipeagit.github.io/accessibility/reference/floating_catchment_area.html) and in RStudio:

> Description
> Calculates accessibility accounting for the competition of resources using one of the multiple accessibility metrics in the floating catchment area family. The function currently includes ⁠2SFCA⁠ 2-Step Floating Catchment Area (Luo and Wang 2003), and BFCA Balanced Floating Catchment Area (Paez et al. 2019). Accessibility can be calculated using multiple alternative decay functions passed through the decay_function parameter.

I tried searching for related issues here but couldn't find any. Perhaps this is something related to, more generally, Rd macros, and not necessarily Rdpack?

**Comment by jalvesaq** [comment]
I'm no longer developing new R packages. So, it would be great if someone could do a pull request fixing the issue...

**Comment by jalvesaq** [comment]
I installed the `accessibility` package... There is no citation in the description of `floating_catchment_area`, but there is one in `cumulative_interval`. Using R-devel (4.3.0), when I press `<LocalLeader>rh` over the function name, the description appears to me as:

![image](https://user-images.githubusercontent.com/891655/197759324-d3515a27-7787-467b-a982-80fe446dffb8.png)

And, during omni completion, the floating window shows:

![image](https://user-images.githubusercontent.com/891655/197759497-ffa80bb7-c106-4ce3-8849-04e90c613acf.png)

**Comment by dhersz** [comment]
Hi @jalvesaq, thanks for looking into this. I'm not sure what happened, but now the citations also render correctly here! Very cool.

Thank you again, and if I ever come across this issue again I'll try to further investigate what's causing it. Cheers.
