### ISSUE TITLE
Long functions break the plugin 

### ISSUE THREAD

**Issue by ttunguz** [jalvesaq/Nvim-R#683]
I have a long function I use to format charts:

``` 
gg_format <- function() {
    color.background = "white"
    color.grid.major = "gray70"
    color.axis.text = "gray30"
    color.axis.title = "gray50"
    color.title = "gray30"
    theme_bw(base_size=24) +
        theme(panel.background=element_rect(fill=color.background, color=color.background)) +
        theme(plot.background=element_rect(fill=color.background, color=color.background)) +
        theme(panel.border=element_rect(color=color.background)) +
        theme(panel.grid.major.y=element_line(color=color.grid.major,size=.25)) +
        theme(panel.grid.major.x=element_line(color=color.grid.major,size=.25)) +
        theme(panel.grid.minor=element_blank()) +
        theme(axis.ticks=element_blank()) +
        theme(strip.background = element_blank())+
        theme(legend.position="bottom") +
        theme(legend.background = element_rect(fill=color.background)) +
        theme(legend.key = element_rect(colour = 'white')) +
        theme(legend.text = element_text(size=24,color=color.axis.title)) +
        theme(plot.title=element_text(color=color.title, size=24, vjust=1.25)) +
        theme(axis.text.x=element_text(size=24,color=color.axis.text, family="Roboto Mono")) +
        theme(axis.text.y=element_text(size=24,color=color.axis.text, family="Roboto Mono")) +
        theme(axis.title.x=element_text(size=24,color=color.axis.title, vjust=0, family="Roboto Mono")) +
        theme(axis.title.y=element_text(size=24,color=color.axis.title, vjust=1.25, family="Roboto Mono")) 
}
```

If I run the function through the plugin (I use F9), then I receive
```
Error: unexpected '}' in "}"
```

But I remove the trailing } and step through the function line by line (so the plugin doesn't ingest the entire function at once and then insert the } and then press f9 again, it works.

In other words I send

``` 
gg_format <- function() {
    color.background = "white"
    color.grid.major = "gray70"
    color.axis.text = "gray30"
    color.axis.title = "gray50"
    color.title = "gray30"
    theme_bw(base_size=24) +
        theme(panel.background=element_rect(fill=color.background, color=color.background)) +
        theme(plot.background=element_rect(fill=color.background, color=color.background)) +
        theme(panel.border=element_rect(color=color.background)) +
        theme(panel.grid.major.y=element_line(color=color.grid.major,size=.25)) +
        theme(panel.grid.major.x=element_line(color=color.grid.major,size=.25)) +
        theme(panel.grid.minor=element_blank()) +
        theme(axis.ticks=element_blank()) +
        theme(strip.background = element_blank())+
        theme(legend.position="bottom") +
        theme(legend.background = element_rect(fill=color.background)) +
        theme(legend.key = element_rect(colour = 'white')) +
        theme(legend.text = element_text(size=24,color=color.axis.title)) +
        theme(plot.title=element_text(color=color.title, size=24, vjust=1.25)) +
        theme(axis.text.x=element_text(size=24,color=color.axis.text, family="Roboto Mono")) +
        theme(axis.text.y=element_text(size=24,color=color.axis.text, family="Roboto Mono")) +
        theme(axis.title.x=element_text(size=24,color=color.axis.title, vjust=0, family="Roboto Mono")) +
        theme(axis.title.y=element_text(size=24,color=color.axis.title, vjust=1.25, family="Roboto Mono")) 
```

and then send

```
}
```

Thanks!

**Comment by jalvesaq** [comment]
I can't replicate the issue with R running in either Vim or Neovim built-in terminal on Linux (Ubuntu 22.04).

**Comment by PhilippVWC** [comment]
I have this kind of issue regularly. I often have to visually select the whole function first and then send the lines, to make it work.
macOS 12.4 with 
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by ttunguz** [comment]
I'm on a Mac too.

**Comment by jalvesaq** [comment]
The function has 1510 characters. Perhaps, that's too much for pasting in your terminal. Could you try a different terminal emulator? Please, see also the option `R_bracketed_paste`.

**Comment by ttunguz** [comment]
Thanks. I tried 4 different emulators: Terminal, Alacritty, Warp, & Kitty but they all failed. 

On the R_bracketed_paste, does that require Radian?
On 2022-10-25, elvis kahoro wrote:
>The function has 1510 characters. Perhaps, that's too much for pasting in your terminal. Could you try a different terminal emulator? Please, see also the option `R_bracketed_paste`.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/jalvesaq/Nvim-R/issues/683#issuecomment-1290424244
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

-- 
Tom Tunguz
tomtunguz.com

**Comment by jalvesaq** [comment]
`R_bracketed_paste` doesn't require Radian. I use it with regular R in Gnome Terminal (but your code also is sent without problems when `R_bracketed_paste=0`). You could just put it in your vimrc/init.vim and see if it makes any difference:

```vim
let R_bracketed_paste = 1
```

**Comment by ttunguz** [comment]
Thanks, I just gave that a try, but it doesn't work either. I appreciate
the help.

**Comment by jalvesaq** [comment]
Nvim-R is being superseded by R.nvim, a new project that will be inaugurated in a week at the [R-nvim](https://github.com/R-nvim) organization.
Please, check out [tmp-Nvim-R](https://github.com/jalvesaq/tmp-R-Nvim) and help us to find the last remaining bugs before R.nvim inauguration.
When the project is officially started, you will be able to open issues there and request new features.

Nvim-R will remain alive as a feature-frozen project for Vim users. If you want to know the reason, please, see [this discussion](https://github.com/jalvesaq/Nvim-R/discussions/797).

Anyway, the R.nvim, at least initially, will not have a command to send function lines to R.
