### ISSUE TITLE
error message fail: invalid version specification

### ISSUE THREAD

**Issue by srearl** [jalvesaq/Nvim-R#687]
I am encountering an unusual, sporadic error that is affecting the output message of R coding errors. When I run R code that contains an error, I typically get a message indicating the cause or source of the R error, as would be expected, but quite often now the error message is  `Error: invalid version specification ‘0.68’` without any other details. This is perhaps best explained with an example. In the simple, toy workflow below, I select a column from the `mtcars` data set. If coded correctly, the chain executes and we get the expected output where that lone mpg column is isolated from the data frame. In the second bit of code where the dplyr select statement is misspelled, the execution fails and generates the expected error message. In the third bit of code, however, where I select a non-existent column, the execution fails and generates the unhelpful error message. I am not seeing this behaviour in RStudio so assume it is related to Nvim-R. I am not certain if this is related but I began seeing this odd behaviour only after upgrading to Ubuntu 22 from 20. Are any other Nvim-R users experiencing this? Thanks for any thoughts and advice!

```r
# works
mtcars |>
dplyr::select(mpg)

```

```r
# fails and reports expected error
mtcars |>
dplyr::selecd(mpg)

```
> Error: 'selecd' is not an exported object from 'namespace:dplyr'

```r
# fails and generates cryptic error
mtcars |>
dplyr::select(mp4)
```

> Error: invalid version specification ‘0.68’

sessionInfo()

R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] nvimcom_0.9-132

loaded via a namespace (and not attached):
 [1] fansi_1.0.3      assertthat_0.2.1 utf8_1.2.2       dplyr_1.0.9      R6_2.5.1         DBI_1.1.3        lifecycle_1.0.1  magrittr_2.0.3   pillar_1.8.1     rlang_1.0.4
[11] cli_3.3.0        ellipsis_0.3.2   vctrs_0.4.1      generics_0.1.3   tools_4.2.1      glue_1.6.2       purrr_0.3.4      compiler_4.2.1   pkgconfig_2.0.3  tidyselect_1.1.2
[21] tibble_3.1.8

**Comment by jalvesaq** [comment]
I can replicate the issue, but I get the same result if I run R in a terminal emulator and copy and paste the commands. So, there is a difference between R in a terminal emulator (regardless of `nvimcom` being loaded or not) and R in RStudio.

**Comment by srearl** [comment]
Indeed. Thank you @jalvesaq for catching that, and I apologize for not having thought to check that before posting the issue. I will close this, and see if we can get some insight from, possibly, the RStudio group (devtools is another library throwing this error and I wonder now if this is a quirk specific to their packages). Thanks, as always, for your quick and helpful responses!
