### ISSUE TITLE
Indentation bug. Known?

### ISSUE THREAD

**Issue by iago-pssjd** [jalvesaq/Nvim-R#688]
Hello Jakson,

First of all thank you very much for the big job done with this great plugin.

I report here an indentation issue, which I do not know if it is known or related to some of the examples in:

https://github.com/jalvesaq/R-Vim-runtime/blob/531ea73a5168654f31be65d53df77f79af2c5b09/tests/indent_test.R#L605-L685

This issue is related to `data.table` chaining (https://rdatatable.gitlab.io/data.table/articles/datatable-intro.html#c-chaining), that is
```r
DT[ ...
   ][ ...
     ][ ...
       ]
```
with which R-Vim-runtime indentation behaves well usually, but,
```r
items[, `:=` (var = fifelse(`Survey name` != "MASTER", sub("^t\\d_", "", `Variable name`), `Variable name`),
	      `Step name` = fcase(`Step name` == "R BTQ", "BTQ",
				  `Step name` == "adapted CSRI", "CSRI",
				  grepl("^COVID-19-related", `Step name`), "COVID-19",
				  rep(TRUE, .N), sub("(^[^ ]*)\\s.*$", "\\1", `Step name`)
	      )
)
][, `:=` (var = fcase(`Step name` == "COVID-19" & var == "covid19_baseline_01_1", "covid19_01_1",
		      `Step name` == "COVID-19", sub("baseline_0", "", var),
		      rep(TRUE, .N), var),
       `Step name` = sub(" \\(baseline\\)", "", `Step name`))]
items <- na.omit(items, cols = "var")
```
so `` `Step name` `` in second line is rightly aligned with `var` in first line, and the same for the next 3 lines, but the first alone `)` is not aligned with the function which it closes, `fcase`, the next `)` also is not aligned with the `(var =` parenthesis, and mainly `][` is placed at column 1, this even if the previous 2 parenthses are placed together at the end of previous line `` rep(TRUE, .N), sub("(^[^ ]*)\\s.*$", "\\1", `Step name`))) ``.

Thanks for your help and time!

**Comment by jalvesaq** [comment]
Thanks for reporting the issue! I'll accept a pull request to [R-Vim-runtime](https://github.com/jalvesaq/R-Vim-runtime) that fixes the issue if it doesn't introduce new bugs. Please, see: https://github.com/jalvesaq/R-Vim-runtime/blob/master/tests/indent_test.R
