### ISSUE TITLE
How to disable Nvim-R for certain filetypes?

### ISSUE THREAD

**Issue by juliantao** [jalvesaq/Nvim-R#689]
Hi,
Thanks for the great plugin. I wonder if there is a way to disable Nvim-R for certain file types such as quarto?

**Comment by jalvesaq** [comment]
You can disable the three commands that are specific to Quarto with

```vim
let R_disable_cmds = ['RQuartoRender', 'RQuartoPreview', 'RQuartoStop']
```

But you can't disable the whole plugin only for the Quarto file type. There is an undocumented variable at the beginning of each ftplugin script but it's a global variable that disables the whole plugin: `g:disable_r_ftplugin`. So, we would have to:

1. Turn the variable into a buffer variable, `b:disable_r_plugin`, whose value could be set by an autocommand in the vimrc/init.vim.
2. Create a new Nvim-R option which would be a list of file types that should have the plugin enabled. Its default value would be:

```vim
R_filetypes = ['r', 'rmd', 'rrst', 'rnoweb', 'quarto', 'rhelp']
```

However, before doing any of the above, I would like to know your reasons. If there is already a better plugin for Quarto, I may follow the easiest path and simply drop support for Quarto from Nvim-R.

**Comment by juliantao** [comment]
Thanks for the quick reply. The real reason is actually not due to Quarto file type itself. It is more related to key mapping conflicts.

 I am using `vimwiki` and `taskwiki` and set any `vimwiki` files to `quarto` so the files would have a combined `vimwiki.quarto` filetype. If `Nvim-R` is installed, all its default key mapping will be enabled, but they will clash with those for `taskwiki`, especially, the ones starting with `<localleader>t`. 

I tried different ways to remap some keys from either the `Nvim-R` side or the `taskwiki` side, but it becomes very tedious and clumsy. But I do like to have `Nvim-R` to be activated on all the `R` files. 

Any better route to solve my problem?

Thank you.

**Comment by jalvesaq** [comment]
Thanks for the feedback. I'm adding the option `R_filetypes`.

**Comment by juliantao** [comment]
Thank you!
