### ISSUE TITLE
g:r_indent_op_pattern is undefined when working from a Quarto file

### ISSUE THREAD

**Issue by BarbaraRobson** [jalvesaq/Nvim-R#691]
I updated R, neovim and NVim-R a few days ago. I'm now running R 4.2.1, nvim 0.8.0 and NVim-R 0.9.17 under Windows 10 Enterprise. Great to see all the improvements since I last updated!

One minor issue I ran into is that when I run R from a Quato (.qmd) file, "g:r_indent_op_pattern" is undefined, which causes "op_pattern" to be undefined and triggers an error message every time I send a line to R. On starting R, I get the error messages: 
> Error detected while processing FuncUndefined Autocommands for "StartR"..
> line 1665:
> E121: Undefined variable: r_indent_op_pattern
> E116: Invalid arguments for function get
and when I send a line, I get the error message:
> Error detected while processing function SendLineToR:
> line 96:
> E716: Key not present in Dictionary: "op_pattern"
> Not ready yet

This doesn't happen when I work from a normal .R file, only when I work from a Quarto file. It is fixed if I define "r_indent_op_pattern" in init.vim:
> let r_indent_op_pattern = '\(&\||\|+\|-\|\*\|/\|=\|\~\|%\|->\)\s*$'

But I thought I'd report it so it's easy to find for anyone else encountering the same issue.

**Comment by jalvesaq** [comment]
I did not yet send the runtime files, including support for Quarto, to either Vim or Neovim. Could you install [R-Vim-runtime](https://github.com/jalvesaq/R-Vim-runtime)?

I added auto omni completion of YAML fields following the `#| ` string in the [pipe_data_frame](https://github.com/jalvesaq/Nvim-R/tree/pipe_data_frame) branch. It would be good if you could try it and report any bugs before I merge it into the master branch.

**Comment by jalvesaq** [comment]
I fixed the issue in the pipe_data_frame branch because I would have trouble trying to merge it later if I had fixed it directly in the master branch.
