### ISSUE TITLE
Weird rendering issue with chunk brackets ```{r} ```

### ISSUE THREAD

**Issue by Adrilord** [jalvesaq/Nvim-R#692]
Hello, 
When I use Rmd files, the chunk brackets ```{r} ```does not correctly appear if there is a line break before it in the file :
![issue_Nvim-R_screenshot_0](https://user-images.githubusercontent.com/16454877/200331519-7546c75f-1aa6-401b-88cd-f81af6c8efcb.png)
![issue_Nvim-R_screenshot_1](https://user-images.githubusercontent.com/16454877/200331540-c6d8a926-6755-4e08-bd83-d3a097c0c8d2.png)

I didn't see any issue related to this one so I thought posting one here.
It doesn't seem to be a normal behavior and I don't know if it comes from my configuration. If it can help, here is the plugin I used alongside NVim-R (I don't have specific setting specific to NVim-R):
![issue_Nvim-R_screenshot_2](https://user-images.githubusercontent.com/16454877/200332173-e0b7d119-b097-4117-a336-d365eaa9472b.png)

**Comment by jalvesaq** [comment]
I can't see the same issue here. Three hyphens at the beginning of the file delimit the beginning of the YAML header, so everything below would be highlighted as YAML code. One or more hyphens below a word or sentence turn that sentence into a section title. So, what is the purpose of the sequence of four hyphens in the middle of the document surrounded by empty lines?

**Comment by Adrilord** [comment]
This is a .rmd file and the three hyphen characters are standard use in the beginning of the file for knit to understand the output file for example. They don't have any purpose here outside showing that I left a line space. The issue is still here even if I remove them :
![issue_Nvim-R_screenshot_3](https://user-images.githubusercontent.com/16454877/200866377-39aad944-5514-4c89-bf1b-975d0c9788f4.png)

![issue_Nvim-R_screenshot_4](https://user-images.githubusercontent.com/16454877/200866403-eda208e8-84dd-46aa-a807-95b6f92802a4.png)

Note that the brackets on the second image are still physically here as I can execute the chunk code normally, they are just not rendered.

**Comment by jalvesaq** [comment]
I'm sorry, but I can't replicate the issue. What is the output if you put the cursor on the wrongly highlighted code and do in Normal mode:
```
:echo 'hi<' . synIDattr(synID(line('.'),col('.'),1),'name') . '> trans<' . synIDattr(synID(line('.'),col('.'),0),'name') . '> lo<' . synIDattr(synIDtrans(synID(line('.'),col('.'),1)),'name') . '>'
```
?

It should print the name of the highlight group in use.
