### ISSUE TITLE
Error [nvimcom]: Invalid message received

### ISSUE THREAD

**Issue by chriskisskiss** [jalvesaq/Nvim-R#694]
Hi,

trying to use external RStudio since I don't get happy with the Nvim-R's object browser.
RStudio is starting without error.
I get the following message no matter which command I send:
`Error [nvimcom]: Invalid message received: T6703854861469651040sendToConsole("library(ggplot2)", execute=TRUE)`
Sight reading the c code I see that a leading T is always handled as an error.
Using nvim v0.8.0, MacOS Monterey, Apple M1.

Thank you!

**Comment by jalvesaq** [comment]
Thanks for reporting the bug. I could replicate it on LInux and it should be fixed now, but, please, reopen it if not fixed on MacOS.

**Comment by a-torgovitsky** [comment]
I am having this problem on Linux after recently updating Nvim-R:
```r
Error [nvimcom]: Invalid message received: T1257137979647630758sendToConsole("a <- 5", execute=TRUE)
```

**Comment by jalvesaq** [comment]
@a-torgovitsky, it should work on the `stable` branch now.

**Comment by a-torgovitsky** [comment]
I can confirm that it works on the `stable` branch now. Thanks!
