### ISSUE TITLE
<leader>aa not mapped for unclear reasons

### ISSUE THREAD

**Issue by DM1NIK** [jalvesaq/Nvim-R#697]
Hello sorry for opening the ticket on the wrong repo before.

So for me, some commands like <leader>aa are not mapped at all and I have no clue why. 

My setup is rather simple.

I use packer to install plugins:

```
 use {
      'folke/neodev.nvim',
      config = function()
          require('neodev').setup()
      end,
  }
  use {'jalvesaq/Nvim-R'}
  use {
      'lukas-reineke/headlines.nvim',
      config = function()
          require('headlines').setup()
      end,
  }
  use 'vim-pandoc/vim-pandoc'
  use 'vim-pandoc/vim-pandoc-syntax'

```

the mapping `<leader>aa` is not mapped (neither is `<leader>a`) by anything it just automatically defaults into append. I am honestly not sure how to recreate it.

Would it be possible for someone to show me their :map output for the Nvim-R section so I can take a look at it and perhaps add the keybindings myself?

Thank you very much.

**Comment by jalvesaq** [comment]
Nvim-R maps `<LocalLeader>`  and not `<Leader>` because it's activated by the ftplugin scripts.

You can see all your key bindings in Normal mode with the command `:nmap`.

I can't replicate the issue. That is, the Normal mode command `<LocalLeader>aa` sends to R Console a command to make R source a temporary copy of the whole R script.

**Comment by jalvesaq** [comment]
Note: `<LocalLeader>aa` is available only for R scripts, not for Rmd, Rhelp, or Quarto.

**Comment by DM1NIK** [comment]
> Note: <LocalLeader>aa is available only for R scripts, not for Rmd, Rhelp, or Quarto.
Ah thank you very much. Didnt' know that. 

So the only real way to run the whole file is by using commands like `<localleader>kr` or similar to build the whole Rmd file?

**Comment by jalvesaq** [comment]
There is also `<LocalLeader>ch` (send the code of all chunks until here).

**Comment by DM1NIK** [comment]
Ah wow, this works. 

Thank you very much.
