### ISSUE TITLE
failed to get Title triggered by omnicompletion

### ISSUE THREAD

**Issue by nks1974** [jalvesaq/Nvim-R#698]
it appears that omnicompletion triggers   line 1834 in   nclientserver.c 

after latest update 9 days ago

[ClientServer] Failed to get Title from kscMisc.          

if

one comments out the overwrite of completeopt in common_buffer.vim line 21 to 30

which

one would do because it for some reason resets to menuone,longest

**Comment by jalvesaq** [comment]
The object kscMisc is from what R package? How can I replicate the bug?

**Comment by nks1974** [comment]
> The object kscMisc is from what R package? How can I replicate the bug?

That is a private package that is missing a Title. Sry.

The issue is gone after removing the package.  

Thanks!

**Comment by jalvesaq** [comment]
Thanks for the feedback!
