### ISSUE TITLE
How can I hide Object Browser

### ISSUE THREAD

**Issue by iago-pssjd** [jalvesaq/Nvim-R#699]
After open the Object browser with `\ro`, I try to hide it with `:set hidden` or `:set bufhidden=hide` without any effect. Is there some way to hide it without closing it?
Thank you!

**Comment by jalvesaq** [comment]
You can close it with the same command used to open it: `<LocalLeader>ro`

**Comment by iago-pssjd** [comment]
But I want to preserve it in the buffer

**Comment by jalvesaq** [comment]
The object browser is created with these options (see `ftplugin/rbrowser.vim`):

```vim
setlocal noswapfile
setlocal buftype=nofile
setlocal nowrap
setlocal iskeyword=@,48-57,_,.
setlocal nolist
setlocal nonumber
setlocal norelativenumber
setlocal nocursorline
setlocal nocursorcolumn
setlocal nospell
```

I don't know if `buftype=nofile` is relevant to what you want to do...
