### ISSUE TITLE
Upcoming Neovim Job API Change

### ISSUE THREAD

**Issue by starcraftman** [jalvesaq/Nvim-R#7]
Just a friendly advanced warning. Changes mainly affect jobstart invocation & handler function.

See https://github.com/neovim/neovim/pull/2247.

**Comment by jalvesaq** [comment]
I adapted the code for the new API (https://github.com/jalvesaq/Nvim-R/commit/98306bee8b0222013a93065400812f25ffa85d2b), but I think we should let this issue open until the pull request 2247 is applied.

**Comment by tarruda** [comment]
@jalvesaq what do you think of the new API?

**Comment by jalvesaq** [comment]
@tarruda I prefer the new API. The use of JobActivity seems to me to be a strange way of setting a callback function. I also like the dictionary with a list of options because it gives more flexibility for programmers.
