### ISSUE TITLE
RBuildTags produced deprecated etags file - need ctags format

### ISSUE THREAD

**Issue by pasha2718** [jalvesaq/Nvim-R#70]
`RBuildTags` invokes R's `rtags(ofile="TAGS")`, which creates a `TAGS` file in etags format.  NeoVim has deprecated support for this etags format, though etags does work in old-school vim.  

My suggestion is to install Universal-Ctags, and create a `tags` file with `ctags *.R` .  This file is compatible and works great.  You could set `RBuildTags` to do the same, and warn if universal-ctags is not installed, or warn if the original ctags is installed.  It's a friendlier error than `E431`, for sure.

See:  https://github.com/neovim/neovim/issues/4856

**Comment by jalvesaq** [comment]
The nvimcom package has the function `etags2ctags()`. So, instead of requiring an external program, we use what we already have. Please, reopen the issue if the next commit does not fix the problem.
