### ISSUE TITLE
Missing links to removed sections of documentation

### ISSUE THREAD

**Issue by jamespeapen** [jalvesaq/Nvim-R#700]
With the new nvim-cmp integration, there are some documentation sections that were removed, but still have links to them.

[Nvim-R-reload-html](https://github.com/jalvesaq/Nvim-R/blob/ea7a36054dae836a476b77a24217b184acd83752/doc/Nvim-R.txt#L1955)
[Nvim-R-quick-setup](https://github.com/jalvesaq/Nvim-R/blob/ea7a36054dae836a476b77a24217b184acd83752/doc/Nvim-R.txt#L164)

**Comment by jalvesaq** [comment]
Thanks for reporting the issue! I will remove the links.
