### ISSUE TITLE
Unknown function: RComplAutCmds

### ISSUE THREAD

**Issue by jpasquier** [jalvesaq/Nvim-R#701]
Dear Jackson

Thank you for this plugin which I use daily for my job.

I get sometimes the following error message:

```
Error detected while processing /home/jerome/.local/share/nvim/plugged/Nvim-R/R/start_ncs.vim:
line  519:
E117: Unknown function: RComplAutCmds
Press ENTER or type command to continue
```

I use neovim 0.7.0 with vim-plug as plugin manager

Steps to reproduce:

Minimal in init.vim:

```
call plug#begin('~/.local/share/nvim/plugged')
Plug 'jalvesaq/Nvim-R'
call plug#end()
```

Create two empty files: `touch test.txt test.R`

Open the text file: `nvim -u minimal.vim test.txt`

Open the R file in a split: `:sp test.R`

The error message appears.

Thank you for your help

**Comment by jalvesaq** [comment]
I have seen this early today, but It might have been fixed about two hours ago (https://github.com/jalvesaq/Nvim-R/commit/4fa298bf992ecfced5fe563fac85be9e65379245).

**Comment by jalvesaq** [comment]
I can replicate the bug now.

**Comment by jpasquier** [comment]
Thank you very much!
