### ISSUE TITLE
"E117: Unknown function: RSimpleCommentLine"  on \o

### ISSUE THREAD

**Issue by esaru** [jalvesaq/Nvim-R#703]
Hi,

Apologies if this is already known. 

There are three interrelated parts to this report...and a forth comment.
 
1) I'm getting an error:

"E117: Unknown function: RSimpleCommentLine"  after \o.

At least on the surface, however, the line send executes and appends output into the buffer.

2) Numbering.  Issue report #49, "customizing R comment string not working #49" refers to section 4.5 in the help file, which appears to be missing in the current help file - ":help Nvim-R" goes from 4.4 to 4.6 directly.  I did find the correct section is 6.12

3) I solved the error by explicitly enabling comments in the .vimrc, eg

let R_enable_comment = 1

However, if the line is left out, or set to 0, I get the error...

4) Thank-you for Nvim-R!  It is a pleasure to use. 

Details are as follows:

MacVim 9.0.472, Nvim-R reports itself to be 0.9.17, using Vundle as a package manager, R is 4.2.2 "Innocent and Trusting", MacOS 11.7 running on an M1.

barebones .vimrc:

filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'jalvesaq/Nvim-R'
call vundle#end()
filetype plugin indent on

"    if R_enable_comment left unset, error
"let R_enable_comment = 0 "error
"let R_enable_comment = 1 "no error

test.R:

x <- c(1)
ls()

to replicate, nothing but:

\rf
\o

Best,
Eric

**Comment by jalvesaq** [comment]
Thanks for reporting the bug! I have made the ability to comment strings optional and didn't remember that this function was used by `<LocalLeader>o`. I'll fix it later today.
