### ISSUE TITLE
Error about no matching buffer when start R for folders with CJK characters

### ISSUE THREAD

**Issue by hongyuanjia** [jalvesaq/Nvim-R#709]
Neovim pops up an error whenever I start R using Nvim-R if the current working directory contains some Chinese characters on Windows:

```vim
Error detected while processing function ROnJobStdout[30]..SetNvimcomInfo:
line   36:
E94: No matching buffer for term://~\Desktop\中文//22800:Rterm.exe --no-save
```

The error comes from here:

https://github.com/jalvesaq/Nvim-R/blob/ea05f960e18930c474233ec20342be2402c7e0d9/R/start_r.vim#L257-L276

It seems that `sbuffer` cannot handle this case? `sbuffer` should work fine for Chinese characters, as `:exe 'sb 测试.R'` works.

Maybe besides saving R terminal buffer name in `g:rplugin`, Nvim-R can also save the buffer number, saying `g:rplugin["R_bufnr"]`, and use `exe 'sb ' . g:rplugin["R_bufnr"]` to do the postprocessing?

**Comment by jalvesaq** [comment]
Thanks for reporting the issue and pointing to the solution. It should be fixed now.

**Comment by hongyuanjia** [comment]
Thanks, @jalvesaq! I confirm that it works now!
