### ISSUE TITLE
Specifying pane for R console.

### ISSUE THREAD

**Issue by wpoosanguansit** [jalvesaq/Nvim-R#71]
HI,

I managed to get the plugin to work but I am not sure how to specify a specific pane for the R console to run in.  I am using tmuxinator and I have a small pane for running the R console in the second pane.  Right now if I issue \rf, a new terminal window would just pop up.  I hope that can be configured easily.  Thanks for your help.

**Comment by jalvesaq** [comment]
I don't know about tmuxinator...
You cannot start R in an existing Tmux pane, but if Vim is already running inside a Tmux session, the plugin can split the window and run R in one of the resulting panes. Please, put in your vimrc:
```
let R_tmux_split = 1
```
If you prefer the two panes side by side:
```
let R_vsplit = 1
```

**Comment by wpoosanguansit** [comment]
Thanks for your help.  I did put let R_vsplit = 1 in the .vimrc but it does not seem to have any effect though.  I do not see any error either.  I assume everything is working correctly as I can do \rf and \rq to bring up a pop up window and close it. Is there any thing else that I need to install for the config to work?

**Comment by jalvesaq** [comment]
- You could try to run Vim inside Tmux.
 - You could also try Neovim instead of Vim.

**Comment by wpoosanguansit** [comment]
Thank you for your help.  I did run Vim in Tmux but the R console does not run in a split pane.  Any case, I think I will just make do for now.  Thanks again.
