### ISSUE TITLE
startup error relating to RInitStdout

### ISSUE THREAD

**Issue by dankelley** [jalvesaq/Nvim-R#710]
In case it's useful, I am passing along this message, which I see when using `init.lua` from https://raw.githubusercontent.com/hongyuanjia/dotfiles/f70321eb99edd2b4ff7a310b453ef04c1d56f3d5/dot_config/nvim/init.lua (see https://github.com/jalvesaq/Nvim-R/issues/708#issue-1511889473 for discussion of how I came to use this `init.lua`).

I am not 100% sure how old my nvim-r is.  To be honest, and this is embarrassing, my vim setup is confusing, with some 'plug' things, other 'vundle' and so forth.  But I sort of think this is independent of my neovim setup.  I am not quite ready to switch from vim to neovim because the latter sometimes causes me problems (not related to the present issue).

There is no great rush on this, of course.  It doesn't seem to hurt anything.  I think it's just trying to make a "ding" sound on my computer.  Maybe I have them turned off in the shell (I never hear such dings, and don't want to, so perhaps I turned it off in a unix config file that is years old by now).

```
Error detected while processing function RInitStdout:
line   24:
E15: Invalid expression: '69615889' echo ''^B
```

**Comment by dankelley** [comment]
(Edit: I altered the title because it was wrong. I was having another error but I got rid of a json lock file and things started working better.)

**Comment by jalvesaq** [comment]
I can't replicate the issue. The number "69615889" seems to be either `$NVIMR_ID` or `$NVIMR_SECRET`, used by nvimcom/Nvim-R to recognize the authenticity of messages coming from the TCP connection.

**Comment by dankelley** [comment]
Thanks.  I'll go ahead and close this, then.  Presumably this is the sort of wrinkle that comes from shifting things on my computer.  I am retaining all my vim configuration files because sometimes I find it (via macvim) more pleasant to use than nvim.  No worries on this, and thanks for the rapid reply, on New Year's Eve :-)

Dan.
