### ISSUE TITLE
Error detected while processing function RInitStdout when use together with treesitter markdown parser and vim-rmarkdown (pandoc-syntax)

### ISSUE THREAD

**Issue by milanglacier** [jalvesaq/Nvim-R#713]
The following config is the minimal example configuration file, put this at the `~/.config/nvim/init.lua`

```lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

local function load_plugins()
  require('packer').startup({
    {
      'wbthomason/packer.nvim',
      { 'nvim-treesitter/nvim-treesitter' },
      { 'jalvesaq/Nvim-R', branch = 'master' },
      { 'vim-pandoc/vim-pandoc-syntax' },
      { 'vim-pandoc/vim-rmarkdown', branch = 'official-filetype' },
      { "catppuccin/nvim", as = "catppuccin" }
      -- use a colorscheme that's support treesitter highlight, can be any colorscheme
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
    },
  })
end

_G.load_config = function()
  require('nvim-treesitter.configs').setup({
    ensure_installed = { "r", "markdown" },
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = { 'markdown' },
      auto_install = true,

    },
  })

  require("catppuccin").setup {}
  vim.cmd [[colorscheme catppuccin]]

end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system({ 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path })
  load_plugins()
  require('packer').sync()
  vim.cmd([[autocmd User PackerCompileDone ++once lua load_config()]])
else
  load_plugins()
  load_config()
end

```

step to reproduce:

1. make sure `~/.cache/Nvim-R` is an empty directory. (**NOTE**: this step is not necessary. Even with Nvim-R already caches a lot of data, this bug can still happen occasionally, however I can't find a stable way to reproduce it. However, if this directory is empty, then it becomes reproducible with a much higher chance).

2. put the following file `xxx.rmd` into your directory `~/test`

3. `cd test`

4. `nvim`

5. `:e xxx.rmd` (**NOTE**: if directly open the file via `nvim xxx.rmd`, then this problem won't happen. However if doing something like `:e xxx.rmd`, or what I used more frequently: `Telescope find_files`, then this problem will often happen).

the content of xxx.rmd is here: https://pastebin.com/e9ccmnY6
(to avoid markdown syntax conflict with github)

6. get the error:

```
Error detected while processing function RInitStdout:
line   24:
E15: Invalid expression: '34065148' echo 'Building completion list for "base"'^B
```

**NOTE**: the detailed content of `E15: Invalid expression: xxxxxxxxx` is different, you get different `xxxxx` every time it issues the error.

system version: macOS 12.6, apple M1
nvim version:

```
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-005.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.2/share/nvim"

Run :checkhealth for more info
```

R version: 4.2.0

**Comment by jalvesaq** [comment]
Thanks for the detailed steps to reproduce the bug! It should be fixed now.

**Comment by milanglacier** [comment]
Yes I cannot reproduce the problem now.
