### ISSUE TITLE
Nvim-R is loaded twice, causing nvimcom installation to fail

### ISSUE THREAD

**Issue by klmr** [jalvesaq/Nvim-R#715]
I am running Nvim-R 8b074b0 on NeoVim v0.8.0/AstroNvim on macOS 12.6.3.

After updating Nvim-R today (from v0.9.17), Nvim-R fails to install ‘nvimcom’ when I open an R file in Nvim, and consequently fails to establish a connection launched inside Vim via `\rf`.

`:messages` tells me:

```
Error detected while processing function RInitStdout:
line   28:
E20: Mark not set
ERROR: R exit code = 1! Please, run :RDebugInfo for details.
ERROR: R exit code = 1! Please, run :RDebugInfo for details.
```

Here’s `:RDebugInfo` (*before* launching R):

```
:RDebugInfo
RInitOut
* checking for file ‘/Users/konrad/Library/nvim/site/pack/packer/opt/Nvim-R/R/nvimcom/DESCRIPTION’ ...
 OK
* checking for file ‘/Users/konrad/Library/nvim/site/pack/packer/opt/Nvim-R/R/nvimcom/DESCRIPTION’ ... OK
* preparing ‘nvimcom’: * checking DESCRIPTION meta-information ...
* preparing ‘nvimcom’: * checking DESCRIPTION meta-information ...
 OK * cleaning src
 OK * cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘nvimcom_0.9-143.tar.gz’
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘nvimcom_0.9-143.tar.gz’
clang -arch arm64 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c nvimcom.c -o nvimcom.o

clang -arch arm64 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c rd2md.c -o rd2md.o
clang -arch arm64 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -o nvimcom.so nvimcom.o rd2md.o -F/Library/Frameworks/R.framework/.. -fram
ework R -Wl,-framework -Wl,CoreFoundation
(cd apps; make)
cc -pthread -std=gnu99 -O2 -Wall nclientserver.c -o nclientserver
Error in findpack(package, lib.loc) :    there is no package called ‘nvimcom’ Calls: <Anonymous> -> findpack Execution halted


Why build nvimcom
Nvimcom not installed

RInitErr

.build_packages() exit status 0

.build_packages() exit status 0
* installing to library ‘/Users/konrad/Library/R/arm64/4.2/library’
* installing *source* package ‘nvimcom’ ...
** using staged installation
** libs
* installing to library ‘/Users/konrad/Library/R/arm64/4.2/library’
ERROR: failed to lock directory ‘/Users/konrad/Library/R/arm64/4.2/library’ for modifying Try removing ‘/Users/konrad/Library/R/arm64/4.2/library/00LOCK-nvimcom’
Error in do_exit(status = 3) : .install_packages() exit status 3
Error in do_exit(status = status) : .install_packages() exit status 1 Execution halted

ld: warning: -undefined dynamic_lookup may not work with chained fixups
installing via 'install.libs.R' to /Users/konrad/Library/R/arm64/4.2/library/00LOCK-nvimcom/00new/nvimcom
** R
** byte-compile and prepare package for lazy loading
ERROR: lazy loading failed for package ‘nvimcom’ * removing ‘/Users/konrad/Library/R/arm64/4.2/library/nvimcom’
Error in do_exit(status = status) : .install_packages() exit status 1
Error in do_exit(status = status) : .install_packages() exit status 1 Execution halted
```

I am noticing that the messages look as if Nvim-R is trying to install the package *twice*. This is in fact a behaviour that I have already noted previously, and across multiple machines with vastly different configuration (at work, my Debian based Linux shows the same, although installing the package ultimately succeeds).

`00LOCK-nvimcom` doesn’t actually exist (although if the package installation is run twice simultaneously, it might well be created temporarily), and the R package library directory exists and is writable. And manually installing ‘nvimcom’ via the following *works*:

```sh
cd ~/Library/nvim/site/pack/packer/opt/Nvim-R/R
R CMD build nvimcom
R CMD install nvimcom_0.9-143.tar.gz
```

Afterwards, I can successfully connect to an R session launched from within Vim-R.

My `.Rprofile` and `.Renviron` files are empty. My Nvim-R settings are:

* inside `~/Library/Preferences/astronvim/lua/user/options.lua`:

```lua
return {
  g = {
    R_args = {"--quiet", "--no-save", "--no-restore"},
  },
}
```

* inside `~/Library/Preferences/astronvim/lua/user/plugins/init.lua`:

```lua
return {
  {
    "jalvesaq/Nvim-R",
    branch = "master",
    ft = {"r", "rmd"},
  },
}
```

**Comment by klmr** [comment]
Ugh. I just tried removing my `nvim` config folder and the error goes away. So this seems to be caused by an interaction with some AstroNvim configuration. It does also happen with a vanilla AstroNvim with no custom user configuration nor plugins. This will make diagnosing this issue a nightmare, since AstroNvim itself comes with a rather extensive palette of plugins.

Do you happen to have any idea where I might start digging?

**Comment by klmr** [comment]
I’ve found out that this issue already existed before the update, and in fact exists across multiple OSes. On my work computer Nvim-R usually works *despite* being launched twice. I think the reason for this is pure luck, because I am working on a much slower system and the redudant ‘nvimcom’ installation (usually, but not always!) occurs sequentially rather than concurrently.

**Comment by jalvesaq** [comment]
@klmr, how can I detect that nvimcom is being loaded twice? I have never noted that, and I have to replicate the issue to fix it. Anyway, if someone could do a pull request fixing the bug it would be even better.

**Comment by klmr** [comment]
@jalvesaq *Nvim-R* is loaded twice, not ‘nvimcom’. Anyway, please refer to the linked issue in the AstroNvim repo: this appears to be a bug in AstroNvim, not in Nvim-R. In fact I forgot to close this issue, apologies.

**Comment by jalvesaq** [comment]
Thanks for the feedback!
