### ISSUE TITLE
"Warning:  It seems that Nvim-R is installed in more than one place. "

### ISSUE THREAD

**Issue by jimrothstein** [jalvesaq/Nvim-R#716]
Setting up new machine:  running Crostini, Debian container.
- R, neovim work fine.
- But opening .R file in nvim produces WARNING below and can not start R.  `:RDebugInfo`

-- Have reinstalled, neovim, Nvim-R (using packer), R etc  but can not figure out problem.

Any obvious mistakes I made?  Thx.

===   W A R N I N G   ===                                                                                                                                                                   
┆   2                                                                                                                                                                                             
┆   3 It seems that Nvim-R is installed in more than one place.                                                                                                                                   
┆   4 Please, remove one of them to avoid conflicts.                                                                                                                                              
┆   5 Below are the paths of the possibly duplicated installations:                                                                                                                               
┆   6                                                                                                                                                                                             
┆   7   /home/jim/.local/share/nvim/site/pack/packer/start/Nvim-R/                                                                                                                                
┆   8   /home/jim/.local/share/nvim/site/pack/packer/start/Nvim-R/                                                                                                                                
┆   9                                                                                                                                                                                             
┆  10 Please, uninstall one version of Nvim-R.                                                                                                                                                    
┆

:version                                                                                                                                                                                          
NVIM v0.9.0-dev-869+g964ae205a                                                                                                                                                                    
Build type: RelWithDebInfo                                                                                                                                                                        
LuaJIT 2.1.0-beta3    
```
RInitOut                                                                                                                                                                                          
   -----------------------------------------                                                                                                                                                      
nvimcom_info                                                                                                                                                                                      
{'version': '0.9-143', 'home': '/home/jim/R/x86_64-pc-linux-gnu-library/4.2', 'Rversion': '4.2.2'}                                                                                                
RInitErr                                                                                                                                                                                          
 Attaching package: ‘nvimcom’                                                                                                                                                                     
The following object is masked from ‘package:utils’:      vi 
```

**Comment by jalvesaq** [comment]
What's the output of `:echo &rtp` ? Is `/home/jim/.local/share/nvim/site/pack/packer/start/Nvim-R/` duplicated there?

**Comment by jimrothstein** [comment]
You are right:   each of these 3  lines is listed twice in `&rtp`
Will remove and post result back here.
Thx !

```
/home/jim/.local/share/nvim/site/pack/*/start/*,

/home/jim/.local/share/nvim/site/pack/*/start/*/after,

/home/jim/.local/share/nvim/site/after,
```
Remainder of `&rtp` lines are unique.
```
/home/jim/.config/nvim,
/etc/xdg/nvim,
/home/jim/.local/share/nvim/site,
/home/jim/.local/share/nvim/site/pack/packer/opt/nvim-treesitter-textobjects,
/home/jim/.local/share/nvim/site/pack/packer/start/nvim-treesitter,
/home/jim/.local/share/nvim/site/pack/packer/opt/telescope-fzf-native.nvim,
/home/jim/.local/share/nvim/site/pack/packer/start/packer.nvim,
/home/jim/.local/share/nvim/site,
/home/jim/.local/share/flatpak/exports/share/nvim/site,
/var/lib/flatpak/exports/share/nvim/site,
/usr/local/share/nvim/site,
/usr/share/nvim/site,
/usr/share/nvim/runtime,
/usr/share/nvim/runtime/pack/dist/opt/matchit,
/lib/nvim,
/usr/share/nvim/site/after,
/usr/local/share/nvim/site/after,
/var/lib/flatpak/exports/share/nvim/site/after,
/home/jim/.local/share/flatpak/exports/share/nvim/site/after,
/etc/xdg/nvim/after,
/home/jim/.config/nvim/after
```
