### ISSUE TITLE
error (?) due to locale settings

### ISSUE THREAD

**Issue by gilles13** [jalvesaq/Nvim-R#72]
OS: Windows 7x64, R-3.3x64

Hello,

I have problem with omni completion in gvim.
It seem nvimcom-install fail to detect my locale.
I have accented character in my path ("d:/ID/Données d'applications/Nvim-R")
My $NVIM_COMPL_DIR in gvim is printed as : "d\ID\DonnÃ©es d'applications\Nvim-R\omni"
I don't have file omni in this path.
Any help please ?
By the way, great job (work very well under linux)

**Comment by jalvesaq** [comment]
I can't test your setup because my Windows (10) is in English. When I include accented characters in `R_compldir`, it still works. So, you could try to put this in your vimrc:

```
let R_compldir = "d:/ID/Données d'applications/Nvim-R"
```

If the above does not work, you could try:

```
let R_compldir = "d:/ID/AppData/Local/Nvim-R"
```

**Comment by gilles13** [comment]
Work great, thank you !
Just don't understand why it's so slow to omni-complete on Windows (2-3 sec) but lightning speed on linux.
Again, excellent job.

**Comment by jalvesaq** [comment]
The first command sent to R on Windows triggers the process of listing objects in the workspace and loaded libraries. After that, the speed of omni completion should be nearly the same of that on Linux.

**Comment by gilles13** [comment]
Ok, thank you
