### ISSUE TITLE
Quitting R returns to closed file buffer

### ISSUE THREAD

**Issue by vvarik** [jalvesaq/Nvim-R#722]
If I do:

1. `nvim script.R`
2. `<localleader>rf` to open R
3. `:wq`  (after a while) to close script.R
4. `q()` in R buffer

Expectation: nvim session ends
Happens instead: I will be returned to script.R buffer and I need to close it (`:q`) again.

How to achieve the expected behaviour?

nvim-r 0.9.13, neovim 0.6.1, Ubuntu 20.04.6

**Comment by jalvesaq** [comment]
I get the same behavior if I manually start a terminal in Neovim. Example:

1. nvim script.sh
2. `:split`
3. `:terminal`
4.  `:wq` (after a while) to close shell script
5. `exit` in the shell buffer

So, if you find Neovim commands with the desired result, I will change the corresponding code in the function `SplitWindowToR()` in `R/nvimbuffer.vim`.

**Comment by jalvesaq** [comment]
Nvim-R is being superseded by R.nvim, a new project that will be inaugurated in a week at the [R-nvim](https://github.com/R-nvim) organization.
Please, check out [tmp-Nvim-R](https://github.com/jalvesaq/tmp-R-Nvim) and help us to find the last remaining bugs before R.nvim inauguration.
When the project is officially started, you will be able to open issues there and request new features.

Nvim-R will remain alive as a feature-frozen project for Vim users. If you want to know the reason, please, see [this discussion](https://github.com/jalvesaq/Nvim-R/discussions/797).
