### ISSUE TITLE
Moving windows vertically doesn't split correctly

### ISSUE THREAD

**Issue by romagnolid** [jalvesaq/Nvim-R#723]
Hello @jalvesaq, as usual thanks for the great plugin.

I noticed that when the window is splitted between script and R-terminal and I move one of the window to be at the very top/bottom using "CTRL-W J" or "CTRL-W K" (https://vimdoc.sourceforge.net/htmldoc/windows.html#window-moving), the moved window occupies the whole screen instead and the other only one line (see the prompt `>` at the very bottom), instead of half the screen each.

At startup:
![start](https://user-images.githubusercontent.com/10038298/232481064-b2938b19-8c73-47d7-b7a4-19572a33f558.png)

After moving the script window up with "CTRL-W K"
![move](https://user-images.githubusercontent.com/10038298/232481051-d923be9e-c70c-487c-b9ea-5a7fdfc0b58e.png)

I tried to remove all the other plugins but it didn't work. I wonder if it happens to others.

**Comment by jalvesaq** [comment]
You may try this in your `init.vim`:


```vim
let R_buffer_opts = "nobuflisted"
```

If using `init.lua`:

```lua
vim.g.R_buffer_opts = "nobuflisted"
```

**Comment by romagnolid** [comment]
It worked, thank you!
