### ISSUE TITLE
FR: an Rmarkdown sections/chunks browser/outline

### ISSUE THREAD

**Issue by iago-pssjd** [jalvesaq/Nvim-R#725]
Hi!

Let's start with a couple of RStudio screenshots:
![outline](https://user-images.githubusercontent.com/40892925/235171938-5420d06a-aa59-4405-bb14-9aaf28e3095c.png)
![Screenshot_2023-04-28_16-13-41](https://user-images.githubusercontent.com/40892925/235171993-97280e37-09e0-41d6-8d4e-98598171ddf2.png)

There we can see an outline of the sections of an RMarkdown file and also other of the chunks. Further, we can move through the file by selecting on them the desired section/chunk.

Is there a similar funcionality with Nvim-R? If not, could it be implemented, at least a command for seeing (like `\ro`)  the different sections/chunks?

Thanks

**Comment by srearl** [comment]
You can achieve this with the [Voom](https://github.com/vim-voom/VOoM) package, which works well for Rmd plus many other markup formats.
![Screenshot_20230428_080203](https://user-images.githubusercontent.com/8332564/235183329-f9677bfe-cecc-4c83-ae00-9d4fbf20c92a.png)

**Comment by iago-pssjd** [comment]
Thanks @srearl . Beyond using Voom, in order to configure it, I've just seen https://github.com/jalvesaq/Nvim-R/blob/093cb979650ac5b0c9b9f49d3cfd5151557668af/doc/Nvim-R.txt#L242-L250
