### ISSUE TITLE
nvim-r and packrat?

### ISSUE THREAD

**Issue by jamesdunham** [jalvesaq/Nvim-R#73]
When using packrat to create a project environment, only the packages in an isolated library are available, and packages are added to that library whenever `install.packages` is called. 

Nvim-R makes manual installation of nvimcom unnecessary, though, so I'm not sure how to force its addition to the project library. Is there a workaround?

Thanks for all your work on this; I use it every day.

**Comment by jalvesaq** [comment]
Perhaps you have to install it manually, as you do with the other packages. But, first, you have to create the package. Go to a terminal emulator and do (example for vim-plug):

```
cd ~/.config/nvim/plugged/Nvim-R/R/
R CMD build nvimcom
```

Then, in R:

```r
install.packages("~/.config/nvim/plugged/Nvim-R/R/nvimcom_0.9-16.tar.gz")
```

Does packrat change the environment variable `R_DEFAULT_PACKAGES`? If not, then, perhaps, you could set it in your .bashrc:

```
export R_DEFAULT_PACKAGES=utils,grDevices,graphics,stats,methods,nvimcom
```

**Comment by jalvesaq** [comment]
There is a discussion on packrat at https://github.com/jalvesaq/Nvim-R/issues/59

**Comment by jamesdunham** [comment]
Great, thanks. Building and installing from the tarball worked.
