### ISSUE TITLE
[solved] NVIMR_SECRET not found 

### ISSUE THREAD

**Issue by nks1974** [jalvesaq/Nvim-R#730]
Posting solved issue.

Error message from neovim when opening an R file:
> [ClientServer] NVIMR_SECRET not found 
> "ClientServer" exited with status 1

Error message in R terminal window when subsequently starting R in neovim with leader rf:
> nvimcom: Environment variable NVIMR_SECRET is missing

Cause: 
- Entry in .Rprofile 
`library(colorut)` 
`SetOutputColors()`

Solution:
- Remove the problem causing entry from .Rprofile

**Comment by jalvesaq** [comment]
This problem only affects Windows, where the compilation of `nvimcom` fails if the `~/.Rprofile` outputs anything.

You can call `SetOutputColors(verbose = FALSE)` to avoid the output.

**Comment by jalvesaq** [comment]
I closed this issue adding it to the _Known bugs_ section. Ideally, it should be fixed but I currently have no access to any Windows machine.

**Comment by nks1974** [comment]
Hi, answering here on email. The error is reproduced on Ubuntu and KDE
Plasma in my case.

In any case, I just wanted the error and a solution to be available via
google.

Openai chat did not have the right solution. It suggested setting the
NVIMRSECRET in init.vim.

Google had nothing except your C-script defining the error message.

CoPilot suggested looking into all the R config files. That is when I
looked into .Rprofile which I edited a week or two ago.

But for your guidance, it was on Ubuntu and KDE Plasma.

BR
Kristian Schmidt

**Comment by jalvesaq** [comment]
I added this to my `~/.Rprofile`:

```r
require(colorout, quietly = TRUE)
setOutputColors()
cat("Hello stdout!\n")
cat("Hello stderr!\n", file = stderr())
```

I started R directly from the terminal emulator and did `remove.packages("nvimcom")`.

Finally, I started editing an R file with Neovim which immediately triggered the compilation of `nvimcom`. The command `:RDebugInfo` shows all the output produced by the code added to `~/.Rprofile`, but the compilation was successful. So, I can't replicate the issue on Ubuntu 23.04, with R-4.3.0, and gnome-terminal.

**Comment by nks1974** [comment]
Confirmed, that works fine on my platform too.

require(colorout, quietly = TRUE)

setOutputColors()

cat("Hello stdout!\n")

cat("Hello stderr!\n", file = stderr())

Whereas

library(colorout); setOutputColors()

cause the error.

Thanks.

BR, Kristian
