### ISSUE TITLE
SendFileToR does not function if the R file is not in the current neovim working directory

### ISSUE THREAD

**Issue by jpasquier** [jalvesaq/Nvim-R#733]
Hi,

The function SendFileToR seems to be buggy. This is certainly related to #729.

Steps to reproduce:

* neovim 0.9.0 (macOS)

* minimal.vim:
```
call plug#begin('~/.local/share/nvim/plugged')
Plug 'jalvesaq/Nvim-R'
call plug#end()
```

* create a folder: `mkdir test`

* test/minimal.R:
```
2+2
```

* open R script: `nvim -u minimal.vim test/minimal.R

* call R `\rf` and send script `\aa`

Result:
```
> nvimcom:::source.and.clean("/Users/u0189152/test/test/minimal.R.tmp.R")
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file '/Users/u0189152/test/test/minimal.R.tmp.R': No such file or directory
```

Thank you for your help and best regards

**Comment by jalvesaq** [comment]
Thanks for reporting the bug!
