### ISSUE TITLE
autocomplete only works on file in home directory

### ISSUE THREAD

**Issue by Yousuf28** [jalvesaq/Nvim-R#734]
Thanks for making it possible writing R code in vim. I have configured in my macOS and everything works fine. 
But on my windows laptop I use gvim 9.0. One thing that kept me away  switching from RStudio to Vim is autocomplete.
If I create an R file in my home directory autocomplete works fine. But any R files in other directory, the autocomplete does not work.
It only show word from buffers but not from f [LS] shown in screenshot (I don't know what that is mean).
## When R file in Home directory, it works
![home](https://github.com/jalvesaq/Nvim-R/assets/31291716/9458ba83-1946-433f-9fa9-64285af788df)

## when R file not in home directory, it does not work

![not_home](https://github.com/jalvesaq/Nvim-R/assets/31291716/07b9c31a-0cd8-4532-bbbf-7674c48d4d3d)

- [here is my _vimrc for gvim](https://github.com/Yousuf28/dotfile/blob/main/_vimrc)

**Comment by jalvesaq** [comment]
The autocompletion doesn't seem to be from Nvim-R and [cmp-nvim-r](https://github.com/jalvesaq/cmp-nvim-r) because cmp-nvim-r doesn't add a `~` suffix to menu lines. Anyway, I currently don't have access to Windows to replicate and fix bugs.

**Comment by Yousuf28** [comment]
Thanks for quick reply. 
any idea/suggestions how I can get R autocomplete to work?

**Comment by jalvesaq** [comment]
Alternatives for Neovim on Linux are:
- [languageserver](https://cran.r-project.org/web/packages/languageserver/index.html) + [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) + [cmp-nvim-lsp](https://github.com/hrsh7th/cmp-nvim-lsp) +  [nvim-cmp](https://github.com/hrsh7th/nvim-cmp)
- [cmp-nvim-r](https://github.com/jalvesaq/cmp-nvim-r) + [nvim-cmp](https://github.com/hrsh7th/nvim-cmp)

**Comment by jalvesaq** [comment]
I'm closing this issue because I think you are using the [languageserver](https://github.com/REditorSupport/languageserver/) and the bug should be reported to them.
