### ISSUE TITLE
Delete key closes R

### ISSUE THREAD

**Issue by iago-pssjd** [jalvesaq/Nvim-R#740]
Is it expected that pressing the Delete key  when the cursor is on the R console closes it? 

If it was, does it depend on some configuration option?

**Comment by mschilli87** [comment]
Does not happen for me. 🤷

**Comment by iago-pssjd** [comment]
@mschilli87 To me on Windows 10

**Comment by mschilli87** [comment]
@iago-pssjd: I'm on Linux.

**Comment by jalvesaq** [comment]
If you search the web for similar issues, you may find cases of terminal emulators whose Delete key is mapped to Ctrl-D, which closes the terminal.

**Comment by iago-pssjd** [comment]
Then, being the terminal emulator Rterm, that seems to be the reason (as if I open separately Rterm.exe and type Del, it closes too). I see in the documentation that there is the option `R_external_term`, but it does not seem to be available/useful on Windows. Or is it? And in that case, which other terminal emulators are suggested?

Thanks!

**Comment by jalvesaq** [comment]
Rgui.exe used to work as an external terminal on Windows. You could try:

```vim
let R_external_term = 1
```

**Comment by iago-pssjd** [comment]
@jalvesaq  Thanks! it works.
