### ISSUE TITLE
Hover help works in R files but not in quarto files

### ISSUE THREAD

**Issue by PMassicotte** [jalvesaq/Nvim-R#741]
(Obligatory disclaimer: I am new to vim, so might be a very basic question, or not the appropriate place to post it)

When working in an R file, I can press shift+K to get into the help of a given function:

![image](https://github.com/jalvesaq/Nvim-R/assets/4519221/f1852bcc-d71d-45a6-b674-92532dc2fe4c)

However, when I am inside a quarto file, it says “man.lua: no manual entry for rnorm”

![image](https://github.com/jalvesaq/Nvim-R/assets/4519221/274a8443-e900-4892-a472-e481d3995420)

Anything I missed out?

Also, is there anyway to format the help file, so it does not show/display as a Markdown document (see first image)?

Regards,
Phil

**Comment by jalvesaq** [comment]
Are you using Vim or Neovim? Perhaps you are using the [languageserver](https://cran.r-project.org/web/packages/languageserver/index.html) in R files and [cmp-nvim-r](https://github.com/jalvesaq/cmp-nvim-r) in Quarto files...

**Comment by PMassicotte** [comment]
I am using Neovim. Digging in the documentation (https://github.com/jamespeapen/Nvim-R/wiki/Options#omni-completion), I found that one should either one. I understand that cmp-nvim-r might be “better” at completing, for example, column names in function, right? Is it possible that shift+K only works with languageserver?

**Comment by jalvesaq** [comment]
Nvim-R provides `<LocalLeader>rh`, but it only works if R is running.

**Comment by PMassicotte** [comment]
Was not aware, this works fine, thank you. I was more talking about Hover Documentation, which is not working on Quarto document.

```
-- See `:help K` for why this keymap
nmap('K', vim.lsp.buf.hover, 'Hover Documentation')
```

Maybe this is something I will have to investigate on LSP configuration. 

Thank you for your help.
