### ISSUE TITLE
Multiline raw strings are sent incorrectly to R

### ISSUE THREAD

**Issue by klmr** [jalvesaq/Nvim-R#743]
[R 4.0 raw strings](https://r4ds.hadley.nz/strings.html#sec-raw-strings) spanning multiple lines are sent to R incorrectly if they are sent as a selection.

MWE:

### `x.r`

```r
r'[
# foo
  # bar
baz
]'
```

Open the file, launch Nvim-R, select all lines, and execute `<Plug>RDSendSelection`. Inside the R terminal, the result is:

```r
[1] "\nbaz\n"
```

It seems that lines starting with `\s*#` are treated as comments and removed.

By contrast, `<Plug>RDSendLine` correctly sends the entire content of the raw string.

**Comment by jalvesaq** [comment]
Thanks for reporting the issue! I have to drop an old option: `R_commented_lines`.
