### ISSUE TITLE
Indentation when using ggplot

### ISSUE THREAD

**Issue by lokesh-krishna** [jalvesaq/Nvim-R#744]
I'm not sure if I'm missing something in my setup but the indentation that I get when using the pipe operator and moving to a new line is absent when using `+`. Is there a way I can get indentation while using `+` as well? I did go over the documentation but didn't find anything that seemed like it could help here.

**Comment by jalvesaq** [comment]
Thanks for reporting the issue! I'll accept a pull request to [R-Vim-runtime](https://github.com/jalvesaq/R-Vim-runtime) that fixes the issue if it doesn't introduce new bugs. Please, see: https://github.com/jalvesaq/R-Vim-runtime/blob/master/tests/indent_test.R
