### ISSUE TITLE
Possible glitch/bug - error message when opening R file - but everything still working

### ISSUE THREAD

**Issue by py9mrg** [jalvesaq/Nvim-R#746]
Hello,

I am trying to learn Neovim (using AstroVim, which in turn uses lazy.nvim as a plugin manager). So far I seem to have everything working but I experience something strange that may be to do with the way I've set it up or might be a bug. I have tried several ways to get rid of it but can't seem to get it to stop so I thought I'd report it.

I am using Windows 11 if that matters, will explain a bit more in a minute.

So far I have installed using lazy.nvim, so my `Nvim-R.lua` file is:

```lua
return {
  "jalvesaq/Nvim-R",
  event = "BufEnter *.R,*.r,*.Rmd,*.rmd,*.RMD",
  init = function()
      vim.g.R_path = "C:\\Users\\ME\\scoop\\apps\\r\\current\\bin\\x64"
  end
}
```

The R_path has to be set as I'm using R with scoop so I get a lot of errors about not finding R. Although it still works after! I think this is because Nvim-R looks in the registry and doesn't find R, but scoop sets up shims so all the R calls work as normal.

I don't know if my `event = ....` settings are right so this could be the cause, but I've tried a few things.

Whenever I open an R file, either after opening nvim or with nvim (e.g. `nvim blah.R`) I get the following message:

    [clientserver] Neovim window not found

Then the localleader doesn't work straight away. If I use leader, then localleader once (<space><,> in my case) it works fine. After that localleader will work fine every time. I'm not sure if these are related or whether AstroVim has a conflict.

The one other thing to mention is I only get the `[clientserver] ...` error when using nvim within Windows Terminal. I don't get it when using the terminal Neovim provides (it gives it's onw basic GUI on Windows). BUT, I do still have the strange localleader issue.

Anyway, everything still works so it's not exactly a pressing issue. But if you have some time and wanted to look into the use of other plugin managers (lazy.nvim seems to be becoming quite popular) to make sure it's not an issue then I thought I'm mention it.

**Comment by jalvesaq** [comment]
I tried lazy.nvim some months ago, but I settled on packer. I don't have access to any (real or virtual) machine running Windows where I could install any software. I also know nothing about scoop and shims. So, perhaps someone else could help you since it's very hard to fix a bug that I can't replicate. The only thing that I can do is completely remove support for Windows if it becomes too buggy.

**Comment by jalvesaq** [comment]
Can't you add the R bin directory to your `PATH` environment variable?

**Comment by py9mrg** [comment]
> I tried lazy.nvim some months ago, but I settled on packer. I don't have access to any (real or virtual) machine running Windows where I could install any software. I also know nothing about scoop and shims.

Sure, I don't think (!) it's a windows specific thing, probably a lazy.nvim thing (or rather my setup of it).

I will have a go with WSL while I think about it, that might give us an idea one way or the other. 

Did you manage to get lazy working before settling in packer? If yes could you take a look at what I have above and let me know if I'm doing something silly?

> Can't you add the R bin directory to your `PATH` environment variable?

I could, but I'm *trying* to do it the "lazy.nvim way" first and I'm not confident I'm doing it right. It's not massively important as everything works, I just get that message which makes me think either I'm doing something wrong (likely) or there might be a bug. I'll keep digging and update here if I fix it / become more confident it's not me.

**Comment by jalvesaq** [comment]
As far as I remember, lazy.nvim tries to load plugins only when they are required. The goal is to make Neovim's startup faster. However, most plugins already load their heavy functions only when they are called for the first time. So, the startup is already fast enough (less than half of a second), and I suspect that there is the risk of lazy.nvim preventing a plugin or part of it from being loaded at the right moment. Packer uses the native Vim/Neovim package management system. I prefer this.

I don't remember if I have had any specific problem with lazy.nvim.

**Comment by py9mrg** [comment]
Sorry for the delay. Ok so... I think I have worked it out:

Using the option `BufEnter`to trigger laoding  was the issue. If I either turned off lazy loading - by replacing the event line with `lazy = false`. Then the `[clientserver]` message doesn't appear. Equally, I can replace the `BufEnter` with `BufRead` or `BufReadPre` and there will be no message. So it was my fault with how I was triggering the loading of the plugin.

Interestingly, I just heard even the author of Packer has migrated to lazy.nvim recently!

**Comment by jalvesaq** [comment]
I have to replace packer... but this isn't urgent for me. Thanks for the feedback!
