### ISSUE TITLE
Support filetype `Rmarkdown`

### ISSUE THREAD

**Issue by rcst** [jalvesaq/Nvim-R#747]
Hi,

I noticed that the (awesome) plugin doesn't recognize files with extension `.Rmarkdown`. I tried including it into the newly available filetypes list variable

```
let R_filetypes = ['r', 'rmd', 'rmarkdown', 'rrst', 'rnoweb', 'quarto', 'rhelp']
```

However, it seems this list can only **disable** filetypes, not add (as the documentation might imply).

I'd like to have this "filetype" working, because I'm editing both `Rmd` and `Rmarkdown` file, which are no different in content, but the `blogdown` packages sees a [difference](https://bookdown.org/yihui/blogdown/output-format.html) as to render the former into HTML and the latter always into plain Markdown.

**Comment by jalvesaq** [comment]
Nvim-R uses Vim's default file type recognition, but `.Rmarkdown` will be recognized as `rmd` if you put this in your `vimrc`:

```vim
autocmd BufNewFile,BufRead *.Rmarkdown set ft=rmd
```

or `init.lua`:
 
```lua
vim.cmd.autocmd('BufNewFile,BufRead', '*.Rmarkdown', 'set ft=rmd')
```

**Comment by rcst** [comment]
Thanks!
