### ISSUE TITLE
 Generalizing the REPL, Noweb Features, and the Jupyter Protocol

### ISSUE THREAD

**Issue by brandonwillard** [jalvesaq/Nvim-R#75]
Since Nvim-R (and Vim-R-plugin) seems to be the best Vim REPL and noweb plugin around, I often find myself taking inspiration/code snippets from it when trying to hack together REPL capabilities for other languages (e.g. Python).  That said, any chance you've worked on, or thought about, abstracting its generic REPL and noweb features? 
At the very least, it seems like Jupyter's computing protocol could be used to generalize most of the interaction between interpreters and Vim, and, with that alone, R and Python are immediately covered.  I've tried some IPython/Jupyter plugins for Nvim, but none seems as mature as Nvim-R (in terms of comparable REPL-only features, of course), so it might not be as simple as using one of those unfortunately.

**Comment by jalvesaq** [comment]
Please, see https://github.com/jalvesaq/vimcmdline which is what I have to offer as a generalization of Nvim-R to other languages. I am sorry, but I can't look at Jupyter's protocol right now.

**Comment by jalvesaq** [comment]
I am closing the issue because I am not going to turn Nvim-R into a general plugin. I have tried this before with Vim-R-plugin and it was too complicated. I am sorry, but Nvim-R will remain as a file type plugin.
