### ISSUE TITLE
Weird behavior when setting  R_rconsole_width

### ISSUE THREAD

**Issue by luizpara** [jalvesaq/Nvim-R#751]
First, thanks for this brilliant plugin.

I have been facing two oddities when trying to set the width of the console:

1. setting nosplitright does nothing
2. using fractions wiht R_rconsole_width forces console to be open horizontally, at the bottom and fill the whole window up to the top.

Here is my .vimrc:

```
Plug 'jalvesaq/Nvim-R'
let R_rconsole_width = ceil(winwidth(0) * 0.5)
autocmd VimResized * let R_rconsole_width = ceil(winwidth(0) * 0.5)
```

The reason I want number 1 is obvious. The reason I am want number 2 is because in my rather wide monitor wit full-screen vim, the console filling half the screen (/2) is too much, but one third (/3) is too little. The ideal would be in-between.

**Comment by jalvesaq** [comment]
Unfortunately, I never managed to get this working very well. The corresponding code is in the `SplitWindowToR()` function at `R/nvimbuffer.vim`. A pull request to improve the code is welcome!

**Comment by luizpara** [comment]
@jalvesaq about the `set nosplitright` not working, I know that `:topleft vert term` works perfectly to open a vertical split to the extreme left. What I don't know is how to manually initialize a R console there that Nvim-R communicates to. But if a boolean variable like `splittofarleft` could be created so that when equal to true it added `:topleft vert term` to the relevant code that launches the vim terminal where the R console will appear, that would solve that problem smoothly.

**Comment by jalvesaq** [comment]
The `:topleft vertical terminal` command only works as expected in Vim, not Neovim. Anyway, in Neovim, the terminal must be opened with the `termopen()` command because we need its `job-id`.

**Comment by jalvesaq** [comment]
I now can replicate the issue in Vim, but not in Neovim with `init.lua`. The problem is that when either `floor()` or `ceil()` is used the result is of type "float" and not "number". The solution is to delete the ".0" string from the result. Example:

```vim
let R_rconsole_width = substitute(floor(winwidth(0) / 2) - 2, '\.0', '', '')
```
