### ISSUE TITLE
how to split the R repl to the right window rather than bottom window after type "\rf"

### ISSUE THREAD

**Issue by zihaoxingstudy1** [jalvesaq/Nvim-R#752]
how to split the R repl to the right window rather than bottom window after type "\rf"

**Comment by jalvesaq** [comment]
Please, read the section "6.14. Control of R window" of Nvim-R's documentation.

**Comment by zihaoxingstudy1** [comment]
thanks, i will read the document, i see the way to split the window is also relevant to the font size
