### ISSUE TITLE
Support lua binding for plugin initialization, for people using nvim `init.lua` with other plugin system(e.g. lazy)

### ISSUE THREAD

**Issue by Tal500** [jalvesaq/Nvim-R#753]
I'm new to Nvim and this plugin.

I'm using AstroVim, which uses Lazy as it's packer manager.

It would be nice if this package will have a "lua" dir with a setup function that calls the initialization function in vim (i.e. lua `vim.cmd("")` function) - this will make life easier to use this plugin with lua based configuration.

Now I did manage to overcome this issue, by having the following `init.lua` file:
```lua
if vim.loader and vim.fn.has "nvim-0.9.1" == 1 then vim.loader.enable() end

for _, source in ipairs {
  "astronvim.bootstrap",
  "astronvim.options",
  "astronvim.lazy",
  "astronvim.autocmds",
  "astronvim.mappings",
} do
  local status_ok, fault = pcall(require, source)
  if not status_ok then vim.api.nvim_err_writeln("Failed to load " .. source .. "\n\n" .. fault) end
end

if astronvim.default_colorscheme then
  if not pcall(vim.cmd.colorscheme, astronvim.default_colorscheme) then
    require("astronvim.utils").notify(
      ("Error setting up colorscheme: `%s`"):format(astronvim.default_colorscheme),
      vim.log.levels.ERROR
    )
  end
end

require("astronvim.utils").conditional_func(astronvim.user_opts("polish", nil, false), true)

-- User conf
vim.cmd("call plug#begin('~/.vim/plugged')")
vim.cmd("Plug 'jalvesaq/Nvim-R'")
vim.cmd("call plug#end()")
```

The init.lua file is split into two now: before the "-- User conf" we have the hard coded AstroVim setup, and after we have the Nvim-R setup via `plug.vim` as instructed in the installation guideline (note - I have `plug.vim` installed in my ".local/share" nvim files).

However, it would be nice if "lazy" users(or other nvim-lua based plugin managers) could setup this plugin by calling in Lua `require("nvim-r").setup()`

**Comment by srearl** [comment]
That seems excessive. I am in the process of making the transition from Vim to Neovim. Using Lazy as the package manager, I added Nvim-R by adding the following as a Nvim-R file in my lua/plugins directory. Worked great.

```
return {
	{
		"jalvesaq/Nvim-R",
		dependencies = {"jalvesaq/cmp-nvim-r"},
		config = function()
			require'cmp'.setup {
				sources = {
					{ name = 'cmp_nvim_r' },
				}
			}
		end
	}
}

```

**Comment by Tal500** [comment]
> That seems excessive. I am in the process of making the transition from Vim to Neovim. Using Lazy as the package manager, I added Nvim-R by adding the following as a Nvim-R file in my lua/plugins directory. Worked great.
> 
> ```
> return {
> 	{
> 		"jalvesaq/Nvim-R",
> 		dependencies = {"jalvesaq/cmp-nvim-r"},
> 		config = function()
> 			require'cmp'.setup {
> 				sources = {
> 					{ name = 'cmp_nvim_r' },
> 				}
> 			}
> 		end
> 	}
> }
> ```

Thanks for the response!

But how can we make this plugin to be loaded without cmp-nvim-r for example?
Don't know which vimscript function should I call.

**Comment by srearl** [comment]
Oh, sorry, you do not necessarily need cmp-nvim-r; to install just Nvim-R:

```
return {
  {
    "jalvesaq/Nvim-R"
  }
}

```

**Comment by Tal500** [comment]
> Oh, sorry, you do not necessarily need cmp-nvim-r; to install just Nvim-R:
> 
> ```
> return {
>   {
>     "jalvesaq/Nvim-R"
>   }
> }
> ```

This however, doesn't call the plugin setup function, just download the repo source.

**Comment by jalvesaq** [comment]
I don't use lazy.nvim, but this example might be useful: https://github.com/jalvesaq/Nvim-R/issues/746#issue-1848118787

**Comment by Tal500** [comment]
> I don't use lazy.nvim, but this example might be useful: [#746 (comment)](https://github.com/jalvesaq/Nvim-R/issues/746#issue-1848118787)

I had a better version, that we can be prettier and supported directly in this repo codebase, or can be given as an example:
https://github.com/Tal500/astronvim_config/blob/c1995fbcdb3ede5e42c98e7ecba4e954b0daba40/plugins/nvim-r.lua :
```lua
return {
  "jalvesaq/Nvim-R",
  enabled = true,
  name = "nvim-r",
  ft = function(plugin, ft)
    local function contains(table, val)
      for k,v in ipairs(table) do
        if k == val then
          return true
        end
      end
      return false
    end

    local function load(subpath)
      vim.cmd("source " .. plugin.dir .. "/ftplugin/" .. subpath .. ".vim")
    end
    
    if contains(ft, "r") then
      load("r_nvimr")
    elseif contains(ft, "quarto") then
      load("quarto_nvimr")
    elseif contains(ft, "rhelp") then
      load("rhelp_nvimr")
    elseif contains(ft, "rmd") then
      load("rmd_nvimr")
    end

    -- Anyway, this function needs to return the supported file types to register for loading
    return {"r", "quarto", "rhelp", "rmd"}
  end,
}
```

I wasn't sure which filetypes should I've added in addition.
This however doesn't load the necessary syntax files...

Any thoughts would be appreciated.

**Comment by jalvesaq** [comment]
I switched to [lazy.nvim](https://github.com/folke/lazy.nvim) today. Following `init.vim` style, my `init.lua` configuration for Nvim-R was:

```lua
--------------------------------------
-- Nvim-R
--------------------------------------
vim.g.R_openpdf = 1
vim.g.R_assign_map = '<M-->'
vim.g.R_clear_console = 0
vim.cmd([[
command RStart let oldft=&ft | set ft=r | exe 'set ft='.oldft | let b:IsInRCode = function('DefaultIsInRCode') | normal <LocalLeader>rf
    ]])

-- vim.g.R_external_term = "foot -a R -T R --log-level error"
-- Close R automatically, but only if it's running in an external terminal
if vim.fn.exists('g:R_external_term') then
    vim.cmd([[
    autocmd VimLeave * if exists("g:SendCmdToR") && string(g:SendCmdToR) != "function('SendCmdToR_fake')" | call RQuit("nosave") | endif
        ]])
end

require("lazy").setup({
  { dir = '~/src/Nvim-R'  },
}, {})
```

Now, it is:


```lua
require("lazy").setup({
  {
      dir = '~/src/Nvim-R',
      init = function()
          vim.g.R_openpdf = 1
          vim.g.R_assign_map = '<M-->'
          vim.g.R_clear_console = 0
          vim.cmd([[
          command RStart let oldft=&ft | set ft=r | exe 'set ft='.oldft | let b:IsInRCode = function('DefaultIsInRCode') | normal <LocalLeader>rf
              ]])

          -- vim.g.R_external_term = "foot -a R -T R --log-level error"
          -- Close R automatically, but only if it's running in an external terminal
          if vim.fn.exists('g:R_external_term') then
              vim.cmd([[
              autocmd VimLeave * if exists("g:SendCmdToR") && string(g:SendCmdToR) != "function('SendCmdToR_fake')" | call RQuit("nosave") | endif
                  ]])
          end
      end
  },
}, {})
```

Both do the same thing: they create global variables and auto commands. Of course, it would be better to use local Lua variables instead of global Vim ones. But Nvim-R is very old (see https://www.vim.org/scripts/script.php?script_id=2628) and still supports Vim which doesn't use Lua for configuration. Unfortunately, I don't have spare time to keep two systems, one for Vim and another for Neovim.

**Comment by Tal500** [comment]
> I switched to [lazy.nvim](https://github.com/folke/lazy.nvim) today. Following `init.vim` style, my `init.lua` configuration for Nvim-R was:
> 
> ```lua
> --------------------------------------
> -- Nvim-R
> --------------------------------------
> vim.g.R_openpdf = 1
> vim.g.R_assign_map = '<M-->'
> vim.g.R_clear_console = 0
> vim.cmd([[
> command RStart let oldft=&ft | set ft=r | exe 'set ft='.oldft | let b:IsInRCode = function('DefaultIsInRCode') | normal <LocalLeader>rf
>     ]])
> 
> -- vim.g.R_external_term = "foot -a R -T R --log-level error"
> -- Close R automatically, but only if it's running in an external terminal
> if vim.fn.exists('g:R_external_term') then
>     vim.cmd([[
>     autocmd VimLeave * if exists("g:SendCmdToR") && string(g:SendCmdToR) != "function('SendCmdToR_fake')" | call RQuit("nosave") | endif
>         ]])
> end
> 
> require("lazy").setup({
>   { dir = '~/src/Nvim-R'  },
> }, {})
> ```
> 
> Now, it is:
> 
> ```lua
> require("lazy").setup({
>   {
>       dir = '~/src/Nvim-R',
>       init = function()
>           vim.g.R_openpdf = 1
>           vim.g.R_assign_map = '<M-->'
>           vim.g.R_clear_console = 0
>           vim.cmd([[
>           command RStart let oldft=&ft | set ft=r | exe 'set ft='.oldft | let b:IsInRCode = function('DefaultIsInRCode') | normal <LocalLeader>rf
>               ]])
> 
>           -- vim.g.R_external_term = "foot -a R -T R --log-level error"
>           -- Close R automatically, but only if it's running in an external terminal
>           if vim.fn.exists('g:R_external_term') then
>               vim.cmd([[
>               autocmd VimLeave * if exists("g:SendCmdToR") && string(g:SendCmdToR) != "function('SendCmdToR_fake')" | call RQuit("nosave") | endif
>                   ]])
>           end
>       end
>   },
> }, {})
> ```
> 
> Both do the same thing: they create global variables and auto commands. Of course, it would be better to use local Lua variables instead of global Vim ones. But Nvim-R is very old (see https://www.vim.org/scripts/script.php?script_id=2628) and still supports Vim which doesn't use Lua for configuration. Unfortunately, I don't have spare time to keep two systems, one for Vim and another for Neovim.

Thanks!
I'm trying to maximize the interoperability between vimscript and lazy(lua), and I'm sure that there are nice ways how to reuse the code.
The code should not be so long and so hard, I'm just learning here with you what is the right thing to write.
I do think we can have a minimal amount of Lua adapter code without pain, and the end user wouldn't even notice the difference between vim-plug and lazy.

In case it would help, here is an explanation for augroups in the Lua api: (by TJ, the official Lua man of neovim)
https://youtu.be/F6GNPOXpfwU?feature=shared

**Comment by jalvesaq** [comment]
Thanks for sharing the link for the video. I didn't know about the functions `vim.api.nvim_create_user_command()` and `vim.api.nvim_create_autocmd()`.

Regarding the Lua adapter, I can accept a pull request for this if it does not duplicate code. When I eventually have to change an existing option or create a new one, I'll not have to remember to edit two different files (Vim and Lua) for the same thing.

However, this is not so easy because, currently, Nvim-R options are many global variables defined in different files and some of them have their default values defined conditionally. Perhaps we would have to create a single Vim dictionary (Lua table) with all options and let users pass a custom dictionary/table to a config function. Is something like this that you are thinking about? This would break the configuration of all current users.

**Comment by Tal500** [comment]
> Thanks for sharing the link for the video. I didn't know about the functions `vim.api.nvim_create_user_command()` and `vim.api.nvim_create_autocmd()`.
> 
> Regarding the Lua adapter, I can accept a pull request for this if it does not duplicate code. When I eventually have to change an existing option or create a new one, I'll not have to remember to edit two different files (Vim and Lua) for the same thing.
> 
> However, this is not so easy because, currently, Nvim-R options are many global variables defined in different files and some of them have their default values defined conditionally. Perhaps we would have to create a single Vim dictionary (Lua table) with all options and let users pass a custom dictionary/table to a config function. Is something like this that you are thinking about? This would break the configuration of all current users.

Still figuring out, I will look into this.

**Comment by Tal500** [comment]
I have update my local configuration to be smarter on loading filetypes plugins, see https://github.com/Tal500/astronvim_config/blob/6394aa891e88734c5043da28e8357132918ae6c1/plugins/nvim-r.lua. The [main parts](https://github.com/Tal500/astronvim_config/blob/6394aa891e88734c5043da28e8357132918ae6c1/plugins/nvim-r.lua#L28-L58) are:
```lua
return {
  "jalvesaq/Nvim-R",
  enabled = true,
  name = "nvim-r",
  init = function(plugin)
    vim.cmd("source " .. plugin.dir .. "/ftdetect/r.vim")
  end,
  ft = function(plugin, ft)
    local function load(subpath)
      vim.cmd("source " .. plugin.dir .. "/ftplugin/" .. subpath .. ".vim")
    end

    local ftplugins_path = vim.split(vim.fn.glob(plugin.dir .. "/ftplugin/*.vim"), "\n")
    local ftplugins = map(ftplugins_path,
      function(path)
        return {
          filetype = string.match(path, escape(plugin.dir) .. "/ftplugin/(%w+)[(_nvim)]?.vim"),
          path = path,
        }
      end
    )
    
    for k, ftplugin in ipairs(ftplugins) do
      if contains(ft, ftplugin.filetype) then
        vim.cmd("source " .. ftplugins.path)
      end
    end

    -- Anyway, this function needs to return the supported file types to register for loading
    return map(ftplugins,
      function(ftplugin)
        return ftplugin.filetype
      end
    )
  end,
}
```

As far as I see, we're left with two things to implement:
1. Move this logic to be in a Lua "setup" function inside the plugin repo codebase. Instead of hooking onto Lazy.vim `ft` trigger, we can achieve the same using Nvim Lua autocmd [as I referred in this video](https://youtu.be/F6GNPOXpfwU?feature=shared).
2. Use Autocmd also to load the syntax files in `/syntax` dir in this repo, as described in https://neovim.io/doc/user/syntax.html#%3Asyn-files.

Your thoughts?

**Comment by Tal500** [comment]
> It seems overly complicated. Nvim-R is a ftplugin. There is no need to manually enable or disable it by file type or manually source the Vim scripts from the `ftplugin` directory. Most of Nvim-R's code is already loaded asynchronously.

The motive was to allow nvim users enjoying this plugin, without setting up vim-plug.

**Comment by jalvesaq** [comment]
I'm also using `lazy.nvim` and the simple configuration below works perfectly:

```lua
require("lazy").setup({
  'jalvesaq/Nvim-R',
}, {})
```

What problem do you find with a simple configuration such as the above one?

**Comment by Tal500** [comment]
> ```lua
> require("lazy").setup({
>   'jalvesaq/Nvim-R',
> }, {})
> ```

This didn't work for me. Are you sure you didn't load it with vim-plug somewhere else?

**Comment by jalvesaq** [comment]
Try this:

- Delete `~/.local/share/nvim`.
- Rename `~/.config/nvim` as `~/.config/nvim_real`.
- Create a new `~/.config/nvim` directory.

```sh
cd ~/.local/share
rm -rf nvim
cd ~/.config
mv nvim nvim_real
mkdir nvim
```

- Then, create a new `init.lua` with the following contents:

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({ 'jalvesaq/Nvim-R' }, {})
```

- Start `nvim` (`lazy.nvim` will be installed and, then, it will install Nvim-R).
- Close `nvim`
- Start editing an R file (remember that the `LocalLeader` is `\` and that you have to press `\rf` to start R and `\d` to send a line to R Console).

**Comment by Tal500** [comment]
> ```lua
> require("lazy").setup({ 'jalvesaq/Nvim-R' }, {})
> ```

Oh OK now I see what I did wrong, I didn't set the parameter "lazy =  false" so it will load the plugin immediately on startup (by the Vim-plug-like compatibility sequence described in [Lazy README](https://github.com/folke/lazy.nvim#%EF%B8%8F-startup-sequence)).

This is my simple setup on `~/.config/nvim/lua/plugins/nvim-r.lua`:
```lua
return {
  "jalvesaq/Nvim-R",
  name = "nvim-r",
  enabled = true,
  lazy = false,
  init = function(plugin)
    vim.cmd([[
      " your Nvim-R configuration goes here, e.g:
      let R_hl_term = 0
      let R_bracketed_paste = 1
    ]])
  end,
}
```

Worth to add to README in my opinion, took me so long to figure this out.
Also, I didn't check that the special syntax files in `syntax/` dir are indeed being loaded, hope that they are though.

Thank you!

**Comment by jalvesaq** [comment]
I have opted not to mention any specific plugin manager, but given the current popularity of `lazy.nvim`, I will add a note on the use of `lazy=false`, as you suggested. Thanks for the feedback!
