### ISSUE TITLE
Problem with initialisation

### ISSUE THREAD

**Issue by konradzdeb** [jalvesaq/Nvim-R#754]
The plug-in fails to initialise with the following message:

> ERROR! Please, run :RDebugInfo for details, and check your '~/.R/Makevars'.

Running `:RDebugInfo`

```
RInitOut
RInitErr
Error in if (grep(R_version, nvimcom_info["Built"]) != 1) { :
  argument is of length zero
Execution halted
```

I've `~/.R/Makevars` but the file only consists of commented lines. I've `~/.Renviron` where I'm defining the `R_LIBS_USER` as follows:

```sh
# Library
R_LIBS_USER="${HOME}/Library/R/4/library"
```

Is this messing up with the `nvimcom` How can I fix that?

**Comment by konradzdeb** [comment]
Thanks for looking into this, as follows:

```sh
Rscript --verbose -e 'utils::installed.packages()["nvimcom", ]'
running
  '/usr/local/Cellar/r/4.3.1/lib/R/bin/R --no-echo --no-restore -e utils::installed.packages()["nvimcom", ]'

                            Package                             LibPath
                          "nvimcom" "/Users/konrad/Library/R/4/library"
                            Version                            Priority
                          "0.9-142"                                  NA
                            Depends                             Imports
                     "R (>= 3.0.0)"                    "methods, tools"
                          LinkingTo                            Suggests
                                 NA          "knitr, rmarkdown, quarto"
                           Enhances                             License
                                 NA                        "GPL (>= 2)"
                    License_is_FOSS               License_restricts_use
                                 NA                                  NA
                            OS_type                              MD5sum
                                 NA                                  NA
                   NeedsCompilation                               Built
                              "yes"                             "4.2.2"
```

**Comment by jalvesaq** [comment]
The "Built" column is in the output.  So, I don't know why the length of `grep(R_version, nvimcom_info["Built"])` is zero. If you look at `R/before_start.R`, you will see that `nvimcom_info` is the result of:

```r
utils::installed.packages()["nvimcom", c("Version", "LibPath", "Built")]
```

**Comment by konradzdeb** [comment]
Possible that the error is caused by the other part of the logic that references R_version?--KonradOn 5 Sep 2023, at 17:24, Jakson Alves de Aquino ***@***.***> wrote:﻿
The "Built" column is in the output.  So, I don't know why the length of grep(R_version, nvimcom_info["Built"]) is zero. If you look at R/before_start.R, you will see that nvimcom_info is the result of:
utils::installed.packages()["nvimcom", c("Version", "LibPath", "Built")]

**Comment by jalvesaq** [comment]
Thanks for reporting the bug! I believe it is fixed now. If not, please, reopen the issue.

**Comment by konradzdeb** [comment]
Thank you for your responsiveness. I've tested, everything seems to be working fine.
