### ISSUE TITLE
Openning multiple R sessions

### ISSUE THREAD

**Issue by iago-pssjd** [jalvesaq/Nvim-R#755]
Hi!

This is a doubt. Is it possible to open multiple R sessions (from a unique Vim session) so for certain R/Rmd files/buffers (let's say for example those in a specific project) R commands are send to an R session, while for other R/Rmd files/buffers (resp. those in other project) R commands would be send to a different R session?

If it isn't, would it be possible to implement this?

Thank you!

**Comment by jalvesaq** [comment]
Please, see https://github.com/jalvesaq/Nvim-R/issues/653
