### ISSUE TITLE
autocmd and colors doubt

### ISSUE THREAD

**Issue by diegodiazd** [jalvesaq/Nvim-R#76]
Hi,

First of all, nice tool, thanks for the contribution. 

I have two doubts:
**First one**:
I wondered if is it possible to start R automatically when a **.r** or **.Rmd** file is opened. I tried to set it with autocmd in my init.vim, using RStart and RSaveClose commands, but I couldn't.

**Second one**:
I have had some problems with syntax highlighting. When I open a **Rmd** file, the syntax looks good (I setted markdown syntax as default for Rmd), but when I send some commands to the R console, for example, library("ggplot2"), the highlight is lost. In attachment, some screenshots before and after to press the Nvim-R send command (Space)

![before](https://cloud.githubusercontent.com/assets/7968130/15945802/772d15e8-2e6a-11e6-825f-2fecb7936f43.png)

![after](https://cloud.githubusercontent.com/assets/7968130/15945892/cc686fd0-2e6a-11e6-9936-4765a85d8a74.png)

I have to type **set syntax=markdown** to restore the original syntax. This behavior is only with Rmarkdown files.

I am using neovim **NVIM 0.1.5-dev** in Ubuntu 16.04

Thanks in advance.

Diego!

**Comment by jalvesaq** [comment]
Thanks for writing!

  1. I added a tip on how to start R automatically: https://github.com/jalvesaq/Nvim-R/commit/6ca0f04e06a7e68514c8ded4fd3db0c2c230c7e6

  2. Now, when a new library is loaded, the `syntax` is reset, and not the `filetype`. This might solve the issue: https://github.com/jalvesaq/Nvim-R/commit/3c2da82b19551247df21a48840d9a1b9a9340fff

**Comment by diegodiazd** [comment]
Hi @jalvesaq,

Thanks, both suggestion worked. Now I am trying to configure nvim to close and save R before quiting. I modified a little the commands that you suggest in the link that you posted before but with no succeed:
```vim
autocmd VimLeave r if string(g:SendCmdToR) =! "function('SendCmdToR_fake')" | call RSaveClose("R") | endif
```

Thanks again!

**Comment by jalvesaq** [comment]
This should work:

```vim
autocmd VimLeave * if exists("g:SendCmdToR") && string(g:SendCmdToR) != "function('SendCmdToR_fake')" | call RQuit("save") | endif
```

**Comment by diegodiazd** [comment]
It worked. Thanks for helping me
