### ISSUE TITLE
`ggplot2` + sign and line indentation

### ISSUE THREAD

**Issue by PMassicotte** [jalvesaq/Nvim-R#760]
I am having an issue where new lines added after `+` are not indented properly (see attached GIF).

![Peek 2023-10-06 07-26](https://github.com/jalvesaq/Nvim-R/assets/4519221/a709bf67-f8a7-45ed-8e5f-9f8082c0951f)

I have searched existing issue (ex.: https://github.com/jalvesaq/Nvim-R/issues/744) and also looked at

```vim
:help ft-r-indent
```

I am not sure what I am missing, but I have not touched to `r_indent_op_pattern`.

Any help appreciated and thank you for the plugin.

**Comment by jalvesaq** [comment]
I can't replicate the issue. Can you replicate it without any plugin at all? Are you using tree-sitter indentation?

Please, note that indentation issues should be reported to https://github.com/jalvesaq/R-Vim-runtime

**Comment by PMassicotte** [comment]
Ok ty, I will try to replicate it. However, the pipe indentation works just fine. We can close it here and report to the other repo.
