### ISSUE TITLE
Use kitty instead of tmux to display R_csv_app

### ISSUE THREAD

**Issue by samtrek** [jalvesaq/Nvim-R#762]
I use kitty to run Nvim-R and it has almost all tmux functions, I dont know if you can implement some of the tmux capability for kitty.
the most important of all is viewing the output of an analysis in a new kitty tab, this can be achieved in kitty by running 
the command `kitty @launch --type tab vd|sc-im` tmux achieve the same thing by running `tmux new-window vd|sc-im`, for the command in kitty to work remote has to be enabled.

**Comment by samtrek** [comment]
I did the same but no response,I tried the suggestion above before posting this issue, normally a new tab should have opened up in kitty with either vd or sc-im with the data frame.

**Comment by jalvesaq** [comment]
The feature that you requested is already implemented: you can run any arbitrary command. If the command works when typed directly in the terminal, but not when called by nvim, then it should be fixed, if possible. I will accept a pull request if you find the fix.

**Comment by samtrek** [comment]
Any hint on where to start probing from?

**Comment by samtrek** [comment]
the code you provide does not work directly in nvim, I dont know which terminal nvim is using to run its code because when I ran `let R_csv_app = 'kitty  @launch --type tab vd'` it only returned timeout, so after looking at kitty documentation I found out that running the below will achieve the desired result
`vim.g["R_csv_app"] = "kitten @ --to unix:/tmp/kitty_sock launch --type tab vd"`
where kitty_sock is set in the initial kitty launch as
kitty -o allow_remote=yes --listen-on unix:/tmp/kitty_sock, where kitty_sock is an arbitrary name that can be set by the user.
