### ISSUE TITLE
Truncated output when using a gnome-terminal as R console

### ISSUE THREAD

**Issue by manumart** [jalvesaq/Nvim-R#763]
When I use a gnome-terminal as a console from Nvim-R, the outputs from R commands printed on the terminal are truncated to ~ the height of my screen, which is a bit problematic, since there is no way for me to look most of these ouputs as soon as they exceed a given length, well below the default R "max.print" option (9999) .

I feel that this might have something to do with the way Nvim-R starts the terminal but I can't figure how (if possible) to parameterize this.

NB : this does not happen when R is started within a Tmux pane the same terminal I use for editing code, using the
let R_external_term = 0 option.

Thanks a lot in advance for your feedback and for all the efforts you have been putting on Nvim-R!

**Comment by manumart** [comment]
No I can't replicate the issue with the command :terminal R... but it indeed seems to be related to the colorout package (no problem without having colorout loaded).

**Comment by jalvesaq** [comment]
Nvim-R is being superseded by R.nvim, a new project that will be inaugurated in a week at the [R-nvim](https://github.com/R-nvim) organization.
Please, check out [tmp-Nvim-R](https://github.com/jalvesaq/tmp-R-Nvim) and help us to find the last remaining bugs before R.nvim inauguration.
When the project is officially started, you will be able to open issues there and request new features.

Nvim-R will remain alive as a feature-frozen project for Vim users. If you want to know the reason, please, see [this discussion](https://github.com/jalvesaq/Nvim-R/discussions/797).
