### ISSUE TITLE
Does not work with neovim v0.6.1

### ISSUE THREAD

**Issue by ayonganguly** [jalvesaq/Nvim-R#765]
I am trying to use Nvim-R with neovim v0.6.1. When I am opening a .R file, it shows the following errors. Could you please look into it and suggest a way out?

Error detected while processing function GlobalRInit:
line    5:
E806: using Float as a String
Press ENTER or type command to continue
Error detected while processing function GlobalRInit:
line    6:
E806: using Float as a String

**Comment by jalvesaq** [comment]
I don't have Neovim 0.6.1 or below to replicate the issue, but it was so simple that I believe that it is fixed now. If not, please, reopen the issue.
