### ISSUE TITLE
FR: a couple of useful features for debugging as in RStudio: show function in new window and its environment in object browser

### ISSUE THREAD

**Issue by iago-pssjd** [jalvesaq/Nvim-R#771]
Hi,

For one time I will ask for a feature RStudio has when debugging a function. See at next image:
![rstudio](https://github.com/jalvesaq/Nvim-R/assets/40892925/988592e0-9a3a-4f08-a294-33c7d839c190)

1. On one hand, in the files pane is displayed a new tab with the involved function displayed and the code to be executed highlighted. In the same way, this (or something like this, not need highlighting, although it is useful) may be done in a new vim window like object browser or help or even in a new vim tab.
2. On the other hand, in the environment pane the environment of the involved function is displayed. So this would be done in the object browser window.

**Comment by jalvesaq** [comment]
A pull request for this would be great! Alternatively, it could be even better if it were possible to integrate Nvim-R with these other projects:

  - https://github.com/mfussenegger/nvim-dap
  - https://github.com/rcarriga/nvim-dap-ui
  - https://github.com/ManuelHentschel/VSCode-R-Debugger

Anyway, I don't plan to work on debugger features any time soon. So, again, a pull request would be welcome.

**Comment by iago-pssjd** [comment]
Thanks for answer. VSCode-R-Debugger seems nice, but my experience trying to use VSCode for coding R is that never and nothing works. For such king of things I also use NVim-R...

**Comment by jalvesaq** [comment]
The plan is to use Lua for new features: https://github.com/jalvesaq/Nvim-R/discussions

**Comment by iago-pssjd** [comment]
Thanks for the info. On my side, as a (pure) ViM user, I will keep using the current or freezed NVim-R derived for ViM, but thanks for all your work!

**Comment by jalvesaq** [comment]
Thanks for understanding!
The new project will be inaugurated in a week at the [R-nvim](https://github.com/R-nvim) organization.
