### ISSUE TITLE
Problems when calling Help ('\rh') on functions operating on objects with several classes 

### ISSUE THREAD

**Issue by ckastall** [jalvesaq/Nvim-R#773]
Hi,

I run Nvim-R version 0.9.17 with vim 9.0

I've noticed a small problem when calling the help (with '\rh') on a function operating on objects with several classes. Here an example:

```
tt <- data.frame()
class(tt) <- c("a", "b")
# using \rh on function "str" leads to an error
str(tt)
```

> Error in objclass != "#E#" && objclass != "" :
>   'length = 2' in coercion to 'logical(1)'

Weirdly enough to me, putting the object in parenthesis solves the issue... eg:
```
# no error when calling nvim.help here
str((tt))
```

The same issue happens with the print ('\rp').

I can imagine that it may not be trivial to identify which class should be assumed, and I'm not sure why the parentheses are making a difference. But to me, it would be nice if it could work by default as if there were parentheses.

This is an issue that occurs when using data.table objects as they commonly (/always?) have two classes: data.frame and data.table, eg:

```
tt <- data.table()
class(tt)
# [1] "data.table" "data.frame"
str(tt)    # \rh won't work here
str((tt))  # \rh will work here
```

**Comment by jalvesaq** [comment]
Thanks for reporting the bug! I will fix it on the stable branch.
