### ISSUE TITLE
How do disable the _ behaviour?

### ISSUE THREAD

**Issue by Unaimend** [jalvesaq/Nvim-R#777]
Hello people
is there any way to disable the conversion of "single-press" _ to <- ?

Thank you for your help :)

**Comment by jalvesaq** [comment]
`vimrc`:

```vim
let R_assign = 0
```

`init.lua`:

```lua
vim.g.R_assign = 0
```

There are many other options in the documentation that you may want to change.

**Comment by Unaimend** [comment]
Thanks, I of course looked in the doc, but did not see this :). So thank you very much :)
