### ISSUE TITLE
RHelp not working

### ISSUE THREAD

**Issue by Unaimend** [jalvesaq/Nvim-R#778]
Executing ` :Rhelp ` results in `E117: Unknow function RAskHelp`

![image](https://github.com/jalvesaq/Nvim-R/assets/7808379/900ffa79-37df-4ba7-a892-6115186c66b8)
![image](https://github.com/jalvesaq/Nvim-R/assets/7808379/f004fea8-edcf-441b-99dd-5a66fd69ce26)

**Comment by jalvesaq** [comment]
Thanks for reporting the bug!
