### ISSUE TITLE
Requires a vim patch 

### ISSUE THREAD

**Issue by hiraksarkar** [jalvesaq/Nvim-R#78]
I started Nvim-R with vim 7.4 with the default patch, after installation it says,

Nvim-R requires either Neovim >= 0.1.4 or Vim >= 7.4.1829.
If using Vim, it must have been compiled with both +channel and +job features.

**Comment by jalvesaq** [comment]
What do you mean by "default patch"? What is your operating system and Vim version? Did you try Neovim?

Unfortunately, if you can't have Vim >= 7.4.1829, you have either to use the last released Vim-R-plugin + vimcom or install Neovim. This not a bug. The plugin requires features only available in the development version of Vim. Earlier versions are not supported.

**Comment by hiraksarkar** [comment]
By default patch I meant what we get from apt-get install, here is the version info, 
I am on a ubuntu server `Distributor ID: Ubuntu
Description:    Ubuntu 14.10
Release:        14.10
Codename:       utopic`
My vim version is 
`VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct 20 2014 16:09:47)
Included patches: 1-273
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@`

@jalvesaq  Is there an older Nvim-R I can use with the current patch I have  ?

**Comment by hiraksarkar** [comment]
@jalvesaq I tried neovim and working on that now, but I just wanted it with vim ... I understand its not a bug just asking if there is a work-around without recompiling vim.

**Comment by jalvesaq** [comment]
You can use Vim-R-plugin 1.3.0 + vimcom 1.3-1 which are the latest versions before the switch to the `+channel` feature:
http://www.vim.org/scripts/script.php?script_id=2628
https://github.com/jalvesaq/VimCom/releases

**Comment by hiraksarkar** [comment]
Thanks !!
