### ISSUE TITLE
Implementing default location for the R Terminal

### ISSUE THREAD

**Issue by Unaimend** [jalvesaq/Nvim-R#785]
Hi,

I am currently trying to implement an option to the set the default location of the terminal buffer. I was under the impression that this is done in `function StartR_InBuffer()` in nvimbuffer.vim for neovim users. But changing any code in this file does not have any effect.

I have to admit I don't really no my way around nvim development, especially in vim script. Maybe you can point out some resources that I can read to not ask such beginner questions.

Thanks for your time
Thomas

**Comment by jalvesaq** [comment]
The position of the R console is defined by the options `R_rconsole_height`, `R_rconsole_width`, and `R_min_editor_width`.
