### ISSUE TITLE
Nvim-R requires Tmux >=3.0 but 3.3a version installed

### ISSUE THREAD

**Issue by einhander** [jalvesaq/Nvim-R#789]
Nvim-R requires Tmux >=3.0, but 3.3a version installed. 
```
tmux -V
tmux 3.3a
```

**Comment by jalvesaq** [comment]
I'm also running Tmux 3.3a (Debian testing), but I can't replicate the issue with

```lua
vim.g.R_external_term = "foot -a R -T R --log-level error"
```

on Neovim or the equivalent option on Vim.

**Comment by einhander** [comment]
Hmm, if I run with terminal nvim there no issue. But in neovide the issue exists.
I looked into variables and found that in case of terminal neovim `s:tmuxversion` has value 3.3. 
In neovide `s:tmuxversion` has value `neovide.Appimage 3.3a`

**Comment by jalvesaq** [comment]
Perhaps you should report the issue to neovide, since it is inserting "neovide.Appimage" in the output of `system()`.

**Comment by jalvesaq** [comment]
But, if only tmux is affected, I fix it here.

**Comment by jalvesaq** [comment]
It might be fixed now. I couldn't test it because I'm not running neovide...

**Comment by einhander** [comment]
> It might be fixed now. I couldn't test it because I'm not running neovide...

Thank you! It's OK now.
