### ISSUE TITLE
nvimcom compile errors with newest Rtools?

### ISSUE THREAD

**Issue by jpmorris** [jalvesaq/Nvim-R#79]
Using newest Rtools34, Nvim-R using vundle (from github HEAD?), and vim 7.4.1952

Once I move to Rtools33 it seems to work.  Feel free to close if you think this is Rtools's problem.

```
* installing *source* package 'nvimcom' ...
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-33~1.1/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"  -D`C:/PROGRA~1/R/R-33~1.1/bin/R --slave -e 'cat(Sys.info()[[1]])'` -DLWS_NO_FORK  -DWIN32   -O3 -Wall  -std=gnu99 -mtune=core2 -c nvimcom.c -o nvimcom.o
c:/Rtools/mingw_32/bin/gcc -shared -s -static-libgcc -o nvimcom.dll tmp.def nvimcom.o -lWs2_32 -Ld:/Compiler/gcc-4.9.3/local330/lib/i386 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-33~1.1/bin/i386 -lR
(cd apps; make -f Makefile.win)
make[1]: Entering directory `/cygdrive/c/Users/mor34/AppData/Local/Temp/RtmpKcyJoU/R.INSTALL27082752449/nvimcom/src-i386/apps'
gcc -m32 -mwindows -std=gnu99 -O3 -Wall -DWIN32 nclientserver.c -o nclientserver.exe -lWs2_32
make[1]: Leaving directory `/cygdrive/c/Users/mor34/AppData/Local/Temp/RtmpKcyJoU/R.INSTALL27082752449/nvimcom/src-i386/apps'
installing via 'install.libs.R' to C:/Users/mor34/Documents/R/win-library/3.3/nvimcom

*** arch - x64
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-33~1.1/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"  -D`C:/PROGRA~1/R/R-33~1.1/bin/R --slave -e 'cat(Sys.info()[[1]])'` -DLWS_NO_FORK  -DWIN32   -O2 -Wall  -std=gnu99 -mtune=core2 -c nvimcom.c -o nvimcom.o
c:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o nvimcom.dll tmp.def nvimcom.o -lWs2_32 -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-33~1.1/bin/x64 -lR
(cd apps; make -f Makefile.win)
make[1]: Entering directory `/cygdrive/c/Users/mor34/AppData/Local/Temp/RtmpKcyJoU/R.INSTALL27082752449/nvimcom/src-x64/apps'
gcc -m64 -mwindows -std=gnu99 -O3 -Wall -DWIN32 nclientserver.c -o nclientserver.exe -lWs2_32
nclientserver.c:1:0: sorry, unimplemented: 64-bit mode not compiled in
 #include <stdio.h>
 ^
make[1]: *** [nclientserver.exe] Error 1
make[1]: Leaving directory `/cygdrive/c/Users/mor34/AppData/Local/Temp/RtmpKcyJoU/R.INSTALL27082752449/nvimcom/src-x64/apps'
make: *** [nvimapps] Error 2
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-33~1.1/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-33~1.1/share/make/winshlib.mk" SHLIB="nvimcom.dll" WIN=64 TCLBIN=64 OBJECTS="nvimcom.o"' had status 2
ERROR: compilation failed for package 'nvimcom'
* removing 'C:/Users/mor34/Documents/R/win-library/3.3/nvimcom'
```

**Comment by jalvesaq** [comment]
It might be a problem with Rtools34, but I don't know. We may let the issue open until someone solves the mystery. Thanks for including a workaround in your report!

**Comment by blayz3r** [comment]
I had a new install of VIM and spent the whole day installing and uninstalling Mingw,Cgwin etc to get the plugin to work.Changing Rtools to v33 works.Thanks jpmorris

**Comment by oli666** [comment]
I had the same issue with Rtools34 today (win10, vim patch level 2133, R 3.3.1) on a brand new installation; falling back to Rtools33 save the day for me! Thanks, blayz3r for putting it to my attention!

**Comment by jalvesaq** [comment]
I added a warning when the installation fails and Rtools version is 3.4: https://github.com/jalvesaq/Nvim-R/commit/8c33d168291f2fe0d9caba58a3ea218532afe13d

However, I downloaded Rtools 3.4 today and it worked. So, the code above was not tested in a real situation.

**Comment by jalvesaq** [comment]
I am closing the issue. Please, reopen it if there is any problem with Rtools and the plugin does not warn about version incompatibility.

**Comment by jpmorris** [comment]
I could be wrong, but tried again when setting up a fresh windows 10 machine.  Rtools 3.4 gave the same error, so uninstalled and 3.3 worked.  Using vim7.4.2251  (maybe it's vim version-dependent?)

**Comment by jalvesaq** [comment]
Did the plugin warned about version incompatibility when you tried Rtools 3.4?

**Comment by jpmorris** [comment]
Yes it did give the warming.

**Comment by jalvesaq** [comment]
I think it is not dependent on Vim version because Vim simply calls R which calls gcc from Rtools. It seems to be an Rtools bug and, in this case, the best that I can do is to warn about the version problem.
