### ISSUE TITLE
Autocomplete for function parameters stops working when R opens

### ISSUE THREAD

**Issue by PMassicotte** [jalvesaq/Nvim-R#796]
Hi.

I think that a recent update of nvim-r broke parameter autocompletion:

![Peek 2024-01-12 13-45](https://github.com/jalvesaq/Nvim-R/assets/4519221/607181a2-23b3-4250-8cb1-f1c66beca7eb)

Any ideas?

**Comment by jalvesaq** [comment]
I couldn't replicate exactly the same issue, but I fixed a bug introduced yesterday in `cmp-nvim-r`. Could you update everything and try again, please?

**Comment by PMassicotte** [comment]
ah yes it fixed the problem!

thank you
