### ISSUE TITLE
`RQuarto()` should escape Windows path seperator before sending to R

### ISSUE THREAD

**Issue by hongyuanjia** [jalvesaq/Nvim-R#798]
`RQuarto()` did not handle the Windows path specifically, which makes `quarto::quarto_*()` error on Windows. 

https://github.com/jalvesaq/Nvim-R/blob/be3ee4177ef869ade1d3f74923040c89c0a4e7f9/ftplugin/quarto_nvimr.vim#L12

```r
quarto::quarto_preview("C:\Users\hongyuanjia\test\index.qmd")
#> Error: '\U' used without hex digits in character string (<input>:1:28)   
```

**Comment by hongyuanjia** [comment]
I have submitted a small PR #799 for fixing.

**Comment by jalvesaq** [comment]
I merged it. Thank you!
