### ISSUE TITLE
Nvim-R: Odd Behavior in Sending Lines/Chunks

### ISSUE THREAD

**Issue by nhejazi** [jalvesaq/Nvim-R#80]
Hello,

I've been trying to move towards adopting Nvim-R as my main R environment, and have run into an issue that appears related to key mappings. I have the following 2 issues:

1) After selecting a single line or chunk of code, Nvim-R successfully sends the code to the running R session, but then enters Insert mode in Neovim (I have no idea why, and forces me to have to manually change back to Normal mode). I suspect this has something to do with key mappings.

2) After successfully sending the code, the R session in Neovim will display a message indicating that it has "sourced" some temporary file. This might not be an error, but it is not terribly informative -- is there a way to prevent this message, or, better yet, display the code sent to the R session?

I have these issues on my machines running either OS X El Capitan or Ubuntu Trusty. I did not find any similar issues in the project history -- has anyone experienced such an error before?

I have the following code related to Nvim-R in my init.vim:
```
" Add settings for NVim-R plugin (auto-start with .R and .Rmd files)
let R_vsplit = 1  "use vertical terminal split
autocmd FileType r if string(g:SendCmdToR) == "function('SendCmdToR_fake')" | call StartR("R") | endif
autocmd FileType rmd if string(g:SendCmdToR) == "function('SendCmdToR_fake')" | call StartR("R") | endif
vmap <LocalLeader>. <Plug>RDSendSelection
nmap <LocalLeader>. <Plug>RDSendLine
```
I also have these (related) settings in my Neovim's run control file:
```
" Remap colon operator to semicolon for easier use.
nnoremap ; :

" Map SPACE to the leader key
let mapleader="<SPACE>"
let maplocalleader = ","
```

Thanks for any help, and, of course, thanks for the great plugin.

**Comment by jalvesaq** [comment]
I can't reproduce bug 1. Perhaps you have an auto command in your init.vim that makes Neovim to enter Insert mode when entering a terminal buffer. Nvim-R needs to check whether the width of the terminal has changed or not, and it quickly moves the cursor into the terminal and back to the editor. You can avoid this if you install and load in your .Rprofile the R package "setwidth".

The command `base::source()` is used to run two or more lines sent to R. I guess that most people don't want to see their contents because they are in the script they are editing. Please, see:
```
:h R_source_args
```
You may want in your vimrc:
```
let R_source_args = "echo=TRUE, print.eval=TRUE"
```
I may consider making `print.eval=TRUE` a default argument passed to `source()`.

**Comment by nhejazi** [comment]
Thanks for your quick response. The problem was indeed exactly what you predicted (that is, I had a line in my init.vim to automatically enter insert mode when entering a terminal). The fix was just an additional line to leave insert mode when leaving a terminal buffer. I didn't realize until you pointed it out that Nvim-R enters the terminal, but that explains the issue I was having across multiple platforms.

I've added the line you suggested to my init.vim and now everything is working as expected. Regarding setting `print.eval=TRUE` as a default: such behavior would be consistent with both the package for the Atom editor that sends code to an R session and with RStudio, which would make Nvim-R's behavior closer to what new user's might expect.

Thanks again for the help and the excellent plugin.

**Comment by jalvesaq** [comment]
Thanks for the feedback!
The default value of `R_source_args` now is `"print.eval=TRUE"`: https://github.com/jalvesaq/Nvim-R/commit/46d2e5335ff74f1db7f2c578e2db267e1b11b866
