### ISSUE TITLE
Is it possible to change the indentation behavior after parenthesis to be the same as curly brace?

### ISSUE THREAD

**Issue by jarodmeng** [jalvesaq/Nvim-R#803]
When I type a line break after an open curly brace (`{`), the auto indent of the new line is shiftwidth from the start of the line.

```
# The following is typed without pressing any Tab key
test_func <- function() {
  run_some_code
}
```

When I type a line break after an open parenthesis (`(`), the auto indent of the new line is at the same position as the parenthesis.

```
# The following is typed without pressing any Tab key
df %>%
  mutate(
         test_col = do_something(another_col)
         )
```

I would like the output to look like this instead.

```
df %>%
  mutate(
    test_col = do_something(another_col)
  )
```

Is there a way to set options to achieve this?

**Comment by jalvesaq** [comment]
Please, see this: https://github.com/jalvesaq/R-Vim-runtime/issues/1

**Comment by jarodmeng** [comment]
Thanks for the link. In this case, I might write a simple customized `indentexpr` to replace the one shipped with nvim-r.

**Comment by jalvesaq** [comment]
Could you share customized `indentexpr` here? Others might benefit from it.
