### ISSUE TITLE
How to use Python in Quarto with Nvim-R

### ISSUE THREAD

**Issue by cowvin0** [jalvesaq/Nvim-R#804]
I've been trying to use Python with Quarto, but I don't know if Nvim-R already supports it. Is it possible to configure it? Thank you.

**Comment by jalvesaq** [comment]
Lines of Python code are sent to R Console as arguments to `reticulate::py_run_string()`. So, you have to install the `reticulate` package.

You can find a different approach at [quarto-nvim](https://github.com/quarto-dev/quarto-nvim).

**Comment by cowvin0** [comment]
Thanks @jalvesaq, it helped a lot. I've been using [vimcmdline](https://github.com/jalvesaq/vimcmdline) and it has been helpful, but I'll try reticulate as well.

**Comment by jalvesaq** [comment]
Nvim-R is being superseded by R.nvim, a new project that will be inaugurated in a week at the [R-nvim](https://github.com/R-nvim) organization.
Please, check out [tmp-Nvim-R](https://github.com/jalvesaq/tmp-R-Nvim) and help us to find the last remaining bugs before R.nvim inauguration.
When the project is officially started, you will be able to open issues there and request new features.

Nvim-R will remain alive as a feature-frozen project for Vim users. If you want to know the reason, please, see [this discussion](https://github.com/jalvesaq/Nvim-R/discussions/797).
