### ISSUE TITLE
Error on keyword completion

### ISSUE THREAD

**Issue by micha-silver** [jalvesaq/Nvim-R#807]
Following your quick fix to the problem I asked last week (`nvim_set_option_value("syntax", bsyn, {'buf': bId})`) now I noticed a similar error when using auto completion. I press C-x C-o and I get the list of possible completions in the minibuffer. Then, as soon as I press tab or arrow down to cycle thru the completions, i get:

```
Error detected while processing function ROnJobStdout[40]..SetComplInfo[15]..CreateNewFloat:                                                                       
line  143:
E5555: API call: Invalid key: 'buf'
Press ENTER or type command to continue
```
Perhaps a similar fix needs to be applied somewhere else? Line 207 in complete.vim??

Thanks,

**Comment by jalvesaq** [comment]
Thank you for reporting! Using `grep`, I found two other occurrences of  `nvim_set_option_value()` and "fixed" them all. Please, reopen the issue if there are any problems.

**Comment by micha-silver** [comment]
Again, many thanks for the **instant** response.
