### ISSUE TITLE
Issues with versions after v0.9.17

### ISSUE THREAD

**Issue by shaman-yellow** [jalvesaq/Nvim-R#814]
Version v0.9.17:
Use nvim-r, enter `print(1)` in the terminal buffer,

```
> print(1)
[1] 1
> #Now I can immediately continue typing
```

but When I update to later versions，

```
> print(1)
[1] 1
# 1 second, I can do nothing
# 2 second, I can do nothing
# 3 second, maybe the same
> #Now I can  continue typing
```

I don't know what happened during this period, why do I have to wait so long?

The same thing happens when using `RSend`.
I use `print(1)` as an example just to make it easier to understand. Entering any other code will result in the same problem: meaningless waiting.

**Comment by jalvesaq** [comment]
I can't note any delay in either R or Vim when using Vim + Nvim-R. Anyway, you may put in your `vimrc`:

```vim
let R_hi_fun_paren = 0
```

or even

```vim
let R_hi_fun = 0
```

Does this make any difference?

**Comment by shaman-yellow** [comment]
Strangely, I tried it today and didn't encounter the same problem as before. Maybe there was a conflict in some settings, but I accidentally changed it later.

**Comment by shaman-yellow** [comment]
I found the problem. This problem does not occur when I start the R console. But when I load the last working environment through `load(".RData")`, the problem occurs (but it does not happen every time, but in specific situations). I think that there is some conflict between one of the R packages I loaded (bioinformatics toolkit, I don't know which one) or some R object and `nvimcom`. Interestingly, when I perform `pkgload::unload(‘nvimcom’)` everything is back to normal. I can use `library(nvimcom)` again.

**Comment by jalvesaq** [comment]
I don't know about the `pkgload` library, but in base R, the following command unloads nvimcom code which normally keeps a permanent connection with `rnvimserver`:

```r
detach("package:nvimcom", unload = TRUE)
```

`nvimcom` wasn't developed to be loaded and unloaded at will. It must be loaded at the beginning of the R session (with all required environment variables set and the appropriate startup script) and remain loaded until the end of the session.

**Comment by jalvesaq** [comment]
> it does not happen every time, but in specific situations

Can you provide easy steps that I could follow to create such a situation on my system?

**Comment by shaman-yellow** [comment]
I have tried to provide you with the R objects that cause the problem, but I am still not sure whether it can be reproduced on your system.
The archive contains two files, both `RDS`, one of which is the output of `sessionInfo()`.
The `debugPlots.rds` is the "plots" object stored in R, which can be output by `print`. The problem is that `nvimcom` seems to check these "plot" objects every time I interact with them (send line) (I found that the delay is the same long as the printing time of the plot objects), regardless of whether I am doing anything related to the plot objects. `nvimcom` may be doing some redundant checks.
Even more interesting is that when I subset the "plot" objects, the problem disappears, which is really elusive. Such as:

```R
# Issue occur:
plots <- readRDS("debugPlots.rds")
length(plots)
# [1] 6

# Issue disappear
plots <- plots[1:3]

# Issue disappear
plots <- plots[4:6]
```

Hopefully this bug can be eliminated, otherwise I will be stuck with version 0.9.17 forever. (The problem occurs in `R.nvim` and `Nvim-R`).

[debug.zip](https://github.com/user-attachments/files/15796640/debug.zip)

**Comment by jalvesaq** [comment]
`debugPlots.rds` depends on a package called `utils.tool` which I couldn't find.

**Comment by shaman-yellow** [comment]
This package is not the problem. It is a collection of tools that I use personally, and is an incomplete R package.
You can get it here: <https://github.com/shaman-yellow/utils.tool>
It is not expected that this package can be used via 'install', but you via:

```R
devtools::load_all("~/utils.tool")
```

**Comment by jalvesaq** [comment]
Thanks! I can replicate the bug now. I will try to find what's happening, but I don't have spare time this week to make big changes in `nvimcom.c`.

**Comment by jalvesaq** [comment]
Thanks! I can replicate the bug now. I will try to find what's happening, but I don't have spare time this week to make big changes in `nvimcom.c`.

**Comment by jalvesaq** [comment]
The bug is the same reported on https://github.com/R-nvim/R.nvim/issues/142

**Comment by jalvesaq** [comment]
Could you, please, try the branch `unnamed_list` in my fork of `R.nvim`?
https://github.com/jalvesaq/R.nvim/branches

**Comment by shaman-yellow** [comment]
> Could you, please, try the branch `unnamed_list` in my fork of `R.nvim`? https://github.com/jalvesaq/R.nvim/branches

Thanks! I have tried, and this branch worked well.

**Comment by jalvesaq** [comment]
I ported to Nvim-R the solution that I have developed for R.nvim. It's on the branch https://github.com/jalvesaq/Nvim-R/tree/compl_data

Can any Nvim-R user try it and make suggestions of improvements? Is the information printed by nvimcom more annoying than useful? Or is it so useful that should be printed even if `nvimcom.verbose = 0`?

**Comment by shaman-yellow** [comment]
> Now, nvimcom starts inspecting at most 12 levels of lists and tolerating up to 100 ms of completion data build time and up to 1,000,000 bytes of completion data size

What you mean in <https://github.com/R-nvim/R.nvim/issues/142> seems to be that nvimcom actually creates the completion list during the delay. The completion list is indeed useful. But for me, not all data needs completion information. For example, `plots` objects generally do not need completion. Perhaps, an optional parameter can be provided here to stop recursively creating completions when a certain Class is encountered.

**Comment by jalvesaq** [comment]
I agree that we don't need completion for most `list` and `S4` objects. But the completion data is also useful to inspect the objects in the Object Browser which might help people developing R packages.

For most users, `max_depth = 2` should be enough. A `lm` object, for example, is a list with elements in only one level. And with a `max_depth` value as low as 2 the time to build and transmit the completion data will be less than 20 ms.
