### ISSUE TITLE
The completion candidates order is not the parameters true order

### ISSUE THREAD

**Issue by shaman-yellow** [jalvesaq/Nvim-R#815]
I have always had a question: `Nvim-R` uses `cmp` to provide function parameter completion, but in many cases the order of the parameters is not followed. Let me give you an example and create the following function:

```R
sortCh <- function(x, decreasing = F, as.factor = F) {
  num <- as.integer(stringr::str_extract(x, "[0-9]+"))
  x <- x[ order(num, decreasing = decreasing) ]
  if ( as.factor ) {
    x <- factor(x, levels = unique(x))
  }
  x
}
```

The true order is: `x, decreasing = F, as.factor = F`.
However, the completion candidates order is: `x, as.factor = F, decreasing = F`.
Many times, I am deceived by the completion.
Is there any way to adjust this?

**Comment by jalvesaq** [comment]
`nvim-cmp` receives the arguments in the correct order from `cmp-nvim-r`. You could try to configure the `sorting` or `sorting.comparators` argument in `nvim-cmp` config so that at least the order of items from `cmp-nvim-r` is preserved. Please, post here if you have success doing it.

**Comment by shaman-yellow** [comment]
Thanks! After trying, I solved the trouble that had been bothering me for a long time!

```lua
cmp.setup({
  -- ...
  -- before is the other configure
  sources = {
    { name = 'cmp_nvim_r' },
  },
  sorting = {
    comparators = {
      -- this function seems to work well
      cmp.config.compare.order, 
    },
  },
})
```

**Comment by jalvesaq** [comment]
Thank you! I will try your solution too.
