### ISSUE TITLE
nvimserver.exe not found 

### ISSUE THREAD

**Issue by Dulohan** [jalvesaq/Nvim-R#818]
Today, after months of stable operation, I was unable to start an R session from Vim. 
I get the error message: "Application "nvimserver.exe" no...ramme/R/R-4.3.2/library/nvimcom". 
The folder and it subfolders exist but do not contain any *.exe file.

**Comment by jalvesaq** [comment]
The application name is either `rnvimserver.exe` (R.nvim) or `nvimrserver.exe` (Nvim-R). Please see section 3.3, _Troubleshooting (if the plugin doesn't work)_. More specifically look at the output of `:messages`, `:RDebugInfo`, and `:checkhealth` and report anything that seems to be useful to diagnostic the cause of the problem.

**Comment by Dulohan** [comment]
Thank you! I reinstalled the plugin and now it works. Maybe some bot of my company deleted the exe.

**Comment by Dulohan** [comment]
Worked after reinstall

**Comment by jalvesaq** [comment]
Thanks for the feedback!
