### ISSUE TITLE
Roxygen tags have weird syntax highlighting

### ISSUE THREAD

**Issue by ashiklom** [jalvesaq/Nvim-R#84]
Roxygen documentation looks like this.

```
#' @param my_param This is my parameter
func <- function(my_param) ...
```

Nvim-R is designed to highlight the tag (`@param`) but leave everything else in the comment color, which is really cool! However, I'm getting some weird behavior.

In the above case, everything after the `#'` gets highlighted, as in.

```
#' <@param my_param This is my parameter>
```

(using `<>` to represent highlighting)

If I insert a `#'` above it with *no space*, everything is highlighted as a comment.

```
#'{no space}
#' @param my_param This is my parameter.
```

However, I get the right behavior if there are at two or more `#'`s above the roxygen comment with spaces (and possibly other characters) after them.

```
#' {space}
#' {space}
#' <@param> my_param This is my parameter.
```

Is this behavior by design? Or is it a faulty syntax highlighting rule?

**Comment by jalvesaq** [comment]
I don't use ROxygen, but the syntax highlight must match the syntax rules. If the space is not required to get ROxygen code correctly processed, then it should not be required to get the code highlighted as ROxygen.

**Comment by jranke** [comment]
Citing from https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html

> Each documentation block starts with some text. The first sentence becomes the title of the documentation. 

So this is the reason I implemented this behaviour. Do you really want to start a roxygen block with `@param`?

If not, I think the issue can be closed. For future issues with syntax highlighting, please file an issue at [R-Vim-runtime](https://github.com/jalvesaq/R-Vim-runtime), this is where the syntax files live.

**Comment by ashiklom** [comment]
Huh, I totally missed that when reading the Roxygen documentation. This syntax highlighting is a great way to enforce correct formatting of Roxygen tags.

Thanks for pointing that out -- clearly this behavior is by design, and now that I see the rationale, I agree that it's a good design choice.

**Comment by klmr** [comment]
@jranke Unfortunately the Roxygen documentation is simply wrong in this regard. For example, the following would be a relatively common piece of R code:

```r
#' Some description
#'
#' Something more
foo = function () …

#' @rdname foo
bar = function () …
```

This would cause `foo` and `bar` to share a documentation page. The current syntax highlighting unfortunately gets this wrong:

![screen shot 2017-01-10 at 13 10 16](https://cloud.githubusercontent.com/assets/38931/21807362/4377c5b6-d736-11e6-9c9c-840487970058.png)

This forces me to change `bar`’s documentation to:

```r
#'‹trailing space›
#' @rdname foo

bar = function () …
```

The trailing space of course makes me die a little inside, and makes git hate me.

**Comment by jranke** [comment]
@klmr I was about to agree, as I have seen a lot of code like this, but don't you think `bar` deserves a description, too?

**Comment by jranke** [comment]
@klmr OK, I did not give it enough thought - it is reasonable to use the same description in this case. Do you think it is sufficient to add `@rdname` as an exception?

**Comment by klmr** [comment]
> Do you think it is sufficient to add `@rdname` as an exception?

No — usually `@rdname` won’t be specified in the first line but rather down the line. Here are three real-world counter-examples (irrelevant details changed):

* This one uses the same arguments as another function and just adds a separate description (but not title!):

    ```r
    #' \code{bar} does the same as \code{foo} but differently.
    #' @rdname foo
    bar = function () …
    ```

    The first line is effectively arbitrary description text.

* Here the function has no separate description but specifies that it is exported:

    ```r
    #' @export
    #' @rdname foo
    foo_ = function () …
    ```

* Here the function has additional parameters that are documented:

    ```r
    #' @param value the attributes to assign
    #' @rdname property
    `property<-` = function (object, value) {
    ```

**Comment by jranke** [comment]
What these examples have in common is that they contain `@rdname`. So any roxygen block containing `@rdname` should not have title nor description, as they are already specified, right? And such a roxygen block can contain text and any additional tags except for title and description?

**Comment by klmr** [comment]
Actually a roxygen block that has a `@rdname` *can* have a title as well. :-( — This happens when the function should just generally be documented under a different name. For example, R’s arithmetic operators (`+` etc) are documented under the topic name `Arithmetic`.

I think the only reliable way of doing this is to implement the following logic

1. If the roxygen block has an empty line (except for leading `#'`), then the stuff before the first empty line is the title.
2. Otherwise,
    1. If the roxygen block contains `@rdname`, then there’s no title.
    2. Otherwise, the whole block is a title.

**Comment by jranke** [comment]
@klrm Would you like to have a look at the PR jalvesaq/R-Vim-runtime#19?
