### ISSUE TITLE
Key binding for pipe operator %>%

### ISSUE THREAD

**Issue by earowang** [jalvesaq/Nvim-R#85]
Thanks so much for the awesome vim add-on, definitely a lifetime saver!

Since there's an increasing demand for using the new forward-pipe operator `%>%` in conjunction with `dplyr` and many other pacakges, I'm wondering whether it is possible to implement a new key binding for this operator. A possible shortcut may be `>` for `%>%`?

Looking forward to your response.

Best,
Earo

**Comment by jalvesaq** [comment]
You could try this in your vimrc:
```
autocmd FileType r inoremap <buffer> > <Esc>:normal! a%>%<CR>a 
autocmd FileType rnoweb inoremap <buffer> > <Esc>:normal! a%>%<CR>a 
autocmd FileType rmd inoremap <buffer> > <Esc>:normal! a%>%<CR>a 
```
Note that the last character of the above lines is an empty space.

**Comment by earowang** [comment]
Thanks for the response. The script works! But how can I tweak a little bit to get `%>%` surrounded by space. Currently only `%>%` is followed by a space, but I'd like to have a space before `%>%`.

**Comment by jalvesaq** [comment]
You can add the space to right hand side of the map:
```
autocmd FileType r inoremap <buffer> > <Esc>:normal! a %>%<CR>a 
autocmd FileType rnoweb inoremap <buffer> > <Esc>:normal! a %>%<CR>a 
autocmd FileType rmd inoremap <buffer> > <Esc>:normal! a %>%<CR>a 
```

**Comment by earowang** [comment]
Works perfectly! Thank you so much.

**Comment by jalvesaq** [comment]
I am closing the issue because it can be solved in the vimrc.

**Comment by paulrougieux** [comment]
How could I enable this mapping in the vim R terminal buffer?
