### ISSUE TITLE
Nvim-R and interactive graphics

### ISSUE THREAD

**Issue by agisga** [jalvesaq/Nvim-R#86]
Thank you very much for a great plugin!

Recently, I came across a problem, when using interactive R plots, such as provided by the R packages ggvis or plotly. When I simply open R in the terminal and run the commands, then the interactive plots are automatically displayed in the web browser. But when I run the commands from within Nvim-R, then Nvim opens a new tab in nvim (which is empty), does not display the plot in any way, and sometimes becomes unresponsive.

Here is a minimal example of the type of code that I'm trying to run:

```{r}
# ggvis
library(ggvis)
data("economics", package = "ggplot2")
economics %>%
  ggvis(~date, ~psavert) %>%
  layer_points() %>%
  layer_smooths(
    span = input_slider(0.2, 1)
  )

# plotly
library(plotly)
plot_ly(economics, x = date, y = unemploy / pop)
```

**Comment by jalvesaq** [comment]
It seems that you have followed the documentation suggestion and set the option `browser` to use the text mode web browser `w3m`. Please, look at your .Rprofile. Everything should be OK if you do not set the option `browser`. I will add an alert the documentation.

**Comment by jalvesaq** [comment]
I replaced the old suggestion with a safer one: https://github.com/jalvesaq/Nvim-R/commit/db8b3422b773bac0e4c7c6be7b52f94a57d5e581

**Comment by agisga** [comment]
Problem solved. Thanks!
