### ISSUE TITLE
Two issues on Windows: RTools installation PATH and multiple R instances

### ISSUE THREAD

**Issue by songcai** [jalvesaq/Nvim-R#87]
Hi Jakson,

I am using Windows 10 and the latest Nvim-R.

First issue:
    I am using RTools 3.3 for installing Nvim-R on Windows. If I install RTools in a customized location (not C:\RTools) and set the system PATH to include the bin folder of RTools, nvimcom building fails. The error message showed that Nvim-R is still searching for RTools under C:\RTools. If I install RTools to location C:\RTools, nvimcom builds successfully. Is there a way to set PATH for RTools or allow Nvim-R to automatically recognize it from system PATH?

Second issue:
    I can keep calling R consoles from Vim using /rf, and every time I do that, there will be a new R console opening. I think on Linux and Mac OS, the default behaviour is that Nvim-R will detect the instance of R and prevent multiple R consoles from opening. Now if I use /rq to close R consoles, only the last R console opened can be closed. If I keep doing /rq, I get "Did you already start R? [ClientServer] Could not get R Console position" message. I think this is the supposed behaviour of "/rq".
    Is there a way to keep only one R console open when I repeatedly use /rf?

Many thanks,
-Song

**Comment by jalvesaq** [comment]
I can't access Windows right now, but regarding the first issue, Nvim-R runs the command `R CMD INSTALL nvimcom_version_number.tar.gz`. It does not look for C:\Rtools. If you start R manually, can it build packages that require compilation?

**Comment by songcai** [comment]
Many thanks, Jakson. I confirm that the nvimcom installation issue (the 
first issue) is an R issue, irrelevant to Nvim-R. The simplest solution 
would be to just install Rtools under C:\Rtools.

**Comment by songcai** [comment]
Hi Jakson,
Since the first issue is irrelevant to Nvim-R, please close this report. I will post a new one describing only the second issue.
