### ISSUE TITLE
nvimcom installation in windows

### ISSUE THREAD

**Issue by songcai** [jalvesaq/Nvim-R#89]
Windows 10 64-bit, Vim 7.4.2042 64-bit, R 3.3.1 64 & 32-bit, Rtools 3.3

Issue: The first time I call R from within Vim, Nvim-R tried to install nvimcom but failed with the following message:
...
** testing if installed package can be loaded
*** arch - i386
Error : .onLoad failed in loadNamespace() for 'nvimcom', details:
  call: library.dynam("nvimcom", pkgname, libname, local = FALSE)
  error: DLL 'nvimcom' not found: maybe not installed for this architecture?
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/Song/Documents/R/win-library/3.3/nvimcom'

The following works though:
  1. go to Nvim-R/R
  2. R CMD build nvimcom
  2. R CMD INSTALL nvimcom_[version number].tar.gz
This way, nvimcom installs and then R can be called without any problem from Vim.

Cheers,
-Song

**Comment by songcai** [comment]
Hi Jakson,

Please close this issue. I figured that this is my R setting doing something funny --- again, I am using a customized location for Rtools (not C:\Rtools); Nvim-R and nvimcom are perfectly fine on their own. If I install Rtools under C:\Rtools, nvimcom can be successfully installed from within R.

Thanks,
-Song

**Comment by jalvesaq** [comment]
Thanks for the feedback!
