### ISSUE TITLE
Undo_ftplugin undefined

### ISSUE THREAD

**Issue by ashiklom** [jalvesaq/Nvim-R#9]
On opening a .Rmd file, I get the following error:

```
Error detected while processing ~/.nvim/bundle/Nvim-R/ftplugin/rmd_nvimr.vim.
line 158:
Undefined variable: b:undo_ftplugin
```

As far as I can tell, all the features of the plugin work fine, but this error pops up every time a .Rmd file is opened, and occasionally while editing the file as well.

From poking around GitHub issues with other plugins ([example](https://github.com/Chiel92/vim-autoformat/issues/3)), I think this can easily be fixed by checking if `b:undo_ftplugin` is set before appending to it with `.=`.

This may also be a problem on my end, via a conflict with a different package. But regardless, I feel like a check on the existence of a variable can't hurt.

Otherwise, great plugin! I use it religiously.

**Comment by jalvesaq** [comment]
Thanks for reporting the bug! It's fixed now.
