### ISSUE TITLE
Multiple R instances on Windows 10

### ISSUE THREAD

**Issue by songcai** [jalvesaq/Nvim-R#90]
I am using: Windows 10, R 3.3.1 with Rtools 3.3

I can keep calling R consoles from Vim using /rf, and every time I do that, there will be a new R console opening. On Linux or Mac OS, the default behaviour of /rf is that Nvim-R will detect the instance of R and prevent multiple R consoles from opening. Now with multiple R consoles opening (on Windows 10),  if I use /rq to close R consoles, only the last R console opened can be closed. If I keep doing /rq, I get "Did you already start R? [ClientServer] Could not get R Console position" message. I think this is the supposed behaviour of "/rq".

 Is there a way to keep only one R console open when I repeatedly use /rf on Windows?

Many thanks,
 -Song

**Comment by jalvesaq** [comment]
Thanks for reporting the issue!
One idea is to use the PID of R's process to check whether it is still running or not. I will see this later.

**Comment by songcai** [comment]
Many thanks, Jakson!

Cheers,

-Song
