### ISSUE TITLE
Undefined variable a:cmd 

### ISSUE THREAD

**Issue by PietaSchofield** [jalvesaq/Nvim-R#91]
Hullo

Using the latest release 0.9.5 with MacVim 7.4 on Mac OSX 10.11.6 I get the following message when sending commands to R (eg with space bar or sending current chunks etc)

Error detected while processing function SendLineToR[79]..SendCmdToR_OSX:
line   14:
E121: Undefined variable: a:cmd
E15: Invalid expression: a:cmd

commenting out line 53 of the file R/osx.vim makes the message go away but I am unsure what are the implications for this.

Thanks

Pieta

**Comment by jalvesaq** [comment]
Thanks for reporting the bug. I believe that it is going to be fixed by the next commit.

**Comment by jalvesaq** [comment]
Please, open this issue again if the bug is not fixed. Deleting the line is the correct fix because `cmd` was already defined a few lines above as `a:1`.
