### ISSUE TITLE
No R GUI popped 

### ISSUE THREAD

**Issue by DadongZ** [jalvesaq/Nvim-R#92]
I just switched from vim-R-plugin to Nvim-R. But after installation, by using `,rf` or `\rf`, no R gui was popped out. What is the possible issues?
I have used the .vimrc for .nvimrc by:
```
ln -s .vimrc .nvimrc
ln -s .vim .nvim
```

**Comment by jalvesaq** [comment]
You should do:

```
cd .config
ln -s ../.vim nvim
cd nvim
ln -s ../../.vimrc init.vim
```

**Comment by DadongZ** [comment]
Thanks. it still doesn't work though.

**Comment by jalvesaq** [comment]
If there is no error message, it is because the plugin is not installed. The Nvim-R plugin works with Vim too. Did you try both Vim and Neovim?

**Comment by DadongZ** [comment]
Thanks! I am able to initiate the R console by using "\rf" but I have
defined `let maplocalleader =","` in my .vimrc, why doesn't work for ",rf"?
Secondly, the R console was started by splitting a terminal at the bottom.
I am wondering how to initiate it at a single separate terminal (or split
by vertical at the right would be fine (I already set splitright in .vimrc).

Thank you for your plugin. I have relied on it for a while.

**Comment by jalvesaq** [comment]
If you have put `let maplocalleader=","` in your vimrc and the local leader still is `\`, then your vimrc might not being sourced.

**Comment by DadongZ** [comment]
How to make R initiated with a separated terminal rather split at the
bottom? I am kind of frustrated by that.

**Comment by DadongZ** [comment]
Sorry for bothering you again. I cannot open R help files from R console:

> ?table
sh: vimrpager: command not found

Could you give me some suggestions?

Thanks

**Comment by jalvesaq** [comment]
`vimrpager` is a very old script, deprecated a long time ago. You have to update your `.Rprofile`. Please, see in either Vim or Neovim:

```
:h Nvim-R-R-setup
```

The default behavior is to open R in an built-in terminal emulator in Neovim, and in an external terminal emulator in Vim. If you want to force the use of an external terminal emulator even in Neovim, put in your init.vim (or vimrc):

```
let R_in_buffer = 0
let R_tmux_split = 0
let R_applescript = 0
```

**Comment by jalvesaq** [comment]
@DadongZ Were you able to configure the plugin as you wanted? Your feedback might be useful for other users.

**Comment by jalvesaq** [comment]
I am closing this issue due to lack of feedback.
