### ISSUE TITLE
Error detected while processing function DisplayArgs

### ISSUE THREAD

**Issue by kprimice** [jalvesaq/Nvim-R#93]
I activated the display of arguments:
```
let R_show_args = 1
let R_args_in_stline = 1
```
But I get this error message when I write a function in vim:

> Error detected while processing function DisplayArgs:                                                                                                                                                                                          
line    6:
E714: List required

Also the highlight of loaded functions doesn't work (even functions from the base package). I am using Nvim-R with vim and tmux. I was using the rplugin package before and these 2 features used to work.

**Comment by kprimice** [comment]
Ful output of `:messages`:

> Messages maintainer: Bram Moolenaar <Bram@vim.org>                                                                                                                                                                                             
Error detected while processing function DisplayArgs:                                                                                                                                                                                          
line    6:                                                                                                                                                                                                                                     
E121: Undefined variable: g:rplugin_omni_lines                                                                                                                                                                                                 
E15: Invalid expression: g:rplugin_omni_lines

**Comment by jalvesaq** [comment]
The variable `g:rplugin_omni_lines` is created in the script R/functions.vim. It looks like your R/functions.vim is not being source. Maybe you have old files from a previous installation of either Vim-R-plugin or Nvim-R installed with a different method (vimball or plugin manager). You can see a list of all sourced files with the command `:scriptnames`, and perhaps you could note if still there are files from old installations.

**Comment by kprimice** [comment]
I tried to delete all the files in `~/.vim/R` and reinstall Nvim-R, but I still have the same issue.

Here is what `:scriptnames` echoes:

> ~/.vimrc                                                                                                                                                                                                                                  
/usr/share/vim/vim74/filetype.vim                                                                                                                                                                                                         
~/.vim/ftdetect/r.vim                                                                                                                                                                                                    
/usr/share/vim/vim74/ftplugin.vim                                                                                                                                                                                                         
/usr/share/vim/vim74/indent.vim                                                                                                                                                                                                           
/usr/share/vim/vim74/syntax/syntax.vim                                                                                                                                                                                                    
/usr/share/vim/vim74/syntax/synload.vim                                                                                                                                                                                                   
/usr/share/vim/vim74/syntax/syncolor.vim                                                                                                                                                                                                  
/usr/share/vim/vim74/colors/darkblue.vim                                                                                                                                                                                                  
~/.vim/plugin/screen.vim                                                                                                                                                                                                 
/usr/share/vim/vim74/plugin/getscriptPlugin.vim                                                                                                                                                                                           
/usr/share/vim/vim74/plugin/gzip.vim                                                                                                                                                                                                      
/usr/share/vim/vim74/plugin/matchparen.vim                                                                                                                                                                                                
/usr/share/vim/vim74/plugin/netrwPlugin.vim                                                                                                                                                                                               
/usr/share/vim/vim74/plugin/rrhelper.vim                                                                                                                                                                                                  
/usr/share/vim/vim74/plugin/spellfile.vim                                                                                                                                                                                                 
/usr/share/vim/vim74/plugin/tarPlugin.vim                                                                                                                                                                                                 
/usr/share/vim/vim74/plugin/tohtml.vim                                                                                                                                                                                                    
/usr/share/vim/vim74/plugin/vimballPlugin.vim                                                                                                                                                                                             
/usr/share/vim/vim74/plugin/zipPlugin.vim                                                                                                                                                                                                 
~/.vim/ftplugin/r_nvimr.vim                                                                                                                                                                                              
~/.vim/R/common_global.vim                                                                                                                                                                                               
~/.vim/R/setcompldir.vim                                                                                                                                                                                                 
~/.vim/R/vimrcom.vim                                                                                                                                                                                                     
~/.vim/R/tmux.vim                                                                                                                                                                                                        
~/.vim/R/tmux_split.vim                                                                                                                                                                                                  
~/.vim/R/common_buffer.vim                                                                                                                                                                                               
/usr/share/vim/vim74/ftplugin/r.vim                                                                                                                                                                                                       
~/.vim/indent/r.vim                                                                                                                                                                                                      
/usr/share/vim/vim74/indent/r.vim                                                                                                                                                                                                         
~/.vim/syntax/r.vim                                                                                                                                                                                                      
/usr/share/vim/vim74/syntax/r.vim

**Comment by jalvesaq** [comment]
Probably these two files are older than the files released with Vim and should be deleted:
```
~/.vim/syntax/r.vim
~/.vim/indent/r.vim
```

**Comment by jalvesaq** [comment]
The proper way of uninstalling a Vimball is:
```
packadd vimball
RmVimball Vim-R-plugin
RmVimball Nvim-R
```

**Comment by kprimice** [comment]
vim-R-plugin was not properly uninstalled. So I uninstalled both Vim-R-plugin and Nvim-R properly, reinstalled Nvim-R, but I still get the same error message when I write the name a function. (And still don't have the highlighting)

**Comment by jalvesaq** [comment]
Did you try to manually delete those two files? The last Vimball of Vim-R-plugin did not have these two files, so they might be from even older installation and will not be recorded by Vimball.

**Comment by kprimice** [comment]
Yes I did. I also removed them from /usr/share/vim/vim74

**Comment by jalvesaq** [comment]
You should not remove the files from /usr/share/vim/vim74 because they were the up-to-date ones. Now, you have to reinstall Vim.

**Comment by kprimice** [comment]
That's what I did, recompiled Vim from source: still the same problem

**Comment by jalvesaq** [comment]
What is the output of `:scriptnames` now?

**Comment by kprimice** [comment]
> /usr/share/vim/vimrc                                                                                                                                                                                                                      
~/.vimrc                                                                                                                                                                                                                                  
/usr/share/vim/vim74/filetype.vim                                                                                                                                                                                                         
~/.vim/ftdetect/r.vim                                                                                                                                                                                                    
/usr/share/vim/vim74/ftplugin.vim                                                                                                                                                                                                         
/usr/share/vim/vim74/indent.vim                                                                                                                                                                                                           
/usr/share/vim/vim74/syntax/syntax.vim                                                                                                                                                                                                    
/usr/share/vim/vim74/syntax/synload.vim                                                                                                                                                                                                   
/usr/share/vim/vim74/syntax/syncolor.vim                                                                                                                                                                                                  
/usr/share/vim/vim74/colors/darkblue.vim                                                                                                                                                                                                  
~/.vim/plugin/screen.vim                                                                                                                                                                                                 
/usr/share/vim/vim74/plugin/getscriptPlugin.vim                                                                                                                                                                                           
/usr/share/vim/vim74/plugin/gzip.vim                                                                                                                                                                                                      
/usr/share/vim/vim74/plugin/matchparen.vim                                                                                                                                                                                                
/usr/share/vim/vim74/plugin/netrwPlugin.vim                                                                                                                                                                                               
/usr/share/vim/vim74/plugin/rrhelper.vim                                                                                                                                                                                                  
/usr/share/vim/vim74/plugin/spellfile.vim                                                                                                                                                                                                 
/usr/share/vim/vim74/plugin/tarPlugin.vim                                                                                                                                                                                                 
/usr/share/vim/vim74/plugin/tohtml.vim                                                                                                                                                                                                    
/usr/share/vim/vim74/plugin/vimballPlugin.vim                                                                                                                                                                                             
/usr/share/vim/vim74/plugin/zipPlugin.vim                                                                                                                                                                                                 
~/.vim/ftplugin/r_nvimr.vim                                                                                                                                                                                              
~/.vim/R/common_global.vim                                                                                                                                                                                               
~/.vim/R/setcompldir.vim                                                                                                                                                                                                 
~/.vim/R/vimrcom.vim                                                                                                                                                                                                     
~/.vim/R/tmux.vim                                                                                                                                                                                                        
~/.vim/R/tmux_split.vim                                                                                                                                                                                                  
~/.vim/R/common_buffer.vim                                                                                                                                                                                               
/usr/share/vim/vim74/ftplugin/r.vim

**Comment by jalvesaq** [comment]
syntax/r.vim is not listed. If you are installing from source, Vim is should be in /usr/local/, and not in /usr.

**Comment by kprimice** [comment]
Apparently it didn't like being installed in /usr/share, I reinstalled vim with the default path and now everything works.
Thank you for your help!
