### ISSUE TITLE
The package nvimcom wasn't loaded yet

### ISSUE THREAD

**Issue by DadongZ** [jalvesaq/Nvim-R#94]
I found this issue and followed the instruction from `:h nvimcom-not-loaded`, but the issue is always there and I can't even start R.
Although I prefer the vim-R-plugin, I was trying to switch to Nvim-R, so far is very frustrated.
I still wanted to thank you for the plugin, maybe my case is single.

**Comment by jalvesaq** [comment]
You could try with zero configuration and, if it works, add your configuration piece by piece to `~/.config/init.vim` and `~/.Rprofile`. If you want to try this, you could do the following:
```
cd /tmp
wget https://github.com/jalvesaq/Nvim-R/releases/download/v0.9.6/Nvim-R_0.9.6.zip
cd ~/.config
mv nvim backup_nvim
cd ~/
mv .Rprofile backup_Rprofile
mkdir -p ~/.local/share/nvim/site/pack/R
cd ~/.local/share/nvim/site/pack/R
unzip /tmp/Nvim-R_0.9.6.zip
```

**Comment by jalvesaq** [comment]
Remember that the LocalLeader is `\` by default. So, you have to type `\rf` to start R.

**Comment by jalvesaq** [comment]
This is a TCP problem (`bind()` is failing), but it has never happened in my systems (Linux and Windows). I have found some examples of how to create a TCP server in C, and I manage to successfully create one for nvimcom, but I don't understand enough of client/server to know what might be causing the problem. As far as I know, all ports from 10001 to 10049 are in use, but I think this is unlikely to be true. So, unfortunately, I don't know how to fix it.

**Comment by jalvesaq** [comment]
No, nvimcom does not use X11 server.

Note that both Vim and R must be running in the same machine which can be the remote one.

**Comment by jalvesaq** [comment]
Perhaps there is a firewall blocking even local connections to ports 10000 and 101001 which are the first port numbers tried by nvimcom and Nvim-R respectively.

**Comment by kmakat** [comment]
Hi, I just also ran into the same error message. In my case this was caused by a hidden .RData file that was created by a previous session on a different machine (both Macs with 10.11.6). Deleting it resolved the issue. No idea why. Maybe it helps.

**Comment by jalvesaq** [comment]
The plugin waits nvimcom for only 5 seconds. I will see if I can put the waiting code in an asynchronous job.

**Comment by DadongZ** [comment]
Where is the hidden .RData you found that may have led to the nvimcom
issue? Maybe I can check whether it works for me.

**Comment by DadongZ** [comment]
I tried using 20 seconds, but the problem was still there. I thought
something else went wrong.

**Comment by kmakat** [comment]
I was in the R working directory. Maybe you’re having a different issue.

**Comment by DadongZ** [comment]
I did see a hidden .RData in the home directory and deleted it. but the
"The package nvimcom wasn't loaded yet." is still there. It seems different
from yours. Thanks though.

**Comment by DadongZ** [comment]
Interestingly, I fixed all issues by reinstall both Vim-R-Plugin and Vimcom
back to 2/1/2014. Just FYI.

**Comment by dlithio** [comment]
In case this helps, I was having the same error for a while. I would always get
```
"Job" exited with status 1
The package nvimcom wasn't loaded yet. Please, see  :h nvimcom-not-loaded
```
while trying to run Nvim-R through putty on a remote linux machine. I knew R was starting and loading the package (I was saving to a file in my .Rprofile to verify), but it just wouldn't work.

After reading through the threads in the [Github Issues](https://github.com/jalvesaq/Nvim-R/issues) and all of the different `let ...` options you can set in the [Vim docs](https://github.com/jalvesaq/Nvim-R/blob/master/doc/Nvim-R.txt), I was able to fix the error by adding these lines to `~/.vimrc`  
```
let R_in_buffer = 0
let R_applescript = 0
let R_tmux_split = 1
```
and then starting tmux before vim
```
tmux
vim test.R
```
Then, all I had to do was type `\rf` as the docs instructed and I got the R window as a tmux pane.  I made a line that was simply `1+1` in the file I had created. I could then execute that line in R by typing `\l` (in vim's normal mode, not insert mode).

Thanks for the wonderful program, @jalvesaq!

**Comment by jalvesaq** [comment]
@DadongZ Nvim-R now waits asynchronously for nvimcom. Although I think this change will not fix the bug that you report, you could update Nvim-R and see what happens.

**Comment by kmakat** [comment]
Thank you for your work, Jakson!

**Comment by DadongZ** [comment]
Thanks, @jalvesaq! I will try it

**Comment by chaselweng** [comment]
I have a similar issue while using macvim. After installing, I can start R from macvim but it shows the package vimcom wasn't loaded yet. The interesting thing is that I can still send my file to R for execution. It seems that data communications between macvim and R is successful. It is just not clear to me why this warning appears.

**Comment by DadongZ** [comment]
The issue was fixed after reinstall the Nvim-R but I am not sure the exactly point on how the issues has been fixed. Recent changes at my end include server upgrade and reboot and recompile vim.

**Comment by jalvesaq** [comment]
Thanks for the feedback!

**Comment by etheleon** [comment]
@dlithio advise works!

**Comment by carljparker** [comment]
After upgrading R from `v3.2.3` (Wooden Christmas Tree) to `v3.4.1` (Single Candle), I started having the issue where the `nvimcom` package would not load.

I resolved the issue by re-installing `nvimcom` from the local source directory. Here are the commands that I used.

    pushd  ~/.vim/R
    Rscript -e 'install.packages( "./nvimcom", repos = NULL, type = "source" )'
