### ISSUE TITLE
How to turn off the underscore being replaced by `->`

### ISSUE THREAD

**Issue by gdoteof** [jalvesaq/Nvim-R#95]
In the old plugin it appears to have been set with `vimrplugin_assign`

But this doesn't work.

This feature drives me insane

**Comment by jalvesaq** [comment]
For most options, just replace `vimrplugin_` with `R_`. Please, look at the documentation. You don't need to read it thoroughly. Just search for the string "assign" or "underscore".

**Comment by izaakm** [comment]
FYI for anyone else that finds this page ...

```
While editing R code, `_` is replaced with `<-`.
...
To completely disable this feature, put in your |vimrc|:
>
   let R_assign = 0
```

**Comment by stevecondylios** [comment]
I'm a newbie to nvim-r but loving it.

I think `_` is used so often in R, that overriding by default it is possibly not a good default setting. @izaakm 's solution solved for me. But I wonder if it should be removed from default behaviour so `_` works as expected (for context, until I found this issue, I was temporarily placing hyphens where underscores should be, then going back and replacing them). I think this might be the only 'gotcha' for newbies, so could be worth considering altering.

**Comment by jalvesaq** [comment]
Nvim-R is frozen. So, it is better to avoid changing default behaviors. The default key binding for writing the assignment operator in [R.nvim](https://github.com/R-nvim/R.nvim) is `Alt+-`.

**Comment by stevecondylios** [comment]
It was hard for me to see the reason for it, but now I understand the reason for it: 

> And in case you don't know your history, `_` used to be the assignment operator in S (and then R). So `x_5` was like `x<-5`, and so emacs' ESS and Vim's R plugin implement this replacement to help us old timers and annoy the hadley_fan_bois :)

That's very interesting, I had no idea.

Source [here](https://stackoverflow.com/questions/22380926/vim-underscore-automatically-converted-to/78085403#comment34025638_22381129).
