### ISSUE TITLE
Failed to install vimcom

### ISSUE THREAD

**Issue by vando026** [jalvesaq/Nvim-R#96]
Hi, I have previously used vim-r-plugin and decided to switch to nvim-r. But the nvim-r plugin fails to install. I have attached the error message below.

My vim version is 7.4.2198 on a Windows 10. I installed Rtools into my c:/Rtools/ folder.

I installed the nvim-r files using Vundle so that C:\users\alain\vimfiles\bundle\nvim-r.

Do you think the problem is that the gcc compiler is not finding the correct paths for the files?

************************* Error log

.Rprofile successfully read
* installing to library 'C:/Users/alain/R/win-library/3.3'
* installing *source* package 'nvimcom' ...
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-33~1.1/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"  -D`C:/PROGRA~1/R/R-33~1.1/bin/R --slave -e 'cat(Sys.info()[[1]])'` -DLWS_NO_FORK  -DWIN32   -O3 -Wall  -std=gnu99 -mtune=core2 -c nvimcom.c -o nvimcom.o
gcc.exe: error: successfully: No such file or directory
gcc.exe: error: read: No such file or directory
gcc.exe: error: Windows: No such file or directory
make: *** [nvimcom.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-33~1.1/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-33~1.1/share/make/winshlib.mk" SHLIB="nvimcom.dll" OBJECTS="nvimcom.o"' had status 2
ERROR: compilation failed for package 'nvimcom'
* removing 'C:/Users/alain/R/win-library/3.3/nvimcom'

**Comment by jalvesaq** [comment]
It looks like "successfully read" and "Windows" are part of messages that gcc is mistakenly taking for files. I don't know what might be causing the problem.

**Comment by vando026** [comment]
Hi Jakson, your response pointed me to the solution. 

In my .Rprofile file I have a line 

cat('.Rprofile successfully read\n')

to let me know that my Rprofile was successfully read everytime I start R. Seems like gcc was incorrectly using this output to compile the files. 

I suspect the lesson of this issue is not to put cat or print statements in your .Rprofile if you intend to load nvimcom.

Thanks again for all your effort in developing and making available your excellent vim-r packages.

Alain
