### ISSUE TITLE
maplocalleader in sample vimrc issue

### ISSUE THREAD

**Issue by zedoul** [jalvesaq/Nvim-R#98]
Hi!

Thank you for your great package :) I use this package everyday.

Let me report one issue.

You set maplocalleader as "," in your sample vimrc in README.md. This changes the local leader so we should use ",rf" instead of "\rf" to start R in vim. 

The thing is that because of this sample vimrc, someone may be confused, especially who started to use your package, so that hard to start to use this package. A starter may read a [document](https://raw.githubusercontent.com/jalvesaq/Nvim-R/master/doc/Nvim-R.txt), and the document says the <LocalLeader> is "\" by default, not ",".

I think we can fix the vimrc example in README.md. 

Best regards,
Kim

**Comment by jalvesaq** [comment]
Thanks for reporting the inconsistency. The main reason to put a sample vimrc in the README was because `syntax`, `filetype plugin` and `filetype indent` were not enabled by default. But now they are.
